/**
 * SF-A02-T40: Roslyn differential test.
 *
 *   node --test packages/compiler/test/differential/run.test.js       run against the checked-in baseline
 *   node packages/compiler/test/differential/run.test.js --update-baseline   regenerate baseline/*.json
 *   node packages/compiler/test/differential/run.test.js --report [--verbose]  print the table (and failures) only
 *   SF_DIFFERENTIAL_UPDATE=1 npm test                                 same as --update-baseline under the test runner
 *
 * Every fixture runs on the bytecode back end, the image-derived CIL back end and the direct CIL pipeline
 * (`compileToAssembly`), and is compared with pinned results from real Roslyn
 * (pinned/*.json, regenerated by tools/pin.mjs). Because the compiler does not yet agree with Roslyn everywhere,
 * the assertion is against baseline/<feature>.json: a baseline entry that stops passing fails, and so does a fixture that
 * newly passes without being added to the baseline.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import {loadFixtures,loadPinned,loadBaseline,saveBaseline,fixtureHash} from './corpus-store.js';
import {report,formatReport,baselineOf,compareBaseline,runFixture,AXES,IMAGE_AXES} from './harness.js';

const UPDATE_COMMAND='node packages/compiler/test/differential/run.test.js --update-baseline';
const update=process.argv.includes('--update-baseline')||process.env.SF_DIFFERENTIAL_UPDATE==='1';
const reportOnly=process.argv.includes('--report'),verbose=process.argv.includes('--verbose');
const show=list=>list.map(e=>`  [${e.axis}] ${e.id}${e.detail?' - '+(typeof e.detail==='string'?e.detail:JSON.stringify(e.detail)):''}`).join('\n');

if(update||reportOnly){
  const result=report();console.log(formatReport(result));
  if(verbose)for(const row of result.fixtures.filter(r=>!r.passed))console.log(`${row.id}: ${JSON.stringify(row.details)}`);
  if(update){saveBaseline(baselineOf(result));console.log(`\nbaseline updated: ${AXES.map(a=>`${a} ${baselineOf(result)[a].length}`).join(', ')}.`);}
}else{
  const fixtures=loadFixtures(),pinned=loadPinned();
  let result=null;const current=()=>result??=report({fixtures,pinned});

  test('A02-T40 corpus: every fixture has a current pinned Roslyn result of the declared kind',()=>{
    assert(fixtures.length>=120,`expected a substantial corpus, found ${fixtures.length}`);
    assert.match(String(pinned.meta?.version),/^\d+\.\d+/);
    const ids=new Set(fixtures.map(f=>f.id));
    for(const f of fixtures){
      const p=pinned.results.get(f.id);assert(p,`${f.id}: not pinned; run node packages/compiler/test/differential/tools/pin.mjs`);
      assert.equal(p.hash,fixtureHash(f),`${f.id}: fixture changed since it was pinned; run node packages/compiler/test/differential/tools/pin.mjs`);
      assert.equal(p.kind,f.kind);
      const errors=p.diagnostics.filter(d=>d[3]==='error').length,warnings=p.diagnostics.filter(d=>d[3]==='warning').length;
      if(f.kind==='output'){assert.equal(errors,0,f.id);assert.equal(typeof p.output,'string',f.id);assert(!p.output.includes('\r'),f.id);}
      else assert(errors+warnings>0,f.id);
      for(const d of p.diagnostics){assert.match(d[0],/^CS\d{4}$/);assert(Number.isInteger(d[1])&&Number.isInteger(d[2]));assert(['error','warning','info'].includes(d[3]));}
    }
    for(const id of pinned.results.keys())assert(ids.has(id),`${id}: pinned result without a fixture; run tools/pin.mjs`);
  });

  test('A02-T40 harness: runs every fixture on both back ends and reports per-feature pass rates',t=>{
    const r=current(),table=formatReport(r);t.diagnostic(table);console.log(table);
    assert.equal(r.fixtures.length,fixtures.length);
    const features=new Set(fixtures.map(f=>f.feature));assert.deepEqual(Object.keys(r.features).sort(),[...features].sort());
    for(const [name,f] of Object.entries(r.features)){
      const rows=r.fixtures.filter(x=>x.feature===name);
      assert.equal(f.total,rows.length);assert.equal(f.passed,rows.filter(x=>x.passed).length);
      assert.equal(f.outputTotal,rows.filter(x=>x.kind==='output').length);
      assert(f.bytecode<=f.outputTotal&&f.cil<=f.outputTotal&&f.diagnostics<=f.total&&f.passed<=f.total);
    }
    for(const row of r.fixtures){
      if(row.kind==='output'){for(const axis of ['bytecode','cil','directCil'])assert.equal(typeof row[axis],'boolean',`${row.id} ${axis}`);}
      else{for(const axis of ['bytecode','cil','directCil'])assert.equal(row[axis],null,`${row.id} ${axis}`);}
    }
  });

  test('A02-T40 harness: unsupported fixtures are never reported as passed',()=>{
    for(const row of current().fixtures)if(row.unsupported){assert.equal(row.passed,false,row.id);for(const axis of IMAGE_AXES)assert.notEqual(row[axis],true,`${row.id} ${axis}`);}
    const fixture=fixtures.find(f=>f.kind==='output'),pin=pinned.results.get(fixture.id);
    const crash=runFixture(fixture,pin,{compile(){throw new Error('boom');}});
    assert.equal(crash.unsupported,true);assert.equal(crash.passed,false);assert.match(crash.details.unsupported,/compiler crash: boom/);
    const profile=runFixture(fixture,pin,{compile:()=>({success:false,image:null,diagnostics:[{code:'SF2099',start:0,length:1,severity:'error'}]})});
    assert.equal(profile.unsupported,true);assert.deepEqual(IMAGE_AXES.map(a=>profile[a]),[false,false,false,false]);
    const stale=runFixture({...fixture,source:fixture.source+'// edited\n'},pin);
    assert.equal(stale.unsupported,true);assert.match(stale.details.unsupported,/stale/);
    assert.equal(runFixture(fixture,undefined).passed,false);
  });

  test('A02-T40 harness: a wrong span, a missing diagnostic or wrong output fails the matching axis',()=>{
    const d=fixtures.find(f=>f.kind==='diagnostics'&&pinned.results.get(f.id).diagnostics.every(x=>x[3]==='error')),pin=pinned.results.get(d.id);
    const exact=()=>({success:false,image:null,diagnostics:pin.diagnostics.map(([code,start,length,severity])=>({code,start,length,severity}))});
    assert.equal(runFixture(d,pin,{compile:exact}).passed,true);
    const repeated=()=>{const r=exact();r.diagnostics.push({...r.diagnostics[0],message:'another field at the same span'});return r;};
    assert.equal(runFixture(d,pin,{compile:repeated}).passed,true,'capture compares distinct code/span/severity projections');
    const shifted=()=>{const r=exact();r.diagnostics[0].start++;return r;};
    assert.equal(runFixture(d,pin,{compile:shifted}).diagnostics,false);
    assert.equal(runFixture(d,pin,{compile:()=>({success:true,image:null,diagnostics:[]})}).diagnostics,false);
    const extraWarning=()=>{const r=exact();r.diagnostics.push({code:'CS0168',start:0,length:1,severity:'warning'});return r;};
    const w=runFixture(d,pin,{compile:extraWarning});assert.equal(w.diagnostics,true);assert.equal(w.warnings,false);assert.equal(w.passed,false);
    const o=fixtures.find(f=>f.kind==='output'),opin=pinned.results.get(o.id);
    const wrong=runFixture(o,{...opin,output:opin.output+'extra\n'});
    assert.equal(wrong.bytecode,false);assert.equal(wrong.cil,false);assert.equal(wrong.directCil,false);assert.equal(wrong.passed,false);
  });

  test('A02-T40 baseline: no fixture regressed and every newly passing fixture is recorded',()=>{
    const {regressions,improvements,stale}=compareBaseline(current(),loadBaseline());
    assert.equal(regressions.length,0,`${regressions.length} fixture(s) in the baseline no longer match Roslyn:\n${show(regressions)}\nFix the compiler, or if the change is intended regenerate the baseline with:\n  ${UPDATE_COMMAND}`);
    assert.equal(stale.length,0,`the baseline lists ${stale.length} unknown fixture(s):\n${show(stale)}\nRegenerate it with:\n  ${UPDATE_COMMAND}`);
    assert.equal(improvements.length,0,`${improvements.length} fixture(s) newly match Roslyn but are not in the baseline:\n${show(improvements)}\nAdd them by running:\n  ${UPDATE_COMMAND}`);
  });
}
