export { validateIdentifier, validateProjectName, validateNamespace, defaultNamespace, TemplateError } from './common.js';
export { projectTemplates, itemTemplates, builtInTemplates, TemplateCatalog, getTemplate, searchTemplates, templateAvailability } from './registry.js';
export { templateOptions, normalizeTemplateOptions } from './options.js';
export { validateFilePlan } from './file-plan.js';
export { createItemPlan } from './item-plan.js';
export { createProjectPlan } from './project-plan.js';
export { mergeResourceDictionary } from './item/winui-controls.js';
export { parseTemplateConfig, evaluateTemplateSymbols } from './engine/template-config.js';
export { evaluateTemplateExpression } from './engine/expression.js';
export { applyValueForm } from './engine/value-forms.js';
export { instantiateTemplate, templatePostActions } from './engine/instantiate.js';
export { installTemplatePackage, uninstallTemplatePackage } from './engine/packages.js';
export { validateTemplateQualifications } from './qualification.js';
