import {xmlEscape,addSolutionProject,addSolutionFolder,editProjectMembership,relativeTo,parseXml} from '@sharpforge/project-system';
import {portablePath} from '@sharpforge/archive';
const join=(...parts)=>parts.filter(Boolean).join('/'),dir=p=>p.includes('/')?p.slice(0,p.lastIndexOf('/')):'',leaf=p=>p.split('/').at(-1);
const words=new Set('abstract as base bool break byte case catch char checked class const continue decimal default delegate do double else enum event explicit extern false finally fixed float for foreach goto if implicit in int interface internal is lock long namespace new null object operator out override params private protected public readonly ref return sbyte sealed short sizeof stackalloc static string struct switch this throw true try typeof uint ulong unchecked unsafe ushort using virtual void volatile while async await var dynamic record required file global'.split(' '));
export function validateIdentifier(value,label='Name'){if(typeof value!=='string'||value.length>100||!/^[_A-Za-z][_A-Za-z0-9]*$/.test(value)||words.has(value))throw new Error(label+' must be a C# identifier (not a keyword), at most 100 characters');return value;}
export function validateProjectName(value){if(typeof value!=='string'||!value||value.length>100||!/^[_A-Za-z][_A-Za-z0-9.-]*$/.test(value))throw new Error('Project name must start with a letter or underscore and contain only letters, digits, dots, hyphens or underscores');portablePath(value);return value;}
export function validateNamespace(value){if(typeof value!=='string'||value.length>200||!value)throw new Error('Enter a namespace');for(const part of value.split('.'))validateIdentifier(part,'Namespace component');return value;}
export const defaultNamespace=name=>name.split(/[.-]/).filter(Boolean).map(p=>{p=p.replace(/[^\w]/g,'_');return words.has(p)||/^\d/.test(p)?'_'+p:p;}).join('.');
function definition(id,name,description,category,extra={}){return Object.freeze({id,name,description,category,language:'C#',platform:'SharpForge browser',...extra});}
export const projectTemplates=Object.freeze([
 definition('console','Console App','An explicit Main entry point with console output and a portable SDK project.','Console',{icon:'>_',nativeCompatible:true}),
 definition('console-async','Console App (async)','An async Task Main entry point and managed Task.Delay example.','Console',{icon:'>_',nativeCompatible:true}),
 definition('class-library','Class Library','A reusable public C# class library with no entry point.','Library',{icon:'◇',nativeCompatible:true}),
 definition('empty-project','Empty C# Project','A library project with no source files; add items as needed.','Library',{icon:'◇',nativeCompatible:true}),
 definition('winui-blank','WinUI App (code-first web)','A managed window, reusable page component and working counter event. HTML controls with graphics fallbacks.','WinUI',{icon:'▣',winui:true}),
 definition('winui-navigation','WinUI Navigation App','Home and Settings page components with managed navigation buttons, no XAML.','WinUI',{icon:'▣',winui:true}),
 definition('winui-controls-library','WinUI Control Library','A reusable code-first UserControl component exposed through its View property.','WinUI',{icon:'◈',winui:true}),
 definition('test-console','Self-test Console','Package-free assertions and process failure on an incorrect result. Not an xUnit/MSTest runner.','Tests',{icon:'✓',nativeCompatible:true}),
 definition('blank-solution','Blank Solution','An empty .slnx solution with solution folders; add existing or new projects.','Solution',{icon:'◇',kind:'solution'}),
 definition('console-library-solution','Console + Library Solution','Two separate SDK projects and a ProjectReference, with the console selected as startup.','Solution',{icon:'◇',kind:'solution',nativeCompatible:true}),
 definition('winui-library-solution','WinUI App + Control Library','A code-first WinUI app consuming a component from a second project.','Solution',{icon:'◇',kind:'solution',winui:true})
]);
export const itemTemplates=Object.freeze([
 definition('class','Class','A public class with an editable property.','Code',{fileName:'Class1.cs'}),
 definition('partial-class','Partial Class','A partial class split into two source files.','Code',{fileName:'Component1.cs'}),
 definition('static-class','Static Class','A static utility class with a callable method.','Code',{fileName:'Utilities.cs'}),
 definition('disposable-class','Disposable Class','A concrete IDisposable implementation compatible with using cleanup.','Code',{fileName:'ResourceLease.cs'}),
 definition('view-model','View Model','A plain model with auto-properties; no unsupported binding/notification behavior is implied.','WinUI',{fileName:'MainViewModel.cs'}),
 definition('winui-page','WinUI Page','A code-first page component with a View property and a title.','WinUI',{fileName:'BlankPage.cs',winui:true}),
 definition('winui-counter-page','WinUI Counter Page','A stateful Page component with a live managed Click handler.','WinUI',{fileName:'CounterPage.cs',winui:true}),
 definition('winui-grid-page','WinUI Grid Page','A Page with Grid row/column definitions and attached layout properties.','WinUI',{fileName:'GridPage.cs',winui:true}),
 definition('winui-settings-page','WinUI Settings Page','A Page with native text, checkbox and managed apply action.','WinUI',{fileName:'SettingsPage.cs',winui:true}),
 definition('winui-user-control','WinUI User Control','A reusable UserControl component with a View property and a mutable caption.','WinUI',{fileName:'CardControl.cs',winui:true}),
 definition('winui-custom-control','WinUI Composite Control','A reusable Border-based control. Composition, not native templated Control inheritance.','WinUI',{fileName:'StatusControl.cs',winui:true}),
 definition('winui-window','WinUI Window','A reusable managed Window component with an Activate method.','WinUI',{fileName:'ToolWindow.cs',winui:true}),
 definition('winui-flyout','WinUI Menu Flyout','A MenuFlyout with a managed MenuFlyoutItem handler.','WinUI',{fileName:'ActionsFlyout.cs',winui:true}),
 definition('winui-resources','WinUI Brush Factory','A code-first SolidColorBrush factory. No XAML ResourceDictionary loader required.','WinUI',{fileName:'AppBrushes.cs',winui:true}),
 definition('text','Text File','An empty UTF-8 text document.','General',{fileName:'Notes.txt',language:'Text'}),
 definition('json','JSON File','An editable data-only JSON document.','General',{fileName:'settings.json',language:'JSON'}),
 definition('editorconfig','EditorConfig','Portable C# whitespace conventions.','Configuration',{fileName:'.editorconfig',language:'Text'}),
 definition('build-props','Directory.Build.props','Shared SDK properties inherited by child projects.','Configuration',{fileName:'Directory.Build.props',language:'XML'}),
 definition('build-targets','Directory.Build.targets','A source-preserving empty MSBuild import ready for authoring.','Configuration',{fileName:'Directory.Build.targets',language:'XML'})
]);
const X='using Microsoft.UI.Xaml;\nusing Microsoft.UI.Xaml.Controls;\nusing Microsoft.UI.Xaml.Media;\nusing Microsoft.UI;\n';
const wrap=(ns,body,usings='')=>usings+(usings?'\n':'')+'namespace '+ns+'\n{\n'+body.split('\n').map(line=>line?'    '+line:'').join('\n')+'\n}\n';
const componentNote='// Code-first SharpForge component: use .View. User inheritance from WinUI classes\n// and XAML/ControlTemplate/DataTemplate loading are not part of this profile.\n';
function component(name,view,body,extra='',usings=X){return {body:`${componentNote}public partial class ${name}\n{\n    public ${view} View { get; private set; }\n${extra}\n    public ${name}()\n    {\n        View = new ${view}();\n${body}\n    }\n}`,usings};}
function itemCode(id,n){
 switch(id){
 case 'class':return {body:`public class ${n}\n{\n    public int Value { get; set; }\n}`};
 case 'partial-class':return {body:`public partial class ${n}\n{\n    public int Value { get; set; }\n}`,second:`public partial class ${n}\n{\n    public int GetValue()\n    {\n        return Value;\n    }\n}`};
 case 'static-class':return {body:`public static class ${n}\n{\n    public static int Add(int left, int right)\n    {\n        return left + right;\n    }\n}`};
 case 'disposable-class':return {usings:'using System;\n',body:`public class ${n} : IDisposable\n{\n    public bool IsDisposed { get; private set; }\n    public void Dispose()\n    {\n        IsDisposed = true;\n    }\n}`};
 case 'view-model':return {body:`public class ${n}\n{\n    public string Title { get; set; } = "New view";\n    public int Count { get; set; }\n}`};
 case 'winui-page':return component(n,'Page',`        StackPanel panel = new StackPanel();\n        panel.Padding = new Thickness(24);\n        panel.Spacing = 16;\n        TextBlock title = new TextBlock();\n        title.Text = "${n}";\n        title.FontSize = 28;\n        panel.Children.Add(title);\n        View.Content = panel;`);
 case 'winui-counter-page':return component(n,'Page',`        StackPanel panel = new StackPanel();\n        panel.Padding = new Thickness(24);\n        panel.Spacing = 16;\n        TextBlock title = new TextBlock();\n        title.Text = "Welcome to your WinUI app";\n        title.FontSize = 28;\n        display = new TextBlock();\n        display.Name = "CounterDisplay";\n        display.Text = "Count: 0";\n        display.FontSize = 36;\n        Button button = new Button();\n        button.Content = "Increment";\n        button.Click += Increment;\n        panel.Children.Add(title);\n        panel.Children.Add(display);\n        panel.Children.Add(button);\n        View.Content = panel;`,`    private TextBlock display;\n    private int count;\n    private void Increment(object sender, RoutedEventArgs args)\n    {\n        count++;\n        display.Text = "Count: " + count;\n    }\n`);
 case 'winui-grid-page':return component(n,'Page',`        Grid grid = new Grid();\n        grid.RowSpacing = 12;\n        grid.ColumnSpacing = 12;\n        RowDefinition header = new RowDefinition();\n        header.Height = GridLength.Auto;\n        grid.RowDefinitions.Add(header);\n        grid.RowDefinitions.Add(new RowDefinition());\n        grid.ColumnDefinitions.Add(new ColumnDefinition());\n        grid.ColumnDefinitions.Add(new ColumnDefinition());\n        TextBlock title = new TextBlock();\n        title.Text = "${n}";\n        title.FontSize = 28;\n        Grid.SetColumnSpan(title, 2);\n        grid.Children.Add(title);\n        Button content = new Button();\n        content.Content = "Content";\n        Grid.SetRow(content, 1);\n        Grid.SetColumn(content, 1);\n        grid.Children.Add(content);\n        View.Content = grid;`);
 case 'winui-settings-page':return component(n,'Page',`        StackPanel panel = new StackPanel();\n        panel.Padding = new Thickness(24);\n        panel.Spacing = 12;\n        TextBlock title = new TextBlock();\n        title.Text = "Settings";\n        title.FontSize = 28;\n        input = new TextBox();\n        input.PlaceholderText = "Display name";\n        enabled = new CheckBox();\n        enabled.Content = "Enable feature";\n        result = new TextBlock();\n        Button apply = new Button();\n        apply.Content = "Apply settings";\n        apply.Click += Apply;\n        panel.Children.Add(title);\n        panel.Children.Add(input);\n        panel.Children.Add(enabled);\n        panel.Children.Add(apply);\n        panel.Children.Add(result);\n        View.Content = panel;`,`    private TextBox input;\n    private CheckBox enabled;\n    private TextBlock result;\n    private void Apply(object sender, RoutedEventArgs args)\n    {\n        result.Text = "Saved: " + input.Text;\n    }\n`);
 case 'winui-user-control':return component(n,'UserControl',`        Border border = new Border();\n        border.Padding = new Thickness(16);\n        border.CornerRadius = new CornerRadius(8);\n        border.Background = new SolidColorBrush(Colors.DodgerBlue);\n        caption = new TextBlock();\n        caption.Text = "Reusable control";\n        caption.Foreground = new SolidColorBrush(Colors.White);\n        border.Child = caption;\n        View.Content = border;`,`    private TextBlock caption;\n    public void SetCaption(string value)\n    {\n        caption.Text = value;\n    }\n`);
 case 'winui-custom-control':return component(n,'Border',`        View.Padding = new Thickness(16);\n        View.CornerRadius = new CornerRadius(6);\n        View.Background = new SolidColorBrush(Colors.DodgerBlue);\n        TextBlock label = new TextBlock();\n        label.Text = "Ready";\n        label.Foreground = new SolidColorBrush(Colors.White);\n        View.Child = label;`);
 case 'winui-window':return component(n,'Window',`        View.Title = "${n}";\n        View.Content = new TextBlock() { Text = "Tool window", FontSize = 24 };`,`    public void Activate()\n    {\n        View.Activate();\n    }\n`);
 case 'winui-flyout':return component(n,'MenuFlyout',`        MenuFlyoutItem action = new MenuFlyoutItem();\n        action.Text = "Run action";\n        action.Click += Run;\n        View.Items.Add(action);`,`    private void Run(object sender, RoutedEventArgs args)\n    {\n        Console.WriteLine("Action selected");\n    }\n`,X+'using System;\n');
 case 'winui-resources':return {usings:X,body:`public static class ${n}\n{\n    public static SolidColorBrush Accent()\n    {\n        return new SolidColorBrush(Colors.DodgerBlue);\n    }\n}`};
 default:throw new Error('Unknown code item template '+id);
 }
}
function projectXml({name,ns,framework='net10.0',library=false,checked=false,winui=false}){
 if(!['net8.0','net9.0','net10.0','netstandard2.0'].includes(framework)||framework==='netstandard2.0'&&!library)throw new Error('This target framework is not supported by the selected project kind');
 return `<Project Sdk="Microsoft.NET.Sdk">\n  <PropertyGroup>\n    <OutputType>${library?'Library':'Exe'}</OutputType>\n    <TargetFramework>${framework}</TargetFramework>\n    <AssemblyName>${xmlEscape(name)}</AssemblyName>\n    <RootNamespace>${xmlEscape(ns)}</RootNamespace>\n    <ImplicitUsings>disable</ImplicitUsings>\n    <Nullable>disable</Nullable>\n    <DebugType>portable</DebugType>\n    <CheckForOverflowUnderflow>${!!checked}</CheckForOverflowUnderflow>\n${winui?'    <SharpForgeUIProfile>WinUIWeb</SharpForgeUIProfile>\n':''}  </PropertyGroup>\n</Project>\n`;
}
export function validateFilePlan(plan,existing=[]){
 const all=[...existing.map(f=>typeof f==='string'?{path:f}:f),...plan.records,...(plan.folders??[]).map(path=>({path,directory:true}))],seen=new Map(),identities=new Map();
 for(const f of all){const path=portablePath(f.path),key=path.normalize('NFC').toLowerCase();let parent=path;while(parent){const pk=parent.normalize('NFC').toLowerCase(),old=identities.get(pk);if(old&&old!==parent)throw new Error('Case-colliding destination parent: '+parent);identities.set(pk,parent);parent=dir(parent);}if(seen.has(key)){if(f.directory&&seen.get(key).directory)continue;throw new Error('Destination already exists or collides by case: '+path);}seen.set(key,f);}
 for(const [key,f]of seen){let p=dir(key);while(p){if(seen.has(p)&&!seen.get(p).directory)throw new Error('Destination parent is a file: '+f.path);p=dir(p);}}
 return plan;
}
export function createItemPlan(templateId,{name,namespace='Application',folder='',projectPath=null,projectText=null,existing=[]}={}){
 const template=itemTemplates.find(t=>t.id===templateId);if(!template)throw new Error('Unknown item template');name??=template.fileName;if(folder)portablePath(folder);portablePath(name);if(name.includes('/'))throw new Error('Use Location for folders, not the item name');
 const records=[];if(template.language==='C#'){if(!/\.cs$/i.test(name))name+='.cs';const id=validateIdentifier(name.replace(/\.cs$/i,''),'Class name');validateNamespace(namespace);const source=itemCode(templateId,id);records.push({path:join(folder,name),text:wrap(namespace,source.body,source.usings)});if(source.second)records.push({path:join(folder,id+'.Methods.cs'),text:wrap(namespace,source.second,source.usings)});}
 else{const text=templateId==='json'?'{}\n':templateId==='editorconfig'?'root = true\n\n[*]\ncharset = utf-8\nend_of_line = lf\ninsert_final_newline = true\n\n[*.cs]\nindent_style = space\nindent_size = 4\n':templateId==='build-props'?'<Project>\n  <PropertyGroup>\n    <DebugType>portable</DebugType>\n  </PropertyGroup>\n</Project>\n':templateId==='build-targets'?'<Project>\n  <!-- Add native MSBuild targets explicitly. Loading does not execute tasks. -->\n</Project>\n':'';records.push({path:join(folder,name),text});}
 const plan={template:templateId,records,folders:[],openFile:records[0].path,modifications:[],warnings:template.winui?['Code-first composition using .View; native WinUI inheritance and XAML templates are not implied.']:[]};
 if(projectPath&&projectText!==null){let text=projectText;for(const record of records)text=editProjectMembership(text,{projectPath,path:record.path,itemType:/\.cs$/i.test(record.path)?'Compile':'None'});plan.modifications.push({path:projectPath,text,expectedText:projectText});}
 return validateFilePlan(plan,existing);
}
function emitProject(id,o){
 const {name,ns,folder}=o,records=[],library=['class-library','empty-project','winui-controls-library'].includes(id),winui=id.startsWith('winui'),put=(path,text)=>records.push({path:join(folder,path),text});
 put(name+'.csproj',projectXml({...o,library,winui}));
 const item=(template,className,sub='')=>{const p=createItemPlan(template,{name:className+'.cs',namespace:ns,folder:join(folder,sub)});records.push(...p.records);};
 let openFile;
 if(id==='console'||id==='console-async'||id==='test-console'){
  const body=id==='console-async'?'    public static async Task Main()\n    {\n        await Task.Delay(1);\n        Console.WriteLine("Hello, async world!");\n    }':id==='test-console'?'    public static void Main()\n    {\n        int actual = Add(20, 22);\n        if (actual != 42)\n            throw new Exception("Expected 42");\n        Console.WriteLine("All self-tests passed.");\n    }\n\n    private static int Add(int a, int b)\n    {\n        return a + b;\n    }':'    public static void Main()\n    {\n        Console.WriteLine("Hello, world!");\n    }';put('Program.cs',wrap(ns,'public class Program\n{\n'+body+'\n}','using System;\n'+(id==='console-async'?'using System.Threading.Tasks;\n':'')));openFile=join(folder,'Program.cs');
 }else if(id==='class-library'){item('static-class','Calculator');openFile=join(folder,'Calculator.cs');}
 else if(id==='winui-controls-library'){item('winui-user-control','CardControl');openFile=join(folder,'CardControl.cs');}
 else if(winui){
  item(id==='winui-navigation'?'winui-page':'winui-counter-page','MainPage','Pages');
  if(id==='winui-navigation'){
   item('winui-settings-page','SettingsPage','Pages');
   put('Shell.cs',wrap(ns,`public class Shell\n{\n    public StackPanel View { get; private set; }\n    private ContentControl content;\n    private MainPage home = new MainPage();\n    private SettingsPage settings = new SettingsPage();\n    public Shell()\n    {\n        View = new StackPanel();\n        View.Spacing = 12;\n        StackPanel navigation = new StackPanel();\n        navigation.Orientation = Orientation.Horizontal;\n        navigation.Spacing = 8;\n        Button homeButton = new Button() { Content = "Home" };\n        homeButton.Click += ShowHome;\n        Button settingsButton = new Button() { Content = "Settings" };\n        settingsButton.Click += ShowSettings;\n        navigation.Children.Add(homeButton);\n        navigation.Children.Add(settingsButton);\n        content = new ContentControl();\n        content.Content = home.View;\n        View.Children.Add(navigation);\n        View.Children.Add(content);\n    }\n    private void ShowHome(object sender, RoutedEventArgs args)\n    {\n        content.Content = home.View;\n    }\n    private void ShowSettings(object sender, RoutedEventArgs args)\n    {\n        content.Content = settings.View;\n    }\n}`,X));
  }
  put('Program.cs',wrap(ns,`public class Program\n{\n    public static void Main()\n    {\n        Window window = new Window();\n        window.Title = "${name}";\n        ${id==='winui-navigation'?'Shell':'MainPage'} page = new ${id==='winui-navigation'?'Shell':'MainPage'}();\n        window.Content = page.View;\n        window.Activate();\n    }\n}`,X));openFile=join(folder,'Program.cs');
 }
 put('README.md',`# ${name}\n\n${winui?'Open this project in SharpForge and Run. This is a code-first WinUI **web profile**, not a Windows App SDK project. Components expose a real WinUI-shaped control through `.View`. Native WinUI base-class inheritance, XAML, dependency properties and control templates are not supplied by this template. No Windows App SDK NuGet dependency is implied.':'Open this SDK-style project in SharpForge, or use the installed .NET SDK for native builds. Browser builds use the supported C# subset and source-combined project references.'}\n\n${library?'This project is a library; add a project reference from an application.':'The entry point is `Program.Main`.'}\n`);
 return {records,folders:winui?[join(folder,'Assets')]:[],projectPath:join(folder,name+'.csproj'),openFile:openFile??join(folder,name+'.csproj'),library,winui};
}
/** Returns a complete create-only plan. Applying it is a separate, explicit filesystem/workspace operation. */
export function createProjectPlan(templateId,{projectName='Application',solutionName=projectName,namespace=defaultNamespace(projectName),location='',sameDirectory=false,solutionMode='new',solutionPath=null,solutionText=null,solutionFolder=null,framework='net10.0',checked=false,existing=[]}={}){
 const template=projectTemplates.find(t=>t.id===templateId);if(!template)throw new Error('Unknown project template');validateProjectName(projectName);validateProjectName(solutionName);validateNamespace(namespace);if(location)portablePath(location);if(!['new','existing','none'].includes(solutionMode))throw new Error('Unknown solution mode');if(solutionMode==='existing'&&(!solutionPath||typeof solutionText!=='string'))throw new Error('An existing .slnx solution is required');if(solutionPath&&!/\.slnx$/i.test(solutionPath))throw new Error('Convert a legacy .sln to .slnx before adding projects');
 let records=[],folders=[],projects=[],openFile=null,startup=null,modifications=[],entry=null;
 const emit=(id,name,ns,folder)=>{const p=emitProject(id,{name,ns,folder,framework,checked});records.push(...p.records);folders.push(...p.folders);projects.push(p.projectPath);openFile??=p.openFile;if(!p.library)startup??=p.projectPath;return p;};
 if(templateId==='blank-solution'){if(solutionMode==='existing')throw new Error('A blank solution cannot be added inside a solution');}
 else if(templateId==='console-library-solution'||templateId==='winui-library-solution'){
  const ui=templateId.startsWith('winui'),app=emit(ui?'winui-blank':'console',projectName,namespace,join(location,projectName)),libName=projectName+(ui?'.Controls':'.Core'),lib=emit(ui?'winui-controls-library':'class-library',libName,namespace+(ui?'.Controls':'.Core'),join(location,libName));
  const project=records.find(r=>r.path===app.projectPath);project.text=project.text.replace('</Project>',`  <ItemGroup>\n    <ProjectReference Include="${xmlEscape(relativeTo(lib.projectPath,dir(app.projectPath)))}" />\n  </ItemGroup>\n</Project>`);
  const program=records.find(r=>r.path===join(dir(app.projectPath),'Program.cs'));
  if(ui)program.text=wrap(namespace,`public class Program\n{\n    public static void Main()\n    {\n        Window window = new Window();\n        window.Title = "${projectName}";\n        CardControl card = new CardControl();\n        card.SetCaption("Control from the referenced library");\n        window.Content = card.View;\n        window.Activate();\n    }\n}`,X+`using ${namespace}.Controls;\n`);
  else program.text=wrap(namespace,'public class Program\n{\n    public static void Main()\n    {\n        Console.WriteLine(Calculator.Add(20, 22));\n    }\n}',`using System;\nusing ${namespace}.Core;\n`);
 }else emit(templateId,projectName,namespace,sameDirectory?location:join(location,projectName));
 if(solutionMode==='existing'){
  let text=solutionText;for(const projectPath of projects)text=addSolutionProject(text,{solutionPath,projectPath,folder:solutionFolder});modifications.push({path:solutionPath,text,expectedText:solutionText});entry=solutionPath;
 }else if(solutionMode==='new'||templateId==='blank-solution'){
  entry=join(location,solutionName+'.slnx');let text='<Solution>\n</Solution>\n';if(!projects.length)text=addSolutionFolder(text,'src');for(const projectPath of projects)text=addSolutionProject(text,{solutionPath:entry,projectPath,folder:projects.length>1?'src':null});records.push({path:entry,text});
 }else entry=projects[0]??null;
 return validateFilePlan({template:templateId,records,folders,projects,entry,startup:startup??projects[0]??null,openFile:openFile??entry,name:solutionName,profile:template.winui?'winui-web':'managed',modifications,warnings:template.winui?['WinUI web profile: native Windows App SDK/MSBuild execution is not provided by this template.','Pages and controls use composition through .View, not WinUI base-class inheritance.']:[]},existing);
}
export function searchTemplates({kind='project',query='',category='',language='',platform=''}={}){const list=kind==='item'?itemTemplates:projectTemplates,words=String(query).toLowerCase().trim().split(/\s+/).filter(Boolean);return list.filter(t=>(!category||t.category===category)&&(!language||t.language===language)&&(!platform||t.platform===platform)&&words.every(w=>[t.name,t.description,t.category,t.id].join(' ').toLowerCase().includes(w)));}
