export {renameSolutionFolder, removeSolutionFolder, moveSolutionProject, addSolutionItem} from './explorer.js';
export {parseConfigurationJson} from './configuration-json.js';
export {getCaseInsensitive} from './evaluation/errors.js';
export * from './tfm.js';
export * from './rid.js';
export * from './context-selection.js';
export {projectCompilationOptions} from './evaluation/compiler-options.js';
export * from './launch-settings.js';
export { expandExpression } from './evaluation/expander.js';
export { matchesGlob, WorkspacePathIndex } from './evaluation/path-index.js';
export * from './resources.js';
export { classifyTask, createTargetGraph } from './evaluation/targets.js';
