import {normalizePath,directoryName,baseName} from './paths.js';
import {relativeTo} from './explorer/solution-edits.js';
export * from './explorer/solution-edits.js';
/** Build a display hierarchy from project evaluation or native static inspection, never execute a project. */
export function buildSolutionTree({name='Workspace',files=[],snapshot=null,startup=null,showAll=false,view='solution',dirty=[],folders=[],generated=[],symbols=[]}={}){
 const map=new Map(files.map(f=>[f.path??f.uri,f])),dirtySet=new Set(dirty),projects=snapshot?.projects??[];
 const root={id:'solution:'+(snapshot?.solution?.path??name),kind:view==='folders'?'workspace':'solution',label:view==='folders'?name:`Solution '${snapshot?.solution?.name??name}' (${snapshot?projects.length:1} project${(snapshot?projects.length:1)===1?'':'s'})`,path:snapshot?.solution?.path??'',icon:'◇',branch:true,defaultExpanded:true,draggable:false,children:[]};
 const addFile=(parent,file,path,display=path,extra={})=>{
  const parts=display.split('/').filter(Boolean);let at=parent;
  for(let i=0;i<parts.length-1;i++){const segment=parts[i],prefix=parts.slice(0,i+1).join('/'),id=parent.id+':folder:'+prefix;let folder=at.children.find(n=>n.id===id);if(!folder){const real=extra.projectBase?normalizePath(prefix,extra.projectBase):prefix;folder={id,kind:'folder',label:segment,path:real,project:extra.project,branch:true,children:[],icon:'▰'};at.children.push(folder);}at=folder;}
  const kind=file.kind??(/\.(?:cs|vb|fs)$/i.test(path)?'source':/\.(?:dll|exe)$/i.test(path)?'assembly':/\.(?:csproj|fsproj|vbproj)$/i.test(path)?'project-file':'file');
  at.children.push({id:parent.id+':file:'+path,kind,label:parts.at(-1)??baseName(path),path,icon:kind==='source'?'C#':kind==='assembly'?'◇':'≡',dirty:dirtySet.has(path),searchText:path,description:path+(extra.linked?' (linked item)':''),...extra});
 };
 const symbolFiles=new Map();for(const symbol of symbols){if(!['class','method','field','property','enum'].includes(symbol.kind)||symbol.name?.startsWith('<')||!symbol.uri)continue;const list=symbolFiles.get(symbol.uri)??[];if(list.length<5000)list.push(symbol);symbolFiles.set(symbol.uri,list);}
 const attachSymbols=n=>{if(n.kind==='source'){const values=symbolFiles.get(n.path)??[],types=new Map();n.children??=[];for(const v of values.filter(v=>['class','enum'].includes(v.kind))){const item={id:n.id+':symbol:'+v.id,kind:'symbol',label:v.name,path:n.path,start:v.start,end:v.end,symbol:v,draggable:false,icon:'C',children:[]};types.set(v.name,item);n.children.push(item);}for(const v of values.filter(v=>!['class','enum'].includes(v.kind))){const parent=types.get(v.owner)??n;parent.children.push({id:n.id+':symbol:'+v.id,kind:'symbol',label:(v.name==='.ctor'?v.owner:v.name)+(v.kind==='method'?'('+(v.parameters??[]).map(p=>p.type).join(', ')+')':'')+(v.type?' : '+v.type:''),path:n.path,start:v.start,end:v.end,symbol:v,draggable:false,icon:v.kind==='method'?'◇':v.kind==='property'?'⚙':'▪'});}return;}n.children?.forEach(attachSymbols);};
 const sort=n=>{n.children?.sort((a,b)=>((a.kind==='dependencies'?0:a.kind==='folder'?1:2)-(b.kind==='dependencies'?0:b.kind==='folder'?1:2))||a.label.localeCompare(b.label,undefined,{numeric:true,sensitivity:'base'}));n.children?.forEach(sort);};
 if(view==='folders'||(!projects.length&&!snapshot)){const parent=view==='folders'?root:{id:'project:loose',kind:'project',label:name,path:'',icon:'C#',branch:true,defaultExpanded:true,startup:true,children:[]};if(parent!==root)root.children.push(parent);
  for(const [path,file]of map)addFile(parent,file,path);for(const path of folders){const marker={path:path+'/.sf-folder',kind:'folder-marker'};addFile(parent,marker,marker.path,marker.path);}
  const clean=n=>{n.children=n.children?.filter(c=>c.kind!=='folder-marker');n.children?.forEach(clean);};clean(root);attachSymbols(root);sort(root);return [root];}
 const solutionFolders=new Map();const solutionFolder=(path)=>{if(!path)return root;const parts=path.split('/').filter(Boolean);let parent=root,current='';for(const part of parts){current+='/'+part;let f=solutionFolders.get(current);if(!f){f={id:root.id+':slnfolder:'+current,kind:'solution-folder',label:part,solutionFolder:current+'/',branch:true,defaultExpanded:true,draggable:false,children:[],icon:'▰'};parent.children.push(f);solutionFolders.set(current,f);}parent=f;}return parent;};
 for(const path of snapshot.solution?.folders??[])solutionFolder(path);
 const owned=new Set();for(const project of projects){const base=directoryName(project.path),node={id:'project:'+project.path,kind:'project',label:project.name??baseName(project.path),path:project.path,project:project.path,projectBase:base,icon:'C#',branch:true,defaultExpanded:true,startup:project.path===startup,draggable:false,children:[]};
  solutionFolder(snapshot.solution?.items?.find(i=>i.kind==='project'&&i.path===project.path)?.folder).children.push(node);
  const dependencies={id:node.id+':dependencies',kind:'dependencies',label:'Dependencies',project:project.path,branch:true,draggable:false,icon:'▱',children:[]};
  for(const [label,kind,values]of [['Projects','project-reference',project.projectReferences??[]],['Packages','package',project.packageReferences??[]],['Assemblies','reference',project.references??[]],['Analyzers','analyzer',project.analyzers??[]]])if(values.length){const group={id:dependencies.id+':'+kind,kind:'dependency-group',label,project:project.path,branch:true,draggable:false,icon:'▱',children:values.map((v,i)=>({id:dependencies.id+':'+kind+':'+i,kind,label:kind==='project-reference'?baseName(v.path??String(v)):v.name??v.path??String(v),path:v.path,project:project.path,metadata:v,badge:v.version??'',icon:kind==='package'?'▣':'◇',draggable:false}))};dependencies.children.push(group);}
  if(project.targetFramework||project.targetFrameworks?.length)dependencies.children.push({id:dependencies.id+':framework',kind:'framework',label:project.targetFrameworks?.join(', ')||project.targetFramework,project:project.path,icon:'◇',draggable:false});
  node.children.push(dependencies);
  const compile=new Set((project.compile??[]).map(f=>f.path));for(const item of project.compile??[]){const file=map.get(item.path)??{path:item.path,kind:'source'},display=item.metadata?.Link??item.link??relativeTo(item.path,base);const outside=display.startsWith('../');addFile(node,file,item.path,outside?'Linked Files/'+baseName(item.path):display,{project:project.path,projectBase:base,included:true,itemType:'Compile',linked:!!item.metadata?.Link||!!item.link||outside,missing:!map.has(item.path),metadata:item.metadata});owned.add(item.path);}
  const explicitItems=new Set();for(const item of project.items??[]){if(item.itemType==='Folder'){addFile(node,{kind:'folder-marker'},item.path+'/.sf-folder',relativeTo(item.path,base)+'/.sf-folder',{project:project.path,projectBase:base});continue;}if(compile.has(item.path)||explicitItems.has(item.path))continue;explicitItems.add(item.path);const display=item.metadata?.Link??relativeTo(item.path,base),outside=display.startsWith('../');addFile(node,map.get(item.path)??{path:item.path},item.path,outside?'Linked Files/'+baseName(item.path):display,{project:project.path,projectBase:base,included:true,itemType:item.itemType,linked:!!item.metadata?.Link||outside,missing:!map.has(item.path),metadata:item.metadata});owned.add(item.path);}
  for(const [path,file]of map){const inside=base?path.startsWith(base+'/'):true,underAnother=projects.some(p=>p.path!==project.path&&directoryName(p.path)!==base&&directoryName(p.path)&&path.startsWith(directoryName(p.path)+'/'));if(inside&&!underAnother&&!compile.has(path)&&!explicitItems.has(path)&&path!==project.path&&(showAll||!['source'].includes(file.kind??(/\.cs$/i.test(path)?'source':'file')))){addFile(node,file,path,relativeTo(path,base),{project:project.path,projectBase:base,excluded:/\.cs$/i.test(path),included:false});owned.add(path);}}
  node.children.push({id:node.id+':xml',kind:'project-file',label:baseName(project.path),path:project.path,project:project.path,icon:'⚙',draggable:false,dirty:dirtySet.has(project.path)});owned.add(project.path);
  for(const path of folders.filter(f=>base?f.startsWith(base+'/'):true)){const display=relativeTo(path,base);if(!display.startsWith('../')){addFile(node,{kind:'folder-marker'},path+'/.sf-folder',display+'/.sf-folder',{project:project.path,projectBase:base});}}
 }
 for(const item of snapshot.solution?.items??[])if(item.kind==='file'){const parent=solutionFolder(item.folder);addFile(parent,map.get(item.path)??{kind:'file'},item.path,baseName(item.path));owned.add(item.path);}
 const others=[...map].filter(([path])=>!owned.has(path)&&path!==snapshot.solution?.path);if(others.length){const group={id:root.id+':items',kind:'solution-folder',label:'Solution Items',branch:true,children:[],icon:'▰',draggable:false};root.children.push(group);for(const [path,file]of others)if(showAll||!/\.cs$/i.test(path))addFile(group,file,path);}
 if(generated.length){root.children.push({id:root.id+':generated',kind:'generated-group',label:'Generated Sources',branch:true,draggable:false,icon:'⚙',children:generated.map(f=>({id:root.id+':generated:'+f.uri,kind:'generated',label:f.uri,path:f.uri,icon:'C#',draggable:false}))});}
 const clean=n=>{if(n.children){n.children=n.children.filter(c=>c.kind!=='folder-marker');n.children.forEach(clean);}};clean(root);attachSymbols(root);sort(root);return [root];
}
