import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { canonicalJSON, readJSON, sha256 } from './common.js';

/** Seals the exact generated bytes, including statuses, observations and issue proposals. */
export function outputManifest(outputs, platform, inputDigest) {
  return { schemaVersion: 1, platform, inputDigest,
    files: Object.keys(outputs).sort().map(name => ({ name, sha256: sha256(canonicalJSON(outputs[name])) })) };
}

export async function verifyRecordedOutputs(directory, current, platform, inputDigest) {
  const manifest = await readJSON(path.join(directory, 'outputs.json'));
  const names = Object.keys(current).sort();
  if (manifest.schemaVersion !== 1 || !/^node-(linux-x64|win32-x64|darwin-arm64)$/.test(manifest.platform ?? '') || manifest.inputDigest !== inputDigest || !Array.isArray(manifest.files)) throw new Error('Invalid/stale inventory output manifest; explicit reviewed --update required');
  if (JSON.stringify(manifest.files.map(file => file.name)) !== JSON.stringify(names)) throw new Error('Inventory output set changed; explicit reviewed --update required');
  const sameTarget = manifest.platform === platform;
  for (const file of manifest.files) {
    if (!/^[a-z][a-z0-9-]*\.json$/.test(file.name) || !/^[a-f0-9]{64}$/.test(file.sha256)) throw new Error('Malformed inventory output identity');
    const bytes = await readFile(path.join(directory, file.name));
    if (sha256(bytes) !== file.sha256) throw new Error(`Inventory output integrity mismatch: ${file.name}`);
    // Catalog observations belong to their actual platform. The shared ledger,
    // denominator and input set must agree even for an independent target run.
    if (sameTarget || ['gap-ids.json', 'obligations.json', 'inputs.json'].includes(file.name)) {
      if (sha256(canonicalJSON(current[file.name])) !== file.sha256) throw new Error(`Regenerated inventory output changed: ${file.name}; explicit reviewed --update required`);
    }
  }
  return { baselinePlatform: manifest.platform, observedPlatform: platform, sameTarget,
    mode: sameTarget ? 'all regenerated outputs match sealed baseline' : 'sealed baseline integrity and shared structure verified; target observations retained independently' };
}
