import {Writer,Reader,readMetadata,readPE,readSignature,metadataSchemas,metadataIndexWidth,decodeCoded,codedIndex,token,utf8,text,align,equalBytes} from '@sharpforge/cil';
import {sha256,sha1,hex} from './hash.js';
import {inflateRaw,deflateStored} from './deflate.js';
export {sha256,sha1,hex,inflateRaw,deflateStored};
export const PdbGuids=Object.freeze({csharp:'3f5162f8-07c6-11d3-9053-00c04fa302a1',sha1:'ff1816ec-aa5e-4d10-87f7-6f4963833460',sha256:'8829d00f-11b8-4213-878b-770e8597ac16',sha384:'d99cfeb1-8c43-444a-8a6c-b61269d2a0bf',sha512:'ef2d1afc-6550-46d6-b14b-d70afe9a5566',embeddedSource:'0e8a571b-6926-466e-b4ad-8ab04611f5fe',sourceLink:'cc110556-a091-4d38-9fec-25ab9a351a6a',asyncSteps:'54fd2ac5-e925-401a-9c2a-f94f171072f8',hoistedScopes:'6da9a61e-f8c7-4874-be62-68bc5630df71',dynamicLocals:'83c563c4-b4f3-47d5-b824-ba5441477ea8',encSlots:'755f52a8-91c5-45be-b4b8-209571e552bd',encLambdas:'a643004c-0240-496f-a783-30d64f4979de',defaultNamespace:'58b2eab6-209f-4e4e-a22c-b2d0f910c782',compilationOptions:'b5feec05-8cd0-4a83-96da-466284bb4bd8'});
export class SymbolError extends Error{constructor(message){super(message);this.name='SymbolError';}}
const fail=message=>{throw new SymbolError(message);};
const HIDDEN=0xfeefee;
export function guidBytes(value){if(!/^[\da-f]{8}-(?:[\da-f]{4}-){3}[\da-f]{12}$/i.test(value))fail('Invalid GUID');const raw=Uint8Array.from(value.replaceAll('-','').match(/../g),s=>parseInt(s,16));return Uint8Array.from([raw[3],raw[2],raw[1],raw[0],raw[5],raw[4],raw[7],raw[6],...raw.slice(8)]);}
export function guidString(bytes){if(bytes.length!==16)fail('Invalid GUID bytes');const b=Uint8Array.from([bytes[3],bytes[2],bytes[1],bytes[0],bytes[5],bytes[4],bytes[7],bytes[6],...bytes.slice(8)]),s=hex(b);return `${s.slice(0,8)}-${s.slice(8,12)}-${s.slice(12,16)}-${s.slice(16,20)}-${s.slice(20)}`;}
function signed(w,n){if(!Number.isInteger(n)||n< -0x10000000||n>0xfffffff)fail('Signed PDB integer out of range');const bits=n>=-64&&n<=63?7:n>=-8192&&n<=8191?14:29,v=((n&((2**(bits-1))-1))*2+(n<0?1:0))>>>0;if(bits===7)w.u8(v);else if(bits===14)w.u8((v>>>8)|0x80).u8(v);else w.u8((v>>>24)|0xc0).u8(v>>>16).u8(v>>>8).u8(v);return w;}
export function readSequencePoints(bytes,document=0,{maxPoints=1_000_000,documents=Infinity}={}){
  if(!bytes.length)return {localSignature:0,points:[]};const r=new Reader(bytes),localSignature=r.compressed();if(!document)document=r.compressed();if(document<1||document>documents)fail('Invalid initial document');let offset=0,line=0,column=0,first=true,visible=false;const points=[];
  while(r.position<r.end){if(points.length>=maxPoints)fail('Sequence point limit exceeded');const delta=r.compressed();if(!first&&delta===0){document=r.compressed();if(document<1||document>documents)fail('Invalid sequence point document');continue;}offset=first?delta:offset+delta;const dl=r.compressed(),dc=dl?r.signedCompressed():r.compressed();let p;if(dl===0&&dc===0)p={offset,document,startLine:HIDDEN,endLine:HIDDEN,startColumn:0,endColumn:0,hidden:true};else{line=visible?line+r.signedCompressed():r.compressed();column=visible?column+r.signedCompressed():r.compressed();p={offset,document,startLine:line,startColumn:column,endLine:line+dl,endColumn:dl?column+dc:column+dc,hidden:false};visible=true;if(line<0||line===HIDDEN||line>=0x20000000||p.endLine>=0x20000000||column<0||column>65535||p.endColumn<0||p.endColumn>65535||!dl&&p.endColumn<=column)fail('Invalid sequence point span');}if(offset>=0x20000000)fail('Invalid sequence point offset');points.push(p);first=false;}
  return {localSignature,points};
}
export function writeSequencePoints(points,document=0,localSignature=0){const w=new Writer().compressed(localSignature);if(!points.length)return new Uint8Array();let doc=document||points[0].document;if(!document)w.compressed(doc);let offset=0,line=0,column=0,first=true,visible=false;for(const p of points){if(p.document!==doc){if(first)fail('Initial PDB document mismatch');w.compressed(0).compressed(p.document);doc=p.document;}if(!Number.isInteger(p.offset)||p.offset<0||!first&&p.offset<=offset)fail('Sequence offsets must increase');w.compressed(first?p.offset:p.offset-offset);offset=p.offset;if(p.hidden||p.startLine===HIDDEN)w.compressed(0).compressed(0);else{const dl=p.endLine-p.startLine,dc=p.endColumn-p.startColumn;if(dl<0||dl===0&&dc<=0)fail('Invalid sequence span');w.compressed(dl);if(dl)signed(w,dc);else w.compressed(dc);if(!visible)w.compressed(p.startLine).compressed(p.startColumn);else{signed(w,p.startLine-line);signed(w,p.startColumn-column);}line=p.startLine;column=p.startColumn;visible=true;}first=false;}return w.finish();}
function decodeConstant(bytes){const r=new Reader(bytes),kind=r.u8();let value,type;const simple={2:['bool',1],3:['char',2],4:['sbyte',1],5:['byte',1],6:['short',2],7:['ushort',2],8:['int',4],9:['uint',4],10:['long',8],11:['ulong',8],12:['float',4],13:['double',8]};if(simple[kind]){[type]=simple[kind];if(kind===13)value=r.f64();else if(kind===12)value=r.f32();else if(kind===10||kind===11){value=r.i64();if(kind===11)value=BigInt.asUintN(64,value);}else{const n=simple[kind][1];value=n===1?r.u8():n===2?r.u16():r.u32();if([4,6,8].includes(kind))value=n===1?(value<<24)>>24:n===2?(value<<16)>>16:value|0;if(kind===2)value=!!value;}}else if(kind===14){type='string';const b=r.take(r.end-r.position);value=b.length===1&&b[0]===255?null:new TextDecoder('utf-16le',{fatal:true}).decode(b);}else if(kind===28){type='object';value=null;}else return {raw:bytes.slice(),type:'signature',decoded:false};return {type,value,decoded:true,enumType:r.position<r.end?r.compressed():null};}
function readImports(bytes,md){const r=new Reader(bytes),result=[];const name=()=>text(md.blob(r.compressed()));while(r.position<r.end){if(result.length>100000)fail('Import limit exceeded');const kind=r.compressed(),d={kind};switch(kind){case 1:d.namespace=name();break;case 2:d.assembly=r.compressed();d.namespace=name();break;case 3:d.type=decodeCoded('TypeDefOrRef',r.compressed());break;case 4:d.alias=name();d.namespace=name();break;case 5:d.alias=name();break;case 6:d.alias=name();d.assembly=r.compressed();break;case 7:d.alias=name();d.namespace=name();break;case 8:d.alias=name();d.assembly=r.compressed();d.namespace=name();break;case 9:d.alias=name();d.type=decodeCoded('TypeDefOrRef',r.compressed());break;default:fail('Unknown import definition kind');}result.push(d);}return result;}
export function readPortablePdb(input,{maxBytes=64*1024*1024,maxSourceBytes=16*1024*1024}={}){
  const bytes=input instanceof ArrayBuffer?new Uint8Array(input):input;if(!(bytes instanceof Uint8Array)||bytes.length>maxBytes)fail('Invalid or oversized Portable PDB');const md=readMetadata(bytes),pdb=md.streams.get('#Pdb');if(!pdb||pdb.length<32)fail('Not a standalone Portable PDB');if(Object.keys(md.rows).some(t=>+t<48||+t>55))fail('Portable PDB contains non-debug tables');const pr=new Reader(pdb),id=pr.take(20).slice(),entryPoint=pr.u32(),guids=md.streams.get('#GUID')??new Uint8Array();if(guids.length%16)fail('Invalid GUID heap');const guid=i=>i===0?null:i*16>guids.length?fail('Invalid GUID index'):guidString(guids.subarray((i-1)*16,i*16));
  const documents=(md.rows[48]??[]).map((row,i)=>{const nr=new Reader(md.blob(row[0]));if(!nr.end)fail('Document name cannot be nil');const separator=nr.u8(),parts=[];while(nr.position<nr.end)parts.push(text(md.blob(nr.compressed())));return {id:i+1,name:parts.join(separator?String.fromCharCode(separator):''),hashAlgorithm:guid(row[1]),hash:md.blob(row[2]).slice(),language:guid(row[3])};});if(new Set(documents.map(d=>d.name)).size!==documents.length)fail('Duplicate document names');
  const methods=(md.rows[49]??[]).map((row,i)=>({token:token(6,i+1),document:row[0],...readSequencePoints(md.blob(row[1]),row[0],{documents:documents.length})}));if(methods.length&&methods.length!==(md.externalCounts[6]??0))fail('PDB method row count does not match MethodDef count');
  const variables=(md.rows[51]??[]).map((r,i)=>({id:i+1,attributes:r[0],index:r[1],name:md.string(r[2]),hidden:!!(r[0]&1)}));
  const constants=(md.rows[52]??[]).map((r,i)=>({id:i+1,name:md.string(r[0]),signature:md.blob(r[1]).slice(),...decodeConstant(md.blob(r[1]))}));
  const imports=(md.rows[53]??[]).map((r,i)=>({id:i+1,parent:r[0],definitions:readImports(md.blob(r[1]),md)}));for(const scope of imports){let cur=scope,seen=new Set();while(cur){if(seen.has(cur.id))fail('Import scope cycle');seen.add(cur.id);if(cur.parent>imports.length)fail('Invalid parent import scope');cur=imports[cur.parent-1];}}
  const scopes=(md.rows[50]??[]).map((r,i,all)=>{const next=all[i+1];if(r[0]<1||r[0]>(md.externalCounts[6]??0)||r[1]>imports.length||r[2]<1||r[2]>variables.length+1||r[3]<1||r[3]>constants.length+1||!r[5]||r[4]+r[5]>=0x80000000)fail('Invalid local scope');const variableEnd=next?next[2]-1:variables.length,constantEnd=next?next[3]-1:constants.length;if(variableEnd<r[2]-1||constantEnd<r[3]-1)fail('Invalid local scope list ordering');const vs=variables.slice(r[2]-1,variableEnd);if(new Set(vs.map(x=>x.index)).size!==vs.length||new Set(vs.map(x=>x.name)).size!==vs.length)fail('Duplicate local in scope');return {id:i+1,methodToken:token(6,r[0]),importScope:r[1],start:r[4],end:r[4]+r[5],variables:vs,constants:constants.slice(r[3]-1,constantEnd)};});
  for(let i=0;i<scopes.length;i++){const s=scopes[i],prev=scopes[i-1];if(prev&&(s.methodToken<prev.methodToken||s.methodToken===prev.methodToken&&(s.start<prev.start||s.start===prev.start&&s.end>prev.end)))fail('Unsorted local scopes');for(let j=i-1;j>=0&&scopes[j].methodToken===s.methodToken;j--){const o=scopes[j];if(s.start<o.end&&s.end>o.end)fail('Partially overlapping local scopes');}}
  const stateMachines=(md.rows[54]??[]).map(r=>({moveNext:token(6,r[0]),kickoff:token(6,r[1])}));for(let i=0;i<stateMachines.length;i++){const s=stateMachines[i];if(!(s.moveNext&0xffffff)||!(s.kickoff&0xffffff)||(s.moveNext&0xffffff)>(md.externalCounts[6]??0)||(s.kickoff&0xffffff)>(md.externalCounts[6]??0)||i&&s.moveNext<=stateMachines[i-1].moveNext)fail('Invalid state machine method');}
  if(new Set(stateMachines.map(s=>s.kickoff)).size!==stateMachines.length)fail('Duplicate state machine kickoff');
  const custom=(md.rows[55]??[]).map((r,i)=>{const c={id:i+1,parent:decodeCoded('HasCustomDebugInformation',r[0]),kind:guid(r[1]),bytes:md.blob(r[2]).slice()};if(c.kind===PdbGuids.embeddedSource){const er=new Reader(c.bytes),size=er.i32();if(size<0||size>maxSourceBytes)fail('Invalid embedded source size');const content=er.take(er.end-er.position);if(content.length>maxSourceBytes)fail('Embedded source size exceeds budget');c.source=size?inflateRaw(content,size,maxSourceBytes):content.slice();if(c.parent>>>24!==48||!documents[(c.parent&0xffffff)-1])fail('Embedded source parent is not a document');documents[(c.parent&0xffffff)-1].embedded=c.source;}
    else if(c.kind===PdbGuids.sourceLink){try{c.sourceLink=JSON.parse(text(c.bytes));}catch{fail('Invalid Source Link JSON');}if(!c.sourceLink||typeof c.sourceLink.documents!=='object'||Array.isArray(c.sourceLink.documents)||!c.sourceLink.documents)fail('Invalid Source Link document map');for(const [k,v]of Object.entries(c.sourceLink.documents))if(typeof v!=='string'||k.split('*').length>2||v.split('*').length>2)fail('Invalid Source Link mapping');}
    else if(c.kind===PdbGuids.asyncSteps){const ar=new Reader(c.bytes);c.catchHandlerOffset=ar.u32()-1;c.awaits=[];while(ar.position<ar.end)c.awaits.push({yieldOffset:ar.u32(),resumeOffset:ar.u32(),resumeMethod:token(6,ar.compressed())});}
    else if(c.kind===PdbGuids.hoistedScopes){if(c.bytes.length%8)fail('Malformed hoisted scopes');const hr=new Reader(c.bytes);c.scopes=[];while(hr.position<hr.end){const start=hr.u32(),length=hr.u32();c.scopes.push({start,end:start+length});}}
    else if(c.kind===PdbGuids.defaultNamespace)c.namespace=text(c.bytes);
    else if(c.kind===PdbGuids.compilationOptions){const vals=text(c.bytes).split('\0');if(vals.at(-1)==='')vals.pop();if(vals.length%2)fail('Invalid compilation options');c.options=Object.fromEntries(Array.from({length:vals.length/2},(_,i)=>[vals[i*2],vals[i*2+1]]));}
    return c;});
  const methodMap=new Map(methods.map(m=>[m.token,m]));
  return {format:'Portable PDB',id,idHex:hex(id),entryPoint,bytes:bytes.slice(),metadata:md,documents,methods,variables,constants,scopes,imports,stateMachines,custom,sourceLink:custom.find(c=>c.sourceLink)?.sourceLink??null,
    location(methodToken,offset){const points=methodMap.get(methodToken)?.points??[];let l=0,r=points.length;while(l<r){const m=(l+r)>>>1;if(points[m].offset<=offset)l=m+1;else r=m;}const p=points[l-1];return p&&!p.hidden?{...p,source:documents[p.document-1]?.name}:null;},
    locals(methodToken,offset){const active=scopes.filter(s=>s.methodToken===methodToken&&offset>=s.start&&offset<s.end);return active.flatMap(s=>s.variables).filter(v=>!v.hidden);},
    asyncInfo(methodToken){return {stateMachine:stateMachines.find(s=>s.moveNext===methodToken||s.kickoff===methodToken)??null,steps:custom.find(c=>c.parent===methodToken&&c.kind===PdbGuids.asyncSteps)?.awaits??[]};}
  };
}
export class PortablePdbBuilder{
  constructor(){this.strings=new Writer().u8(0);this.blobs=new Writer().u8(0);this.guids=new Writer();this.sm=new Map([['',0]]);this.bm=new Map();this.gm=new Map();this.rows={};}
  string(s){if(this.sm.has(s))return this.sm.get(s);const at=this.strings.length;this.strings.bytes(utf8(s)).u8(0);this.sm.set(s,at);return at;}
  blob(b){if(!b.length)return 0;const key=hex(b);if(this.bm.has(key))return this.bm.get(key);const at=this.blobs.length;this.blobs.compressed(b.length).bytes(b);this.bm.set(key,at);return at;}
  guid(s){if(!s)return 0;if(this.gm.has(s))return this.gm.get(s);const n=this.guids.length/16+1;this.guids.bytes(guidBytes(s));this.gm.set(s,n);return n;}
  add(t,r){const a=this.rows[t]??=[];a.push(r);return a.length;}
  finish(external,entryPoint){const pdb=new Writer().zero(20).u32(entryPoint);let lo=0,hi=0;for(const [id,n]of Object.entries(external))if(n){if(+id<32)lo|=1<<+id;else hi|=1<<(+id-32);}pdb.u32(lo).u32(hi);for(let i=0;i<64;i++)if(external[i])pdb.u32(external[i]);const counts={...external,...Object.fromEntries(Object.entries(this.rows).map(([t,r])=>[t,r.length]))},flags=(this.strings.length>=65536?1:0)|(this.guids.length>=65536?2:0)|(this.blobs.length>=65536?4:0),tb=new Writer().u32(0).u8(2).u8(0).u8(flags).u8(1);let high=0;for(const t of Object.keys(this.rows))high|=1<<(+t-32);tb.u32(0).u32(high).u32(0).u32((1<<(50-32))|(1<<(54-32))|(1<<(55-32)));for(let t=48;t<=55;t++)if(this.rows[t])tb.u32(this.rows[t].length);for(let t=48;t<=55;t++)for(const row of this.rows[t]??[])row.forEach((v,i)=>metadataIndexWidth(metadataSchemas[t][i],counts,flags)===2?tb.u16(v):tb.u32(v));const streams=[['#Pdb',pdb.finish()],['#~',tb.finish()],['#Strings',this.strings.finish()],['#GUID',this.guids.finish()],['#Blob',this.blobs.finish()]],root=new Writer().u32(0x424a5342).u16(1).u16(1).u32(0).u32(12).bytes(utf8('PDB v1.0\0\0\0\0')).u16(0).u16(streams.length),patch=[];for(const[n,b]of streams){patch.push(root.length);root.u32(0).u32(b.length).bytes(utf8(n)).u8(0).pad();}let pdbOffset;streams.forEach(([name,b],i)=>{root.pad();root.patch32(patch[i],root.length);if(name==='#Pdb')pdbOffset=root.length;root.bytes(b);});const bytes=root.finish(),hash=sha256(bytes),id=hash.slice(0,20);id[7]=(id[7]&15)|0x40;id[8]=(id[8]&63)|0x80;id[19]|=0x80;bytes.set(id,pdbOffset);return {bytes,id,checksum:hash};}
}
/** Emit independent standard symbols for the exact emitted PE's tokens/offsets. */
export function emitPortablePdb(assembly,debug,{embedSources=true,sourceLink=null}={}){
  const pe=readPE(assembly,{inspection:true}),b=new PortablePdbBuilder(),docs=new Map(),cdi=[];for(const s of debug.sources??[]){const raw=s.bytes??utf8(s.text??''),name=b.blob(new Writer().u8(0).compressed(b.blob(utf8(s.uri))).finish()),id=b.add(48,[name,b.guid(PdbGuids.sha256),b.blob(sha256(raw)),b.guid(PdbGuids.csharp)]);docs.set(s.uri,id);if(embedSources&&s.text!==undefined)cdi.push([codedIndex('HasCustomDebugInformation',token(48,id)),b.guid(PdbGuids.embeddedSource),b.blob(new Writer().u32(0).bytes(raw).finish())]);}
  const sourceIndexes=new Map((debug.sources??[]).map(s=>[s.uri,{text:s.text??'',lines:lineIndex(s.text??'')}])),pointsByMethod=new Map();for(const p of debug.sequencePoints??[]){if(!docs.has(p.uri))continue;if(!pointsByMethod.has(p.methodToken))pointsByMethod.set(p.methodToken,[]);pointsByMethod.get(p.methodToken).push(p);}const methods=new Map((debug.methods??[]).map(m=>[m.token,m]));for(let i=1;i<=(pe.metadata.counts[6]??0);i++){const methodToken=token(6,i),m=methods.get(methodToken),body=pe.metadata.row(methodToken)[0]?pe.methodBody(methodToken):null,points=(pointsByMethod.get(methodToken)??[]).map(p=>{const src=sourceIndexes.get(p.uri),loc=p.line!=null&&p.column!=null&&p.endLine!=null&&p.endColumn!=null?p:sourceSpan(src?.text??'',p.start,p.end,src?.lines);return {offset:p.ilOffset,document:docs.get(p.uri),startLine:p.line??loc.line,startColumn:p.column??loc.column,endLine:p.endLine??loc.endLine,endColumn:p.endColumn??loc.endColumn};}).sort((a,c)=>a.offset-c.offset).filter((p,j,a)=>!j||p.offset!==a[j-1].offset),doc=points.length&&points.every(p=>p.document===points[0].document)?points[0].document:0;b.add(49,[doc,b.blob(writeSequencePoints(points,doc,body?.localSignature&0xffffff))]);if(m&&body?.code.length){const ranges=[{start:0,end:body.code.length,locals:(m.locals??[]).filter(l=>l.hidden)}];for(const local of (m.locals??[]).filter(l=>!l.hidden)){const start=m.spans[local.scopeStartPc??0]?.[0]??0,end=local.scopeEndPc===m.spans.length?body.code.length:m.spans[local.scopeEndPc]?.[0]??body.code.length;if(end>start)ranges.push({start,end,locals:[local]});}ranges.sort((a,z)=>a.start-z.start||z.end-a.end);for(const scope of ranges){const start=(b.rows[51]?.length??0)+1;for(const local of scope.locals)b.add(51,[local.hidden?1:0,local.slot,b.string(local.name)]);b.add(50,[i,0,start,(b.rows[52]?.length??0)+1,scope.start,scope.end-scope.start]);}}}
  if(sourceLink)cdi.push([codedIndex('HasCustomDebugInformation',token(0,1)),b.guid(PdbGuids.sourceLink),b.blob(utf8(JSON.stringify(sourceLink)))]);cdi.sort((a,c)=>a[0]-c[0]);for(const r of cdi)b.add(55,r);return b.finish(pe.metadata.counts,pe.entryPoint);
}
function lineIndex(source){const lines=[0];for(let i=0;i<source.length;i++)if(source.charCodeAt(i)===10)lines.push(i+1);return lines;}
export function sourceSpan(source,start=0,end=start+1,lines=lineIndex(source)){start=Math.min(Math.max(0,start),source.length);end=Math.min(Math.max(start+1,end),source.length);const at=n=>{let l=0,r=lines.length;while(l<r){const m=(l+r)>>>1;if(lines[m]<=n)l=m+1;else r=m;}const index=Math.max(0,l-1);return {line:index+1,column:n-lines[index]+1};},a=at(start),z=at(end);if(z.line===a.line&&z.column<=a.column)z.column=a.column+1;return {...a,endLine:z.line,endColumn:z.column};}
export function readDebugDirectory(assembly){const pe=readPE(assembly,{inspection:true}),v=new DataView(pe.bytes.buffer,pe.bytes.byteOffset,pe.bytes.byteLength),dir=pe.optionalStart+(pe.magic===0x10b?96:112)+6*8,rva=v.getUint32(dir,true),size=v.getUint32(dir+4,true);if(!size)return [];if(size%28||size>28*1024)fail('Invalid debug directory size');const r=new Reader(pe.bytes,pe.offsetOf(rva,size),size),entries=[];while(r.position<r.end){const characteristics=r.u32(),stamp=r.u32(),major=r.u16(),minor=r.u16(),kind=r.u32(),length=r.u32(),dataRva=r.u32(),offset=r.u32();if(offset+length>pe.bytes.length)fail('Truncated debug entry');const bytes=pe.bytes.subarray(offset,offset+length),e={kind,stamp,major,minor,bytes,offset};if(kind===2){if(bytes.length<25||text(bytes.subarray(0,4))!=='RSDS')fail('Invalid CodeView record');e.guid=bytes.slice(4,20);e.age=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).getUint32(20,true);const zero=bytes.indexOf(0,24);if(zero<0)fail('Unterminated PDB path');e.path=text(bytes.subarray(24,zero));e.id=new Writer().bytes(e.guid).u32(stamp).finish();}else if(kind===17){const er=new Reader(bytes);if(er.u32()!==0x4244504d)fail('Invalid embedded Portable PDB signature');const n=er.u32();e.pdb=inflateRaw(er.take(er.end-er.position),n);}else if(kind===19){const zero=bytes.indexOf(0);if(zero<0)fail('Invalid PDB checksum');e.algorithm=text(bytes.subarray(0,zero));e.checksum=bytes.slice(zero+1);}entries.push(e);}return entries;}
export function attachPortablePdb(assembly,pdb,{path='Application.pdb',embedded=false,checksum=true}={}){if(pdb instanceof ArrayBuffer)pdb=new Uint8Array(pdb);if(typeof path!=='string'||path.includes('\0')||path.length>32768)fail('Invalid PDB path');
  if(typeof path!=='string'||path.includes('\0')||path.length>4096)fail('Invalid symbol path');const parsed=readPortablePdb(pdb),pe=readPE(assembly,{inspection:true}),entries=readDebugDirectory(assembly);if(entries.length)fail('Assembly already contains a debug directory');const last=[...pe.sections].sort((a,b)=>a.offset-b.offset).at(-1);if(last.offset+last.size!==pe.bytes.length)fail('Cannot append symbols to PE with an overlay');const payloads=[{kind:2,major:0x100,minor:0x504d,stamp:new DataView(parsed.id.buffer,parsed.id.byteOffset).getUint32(16,true),bytes:new Writer().bytes(utf8('RSDS')).bytes(parsed.id.subarray(0,16)).u32(1).bytes(utf8(path)).u8(0).finish()}];if(embedded)payloads.push({kind:17,major:0x100,minor:0x100,stamp:0,bytes:new Writer().u32(0x4244504d).u32(pdb.length).bytes(deflateStored(pdb)).finish()});if(checksum){const zero=pdb.slice(),pdbAt=parsed.metadata.streams.get('#Pdb').byteOffset-pdb.byteOffset;zero.fill(0,pdbAt,pdbAt+20);payloads.push({kind:19,major:1,minor:0,stamp:0,bytes:new Writer().bytes(utf8('SHA256\0')).bytes(sha256(zero)).finish()});}const offset=align(pe.bytes.length,4),w=new Writer().bytes(pe.bytes).zero(offset-pe.bytes.length).zero(28*payloads.length);payloads.forEach((e,i)=>{w.pad();const at=w.length;w.bytes(e.bytes);const p=new Writer().u32(0).u32(e.stamp).u16(e.major).u16(e.minor).u32(e.kind).u32(e.bytes.length).u32(last.rva+at-last.offset).u32(at);w.buffer.set(p.finish(),offset+i*28);});const virtualSize=w.length-last.offset;w.pad(512);const out=w.finish(),v=new DataView(out.buffer);v.setUint32(last.headerOffset+8,virtualSize,true);v.setUint32(last.headerOffset+16,out.length-last.offset,true);v.setUint32(pe.optionalStart+56,align(last.rva+virtualSize,8192),true);v.setUint32(pe.optionalStart+4,out.length-512,true);const dir=pe.optionalStart+(pe.magic===0x10b?96:112)+6*8;v.setUint32(dir,last.rva+offset-last.offset,true);v.setUint32(dir+4,28*payloads.length,true);return out;}
export function loadSymbols(assembly,pdbBytes=null,options={}){if(pdbBytes instanceof ArrayBuffer)pdbBytes=new Uint8Array(pdbBytes);const entries=readDebugDirectory(assembly),embedded=entries.find(e=>e.kind===17)?.pdb;if(!pdbBytes)pdbBytes=embedded;if(!pdbBytes)fail('No Portable PDB was selected or embedded');const symbols=readPortablePdb(pdbBytes,options),codeViews=entries.filter(e=>e.kind===2&&e.minor===0x504d);if(!codeViews.length&&!options.allowUnbound)fail('Assembly has no Portable PDB identity; explicit unbound inspection is required');if(codeViews.length&&!codeViews.some(e=>e.age===1&&equalBytes(e.id,symbols.id)))fail('Portable PDB does not match assembly identity');if(embedded&&!equalBytes(readPortablePdb(embedded).id,symbols.id))fail('Embedded and external PDB identities differ');for(const e of entries.filter(e=>e.kind===19)){if(e.algorithm!=='SHA256')continue;const zero=symbols.bytes.slice(),at=symbols.metadata.streams.get('#Pdb').byteOffset-pdbBytes.byteOffset;zero.fill(0,at,at+20);if(!equalBytes(sha256(zero),e.checksum))fail('Portable PDB checksum mismatch');}const pe=readPE(assembly,{inspection:true});for(const [t,n]of Object.entries(symbols.metadata.externalCounts))if((pe.metadata.counts[t]??0)!==n)fail('Portable PDB type-system row counts differ');for(const m of symbols.methods){if(!m.points.length)continue;const body=pe.methodBody(m.token);for(const p of m.points)if(p.offset>=body.code.length)fail('Sequence point is outside its method body');}symbols.bound=codeViews.length>0;return symbols;}
export function verifySource(document,input){const bytes=typeof input==='string'?utf8(input):input;if(!(bytes instanceof Uint8Array))fail('Source must be text or bytes');if(document.hashAlgorithm===PdbGuids.sha256)return equalBytes(sha256(bytes),document.hash);if(document.hashAlgorithm===PdbGuids.sha1)return equalBytes(sha1(bytes),document.hash);return false;}
export async function verifySourceAsync(document,input){if([PdbGuids.sha256,PdbGuids.sha1].includes(document.hashAlgorithm))return verifySource(document,input);const algorithm={[PdbGuids.sha384]:'SHA-384',[PdbGuids.sha512]:'SHA-512'}[document.hashAlgorithm];if(!algorithm||!globalThis.crypto?.subtle)return false;const bytes=typeof input==='string'?utf8(input):input;return equalBytes(new Uint8Array(await crypto.subtle.digest(algorithm,bytes)),document.hash);}
export function sourceLinkUrl(symbols,documentName){const matches=[];for(const [pattern,url]of Object.entries(symbols.sourceLink?.documents??{})){const pos=pattern.indexOf('*');if(pos<0){if(pattern===documentName)matches.push({url,specificity:Infinity});}else{const begin=pattern.slice(0,pos),end=pattern.slice(pos+1);if(documentName.startsWith(begin)&&documentName.endsWith(end)){const middle=documentName.slice(begin.length,documentName.length-end.length),encoded=middle.split(/[\\/]/).map(encodeURIComponent).join('/');matches.push({url:url.replace('*',encoded),specificity:begin.length+end.length});}}}matches.sort((a,b)=>b.specificity-a.specificity);const value=matches[0]?.url;if(!value)return null;const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password)fail('Source Link must use credential-free HTTPS');return u.href;}
/** Attach only checksum-verified source; never fetch Source Link implicitly. */
export function bindSources(symbols,sources={}){const byName=sources instanceof Map?sources:new Map(Object.entries(sources)),documents=symbols.documents.map(d=>{const raw=byName.get(d.name)??d.embedded,bytes=typeof raw==='string'?utf8(raw):raw,verified=bytes?verifySource(d,bytes):false;let content=null;if(verified){const hasUtf16=bytes[0]===255&&bytes[1]===254||bytes[0]===254&&bytes[1]===255;content=hasUtf16?new TextDecoder(bytes[0]===255?'utf-16le':'utf-16be',{fatal:true}).decode(bytes):new TextDecoder('utf-8',{fatal:true}).decode(bytes);}return {...d,verified,text:content,reason:raw===undefined?'Source not supplied':verified?'Checksum verified':'Source checksum mismatch or unsupported algorithm'};}),indexes=documents.map(d=>d.verified?lineIndex(d.text):[]),sequencePoints=[];for(const m of symbols.methods)for(const p of m.points){const d=documents[p.document-1];if(p.hidden)continue;const lines=indexes[p.document-1],valid=d.verified&&p.startLine>=1&&p.endLine<=lines.length&&p.startColumn>=1&&p.endColumn>=1,start=valid?lines[p.startLine-1]+p.startColumn-1:0,end=valid?lines[p.endLine-1]+p.endColumn-1:1;if(d.verified&&(!valid||start>d.text.length||end>d.text.length||end<=start))fail('Sequence point is outside verified source text');sequencePoints.push({id:sequencePoints.length,uri:d.name,line:p.startLine,column:p.startColumn,endLine:p.endLine,endColumn:p.endColumn,start,end,ilOffset:p.offset,methodToken:m.token,methodId:m.token&0xffffff,sourceVerified:d.verified});}return {documents,sequencePoints,sources:documents.filter(d=>d.verified).map(d=>({uri:d.name,text:d.text,version:1})),methods:symbols.methods.map(m=>({token:m.token,locals:symbols.scopes.filter(s=>s.methodToken===m.token).flatMap(s=>s.variables.map(v=>({name:v.name,slot:v.index,hidden:v.hidden,startOffset:s.start,endOffset:s.end})))}))};}
