import {DiagnosticId} from '../diagnostics/codes.js';
/**
 * Global using directives (SF-A02-T74, C# 10): the `global using` directives of every compilation unit apply to all
 * of them. This module merges them across trees, checks where they are written and produces the implicit usings of
 * an SDK project as one more compilation unit, the way the .NET SDK does (`GlobalUsings.g.cs`).
 *
 *   CS8914  a global using directive inside a namespace declaration
 *   CS8915  a global using directive after a non-global one
 * Binding (./using-directives.js) reports an alias declared by two global directives (CS1537) on the later one, in
 * its own file; a directive that repeats a global using of another file is not a warning (Roslyn's hidden CS8933).
 */

const isNamespace = member => member.kind === 'NamespaceDeclaration' || member.kind === 'FileScopedNamespaceDeclaration';

/**
 * The global using directives of all files in file order, with the file each one comes from.
 * @returns {{directives:object[],uriOf:Map<object,string>}}
 */
export function mergeGlobalUsings(files) {
  const directives = [],
    uriOf = new Map();
  for (const file of files) {
    for (const directive of file.syntax.usings) {
      if (!directive.globalKeyword) continue;
      directives.push(directive);
      uriOf.set(directive, file.source.uri);
    }
  }
  return { directives, uriOf };
}

/**
 * Placement rules of the global using directives of one file.
 * @returns {{node:object,code:string,args:string[]}[]} rows located at the `global` keyword
 */
export function checkGlobalUsingPlacement(file) {
  const rows = [];
  // CS8915 is reported once per file, at the first global directive that follows a non-global one.
  const usings = [...(file.syntax?.usings ?? [])],
    firstPlain = usings.findIndex(directive => !directive.globalKeyword),
    misplaced = firstPlain < 0 ? null : usings.slice(firstPlain).find(directive => directive.globalKeyword);
  if (misplaced) rows.push({ node: misplaced.globalKeyword, code: DiagnosticId.CS8915, args: [] });
  const visit = container => {
    for (const member of container.members ?? []) {
      if (!isNamespace(member)) continue;
      for (const directive of member.usings ?? [])
        if (directive.globalKeyword) rows.push({ node: directive.globalKeyword, code: DiagnosticId.CS8914, args: [] });
      visit(member);
    }
  };
  if (file.syntax) visit(file.syntax);
  return rows;
}

/** The namespaces `<ImplicitUsings>enable</ImplicitUsings>` imports in a Microsoft.NET.Sdk project. */
export const sdkImplicitUsings = Object.freeze([
  'System',
  'System.Collections.Generic',
  'System.IO',
  'System.Linq',
  'System.Net.Http',
  'System.Threading',
  'System.Threading.Tasks',
]);

/** The document name of the generated compilation unit that carries the implicit usings. */
export const implicitUsingsUri = 'GlobalUsings.g.cs';

/**
 * The compilation unit for the `implicitUsings` option: `true` (the SDK set) or a list of namespace names
 * (`static X` and `Alias = X` entries are written as given).
 * @returns {{uri:string,text:string}|null} null when the option is off or the list is empty
 */
export function implicitUsingsUnit(option) {
  const names = option === true ? sdkImplicitUsings : Array.isArray(option) ? option : [];
  if (!names.length) return null;
  const text = '// <auto-generated/>\n' + names.map(name => `global using ${String(name).trim()};\n`).join('');
  return { uri: implicitUsingsUri, text };
}
