import { RendererRegistry } from '../registry.js';
import { contentLayout } from './border-viewbox.js';
import { buttonLayout } from './button-layout.js';
import { stackPanelLayout } from './stackpanel.js';
import { canvasLayout } from './canvas.js';
import { gridLayout } from './grid.js';
import { relativePanelLayout } from './relativepanel.js';
import { wrapGridLayout } from './wrapgrid.js';
import { scrollViewerLayout } from './scrollviewer.js';
import { scrollViewLayout } from './scroll-presenter.js';
import { annotatedScrollLayout } from './annotated-layout.js';
import { viewboxLayout } from './border-viewbox.js';
import { expanderLayout } from './expander.js';
import { twoPaneLayout } from './twopaneview.js';
import { parallaxLayout } from './parallaxview.js';
import { registerNavigationLayouts } from '../navigation/layout.js';
import { registerCommandLayouts } from '../commands/layout.js';
import { registerMenuLayouts } from '../commands/menu-layout.js';

export function createLayoutRegistry(options) {
  const registry = new RendererRegistry(options);
  registry.register('*', contentLayout);
  registry.register(['Button', 'ToggleButton', 'AppBarButton', 'HyperlinkButton'], buttonLayout);
  registry.register('StackPanel', stackPanelLayout);
  registry.register('Canvas', canvasLayout);
  registry.register('Grid', gridLayout);
  registry.register('RelativePanel', relativePanelLayout);
  registry.register(['WrapGrid', 'VariableSizedWrapGrid'], wrapGridLayout);
  registry.register(['ScrollViewer', 'ScrollPresenter'], scrollViewerLayout);
  registry.register('ScrollView', scrollViewLayout);
  registry.register('AnnotatedScrollBar', annotatedScrollLayout);
  registry.register('Viewbox', viewboxLayout);
  registry.register('Expander', expanderLayout);
  registry.register('TwoPaneView', twoPaneLayout);
  registry.register('ParallaxView', parallaxLayout);
  registerNavigationLayouts(registry);
  registerCommandLayouts(registry);
  registerMenuLayouts(registry);
  return registry;
}
export * from './geometry.js';
export * from './layout-engine.js';
export * from './framework-element-layout.js';
export * from './measure-provider.js';
export * from './custom-layout.js';
export * from './stackpanel.js';
export * from './canvas.js';
export * from './border-viewbox.js';
export * from './grid.js';
export * from './grid-tracks.js';
export * from './grid-span.js';
export * from './relativepanel.js';
export * from './wrapgrid.js';
export * from './scrollviewer.js';
export * from './scrollview.js';
export * from './scroll-options.js';
export * from './scroll-animation.js';
export * from './scroll-anchoring.js';
export * from './scroll-host.js';
export * from './scroll-presenter.js';
export * from './annotated-scrollbar.js';
export * from './annotated-adapters.js';
export * from './template-services.js';
export * from './expander.js';
export * from './twopaneview.js';
export * from './render-properties.js';
export * from './dom-applier.js';
export { XamlRootMetrics } from './dpi.js';
export * from './text-scale.js';
export * from './parallaxview.js';
export * from './operations.js';
export * from './adapters.js';
export * from './button-layout.js';
export * from './text-format.js';
export * from './environment-state.js';
export * from './environment-browser.js';
export * from './environment-adapters.js';
export { registerEnvironmentContracts } from '../contracts/environment.js';
