import '../planning/contracts/tests/value-abi.test.js';
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {inventoryText} from '../scripts/planning/inventory-values.js';import {checkVersions,negotiate,sourceVersion} from '../scripts/planning/abi/check-versions.js';
test('A00 inventory reproducible and all result carriers documented',()=>{assert.equal(inventoryText(),readFileSync(new URL('../planning/contracts/value-abi/current-js-inventory.json',import.meta.url),'utf8'));assert.deepEqual(Object.keys(JSON.parse(inventoryText()).resultKinds),['int','long','double','numeric','bool','string','array','exception','any']);});
test('A00 version registry equals public source constants',()=>{const versions=checkVersions();for(const value of [0,2,99,null])assert.throws(()=>negotiate({...versions,value},versions),{code:'ABI_VERSION'});assert.throws(()=>negotiate({...versions,unknown:1},versions));});

test('A00 source constant drift fails before version negotiation',()=>{const root=mkdtempSync(join(tmpdir(),'sf-version-'));try{for(const d of ['planning/contracts','packages/framework/src','packages/bytecode/src','scripts/planning/abi'])mkdirSync(join(root,d),{recursive:true});writeFileSync(join(root,'planning/contracts/versions.json'),JSON.stringify({framework:1,bytecode:1,value:1,metadata:1}));writeFileSync(join(root,'packages/framework/src/index.js'),'export const ABI_VERSION = 2;');assert.throws(()=>checkVersions(root),/framework version drift/);}finally{rmSync(root,{recursive:true,force:true});}});

test('A00 version reader follows explicit re-exports and rejects cycles',()=>{const root=mkdtempSync(join(tmpdir(),'sf-version-exports-'));try{const entry=join(root,'index.js');writeFileSync(entry,"export { VERSION as ABI_VERSION } from './registry.js';");writeFileSync(join(root,'registry.js'),'export const VERSION = 1;');assert.equal(sourceVersion(entry,'ABI_VERSION'),1);writeFileSync(join(root,'registry.js'),'export const VERSION = 2;');assert.equal(sourceVersion(entry,'ABI_VERSION'),2);writeFileSync(join(root,'registry.js'),"export { ABI_VERSION as VERSION } from './index.js';");assert(Number.isNaN(sourceVersion(entry,'ABI_VERSION')));}finally{rmSync(root,{recursive:true,force:true});}});
