import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {createServiceRegistry} from '../apps/studio/services/registry.js';
import {createCommandRegistry} from '../apps/studio/commands/registry.js';
import {registerStudioCommands} from '../apps/studio/commands/core.js';
import {createMenuRegistry} from '../apps/studio/menus/registry.js';
import {registerStudioMenus} from '../apps/studio/menus/core.js';
import {createToolRegistry} from '../apps/studio/tools/registry.js';
import {toolDefinitions} from '../apps/studio/tools/definitions.js';
import {createAutomationApi,automationKeyPaths} from '../apps/studio/automation-api.js';
import {createStorage,storageKeys} from '../apps/studio/settings/storage.js';
import {createWorkerProtocol,workerMethods} from '../apps/studio/workers/protocol.js';

test('two independent tools start and a failed third batch restores the container',()=>{const registry=createServiceRegistry(),stopped=[];const first=registry.register('first',()=>({count:0}),v=>stopped.push(v));const second=registry.register('second',()=>({count:0}));first.count++;assert.equal(second.count,0);assert.throws(()=>registry.registerAll([{name:'transient',factory:()=>({}),dispose:()=>stopped.push('transient')},{name:'failure',factory:()=>{throw new Error('factory failure');}}]),/factory failure/);assert.equal(registry.get('first'),first);assert.equal(registry.has('transient'),false);assert.deepEqual(stopped,['transient']);registry.dispose();registry.dispose();assert.equal(stopped[1],first);assert.throws(()=>registry.get('first'),/disposed/);});
test('container preflights duplicates, reports disposal errors and rolls back cancellation',()=>{const registry=createServiceRegistry(),abort=new AbortController();let starts=0;assert.throws(()=>registry.registerAll([{name:'same',factory:()=>starts++},{name:'same',factory:()=>starts++}]),/Duplicate/);assert.equal(starts,0);assert.throws(()=>registry.registerAll([{name:'one',factory:()=>{abort.abort();return 1;}}],{signal:abort.signal}),{name:'AbortError'});assert.equal(registry.has('one'),false);assert.throws(()=>registry.register('async',async()=>1),/synchronous/);registry.register('throws',()=>1,()=>{throw new Error('cleanup');});assert.throws(()=>registry.dispose(),AggregateError);});
test('commands preserve handler behavior and reject duplicate registrations',async()=>{const registry=createCommandRegistry(),panels=[],context=new Proxy({toolDefinitions,EDITOR_KEYMAPS:[{id:'vim',label:'Vim'}],setPanel:id=>panels.push(id),state:{},setEditorKeymap:id=>panels.push(id)}, {get:(t,key)=>t[key]??(()=>{})});registerStudioCommands(registry,context);await registry.execute('output');await registry.execute('tool:heap');await registry.execute('keymap:vim');assert.deepEqual(panels,['output','heap','vim']);assert.throws(()=>registry.registerCommand('output','Duplicate','',()=>{}),/Duplicate/);await assert.rejects(registry.execute('unknown'),/Unknown/);registry.dispose();assert.deepEqual(registry.list(),[]);});
test('tools append menu items without global state or editing Studio',()=>{const a=createMenuRegistry(),b=createMenuRegistry();registerStudioMenus(a,{toolDefinitions});assert.equal(a.items('file')[0][0],'New Project / Solution…');const remove=a.registerMenu('tools',[['Independent tool','tool:example','']]);assert.equal(a.items('tools').at(-1)[0],'Independent tool');assert.deepEqual(b.items('tools'),[]);remove();assert.notEqual(a.items('tools').at(-1)?.[0],'Independent tool');assert.throws(()=>a.registerMenu('bad',[{}]),/Malformed/);a.dispose();assert.deepEqual(a.items('file'),[]);});
test('each mount has independent state and DOM, and failed render cleans up',()=>{const registry=createToolRegistry(),stopped=[];for(const id of ['one','two'])registry.registerTool(id,id,(element,{state})=>{state.count=(state.count??0)+1;element.value=state.count;},(element,{state})=>stopped.push([element,state.count]));const elements=[{},{},{},{}],mounts=elements.map((element,i)=>registry.mount(i<2?'one':'two',element));mounts[0].render();assert.deepEqual(elements.map(e=>e.value),[2,1,1,1]);registry.registerTool('broken','Broken',()=>{throw new Error('render');},()=>stopped.push('broken'));assert.throws(()=>registry.mount('broken',{}),/render/);assert.equal(stopped[0],'broken');registry.dispose();assert.equal(stopped.length,5);assert.throws(()=>mounts[0].render(),/disposed/);});
test('automation contributions preserve the complete pre-extraction key surface',async()=>{const registry=createAutomationApi(),context=new Proxy({}, {get:()=>()=>{}});for(const file of (await readdir(new URL('../apps/studio/tools/',import.meta.url))).filter(name=>name.endsWith('-automation.js'))){const module=await import('../apps/studio/tools/'+file);Object.values(module)[0](registry,context);}const expected=JSON.parse(await readFile(new URL('../planning/contracts/studio-automation.lock.json',import.meta.url)));assert.deepEqual(automationKeyPaths(registry.api),expected);});
test('automation duplicate batches roll back and namespaces dispose cleanly',()=>{const r=createAutomationApi();const remove=r.contributeAutomation('tools.one',{run:()=>1});assert.equal(r.api.tools.one.run(),1);assert.throws(()=>r.contributeAutomation('tools.one',{other:()=>2,run:()=>3}),/Duplicate/);assert.equal(r.api.tools.one.other,undefined);assert.throws(()=>r.contributeAutomation('__proto__.bad',{run:()=>{}}),/namespace/);remove();assert.deepEqual(r.api,{});});
test('storage preserves v1 payloads, versions and quota failures',()=>{const values=new Map([[storageKeys.workspace,'{"files":[]}']]),backend={getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key)},s=createStorage({provider:()=>backend});assert.deepEqual(s.get(storageKeys.workspace),{files:[]});assert.equal(s.set(storageKeys.editor,{keymap:'vim'},{version:2}).ok,true);assert.equal(s.get(storageKeys.editor),null);assert.deepEqual(s.get(storageKeys.editor,{version:2}),{keymap:'vim'});assert.throws(()=>s.setItem('unknown','data'),/Unregistered/);values.set(storageKeys.workspace,'broken');assert.equal(s.get(storageKeys.workspace,{fallback:'fallback'}),'fallback');const quota=createStorage({provider:()=>({setItem(){const error=new Error('full');error.name='QuotaExceededError';throw error;}})});const failure=quota.set(storageKeys.workspace,{});assert.equal(failure.ok,false);assert.equal(failure.error.code,'quota');assert.throws(()=>quota.setItem(storageKeys.workspace,'x'),/Could not write/);});
test('every worker message has a handler seam and unknown messages fail structurally',()=>{assert.equal(workerMethods.compiler.length,31);assert.equal(workerMethods.runtime.length,46);for(const kind of ['compiler','runtime']){const protocol=createWorkerProtocol(kind);for(const method of workerMethods[kind])protocol.registerHandler(method,params=>({method,...params}));for(const method of workerMethods[kind])assert.deepEqual(protocol.dispatch(method,{probe:true}),{method,probe:true});assert.throws(()=>protocol.registerHandler(workerMethods[kind][0],()=>{}),/Duplicate/);assert.throws(()=>protocol.dispatch('missing'),e=>e.name==='ProtocolError'&&e.code==='UNKNOWN_METHOD');assert.throws(()=>protocol.dispatch(workerMethods[kind][0],null),/params/);protocol.dispose();assert.throws(()=>protocol.dispatch(workerMethods[kind][0]),/Unknown/);}});
test('Studio has no command branches, direct persistence or inline automation literal',async()=>{const source=await readFile(new URL('../apps/studio/studio.js',import.meta.url),'utf8');assert(!source.includes('switch(command)'));assert(!source.includes('window.sharpforge={'));for(const file of await readdir(new URL('../apps/studio/',import.meta.url)))if(file.endsWith('.js'))assert(!(await readFile(new URL('../apps/studio/'+file,import.meta.url),'utf8')).includes('localStorage.'),file);});

test('real compiler and runtime workers dispatch known requests and return structured unknown errors',async()=>{
  const {Worker}=await import('node:worker_threads');
  for(const [kind,method]of [['compiler','analyze'],['runtime','state']]){
    const url=new URL('../apps/studio/'+kind+'.worker.js',import.meta.url).href;
    const worker=new Worker(`const {parentPort}=require('node:worker_threads');globalThis.self={postMessage:message=>parentPort.postMessage(message)};import(${JSON.stringify(url)}).then(()=>{parentPort.on('message',data=>self.onmessage({data}));parentPort.postMessage({ready:true});}).catch(error=>{throw error;});`,{eval:true});
    const receive=()=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>{cleanup();reject(new Error('Worker response timeout'));},10000);const cleanup=()=>{clearTimeout(timer);worker.off('message',success);worker.off('error',failure);};const success=value=>{cleanup();resolve(value);},failure=error=>{cleanup();reject(error);};worker.once('message',success);worker.once('error',failure);});
    try{assert.deepEqual(await receive(),{ready:true});let result=receive();worker.postMessage({id:1,method,params:{files:[]}});assert.equal((await result).id,1);result=receive();worker.postMessage({id:2,method:'unregistered',params:{}});assert.deepEqual(await result,{id:2,error:{name:'ProtocolError',message:`Unknown ${kind} request 'unregistered'`,code:'UNKNOWN_METHOD'}});result=receive();worker.postMessage({id:3,method:42});assert.equal((await result).error.code,'BAD_REQUEST');}finally{await worker.terminate();}
  }
});
