import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { compileToIL } from '@sharpforge/compiler';
import { readPE } from '@sharpforge/cil';

/** The committed observations are generated by the independent .NET PEReader + runtime oracle. */
test('A03 fresh output headers match native PEReader and matching-host reflection observations', () => {
  const oracle = JSON.parse(readFileSync(new URL('./fixtures/a03-pe/native.json', import.meta.url), 'utf8'));
  for (const expected of oracle.observations) {
    const [platform, outputKind] = expected.name.replace(/\.dll$/, '').split('-');
    if (platform === 'desktop') continue;
    const name = `${platform}-${outputKind}`;
    const compiled = compileToIL(outputKind === 'library' ? 'public class Library {}' : 'Console.WriteLine(42);',
      { platform, name, outputKind: outputKind === 'console' ? 'exe' : outputKind });
    assert(compiled.success, JSON.stringify(compiled.diagnostics));
    const pe = readPE(compiled.assembly);
    assert.equal(pe.machine, expected.machine, name);
    assert.equal(pe.magic, expected.magic, name);
    assert.equal(pe.characteristics, expected.characteristics, name);
    assert.equal(pe.flags, expected.flags, name);
    assert.equal(pe.subsystem, expected.subsystem, name);
    assert.equal(pe.addressOfEntryPoint, expected.entryPoint, name);
    if (expected.execution === 'passed') assert.equal(expected.reflectedMachine, pe.machine);
  }
  assert(oracle.observations.some(item => item.execution === 'passed'));
});
