import test from 'node:test';
import assert from 'node:assert/strict';
import {DirtyRegions} from '../packages/rendering/src/dirty-regions.js';
import {Canvas2DBackend} from '../packages/rendering/src/backends/canvas2d.js';
import {DrawingContext} from '../packages/rendering/src/drawing/context.js';
import {ResourceTable} from '../packages/rendering/src/resources/resource-table.js';
import {describeLayerRaster, hasBackdropDependency} from '../packages/rendering/src/layer-raster-key.js';
import {createRecordingDocument} from './fixtures/rendering/recording-canvas.js';

test('damage clips moved bounds, merges touching rectangles and escalates when backing content is unavailable', () => {
  const damage = new DirtyRegions({width: 100, height: 80, maxRects: 2});
  assert.equal(damage.consume({preservedContents: true}).full, true);
  damage.moved('layer', [-5, 2, 10, 10], [5, 2, 10, 10], 1);
  const moved = damage.consume({preservedContents: true});
  assert.equal(moved.full, false);
  assert.deepEqual(moved.layers.get('layer'), [[0, 1, 16, 12]]);
  damage.add('layer', [0, 0, 80, 70]);
  assert.equal(damage.consume({preservedContents: true}).full, true);
  damage.add('layer', [1, 1, 2, 2]);
  assert.equal(damage.consume().full, true);
  damage.add('layer', [1, 1, 1, 1]);
  damage.add('layer', [10, 10, 1, 1]);
  damage.add('layer', [20, 20, 1, 1]);
  assert.deepEqual(damage.consume({preservedContents: true}).layers.get('layer'), [[1, 1, 20, 20]]);
  assert.throws(() => damage.add('layer', [0, 0, -1, 1]), /nonnegative/);
  assert.throws(() => damage.add('layer', [0, 0, 1, 1], Infinity), /inflation/);
  damage.resize(0, 0);
  assert.equal(damage.consume().fraction, 0);
});

test('Canvas layer cache reuses local content, invalidates resource edits and resets its owned canvases on disposal', async () => {
  const document = createRecordingDocument(), canvas = document.createElement('canvas');
  const resources = new ResourceTable({session: 'canvas-retention'});
  const brush = resources.register('brush', '#ff0000');
  const child = new DrawingContext({elementId: 'child', version: 1}).DrawRectangle([3, 4, 20, 10], brush).finish([3, 4, 20, 10]);
  const layer = {cacheKey: 'child', displayList: child};
  const handle = resources.register('layer', layer);
  const renderer = new Canvas2DBackend(canvas);
  const parent = offset => new DrawingContext().DrawLayer(handle, {transform: [1, 0, 0, 1, offset, 0]}).finish();
  renderer.render(parent(0), resources, {width: 100, height: 100, dpr: 2});
  const initialDraw = canvas.calls.find(call => call.name === 'drawImage');
  const raster = initialDraw.args[0];
  assert.deepEqual([raster.width, raster.height], [40, 20]);
  renderer.render(parent(10), resources, {width: 100, height: 100, dpr: 2});
  assert.equal(canvas.calls.filter(call => call.name === 'drawImage').at(-1).args[0], raster);
  assert.equal(raster.calls.filter(call => call.name === 'fill').length, 1);
  resources.update(brush, '#0000ff');
  assert.equal(raster.width, 0);
  renderer.render(parent(10), resources, {width: 100, height: 100, dpr: 2});
  const replacement = canvas.calls.filter(call => call.name === 'drawImage').at(-1).args[0];
  assert.notEqual(replacement, raster);
  const before = canvas.calls.length;
  renderer.render(parent(10), resources, {width: 100, height: 100, dpr: 2, clear: false, damage: [1, 2, 3, 4]});
  assert.deepEqual(canvas.calls.slice(before).find(call => call.name === 'clearRect').args, [1, 2, 3, 4]);
  assert.equal(canvas.context.stack.length, 0);
  renderer.dispose();
  renderer.dispose();
  assert.equal(replacement.width, 0);
  assert.equal(resources.listeners.size, 0);
  await resources.dispose();
});

test('layer cache keys include transitive resource versions, effect outsets, color policy and DPR', async () => {
  const resources = new ResourceTable({session: 'raster-keys'});
  const color = resources.register('brush', '#ff0000');
  const child = new DrawingContext({elementId: 'child', version: 1}).DrawRectangle([0, 0, 10, 10], color).finish([0, 0, 10, 10]);
  const layer = {cacheKey: 'child', displayList: child, effect: {type: 'GaussianBlur', blurAmount: 2, sources: [{type: 'Source', name: 'Source'}]}};
  const first = describeLayerRaster(layer, resources, {width: 100, height: 100, dpr: 2});
  assert.deepEqual(first.bounds, [-6, -6, 22, 22]);
  assert.deepEqual([first.width, first.height], [44, 44]);
  const moved = describeLayerRaster({...layer, transform: [1, 0, 0, 1, 100, 50], opacity: 0.5}, resources, {width: 100, height: 100, dpr: 2});
  assert.equal(first.version, moved.version);
  assert.equal(first.key, moved.key);
  resources.update(color, '#0000ff');
  assert.notEqual(describeLayerRaster(layer, resources, {width: 100, height: 100, dpr: 2}).version, first.version);
  assert.notEqual(describeLayerRaster(layer, resources, {width: 100, height: 100, dpr: 1}).version, first.version);
  assert.notEqual(describeLayerRaster(layer, resources, {width: 100, height: 100, dpr: 2, blendColorSpace: 'linear'}).version, first.version);
  const backdrop = resources.register('brush', {kind: 'backdrop'});
  const mask = resources.register('brush', {kind: 'mask', source: backdrop});
  assert.equal(hasBackdropDependency({brush: mask}, resources), true);
  assert.throws(() => describeLayerRaster({...layer, bounds: [0, 0, 100000, 1]}, resources, {dpr: 1}), /pixel budget/);
  await resources.dispose();
});
