import test from 'node:test';
import assert from 'node:assert/strict';
import {updateGuideSettings} from '@sharpforge/designer';
import {designerSourceDocument} from '../apps/studio/designer-source-projection.js';
import {studioHarness, ownerUri, constructionUri} from './fixtures/a18-studio-harness.js';

test('Canvas-to-Grid reparent commits the compiled normalized model, source, protocol and atomic history together', async context => {
  const harness = await studioHarness(context);
  const original = harness.file(constructionUri).text.replace('panel.Children.Add(action);', `panel.Children.Add(action);
        Canvas.SetLeft(action, 24);
        Canvas.SetTop(action, 32);
        var target = new Grid();
        panel.Children.Add(target);`);
  harness.type(constructionUri, original);
  await harness.connect();
  updateGuideSettings(harness.document, {gridSize: 14});
  harness.document.change('live attach', document => { document.nodes.find(node => node.id === 'action').runtimeId = 41; });
  harness.document.move('action', 'target');
  assert.equal(harness.document.node('action').properties.Left, 24);
  assert.equal(harness.document.node('action').properties.Top, 32);
  const written = await harness.sync.write();
  assert.equal(written.state, 'synced');
  assert.equal(harness.document.parent('action').id, 'target');
  assert.equal(Object.hasOwn(harness.document.node('action').properties, 'Left'), false);
  assert.equal(Object.hasOwn(harness.document.node('action').properties, 'Top'), false);
  assert.equal(harness.document.node('action').runtimeId, 41);
  assert.equal(harness.document.value.designer.guides.gridSize, 14);
  assert.doesNotMatch(harness.file(constructionUri).text, /Canvas\.Set(?:Left|Top)\(action/);
  assert.match(harness.file(constructionUri).text, /target\.Children\.Add\(action\)/);
  const projected = designerSourceDocument(harness.document.value);
  assert.deepEqual(harness.sync.protocol.document, projected);
  assert.deepEqual(designerSourceDocument(harness.sync.session.analysis.document), projected);
  assert.deepEqual(designerSourceDocument(harness.history.past[0].afterAnalysis.document), projected);
  assert.equal(harness.sync.dirty(), false);
  assert.equal(harness.history.undo(ownerUri), true);
  assert.equal(harness.document.node('action').properties.Left, 24);
  assert.equal(harness.document.parent('action').id, 'panel');
  assert.equal(harness.document.value.designer.guides.gridSize, 14);
  assert.equal(harness.history.undo(ownerUri, true), true);
  assert.equal(harness.document.parent('action').id, 'target');
  assert.equal(Object.hasOwn(harness.document.node('action').properties, 'Left'), false);
  assert.deepEqual(harness.sync.protocol.document, designerSourceDocument(harness.document.value));
  assert.equal(harness.sync.dirty(), false);
});
