import test from 'node:test';
import assert from 'node:assert/strict';
import { createProjectPlan, createItemPlan, searchTemplates, TemplateCatalog, templateAvailability, normalizeTemplateOptions } from '@sharpforge/templates';
import { parseXml, ProjectSystem } from '@sharpforge/project-system';
import noticeTemplate from '../packages/templates/examples/notice-template.mjs';

function elements(node, name) { return [...(node.name === name ? [node] : []), ...node.children.flatMap(child => elements(child, name))]; }

test('One template module registers and generates through an explicit catalog without changing the built-in registry', () => {
  const catalog = new TemplateCatalog();
  catalog.add(noticeTemplate);
  assert.equal(searchTemplates({ catalog, kind: 'item', query: 'example-notice' }).length, 1);
  assert.deepEqual(createItemPlan('example-notice', { catalog, folder: 'docs' }).records,
    [{ path: 'docs/NOTICE.txt', text: 'Generated by a catalog contribution.\n' }]);
  assert.equal(searchTemplates({ kind: 'item', query: 'example-notice' }).length, 0);
  assert.throws(() => catalog.add(noticeTemplate), /already installed/);
});

test('Template catalog has native distinctions and deterministic SDK test project packages', () => {
  for (const id of ['xunit', 'nunit', 'mstest']) {
    const template = searchTemplates({ query: id }).find(template => template.id === id);
    assert.equal(template.nativeOnly, true);
    assert.equal(templateAvailability(template, { native: false }).available, false);
    const plan = createProjectPlan(id, { projectName: 'Tests' });
    const project = parseXml(plan.records.find(record => record.path.endsWith('.csproj')).text);
    assert.equal(elements(project, 'IsTestProject')[0].text, 'true');
    assert.equal(elements(project, 'PackageReference').length, 3);
    assert(plan.records.some(record => /AdditionReturnsExpectedValue/.test(record.text ?? '')));
    assert(plan.diagnostics.some(diagnostic => diagnostic.code === 'SFTPL_TARGET'));
  }
});

test('Windows App SDK template catalog creates manifests, XAML and correctly dimensioned PNGs', () => {
  for (const id of ['winui-native-unpackaged', 'winui-native-packaged', 'winui-native-library', 'winui-native-tests']) {
    const template = searchTemplates({ query: id }).find(template => template.id === id);
    assert.equal(templateAvailability(template, { native: true, platform: 'linux' }).available, false);
    const plan = createProjectPlan(id, { projectName: 'NativeApp' });
    for (const record of plan.records.filter(record => /\.(xaml|manifest|appxmanifest|csproj)$/.test(record.path))) parseXml(record.text);
    assert(plan.records.some(record => record.text?.includes('Microsoft.WindowsAppSDK')));
    if (id === 'winui-native-packaged') {
      const png = plan.records.find(record => record.path.endsWith('Square150x150Logo.png')).bytes;
      assert.equal(new DataView(png.buffer).getUint32(16), 150);
      assert.equal(new DataView(png.buffer).getUint32(20), 150);
    }
  }
});

test('Template options create top-level code, nullable metadata, namespace style and classic solution', () => {
  const plan = createProjectPlan('console', { projectName: 'Options', 'use-program-main': false, nullable: 'enable',
    implicitUsings: true, noRestore: false, solutionFormat: 'sln' });
  const source = plan.records.find(record => record.path.endsWith('Program.cs')).text;
  assert.equal(source, 'Console.WriteLine("Hello, world!");\n');
  assert(plan.records.find(record => record.path.endsWith('.csproj')).text.includes('<Nullable>enable</Nullable>'));
  assert.equal(plan.postActions[0].kind, 'restore');
  assert(plan.entry.endsWith('.sln'));
  const system = new ProjectSystem(plan.records);
  assert.equal(system.load(plan.entry).projects.length, 1);
  const item = createItemPlan('interface', { name: 'IWorker', namespace: 'Example.App', namespaceStyle: 'file-scoped', nullable: true });
  assert(item.records[0].text.includes('namespace Example.App;'));
  assert(item.records[0].text.includes('#nullable enable'));
  for (const input of [{ framework: 'bad' }, { nullable: 'sometimes' }, { useProgramMain: 'false' }, { noRestore: 0 }]) {
    assert.throws(() => normalizeTemplateOptions(input), error => error.code === 'SFTPL002');
  }
});

test('Configuration files and core C# items preserve options and strict path validation', () => {
  for (const id of ['global-json', 'nuget-config', 'gitignore-dotnet', 'gitattributes', 'central-packages', 'dotnet-tools', 'launch-settings', 'app-manifest', 'appsettings']) {
    const plan = createItemPlan(id);
    const record = plan.records[0];
    assert.equal(typeof record.text, 'string');
    if (record.path.endsWith('.json')) JSON.parse(record.text);
    if (/\.(config|props|manifest)$/.test(record.path) && record.path !== '.editorconfig') parseXml(record.text);
  }
  assert.equal(createItemPlan('dotnet-tools').records[0].path, '.config/dotnet-tools.json');
  assert.equal(createItemPlan('launch-settings').records[0].path, 'Properties/launchSettings.json');
  for (const id of ['interface', 'record', 'struct', 'enum', 'delegate', 'exception', 'attribute', 'extension-methods']) {
    const plan = createItemPlan(id, { namespaceStyle: 'file-scoped' });
    assert(plan.records[0].text.includes('namespace Application;'));
  }
  assert.throws(() => createItemPlan('global-json', { sdkVersion: 'injected' }), /SDK version/);
  assert.throws(() => createItemPlan('interface', { name: '../escape' }));
  const cancelled = new AbortController();
  cancelled.abort();
  assert.throws(() => createProjectPlan('console', { signal: cancelled.signal }), { name: 'AbortError' });
  const catalog = new TemplateCatalog();
  assert.throws(() => catalog.add(catalog.get('console')), /already installed/);
});
