import test from 'node:test';
import assert from 'node:assert/strict';
import { deflateSync, inflateSync, constants } from 'node:zlib';
import { deflateZlib, inflateZlib, inflateZlibSync, adler32, MAX_INFLATED_BYTES } from '../packages/git/src/zlib.js';

const bytes = value => new TextEncoder().encode(value);

test('portable zlib reads stored, fixed and dynamic streams generated by reference zlib', async () => {
  const payloads = [new Uint8Array(), bytes('hello\0hello'), bytes('compressible data '.repeat(6000)),
    Uint8Array.from({ length: 100_003 }, (_, index) => index * 41 + (index >> 7) & 255)];
  for (const payload of payloads) {
    for (const options of [{ level: 0 }, { strategy: constants.Z_FIXED }, { level: 9 }]) {
      const compressed = new Uint8Array(deflateSync(payload, options));
      const result = inflateZlibSync(compressed);
      assert.deepEqual(result.data, payload);
      assert.equal(result.bytesRead, compressed.length);
      assert.deepEqual(await inflateZlib(compressed, { backend: 'portable' }), payload);
    }
  }
});

test('real portable compression round-trips with native zlib and saves repeated data', async () => {
  const data = bytes('abcdef0123456789'.repeat(8192));
  const encoded = await deflateZlib(data, { backend: 'portable' });
  assert.ok(encoded.length < data.length / 10);
  assert.deepEqual(new Uint8Array(inflateSync(encoded)), data);
  assert.deepEqual(inflateZlibSync(encoded).data, data);
  assert.deepEqual(await inflateZlib(await deflateZlib(data)), data);
});

test('pack entry inflation reports exact consumption and distinguishes truncation from corruption', () => {
  const first = deflateSync(bytes('first'));
  const second = deflateSync(bytes('second'));
  const joined = new Uint8Array(Buffer.concat([first, second]));
  assert.equal(inflateZlibSync(joined, { allowTrailing: true }).bytesRead, first.length);
  assert.throws(() => inflateZlibSync(joined), { code: 'Corrupt' });
  for (let length = 0; length < first.length; length++) {
    assert.throws(() => inflateZlibSync(first.subarray(0, length)),
      error => error.code === 'Corrupt' && error.details.truncated === true, `prefix ${length}`);
  }
  const corrupt = new Uint8Array(first);
  corrupt[corrupt.length - 1] ^= 1;
  assert.throws(() => inflateZlibSync(corrupt), error => error.code === 'Corrupt' && !error.details.truncated);
});

test('both backends enforce output, input, block and cancellation bounds', async () => {
  const compressed = deflateSync(bytes('x'.repeat(100_000)));
  for (const backend of ['portable', 'auto']) {
    await assert.rejects(inflateZlib(compressed, { backend, maxOutputBytes: 99_999 }), { code: 'Limit' });
    await assert.rejects(inflateZlib(compressed, { backend, maxInputBytes: 1 }), { code: 'Limit' });
    await assert.rejects(deflateZlib(bytes('hello'), { backend, maxOutputBytes: 1 }), { code: 'Limit' });
    await assert.rejects(inflateZlib(compressed, { backend, signal: AbortSignal.abort() }), { code: 'Cancelled' });
  }
  assert.throws(() => inflateZlibSync(compressed, { maxBlocks: 0 }), { code: 'Limit' });
  assert.throws(() => inflateZlibSync(compressed, { maxOutputBytes: MAX_INFLATED_BYTES + 1 }), { code: 'Limit' });
  assert.throws(() => inflateZlibSync(new Uint8Array([0x78, 0x01, 7, 0, 0, 0, 1])), { code: 'Corrupt' });
  assert.throws(() => inflateZlibSync(new Uint8Array([0x78, 0x20])), { code: 'Unsupported' });
});

test('Adler-32 matches standard vectors and incremental checksum continuation', () => {
  assert.equal(adler32(new Uint8Array()), 1);
  assert.equal(adler32(bytes('Wikipedia')), 0x11e60398);
  assert.equal(adler32(bytes('pedia'), adler32(bytes('Wiki'))), adler32(bytes('Wikipedia')));
});
