import test from 'node:test';import assert from 'node:assert/strict';
import {AnimationClock,easing,prepareTimeline,timelinePosition} from '@sharpforge/framework';
import {compileToIL} from '@sharpforge/compiler';import {VirtualMachine,CilVirtualMachine} from '@sharpforge/runtime';import {loadAssembly,formatILDocument,assembleILDocument} from '@sharpforge/cil';
const prefix='using System;using Microsoft.UI.Xaml;using Microsoft.UI.Xaml.Controls;using Microsoft.UI.Xaml.Media;using Microsoft.UI.Xaml.Media.Animation;';
const setup='var b=new Button(){Opacity=0.7};var a=new DoubleAnimation(){From=0,To=1,Duration=new Duration(TimeSpan.FromSeconds(1))};Storyboard.SetTarget(a,b);Storyboard.SetTargetProperty(a,"Opacity");var s=new Storyboard();s.Children.Add(a);';
const advance=t=>`SharpForge.UI.AnimationClock.AdvanceBy(${t});`;
const cases=[
 ['sampling and Stop restore changed base',setup+'s.Begin();Console.WriteLine(b.Opacity);'+advance(500)+'Console.WriteLine(b.Opacity);b.Opacity=0.8;Console.WriteLine(b.Opacity);Console.WriteLine(b.ReadLocalValue(Button.OpacityProperty));s.Stop();Console.WriteLine(b.Opacity);','0\n0.5\n0.5\n0.8\n0.8\n'],
 ['deferred BeginTime runs before first active frame',setup+'a.BeginTime=TimeSpan.FromMilliseconds(200);s.Begin();Console.WriteLine(b.Opacity);'+advance(700)+'Console.WriteLine(b.Opacity);Console.WriteLine(s.GetCurrentTime().TotalMilliseconds);','0.7\n0.5\n700\n'],
 ['pause resume and seek',setup+'s.Begin();'+advance(250)+'s.Pause();'+advance(200)+'Console.WriteLine(b.Opacity);s.Resume();'+advance(250)+'Console.WriteLine(b.Opacity);s.Seek(TimeSpan.FromMilliseconds(800));Console.WriteLine(b.Opacity);s.SkipToFill();Console.WriteLine(b.Opacity);','0.25\n0.5\n0.8\n1\n'],
 ['zero duration fills immediately',setup+'a.Duration=new Duration(TimeSpan.Zero);s.Begin();Console.WriteLine(b.Opacity);s.Stop();Console.WriteLine(b.Opacity);','1\n0.7\n'],
 ['repeat and auto reverse',setup+'a.AutoReverse=true;a.RepeatBehavior=new RepeatBehavior(2);s.Begin();'+advance(1250)+'Console.WriteLine(b.Opacity);'+advance(1250)+'Console.WriteLine(b.Opacity);s.SkipToFill();Console.WriteLine(b.Opacity);','0.75\n0.5\n0\n'],
 ['stop fill restores unmodified local',setup+'a.FillBehavior=FillBehavior.Stop;s.Begin();'+advance(1000)+'Console.WriteLine(b.Opacity);Console.WriteLine(s.GetCurrentState()==ClockState.Filling);','0.7\nTrue\n'],
 ['nested storyboard speed and offset',setup+'var parent=new Storyboard(){SpeedRatio=2};s.BeginTime=TimeSpan.FromMilliseconds(100);parent.Children.Add(s);parent.Begin();'+advance(300)+'Console.WriteLine(b.Opacity);','0.5\n'],
 ['quadratic ease in',setup+'a.EasingFunction=new QuadraticEase(){EasingMode=EasingMode.EaseIn};s.Begin();'+advance(500)+'Console.WriteLine(b.Opacity);','0.25\n'],
 ['transform target path',setup+'b.RenderTransform=new TranslateTransform();Storyboard.SetTargetProperty(a,"(UIElement.RenderTransform).(TranslateTransform.X)");a.To=80;s.Begin();'+advance(500)+'Console.WriteLine(b.RenderTransform.GetValue(TranslateTransform.XProperty));','40\n'],
 ['attached canvas target',setup+'Canvas.SetLeft(b,10);Storyboard.SetTargetProperty(a,"(Canvas.Left)");a.To=80;s.Begin();'+advance(500)+'Console.WriteLine(Canvas.GetLeft(b));Canvas.SetLeft(b,20);s.Stop();Console.WriteLine(Canvas.GetLeft(b));','40\n20\n'],
 ['name binding requires unique live target',setup+'var w=new Window();b.Name="target";w.Content=b;w.Activate();Storyboard.SetTarget(a,null);Storyboard.SetTargetName(a,"target");s.Begin();'+advance(250)+'Console.WriteLine(b.Opacity);','0.25\n'],
 ['based-on style mutation while animated restores latest base',setup+'var style=new Style("Button");var setter=new Setter(Button.OpacityProperty,0.4);style.Setters.Add(setter);b.ClearValue(Button.OpacityProperty);b.Style=style;s.Begin();'+advance(500)+'setter.Value=0.6;Console.WriteLine(b.Opacity);s.Stop();Console.WriteLine(b.Opacity);','0.5\n0.6\n'],
 ['garbage collection keeps active timelines/targets',setup+'s.Begin();GC.Collect();'+advance(500)+'Console.WriteLine(b.Opacity);s.Stop();','0.5\n'],
 ['invalid target does not replace running animation',setup+'s.Begin();'+advance(250)+'Storyboard.SetTargetProperty(a,"NotAProperty");try{s.Begin();}catch(Exception e){Console.WriteLine("rejected");}'+advance(250)+'Console.WriteLine(b.Opacity);','rejected\n0.5\n'],
 ['wrap panel contracts and attached spans','var grid=new VariableSizedWrapGrid(){ItemWidth=120,ItemHeight=40,MaximumRowsOrColumns=3,Orientation=Orientation.Horizontal};var b=new Button();VariableSizedWrapGrid.SetColumnSpan(b,2);Grid.SetColumnSpan(b,3);grid.Children.Add(b);Console.WriteLine(VariableSizedWrapGrid.GetColumnSpan(b));Console.WriteLine(Grid.GetColumnSpan(b));Console.WriteLine(grid.Children.Count);','2\n3\n1\n'],
];
const factories={source:c=>new VirtualMachine(c.image),reload:c=>new VirtualMachine(loadAssembly(c.assembly)),cil:c=>new CilVirtualMachine(c.assembly),reassembled:c=>new CilVirtualMachine(assembleILDocument(formatILDocument(c.assembly)).bytes)};
for(const [name,body,expected]of cases){const c=compileToIL(prefix+body);for(const [path,make]of Object.entries(factories))test(`Animation ${path}: ${name}`,()=>{assert(c.success,JSON.stringify(c.diagnostics));const vm=make(c),r=vm.run();assert.equal(r.state,'terminated',JSON.stringify(r.fault));assert.equal(r.output,expected);});}
function clock(){const values=new Map([['x',4],['y',0]]),events=[];const c=new AnimationClock({key:x=>x,read:(id,k)=>values.get(k),write:(id,k,v)=>values.set(k,v),validate:(id,k)=>{assert(values.has(k));},completed:x=>events.push(x)});return {c,values,events};}
test('AnimationClock pending root BeginTime still drives the clock',()=>{const {c,values}=clock();c.begin('s',{id:'s',target:'o',property:'x',begin:200,duration:1000,from:0,to:100});assert.equal(c.running,true);c.advance(700);assert.equal(values.get('x'),50);});
test('AnimationClock snapshot restores all clocks, bases and completion state',()=>{const {c,values,events}=clock();c.begin('s',{id:'s',target:'o',property:'x',duration:1000,from:0,to:100});c.advance(200);const snap=c.snapshot();c.advance(800);assert.equal(values.get('x'),100);assert.deepEqual(events,['s']);c.restore(snap);c.apply();assert.equal(values.get('x'),20);c.advance(800);assert.deepEqual(events,['s','s']);});
test('AnimationClock latest storyboard takes precedence; stopping reveals earlier clock then base',()=>{const {c,values}=clock();c.begin('a',{id:'a',target:'o',property:'x',duration:1000,from:0,to:100});c.advance(200);c.begin('b',{id:'b',target:'o',property:'x',duration:1000,from:50,to:150});c.advance(200);assert.equal(values.get('x'),70);c.stop('b');assert.equal(values.get('x'),40);c.stop('a');assert.equal(values.get('x'),4);});
test('AnimationClock Begin validation leaves previous state untouched',()=>{const {c,values}=clock();c.begin('s',{id:'s',target:'o',property:'x',from:0,to:10});const snapshot=c.snapshot();assert.throws(()=>c.begin('s',{id:'s',target:'o',property:'missing'}));assert.deepEqual(c.snapshot(),snapshot);assert.equal(values.get('x'),0);});
test('AnimationClock rejects cycles, huge trees, and invalid speed',()=>{const read=()=>0,validate=()=>{};for(const def of [{id:'a',speed:0},{id:'a',children:[{id:'a'}]},{id:'a',duration:-1},{id:'a',target:'o',property:'x',to:Infinity}])assert.throws(()=>prepareTimeline(def,read,validate));});
test('AnimationClock repeat-duration and fractional repeats keep correct final value',()=>{const {c,values}=clock();c.begin('s',{id:'s',target:'o',property:'x',duration:1000,repeat:1.25,from:0,to:100});c.skipToFill('s');assert.equal(values.get('x'),25);c.begin('s',{id:'s',target:'o',property:'x',duration:1000,repeatDuration:1250,from:0,to:100});c.skipToFill('s');assert.equal(values.get('x'),25);});
test('Easing symmetry and endpoints across all supported families', () => {
  const families = ['QuadraticEase', 'CubicEase', 'QuarticEase', 'QuinticEase', 'SineEase', 'CircleEase',
    'PowerEase', 'BackEase', 'BounceEase', 'ElasticEase', 'ExponentialEase'];
  for (const kind of families) for (const mode of [0, 1, 2]) {
    assert.equal(easing(0, {kind, mode}), 0);
    assert.equal(easing(1, {kind, mode}), 1);
    assert(Math.abs(easing(.5, {kind, mode: 2}) - .5) < 1e-12);
  }
});
