import test from 'node:test';import assert from 'node:assert/strict';
import {compileToIL} from '@sharpforge/compiler';
import {VirtualMachine,CilVirtualMachine} from '@sharpforge/runtime';
import {loadAssembly,formatILDocument,assembleILDocument} from '@sharpforge/cil';
const paths={source:c=>new VirtualMachine(c.image,{initialThreshold:64}),reload:c=>new VirtualMachine(loadAssembly(c.assembly),{initialThreshold:64}),cil:c=>new CilVirtualMachine(c.assembly,{initialThreshold:64}),reassembled:c=>new CilVirtualMachine(assembleILDocument(formatILDocument(c.assembly)).bytes,{initialThreshold:64})};
const cases=[
 ['list initializer, index update and foreach','var a=new List<int>(){3,1,2};a[1]+=9;foreach(var n in a)Console.WriteLine(n);','3\n10\n2\n'],
 ['indexer receiver and key evaluate once','class P {static int calls;static Dictionary<string,int> d;static Dictionary<string,int> Get(){calls++;return d;}static string Key(){calls++;return "a";}static void Main(){d=new Dictionary<string,int>(){{"a",4}};Get()[Key()]+=3;Console.WriteLine(calls);Console.WriteLine(d["a"]);}}','2\n7\n'],
 ['collection foreach break and continue','var a=new List<int>(){1,2,3,4};foreach(var n in a){if(n==2)continue;if(n==4)break;Console.WriteLine(n);}Console.WriteLine(a.Count);','1\n3\n4\n'],
 ['versioned iterator mutation throws with cleanup','var a=new List<int>(){1,2};try{foreach(var n in a){a.Add(3);}}catch(Exception e){Console.WriteLine("changed");}Console.WriteLine(a.Count);','changed\n3\n'],
 ['dictionary key equality, duplicate, remove and snapshots','var d=new Dictionary<string,int>(){{"answer",42}};Console.WriteLine(d["ans"+"wer"]);Console.WriteLine(d.TryAdd("answer",8));d["other"]=2;Console.WriteLine(d.Keys.Length);Console.WriteLine(d.Remove("other"));try{d.Add("answer",5);}catch(Exception e){Console.WriteLine("duplicate");}Console.WriteLine(d.Count);','42\nFalse\n2\nTrue\nduplicate\n1\n'],
 ['dictionary null and missing reject','var d=new Dictionary<string,string>();try{d.Add(null,"v");}catch(Exception e){Console.WriteLine("null");}try{Console.WriteLine(d["missing"]);}catch(Exception e){Console.WriteLine("missing");}','null\nmissing\n'],
 ['list copy is independent, insert/remove/reverse/sort','var a=new List<int>(new int[]{3,1,2});var b=a.ToArray();a.Sort();a.Insert(1,8);a.RemoveAt(0);a.Reverse();Console.WriteLine(string.Join(",",a.ToArray()));Console.WriteLine(b[0]);','3,2,8\n3\n'],
 ['list range/capacity transactional failure','var a=new List<int>(){1,2};a.AddRange(new int[]{3,4});a.RemoveRange(1,2);a.Capacity=8;try{a.Capacity=1;}catch(Exception e){Console.WriteLine("range");}Console.WriteLine(a.Count);Console.WriteLine(a.Capacity);','range\n2\n8\n'],
 ['HashSet set operations','var s=new HashSet<int>(new int[]{1,1,2});Console.WriteLine(s.Count);Console.WriteLine(s.Add(2));s.UnionWith(new int[]{2,3});s.ExceptWith(new int[]{1});s.IntersectWith(new int[]{3});Console.WriteLine(s.Contains(3));Console.WriteLine(s.Count);','2\nFalse\nTrue\n1\n'],
 ['queue stack order and empty error','var q=new Queue<string>(new string[]{"a","b"});q.Enqueue("c");Console.WriteLine(q.Dequeue());Console.WriteLine(q.Peek());var s=new Stack<int>(new int[]{1,2,3});foreach(var v in s)Console.WriteLine(v);s.Clear();try{s.Pop();}catch(Exception e){Console.WriteLine("empty");}','a\nb\n3\n2\n1\nempty\n'],
 ['boxed list roots retain custom objects through GC','class Box{public int Value;}class P{static void Main(){var a=new List<object>();a.Add(new Box(){Value=42});GC.Collect();Console.WriteLine(a[0]!=null);}}','True\n'],
 ['string dictionary heap roots survive collection','var d=new Dictionary<string,string>();for(int i=0;i<60;i++){d[$"k{i}"]=$"value{i}";}GC.Collect();Console.WriteLine(d["k42"]);Console.WriteLine(d.Count);','value42\n60\n'],
 ['StringBuilder chunk append length and range','var b=new StringBuilder("abc");b.Append(42).Append(true).AppendLine();Console.WriteLine(b.Length);Console.WriteLine(b.ToString(0,5));b.Remove(0,3).Insert(0,"n=").Replace("42","8");Console.WriteLine(b.ToString());b.Clear();Console.WriteLine(b.Length);','10\nabc42\nn=8True\n\n0\n'],
 ['StringBuilder repeated append and GC','var b=new StringBuilder(4);for(int i=0;i<200;i++){b.Append("x");}GC.Collect();Console.WriteLine(b.Length);Console.WriteLine(b.ToString().Length);','200\n200\n'],
 ['StringBuilder formatting and capacity bounds','var b=new StringBuilder();b.AppendFormat("{0:D4} {1:F1}",42,2.25);Console.WriteLine(b.ToString());b.Length=3;Console.WriteLine(b.ToString());try{b.Capacity=1;}catch(Exception e){Console.WriteLine("capacity");}','0042 2.2\n004\ncapacity\n'],
 ['string ordinal editing and null helpers','string s="  Alpha,beta  ";Console.WriteLine(s.Trim().ToUpperInvariant());Console.WriteLine(s.Contains("Alpha"));Console.WriteLine(s.IndexOf("beta"));Console.WriteLine(s.Trim().Replace("Alpha","A").Split(",")[1]);Console.WriteLine(string.IsNullOrWhiteSpace(null));Console.WriteLine(string.IsNullOrWhiteSpace(" \t"));','ALPHA,BETA\nTrue\n8\nbeta\nTrue\nTrue\n'],
 ['string bounds and split remainder','Console.WriteLine("a,b,c".Split(",",2)[1]);Console.WriteLine("abc".Substring(1,2));Console.WriteLine("abc".Insert(1,"!").Remove(2,1));try{"a".Substring(2);}catch(Exception e){Console.WriteLine("bounds");}','b,c\nbc\na!c\nbounds\n'],
 ['interpolation evaluated once, alignment and braces','int i=1;Console.WriteLine($"{{{i++,4:D3}}}:{i++}:{true}:{3.125:F2}");Console.WriteLine(i);','{ 001}:2:True:3.12\n3\n'],
 ['verbatim interpolation escapes and nested calls','Console.WriteLine($@"path\\{string.Join(",",new string[]{"a","b"})} ""ok""");','path\\a,b "ok"\n'],
 ['interpolation selected expression and braces in string','int x=3;Console.WriteLine($"{(x>0 ? "}" : "{")}:{x,-4}:{x:X4}");','}:3   :0003\n'],
 ['composite formatting null and literal braces','Console.WriteLine(string.Format("{{{0:D3}}} {1} {2,-4}",7,null,"x"));','{007}  x   \n'],
 ['extra Math contracts coexist with old builtins','Console.WriteLine(Math.Clamp(12,0,10));Console.WriteLine(Math.Sin(0));Console.WriteLine(Math.Sqrt(9));Console.WriteLine(Math.Truncate(3.9));','10\n0\n3\n3\n']
];
for(const [name,body,expected]of cases){const c=compileToIL('using System;using System.Collections.Generic;using System.Text;'+body);for(const [kind,make]of Object.entries(paths))test(`BCL ${kind}: ${name}`,()=>{assert(c.success,JSON.stringify(c.diagnostics));const vm=make(c),r=vm.run();assert.equal(r.state,'terminated',JSON.stringify(r.fault));assert.equal(r.output,expected);});}
for(const source of ['foreach(var n in new List<int>(){1}){n=2;}','var a=new List<int>();a.Add("x");','var d=new Dictionary<string,int>();d[1]=2;','var a=new List<P>();','Console.WriteLine($"{1,variable}");','Console.WriteLine($"{1");'])test('C# rejects invalid collection/interpolation: '+source,()=>assert.equal(compileToIL(source).success,false));
