import {sampleSources} from './sample-sources.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import { compile } from '@sharpforge/compiler';
import { VirtualMachine } from '@sharpforge/runtime';
import { DebugSession } from '@sharpforge/debugger';
import { emitAssembly, emitAssemblyDetailed, loadAssembly, readPE, readSignature, decodeInstructions, Writer, Reader, equalBytes } from '@sharpforge/cil';
import { cilExecutionCases } from './cil-fixtures.js';
import { samples } from '../apps/studio/samples.js';
const create=(source,options)=>{const r=compile(source,options);assert(r.success,JSON.stringify(r.diagnostics));return r.image;};
for(const [name,source,expected]of cilExecutionCases)test('CIL execution: '+name,()=>{const original=create(source),bytes=emitAssembly(original),decoded=loadAssembly(bytes),vm=new VirtualMachine(decoded),result=vm.run();assert.equal(result.state,'terminated',result.fault?.stack);assert.equal(result.output,expected);assert.equal(result.stats.instructions,new VirtualMachine(original).run().stats.instructions);});
for(const sample of samples.filter(s=>s.id!=='errors'))test('CIL sample: '+sample.id,async()=>{const original=create(sampleSources(sample),sample.compilationOptions),decoded=loadAssembly(emitAssembly(original));assert.equal((await new VirtualMachine(decoded,{virtualTime:true}).runAsync()).output,(await new VirtualMachine(original,{virtualTime:true}).runAsync()).output);});
test('CIL: emitted bytes contain real PE/CLI headers and real opcodes',()=>{const bytes=emitAssembly(create('Console.WriteLine(42);')),pe=readPE(bytes);assert.equal(bytes[0],77);assert.equal(bytes[1],90);assert.equal(pe.metadata.version,'v4.0.30319');assert.equal(pe.entryPoint>>>24,6);const debug=JSON.parse(new TextDecoder().decode(pe.metadata.streams.get('#SF'))),code=decodeInstructions(pe.methodBody(debug.methods[0].token).code);assert(code.some(i=>i.name==='ldc.i4'&&i.operand===42));assert(code.some(i=>i.name==='call'&&i.operand>>>24===10));assert(!Object.hasOwn(debug.methods[0],'code'));assert(!JSON.stringify(debug).includes('$int32'));assert(!Object.hasOwn(debug,'constants'));});
test('CIL: deterministic full artifact',()=>{const im=create('Console.WriteLine("Hello");');assert.deepEqual(emitAssembly(im),emitAssembly(im));});
test('CIL: code is decoded from IL, not from embedded source',()=>{const im=create('Console.WriteLine(42);');im.sources[0].text='this is deliberately not C#';im.constants[im.constants.indexOf(42)]=99;assert.equal(new VirtualMachine(loadAssembly(emitAssembly(im))).run().output,'99\n');});
test('CIL: int Main entry signature and result are preserved',()=>{const im=loadAssembly(emitAssembly(create('class P{static int Main(){return 7;}}')));assert.equal(im.methods[im.entryPoint].returnType,'int');assert.equal(new VirtualMachine(im).run().exitCode,7);});
test('CIL: typed literal 7.0 remains ldc.r8 instead of ldc.i4',()=>{const result=emitAssemblyDetailed(create('Console.WriteLine(7.0/2);'));const pe=readPE(result.bytes),code=decodeInstructions(pe.methodBody(result.debug.methods[0].token).code);assert(code.some(i=>i.name==='ldc.r8'&&i.operand===7));assert.equal(new VirtualMachine(loadAssembly(result.bytes)).run().output,'3.5\n');});
for(const [name,source,expected]of [
 ['mixed numeric conditional','double d=true?1:2.5;Console.WriteLine(d/2);','0.5\n'],
 ['typed assignment expression','double d=0;Console.WriteLine((d=7)/2);','3.5\n'],
 ['double method arguments','double F(double a,double b){return a/b;}Console.WriteLine(F(7,2));','3.5\n'],
 ['return in protected region','int F(){try{return 7;}catch(Exception e){return 9;}}Console.WriteLine(F());','7\n'],
 ['void return in catch','void F(){try{throw new Exception("x");}catch(Exception e){Console.WriteLine("ok");return;}}F();','ok\n'],
 ['break crossing protected region','int n=0;while(true){try{n++;break;}catch(Exception e){}}Console.WriteLine(n);','1\n'],
 ['continue crossing protected region','int n=0;for(int i=0;i<4;i++){try{n++;continue;}catch(Exception e){}}Console.WriteLine(n);','4\n'],
 ['empty string and Unicode','Console.WriteLine("");Console.WriteLine("🧬 Łódź");','\n🧬 Łódź\n'],
 ['all boolean operations','Console.WriteLine(true & false);Console.WriteLine(true ^ false);Console.WriteLine(true==false);','False\nTrue\nFalse\n'],
 ['string mixed concat','Console.WriteLine("value="+42+", flag="+true);','value=42, flag=True\n'],
 ['floating NaN comparisons','double n=Math.Sqrt(-1);Console.WriteLine(n<=1);Console.WriteLine(n>=1);','False\nFalse\n']
])test('CIL regression: '+name,()=>{const im=create(source);assert.equal(new VirtualMachine(loadAssembly(emitAssembly(im))).run().output,expected);});
test('CIL: emit native-only assembly without debug stream',()=>{const bytes=emitAssembly(create('Console.WriteLine(42);'),{includeDebug:false});assert(!readPE(bytes).metadata.streams.has('#SF'));assert.throws(()=>loadAssembly(bytes),/arbitrary .NET assembly/);});
test('CIL: source-free profile is still executable and debuggable',()=>{const im=loadAssembly(emitAssembly(create('Console.WriteLine(42);'),{embedSources:false}));assert.equal(im.sources[0].text,undefined);assert.equal(new VirtualMachine(im).run().output,'42\n');});
test('CIL: CLR-compatible constructor wrappers and raw allocator have distinct signatures',()=>{const e=emitAssemblyDetailed(create('var c=new C(42);Console.WriteLine(c.X);class C{public int X;public C(int x){X=x;}}'));const pe=readPE(e.bytes),md=pe.metadata,ctors=md.rows[6].filter(r=>md.string(r[3])==='.ctor').map(r=>readSignature(md.blob(r[4]),md));assert(ctors.some(s=>s.parameters[0]==='int'));assert(ctors.some(s=>s.parameters[0]==='SharpForge.<>AllocationToken'));});
test('CIL: catch regions carry real CLI exception metadata',()=>{const e=emitAssemblyDetailed(create('try{throw new Exception("x");}catch(Exception e){Console.WriteLine(e.Message);}'));const pe=readPE(e.bytes),body=pe.methodBody(e.debug.methods[0].token);assert.equal(body.handlers.length,1);assert.equal(pe.metadata.typeName(body.handlers[0].catchType),'System.Exception');assert(decodeInstructions(body.code).some(i=>i.name==='leave'));});
test('CIL: source stepping, watches and reverse snapshots survive IL predecoding',()=>{const source='int total=1;\ntotal+=2;\nConsole.WriteLine(total);',image=loadAssembly(emitAssembly(create(source))),debug=new DebugSession(image,{recordHistory:true});debug.start(true);debug.pump();assert.equal(debug.vm.state,'paused');assert.equal(debug.vm.currentPoint.line,1);debug.resume('next');debug.pump();assert.equal(debug.vm.currentPoint.line,2);assert.equal(debug.evaluate('total').value,1);debug.resume('next');debug.pump();assert.equal(debug.evaluate('total').value,3);debug.stepBack();assert.equal(debug.evaluate('total').value,1);assert(Number.isInteger(debug.vm.currentPoint.ilOffset));assert.equal(debug.stackTrace()[0].ilOffset,debug.vm.currentPoint.ilOffset);});
test('CIL: invalid headers and every truncated prefix are rejected',()=>{const bytes=emitAssembly(create('Console.WriteLine(42);'));for(const length of [0,1,2,63,127,255,511,bytes.length-1])assert.throws(()=>loadAssembly(bytes.subarray(0,length)));const bad=bytes.slice();bad[0]=0;assert.throws(()=>loadAssembly(bad));});
test('CIL: modified CIL instruction is rejected before execution',()=>{const e=emitAssemblyDetailed(create('Console.WriteLine(42);')),bytes=e.bytes.slice(),pe=readPE(bytes),body=pe.methodBody(e.debug.methods[0].token),instruction=decodeInstructions(body.code).find(i=>i.name==='ldc.i4');bytes[body.fileOffset+body.headerSize+instruction.offset+1]=43;assert.throws(()=>loadAssembly(bytes),/canonical/);});
test('CIL: unsupported opcode is rejected, not silently interpreted',()=>{const e=emitAssemblyDetailed(create('Console.WriteLine(42);')),bytes=e.bytes.slice(),pe=readPE(bytes),body=pe.methodBody(e.debug.methods[0].token);bytes[body.fileOffset+body.headerSize]=0x29;assert.throws(()=>loadAssembly(bytes),/Unsupported CIL opcode/);});
test('CIL: compressed unsigned integer boundaries roundtrip',()=>{for(const value of [0,127,128,16383,16384,0x1fffffff]){const w=new Writer().compressed(value);assert.equal(new Reader(w.finish()).compressed(),value);}assert.throws(()=>new Writer().compressed(-1));assert.throws(()=>new Reader(new Uint8Array([255])).compressed());});

import { compileToIL } from '@sharpforge/compiler';
import { MetadataBuilder, disassembleAssembly, formatAssembly, createRuntimeConfig, readMetadata } from '@sharpforge/cil';
import { Workspace } from '@sharpforge/workspace';
import { clrExecutionCases } from './clr-fixtures.js';
for(const [name,source,expected]of clrExecutionCases)test('CIL/CLR semantic fixture: '+name,()=>{const built=compileToIL(source);assert(built.success,JSON.stringify(built.diagnostics));const vm=new VirtualMachine(built.assembly),run=vm.run();assert.equal(run.state,'terminated',run.fault?.stack);assert.equal(run.exitCode,expected);assert.equal(run.stats.artifactFormat,'ECMA-335');assert.equal(run.stats.instructions,new VirtualMachine(built.image).run().stats.instructions);});
test('CIL API: errors block binary emission',()=>{const r=compileToIL('int x="wrong";');assert.equal(r.success,false);assert.equal(r.assembly,null);assert(r.diagnostics.some(d=>d.code==='CS0029'));});
test('CIL API: backend errors become diagnostics',()=>{const r=compileToIL('Console.WriteLine(42);',{framework:'unknown'});assert.equal(r.success,false);assert(r.diagnostics.some(d=>d.code==='SF3001'));});
test('CIL API: ArrayBuffer executes directly',()=>{assert.equal(new VirtualMachine(compileToIL('Console.WriteLine(42);').assembly.buffer).run().output,'42\n');});
test('CIL API: direct debugger construction accepts DLL bytes',()=>{const session=new DebugSession(compileToIL('int n=42;\nConsole.WriteLine(n);').assembly);session.start(true);session.pump();assert.equal(session.vm.state,'paused');assert.equal(session.stackTrace()[0].methodToken>>>24,6);assert(Number.isInteger(session.stackTrace()[0].ilOffset));assert.equal(session.stackTrace()[0].ilOffset,session.vm.currentPoint.ilOffset);});
test('CIL inspection: standard opcodes and metadata names',()=>{const b=compileToIL('Console.WriteLine(42);').assembly,s=formatAssembly(b);assert.match(s,/ldc.i4\s+42/);assert.match(s,/call\s+void System.Console::WriteLine\(int\)/);assert.match(s,/IL_[a-f0-9]+:/);const a=disassembleAssembly(b);assert(a.methods.some(m=>m.isEntryPoint));assert(a.methods.some(m=>m.instructions.some(i=>i.point)));});
test('CIL runtime configuration: explicit host policy',()=>{assert.equal(createRuntimeConfig().runtimeOptions.framework.version,'8.0.0');assert.throws(()=>createRuntimeConfig({version:'bad'}));assert.throws(()=>createRuntimeConfig({rollForward:'unknown'}));});
test('CIL front end remains light: ordinary compile does not emit an assembly',()=>{const r=compile('Console.WriteLine(42);');assert(!Object.hasOwn(r,'assembly'));});
test('Workspace cache includes assembly-related compilation options',()=>{const w=new Workspace();w.update('P.cs','Console.WriteLine(42);',1);const a=w.compile({name:'First'}),b=w.compile({name:'Second'});assert.notEqual(a,b);assert.equal(b.image.name,'Second');assert.equal(w.compile({name:'Second'}),b);});
test('CIL metadata: genuine four-byte string and blob heap indexes',()=>{const md=new MetadataBuilder('Wide');const big=md.string('X'.repeat(70000)),blob=md.blob(new Uint8Array(70000)),field=md.add(4,[0x16,md.string('AfterLargeString'),md.blob(new Uint8Array([6,8]))]);md.add(17,[blob]);const read=readMetadata(md.finish(null,new Uint8Array([1])));assert.equal(read.streams.get('#~')[6]&5,5);assert.equal(read.string(big).length,70000);assert.equal(read.string(read.row(field)[1]),'AfterLargeString');assert.equal(read.blob(blob).length,70000);});
