import test from 'node:test';
import assert from 'node:assert/strict';
import {SourceText} from '@sharpforge/text';
import {parse} from '@sharpforge/syntax';
import {MethodSymbol,FieldSymbol,PropertySymbol,EventSymbol,ParameterSymbol,LocalSymbol,LabelSymbol,MethodKind,DeclarationModifiers,LocalDeclarationKind,modifiersFromSyntax,accessibilityFromSyntax,modifierKeywords,isAccessibilityKeyword,createTypeParameters} from '../packages/compiler/src/symbols/members.js';
import {NamedTypeSymbol,ArrayTypeSymbol,TypeParameterSymbol,TypeWithAnnotations,TypeKind,SymbolKind,Accessibility,RefKind,NullableAnnotation,SymbolDisplayFormat as F} from '../packages/compiler/src/symbols/types.js';
import {NamespaceSymbol} from '../packages/compiler/src/symbols/namespaces.js';
import {DeclarationTable} from '../packages/compiler/src/symbols/source/declaration-table.js';
const global=new NamespaceSymbol(),system=global.ensureNamespace('System');
const special=(name,id,typeKind=TypeKind.Struct)=>system.addType(new NamedTypeSymbol({name,specialType:id,typeKind}));
const object=special('Object','System_Object',TypeKind.Class),int=special('Int32','System_Int32'),string=special('String','System_String',TypeKind.Class),voidType=special('Void','System_Void'),bool=special('Boolean','System_Boolean'),double=special('Double','System_Double');
const action=system.addType(new NamedTypeSymbol({name:'Action',typeKind:TypeKind.Delegate})),list=global.ensureNamespace('System.Collections.Generic').addType(new NamedTypeSymbol({name:'List',arity:1,baseType:object}));
const app=global.ensureNamespace('App'),C=app.addType(new NamedTypeSymbol({name:'C',baseType:object})),box=app.addType(new NamedTypeSymbol({name:'Box',arity:1,baseType:object})),T=box.typeParameters[0];
const parameter=(name,type,init={})=>new ParameterSymbol({name,type,...init});
const method=(owner,name,returnType,parameters=[],init={})=>owner.addMember(new MethodSymbol({name,returnType,parameters,containingSymbol:owner,...init}));

test('A02-T15 declaration modifiers are a bit set with keyword and accessibility helpers',()=>{
  assert.equal(modifiersFromSyntax(),0);assert.equal(modifiersFromSyntax(['public','static','readonly']),DeclarationModifiers.Static|DeclarationModifiers.ReadOnly);assert.equal(modifiersFromSyntax(['private','protected']),DeclarationModifiers.None);
  const all=['static','abstract','virtual','override','sealed','readonly','const','volatile','extern','async','partial','new','unsafe','required','ref','file','fixed'],flags=modifiersFromSyntax(all);
  assert.deepEqual(modifierKeywords(flags),all);assert.equal(flags,2**all.length-1);assert.equal(new Set(Object.values(DeclarationModifiers)).size,all.length+1);assert.equal(Object.isFrozen(DeclarationModifiers),true);
  assert.deepEqual(modifierKeywords(DeclarationModifiers.Async|DeclarationModifiers.Static),['static','async']);assert.deepEqual(modifierKeywords(0),[]);assert.equal(modifiersFromSyntax(['unknown','static']),DeclarationModifiers.Static);
  const access=(...k)=>accessibilityFromSyntax(k);
  assert.equal(access(),Accessibility.Private);assert.equal(accessibilityFromSyntax([],Accessibility.Internal),Accessibility.Internal);assert.equal(accessibilityFromSyntax(undefined,Accessibility.Public),Accessibility.Public);
  assert.equal(access('public'),Accessibility.Public);assert.equal(access('private'),Accessibility.Private);assert.equal(access('protected'),Accessibility.Protected);assert.equal(access('internal'),Accessibility.Internal);
  assert.equal(access('protected','internal'),Accessibility.ProtectedOrInternal);assert.equal(access('internal','static','protected'),Accessibility.ProtectedOrInternal);assert.equal(access('private','protected'),Accessibility.ProtectedAndInternal);assert.equal(access('protected','private'),Accessibility.ProtectedAndInternal);
  assert.equal(accessibilityFromSyntax(['static'],Accessibility.Internal),Accessibility.Internal);assert.deepEqual(['public','private','protected','internal','static','file'].map(isAccessibilityKeyword),[true,true,true,true,false,false]);
});
test('A02-T15 method symbols: kinds, modifiers, parameters and ownership',()=>{
  const m=method(C,'Run',voidType,[parameter('a',int),parameter('b',string)],{declaredAccessibility:Accessibility.Public,modifiers:DeclarationModifiers.Static|DeclarationModifiers.Async});
  assert.equal(m.kind,SymbolKind.Method);assert.equal(m.methodKind,MethodKind.Ordinary);assert.equal(m.name,'Run');assert.equal(m.metadataName,'Run');assert.equal(m.containingSymbol,C);assert.equal(m.containingType,C);assert.equal(m.containingNamespace,app);
  assert.equal(m.declaredAccessibility,Accessibility.Public);assert.equal(m.isStatic,true);assert.equal(m.isAsync,true);assert.equal(m.isAbstract,false);assert.equal(m.isVirtual,false);assert.equal(m.isOverride,false);assert.equal(m.isSealed,false);assert.equal(m.isExtern,false);assert.equal(m.isNew,false);assert.equal(m.isReadOnly,false);assert.equal(m.isPartialDefinition,false);
  assert.equal(m.returnType,voidType);assert.equal(m.returnsVoid,true);assert(m.returnTypeWithAnnotations instanceof TypeWithAnnotations);assert.equal(m.refKind,RefKind.None);assert.equal(m.arity,0);assert.equal(m.isGenericMethod,false);assert.deepEqual(m.typeArguments,[]);
  assert.deepEqual(m.parameters.map(p=>[p.name,p.ordinal,p.type,p.containingSymbol]),[['a',0,int,m],['b',1,string,m]]);assert.equal(Object.isFrozen(m.parameters),true);assert.deepEqual(m.parameterTypes.map(t=>t.type),[int,string]);
  assert.equal(m.isDefinition,true);assert.equal(m.originalDefinition,m);assert.equal(m.constructedFrom,m);assert.equal(m.isConstructor,false);assert.equal(m.isAccessor,false);assert.equal(m.isImplicitlyDeclared,false);assert.equal(m.isExtensionMethod,false);assert.equal(m.isVararg,false);assert.equal(m.overriddenMethod,null);assert.deepEqual(m.explicitInterfaceImplementations,[]);
  const defaults=new MethodSymbol({name:'D',returnType:int});assert.equal(defaults.declaredAccessibility,Accessibility.Private);assert.equal(defaults.modifiers,0);assert.equal(defaults.containingSymbol,null);assert.equal(defaults.containingType,null);assert.equal(defaults.returnsVoid,false);assert.deepEqual(defaults.locations,[]);assert.equal(defaults.syntax,null);
  const flagged=new MethodSymbol({name:'F',returnType:voidType,modifiers:modifiersFromSyntax(['abstract','virtual','override','sealed','extern','new','readonly','partial','required'])});
  for(const flag of ['isAbstract','isVirtual','isOverride','isSealed','isExtern','isNew','isReadOnly','isPartialDefinition','isRequired'])assert.equal(flagged[flag],true,flag);assert.equal(flagged.isStatic,false);
  const ctor=method(C,'.ctor',voidType,[parameter('x',int)],{methodKind:MethodKind.Constructor}),cctor=method(C,'.cctor',voidType,[],{methodKind:MethodKind.StaticConstructor,modifiers:DeclarationModifiers.Static}),dtor=method(C,'Finalize',voidType,[],{methodKind:MethodKind.Destructor});
  assert.equal(ctor.isConstructor,true);assert.equal(cctor.isConstructor,true);assert.equal(dtor.isConstructor,false);assert.equal(ctor.metadataName,'.ctor');assert.equal(cctor.metadataName,'.cctor');
  assert.equal(new MethodSymbol({name:'C',methodKind:MethodKind.Constructor,returnType:voidType}).metadataName,'.ctor');assert.equal(new MethodSymbol({name:'C',methodKind:MethodKind.StaticConstructor,returnType:voidType}).metadataName,'.cctor');
  assert.equal(ctor.toDisplayString(),'App.C.C(int)');assert.equal(cctor.toDisplayString(),'App.C.C()');assert.equal(dtor.toDisplayString(),'App.C.~C()');
  assert.equal(new Set(Object.values(MethodKind)).size,Object.keys(MethodKind).length);for(const kind of [MethodKind.PropertyGet,MethodKind.PropertySet,MethodKind.EventAdd,MethodKind.EventRemove,MethodKind.EventRaise])assert.equal(new MethodSymbol({name:'a',methodKind:kind,returnType:voidType}).isAccessor,true);
  assert.equal(new MethodSymbol({name:'e',returnType:voidType,isExtensionMethod:true,isVararg:true,isInitOnly:true}).isExtensionMethod,true);
});
test('A02-T15 method display strings in the Roslyn error-message and test formats',()=>{
  const m=method(C,'Mix',int,[parameter('a',int,{refKind:RefKind.Ref}),parameter('b',string,{refKind:RefKind.Out}),parameter('c',double,{refKind:RefKind.In}),parameter('d',bool,{refKind:RefKind.RefReadOnlyParameter}),parameter('rest',new ArrayTypeSymbol(int),{isParams:true})]);
  assert.equal(m.toDisplayString(),'App.C.Mix(ref int, out string, in double, ref readonly bool, params int[])');assert.equal(String(m),m.toDisplayString());
  assert.equal(m.toDisplayString(F.Test),'System.Int32 App.C.Mix(ref System.Int32 a, out System.String b, in System.Double c, ref readonly System.Boolean d, params System.Int32[] rest)');
  assert.equal(m.toDisplayString(F.MinimallyQualified),'C.Mix(ref int, out string, in double, ref readonly bool, params int[])');assert.equal(m.toDisplayString(F.FullyQualified),'global::App.C.Mix(ref int, out string, in double, ref readonly bool, params int[])');
  const byRef=method(C,'Slot',int,[],{refKind:RefKind.Ref}),readonlyRef=method(C,'Peek',int,[],{refKind:RefKind.RefReadOnly});assert.equal(byRef.toDisplayString(),'App.C.Slot()');assert.equal(byRef.toDisplayString(F.Test),'ref System.Int32 App.C.Slot()');assert.equal(readonlyRef.toDisplayString(F.Test),'ref readonly System.Int32 App.C.Peek()');
  assert.equal(method(C,'Log',voidType,[parameter('format',string)],{isVararg:true}).toDisplayString(),'App.C.Log(string, __arglist)');assert.equal(method(C,'Any',voidType,[],{isVararg:true}).toDisplayString(),'App.C.Any(__arglist)');
  const nullable=method(C,'Find',new TypeWithAnnotations(string,NullableAnnotation.Annotated),[parameter('key',new TypeWithAnnotations(string,NullableAnnotation.Annotated))]);assert.equal(nullable.toDisplayString(),'App.C.Find(string?)');assert.equal(nullable.toDisplayString(F.Test),'System.String? App.C.Find(System.String? key)');
  const add=method(C,'op_Addition',C,[parameter('a',C),parameter('b',C)],{methodKind:MethodKind.UserDefinedOperator,modifiers:DeclarationModifiers.Static}),checked=method(C,'op_CheckedAddition',C,[parameter('a',C),parameter('b',C)],{methodKind:MethodKind.UserDefinedOperator});
  const toInt=method(C,'op_Implicit',int,[parameter('c',C)],{methodKind:MethodKind.Conversion}),fromInt=method(C,'op_Explicit',C,[parameter('i',int)],{methodKind:MethodKind.Conversion}),isTrue=method(C,'op_True',bool,[parameter('c',C)],{methodKind:MethodKind.UserDefinedOperator});
  assert.equal(add.toDisplayString(),'App.C.operator +(App.C, App.C)');assert.equal(checked.toDisplayString(),'App.C.operator +(App.C, App.C)');assert.equal(toInt.toDisplayString(),'App.C.implicit operator int(App.C)');assert.equal(fromInt.toDisplayString(),'App.C.explicit operator App.C(int)');assert.equal(isTrue.toDisplayString(),'App.C.operator true(App.C)');
  const host=method(C,'Host',voidType),local=new MethodSymbol({name:'helper',methodKind:MethodKind.LocalFunction,returnType:int,parameters:[parameter('x',int)],containingSymbol:host}),lambda=new MethodSymbol({name:'',methodKind:MethodKind.AnonymousFunction,returnType:int,containingSymbol:host});
  assert.equal(local.toDisplayString(),'helper(int)');assert.equal(local.containingType,C);assert.equal(lambda.toDisplayString(),'lambda expression');assert.equal(lambda.toDisplayString(F.Test),'lambda expression');
  assert.equal(new MethodSymbol({name:'Free',returnType:int,parameters:[parameter('x',int)]}).toDisplayString(),'Free(int)');
  assert.equal(parameter('x',int).toDisplayString(),'int x');assert.equal(parameter('',int,{refKind:RefKind.Out}).toDisplayString(),'out int');assert.equal(parameter('xs',new ArrayTypeSymbol(string),{isParams:true}).toDisplayString(F.Test),'params System.String[] xs');
});
test('A02-T15 generic methods: type parameters, construct and signature keys',()=>{
  const [TFirst,TSecond]=createTypeParameters(['TFirst','TSecond']),m=method(C,'Map',TSecond,[parameter('source',list.construct(TFirst)),parameter('seed',TSecond,{refKind:RefKind.Ref})],{typeParameters:[TFirst,TSecond]});
  assert.equal(m.arity,2);assert.equal(m.isGenericMethod,true);assert.equal(TFirst.containingSymbol,m);assert.equal(TSecond.ordinal,1);assert.equal(TFirst.typeParameterKind,'method');assert.deepEqual(m.typeArguments.map(a=>a.type),[TFirst,TSecond]);assert.equal(Object.isFrozen(m.typeParameters),true);
  assert.equal(m.toDisplayString(),'App.C.Map<TFirst, TSecond>(System.Collections.Generic.List<TFirst>, ref TSecond)');assert.equal(m.toDisplayString(F.Test),'TSecond App.C.Map<TFirst, TSecond>(System.Collections.Generic.List<TFirst> source, ref TSecond seed)');
  const constructed=m.construct(int,string);assert.notEqual(constructed,m);assert.equal(constructed.originalDefinition,m);assert.equal(constructed.constructedFrom,m);assert.equal(constructed.isDefinition,false);assert.equal(constructed.returnType,string);assert.equal(constructed.parameters[0].type.equals(list.construct(int)),true);assert.equal(constructed.parameters[1].type,string);assert.equal(constructed.parameters[1].refKind,RefKind.Ref);
  assert.deepEqual(constructed.typeArguments.map(a=>a.type),[int,string]);assert.equal(constructed.arity,2);assert.equal(constructed.containingType,C);assert.equal(constructed.parameters[0].containingSymbol,constructed);assert.equal(constructed.parameters[0].originalDefinition,m.parameters[0]);
  assert.equal(constructed.toDisplayString(),'App.C.Map<int, string>(System.Collections.Generic.List<int>, ref string)');assert.equal(constructed.toDisplayString(F.Test),'System.String App.C.Map<System.Int32, System.String>(System.Collections.Generic.List<System.Int32> source, ref System.String seed)');
  assert.equal(m.construct([int,string]).equals(constructed),true);assert.equal(constructed.equals(m.construct(string,int)),false);assert.equal(constructed.equals(m),false);assert.equal(m.equals(m),true);assert.equal(constructed.construct(double,bool).returnType,bool);assert.equal(constructed.construct(double,bool).constructedFrom,m);
  assert.throws(()=>m.construct(int),RangeError);const plain=method(C,'Plain',voidType);assert.equal(plain.construct(),plain);assert.throws(()=>plain.construct(int),RangeError);
  // Signature keys: name, arity and parameter types with ref-ness; type parameters by position; return type and names do not matter.
  assert.equal(m.signatureKey,'Map`2(System.Collections.Generic.List<!!0>,ref !!1)');
  const [X,Y]=createTypeParameters(['X','Y']),renamed=new MethodSymbol({name:'Map',returnType:voidType,parameters:[parameter('a',list.construct(X)),parameter('b',Y,{refKind:RefKind.Out})],typeParameters:[X,Y]});assert.equal(renamed.signatureKey,m.signatureKey);
  const [P,Q]=createTypeParameters(['P','Q']),swapped=new MethodSymbol({name:'Map',returnType:voidType,parameters:[parameter('a',list.construct(Q)),parameter('b',P,{refKind:RefKind.Ref})],typeParameters:[P,Q]});assert.notEqual(swapped.signatureKey,m.signatureKey);
  const key=(name,...types)=>new MethodSymbol({name,returnType:voidType,parameters:types.map((t,i)=>t instanceof ParameterSymbol?t:parameter('p'+i,t))}).signatureKey;
  assert.equal(key('F',int,string),'F`0(System.Int32,System.String)');assert.equal(key('F'),'F`0()');assert.notEqual(key('F',int),key('F',string));assert.notEqual(key('F',int),key('G',int));assert.notEqual(key('F',int),key('F',parameter('x',int,{refKind:RefKind.Ref})));
  assert.equal(key('F',parameter('x',int,{refKind:RefKind.Ref})),key('F',parameter('y',int,{refKind:RefKind.In})));assert.notEqual(key('F',new ArrayTypeSymbol(int)),key('F',int));assert.equal(new MethodSymbol({name:'F',returnType:int,parameters:[parameter('q',int)]}).signatureKey,key('F',int));
  assert.equal(constructed.signatureKey,m.signatureKey.replace('!!0','System.Int32').replace('!!1','System.String'));
});
test('A02-T15 members of constructed types: asMemberOf substitutes and keeps the definition',()=>{
  const value=box.addMember(new FieldSymbol({name:'value',type:T,containingSymbol:box,declaredAccessibility:Accessibility.Public})),get=method(box,'Get',T,[parameter('fallback',T),parameter('all',new ArrayTypeSymbol(T))],{declaredAccessibility:Accessibility.Public,modifiers:DeclarationModifiers.Virtual});
  const [U]=createTypeParameters(['U']),convert=method(box,'Convert',U,[parameter('from',T)],{typeParameters:[U]});
  const item=box.addMember(new PropertySymbol({name:'Item',type:T,containingSymbol:box,getMethod:new MethodSymbol({name:'get_Item',methodKind:MethodKind.PropertyGet,returnType:T,containingSymbol:box}),setMethod:new MethodSymbol({name:'set_Item',methodKind:MethodKind.PropertySet,returnType:voidType,parameters:[parameter('value',T)],containingSymbol:box})}));
  const changed=box.addMember(new EventSymbol({name:'Changed',type:list.construct(T),containingSymbol:box,addMethod:new MethodSymbol({name:'add_Changed',methodKind:MethodKind.EventAdd,returnType:voidType,containingSymbol:box}),removeMethod:new MethodSymbol({name:'remove_Changed',methodKind:MethodKind.EventRemove,returnType:voidType,containingSymbol:box})}));
  const ofInt=box.construct(int),member=name=>ofInt.getMembers(name)[0];
  const getInt=member('Get');assert.notEqual(getInt,get);assert.equal(getInt.originalDefinition,get);assert.equal(getInt.isDefinition,false);assert.equal(getInt.containingType,ofInt);assert.equal(getInt.returnType,int);assert.equal(getInt.parameters[0].type,int);assert.equal(getInt.parameters[1].type.elementType,int);assert.equal(getInt.isVirtual,true);assert.equal(getInt.declaredAccessibility,Accessibility.Public);
  assert.equal(getInt.toDisplayString(),'App.Box<int>.Get(int, int[])');assert.equal(get.toDisplayString(),'App.Box<T>.Get(T, T[])');assert.equal(getInt.toDisplayString(F.Test),'System.Int32 App.Box<System.Int32>.Get(System.Int32 fallback, System.Int32[] all)');
  assert.equal(getInt.equals(get.asMemberOf(box.construct(int))),true);assert.equal(getInt.equals(get.asMemberOf(box.construct(string))),false);assert.equal(getInt.equals(get),false);
  const valueInt=member('value');assert.equal(valueInt.type,int);assert.equal(valueInt.originalDefinition,value);assert.equal(valueInt.containingType,ofInt);assert.equal(valueInt.toDisplayString(),'App.Box<int>.value');assert.equal(valueInt.toDisplayString(F.Test),'System.Int32 App.Box<System.Int32>.value');assert.equal(valueInt.equals(value.asMemberOf(ofInt)),true);
  const itemInt=member('Item');assert.equal(itemInt.type,int);assert.equal(itemInt.originalDefinition,item);assert.equal(itemInt.getMethod.returnType,int);assert.equal(itemInt.setMethod.parameters[0].type,int);assert.equal(itemInt.getMethod.associatedSymbol,itemInt);assert.equal(itemInt.getMethod.originalDefinition,item.getMethod);assert.equal(itemInt.toDisplayString(F.Test),'System.Int32 App.Box<System.Int32>.Item { get; set; }');assert.equal(item.getMethod.associatedSymbol,item);
  const changedInt=member('Changed');assert.equal(changedInt.type.equals(list.construct(int)),true);assert.equal(changedInt.originalDefinition,changed);assert.equal(changedInt.addMethod.associatedSymbol,changedInt);assert.equal(changedInt.addMethod.containingType,ofInt);
  // A generic method of a constructed type keeps its own type parameters and can still be constructed.
  const convertInt=member('Convert');assert.equal(convertInt.arity,1);assert.equal(convertInt.parameters[0].type,int);assert.equal(convertInt.returnType,U);assert.equal(convertInt.toDisplayString(),'App.Box<int>.Convert<U>(int)');
  const closed=convertInt.construct(string);assert.equal(closed.returnType,string);assert.equal(closed.parameters[0].type,int);assert.equal(closed.originalDefinition,convert);assert.equal(closed.toDisplayString(),'App.Box<int>.Convert<string>(int)');assert.equal(closed.containingType,ofInt);
});
test('A02-T15 field symbols',()=>{
  const f=C.addMember(new FieldSymbol({name:'count',type:int,containingSymbol:C,declaredAccessibility:Accessibility.Internal,modifiers:DeclarationModifiers.ReadOnly|DeclarationModifiers.Volatile}));
  assert.equal(f.kind,SymbolKind.Field);assert.equal(f.type,int);assert(f.typeWithAnnotations instanceof TypeWithAnnotations);assert.equal(f.isReadOnly,true);assert.equal(f.isVolatile,true);assert.equal(f.isStatic,false);assert.equal(f.isConst,false);assert.equal(f.hasConstantValue,false);assert.equal(f.constantValue,undefined);assert.equal(f.declaredAccessibility,Accessibility.Internal);
  assert.equal(f.toDisplayString(),'App.C.count');assert.equal(f.toDisplayString(F.Test),'System.Int32 App.C.count');assert.equal(f.toDisplayString(F.MinimallyQualified),'C.count');assert.equal(f.refKind,RefKind.None);assert.equal(f.isFixedSizeBuffer,false);assert.equal(f.associatedSymbol,null);
  const constant=new FieldSymbol({name:'Max',type:int,containingSymbol:C,modifiers:DeclarationModifiers.Const,constantValue:{value:42}});assert.equal(constant.isConst,true);assert.equal(constant.isStatic,true,'constants are static');assert.equal(constant.hasConstantValue,true);assert.equal(constant.constantValue,42);
  const nullConstant=new FieldSymbol({name:'None',type:string,modifiers:DeclarationModifiers.Const,constantValue:{value:null}});assert.equal(nullConstant.hasConstantValue,true);assert.equal(nullConstant.constantValue,null);assert.equal(nullConstant.toDisplayString(),'None');
  assert.equal(new FieldSymbol({name:'s',type:int,modifiers:DeclarationModifiers.Static}).isStatic,true);assert.equal(new FieldSymbol({name:'p',type:int}).declaredAccessibility,Accessibility.Private);assert.equal(f.equals(f),true);assert.equal(f.equals(constant),false);
  const copy=constant.asMemberOf(box.construct(int));assert.equal(copy.constantValue,42);assert.equal(copy.isConst,true);
});
test('A02-T15 property symbols including indexers',()=>{
  const getter=new MethodSymbol({name:'get_Size',methodKind:MethodKind.PropertyGet,returnType:int,containingSymbol:C}),setter=new MethodSymbol({name:'set_Size',methodKind:MethodKind.PropertySet,returnType:voidType,parameters:[parameter('value',int)],containingSymbol:C});
  const size=C.addMember(new PropertySymbol({name:'Size',type:int,containingSymbol:C,getMethod:getter,setMethod:setter,declaredAccessibility:Accessibility.Public,modifiers:DeclarationModifiers.Virtual}));
  assert.equal(size.kind,SymbolKind.Property);assert.equal(size.type,int);assert.equal(size.isIndexer,false);assert.equal(size.isReadOnly,false);assert.equal(size.isWriteOnly,false);assert.equal(size.isInitOnly,false);assert.equal(size.isVirtual,true);assert.equal(size.metadataName,'Size');assert.equal(size.backingField,null);
  assert.equal(getter.associatedSymbol,size);assert.equal(setter.associatedSymbol,size);assert.equal(getter.isAccessor,true);assert.equal(size.toDisplayString(),'App.C.Size');assert.equal(size.toDisplayString(F.Test),'System.Int32 App.C.Size { get; set; }');assert.equal(getter.toDisplayString(),'App.C.Size.get');assert.equal(setter.toDisplayString(),'App.C.Size.set');assert.equal(getter.toDisplayString(F.Test),'System.Int32 App.C.Size.get');
  const readOnly=new PropertySymbol({name:'Id',type:int,containingSymbol:C,getMethod:new MethodSymbol({name:'get_Id',methodKind:MethodKind.PropertyGet,returnType:int})});assert.equal(readOnly.isReadOnly,true);assert.equal(readOnly.isWriteOnly,false);assert.equal(readOnly.toDisplayString(F.Test),'System.Int32 App.C.Id { get; }');
  const init=new MethodSymbol({name:'set_Name',methodKind:MethodKind.PropertySet,returnType:voidType,parameters:[parameter('value',string)],isInitOnly:true}),initOnly=new PropertySymbol({name:'Name',type:string,containingSymbol:C,getMethod:new MethodSymbol({name:'get_Name',methodKind:MethodKind.PropertyGet,returnType:string}),setMethod:init});
  assert.equal(initOnly.isInitOnly,true);assert.equal(init.toDisplayString(),'App.C.Name.init');assert.equal(initOnly.toDisplayString(F.Test),'System.String App.C.Name { get; init; }');
  const writeOnly=new PropertySymbol({name:'Sink',type:int,setMethod:new MethodSymbol({name:'set_Sink',methodKind:MethodKind.PropertySet,returnType:voidType})});assert.equal(writeOnly.isWriteOnly,true);assert.equal(writeOnly.isReadOnly,false);assert.equal(writeOnly.toDisplayString(),'Sink');assert.equal(new PropertySymbol({name:'Bare',type:int}).toDisplayString(F.Test),'System.Int32 Bare { }');
  const indexer=C.addMember(new PropertySymbol({name:'this[]',type:string,containingSymbol:C,parameters:[parameter('index',int),parameter('key',string,{refKind:RefKind.In})],getMethod:new MethodSymbol({name:'get_Item',methodKind:MethodKind.PropertyGet,returnType:string,parameters:[parameter('index',int),parameter('key',string)],containingSymbol:C})}));
  assert.equal(indexer.isIndexer,true);assert.deepEqual(indexer.parameters.map(p=>[p.ordinal,p.containingSymbol]),[[0,indexer],[1,indexer]]);assert.equal(indexer.toDisplayString(),'App.C.this[int, in string]');assert.equal(indexer.toDisplayString(F.Test),'System.String App.C.this[System.Int32 index, in System.String key] { get; }');assert.equal(indexer.getMethod.toDisplayString(),'App.C.this[int, in string].get');
  const byRef=new PropertySymbol({name:'Slot',type:int,refKind:RefKind.Ref});assert.equal(byRef.refKind,RefKind.Ref);
  const boxIndexer=box.addMember(new PropertySymbol({name:'this[]',type:T,containingSymbol:box,parameters:[parameter('i',T)]})),constructed=box.construct(string).getMembers('this[]')[0];assert.equal(constructed.parameters[0].type,string);assert.equal(constructed.type,string);assert.equal(constructed.originalDefinition,boxIndexer);assert.equal(constructed.toDisplayString(),'App.Box<string>.this[string]');
});
test('A02-T15 event symbols',()=>{
  const add=new MethodSymbol({name:'add_Changed',methodKind:MethodKind.EventAdd,returnType:voidType,parameters:[parameter('value',action)],containingSymbol:C}),remove=new MethodSymbol({name:'remove_Changed',methodKind:MethodKind.EventRemove,returnType:voidType,parameters:[parameter('value',action)],containingSymbol:C});
  const backing=new FieldSymbol({name:'Changed',type:action,containingSymbol:C}),e=C.addMember(new EventSymbol({name:'Changed',type:action,containingSymbol:C,addMethod:add,removeMethod:remove,isFieldLike:true,associatedField:backing,declaredAccessibility:Accessibility.Public,modifiers:DeclarationModifiers.Static}));
  assert.equal(e.kind,SymbolKind.Event);assert.equal(e.type,action);assert.equal(e.isFieldLike,true);assert.equal(e.associatedField,backing);assert.equal(e.isStatic,true);assert.equal(e.raiseMethod,null);assert.equal(add.associatedSymbol,e);assert.equal(remove.associatedSymbol,e);
  assert.equal(e.toDisplayString(),'App.C.Changed');assert.equal(e.toDisplayString(F.Test),'event System.Action App.C.Changed');assert.equal(add.toDisplayString(),'App.C.Changed.add');assert.equal(remove.toDisplayString(),'App.C.Changed.remove');
  const raise=new MethodSymbol({name:'raise_X',methodKind:MethodKind.EventRaise,returnType:voidType}),custom=new EventSymbol({name:'X',type:action,raiseMethod:raise});assert.equal(custom.isFieldLike,false);assert.equal(raise.associatedSymbol,custom);assert.equal(raise.toDisplayString(),'X.raise');assert.equal(custom.addMethod,null);
});
test('A02-T15 parameter symbols',()=>{
  const p=parameter('count',int);assert.equal(p.kind,SymbolKind.Parameter);assert.equal(p.type,int);assert.equal(p.ordinal,0);assert.equal(p.refKind,RefKind.None);assert.equal(p.isParams,false);assert.equal(p.isThis,false);assert.equal(p.isDiscard,false);assert.equal(p.isOptional,false);assert.equal(p.hasExplicitDefaultValue,false);assert.equal(p.explicitDefaultValue,undefined);assert.equal(p.scoped,null);assert.equal(p.originalDefinition,p);
  const optional=parameter('n',int,{explicitDefaultValue:{value:7}});assert.equal(optional.isOptional,true);assert.equal(optional.hasExplicitDefaultValue,true);assert.equal(optional.explicitDefaultValue,7);
  const nullDefault=parameter('s',string,{explicitDefaultValue:{value:null}});assert.equal(nullDefault.hasExplicitDefaultValue,true);assert.equal(nullDefault.explicitDefaultValue,null);assert.equal(parameter('o',int,{isOptional:true}).isOptional,true);assert.equal(parameter('o',int,{isOptional:true}).hasExplicitDefaultValue,false);
  const receiver=parameter('self',C,{isThis:true}),ext=new MethodSymbol({name:'Ext',returnType:voidType,parameters:[receiver],isExtensionMethod:true});assert.equal(receiver.isThis,true);assert.equal(receiver.containingSymbol,ext);
  const generic=parameter('item',T,{refKind:RefKind.Out,explicitDefaultValue:{value:1},isParams:true}),owner=new MethodSymbol({name:'Own',returnType:voidType}),copy=generic.substitute(box.construct(double).typeMap,owner);
  assert.equal(copy.type,double);assert.equal(copy.name,'item');assert.equal(copy.refKind,RefKind.Out);assert.equal(copy.isParams,true);assert.equal(copy.explicitDefaultValue,1);assert.equal(copy.hasExplicitDefaultValue,true);assert.equal(copy.containingSymbol,owner);assert.equal(copy.originalDefinition,generic);assert.equal(copy.isDefinition,false);
  assert.equal(parameter('',int,{isDiscard:true}).isDiscard,true);assert.equal(parameter('x',int,{scoped:'scoped'}).scoped,'scoped');assert.equal(parameter('x',new TypeWithAnnotations(string,NullableAnnotation.Annotated)).toDisplayString(),'string? x');
});
test('A02-T15 local and label symbols',()=>{
  const host=method(C,'Body',voidType),x=new LocalSymbol({name:'x',type:int,containingSymbol:host});
  assert.equal(x.kind,SymbolKind.Local);assert.equal(x.type,int);assert.equal(x.declarationKind,LocalDeclarationKind.Regular);assert.equal(x.isConst,false);assert.equal(x.isUsing,false);assert.equal(x.isForEach,false);assert.equal(x.isRef,false);assert.equal(x.isCompilerGenerated,false);assert.equal(x.isImplicitlyDeclared,false);assert.equal(x.readOnlyReason,null);assert.equal(x.containingSymbol,host);assert.equal(x.containingType,C);
  assert.equal(x.toDisplayString(),'x');assert.equal(x.toDisplayString(F.Test),'System.Int32 x');
  const inferred=new LocalSymbol({name:'v'});assert.equal(inferred.type,null);assert.equal(inferred.toDisplayString(F.Test),'var v');assert.equal(inferred.setType(string),inferred);assert.equal(inferred.type,string);assert.equal(inferred.toDisplayString(F.Test),'System.String v');
  const constant=new LocalSymbol({name:'k',type:int,declarationKind:LocalDeclarationKind.Constant,constantValue:{value:3}});assert.equal(constant.isConst,true);assert.equal(constant.hasConstantValue,true);assert.equal(constant.constantValue,3);
  assert.equal(new LocalSymbol({name:'u',type:C,declarationKind:LocalDeclarationKind.Using}).readOnlyReason,'using variable');assert.equal(new LocalSymbol({name:'i',type:int,declarationKind:LocalDeclarationKind.Foreach}).readOnlyReason,'foreach iteration variable');assert.equal(new LocalSymbol({name:'p',type:int,declarationKind:LocalDeclarationKind.Fixed}).readOnlyReason,'fixed variable');
  assert.equal(new LocalSymbol({name:'u',declarationKind:LocalDeclarationKind.Using}).isUsing,true);assert.equal(new LocalSymbol({name:'i',declarationKind:LocalDeclarationKind.Foreach}).isForEach,true);assert.equal(new LocalSymbol({name:'r',type:int,refKind:RefKind.Ref}).isRef,true);
  const temp=new LocalSymbol({name:'<>t',type:int,synthesizedKind:'temp'});assert.equal(temp.isCompilerGenerated,true);assert.equal(temp.isImplicitlyDeclared,true);assert.equal(new Set(Object.values(LocalDeclarationKind)).size,10);
  const syntax={kind:'Label'},label=new LabelSymbol({name:'retry',containingSymbol:host,syntax});assert.equal(label.kind,SymbolKind.Label);assert.equal(label.name,'retry');assert.equal(label.containingSymbol,host);assert.equal(label.syntax,syntax);assert.equal(label.toDisplayString(),'retry');assert.equal(label.declaredAccessibility,Accessibility.NotApplicable);
  const [A,B]=createTypeParameters(['A','B'],host);assert(A instanceof TypeParameterSymbol);assert.equal(B.ordinal,1);assert.equal(B.containingSymbol,host);assert.deepEqual(createTypeParameters([]),[]);
});
// Symbols produced from declaration fixtures: each line is `kind accessibility [modifiers] display(test format)`.
const keywords={object,int,string,void:voidType,bool,double};
const describe=m=>[m.kind,m.declaredAccessibility,'['+modifierKeywords(m.modifiers).join(' ')+']',m.kind===SymbolKind.NamedType||m.isConstructor?m.toDisplayString():m.toDisplayString(F.Test).replace(/^System\.Void /,'void ')].join(' ');
const fixtures=[
  {name:'fields',source:'namespace Shop { public class Item { int id; public string Name; protected static readonly double Rate = 1.5; internal const int Max = 9; private protected bool flag; protected internal int[] sizes; } }',type:'Shop.Item',
    expected:['Field private [] System.Int32 Shop.Item.id','Field public [] System.String Shop.Item.Name','Field protected [static readonly] System.Double Shop.Item.Rate','Field internal [const] System.Int32 Shop.Item.Max','Field privateProtected [] System.Boolean Shop.Item.flag','Field protectedInternal [] System.Int32[] Shop.Item.sizes']},
  {name:'methods',source:'class Calc { public static int Add(int a, int b) { return a + b; } internal string Describe(double value, string[] tags) { return ""; } bool Check() => true; public sealed override string ToString() { return ""; } protected virtual int Hook(Calc other) { return 0; } }',type:'Calc',
    expected:['Method public [static] System.Int32 Calc.Add(System.Int32 a, System.Int32 b)','Method internal [] System.String Calc.Describe(System.Double value, System.String[] tags)','Method private [] System.Boolean Calc.Check()','Method public [override sealed] System.String Calc.ToString()','Method protected [virtual] System.Int32 Calc.Hook(Calc other)']},
  {name:'properties',source:'class Shape { public int Width { get; set; } public static string Kind { get; private set; } internal double Area => 2.0; protected bool Ready { get { return true; } } }',type:'Shape',
    expected:['Property public [] System.Int32 Shape.Width { get; set; }','Method public [] System.Int32 Shape.Width.get','Method public [] void Shape.Width.set','Field private [] System.Int32 Shape.<Width>k__BackingField',
      'Property public [static] System.String Shape.Kind { get; set; }','Method public [static] System.String Shape.Kind.get','Method private [static] void Shape.Kind.set','Field private [static] System.String Shape.<Kind>k__BackingField',
      'Property internal [] System.Double Shape.Area { get; }','Method internal [] System.Double Shape.Area.get','Property protected [] System.Boolean Shape.Ready { get; }','Method protected [] System.Boolean Shape.Ready.get']},
  {name:'constructors',source:'namespace A.B { public partial class Node { public Node() { } internal Node(int value, Node next) { } } partial class Node { static Node() { } private Node(string text) { } } }',type:'A.B.Node',constructors:true,
    expected:['Method public [] A.B.Node.Node()','Method internal [] A.B.Node.Node(int, A.B.Node)','Method private [static] A.B.Node.Node()','Method private [] A.B.Node.Node(string)']},
];
for(const fixture of fixtures)test(`A02-T15 symbols from declaration fixture: ${fixture.name}`,()=>{
  const file=parse(new SourceText(fixture.source,fixture.name+'.cs'));assert.deepEqual(file.diagnostics.filter(d=>!d.code.startsWith('SF')),[]);
  const table=new DeclarationTable([file],{resolveType:(text,context)=>keywords[text]??context.table.globalNamespace.lookupType(text)??context.containingNamespace.lookupType(text),report:(node,code)=>assert.fail('unexpected '+code)});
  const type=table.globalNamespace.lookupType(fixture.type),members=type.getMembers().filter(m=>fixture.constructors||!(m.kind===SymbolKind.Method&&m.isConstructor));
  assert.deepEqual(members.map(describe),fixture.expected);
  for(const m of members){assert.equal(m.containingType,type);assert.equal(m.isDefinition,true);if(!m.isImplicitlyDeclared||m.kind===SymbolKind.Field){assert.equal(m.locations.length,1);assert.equal(m.locations[0].uri,fixture.name+'.cs');assert(m.syntax);}}
});
test('A02-T15 fixture symbols expose signatures and implicit members',()=>{
  const file=parse(new SourceText('class Calc { public static int Add(int a, int b) { return a + b; } void Add(string s) { } public int Total { get; set; } }','calc.cs'));
  const table=new DeclarationTable([file],{resolveType:text=>keywords[text]??null}),calc=table.globalNamespace.lookupType('Calc'),[add,addText]=calc.getMembers('Add');
  assert.equal(add.signatureKey,'Add`0(System.Int32,System.Int32)');assert.equal(addText.signatureKey,'Add`0(System.String)');assert.equal(add.toDisplayString(),'Calc.Add(int, int)');assert.deepEqual(add.parameters.map(p=>p.syntax.name),['a','b']);
  const ctor=calc.getMembers('.ctor')[0];assert.equal(describe(ctor),'Method public [] Calc.Calc()');assert.equal(ctor.isImplicitlyDeclared,true);assert.equal(calc.getMembers('Total')[0].setMethod.parameters[0].name,'value');assert.equal(calc.getMembers('<Total>k__BackingField')[0].isImplicitlyDeclared,true);
});
