import test from 'node:test';import assert from 'node:assert/strict';import {createSimdEngine,ComputePool} from '@sharpforge/compute';
const scalar=createSimdEngine({backend:'scalar'}),simd=createSimdEngine({backend:'wasm'});
for(const C of [Int32Array,Float64Array])for(const length of [0,1,2,3,4,5,7,8,31,1024])test(`SIMD scalar equivalence ${C.name} length ${length}`,()=>{
 const a=C.from({length},(_,i)=>i%7===0?-2147483648:i%13-7),b=C.from({length},(_,i)=>i%11+1);
 for(const op of ['add','subtract','multiply','min','max','sum','dot',...(C===Int32Array?['and','xor']:['divide'])])assert.deepEqual(simd.execute(op,a,['sum'].includes(op)?null:b),scalar.execute(op,a,['sum'].includes(op)?null:b),op);
});
test('SIMD IEEE special values and signed zero',()=>{const a=new Float64Array([NaN,Infinity,-Infinity,-0,0,NaN,-0]),b=new Float64Array([1,2,3,0,-0,NaN,0]);for(const op of ['add','subtract','multiply','divide','min','max','dot','sum']){const x=simd.execute(op,a,op==='sum'?null:b),y=scalar.execute(op,a,op==='sum'?null:b);assert.deepEqual(ArrayBuffer.isView(x)?[...x]:x,ArrayBuffer.isView(y)?[...y]:y,op);}});
test('SIMD actual WebAssembly backend and growing memory',()=>{assert.equal(simd.backend,'wasm-simd128');const a=new Float64Array(100000).fill(1.25);assert.equal(simd.execute('sum',a),125000);assert.ok(simd.metrics.elements>100000);});
for(const options of [{backend:'bad'},{maxElements:0},{maxElements:2e9}])test('SIMD invalid options '+JSON.stringify(options),()=>assert.throws(()=>createSimdEngine(options)));
test('SIMD rejects type, shape, unsupported operation, and element limit',()=>{const e=createSimdEngine({maxElements:2});for(const f of [()=>e.execute('sum',[]),()=>e.execute('add',new Int32Array(1),new Float64Array(1)),()=>e.execute('add',new Int32Array(1),new Int32Array(2)),()=>e.execute('bad',new Int32Array(1)),()=>e.execute('sum',new Int32Array(3))])assert.throws(f);});
test('worker compute uses distinct real Node workers with SIMD',async()=>{const pool=new ComputePool({workers:2,backend:'wasm'});try{await pool.init();const jobs=Array.from({length:8},(_,i)=>pool.execute('sum',new Float64Array(100000).fill(i+1)));assert.deepEqual(await Promise.all(jobs),[1,2,3,4,5,6,7,8].map(i=>i*100000));const caps=await pool.capabilities();assert.equal(new Set(caps.slots.map(s=>s.threadId)).size,2);assert(caps.slots.every(s=>s.backend==='wasm-simd128'));assert.equal(caps.maxActive,2);}finally{pool.dispose();}});
test('worker snapshots own inputs, transfers preserve caller buffer, scalar fallback',async()=>{const pool=new ComputePool({backend:'scalar'});try{const a=new Float64Array([1,2]),b=new Float64Array([3,4]),job=pool.execute('add',a,b);a[0]=999;assert.deepEqual(await job,new Float64Array([4,6]));assert.equal(a.byteLength,16);assert.equal((await pool.capabilities()).slots[0].backend,'scalar');}finally{pool.dispose();}});
test('worker cancel queued job, dispose pending, and reject new work',async()=>{const pool=new ComputePool({workers:1}),abort=new AbortController();const first=pool.execute('sum',new Float64Array([42])),cancel=pool.execute('sum',new Float64Array([1]),null,{signal:abort.signal});const rejected=assert.rejects(cancel,e=>e.name==='AbortError');abort.abort();try{await rejected;assert.equal(await first,42);const job=pool.execute('sum',new Float64Array(1000000));const stopped=assert.rejects(job,/disposed/);pool.dispose();await stopped;await assert.rejects(pool.execute('sum',new Float64Array()),/disposed/);}finally{pool.dispose();}});
test('worker bounded queue and deadlines',async()=>{const pool=new ComputePool({workers:1,maxQueue:1,timeoutMs:30000});try{const job=pool.execute('sum',new Float64Array([1]));await assert.rejects(pool.execute('sum',new Float64Array([2])),/queue/);assert.equal(await job,1);const timed=pool.execute('sum',new Float64Array(1000000),null,{timeoutMs:0.01});await assert.rejects(timed,/deadline/);assert.equal(await pool.execute('sum',new Float64Array([42])),42);}finally{pool.dispose();}});

test('worker queued/active input byte budget is released after cancellation and completion',async()=>{const pool=new ComputePool({maxQueuedBytes:32,workers:1});try{const controller=new AbortController(),job=pool.execute('sum',new Float64Array(4),null,{signal:controller.signal});await assert.rejects(pool.execute('sum',new Float64Array(1)),/byte budget/);const canceled=assert.rejects(job);controller.abort();await canceled;assert.equal(pool.pendingBytes,0);assert.equal(await pool.execute('sum',new Float64Array([42])),42);assert.equal(pool.pendingBytes,0);}finally{pool.dispose();}});
