import test from 'node:test';
import assert from 'node:assert/strict';
import {NamedTypeSymbol,ConstructedNamedTypeSymbol,ArrayTypeSymbol,PointerTypeSymbol,TypeParameterSymbol,FunctionPointerTypeSymbol,DynamicTypeSymbol,ErrorTypeSymbol,TypeWithAnnotations,TypeMap,TypeKind,SymbolKind,NullableAnnotation,TypeCompareKind,SymbolDisplayFormat as F,RefKind,Variance,substituteType,typeOf,elementTypeOf,specialTypeKeyword} from '../packages/compiler/src/symbols/types.js';
import {NamespaceSymbol} from '../packages/compiler/src/symbols/namespaces.js';
// A small hand-built universe: System, System.Collections.Generic and a user namespace.
const global=new NamespaceSymbol(),system=global.ensureNamespace('System'),generic=global.ensureNamespace('System.Collections.Generic');
const special=(name,id,typeKind=TypeKind.Struct)=>system.addType(new NamedTypeSymbol({name,specialType:id,typeKind}));
const object=special('Object','System_Object',TypeKind.Class),int=special('Int32','System_Int32'),string=special('String','System_String',TypeKind.Class),bool=special('Boolean','System_Boolean'),voidType=special('Void','System_Void'),double=special('Double','System_Double'),intPtr=special('IntPtr','System_IntPtr');
const nullable=system.addType(new NamedTypeSymbol({name:'Nullable',arity:1,typeKind:TypeKind.Struct,specialType:'System_Nullable_T'}));
const list=generic.addType(new NamedTypeSymbol({name:'List',arity:1,baseType:object}));
const dictionary=generic.addType(new NamedTypeSymbol({name:'Dictionary',typeParameters:[new TypeParameterSymbol({name:'TKey'}),new TypeParameterSymbol({name:'TValue'})],baseType:object}));
const tuple2=system.addType(new NamedTypeSymbol({name:'ValueTuple',arity:2,typeKind:TypeKind.Struct}));
const outer=global.ensureNamespace('App').addType(new NamedTypeSymbol({name:'Outer',arity:1}));
const inner=outer.addMember(new NamedTypeSymbol({name:'Inner',typeParameters:[new TypeParameterSymbol({name:'U'})]}));
const T=list.typeParameters[0];
test('A02-T14 named types: construction, kinds and metadata names',()=>{
  assert.equal(int.kind,SymbolKind.NamedType);assert.equal(int.typeKind,TypeKind.Struct);assert.equal(int.isValueType,true);assert.equal(string.isReferenceType,true);assert.equal(int.specialType,'System_Int32');
  assert.equal(list.arity,1);assert.equal(list.isGenericType,true);assert.equal(list.isDefinition,true);assert.equal(list.metadataName,'List`1');assert.equal(list.metadataFullName,'System.Collections.Generic.List`1');assert.equal(inner.metadataFullName,'App.Outer`1+Inner`1');
  assert.equal(T.kind,SymbolKind.TypeParameter);assert.equal(T.containingSymbol,list);assert.equal(T.ordinal,0);assert.equal(T.typeParameterKind,'type');assert.equal(dictionary.typeParameters[1].ordinal,1);
  const listOfInt=list.construct(int);assert(listOfInt instanceof ConstructedNamedTypeSymbol);assert.equal(listOfInt.isDefinition,false);assert.equal(listOfInt.originalDefinition,list);assert.equal(listOfInt.constructedFrom,list);assert.equal(listOfInt.typeArguments[0].type,int);assert.equal(listOfInt.arity,1);
  assert.equal(int.construct(),int);assert.throws(()=>list.construct(int,int),RangeError);assert.equal(list.containingNamespace.qualifiedName,'System.Collections.Generic');assert.equal(inner.containingType,outer);
  assert.equal(specialTypeKeyword('System_Int32'),'int');assert.equal(specialTypeKeyword('System_DateTime'),null);
});
test('A02-T14 display strings match Roslyn formats',()=>{
  const listOfInt=list.construct(int),dict=dictionary.construct(string,list.construct(int));
  assert.equal(int.toDisplayString(),'int');assert.equal(int.toDisplayString(F.Test),'System.Int32');assert.equal(int.toDisplayString(F.FullyQualified),'int');
  assert.equal(listOfInt.toDisplayString(),'System.Collections.Generic.List<int>');assert.equal(listOfInt.toDisplayString(F.MinimallyQualified),'List<int>');
  assert.equal(listOfInt.toDisplayString(F.FullyQualified),'global::System.Collections.Generic.List<int>');assert.equal(listOfInt.toDisplayString(F.Test),'System.Collections.Generic.List<System.Int32>');
  assert.equal(list.toDisplayString(),'System.Collections.Generic.List<T>');assert.equal(dictionary.toDisplayString(F.MinimallyQualified),'Dictionary<TKey, TValue>');
  assert.equal(dict.toDisplayString(),'System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<int>>');
  assert.equal(String(listOfInt),'System.Collections.Generic.List<int>');
  assert.equal(new ArrayTypeSymbol(int).toDisplayString(),'int[]');assert.equal(new ArrayTypeSymbol(int,2).toDisplayString(),'int[,]');assert.equal(new ArrayTypeSymbol(int,3).toDisplayString(F.Test),'System.Int32[,,]');
  assert.equal(new ArrayTypeSymbol(new ArrayTypeSymbol(int,2)).toDisplayString(),'int[][,]');assert.equal(new ArrayTypeSymbol(new ArrayTypeSymbol(int),2).toDisplayString(),'int[,][]');
  assert.equal(new ArrayTypeSymbol(int,1,{isSZArray:false}).toDisplayString(),'int[*]');assert.equal(new ArrayTypeSymbol(listOfInt).toDisplayString(F.MinimallyQualified),'List<int>[]');
  assert.equal(new PointerTypeSymbol(int).toDisplayString(),'int*');assert.equal(new PointerTypeSymbol(new PointerTypeSymbol(voidType)).toDisplayString(),'void**');
  assert.equal(new FunctionPointerTypeSymbol({returnType:voidType,parameters:[int,string]}).toDisplayString(),'delegate*<int, string, void>');
  assert.equal(new FunctionPointerTypeSymbol({callingConvention:'unmanaged',unmanagedConventions:['Cdecl'],returnType:int,parameters:[{type:int,refKind:RefKind.Ref}]}).toDisplayString(),'delegate* unmanaged[Cdecl]<ref int, int>');
  assert.equal(new FunctionPointerTypeSymbol({callingConvention:'unmanaged',returnType:int,returnRefKind:RefKind.RefReadOnly}).toDisplayString(),'delegate* unmanaged<ref readonly int>');
  assert.equal(DynamicTypeSymbol.instance.toDisplayString(),'dynamic');assert.equal(T.toDisplayString(),'T');
  assert.equal(nullable.construct(int).toDisplayString(),'int?');assert.equal(nullable.construct(int).toDisplayString(F.Test),'System.Int32?');assert.equal(nullable.toDisplayString(),'System.Nullable<T>');
  assert.equal(new TypeWithAnnotations(string,NullableAnnotation.Annotated).toDisplayString(),'string?');assert.equal(new TypeWithAnnotations(string,NullableAnnotation.NotAnnotated).toDisplayString(),'string');
  assert.equal(list.construct(new TypeWithAnnotations(string,NullableAnnotation.Annotated)).toDisplayString(F.MinimallyQualified),'List<string?>');
  assert.equal(new ArrayTypeSymbol(new TypeWithAnnotations(string,NullableAnnotation.Annotated)).toDisplayString(),'string?[]');
  assert.equal(tuple2.construct(int,string).toDisplayString(),'(int, string)');assert.equal(tuple2.construct(int,string).withTupleElementNames(['a','b']).toDisplayString(),'(int a, string b)');
  assert.equal(tuple2.construct(int,string).withTupleElementNames(['a','b']).toDisplayString(F.Test),'(System.Int32 a, System.String b)');
  assert.equal(outer.construct(int).getTypeMembers('Inner').length,1);assert.equal(inner.toDisplayString(),'App.Outer<T>.Inner<U>');
  assert.equal(new ErrorTypeSymbol('Missing').toDisplayString(),'Missing');assert.equal(new ErrorTypeSymbol('Missing').toDisplayString(F.Test),'Missing[missing]');assert.equal(new ErrorTypeSymbol('G',1,{typeArguments:[int]}).toDisplayString(),'G<int>');
  assert.equal(new NamedTypeSymbol({name:'IntPtr',specialType:'System_IntPtr',typeKind:TypeKind.Struct,isNativeInteger:true,containingSymbol:system}).toDisplayString(),'nint');assert.equal(intPtr.toDisplayString(),'System.IntPtr');
});
test('A02-T14 equality is structural and survives substitution',()=>{
  const a=list.construct(int),b=list.construct(int);assert.notEqual(a,b);assert(a.equals(b));assert(!a.equals(list.construct(string)));assert(!a.equals(list));assert(!int.equals(string));assert(int.equals(int));
  const map=new TypeMap([T],[int]);assert(list.substitute(map).equals(a),'List<T>{T:=int} is List<int>');assert.equal(list.substitute(TypeMap.empty),list);
  assert.equal(a.substitute(map),a,'a closed type is unchanged by substitution');
  const identity=new TypeMap([T],[T]);assert.equal(list.substitute(identity),list,'identity substitution returns the same symbol');
  const [K,V]=dictionary.typeParameters,open=dictionary.construct(K,new ArrayTypeSymbol(list.construct(V)));
  const closed=open.substitute(new TypeMap([K,V],[string,int]));assert.equal(closed.toDisplayString(F.MinimallyQualified),'Dictionary<string, List<int>[]>');
  assert(closed.equals(dictionary.construct(string,new ArrayTypeSymbol(list.construct(int)))));
  assert(substituteType(T,map).equals(int));assert.equal(substituteType(dictionary.typeParameters[0],map),dictionary.typeParameters[0]);
  assert(new ArrayTypeSymbol(T).substitute(map).equals(new ArrayTypeSymbol(int)));assert(!new ArrayTypeSymbol(int).equals(new ArrayTypeSymbol(int,2)));assert.equal(elementTypeOf(new ArrayTypeSymbol(int)),int);assert.equal(elementTypeOf(int),null);
  assert(new PointerTypeSymbol(T).substitute(map).equals(new PointerTypeSymbol(int)));
  const fp=new FunctionPointerTypeSymbol({returnType:T,parameters:[T,string]});assert(fp.substitute(map).equals(new FunctionPointerTypeSymbol({returnType:int,parameters:[int,string]})));assert.equal(fp.substitute(new TypeMap()),fp);
  assert(!fp.equals(new FunctionPointerTypeSymbol({returnType:T,parameters:[{type:T,refKind:RefKind.Ref},string]})));
});
test('A02-T14 nested generic construction substitutes the containing type',()=>{
  const U=inner.typeParameters[0],OT=outer.typeParameters[0];
  const closedInner=inner.substitute(new TypeMap([OT,U],[int,string]));assert.equal(closedInner.toDisplayString(),'App.Outer<int>.Inner<string>');assert.equal(closedInner.toDisplayString(F.MinimallyQualified),'Outer<int>.Inner<string>');
  assert(closedInner.containingType.equals(outer.construct(int)));assert(closedInner.equals(inner.substitute(new TypeMap([U,OT],[string,int]))));assert(!closedInner.equals(inner.substitute(new TypeMap([OT,U],[string,string]))));
  assert(typeOf(closedInner.typeMap.get(OT)).equals(int));assert(typeOf(closedInner.typeMap.get(U)).equals(string));
  const half=inner.substitute(new TypeMap([OT],[int]));assert.equal(half.toDisplayString(),'App.Outer<int>.Inner<U>');
});
test('A02-T14 comparison options: dynamic, nullable annotations, tuple names',()=>{
  const dyn=DynamicTypeSymbol.instance;assert(!dyn.equals(object));assert(dyn.equals(object,TypeCompareKind.IgnoreDynamic));assert(object.equals(dyn,TypeCompareKind.IgnoreDynamic));
  assert(!list.construct(dyn).equals(list.construct(object)));assert(list.construct(dyn).equals(list.construct(object),TypeCompareKind.IgnoreDynamic));
  const annotated=new TypeWithAnnotations(string,NullableAnnotation.Annotated),plain=new TypeWithAnnotations(string,NullableAnnotation.NotAnnotated),oblivious=new TypeWithAnnotations(string);
  assert(annotated.equals(plain),'nullability is not part of type identity');assert(!annotated.equals(plain,TypeCompareKind.StrictNullability));assert(annotated.equals(plain,TypeCompareKind.IgnoreNullableModifiersForReferenceTypes));assert(annotated.equals(oblivious),'oblivious matches either annotation');
  assert(list.construct(annotated).equals(list.construct(plain)));assert(!list.construct(annotated).equals(list.construct(plain),TypeCompareKind.StrictNullability));assert(list.construct(annotated).equals(list.construct(plain),TypeCompareKind.AllIgnoreOptions));
  const named=tuple2.construct(int,string).withTupleElementNames(['a','b']),other=tuple2.construct(int,string).withTupleElementNames(['x','y']);
  assert(!named.equals(other));assert(named.equals(other,TypeCompareKind.IgnoreTupleNames));assert(named.equals(tuple2.construct(int,string),TypeCompareKind.IgnoreTupleNames));
  assert.equal(TypeWithAnnotations.create(annotated),annotated);assert.equal(TypeWithAnnotations.create(string,NullableAnnotation.Annotated).isAnnotated,true);assert.equal(annotated.withAnnotation(NullableAnnotation.NotAnnotated).isAnnotated,false);
  const nullableT=new TypeWithAnnotations(T,NullableAnnotation.Annotated);assert.equal(nullableT.substitute(new TypeMap([T],[string])).toDisplayString(),'string?','T? keeps its annotation when T is substituted');
});
test('A02-T14 type parameters, error types and base/interface queries',()=>{
  const p=new TypeParameterSymbol({name:'TItem',hasReferenceTypeConstraint:true,hasConstructorConstraint:true,variance:Variance.Out,constraintTypes:[object]});
  assert.equal(p.isReferenceType,true);assert.equal(p.isValueType,false);assert.equal(p.variance,'out');assert.equal(new TypeParameterSymbol({name:'S',hasValueTypeConstraint:true}).isValueType,true);assert.equal(new TypeParameterSymbol({name:'Q'}).isReferenceType,null);
  const e1=new ErrorTypeSymbol('Missing'),e2=new ErrorTypeSymbol('Missing');assert(e1.equals(e2));assert(!e1.equals(new ErrorTypeSymbol('Other')));assert(!ErrorTypeSymbol.unknown.equals(new ErrorTypeSymbol('')));assert.equal(e1.isErrorType(),true);assert.equal(int.isErrorType(),false);
  const enumerable=generic.addType(new NamedTypeSymbol({name:'IEnumerable',arity:1,typeKind:TypeKind.Interface})),collection=generic.addType(new NamedTypeSymbol({name:'ICollection',arity:1,typeKind:TypeKind.Interface}));
  collection._interfaces=[enumerable.construct(collection.typeParameters[0])];
  const bag=generic.addType(new NamedTypeSymbol({name:'Bag',arity:1,baseType:object,interfaces:()=>[collection.construct(bag.typeParameters[0])]}));
  const closed=bag.construct(int);assert.equal(closed.baseType,object);assert.deepEqual(closed.allInterfaces.map(i=>i.toDisplayString(F.MinimallyQualified)),['ICollection<int>','IEnumerable<int>']);
  assert.equal(closed.isDerivedFrom(object),true);assert.equal(object.isDerivedFrom(closed),false);
  const array=new ArrayTypeSymbol(int,1,{baseType:object,interfaces:self=>[enumerable.construct(self.elementType)]});assert.equal(array.baseType,object);assert.equal(array.interfaces[0].toDisplayString(F.MinimallyQualified),'IEnumerable<int>');assert.equal(array.isReferenceType,true);
  assert.throws(()=>new ArrayTypeSymbol(int,0),RangeError);assert.throws(()=>new TypeMap([T],[]),RangeError);
});
