import {cases,diagnosticCases,unsupportedCases} from './fixtures/language/compiler.js';
import {sampleSources} from './sample-sources.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import { compile } from '@sharpforge/compiler';
import { serializeImage,deserializeImage,verifyImage,Op,disassemble } from '@sharpforge/bytecode';
import { VirtualMachine } from '@sharpforge/runtime';
import { image,output,execute } from './helpers.js';
import { samples } from '../apps/studio/samples.js';
for(const [name,source,expected]of cases)test('execution: '+name,()=>output(source,expected));
for(const [name,source,code]of diagnosticCases)test('diagnostic: '+name,()=>{const r=compile(source);assert.equal(r.success,false);assert.equal(r.image,null);assert(r.diagnostics.some(d=>d.code===code),JSON.stringify(r.diagnostics));});
for(const source of unsupportedCases)test('profile: unsupported syntax blocks emission '+source.slice(0,40),()=>{const r=compile(source);assert.equal(r.success,false);assert.equal(r.image,null);});
test('compiler: references resolve across source files',()=>{output([{uri:'Program.cs',text:'class P{static void Main(){Console.WriteLine(C.Square(7));}}'},{uri:'C.cs',text:'class C{public static int Square(int x)=>x*x;}'}],'49\n');});
test('compiler: int Main exit code survives startup',()=>{assert.equal(execute('class P{static int Main(){return 7;}}').exitCode,7);});
test('bytecode: serialize and verify roundtrip',()=>{const original=image('Console.WriteLine(42);'),copy=deserializeImage(serializeImage(original));assert(copy.methods[0].code instanceof Int32Array);assert.deepEqual(verifyImage(copy),[]);assert.equal(new VirtualMachine(copy).run().output,'42\n');assert(disassemble(copy).some(m=>m.instructions.some(i=>i.op==='CALL')));});
test('bytecode: rejects corrupt version and stack underflow',()=>{const a=image('Console.WriteLine(1);');a.formatVersion=999;assert(verifyImage(a).length>0);assert.throws(()=>new VirtualMachine(a));const b=image('Console.WriteLine(1);');b.methods[b.entryPoint].code=Int32Array.from([Op.POP,0,0,Op.RET,0,0]);assert(verifyImage(b).length>0);});
test('bytecode: rejects invalid branch target',()=>{const a=image('Console.WriteLine(1);');a.methods[a.entryPoint].code=Int32Array.from([Op.JUMP,100000,0]);assert(verifyImage(a).length>0);});
for(const sample of samples)test('sample: '+sample.id,async()=>{const r=compile(sampleSources(sample),sample.compilationOptions);if(sample.id==='errors'){assert.equal(r.success,false);assert(r.diagnostics.length>=3);}else {assert.equal(r.success,true,JSON.stringify(r.diagnostics));const vm=new VirtualMachine(r.image,{virtualTime:true});assert.equal((await vm.runAsync()).state,'terminated',vm.fault?.stack);}});

test('compiler: empty file set reports a missing entry point',()=>{const r=compile([]);assert.equal(r.success,false);assert.equal(r.image,null);assert(r.diagnostics.some(d=>d.code==='CS5001'));});
