import test from 'node:test';import assert from 'node:assert/strict';
import {compileToIL} from '@sharpforge/compiler';import {loadAssembly,formatILDocument,assembleILDocument} from '@sharpforge/cil';
import {VirtualMachine,CilVirtualMachine} from '@sharpforge/runtime';import {DebugSession,CilDebugSession} from '@sharpforge/debugger';
const cache=new Map();function compile(text){if(!cache.has(text)){const c=compileToIL(text);assert(c.success,JSON.stringify(c.diagnostics));cache.set(text,c);}return cache.get(text);}
const paths={source:c=>new VirtualMachine(c.image,{virtualTime:true,initialThreshold:64}),reload:c=>new VirtualMachine(loadAssembly(c.assembly),{virtualTime:true,initialThreshold:64}),cil:c=>new CilVirtualMachine(c.assembly,{virtualTime:true,initialThreshold:64})};
const programs=[
 ['async Main, parameters and a value across await',`using System.Threading.Tasks; class P { static async Task<int> Work(int n){int k=n+2;await Task.Delay(5);return k*3;}static async Task Main(){int x=await Work(12);Console.WriteLine(x);}}`,'42\n'],
 ['async starts synchronously and returns at suspension',`using System.Threading.Tasks; class P{static async Task Work(){Console.WriteLine(1);await Task.Delay(10);Console.WriteLine(3);}static async Task Main(){Task task=Work();Console.WriteLine(2);await task;Console.WriteLine(4);}}`,'1\n2\n3\n4\n'],
 ['nested await preserves live operand and argument order',`using System.Threading.Tasks;class P{static int marker;static int Before(){marker++;return 2;}static async Task<int> F(){await Task.Delay(2);return 40;}static async Task Main(){int result=Before()+await F();Console.WriteLine(result);Console.WriteLine(marker);}}`,'42\n1\n'],
 ['parallel tasks keep distinct parameter captures',`using System.Threading.Tasks;class P{static async Task<int> F(int x,int d){await Task.Delay(d);return x;}static async Task Main(){Task<int> a=F(20,4);Task<int> b=F(22,1);int x=await a;int y=await b;Console.WriteLine(x+y);}}`,'42\n'],
 ['fault propagation and finally after await',`using System.Threading.Tasks;class P{static async Task<int> F(){try{await Task.Delay(5);throw new Exception("bad");}finally{Console.WriteLine("cleanup");}}static async Task Main(){try{int x=await F();}catch(Exception e){Console.WriteLine(e.Message);}}}`,'cleanup\nbad\n'],
 ['instance capture keeps receiver and managed string rooted',`using System.Threading.Tasks;class Item{public string Name;public async Task<string> F(){string suffix=" suffix";await Task.Delay(5);GC.Collect();return Name+suffix;}}class P{static async Task Main(){var i=new Item(){Name="kept"};Console.WriteLine(await i.F());}}`,'kept suffix\n'],
 ['Task.Run and await value',`using System.Threading.Tasks;class P{static int F(){GC.Collect();return 42;}static async Task Main(){Task<int> t=Task.Run(F);Console.WriteLine(await t);Console.WriteLine(t.IsCompleted);}}`,'42\nTrue\n'],
 ['completed tasks and synchronous FromResult',`using System.Threading.Tasks;class P{static async Task Main(){await Task.CompletedTask;Console.WriteLine(await Task.FromResult(42));Console.WriteLine(await Task.FromResult("ready"));}}`,'42\nready\n'],
 ['Task.Yield yields before continuation',`using System.Threading.Tasks;class P{static async Task F(){await Task.Yield();Console.WriteLine(2);}static async Task Main(){Task t=F();Console.WriteLine(1);await t;Console.WriteLine(3);}}`,'1\n2\n3\n'],
 ['WhenAll and two pending tasks',`using System.Threading.Tasks;class P{static async Task F(int n){await Task.Delay(n);Console.WriteLine(n);}static async Task Main(){Task[] tasks=new Task[]{F(2),F(1)};await Task.WhenAll(tasks);Console.WriteLine("done");}}`,'1\n2\ndone\n'],
 ['WhenAny and no duplicate completion',`using System.Threading.Tasks;class P{static async Task Main(){Task a=Task.Delay(10);Task b=Task.Delay(2);Task[] tasks=new Task[]{a,b};object winner=await Task.WhenAny(tasks);Console.WriteLine(winner==b);await a;Console.WriteLine(a.IsCompleted);}}`,'True\nTrue\n'],
 ['Thread.Start, name and Join',`using System.Threading;class P{static int result;static void F(){Thread.Sleep(3);result=42;Console.WriteLine(Thread.CurrentThread.Name);}static void Main(){Thread t=new Thread(F);t.Name="worker";t.Start();Console.WriteLine(t.IsAlive);t.Join();Console.WriteLine(result);Console.WriteLine(t.IsAlive);}}`,'True\nworker\n42\nFalse\n'],
 ['loop with repeated suspension',`using System.Threading.Tasks;class P{static async Task Main(){int total=0;for(int i=0;i<4;i++){await Task.Delay(1);total+=i;}Console.WriteLine(total);}}`,'6\n'],
 ['async return cleanup retains computed return value',`using System.Threading.Tasks;class P{static async Task<int> F(){int x=42;try{await Task.Delay(2);return x;}finally{x=0;Console.WriteLine(x);}}static async Task Main(){Console.WriteLine(await F());}}`,'0\n42\n'],
 ['async Task<int> entry point',`using System.Threading.Tasks;class P{static async Task<int> Main(){await Task.Delay(1);return 42;}}`,''],
 ['cooperative worker sees shared statics',`using System.Threading;class P{static int value;static void A(){value=20;}static void B(){value+=22;}static void Main(){Thread a=new Thread(A);a.Start();a.Join();Thread b=new Thread(B);b.Start();b.Join();Console.WriteLine(value);}}`,'42\n']
];
for(const [path,factory]of Object.entries(paths))for(const[name,text,expected]of programs)test(`${path} cooperative: ${name}`,async()=>{const vm=factory(compile(text)),r=await vm.runAsync();assert.equal(r.state,'terminated',r.fault?.message);assert.equal(r.output,expected);assert.equal(vm.allFrames().length,0);assert(vm.scheduler.threads().every(t=>['completed','canceled','faulted'].includes(t.status)));});
const held=`using System.Threading.Tasks;class Box{public string Text;}class P{static async Task Main(){var box=new Box(){Text="survives"};await Task.Delay(100);Console.WriteLine(box.Text);}}`;
for(const [path,factory]of Object.entries(paths)){
 test(`${path}: querying waiting contexts never destroys their suspended frames`,async()=>{const vm=factory(compile(held));vm.run();assert.equal(vm.state,'waiting');const ids=vm.allFrames().map(f=>f.id);assert(ids.length>0);for(let i=0;i<10;i++){vm.scheduler.threads();vm.scheduler.parallelStacks();vm.snapshot();}assert.deepEqual(vm.allFrames().map(f=>f.id),ids);vm.heap.collect();assert.equal((await vm.runAsync()).output,'survives\n');});
 test(`${path}: snapshot while all tasks wait restores all frames and precise GC roots`,async()=>{const vm=factory(compile(held));vm.run();const saved=vm.snapshot(),ids=vm.allFrames().map(f=>f.id);await vm.runAsync();vm.restore(saved);assert.deepEqual(vm.allFrames().map(f=>f.id),ids);vm.heap.collect();vm.state='waiting';const replay=await vm.runAsync();assert.equal(replay.output,'survives\n');assert.equal(replay.state,'terminated');});
 test(`${path}: freezing a ready context prevents instruction execution`,async()=>{const vm=factory(compile(held));vm.run();const context=vm.scheduler.threads().find(t=>t.kind==='async');vm.scheduler.freeze(context.id,true);vm.scheduler.advance(100);const before=vm.instructions;vm.runSlice();assert.equal(vm.instructions,before);vm.scheduler.freeze(context.id,false);assert.equal((await vm.runAsync()).output,'survives\n');});
 test(`${path}: pending awaited exception is retained through snapshots`,async()=>{const c=compile(programs[4][1]),vm=factory(c);vm.run();const snapshot=vm.snapshot();const first=await vm.runAsync();vm.restore(snapshot);vm.state='waiting';const replay=await vm.runAsync();assert.equal(replay.output,first.output);assert.equal(replay.state,'terminated');});
 test(`${path}: cancellation terminates all live cooperative contexts`,async()=>{const vm=factory(compile(held));vm.run();const controller=new AbortController();controller.abort();await assert.rejects(vm.runAsync({signal:controller.signal}),/cancel/i);assert.equal(vm.state,'terminated');assert(vm.scheduler.threads().every(t=>['completed','canceled'].includes(t.status)));});
 test(`${path}: validation errors remain managed exceptions`,async()=>{for(const statement of ['await Task.Delay(-1);','Task[] empty=new Task[0];await Task.WhenAny(empty);']){const vm=factory(compile(`using System.Threading.Tasks;class P{static async Task Main(){try{${statement}}catch(Exception e){Console.WriteLine("caught");}}}`));assert.equal((await vm.runAsync()).output,'caught\n');}});
}
for(const direct of [false,true]){
 const name=direct?'CIL':'source';const session=(text=held)=>{const c=compile(text);return direct?new CilDebugSession(c.assembly,{virtualTime:true,recordHistory:true}):new DebugSession(c.image,{virtualTime:true,recordHistory:true});};
 test(`${name}: debugger lists real suspended frames, local values and await relationships`,()=>{const s=session();s.start(false);s.runUntilStop();const threads=s.threads();assert(threads.length>=2);const asyncThread=threads.find(t=>t.kind==='async');const frames=s.stackTrace(asyncThread.id);assert(frames.length>0);const body=frames.find(f=>s.locals(f.id).some(v=>v.name==='box'));assert(body);assert(s.locals(body.id).find(v=>v.name==='box').reference);const graph=s.parallelStacks();assert.equal(graph.kind,'cooperative');assert(graph.contexts.some(c=>c.waitingFor));});
 test(`${name}: source breakpoint after await stops before the statement`,()=>{const text='using System.Threading.Tasks;class P{static async Task Main(){\nint x=42;\nawait Task.Delay(10);\nConsole.WriteLine(x);\n}}',s=session(text);s.setBreakpoints('Program.cs',[{line:4}]);s.start(false);s.runUntilStop();assert.equal(s.vm.state,'waiting');s.vm.scheduler.advance(10);s.runUntilStop();assert.equal(s.vm.state,'paused');assert.equal(s.stackTrace()[0].line,4);assert.equal(s.evaluate('x').result,'42');assert.equal(s.vm.output.join(''),'');});
 test(`${name}: Hot Reload validates locals in suspended async frames`,()=>{const s=session();s.start(false);s.runUntilStop();const next=compile(held.replace('Console.WriteLine(box.Text);','int n=1;Console.WriteLine(box.Text+n);'));assert.throws(()=>s.applyChanges(direct?next.assembly:next.image),/Rude edit/);assert(s.vm.allFrames().length>0);});
}
test('async profile uses real IL and survives editable IL roundtrip',async()=>{const c=compile(programs[0][1]),il=formatILDocument(c.assembly),result=assembleILDocument(il),vm=new CilVirtualMachine(result.assembly??result.bytes??result,{virtualTime:true});assert.equal((await vm.runAsync()).output,'42\n');});
test('async void Main and unsupported task type are diagnosed rather than approximated',()=>{for(const text of ['class P{static async void Main(){}}','class P{static async Task<decimal> Main(){return 0;}}']){const c=compileToIL(text);assert.equal(c.success,false);}});
