import test from 'node:test';
import assert from 'node:assert/strict';
import { debug,stop } from './helpers.js';
const source='int Double(int value) {\n return value * 2;\n}\nint input = 2;\nint result = Double(input);\nConsole.WriteLine(result);\n';

test('debugger: entry, step over, step in and step out use source points',()=>{
 const s=debug(source).start();assert.equal(stop(s).point.line,4);assert.equal(stop(s,'next').point.line,5);assert.equal(s.evaluate('input').value,2);
 const inside=stop(s,'stepIn');assert.equal(inside.point.line,2);assert.equal(inside.frames.length,2);assert.equal(s.evaluate('value').value,2);
 assert.equal(stop(s,'stepOut').point.line,6);assert.equal(s.evaluate('result').value,4);assert.equal(stop(s,'continue').output,'4\n');
});
test('debugger: step over does not enter called method',()=>{const s=debug(source).start();stop(s);stop(s,'next');assert.equal(stop(s,'next').point.line,6);});
test('debugger: bound breakpoints, conditions and hit counts',()=>{
 const s=debug('int sum=0;\nfor(int i=0;i<5;i++){\n sum+=i;\n}\nConsole.WriteLine(sum);');
 const b=s.setBreakpoints('Program.cs',[{line:3,condition:'i >= 2',hitCondition:'3'}]);assert.equal(b[0].verified,true);s.start(false);const state=stop(s);assert.equal(state.reason.reason,'breakpoint');assert.equal(s.evaluate('i').value,2);assert.equal(state.breakpoints[0].hits,3);assert.equal(stop(s,'continue').output,'10\n');
});
test('debugger: logpoints continue without pausing',()=>{const s=debug('int x=7;\nConsole.WriteLine(x);');s.setBreakpoints('Program.cs',[{line:2,logMessage:'x={x}'}]);s.start(false);const state=stop(s);assert.equal(state.state,'terminated');assert.equal(state.output,'x=7\n7\n');});
test('debugger: invalid breakpoints report unverified locations',()=>{const s=debug(source);const b=s.setBreakpoints('Program.cs',[{line:999},{line:4,condition:'('},{line:4,hitCondition:'0'}]);assert(b.every(x=>!x.verified));});
test('debugger: disabled breakpoints do not stop',()=>{const s=debug(source);s.setBreakpoints('Program.cs',[{line:6,enabled:false}]);s.start(false);assert.equal(stop(s).state,'terminated');});
test('debugger: function breakpoints stop in callee',()=>{const s=debug(source);assert.equal(s.setFunctionBreakpoints(['Double'])[0].verified,true);s.start(false);assert.equal(stop(s).reason.reason,'function breakpoint');assert.equal(s.vm.currentPoint.line,2);});
test('debugger: data breakpoint fires on local write',()=>{const s=debug('int x=1;\nx=2;\nConsole.WriteLine(x);').start();stop(s);const local=s.vm.image.methods[s.vm.top.methodId].locals.find(l=>l.name==='x');s.dataBreakpoints=[{kind:'local',index:local.slot}];const state=stop(s,'continue');assert.equal(state.reason.reason,'data breakpoint');assert.equal(s.vm.top.locals[local.slot],1);});
test('debugger: side-effect-free watches cannot invoke or mutate',()=>{const s=debug(source).start();stop(s);stop(s,'next');for(const expression of ['input++','input=9','Double(3)','new int[2]'])assert.throws(()=>s.evaluate(expression),/not allowed|cannot change/);assert.equal(s.evaluate('input').value,2);assert.equal(s.evaluate('input * 5 + 1').value,11);});
test('debugger: local edits affect continuation and validate types',()=>{const s=debug(source).start();stop(s);stop(s,'next');const id=s.vm.top.id;assert.throws(()=>s.setVariable(id,'input','"bad"'),/Cannot assign/);s.setVariable(id,'input','7');assert.equal(stop(s,'continue').output,'14\n');});
test('debugger: const locals cannot be edited',()=>{const s=debug('const int x=3;\nConsole.WriteLine(x);').start();stop(s);stop(s,'next');assert.throws(()=>s.setVariable(s.vm.top.id,'x','4'),/const/);});
test('debugger: arrays and object children expose actual values',()=>{const s=debug('var n=new N(){Value=9};\nint[] a=new int[]{1,2};\nConsole.WriteLine(n.Value);\nclass N{public int Value;}').start();stop(s);stop(s,'next');stop(s,'next');const locals=s.locals(),n=locals.find(l=>l.name==='n'),a=locals.find(l=>l.name==='a');assert.equal(s.children(n.reference)[0].value,'9');assert.equal(s.children(a.reference,1,1)[0].value,'2');assert.equal(s.evaluate('n.Value+a[1]').value,11);});
test('debugger: exception break happens before catch and resumes into handler',()=>{const s=debug('try{int z=0;Console.WriteLine(1/z);}catch(Exception e){Console.WriteLine("handled");}');s.exceptionBreak='all';s.start(false);assert.equal(stop(s).reason.reason,'exception');assert.equal(s.vm.pendingFault.name,'DivideByZeroException');assert.equal(stop(s,'continue').output,'handled\n');});
test('debugger: uncaught-only exception mode ignores caught exceptions',()=>{const s=debug('try{throw new Exception("x");}catch(Exception e){Console.WriteLine(e.Message);}');s.exceptionBreak='uncaught';s.start(false);assert.equal(stop(s).state,'terminated');});
test('debugger: reverse snapshots restore locals and output',()=>{const s=debug('int x=1;\nx=2;\nConsole.WriteLine(x);',{recordHistory:true}).start();stop(s);stop(s,'next');stop(s,'next');assert.equal(s.evaluate('x').value,2);s.stepBack();assert.equal(s.vm.currentPoint.line,2);assert.equal(s.evaluate('x').value,1);assert.equal(stop(s,'continue').output,'2\n');});
test('debugger: reverse snapshots retain objects across later collection',()=>{const s=debug('var n=new N(){Value=11};\nn=null;\nGC.Collect();\nConsole.WriteLine(0);\nclass N{public int Value;}',{recordHistory:true}).start();stop(s);stop(s,'next');assert.equal(s.evaluate('n.Value').value,11);stop(s,'next');stop(s,'next');assert.equal(s.vm.heap.stats.liveObjects,0);s.stepBack();s.stepBack();assert.equal(s.evaluate('n.Value').value,11);});
test('debugger: recording is bounded and optional',()=>{const s=debug('int i=0;while(i<40){i++;}',{recordHistory:true,maxHistory:5,maxHistoryBytes:2048}).start(false);stop(s);assert(s.history.length<=5);assert(s.historyBytes<=2048);const no=debug(source).start(false);stop(no);assert.equal(no.history.length,0);});
test('debugger: pause/stop are cooperative and invalidate frames',()=>{const s=debug('while(true){}').start(false);s.pump({instructionBudget:50});s.pause();assert.equal(s.vm.state,'paused');const id=s.vm.top.id;s.stop();assert.throws(()=>s.frame(id),/no longer exists/);});
