import test from 'node:test';import assert from 'node:assert/strict';
import {createDesign,DesignDocument,generateDesignCode,readDesignSource,planDesignSourceUpdate,CSharpDesignSession} from '@sharpforge/designer';
import {compileToIL} from '@sharpforge/compiler';
const code=()=>generateDesignCode(createDesign('Sync'));
const checkCompile=s=>assert(compileToIL(s+'\nclass Program {static void Main(){DesignedView.Create();}public static void OnAction(object s,Microsoft.UI.Xaml.RoutedEventArgs e){}}').success);
const user=`using Microsoft.UI.Xaml;using Microsoft.UI.Xaml.Controls;
// Outside: preserved exactly
class View {
  static int count;
  public static Window Create() {
    Window window = new Window();
    Canvas panel = new Canvas();
    Button action = new Button() { Name = "Action", Content = "Hello", Width = 160, Height = 40 }; // button note
    Canvas.SetLeft(action, 24); Canvas.SetTop(action, 32);
    action.Click += OnClick;
    panel.Children.Add(action); window.Content = panel; window.Activate();
    return window;
  }
  // User handler: don't regenerate or format this!
  static void OnClick(object s, RoutedEventArgs e) { count++; Console.WriteLine(count); }
}
`;
test('C# source reader imports generated graph, resources and variables without executing it',()=>{const a=readDesignSource(code());assert.equal(a.document.nodes.length,5);assert.equal(a.bindings.action.name,'v_action');assert.equal(a.document.styles.Accent.setters.FontSize,15);assert.equal(a.structuralEditable,true);assert.equal(a.warnings.length,0);});
test('no-op source roundtrip is byte-identical including comments/newlines',()=>{for(const source of [code(),user,user.replaceAll('\n','\r\n')]){const a=readDesignSource(source);assert.equal(planDesignSourceUpdate(a,a.document).text,source);}});
test('C# scalar/property/attached/event edits only touch the mapped expressions',()=>{const a=readDesignSource(user),d=new DesignDocument(a.document);d.setProperty('Width',218,['action']);d.setProperty('Left',44,['action']);d.change('handler',v=>v.nodes.find(n=>n.id==='action').events.Click='OnOther');const p=planDesignSourceUpdate(a,d.value);assert.equal(p.edits.length,3);assert(p.text.includes('Width = 218,'));assert(p.text.includes('SetLeft(action, 44)'));assert(p.text.includes('action.Click += OnOther'));assert(p.text.includes(user.slice(user.indexOf('  // User handler'))));assert(p.text.includes('// button note'));});
test('reading edited C# updates designer geometry/text without rewriting source',()=>{const session=new CSharpDesignSession(user),d=session.read(user.replace('Width = 160','Width = 251').replace('"Hello"','"From C#"'));assert.equal(d.nodes.find(n=>n.id==='action').properties.Width,251);assert.equal(d.nodes.find(n=>n.id==='action').properties.Content,'From C#');assert.equal(session.analysis.text.includes('Width = 251'),true);});
test('C# syntax errors leave synchronized baseline unchanged',()=>{const session=new CSharpDesignSession(user),old=session.analysis;assert.throws(()=>session.read(user.replace('new Window()','new Window(')),/expected/);assert.equal(session.analysis,old);});
test('stale source update and optimistic session commits are rejected',()=>{const s=new CSharpDesignSession(user),d=new DesignDocument(s.document);d.setProperty('Width',210,['action']);assert.throws(()=>s.plan(d.value,user+' '),/changed/);const p=s.plan(d.value);s.read(user);assert.throws(()=>s.commit(p),/newer/);assert.equal(s.analysis.text,user);});
test('structural updates preserve hand-written handler bodies, identifiers and comments',()=>{const a=readDesignSource(user),d=new DesignDocument(a.document);d.add('TextBlock','panel',{Text:'New'});const p=planDesignSourceUpdate(a,d.value);assert(p.structural);assert(p.text.includes('Button action = new'));assert(p.text.includes('// button note'));assert(p.text.includes(user.slice(user.indexOf('  // User handler'))));assert.equal(p.document.nodes.length,4);assert(compileToIL(p.text+'class P{static void Main(){View.Create();}}').success);});
test('generated view structural updates compile and preserve names of existing fields',()=>{const a=readDesignSource(code()),d=new DesignDocument(a.document);d.add('TextBlock','canvas',{Text:'Added'});const p=planDesignSourceUpdate(a,d.value);assert(p.text.includes('v_action = new'));checkCompile(p.text);assert.equal(p.document.nodes.length,6);});
test('new scalar property inserts before Activate and is available in the preview',()=>{const a=readDesignSource(user),d=new DesignDocument(a.document);d.setProperty('Opacity',.7,['action']);const p=planDesignSourceUpdate(a,d.value);assert(p.text.indexOf('action.Opacity = 0.7;')<p.text.indexOf('window.Activate()'));assert.equal(p.document.nodes.find(n=>n.id==='action').properties.Opacity,.7);});
for(const name of ['Name','Content','Width','Height'])test('clear object initializer property '+name,()=>{const a=readDesignSource(user),d=new DesignDocument(a.document);d.setProperty(name,undefined,['action']);const p=planDesignSourceUpdate(a,d.value);assert(!Object.hasOwn(p.document.nodes.find(n=>n.id==='action').properties,name));assert(compileToIL(p.text+'class P{static void Main(){View.Create();}}').success);});
test('clearing every object initializer remains syntactically valid',()=>{const a=readDesignSource(user),d=new DesignDocument(a.document);for(const name of ['Name','Content','Width','Height'])d.setProperty(name,undefined,['action']);const p=planDesignSourceUpdate(a,d.value);assert(compileToIL(p.text+'class P{static void Main(){View.Create();}}').success);});
test('dynamic expressions are never executed or overwritten and unrelated properties remain editable',()=>{const text=user.replace('Width = 160','Width = ComputeWidth()'),a=readDesignSource(text),d=new DesignDocument(a.document);assert(a.warnings.some(w=>w.property==='Width'));assert(!a.structuralEditable);d.setProperty('Height',72,['action']);assert(planDesignSourceUpdate(a,d.value).text.includes('ComputeWidth()'));d.setProperty('Width',111,['action']);assert.throws(()=>planDesignSourceUpdate(a,d.value),/dynamic/);});
test('unknown statements block structural edits but retain minimal property editing',()=>{const text=user.replace('window.Activate();','Console.WriteLine("custom");window.Activate();'),a=readDesignSource(text),d=new DesignDocument(a.document);assert.equal(a.structuralEditable,false);d.setProperty('Width',220,['action']);assert(planDesignSourceUpdate(a,d.value).text.includes('Console.WriteLine("custom");'));d.add('TextBlock','panel');assert.throws(()=>planDesignSourceUpdate(a,d.value),/custom statements/);});
test('multiple same-control event subscriptions are never silently collapsed on writeback',()=>{const text=user.replace('action.Click += OnClick;','action.Click += OnClick; action.Click += OnClick;'),a=readDesignSource(text),d=new DesignDocument(a.document);assert(!a.structuralEditable);d.change('event',v=>v.nodes.find(n=>n.id==='action').events.Click='P.Other');assert.throws(()=>planDesignSourceUpdate(a,d.value),/Multiple handlers/);});
test('shared styles, BasedOn and template factories survive structural sync',()=>{const d=new DesignDocument(createDesign());d.setStyle('Base',{targetType:'Button',setters:{Width:100}});d.setStyle('Accent',{targetType:'Button',basedOn:'Base',setters:{FontSize:21}});d.setTemplate('Frame',{targetType:'Button',root:{id:'root',type:'Border',properties:{Padding:8},children:[{id:'label',type:'TextBlock',properties:{},bindings:{Foreground:'Foreground'},children:[]}]}});d.setReference('template','Frame',['action']);const a=readDesignSource(generateDesignCode(d.value));assert(a.structuralEditable,JSON.stringify(a.unmanaged));assert.equal(a.document.styles.Accent.basedOn,'Base');const edit=new DesignDocument(a.document);edit.setStyle('Base',{targetType:'Button',setters:{Width:130}});const p=planDesignSourceUpdate(a,edit.value);assert.equal(p.document.styles.Base.setters.Width,130);assert.equal(p.document.templates.Frame.root.children[0].bindings.Foreground,'Foreground');checkCompile(p.text);});
test('C# Grid definitions and spans are read and updated',()=>{const d=new DesignDocument(createDesign());d.change('Grid',v=>v.nodes.find(n=>n.id==='canvas').type='Microsoft.UI.Xaml.Controls.Grid');d.tracks('canvas',['Auto','*'],['120','2*']);d.setProperty('ColumnSpan',2,['action']);const a=readDesignSource(generateDesignCode(d.value));assert.equal(a.document.nodes.find(n=>n.id==='canvas').rows.length,2);assert.equal(a.document.nodes.find(n=>n.id==='action').properties.ColumnSpan,2);const edit=new DesignDocument(a.document);edit.tracks('canvas',['50','*'],['1*','1*']);checkCompile(planDesignSourceUpdate(a,edit.value).text);});
test('UTF16 unicode and CRLF offsets produce minimal correct edits',()=>{const a=readDesignSource(user.replace('// Outside: preserved exactly','// 😀 exactly').replaceAll('\n','\r\n')),d=new DesignDocument(a.document);d.setProperty('Content','Zażółć 😀',['action']);const p=planDesignSourceUpdate(a,d.value);assert(p.text.includes('// 😀 exactly\r\n'));assert(p.text.includes('Content = "Zażółć 😀"'));assert.equal(p.edits.length,1);});
test('structural sync does not activate a returned Window because of a comment or a method named Main',()=>{for(const source of [user.replace('window.Activate();','/* window.Activate(); stays inactive */'),user.replace('Create()', 'Main()').replace('window.Activate();','')]){const a=readDesignSource(source),d=new DesignDocument(a.document);d.add('TextBlock','panel',{Text:'Extra'});const p=planDesignSourceUpdate(a,d.value);readDesignSource(p.text);assert.equal((p.text.replace(/\/\*[\s\S]*?\*\//g,'').match(/window\.Activate\(/g)??[]).length,0);}});
test('source sync records all wrap-grid attached spans without confusing Grid row/column spans',()=>{const text=user.replace('Canvas panel = new Canvas();','VariableSizedWrapGrid panel = new VariableSizedWrapGrid();').replace('Canvas.SetLeft(action, 24); Canvas.SetTop(action, 32);','VariableSizedWrapGrid.SetColumnSpan(action, 2);'),a=readDesignSource(text),d=new DesignDocument(a.document);assert.equal(d.value.nodes.find(n=>n.id==='action').properties.WrapColumnSpan,2);d.setProperty('WrapColumnSpan',3,['action']);const p=planDesignSourceUpdate(a,d.value);assert.match(p.text,/VariableSizedWrapGrid.SetColumnSpan\(action, 3\)/);assert(compileToIL(p.text+'class P{static void Main(){View.Create();}}').success);});
test('explicit non-Button resource target types survive unused-resource and structural source round trips',()=>{const text=user.replace('Window window =','var textStyle = new Microsoft.UI.Xaml.Style("TextBlock");\nWindow window ='),a=readDesignSource(text),d=new DesignDocument(a.document);assert.equal(a.document.styles.textStyle.targetType,'Microsoft.UI.Xaml.Controls.TextBlock');d.add('TextBlock','panel');const p=planDesignSourceUpdate(a,d.value);assert.equal(p.document.styles.textStyle.targetType,'Microsoft.UI.Xaml.Controls.TextBlock');assert(p.text.includes('Style("TextBlock")'));assert(compileToIL(p.text+'class P{static void Main(){View.Create();}}').success);});
