import test from 'node:test';import assert from 'node:assert/strict';
import {DesignDocument,createDesign,validateDesign,designControls,propertySchema,normalizeProperty,childSlot,track,resolvedProperties,designScene,designFromScene,designPatch,generateDesignCode,generateDesignProject} from '@sharpforge/designer';
import {XAML,CONTROLS,MEDIA} from '@sharpforge/framework';
import {compileToIL} from '@sharpforge/compiler';import {loadAssembly,formatILDocument,assembleILDocument} from '@sharpforge/cil';
import {VirtualMachine,CilVirtualMachine,applyDesignPatch} from '@sharpforge/runtime';import {DebugSession,CilDebugSession} from '@sharpforge/debugger';
const fixture=()=>new DesignDocument(createDesign('Designer tests'));
const compile=d=>{const c=compileToIL(generateDesignProject(d).filter(f=>f.path.endsWith('.cs')).map(f=>({uri:f.path,text:f.text})));assert(c.success,JSON.stringify(c.diagnostics));return c;};
const view=(vm,name)=>vm.platform.scene().nodes.find(n=>n.properties.Name===name);
const paths={source:c=>new VirtualMachine(c.image,{initialThreshold:64,virtualTime:true}),reload:c=>new VirtualMachine(loadAssembly(c.assembly),{initialThreshold:64,virtualTime:true}),cil:c=>new CilVirtualMachine(c.assembly,{initialThreshold:64,virtualTime:true}),reassembled:c=>new CilVirtualMachine(assembleILDocument(formatILDocument(c.assembly)).bytes,{initialThreshold:64,virtualTime:true})};
const templated=()=>{const doc=fixture();doc.add('TextBox','canvas',{Name:'Input',Text:'initial',Top:260});doc.setTemplate('InputFrame',{targetType:'TextBox',root:{id:'frame',type:'Border',properties:{Padding:8,Background:'#263346'},children:[{id:'editor',type:'TextBox',properties:{Name:'PART_Editor'},bindings:{Text:'Text',Foreground:'Foreground'},children:[]}]}});doc.setReference('template','InputFrame');return doc;};
test('design documents round-trip independently and default project uses real generated source',()=>{const a=fixture(),b=new DesignDocument(JSON.parse(a.serialize()));assert.deepEqual(a.value,b.value);assert(generateDesignProject(a.value).some(f=>f.path.endsWith('.slnx')));assert.match(generateDesignCode(a.value),/Setters.Add/);assert(!propertySchema('Window').Left);assert.equal(childSlot('Grid').property,'Children');});
test('property validation covers typed layout values and inherited properties',()=>{assert.equal(normalizeProperty('Button','Width','100'),100);assert.deepEqual(normalizeProperty('Border','Padding','2,4'),{valueType:XAML+'Thickness',Left:2,Top:4,Right:2,Bottom:4});assert.equal(normalizeProperty('TextBlock','Foreground','#80112233').Color.A,128);assert.equal(propertySchema('TextBox').Style.type,XAML+'Style');});
for(const [type,key,value]of [['Button','Width',-1],['Button','Opacity',2],['Button','Grid','bad'],['Button','IsEnabled','true'],['Button','RowSpan',0],['Button','Row',1.5],['Button','Row',2147483648],['Button','Width',null],['TextBox','Text',42],['Border','Padding','1,2,3'],['Button','Background','red'],['Button','ActualWidth',20]])test(`design rejects invalid ${type}.${key} ${JSON.stringify(value)}`,()=>assert.throws(()=>normalizeProperty(type,key,value)));
for(const [value,kind,n]of [['Auto',0,1],['*',2,1],['3*',2,3],['48',1,48],['0',1,0]])test('Grid track parsing '+value,()=>assert.deepEqual(track(value),{valueType:XAML+'GridLength',Value:n,GridUnitType:kind}));
test('Grid tracks reject nonfinite and negative dimensions',()=>{for(const v of ['NaN','-1','infinity','n*'])assert.throws(()=>track(v));});
for(const [name,mutate]of [
 ['cycle',d=>d.nodes.find(n=>n.id==='canvas').children.push('window')],['missing child',d=>d.nodes[0].children=['missing']],['multiple parents',d=>d.nodes.find(n=>n.id==='action').children.push('title')],['unparented node',d=>d.nodes.find(n=>n.id==='canvas').children=[]],['unsafe event',d=>d.nodes[4].events.Click='P.X();'],['resource code injection',d=>d.styles['x;evil()']={targetType:'Button',setters:{}}],['duplicate name',d=>d.nodes[3].properties.Name='Title'],['window child',d=>d.nodes[4].type='Window'],['resource cycle',d=>{d.styles.Accent.basedOn='Other';d.styles.Other={targetType:'Button',basedOn:'Accent',setters:{}}}],['incorrect target',d=>d.styles.Accent.targetType='TextBox']
])test('design validation is transactional: '+name,()=>{const doc=fixture(),before=doc.serialize();assert.throws(()=>doc.change(name,mutate));assert.equal(doc.serialize(),before);assert.equal(doc.revision,0);assert.equal(doc.undoStack.length,0);});
test('document edit versions, no-op edits, undo and redo preserve selection',()=>{const d=fixture();d.select('action');assert.equal(d.setProperty('Width',160),false);d.setProperty('Width',200);assert.equal(d.revision,1);assert.throws(()=>d.change('stale',()=>{},{expectedRevision:0}),/changed/);d.undo();assert.equal(d.node().properties.Width,160);d.undo(true);assert.equal(d.node().properties.Width,200);assert.equal(d.revision,3);});
test('empty selection safely falls back to root',()=>{const d=fixture();d.select([]);assert.equal(d.node().id,d.value.root);});
test('duplicate subtree has unique names, no runtime bindings and independent properties',()=>{const d=fixture();const group=d.add('StackPanel','canvas',{Name:'Group'});d.move('title',group);d.move('caption',group);d.select(group);const id=d.duplicate();assert(id);assert.equal(d.node(id).children.length,2);d.setProperty('Background','#abcdef');assert.equal(d.node('canvas').properties.Background.Color.R,32);assert.equal(new Set(d.value.nodes.map(n=>n.properties.Name).filter(Boolean)).size,d.value.nodes.filter(n=>n.properties.Name).length);});
test('copy/paste imports referenced resources without overwriting incompatible destination resources',()=>{const from=templated(),to=fixture();to.setStyle('Accent',{targetType:'Button',setters:{FontSize:44}});const ids=to.paste(from.value,['action',from.node().id],'canvas');assert.equal(ids.length,2);assert.equal(to.node(ids[0]).style,'Accent_1');assert.equal(to.value.styles.Accent.setters.FontSize,44);assert.equal(to.node(ids[1]).template,'InputFrame');assert.doesNotThrow(()=>compile(to.value));});
test('Canvas grouping/ungrouping preserves coordinates with undo',()=>{const d=fixture(),before=d.node('action').properties;d.select(['caption','action']);const group=d.group();assert.equal(d.node(group).children.length,2);const children=d.ungroup();assert.equal(children.length,2);assert.equal(d.node('action').properties.Left,before.Left);assert.equal(d.node('action').properties.Top,before.Top);d.undo();assert(d.node(group));});
test('reparent moves are atomic and reject visual cycles or content overfill',()=>{const d=fixture(),before=d.serialize();assert.throws(()=>d.move('canvas','action'));assert.equal(d.serialize(),before);assert.throws(()=>d.move('title','window'));assert.equal(d.serialize(),before);const panel=d.add('StackPanel','canvas');d.move('title',panel);assert.equal(d.parent('title').id,panel);});
test('styles respect BasedOn, implicit exact target and local precedence with clear',()=>{const d=fixture();d.setStyle('Base',{targetType:'Button',setters:{FontSize:21,Width:91}});d.setStyle('Accent',{targetType:'Button',basedOn:'Base',setters:{FontSize:27},implicit:true});d.select('action');assert.equal(resolvedProperties(d.value,d.node()).properties.FontSize,27);assert.equal(resolvedProperties(d.value,d.node()).properties.Width,160);d.setProperty('Width',undefined);assert.equal(resolvedProperties(d.value,d.node()).properties.Width,91);d.setProperty('Width',110);assert.equal(resolvedProperties(d.value,d.node()).sources.Width,'local');});
test('template preview instantiates distinct parts and reflects owner properties',()=>{const d=templated(),one=d.node().id,two=d.duplicate(),scene=designScene(d.value);assert.notEqual(scene.nodes.find(n=>n.id===one).templateRoot,scene.nodes.find(n=>n.id===two).templateRoot);d.setProperty('Text','second',[two]);const changed=designScene(d.value);assert.equal(changed.nodes.find(n=>n.id===one+'::editor').properties.Text,'initial');assert.equal(changed.nodes.find(n=>n.id===two+'::editor').properties.Text,'second');});
test('templates reject invalid target, mismatched bindings and duplicate part IDs',()=>{const d=fixture();for(const value of [{targetType:'Window',root:{id:'x',type:'Button'}},{targetType:'Button',root:{id:'x',type:'TextBlock',properties:{},bindings:{Text:'Width'}}},{targetType:'Button',root:{id:'x',type:'StackPanel',children:[{id:'x',type:'TextBlock'}]}}])assert.throws(()=>d.setTemplate('Bad',value));});
test('codegen rejects identifiers which alias after C# encoding',()=>{const d=fixture();d.value.nodes.find(n=>n.id==='caption').id='a-b';d.value.nodes.find(n=>n.id==='canvas').children[1]='a-b';d.value.nodes.find(n=>n.id==='action').id='a_b';d.value.nodes.find(n=>n.id==='canvas').children[2]='a_b';assert.throws(()=>generateDesignCode(d.value),/collide/);});
const generatedCache=new Map();for(const control of designControls.filter(c=>c.type!==XAML+'Window'))test(`toolbox ${control.name} generates, compiles and executes real C#`,()=>{const d=fixture();d.add(control.type,'canvas');const c=compile(d.value);generatedCache.set(control.type,c);for(const path of ['source','cil']){const vm=paths[path](c);const result=vm.run();assert.equal(result.state,'terminated',path+': '+result.fault?.message);assert(vm.platform.scene().nodes.some(n=>n.type===control.type));}});
for(const [path,factory]of Object.entries(paths))test(`${path}: styled/templated designer code executes with valid IL and survives GC`,()=>{const d=templated(),vm=factory(compile(d.value)),r=vm.run();assert.equal(r.state,'terminated',r.fault?.message);vm.heap.collect();const input=view(vm,'Input');assert(input.templateRoot);assert(vm.platform.scene().nodes.some(n=>n.properties.Name==='PART_Editor'));const action=view(vm,'ActionButton');assert.equal(action.properties.FontSize,15);assert.equal(action.properties.Background.Color.B,184);vm.platform.dispatchEvent(action.id,'Click');assert.equal(vm.run().output,'OnAction invoked\n');});
const liveProgram=`using Microsoft.UI.Xaml;using Microsoft.UI.Xaml.Controls;class P {static int count;static TextBox input;static TextBlock label;static void Click(object s,RoutedEventArgs e){count++;label.Text=input.Text+":"+count;GC.Collect();}static void Main(){Window w=new Window();Canvas panel=new Canvas(){Name="Root"};input=new TextBox(){Name="Input",Text="initial"};label=new TextBlock(){Name="Label",Text="0"};Button b=new Button(){Name="Button",Content="Add"};b.Click+=Click;panel.Children.Add(input);panel.Children.Add(label);panel.Children.Add(b);w.Content=panel;w.Activate();}}`;
for(const direct of [false,true]){
 const kind=direct?'CIL':'source';const session=()=>{const c=compileToIL(liveProgram);assert(c.success,JSON.stringify(c.diagnostics));const s=direct?new CilDebugSession(c.assembly,{initialThreshold:64}):new DebugSession(c.image,{initialThreshold:64});s.start(false);s.runUntilStop();return s;};
 test(`${kind}: live property/style patch retains user text, control identity and managed callbacks`,()=>{const s=session(),before=designFromScene(s.vm.platform.scene()),doc=new DesignDocument(before),button=view(s.vm,'Button'),input=view(s.vm,'Input');s.vm.platform.dispatchEvent(input.id,'TextChanged',{value:'typed'});s.vm.platform.dispatchEvent(button.id,'Click');s.runUntilStop();doc.select(doc.value.nodes.find(n=>n.properties.Name==='Button').id);doc.setProperty('Width',250);doc.setStyle('Theme',{targetType:'Button',setters:{FontSize:25}});doc.setReference('style','Theme');const delta=designPatch(before,doc.value);assert(!delta.commands.some(c=>c.property==='Text'));const result=applyDesignPatch(s,delta);assert.equal(result.revision,1);assert.equal(view(s.vm,'Input').id,input.id);assert.equal(view(s.vm,'Input').properties.Text,'typed');assert.equal(view(s.vm,'Button').properties.FontSize,25);s.vm.platform.dispatchEvent(button.id,'Click');s.runUntilStop();assert.equal(view(s.vm,'Label').properties.Text,'typed:2');});
 test(`${kind}: new live controls retain scalar Content, reparent and Grid track edits apply`,()=>{const s=session(),before=designFromScene(s.vm.platform.scene()),d=new DesignDocument(before),root=d.value.nodes.find(n=>n.properties.Name==='Root').id,button=d.add('Button',root,{Name:'New',Content:'New content'}),grid=d.add('Grid',root,{Name:'Grid'});d.tracks(grid,['Auto','*'],[120,'2*']);d.move(button,grid);const result=applyDesignPatch(s,designPatch(before,d.value));assert.equal(view(s.vm,'New').properties.Content,'New content');assert.equal(view(s.vm,'Grid').collections.RowDefinitions.length,2);assert(view(s.vm,'Grid').collections.Children.some(n=>n.$ref===view(s.vm,'New').id));assert(result.bindings[button]);});
 test(`${kind}: template-only live edits preserve original C# handlers`,()=>{const s=session(),before=designFromScene(s.vm.platform.scene()),d=new DesignDocument(before),id=d.value.nodes.find(n=>n.properties.Name==='Input').id;d.setTemplate('InputTemplate',{targetType:'TextBox',root:{id:'part',type:'TextBox',properties:{Name:'PART_Input'},bindings:{Text:'Text'},children:[]}});d.setReference('template','InputTemplate',[id]);const old=view(s.vm,'Input').id;applyDesignPatch(s,designPatch(before,d.value));assert.equal(view(s.vm,'Input').id,old);assert(view(s.vm,'Input').templateRoot);s.vm.platform.dispatchEvent(old,'TextChanged',{value:'template input'});s.vm.platform.dispatchEvent(view(s.vm,'Button').id,'Click');s.runUntilStop();assert.equal(view(s.vm,'Label').properties.Text,'template input:1');assert.equal(view(s.vm,'PART_Input').properties.Text,'template input');});
 test(`${kind}: invalid live patch restores heap, UI, stopped execution and revision`,()=>{const s=session(),before=designFromScene(s.vm.platform.scene()),d=new DesignDocument(before);d.setProperty('Width',250,[d.value.nodes.find(n=>n.properties.Name==='Button').id]);const delta=designPatch(before,d.value),original=JSON.stringify(s.vm.platform.scene()),old=s.vm.instructions;delta.commands.push({op:'set',id:before.root,property:'Unknown',value:42});assert.throws(()=>applyDesignPatch(s,delta),/Unknown/);assert.equal(JSON.stringify(s.vm.platform.scene()),original);assert.equal(s.vm.instructions,old);assert.equal(s.designRevision??0,0);assert.equal(s.vm.state,'terminated');});
 test(`${kind}: live revision and stale object checks precede mutations`,()=>{const s=session(),before=designFromScene(s.vm.platform.scene()),delta=designPatch(before,before);applyDesignPatch(s,delta);assert.throws(()=>applyDesignPatch(s,delta,{expectedRevision:0}),/revision/);delta.bindings[before.root]='9999:1';assert.throws(()=>applyDesignPatch(s,delta),/outside/);});
 test(`${kind}: aliased live bindings and unsupported new handlers are rejected`,()=>{const s=session(),before=designFromScene(s.vm.platform.scene()),delta=designPatch(before,before);delta.bindings.alias=delta.bindings[before.root];assert.throws(()=>applyDesignPatch(s,delta),/aliases/);const d=new DesignDocument(before);d.value.nodes.find(n=>n.properties.Name==='Button').events.Click='P.NewHandler';assert.throws(()=>designPatch(before,d.value),/event handlers/);});
}
