import test from 'node:test';import assert from 'node:assert/strict';import {compileToIL} from '@sharpforge/compiler';import {DebugSession} from '@sharpforge/debugger';
const compile=source=>{const c=compileToIL(source);assert(c.success,JSON.stringify(c.diagnostics));return c.image;};
function paused(text,line,options={}){const s=new DebugSession(compile(text),{recordHistory:true,...options});s.setBreakpoints('Program.cs',[{line}]);s.start(false);s.runUntilStop();assert.equal(s.vm.state,'paused');return s;}
function done(s){s.setBreakpoints('Program.cs',[]);s.resume();const r=s.runUntilStop();assert.equal(r.state,'terminated',r.fault?.message);return r.output;}
test('EnC adds and reorders methods while preserving IDs and active caller state',()=>{const old='class P { static int A(int x){return x+1;} static void Main(){\nint x=2;\nConsole.WriteLine(A(x));\n}}',s=paused(old,3),id=s.vm.image.methods.find(m=>m.name==='A').id;const next='class P { static int B(int x){return x*7;} static void Main(){\nint x=2;\nConsole.WriteLine(A(x));\n} static int A(int x){return B(x)+1;} }';const applied=s.applyChanges(compile(next));assert.equal(applied.summary.addedMethods,1);assert.equal(s.vm.image.methods.find(m=>m.name==='A').id,id);assert.equal(s.evaluate('x').value,2);assert.equal(done(s),'15\n');});
test('EnC supports multiple generations without method identity drift',()=>{const base='class P { static int A(int x){return x+1;} static void Main(){\nint x=2;\nConsole.WriteLine(A(x));\n}}',s=paused(base,3),id=s.vm.image.methods.find(m=>m.name==='A').id;for(let n=2;n<8;n++){const next=base.replace('return x+1;',`return H(x);`).replace('static void Main()',`static int H(int x){return x+${n};} static void Main()`);s.applyChanges(compile(next),{expectedVersion:n-2});assert.equal(s.vm.image.methods.find(m=>m.name==='A').id,id);assert.equal(s.vm.image.methods.filter(m=>m.name==='H').length,1);}assert.equal(s.codeVersion,6);assert.equal(done(s),'9\n');});
test('EnC inserts a new active local after a surviving source statement',()=>{const before='int x=1;\nx=x+1;\nConsole.WriteLine(x);',after='int x=1;\nx=x+1;\nint y=x*2;\nConsole.WriteLine(y);',s=paused(before,2);const id=s.vm.top.id;s.applyChanges(compile(after));assert.equal(s.vm.top.id,id);assert.equal(s.evaluate('x').value,1);assert.equal(done(s),'4\n');});
test('EnC remaps active locals and write breakpoint descriptors after inserting an earlier local',()=>{const before='int x=1;\nx=x+1;\nConsole.WriteLine(x);',after='int unused=99;\nint x=1;\nx=x+1;\nConsole.WriteLine(x);',s=paused(before,2),info=s.dataBreakpointInfo({name:'x',frameId:s.vm.top.id});assert(info.dataId);s.setDataBreakpoints([{dataId:info.dataId}]);s.applyChanges(compile(after));assert.equal(s.evaluate('x').value,1);const bp=s.dataBreakpoints[0];assert.equal(bp.index,1);assert.equal(JSON.parse(decodeURIComponent(bp.dataId.slice(12))).index,1);s.setBreakpoints('Program.cs',[]);s.resume();const result=s.runUntilStop();assert.equal(result.reason.reason,'data breakpoint');assert.equal(s.evaluate('x').value,2);s.setDataBreakpoints([]);assert.equal(done(s),'2\n');});
test('EnC never guesses skipped initialization needed after the target checkpoint',()=>{const before='int x=1;\nConsole.WriteLine(x);',after='int x=1;\nint y=2;\nConsole.WriteLine(x);\nConsole.WriteLine(y);',s=paused(before,2),old=s.vm.image;assert.throws(()=>s.applyChanges(compile(after)),/unassigned/);assert.equal(s.vm.image,old);assert.equal(done(s),'1\n');});
test('EnC rejects changes to an active statement without mutating its value or location',()=>{const before='int x=1;\nx=x+1;\nConsole.WriteLine(x);',s=paused(before,2),pc=s.vm.top.pc;assert.throws(()=>s.applyChanges(compile(before.replace('x=x+1;','int y=3;x=x+y;'))),/Rude edit/);assert.equal(s.vm.top.pc,pc);assert.equal(s.evaluate('x').value,1);assert.equal(done(s),'2\n');});
test('EnC appends fields to existing objects with defaults and initializes newly created instances',()=>{const before='class N { public int Value=9; } class P {static void Main(){\nN n=new N();\nn.Value+=1;\nConsole.WriteLine(n.Value);\n}}',after=before.replace('public int Value=9;','public int Value=9; public int Extra=42;'),s=paused(before,3),ref=s.evaluate('n').reference??s.vm.top.locals[0];const h=ref.h,g=ref.g;const result=s.applyChanges(compile(after));assert.equal(result.summary.appendedFields,1);assert.equal(s.vm.heap.get({h,g}).data[1],0);assert.equal(s.evaluate('n.Extra').value,0);assert.equal(s.evaluateFunction('new N().Extra',{allowSideEffects:true}).result,'42');assert.equal(done(s),'10\n');});
test('EnC adds types and methods used after a safe active checkpoint',()=>{const before='int x=1;\nx=x+1;\nConsole.WriteLine(x);',after='int x=1;\nx=x+1;\nConsole.WriteLine(Answer.Value(x));\nclass Answer{public static int Value(int n){return n+40;}}',s=paused(before,2);const r=s.applyChanges(compile(after));assert.equal(r.summary.addedTypes,1);assert.equal(done(s),'42\n');});
test('EnC preserves existing statics through reordering and adds default-valued storage',()=>{const before='class P {static int a=10;static int b=20;static void Main(){\nint x=1;\nx++;\nConsole.WriteLine(a+b+x);\n}}',after=before.replace('static int a=10;static int b=20;','static int b=20;static int c;static int a=10;').replace('a+b+x','a+b+c+x'),s=paused(before,3);const r=s.applyChanges(compile(after));assert.equal(r.summary.addedStatics,1);assert.equal(done(s),'32\n');});
for(const[name,change]of [['field reorder',t=>t.replace('public int A;public int B;','public int B;public int A;')],['field type',t=>t.replace('public int A;','public double A;')],['remove field',t=>t.replace('public int A;','')],['remove type',t=>t.replace('class N {public int A;public int B;}','')]])test('EnC rejects incompatible '+name+' before mutating the running image',()=>{const text='class N {public int A;public int B;} class P {static void Main(){\nint x=1;\nConsole.WriteLine(x);\n}}',s=paused(text,3),image=s.vm.image;assert.throws(()=>s.applyChanges(compile(change(text))),/Rude edit/);assert.equal(s.vm.image,image);assert.equal(done(s),'1\n');});
test('EnC rejects a signature change even when the method is currently inactive',()=>{const text='class P {static int F(){return 1;}static void Main(){\nint x=1;\nConsole.WriteLine(x);\n}}',s=paused(text,3);assert.throws(()=>s.applyChanges(compile(text.replace('static int F()','static int F(int unused)'))),/signature/);assert.equal(done(s),'1\n');});
test('EnC observes the heap budget before appended-field mutation',()=>{const before='class N {public int A;}class P {static void Main(){\nN n=new N();\nConsole.WriteLine(n.A);\n}}',s=paused(before,3),limit=s.vm.heap.stats.liveBytes;s.vm.heap.maxBytes=limit;const next=before.replace('public int A;','public int A;public int B;'),image=s.vm.image,heap=s.vm.heap.snapshot();assert.throws(()=>s.applyChanges(compile(next)),/heap budget/);assert.equal(s.vm.image,image);assert.equal(s.vm.heap.stats.liveBytes,heap.stats.liveBytes);});
test('EnC preserves live delegates when a new declaration shifts compiler method indexes',()=>{const before='using System;class P {static int V(){return 42;}static void Main(){\nFunc<int> f=new Func<int>(V);\nConsole.WriteLine(f.Invoke());\n}}',s=paused(before,3),next=before.replace('static int V()', 'static int Added(){return 999;}static int V()');s.applyChanges(compile(next));assert.equal(done(s),'42\n');});
test('EnC updates inactive helpers while real async frames are suspended',async()=>{const text='using System.Threading.Tasks;class P {static int V(){return 1;}static async Task Main(){int x=2;await Task.Delay(10);Console.WriteLine(V()+x);}}',s=new DebugSession(compile(text),{virtualTime:true});s.start(false);s.vm.run();assert.equal(s.vm.state,'waiting');const frames=[...s.vm.allFrames()].map(f=>f.id);s.applyChanges(compile(text.replace('return 1;','return 40;')));assert.deepEqual([...s.vm.allFrames()].map(f=>f.id),frames);const result=await s.vm.runAsync();assert.equal(result.output,'42\n');});
test('EnC clears reverse snapshots across a successful generation, not a rejected one',()=>{const source='int x=1;\nx++;\nConsole.WriteLine(x);',s=paused(source,2);assert(s.history.length);const count=s.history.length;assert.throws(()=>s.applyChanges(compile(source.replace('x++;','int y=1;x+=y;'))));assert.equal(s.history.length,count);s.applyChanges(compile(source.replace('int x=1;','int x=2;')));assert.equal(s.history.length,0);assert.equal(s.evaluate('x').value,1);assert.equal(done(s),'2\n');});
