import test from 'node:test';import assert from 'node:assert/strict';
import {compile,compileToIL} from '@sharpforge/compiler';import {VirtualMachine,CilVirtualMachine} from '@sharpforge/runtime';import {Workspace} from '@sharpforge/workspace';import {LanguageService} from '@sharpforge/language';import {LanguageServer} from '@sharpforge/protocol';import {RefactoringEngine,applyWorkspaceEdits,formatDocument,foldingRanges,selectionRanges} from '@sharpforge/refactoring';import {ExtensionDriver,BuildInfoGenerator,JsonSchemaGenerator,EmptyCatchAnalyzer,UnreferencedLocalAnalyzer} from '@sharpforge/extensions';
const workspace=(text,options)=>{const w=new Workspace(options);w.update('Program.cs',text,1);return w;};
for(const [name,source,output]of [
 ['cast int','Console.WriteLine((int)3.9);','3\n'],['cast double','Console.WriteLine((double)3/2);','1.5\n'],['typed defaults','Console.WriteLine(default(int));Console.WriteLine(default(bool));','0\nFalse\n'],['switch grouped','int n=2;switch(n){case 1:Console.WriteLine(1);break;case 2:case 3:Console.WriteLine(7);break;default:Console.WriteLine(9);break;}','7\n'],['string switch','string s="b";switch(s){case "a":Console.WriteLine(1);break;case "b":Console.WriteLine(2);break;default:break;}','2\n'],['null switch','string s=null;switch(s){case null:Console.WriteLine(3);break;default:break;}','3\n'],['negative pattern','int n=-1;Console.WriteLine(n switch{-1=>7,_=>9});','7\n'],['switch expression','int n=2;Console.WriteLine(n switch{1=>"one",2=>"two",_=>"other"});','two\n'],['numeric switch expression','int n=0;double d=n switch{0=>1,_=>2.5};Console.WriteLine(d/2);','0.5\n'],['nested switch continue','for(int n=0;n<3;n++){switch(n){case 1:continue;default:break;}Console.WriteLine(n);}','0\n2\n'],['null coalescing assignment once','int calls=0;string F(){return "x";}string s=null;s??=F();s??="y";Console.WriteLine(s);','x\n'],['null coalescing field','var c=new C();c.S??="x";Console.WriteLine(c.S);class C{public string S;}','x\n'],['unchecked overflow','int n=2147483647;Console.WriteLine(unchecked(n+1));','-2147483648\n'],['unchecked block','unchecked { int n=2147483647;Console.WriteLine(n+1); }','-2147483648\n']
])test('C# language additions on IR, strict IL and direct CIL: '+name,()=>{const r=compileToIL(source);assert(r.success,JSON.stringify(r.diagnostics));for(const vm of [new VirtualMachine(r.image),new VirtualMachine(r.assembly),new CilVirtualMachine(r.assembly)]){const e=vm.run();assert.equal(e.state,'terminated',e.fault?.stack);assert.equal(e.output,output);}});
for(const [name,source,code]of [['duplicate switch','switch(1){case 1:break;case 1:break;}','CS0152'],['fallthrough','switch(1){case 1:Console.WriteLine(1);case 2:break;}','CS0163'],['nonconstant switch','int a=1;switch(2){case a:break;}','CS9135'],['invalid cast','Console.WriteLine((int)"x");','CS0030']])test('C# diagnostics: '+name,()=>{const r=compile(source);assert(!r.success);assert(r.diagnostics.some(d=>d.code===code),JSON.stringify(r.diagnostics));});
test('C# nonexhaustive switch expression warns and throws for unmatched value',()=>{const r=compileToIL('int n=2;Console.WriteLine(n switch{1=>3});');assert(r.success);assert(r.diagnostics.some(d=>d.code==='CS8509'));assert.equal(new VirtualMachine(r.assembly).run().state,'faulted');});
test('Generators: build-info source participates in binding and execution',()=>{const extensions=new ExtensionDriver().registerGenerator(BuildInfoGenerator),w=workspace('Console.WriteLine(GeneratedBuildInfo.Version());',{extensions,extensionOptions:{version:'3.1'}}),r=w.compile();assert(r.success,JSON.stringify(r.diagnostics));assert.equal(new VirtualMachine(r.image).run().output,'3.1\n');assert.equal(w.generatedDocuments.size,1);assert.equal(w.exportProject().files.length,1);});
test('Generators: source/additional/options snapshots invalidate input cache',()=>{let runs=0;const e=new ExtensionDriver().registerGenerator({id:'Counter',generate(c){runs++;c.addSource('G.cs','class G{}');}}),w=workspace('Console.WriteLine(1);',{extensions:e});w.compile();w.compile();assert.equal(runs,1);w.update('Program.cs','Console.WriteLine(2);',2);w.compile();assert.equal(runs,2);w.extensionOptions.version='x';w.compile();assert.equal(runs,3);w.additionalFiles.push({uri:'a.txt',text:'x'});w.compile();assert.equal(runs,4);});
test('Generators: cache reused when compiler-only options change',()=>{const e=new ExtensionDriver().registerGenerator(BuildInfoGenerator),w=workspace('Console.WriteLine(1);',{extensions:e});w.compile({name:'A'});w.compile({name:'B'});assert.equal(e.metrics.generatorRuns,1);assert.equal(e.metrics.generatorCacheHits,1);});
test('Generators: JSON schema classes are usable by source',()=>{const e=new ExtensionDriver().registerGenerator(JsonSchemaGenerator),w=workspace('var c=new Customer();c.Id=42;Console.WriteLine(c.Id);',{extensions:e,additionalFiles:[{uri:'model.schema.json',text:JSON.stringify({name:'Customer',fields:[{name:'Id',type:'int'}]})}]});const r=w.compile();assert(r.success,JSON.stringify(r.diagnostics));assert.equal(new VirtualMachine(r.image).run().output,'42\n');});
test('Generators: failure rolls back partial output and blocks emission',()=>{const e=new ExtensionDriver().registerGenerator({id:'Broken',generate(c){c.addSource('G.cs','class G{}');throw new Error('failed');}}),w=workspace('Console.WriteLine(1);',{extensions:e}),r=w.compile();assert(!r.success);assert.equal(r.image,null);assert.equal(w.generatedDocuments.size,0);assert(r.diagnostics.some(d=>d.code==='SFGEN001'));});
test('Generators: Promise callbacks explicitly refused',()=>{const e=new ExtensionDriver().registerGenerator({id:'Async',generate(){return Promise.resolve();}}),r=workspace('Console.WriteLine(1);',{extensions:e}).compile();assert(!r.success);assert.match(r.diagnostics[0].message,/synchronous/);});
test('Generators: duplicate paths and traversal rejected',()=>{for(const hint of ['../Bad.cs','/Bad.cs','Bad.txt']){const e=new ExtensionDriver().registerGenerator({id:'Bad',generate:c=>c.addSource(hint,'class Bad{}')});assert(!workspace('Console.WriteLine(1);',{extensions:e}).compile().success);}assert.throws(()=>new ExtensionDriver().registerGenerator(BuildInfoGenerator).registerGenerator(BuildInfoGenerator),/Duplicate/);});
test('Generators: generated-document API cannot be edited as user source',()=>{const w=workspace('Console.WriteLine(1);',{extensions:new ExtensionDriver().registerGenerator(BuildInfoGenerator)});w.compile();assert.throws(()=>w.update('generated://BuildInfo/BuildInfo.g.cs','',2),/generated|read.only/i);});
test('Generators: output budgets reject oversized generators',()=>{const e=new ExtensionDriver({maxGeneratedCharacters:8}).registerGenerator(BuildInfoGenerator),r=workspace('Console.WriteLine(1);',{extensions:e}).compile();assert(!r.success);assert.match(r.diagnostics[0].message,/budget/);});
test('Analyzers: unreferenced locals and empty catches use actual source spans',()=>{const e=new ExtensionDriver().registerAnalyzer(EmptyCatchAnalyzer).registerAnalyzer(UnreferencedLocalAnalyzer),w=workspace('int unused=1;try{}catch(Exception e){}',{extensions:e}),r=w.compile();assert(r.success);assert(r.diagnostics.some(d=>d.code==='SFAN1001'&&d.start===4));assert(r.diagnostics.some(d=>d.code==='SFAN1002'));assert(r.diagnostics.every(d=>d.version===1&&d.uri==='Program.cs'));});
test('Analyzers: severity overrides can suppress or block compilation',()=>{const e=new ExtensionDriver().registerAnalyzer(UnreferencedLocalAnalyzer),w=workspace('int unused=1;',{extensions:e,extensionOptions:{severities:{SFAN1001:'none'}}});assert(!w.compile().diagnostics.some(d=>d.code==='SFAN1001'));w.extensionOptions.severities.SFAN1001='error';assert(!w.compile().success);});
test('Extensions: cancellation precedes callback execution',()=>{let calls=0;const e=new ExtensionDriver().registerGenerator({id:'Cancel',generate(){calls++;}}),w=workspace('Console.WriteLine(1);',{extensions:e}),c=new AbortController();c.abort();assert.throws(()=>w.compile({signal:c.signal}),/cancelled/);assert.equal(calls,0);});
test('Refactoring: bound var to explicit type applies transactionally',()=>{const w=workspace('var number=42;Console.WriteLine(number);'),e=new RefactoringEngine(w,new LanguageService(w)),actions=e.actions('Program.cs',5);const action=actions.find(a=>a.title.startsWith('Use explicit type'));assert(action);assert.equal(action.edits[0].version,1);e.apply(action);assert.match(w.documents.get('Program.cs').source.text,/int number/);assert(w.compile().success);});
test('Refactoring: stale, overlapping and malformed multi-file edits never partially apply',()=>{const w=workspace('int n=1;');w.update('Other.cs','class Other{}',1);const before=w.exportProject();for(const edits of [[{uri:'Program.cs',start:4,end:5,newText:'value',version:1},{uri:'Other.cs',start:6,end:11,newText:'C',version:0}],[{uri:'Program.cs',start:4,end:6,newText:'value',version:1},{uri:'Program.cs',start:5,end:7,newText:'x',version:1}]]){assert.throws(()=>applyWorkspaceEdits(w,edits));assert.deepEqual(w.exportProject(),before);}});
test('Refactoring: successful project rejects a rewrite that introduces compile errors',()=>{const w=workspace('int n=1;'),before=w.exportProject();assert.throws(()=>applyWorkspaceEdits(w,[{uri:'Program.cs',start:6,end:7,newText:'"x"',version:1}]),/compilation errors/);assert.deepEqual(w.exportProject(),before);});
test('Refactoring: rename updates bound references, not strings or comments',()=>{const w=workspace('int n=1;Console.WriteLine(n);Console.WriteLine("n"); // n'),e=new RefactoringEngine(w,new LanguageService(w));e.apply(e.rename('Program.cs',4,'value'));const text=w.documents.get('Program.cs').source.text;assert.match(text,/WriteLine\(value\)/);assert.match(text,/"n"/);assert.match(text,/\/\/ n/);});
test('Formatting: indentation preserves literal and comment text',()=>{const w=workspace('class P\n{\nstatic void Main()\n{\n// { leave me }\nConsole.WriteLine("{ literal }");\n}\n}');const before=w.syntax('Program.cs').tokens.map(t=>t.text),edits=formatDocument(w,'Program.cs');applyWorkspaceEdits(w,edits);assert.deepEqual(w.syntax('Program.cs').tokens.map(t=>t.text),before);assert.match(w.documents.get('Program.cs').source.text,/        Console/);assert.match(w.documents.get('Program.cs').source.text,/\/\/ \{ leave me \}/);});
test('Folding and selection ranges are nested and ignore braces inside literals',()=>{const w=workspace('class P\n{\nstatic void Main()\n{\nConsole.WriteLine("{");\n}\n}');assert.equal(foldingRanges(w,'Program.cs').length,2);const s=selectionRanges(w,'Program.cs',[w.documents.get('Program.cs').source.text.indexOf('WriteLine')])[0];assert(s.parent);assert(s.range.start.line===4);});
async function lsp(server,method,params={}){const r=await server.handle({jsonrpc:'2.0',id:1,method,params});assert(!r.error,JSON.stringify(r.error));return r.result;}
test('LSP: new capabilities correspond to actual handlers',async()=>{const w=workspace('class P\n{\nstatic void Main()\n{\nvar n=42;\nConsole.WriteLine(n);\n}\n}'),server=new LanguageServer({workspace:w}),caps=(await lsp(server,'initialize',{})).capabilities;assert(caps.renameProvider.prepareProvider);assert(caps.foldingRangeProvider&&caps.codeActionProvider&&caps.inlayHintProvider);const doc={uri:'Program.cs'},position={line:4,character:4};assert.equal((await lsp(server,'textDocument/prepareRename',{textDocument:doc,position})).placeholder,'n');assert.equal((await lsp(server,'textDocument/documentHighlight',{textDocument:doc,position})).length,2);assert.equal((await lsp(server,'textDocument/foldingRange',{textDocument:doc})).length,2);assert((await lsp(server,'textDocument/selectionRange',{textDocument:doc,positions:[position]}))[0].parent);assert.equal((await lsp(server,'workspace/symbol',{query:'Main'}))[0].name,'Main');});
test('LSP: code actions carry versions and type hints use inferred types',async()=>{const server=new LanguageServer({workspace:workspace('var number=42;Console.WriteLine(number);')}),textDocument={uri:'Program.cs'},range={start:{line:0,character:0},end:{line:0,character:42}},actions=await lsp(server,'textDocument/codeAction',{textDocument,range:{start:{line:0,character:5},end:{line:0,character:5}},context:{diagnostics:[],only:['refactor']}});const action=actions.find(a=>a.title.startsWith('Use explicit type'));assert(action);assert.equal(action.edit.documentChanges[0].textDocument.version,1);const hints=await lsp(server,'textDocument/inlayHint',{textDocument,range});assert.equal(hints[0].label,': int');assert.equal((await lsp(server,'textDocument/codeAction',{textDocument,range,context:{diagnostics:[],only:['quickfix']}})).length,0);});
test('LSP: versioned rename WorkspaceEdit when client supports documentChanges',async()=>{const server=new LanguageServer({workspace:workspace('int n=1;Console.WriteLine(n);')});await lsp(server,'initialize',{capabilities:{workspace:{workspaceEdit:{documentChanges:true}}}});const edit=await lsp(server,'textDocument/rename',{textDocument:{uri:'Program.cs'},position:{line:0,character:4},newName:'value'});assert.equal(edit.documentChanges[0].textDocument.version,1);assert.equal(edit.documentChanges[0].edits.length,2);});
