import test from 'node:test';
import assert from 'node:assert/strict';
import { Workspace } from '@sharpforge/workspace';
import { LanguageService } from '@sharpforge/language';

test('workspace: unchanged compilation returns cached identity',()=>{const w=new Workspace();w.update('A.cs','Console.WriteLine(1);',1);const a=w.compile();assert.equal(w.compile(),a);assert.equal(w.metrics.parsedDocuments,1);assert.equal(w.metrics.compilationCacheHits,1);});
test('workspace: edit retains other document tree and reparses only changed file',()=>{const w=new Workspace();w.update('A.cs','class A{public static int X=1;}',1);w.update('Program.cs','Console.WriteLine(A.X);',1);w.compile();const tree=w.syntax('A.cs');w.update('Program.cs','Console.WriteLine(A.X+1);',2);const result=w.compile();assert.equal(w.syntax('A.cs'),tree);assert.equal(result.metrics.parsedThisCompilation,1);assert.equal(result.metrics.reusedDocuments,1);});
test('workspace: rejects stale changes',()=>{const w=new Workspace();w.update('A.cs','Console.WriteLine(2);',2);assert.equal(w.update('A.cs','bad',1),false);assert.equal(w.documents.get('A.cs').source.version,2);});
test('workspace: incremental UTF-16 document changes',()=>{const w=new Workspace();w.update('A.cs','int x=1;\r\nConsole.WriteLine(x);',1);w.change('A.cs',[{range:{start:{line:0,character:6},end:{line:0,character:7}},text:'9'}],2);assert.equal(w.documents.get('A.cs').source.text,'int x=9;\r\nConsole.WriteLine(x);');assert.equal(w.compile().success,true);});
test('workspace: pre-cancelled request aborts',()=>{const w=new Workspace();w.update('A.cs','Console.WriteLine(1);');const c=new AbortController();c.abort();assert.throws(()=>w.compile({signal:c.signal}),{name:'AbortError'});});
test('workspace: limits and atomic project imports',()=>{const w=new Workspace({maxDocuments:1,maxDocumentLength:100});w.update('A.cs','Console.WriteLine(1);');assert.throws(()=>w.update('B.cs',''));assert.throws(()=>w.update('A.cs','x'.repeat(101)));assert.throws(()=>w.importProject({format:'sharpforge-project',version:1,files:[{uri:'B.cs',text:'x'.repeat(101)}]}));assert(w.documents.has('A.cs'));});
test('workspace: export/import roundtrip',()=>{const w=new Workspace();w.update('A.cs','Console.WriteLine(1);');const v=new Workspace();v.importProject(w.exportProject());assert.equal(v.compile().success,true);});
function language(text){const w=new Workspace();w.update('Program.cs',text,1);return new LanguageService(w);}
test('language: member completion on unfinished file',()=>{const l=language('int count=1;\nConsole.');assert(l.completions('Program.cs',21).some(x=>x.label==='WriteLine'));});
test('language: local type-aware array completion',()=>{const text='int[] values=new int[2];\nvalues.';const l=language(text);assert(l.completions('Program.cs',text.length).some(x=>x.label==='Length'));});
test('language: definitions, bound references, hover and rename',()=>{const text='int count=1;\nConsole.WriteLine(count);',l=language(text),at=text.lastIndexOf('count')+2;assert.equal(l.definition('Program.cs',at).start,4);assert.equal(l.references('Program.cs',at).length,2);assert.match(l.hover('Program.cs',at).contents,/int count/);assert.equal(l.rename('Program.cs',at,'amount').length,2);assert.throws(()=>l.rename('Program.cs',at,'class'));});
test('language: rename collision rejected',()=>{const l=language('int a=1;int b=2;Console.WriteLine(a+b);');assert.throws(()=>l.rename('Program.cs',4,'b'),/conflict/);});
test('language: no unbound text replacements during rename',()=>{const text='int count=1;Console.WriteLine("count"); // count\nConsole.WriteLine(count);';const l=language(text);assert.equal(l.rename('Program.cs',4,'amount').length,2);});
test('language: cross-file method definition',()=>{const w=new Workspace();w.update('A.cs','class A{public static int F(int x)=>x;}');const text='Console.WriteLine(A.F(1));';w.update('Program.cs',text);const l=new LanguageService(w);assert.equal(l.definition('Program.cs',text.indexOf('.F')+1).uri,'A.cs');});
test('language: document symbols and semantic tokens',()=>{const l=language('class P{static void Main(){int n=1;Console.WriteLine(n);}}');assert(l.documentSymbols('Program.cs').some(s=>s.name==='Main'));assert(l.semanticTokens('Program.cs').some(t=>t.kind==='number'));});
