import test from 'node:test';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {compileToIL,compile} from '@sharpforge/compiler';import {CilVirtualMachine,VirtualMachine,ManagedHeap} from '@sharpforge/runtime';import {AssemblyInspector,inspectAssembly,verifyCilAssembly,formatILDocument,assembleILDocument,decompileMethod,decompileAssembly,decodeInstructions,CilWriter,Reader,Writer,readSignature,readTypeSignature,codedIndex,token,loadAssembly,formatAssembly,readPE} from '@sharpforge/cil';import {managedFixture,arithmeticLibrary} from './managed-fixtures.js';
const compiled=source=>{const r=compileToIL(source,{includeDebug:false});assert(r.success,JSON.stringify(r.diagnostics));return r.assembly;};
const run=(bytes,options={})=>{const r=new CilVirtualMachine(bytes,options).run();assert.equal(r.state,'terminated',r.fault?.stack);return r;};
for(const [name,source,expected] of [
 ['int output','Console.WriteLine(42);','42\n'],['double','Console.WriteLine(1.0/2);','0.5\n'],['loop','for(int i=0;i<3;i++) Console.WriteLine(i);','0\n1\n2\n'],['call','int F(int x){return x*2;}Console.WriteLine(F(7));','14\n'],['object','var c=new C(8); Console.WriteLine(c.X); class C{public int X;public C(int x){X=x;}}','8\n'],['array','int[] a=new int[3];a[1]=9;Console.WriteLine(a[1]);','9\n'],['throw catch','try{throw new Exception("hello");}catch(Exception e){Console.WriteLine(e.Message);}','hello\n'],['null catch','string s=null;try{Console.WriteLine(s.Length);}catch(Exception e){Console.WriteLine("caught");}','caught\n'],['bool boxing','Console.WriteLine("bool="+true);','bool=True\n'],['empty catch','try{}catch(Exception e){} Console.WriteLine(1);','1\n'],['string ops','Console.WriteLine(" abc ".Trim().ToUpper());','ABC\n'],['ceil','Console.WriteLine(Math.Ceiling(1.2));','2\n']
])test('Managed DLL without #SF: '+name,()=>{const bytes=compiled(source);assert(!new AssemblyInspector(bytes).metadata.streams.has('#SF'));assert.equal(run(bytes).output,expected);});
test('Independent managed DLL: methods can be invoked without an entry point',()=>{const bytes=arithmeticLibrary(),s=inspectAssembly(bytes);assert.equal(s.entryPoint,0);assert.equal(s.methods.length,3);assert.throws(()=>new CilVirtualMachine(bytes),/no entry point/);assert.equal(run(bytes,{methodToken:'Fixture.Program::Add',arguments:[19,23]}).returnValue,42);assert.equal(run(bytes,{methodToken:'Square',arguments:[9]}).returnValue,81);assert.equal(run(bytes,{methodToken:'Hello'}).output,'Hello from ordinary CIL\n');});
test('Independent managed DLL: 64-bit arithmetic stays exact',()=>{const b=managedFixture({methods:[{name:'Main',result:'long',body:w=>w.op('ldc.i8',9007199254740993n).op('ldc.i8',11n).op('add').op('ret')}]});assert.equal(run(b).returnValue,9007199254741004n);});
test('Independent managed DLL: short floating literal and conversion',()=>{const b=managedFixture({methods:[{name:'Main',result:'int',body:w=>w.op('ldc.r4',3.9).op('conv.i4').op('ret')}]});assert.equal(run(b).returnValue,3);});
test('Independent managed DLL: switch table dispatch',()=>{const b=managedFixture({methods:[{name:'Main',parameters:['int'],result:'int',body:w=>w.op('ldarg.0').op('switch',['zero','one']).op('ldc.i4',99).op('ret').mark('zero').op('ldc.i4',10).op('ret').mark('one').op('ldc.i4',20).op('ret')}]});for(const [n,expected]of [[0,10],[1,20],[2,99],[-1,99]])assert.equal(run(b,{arguments:[n]}).returnValue,expected);});
test('Independent managed DLL: managed address into local',()=>{const b=managedFixture({methods:[{name:'Main',result:'int',locals:['int'],body:w=>w.op('ldloca.s',0).op('ldc.i4',42).op('stind.i4').op('ldloc.0').op('ret')}]});assert.equal(run(b).returnValue,42);});
test('Independent managed DLL: static initializer executes exactly once',()=>{const b=managedFixture({fields:[{name:'Value'}],methods:[{name:'Main',result:'int',body:(w,c)=>w.op('ldsfld',c.fields.Value).op('ldsfld',c.fields.Value).op('add').op('ret')},{name:'.cctor',result:'void',body:(w,c)=>w.op('ldc.i4',21).op('stsfld',c.fields.Value).op('ret')}]});assert.equal(run(b).returnValue,42);});
test('Independent managed DLL: finally executes on leave',()=>{const b=managedFixture({methods:[{name:'Main',result:'int',locals:['int'],body:w=>w.mark('try').op('ldc.i4',7).op('stloc.0').op('leave','done').mark('finally').op('ldloc.0').op('ldc.i4.1').op('add').op('stloc.0').op('endfinally').mark('done').op('ldloc.0').op('ret'),handlers:l=>[{flags:2,start:l.get('try'),end:l.get('finally'),target:l.get('finally'),handlerEnd:l.get('done')}] }]});assert.equal(run(b).returnValue,8);assert.equal(new AssemblyInspector(b).getMethod(token(6,1)).handlers[0].kind,'finally');});
test('Independent managed DLL: checked overflow becomes a managed fault',()=>{const b=managedFixture({methods:[{name:'Main',result:'int',body:w=>w.op('ldc.i4',2147483647).op('ldc.i4.1').op('add.ovf').op('ret')}]});const r=new CilVirtualMachine(b).run();assert.equal(r.state,'faulted');assert.equal(r.fault.name,'OverflowException');});
test('Independent managed DLL: unsigned division uses unsigned operands',()=>{const b=managedFixture({methods:[{name:'Main',result:'int',body:w=>w.op('ldc.i4.m1').op('ldc.i4.2').op('div.un').op('ret')}]});assert.equal(run(b).returnValue,2147483647);});
test('Direct CIL: hard instruction limit',()=>{const b=managedFixture({methods:[{name:'Main',result:'void',body:w=>w.mark('again').op('br','again')}]});const r=new CilVirtualMachine(b,{maxInstructions:50}).run();assert.equal(r.fault.name,'InstructionLimitException');assert(r.stats.instructions<=51);});
test('Direct CIL: hard output limit',()=>{const r=new CilVirtualMachine(compiled('Console.WriteLine("too long");'),{maxOutputCharacters:3}).run();assert.equal(r.fault.name,'OutputLimitException');assert.equal(r.output,'');});
test('Direct CIL: unknown external method is refused before output',()=>{const b=managedFixture({methods:[{name:'Main',result:'void',body:(w,c)=>w.op('call',c.member('Dangerous.Native','Launch','void',[])).op('ret')}]});const r=verifyCilAssembly(b);assert(!r.success);assert.match(JSON.stringify(r.issues),/inspection-only|external|intrinsic/i);assert.throws(()=>new CilVirtualMachine(b),/verification failed/);assert.match(formatAssembly(b),/Dangerous.Native/);});
test('Direct CIL: native pointer instructions remain inspectable, not executable',()=>{const b=managedFixture({methods:[{name:'Main',result:'void',body:w=>w.op('ldc.i4.1').op('localloc').op('pop').op('ret')}]});assert.match(formatAssembly(b),/localloc/);assert(!verifyCilAssembly(b).success);});
test('Direct CIL: invalid local slot and stack underflow rejected',()=>{for(const body of [w=>w.op('ldloc.3').op('pop').op('ret'),w=>w.op('pop').op('ret')]){const b=managedFixture({methods:[{name:'Main',body}]});assert(!verifyCilAssembly(b).success);}});
test('Direct CIL: host arguments use strict declared types and arity',()=>{const b=arithmeticLibrary();for(const args of [[1],['1',2],[2147483648,1],[{},1]])assert.throws(()=>new CilVirtualMachine(b,{methodToken:token(6,1),arguments:args}));});
test('IL text: every method rebuilt; changed constants actually execute',()=>{const b=managedFixture(),text=formatILDocument(b);const a=assembleILDocument(text.replace('ldc.i4 42','ldc.i4 77'));assert.equal(run(a.bytes).returnValue,77);assert.equal(a.methods,1);assert(!new AssemblyInspector(a.bytes).metadata.streams.has('#SF'));});
test('IL text: changed bodies invalidate stale debug-profile metadata', () => {
  const bytes = compileToIL('Console.WriteLine(42);').assembly;
  const rebuilt = assembleILDocument(formatILDocument(bytes).replace('ldc.i4 42', 'ldc.i4 43'));
  assert.equal(run(rebuilt.bytes).output, '43\n');
  assert.throws(() => loadAssembly(rebuilt.bytes), /arbitrary .NET assembly/);
});
test('IL text: long, branch and switch round trips',()=>{const b=managedFixture({methods:[{name:'Main',result:'long',body:w=>w.op('ldc.i8',-9223372036854775807n).op('ret')}]});const a=assembleILDocument(formatILDocument(b));assert.equal(run(a.bytes).returnValue,-9223372036854775807n);});
test('IL text: catches round trip',()=>{const b=compiled('try{throw new Exception("x");}catch(Exception e){Console.WriteLine(e.Message);}');assert.equal(run(assembleILDocument(formatILDocument(b)).bytes).output,'x\n');});
test('IL text: omitted or duplicate methods are never read from image fallback',()=>{const text=formatILDocument(managedFixture());const start=text.indexOf('.method');assert.throws(()=>assembleILDocument(text.slice(0,start)),/method|body/i);assert.throws(()=>assembleILDocument(text+'\n'+text.slice(start)),/duplicate/i);});
test('IL text: undefined labels and invalid opcodes are rejected',()=>{const text=formatILDocument(managedFixture());assert.throws(()=>assembleILDocument(text.replace('ldc.i4 42','br IL_ffff')),/label/i);assert.throws(()=>assembleILDocument(text.replace('ldc.i4 42','invented.op')),/opcode/i);});
test('Decompiler: simple independently authored Add is reconstructable C#',()=>{const b=arithmeticLibrary(),d=decompileMethod(b,token(6,1));assert(d.complete,d.source);assert.equal(d.language,'csharp');const r=compile(`class P { ${d.source} static void Main(){Console.WriteLine(Add(20,22));} }`);assert(r.success,JSON.stringify(r.diagnostics));assert.equal(new VirtualMachine(r.image).run().output,'42\n');});
test('Decompiler: mutable local loads captured before writes',()=>{const b=managedFixture({methods:[{name:'Main',result:'int',locals:['int'],body:w=>w.op('ldc.i4.1').op('stloc.0').op('ldloc.0').op('ldc.i4.2').op('stloc.0').op('ret')}]});const d=decompileMethod(b,token(6,1));assert(d.complete);assert.match(d.source,/stack\d+ = v0/);assert.equal(run(b).returnValue,1);});
test('Decompiler: EH returns full IL and explicit fallback, not fake C#',()=>{const b=compiled('try{Console.WriteLine(1);}catch(Exception e){Console.WriteLine(2);}');const i=new AssemblyInspector(b),d=decompileMethod(i,i.pe.entryPoint);assert.equal(d.language,'cil');assert.equal(d.complete,false);assert.match(d.source,/IL_.*:/);assert(d.diagnostics.length);assert.equal(decompileAssembly(b).total,i.methods.size);});
test('Decoder: i64, r4 and standard two-byte operations',()=>{const code=new CilWriter().op('ldc.i8',-4n).op('ldc.r4',1.25).op('readonly.').op('ret').finish(),decoded=decodeInstructions(code);assert.equal(decoded[0].operand,-4n);assert.equal(decoded[1].operand,1.25);assert.equal(decoded[2].name,'readonly.');});
test('Decoder: branch into operand rejected',()=>assert.throws(()=>decodeInstructions(Uint8Array.from([0x2b,1,0x20,42,0,0,0,0x2a])),/branch|target/i));
test('Metadata: generic method spec signature uses its blob column',()=>{const b=managedFixture({decorate:c=>c.md.add(43,[codedIndex('MethodDefOrRef',c.methods.Main),c.md.blob(Uint8Array.from([0x0a,1,8]))])});const i=new AssemblyInspector(b);assert.deepEqual(i.signature(token(43,1)).arguments,['int']);assert.deepEqual(i.resolveToken(token(43,1)).genericArguments,['int']);});
test('Metadata: generic variables, arrays, byrefs and function pointers inspect',()=>{const md={typeName:()=> 'List`1'};assert.equal(readTypeSignature(Uint8Array.from([0x13,2]),md),'!2');assert.equal(readTypeSignature(Uint8Array.from([0x10,8]),md),'int&');assert.equal(readTypeSignature(Uint8Array.from([0x1d,8]),md),'int[]');assert.match(readTypeSignature(Uint8Array.from([0x1b,0,1,8,8]),md),/method|fnptr/);});
test('PE: inspection rejects malformed and truncated user DLLs',()=>{const b=arithmeticLibrary();for(const length of [0,1,30,127,511,b.length-1])assert.throws(()=>new AssemblyInspector(b.subarray(0,length)));});
test('GC: strong handles retain; weak handles clear after strong release',()=>{const h=new ManagedHeap(),v=h.string('retained'),strong=h.createHandle(v),weak=h.createHandle(v,{weak:true});h.collect();assert.equal(h.getHandle(weak),v);h.releaseHandle(strong);h.collect();assert.equal(h.getHandle(weak),null);assert.equal(h.getHandle(strong),null);});
test('GC: scratch marks reused; foreign handles rejected',()=>{const a=new ManagedHeap(),b=new ManagedHeap(),v=a.string('a'),root=a.createHandle(v),foreign=b.createHandle(b.string('b'));a.collect();const marks=a.marks;a.collect();assert.equal(a.marks,marks);assert.equal(a.getHandle(foreign),null);assert.equal(a.releaseHandle(foreign),false);assert.equal(a.getHandle(root),v);assert(a.stats.markedObjects>0);assert(a.stats.rootsScanned>0);});
test('CLI: inspect, invoke, decompile, editable IL, assemble, exec ordinary DLL',()=>{const dir=mkdtempSync(join(tmpdir(),'sf-managed-'));try{const dll=join(dir,'fixture.dll'),il=join(dir,'fixture.sf.il'),edited=join(dir,'edited.dll');writeFileSync(dll,arithmeticLibrary());const cli=(...args)=>execFileSync(process.execPath,['apps/cli/main.js',...args],{encoding:'utf8'});assert.match(cli('inspect',dll),/Arithmetic/);assert.match(cli('invoke',dll,'--method','Add','--args','[20,22]'),/Return: 42/);assert.match(cli('decompile',dll,'--method','Add','--args','[0,0]'),/return/);cli('il-export',dll,'-o',il);cli('il-assemble',il,'-o',edited);assert.match(cli('invoke',edited,'--method','Add','--args','[20,22]'),/Return: 42/);}finally{rmSync(dir,{recursive:true,force:true});}});

for(const [type,constant,expected]of [['byte',511,255],['sbyte',255,-1],['ushort',131071,65535],['short',65535,-1]])test('Direct CIL storage: '+type+' local truncates and extends',()=>{
 const b=managedFixture({methods:[{name:'Main',result:'int',locals:[type],body:w=>w.op('ldc.i4',constant).op('stloc.0').op('ldloc.0').op('ret')}]});assert.equal(run(b).returnValue,expected);
});
for(const [type,ldop,constant,expected]of [['System.Byte','ldelem.u1',511,255],['System.SByte','ldelem.i1',255,-1]])test('Direct CIL storage: '+ldop+' array extends correctly',()=>{
 const b=managedFixture({methods:[{name:'Main',result:'int',body:(w,c)=>w.op('ldc.i4.1').op('newarr',c.resolve(type)).op('dup').op('ldc.i4.0').op('ldc.i4',constant).op('stelem.i1').op('ldc.i4.0').op(ldop).op('ret')}]});assert.equal(run(b).returnValue,expected);
});
test('Direct CIL storage: indirect byte store truncates before unsigned load',()=>{const b=managedFixture({methods:[{name:'Main',result:'int',locals:['byte'],body:w=>w.op('ldloca.s',0).op('ldc.i4',511).op('stind.i1').op('ldloca.s',0).op('ldind.u1').op('ret')}]});assert.equal(run(b).returnValue,255);});
for(const [type,value,expected]of [['uint',4294967295,4294967295],['ulong','18446744073709551615',18446744073709551615n],['bool',true,true]])test('Direct CIL host result keeps '+type+' identity',()=>{const b=managedFixture({methods:[{name:'Identity',parameters:[type],result:type,body:w=>w.op('ldarg.0').op('ret')}]});assert.equal(run(b,{arguments:[value]}).returnValue,expected);});
test('Direct CIL: string[] Main defaults to an empty argument array',()=>{const b=managedFixture({methods:[{name:'Main',parameters:['string[]'],result:'int',body:w=>w.op('ldarg.0').op('ldlen').op('ret')}]});assert.equal(run(b).returnValue,0);});
test('CLI: no dummy arguments required for method decompilation or string[] entry point',()=>{const dir=mkdtempSync(join(tmpdir(),'sf-main-'));try{const dll=join(dir,'fixture.dll'),cli=(...args)=>execFileSync(process.execPath,['apps/cli/main.js',...args],{encoding:'utf8'});writeFileSync(dll,arithmeticLibrary());assert.match(cli('decompile',dll,'--method','Add'),/return/);writeFileSync(dll,managedFixture({methods:[{name:'Main',parameters:['string[]'],result:'int',body:w=>w.op('ldarg.0').op('ldlen').op('ret')}] }));assert.equal(cli('exec',dll),'');}finally{rmSync(dir,{recursive:true,force:true});}});
