import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, mkdir, readFile, rm, symlink, lstat } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';
import { request as httpRequest } from 'node:http';
const rawStatus=(url,headers)=>new Promise((resolve,reject)=>{const req=httpRequest(url,{headers},res=>{res.resume();resolve(res.statusCode);});req.on('error',reject);req.end();});
import { NativeWorkspace, NativeMSBuild, startMSBuildHost, hashBytes } from '../packages/msbuild/src/node.js';
const fixture=fileURLToPath(new URL('./fixtures/msbuild-process-simulator.mjs',import.meta.url));
const simulator=(command,args,options)=>spawn(process.execPath,[fixture,...args],options);
async function setup(t){const root=await mkdtemp(join(tmpdir(),'sharpforge-msbuild-'));t.after(()=>rm(root,{recursive:true,force:true}));await mkdir(join(root,'App'));await writeFile(join(root,'App','App.csproj'),'<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup></Project>');await writeFile(join(root,'App','Program.cs'),'Console.WriteLine(42);');await writeFile(join(root,'App.slnx'),'<Solution><Project Path="App/App.csproj" /></Solution>');return NativeWorkspace.open(root);}
const request=(extra={})=>({project:'App/App.csproj',trusted:true,...extra});
test('Workspace scan lists build/source files, not outputs or ignored folders',async t=>{const ws=await setup(t);for(const dir of ['bin','obj','.git','.sharpforge','.packages','node_modules']){await mkdir(join(ws.root,dir));await writeFile(join(ws.root,dir,'Hidden.cs'),'x');}const scan=await ws.scan();assert.deepEqual(scan.projects,['App/App.csproj']);assert.deepEqual(scan.solutions,['App.slnx']);assert.equal(scan.files.length,3);});
test('Native read returns content and SHA-256; existing saves use actual disk data',async t=>{const ws=await setup(t),file=await ws.read('App/Program.cs');assert.equal(file.hash,hashBytes(file.text));const r=await ws.save([{path:file.path,text:'changed',expectedHash:file.hash}]);assert.equal(r.atomic,false);assert.equal((await ws.read(file.path)).hash,r.written[0].hash);});
test('Preflight checks all files before write on a multi-file conflict',async t=>{const ws=await setup(t),a=await ws.read('App/Program.cs'),b=await ws.read('App/App.csproj');await writeFile(join(ws.root,b.path),'<Project/>');await assert.rejects(()=>ws.save([{path:a.path,text:'new',expectedHash:a.hash},{path:b.path,text:'<Project />',expectedHash:b.hash}]),e=>e.status===409);assert.equal((await ws.read(a.path)).text,a.text);});
test('Missing hash, duplicate paths, invalid XML and invalid file types fail without writes',async t=>{const ws=await setup(t),a=await ws.read('App/Program.cs');for(const changes of [[{path:a.path,text:'x'}],[{path:a.path,text:'x',expectedHash:a.hash},{path:a.path,text:'y',expectedHash:a.hash}],[{path:'App/B.csproj',text:'<Project>',expectedHash:null}],[{path:'App/tool.exe',text:'x',expectedHash:null}]])await assert.rejects(()=>ws.save(changes));assert.equal((await ws.read(a.path)).text,a.text);});
test('Create project files is exclusive and does not overwrite existing files',async t=>{const ws=await setup(t);await ws.save([{path:'New.csproj',text:'<Project/>',expectedHash:null}]);await assert.rejects(()=>ws.save([{path:'New.csproj',text:'<Project />',expectedHash:null}]),/conflict/);});
test('Workspace APIs reject traversal and reserved paths',async t=>{const ws=await setup(t);for(const path of ['../x','/tmp/x','App/../../x','.git/config','.sharpforge/secret','node_modules/x.cs'])await assert.rejects(()=>ws.read(path));});
test('Symlink files and ancestor folders are never followed by API reads/saves',async t=>{const ws=await setup(t);await symlink(join(ws.root,'App'),join(ws.root,'Link'),process.platform==='win32'?'junction':'dir');await assert.rejects(()=>ws.read('Link/Program.cs'),/Symbolic/);await assert.rejects(()=>ws.save([{path:'Link/New.cs',text:'x',expectedHash:null}]),/Symbolic/);assert(!(await ws.scan()).files.some(f=>f.path.startsWith('Link')));});
test('Native operations require host and request trust, including evaluation',async t=>{const ws=await setup(t);for(const [host,requestTrust]of [[false,true],[true,false]]){const engine=new NativeMSBuild(ws,{trusted:host,spawnProcess:simulator});await assert.rejects(()=>engine.start(request({action:'evaluate',trusted:requestTrust})),e=>e.status===403);assert.equal(engine.jobs.size,0);}});
test('Real child-process transport collects UTF-8 logs, diagnostics and artifacts (simulated engine)',async t=>{const ws=await setup(t),engine=new NativeMSBuild(ws,{trusted:true,spawnProcess:simulator});const job=await engine.start(request({binaryLog:true}));const r=await engine.wait(job.id);assert.equal(r.status,'succeeded',r.error);assert(r.events.map(e=>e.text).join('').includes('😀 café'));assert.equal(r.diagnostics.length,1);assert.equal(r.diagnostics[0].workspacePath,'App/App.csproj');assert(r.artifacts.some(a=>a.path.endsWith('Fixture.dll')));assert.deepEqual([...await engine.artifact(r.id,r.artifacts.find(a=>a.kind==='binlog').path)],[1,2,3,4]);await assert.rejects(()=>engine.artifact(r.id,'App/Program.cs'));assert.equal(engine.active,null);});
test('Evaluation result and inspection files are exposed with actual invocation (simulator)',async t=>{const ws=await setup(t),engine=new NativeMSBuild(ws,{trusted:true,spawnProcess:simulator});for(const [action,key]of [['evaluate','Properties'],['preprocess','preprocessedText'],['targets','targetsText']]){const j=await engine.start(request({action})),r=await engine.wait(j.id);assert.equal(r.status,'succeeded',r.error);assert(r.result[key]);assert.equal(r.request.action,action);}});
test('Nonzero exit is failure even when output is otherwise valid',async t=>{const ws=await setup(t),engine=new NativeMSBuild(ws,{trusted:true,spawnProcess:simulator}),j=await engine.start(request({properties:{Fixture:'fail'}})),r=await engine.wait(j.id);assert.equal(r.status,'failed');assert.equal(r.exitCode,1);assert.equal(r.diagnostics[0].code,'CS1002');});
test('Missing native executable is explicit; never substitutes the browser compiler',async t=>{const ws=await setup(t),engine=new NativeMSBuild(ws,{trusted:true,executable:join(ws.root,'nonexistent-sdk')});assert.equal((await engine.probe()).available,false);const j=await engine.start(request()),r=await engine.wait(j.id);assert.equal(r.status,'failed');assert.match(r.error,/not substituted/);});
test('Cancellation terminates an actual long-running child while a queued operation completes',async t=>{const ws=await setup(t),engine=new NativeMSBuild(ws,{trusted:true,spawnProcess:simulator});t.after(()=>engine.close());const j=await engine.start(request({properties:{Fixture:'sleep'}}));const queued=await engine.start(request());assert.equal(queued.status,'queued');await new Promise(r=>setTimeout(r,70));engine.cancel(j.id);const r=await engine.wait(j.id);assert.equal(r.status,'cancelled');assert.equal(r.cancelReason,'user');assert.equal((await engine.wait(queued.id)).status,'succeeded');assert.equal(engine.active,null);});
test('Output limits cancel noisy child instead of unbounded capture',async t=>{const ws=await setup(t),engine=new NativeMSBuild(ws,{trusted:true,spawnProcess:simulator,maxOutputBytes:100000});t.after(()=>engine.close());const j=await engine.start(request({properties:{Fixture:'flood'}})),r=await engine.wait(j.id);assert.equal(r.status,'cancelled');assert.equal(r.cancelReason,'output-limit');assert.match(r.error,/output limit/);assert(r.events.reduce((n,e)=>n+e.text.length,0)<=100000);});
test('Timeout cancels jobs and host shutdown prevents future launches',async t=>{const ws=await setup(t),engine=new NativeMSBuild(ws,{trusted:true,spawnProcess:simulator,timeoutMs:100});const j=await engine.start(request({properties:{Fixture:'sleep'}})),r=await engine.wait(j.id);assert.equal(r.cancelReason,'timeout');await engine.close();await assert.rejects(()=>engine.start(request()),/closing/);});
test('Completed job retention is bounded and cursors do not repeat logs',async t=>{const ws=await setup(t),engine=new NativeMSBuild(ws,{trusted:true,spawnProcess:simulator,maxJobs:1});const a=await engine.start(request());const old=await engine.wait(a.id);assert.equal(engine.snapshot(a.id,old.nextCursor).events.length,0);const b=await engine.start(request());await engine.wait(b.id);assert.equal(engine.jobs.size,1);assert.throws(()=>engine.snapshot(a.id));assert.throws(()=>engine.snapshot(b.id,-1));});
async function hostSetup(t){const ws=await setup(t),staticRoot=join(ws.root,'ui');await mkdir(staticRoot);await writeFile(join(staticRoot,'index.html'),'<html>Studio fixture</html>');const host=await startMSBuildHost({root:ws.root,studioRoot:staticRoot,port:0,trusted:true,spawnProcess:simulator});t.after(()=>host.close());const headers={Authorization:'Bearer '+host.token};return {host,ws,headers};}
test('Loopback HTTP host authenticates APIs, enforces same-origin and does not leak token',async t=>{const{host,headers}=await hostSetup(t);const plain=await fetch(host.origin);assert.equal(plain.status,200);assert.match(plain.headers.get('content-security-policy'),/frame-ancestors 'none'/);assert.match(plain.headers.get('content-security-policy'),/img-src 'self' data: blob:/);assert.match(plain.headers.get('content-security-policy'),/script-src 'self' 'wasm-unsafe-eval'; worker-src 'self' blob:;/);assert(!(await plain.text()).includes(host.token));assert.equal((await fetch(host.origin+'/api/msbuild/workspace')).status,401);assert.equal((await fetch(host.origin+'/api/msbuild/workspace',{headers:{...headers,Origin:'https://evil.invalid'}})).status,403);assert.equal((await rawStatus(host.origin+'/api/msbuild/workspace',{...headers,Host:'evil.invalid'})),403);const data=await(await fetch(host.origin+'/api/msbuild/capabilities',{headers})).json();assert.equal(data.protocolVersion,1);assert(data.available);assert.match(data.version,/TEST PROCESS/);assert(!JSON.stringify(data).includes(host.token));});
test('HTTP job start/poll/artifact and JSON file writes use real API routes (simulated engine)',async t=>{const{host,headers}=await hostSetup(t),jsonHeaders={...headers,'Content-Type':'application/json'};const response=await fetch(host.origin+'/api/msbuild/jobs',{method:'POST',headers:jsonHeaders,body:JSON.stringify(request({action:'evaluate'}))});assert.equal(response.status,202);const started=await response.json();await host.engine.wait(started.id);const done=await(await fetch(host.origin+'/api/msbuild/jobs/'+started.id,{headers})).json();assert.equal(done.status,'succeeded');const artifact=done.artifacts[0];assert.equal((await fetch(host.origin+'/api/msbuild/jobs/'+done.id+'/artifact?path='+encodeURIComponent(artifact.path),{headers})).status,200);const file=await(await fetch(host.origin+'/api/msbuild/file?path=App%2FProgram.cs',{headers})).json();const saved=await fetch(host.origin+'/api/msbuild/files',{method:'POST',headers:jsonHeaders,body:JSON.stringify({changes:[{path:file.path,text:'new text',expectedHash:file.hash}]})});assert.equal(saved.status,200);assert.equal((await host.workspace.read(file.path)).text,'new text');});
test('HTTP rejects non-JSON mutations, untrusted operations, invalid cursors and saves during a build',async t=>{const{host,headers}=await hostSetup(t),url=host.origin+'/api/msbuild';assert.equal((await fetch(url+'/jobs',{method:'POST',headers,body:'{}'})).status,415);assert.equal((await fetch(url+'/jobs',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(request({trusted:false}))})).status,403);const j=await host.engine.start(request({properties:{Fixture:'sleep'}}));assert.equal((await fetch(url+'/jobs/'+j.id+'?after=x',{headers})).status,400);assert.equal((await fetch(url+'/files',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:'{"changes":[]}'})).status,409);host.engine.cancel(j.id);await host.engine.wait(j.id);});
for(const encoding of ['utf-8-bom','utf-16le','utf-16be'])test('Native saves preserve '+encoding+' bytes and SHA-256',async t=>{const ws=await setup(t),text='<Project><!-- café 😀 --></Project>';let bytes=Buffer.from(text,encoding==='utf-8-bom'?'utf8':'utf16le');if(encoding==='utf-16be')bytes=bytes.swap16();bytes=Buffer.concat([Buffer.from(encoding==='utf-8-bom'?[239,187,191]:encoding==='utf-16be'?[254,255]:[255,254]),bytes]);await writeFile(join(ws.root,'Encoding.csproj'),bytes);const loaded=await ws.read('Encoding.csproj');assert.equal(loaded.text,text);const report=await ws.save([{path:loaded.path,text:loaded.text,expectedHash:loaded.hash}]);assert.deepEqual(await readFile(join(ws.root,'Encoding.csproj')),bytes);assert.equal(report.written[0].hash,loaded.hash);});
test('Native MSBuild response files must be workspace files before process creation',async t=>{const ws=await setup(t),engine=new NativeMSBuild(ws,{trusted:true,spawnProcess:simulator});await assert.rejects(()=>engine.start(request({arguments:['@missing.rsp']})));await writeFile(join(ws.root,'flags.rsp'),'-p:Configuration=Release');const j=await engine.start(request({arguments:['@flags.rsp']})),r=await engine.wait(j.id);assert(r.invocation.arguments.includes('@flags.rsp'));assert.equal(r.status,'succeeded');});
test('Terminal status is not visible before output discovery completes',async t=>{const ws=await setup(t),original=ws.outputs.bind(ws);let release,entered;const gate=new Promise(r=>release=r),seen=new Promise(r=>entered=r);ws.outputs=async(...args)=>{entered();await gate;return original(...args);};const engine=new NativeMSBuild(ws,{trusted:true,spawnProcess:simulator}),j=await engine.start(request());await seen;assert.equal(engine.snapshot(j.id).status,'running');assert.equal(engine.active,j.id);release();const result=await engine.wait(j.id);assert.equal(result.status,'succeeded');assert(result.artifacts.some(a=>a.path.endsWith('Fixture.dll')));});

for(const [description,file,project,expected]of [
 ['project basename diagnostic','App.csproj','App/App.csproj','App/App.csproj'],
 ['project-relative compiler filename','Program.cs','App/App.csproj','App/Program.cs'],
 ['project-relative generated file','obj/Debug/Generated.g.cs','App/App.csproj','App/obj/Debug/Generated.g.cs'],
 ['workspace-prefixed filename','App/Program.cs','App/App.csproj','App/Program.cs'],
 ['linked source in sibling directory','../Shared/Value.cs','App/App.csproj','Shared/Value.cs'],
 ['target-framework project suffix','Program.cs','App/App.csproj::TargetFramework=net10.0','App/Program.cs'],
 ['external linked source remains not navigable','../../Outside.cs','App/App.csproj',null],
]) test('Native diagnostic resolves '+description,async t=>{const ws=await setup(t),engine=new NativeMSBuild(ws),job={request:{project:'App.slnx'},diagnostics:[],diagnosticKeys:new Set()};engine.diagnostic(job,`${file}(2,3): error CS1002: Semicolon expected [${project}]`);assert.equal(job.diagnostics[0].workspacePath,expected);});
