import test from 'node:test';
import assert from 'node:assert/strict';
import { normalizeBuildRequest, parsePropertyLines, workspacePath, escapeMSBuild, parseDiagnosticLine, parseEvaluationOutput, BUILD_ACTIONS, MSBuildClient } from '../packages/msbuild/src/index.js';
import { createInvocation } from '../packages/msbuild/src/node.js';
const req=(extra={})=>({project:'App/App.csproj',trusted:true,...extra});
for(const action of BUILD_ACTIONS)test('MSBuild contract supports '+action,()=>{assert.equal(normalizeBuildRequest(req({action,targets:['Custom']})).action,action);});
for(const path of ['../outside.csproj','/tmp/X.csproj','C:\\X.csproj','a/../X.csproj','a//X.csproj','a/./X.csproj','-something.csproj','https://x.csproj','a\0.csproj',''])test('MSBuild rejects invalid workspace path '+JSON.stringify(path),()=>assert.throws(()=>workspacePath(path)));
for(const extra of [{action:'exec'},{project:'input.cs'},{properties:[]},{maxNodes:0},{maxNodes:65},{maxNodes:1.2},{verbosity:'verbose'},{arguments:['not-a-switch']},{arguments:['-p:X=a\nb']},{targets:['x;Build']},{propertyNames:['A,B']},{itemNames:['*']},{trusted:'true'},{restore:1},{action:'target'},{properties:{A:'1',a:'2'}}])test('MSBuild request rejects '+JSON.stringify(extra),()=>assert.throws(()=>normalizeBuildRequest(req(extra))));
test('Global property parser preserves equals, spaces, Unicode, no shell interpretation',()=>{assert.deepEqual({...parsePropertyLines(' # comment\nDefineConstants=A;B\nMessage= hi=😀 \n')},{DefineConstants:'A;B',Message:' hi=😀 '});assert.throws(()=>parsePropertyLines('bad line'));assert.throws(()=>parsePropertyLines('A;B=x'));});
test('Properties escape all MSBuild special characters without shell quoting',()=>{assert.equal(escapeMSBuild('a;b,%$@()\'"?*'),'a%3Bb%2C%25%24%40%28%29%27%22%3F%2A');});
test('Node invocation preserves actual engine and project path; build flags global properties',()=>{const x=createInvocation(req({action:'build',configuration:'Release',platform:'Any CPU',framework:'net10.0',properties:{DefineConstants:'ONE;TWO'},restore:true,binaryLog:true,graphBuild:true,maxNodes:4}),{projectPath:'/tmp/space dir/App.csproj',jobDirectory:'/tmp/logs',executable:'/sdk/dotnet'});assert.equal(x.executable,'/sdk/dotnet');assert.equal(x.args[0],'msbuild');assert.equal(x.args[1],'/tmp/space dir/App.csproj');assert(x.args.includes('-p:DefineConstants=ONE%3BTWO'));assert(x.args.includes('-p:Platform=Any CPU'));assert(x.args.includes('-restore'));assert(x.args.includes('-graphBuild'));assert.equal(x.args.at(-1),'-nodeReuse:false');assert(x.args.some(a=>a.includes('ProjectImports=None')));});
test('MSBuild.exe engine omits dotnet subcommand and forwards advanced switches separately',()=>{const x=createInvocation(req({arguments:['-warnAsError','-detailedSummary']}),{engine:'msbuild',executable:'MSBuild.exe'});assert.equal(x.args[0],'App/App.csproj');assert(x.args.includes('-warnAsError'));});
test('Evaluation emits JSON queries without targets, restore or graph execution by default',()=>{const x=createInvocation(req({action:'evaluate',propertyNames:['AssemblyName'],itemNames:[],restore:true}),{jobDirectory:'/x'});assert(x.args.includes('-getProperty:AssemblyName,MSBuildProjectFullPath,MSBuildVersion'));assert(!x.args.some(a=>a.startsWith('-t:')||a==='-restore'));});
for(const [action,target]of [['build','Build'],['rebuild','Rebuild'],['restore','Restore'],['pack','Pack'],['publish','Publish'],['clean','Clean'],['test','VSTest']])test('Native '+action+' calls '+target,()=>{assert(createInvocation(req({action}),{jobDirectory:'/x'}).args.includes('-t:'+target));});
test('custom targets and requested target results are explicit',()=>{const x=createInvocation(req({action:'target',targets:['Prepare','Compile'],resultTargets:['Compile']}),{jobDirectory:'/x'});assert(x.args.includes('-t:Prepare;Compile'));assert(x.args.includes('-getTargetResult:Compile'));});
test('preprocessed and target listing files use the owner-provided job directory',()=>{assert(createInvocation(req({action:'preprocess'}),{jobDirectory:'/logs'}).args.some(a=>a.endsWith('expanded.xml')));assert(createInvocation(req({action:'targets'}),{jobDirectory:'/logs'}).args.some(a=>a.endsWith('targets.txt')));});
for(const [line,expected]of [
 ['1>C:\\Code Dir\\App.cs(12,7): error CS1002: ; expected [C:\\Code Dir\\App.csproj]',{severity:'error',code:'CS1002',line:12,column:7,file:'C:\\Code Dir\\App.cs'}],
 ['/tmp/A.cs(3,4,3,8): warning CS0168: unused [/tmp/App.csproj]',{severity:'warning',code:'CS0168',line:3,column:4,endColumn:8}],
 ['MSBUILD : error MSB1001: Unknown switch.',{severity:'error',code:'MSB1001',file:null}],
 ['App.csproj : error NU1101: Package unavailable',{severity:'error',code:'NU1101',file:'App.csproj'}],
 ['CSC : warning CS2008: No source files specified.',{severity:'warning',code:'CS2008',file:null}]
])test('Parses diagnostic '+line,()=>{const actual=parseDiagnosticLine(line);assert(actual);for(const[k,v]of Object.entries(expected))assert.equal(actual[k],v,k);});
test('Non-diagnostic output is never promoted to an error',()=>{for(const line of ['Build succeeded.','0 Warning(s)','some ordinary log','error occurred without MSBuild location'])assert.equal(parseDiagnosticLine(line),null);});
test('MSBuild JSON parsing tolerates startup banner but rejects malformed/trailing logs',()=>{assert.equal(parseEvaluationOutput('Welcome\n{log noise}\n'+JSON.stringify({Properties:{Value:'😀'},Items:{}})).Properties.Value,'😀');assert.throws(()=>parseEvaluationOutput('{"Properties":{}}\ntrailing'));assert.throws(()=>parseEvaluationOutput('42'));});
test('Browser client uses same-origin bearer requests; token is not persisted in request URL',async()=>{const calls=[],client=new MSBuildClient({token:'a'.repeat(64),fetch:async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>({protocolVersion:1})};}});await client.connect();await client.start(req());assert.equal(calls[0].url,'/api/msbuild/capabilities');assert.equal(calls[1].options.headers.Authorization,'Bearer '+'a'.repeat(64));assert.equal(calls[1].options.redirect,'error');assert.equal(calls[1].options.credentials,'omit');client.disconnect();assert.equal(client.token,'');});
test('Browser client strips only the fragment token and retains unrelated hash data',()=>{let url;const client=MSBuildClient.fromLocation({hash:'#view=build&sharpforge-token='+'b'.repeat(64),pathname:'/index.html',search:'?theme=dark'},{replaceState:(a,b,c)=>url=c});assert(client);assert.equal(url,'/index.html?theme=dark#view=build');assert.equal(MSBuildClient.fromLocation({hash:''}),null);});
test('Browser client propagates disk conflicts and rejects foreign endpoint origins',async()=>{assert.throws(()=>new MSBuildClient({token:'b'.repeat(64),base:'https://evil/api'}));const client=new MSBuildClient({token:'a'.repeat(64),fetch:async()=>({ok:false,status:409,json:async()=>({error:'Disk conflict',written:[]})})});await assert.rejects(()=>client.save([]),e=>e.status===409&&e.message==='Disk conflict');});
