import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import {createHash} from 'node:crypto';import {NetworkPolicy,HttpTransport,WebSocketClient} from '@sharpforge/network';
async function server(){const requests=[];const s=http.createServer(async(q,r)=>{requests.push(q.url);if(q.url==='/slow'){await new Promise(r=>setTimeout(r,100));}if(q.url==='/redirect'){r.writeHead(302,{location:'/ok'});r.end();return;}if(q.url==='/404'){r.writeHead(404);r.end('missing');return;}if(q.url==='/size'){r.writeHead(200,{'content-length':10000});r.end('x'.repeat(10000));return;}if(q.url==='/stream'){r.write('x'.repeat(20));r.end('y'.repeat(20));return;}let body='';try{for await(const c of q)body+=c;}catch{return;}if(q.destroyed&&r.destroyed)return;r.setHeader('x-test','42');r.setHeader('set-cookie','secret=hidden');r.end(q.method==='POST'?body:JSON.stringify({method:q.method,header:q.headers['x-custom']??null}));});
 s.on('upgrade',(q,socket)=>{const key=createHash('sha1').update(q.headers['sec-websocket-key']+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64');socket.write('HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: '+key+'\r\n\r\n');let buffer=Buffer.alloc(0);socket.on('data',chunk=>{buffer=Buffer.concat([buffer,chunk]);while(buffer.length>=2){const opcode=buffer[0]&15,masked=!!(buffer[1]&128);let size=buffer[1]&127,offset=2;if(size===126){if(buffer.length<4)return;size=buffer.readUInt16BE(2);offset=4;}if(size===127){socket.destroy();return;}if(buffer.length<offset+(masked?4:0)+size)return;const mask=masked?buffer.subarray(offset,offset+4):null;offset+=masked?4:0;const data=Buffer.from(buffer.subarray(offset,offset+size));if(mask)for(let i=0;i<data.length;i++)data[i]^=mask[i%4];buffer=buffer.subarray(offset+size);const header=size<126?Buffer.from([128|opcode,size]):Buffer.from([128|opcode,126,size>>8,size&255]);socket.write(Buffer.concat([header,data]));if(opcode===8){socket.end();return;}}});socket.on('error',()=>{});});
 s.listen(0,'127.0.0.1');await new Promise(r=>s.once('listening',r));const origin='http://127.0.0.1:'+s.address().port;return {origin,requests,close:()=>new Promise(r=>{s.close(r);s.closeAllConnections();})};}
for(const grant of ['*','https://host/path','https://user:password@host','ftp://host','https://host?q=1'])test('network rejects grant '+grant,()=>assert.throws(()=>new NetworkPolicy({allowedOrigins:[grant]})));
test('network denied by default; exact origins and header restrictions',async()=>{const p=new NetworkPolicy({allowedOrigins:['http://localhost:8000']});assert.throws(()=>p.check('http://localhost:8001/a'),/not permitted/);assert.throws(()=>p.check('http://u:p@localhost:8000/a'),/not permitted/);assert.equal(p.check('http://localhost:8000/a#b').hash,'');for(const name of ['Cookie','Host','Origin','Sec-Fetch-Site','Connection'])assert.throws(()=>p.headers({[name]:'x'}));await assert.rejects(new HttpTransport().request('https://example.com'),e=>e.code==='DENIED');});
test('HTTP real GET POST status and immutable safe headers',async()=>{const s=await server(),t=new HttpTransport({allowedOrigins:[s.origin]});try{const a=await t.request(s.origin+'/ok',{headers:{'x-custom':'hello'}});assert.equal(JSON.parse(a.text).header,'hello');assert.equal(a.headers['x-test'],'42');assert.equal(a.headers['set-cookie'],undefined);const b=await t.request(s.origin+'/echo',{method:'POST',body:'hello 🌍'});assert.equal(b.text,'hello 🌍');const missing=await t.request(s.origin+'/404');assert.equal(missing.status,404);assert.equal(missing.ok,false);}finally{t.dispose();await s.close();}});
test('HTTP refuses redirects and origin escalation',async()=>{const s=await server(),t=new HttpTransport({allowedOrigins:[s.origin]});try{await assert.rejects(t.request(s.origin+'/redirect'));assert.deepEqual(s.requests,['/redirect']);}finally{t.dispose();await s.close();}});
test('HTTP bounded content length, streaming and request body',async()=>{const s=await server(),t=new HttpTransport({allowedOrigins:[s.origin],maxResponseBytes:32,maxRequestBytes:16});try{await assert.rejects(t.request(s.origin+'/size'),e=>e.code==='LIMIT');await assert.rejects(t.request(s.origin+'/stream'),e=>e.code==='LIMIT');await assert.rejects(t.request(s.origin+'/echo',{method:'POST',body:'x'.repeat(17)}),e=>e.code==='LIMIT');}finally{t.dispose();await s.close();}});
test('HTTP timeout, external cancellation, queue limit and disposal',async()=>{const s=await server(),t=new HttpTransport({allowedOrigins:[s.origin],maxConcurrent:1,maxQueue:1});try{const a=t.request(s.origin+'/slow',{timeoutMs:5});await assert.rejects(a,e=>e.code==='TIMEOUT');const ab=new AbortController(),first=t.request(s.origin+'/slow',{signal:ab.signal}),second=t.request(s.origin+'/slow');const f=assert.rejects(first,e=>e.name==='AbortError'),g=assert.rejects(second);await assert.rejects(t.request(s.origin+'/ok'),e=>e.code==='QUEUE');ab.abort();await f;t.dispose();await g;await assert.rejects(t.request(s.origin+'/ok'),e=>e.code==='DISPOSED');}finally{t.dispose();await s.close();}});
test('real WebSocket text and binary echo, receive cancellation and closure',async()=>{const s=await server(),origin=s.origin.replace('http:','ws:'),client=new WebSocketClient({allowedOrigins:[origin]});try{await client.connect(origin);client.send('hello');assert.equal(await client.receive(),'hello');client.send(new Uint8Array([0,1,2,255]));assert.deepEqual(await client.receive(),new Uint8Array([0,1,2,255]));const abort=new AbortController(),p=assert.rejects(client.receive({signal:abort.signal}),e=>e.name==='AbortError');abort.abort();await p;client.close();assert.equal(await client.receive(),null);}finally{client.close();await s.close();}});
test('WebSocket explicit origin, send size and receive deadline',async()=>{const s=await server(),origin=s.origin.replace('http:','ws:'),client=new WebSocketClient({allowedOrigins:[origin]},{maxMessageBytes:3});try{await assert.rejects(new WebSocketClient().connect(origin),e=>e.code==='DENIED');await client.connect(origin);assert.throws(()=>client.send('longer'),e=>e.code==='LIMIT');await assert.rejects(client.receive({timeoutMs:5}),e=>e.code==='TIMEOUT');}finally{client.close();await s.close();}});

test('host CSP permits only explicitly named origins, wasm and Blob workers without JS eval',async()=>{const {createBrowserCsp}=await import('@sharpforge/network');const base=createBrowserCsp();assert.match(base,/connect-src 'self';/);assert.match(base,/script-src 'self' 'wasm-unsafe-eval';/);assert(!base.includes("'unsafe-eval'"));assert.match(base,/worker-src 'self' blob:;/);assert.match(createBrowserCsp(['https://example.com','http://localhost:8080']),/connect-src 'self' http:\/\/localhost:8080 https:\/\/example.com;/);assert.throws(()=>createBrowserCsp(['https://example.com/path']));});
