import test from 'node:test';import assert from 'node:assert/strict';
import {compile,compileToIL} from '@sharpforge/compiler';import {Workspace} from '@sharpforge/workspace';import {LanguageService} from '@sharpforge/language';import {RefactoringEngine} from '@sharpforge/refactoring';import {DebugSession,CilDebugSession} from '@sharpforge/debugger';import {VirtualMachine} from '@sharpforge/runtime';import {ExtensionDriver,JsonSchemaGenerator,ConstantConditionAnalyzer,TodoCommentAnalyzer} from '@sharpforge/extensions';
function debug(text,options={}){const result=compileToIL(text);assert(result.success,JSON.stringify(result.diagnostics));return new DebugSession(result.assembly,options);}
const stop=(d,mode)=>{if(mode)d.resume(mode);return d.runUntilStop();};
for(const expression of ['X++','X+=1','X??=null'])test('0.5 read-only auto-property rejects '+expression,()=>{const type=expression.includes('??')?'string':'int',r=compile(`var c=new C();class C{public ${type} X{get;}public void M(){${expression};}}`);assert(!r.success);assert(r.diagnostics.some(d=>d.code==='CS0200'));});
test('0.5 C# explicit accessor method calls are diagnosed',()=>{const r=compile('var c=new C();c.set_X(7);class C{public int X{get;set;}}');assert(!r.success);assert(r.diagnostics.some(d=>d.code==='CS0571'));});
test('0.5 inline refuses references inside nameof',()=>{const w=new Workspace();w.update('Program.cs','int x=1;Console.WriteLine(nameof(x));',1);const r=new RefactoringEngine(w,new LanguageService(w));assert(!r.actions('Program.cs',4).some(a=>a.kind==='refactor.inline'));});
test('0.5 source watch reads auto-property without executing computed getter',()=>{const d=debug('var c=new C();\nConsole.WriteLine(c.X);\nclass C{public int X{get;set;}=7;public int Unsafe{get{throw new Exception("do not run");}}}');d.setBreakpoints('Program.cs',[{line:2}]);d.start(false);stop(d);assert.equal(d.evaluate('c.X').result,'7');assert.throws(()=>d.evaluate('c.Unsafe'),/getters/);assert.equal(d.vm.state,'paused');});
test('0.5 source run-to-cursor adds no persistent breakpoint',()=>{const d=debug('int x=1;\nx=2;\nConsole.WriteLine(x);');d.start();stop(d);d.runToCursor('Program.cs',3);stop(d);assert.equal(d.reason.reason,'goto');assert.equal(d.evaluate('x').result,'2');assert.equal(d.breakpoints.length,0);stop(d,'continue');assert.equal(d.vm.output.join(''),'2\n');});
test('0.5 source data breakpoint uses frame identity and local slot',()=>{const d=debug('int x=1;\nx=2;\nConsole.WriteLine(x);').start();stop(d);const frame=d.vm.top,local=d.vm.image.methods[frame.methodId].locals.find(l=>l.name==='x');assert(d.setDataBreakpoints([{kind:'local',frameId:frame.id,index:local.slot}])[0].verified);stop(d,'continue');assert.equal(d.reason.reason,'data breakpoint');});
test('0.5 stale allocation watchpoint cannot match reused heap slot',()=>{const d=debug('Console.WriteLine(1);'),heap=d.vm.heap,old=heap.object('C',[0]);assert(d.setDataBreakpoints([{kind:'field',handle:old.h,generation:old.g,index:0}])[0].verified);heap.collect();const fresh=heap.object('C',[0]);assert.equal(fresh.h,old.h);assert.notEqual(fresh.g,old.g);d.vm.onWrite({kind:'field',handle:fresh.h,generation:fresh.g,index:0});assert.notEqual(d.vm.state,'paused');assert(!d.setDataBreakpoints([{kind:'field',handle:old.h,generation:old.g,index:0}])[0].verified);});
test('0.5 debugger snapshots retain finally unwind continuations',()=>{const d=debug('int F(){try{return 7;}finally{Console.WriteLine("a");\nConsole.WriteLine("b");}}\nConsole.WriteLine(F());',{recordHistory:true});d.setBreakpoints('Program.cs',[{line:2}]);d.start(false);stop(d);const saved=d.vm.snapshot();stop(d,'continue');const expected=d.vm.output.join('');d.vm.restore(saved);stop(d,'continue');assert.equal(d.vm.output.join(''),expected);assert.equal(expected,'a\nb\n7\n');});
test('0.5 direct watches compare strings and bools and refuse invalid cast',()=>{const r=compileToIL('Console.WriteLine(1);'),d=new CilDebugSession(r.assembly);d.start();stop(d);for(const [expr,value]of [['true == false',false],['"a"=="a"',true],['"a"!=null',true],['"a"+true','aTrue']])assert.equal(d.evaluate(expr).value,value);assert.throws(()=>d.evaluate('(bool)1'),/numeric watch casts|trailing input/);});
test('0.5 JSON schema optionally emits real auto-properties',()=>{const w=new Workspace({extensions:new ExtensionDriver().registerGenerator(JsonSchemaGenerator),extensionOptions:{schemaProperties:true},additionalFiles:[{uri:'model.schema.json',text:'{"name":"Row","fields":[{"name":"Value","type":"int"}]}'}]});w.update('Program.cs','var r=new Row();r.Value=42;Console.WriteLine(r.Value);',1);const result=w.compile();assert(result.success,JSON.stringify(result.diagnostics));assert.equal(new VirtualMachine(result.image).run().output,'42\n');assert([...w.generatedDocuments.values()][0].source.text.includes('{ get; set; }'));});
test('0.5 analyzers report literal conditions and task comments, never strings',()=>{const extensions=new ExtensionDriver().registerAnalyzer(ConstantConditionAnalyzer).registerAnalyzer(TodoCommentAnalyzer),w=new Workspace({extensions});const text='// TODO review\nif(false){Console.WriteLine("TODO");}\n/* FIXME detail */\nwhile(false){}';w.update('Program.cs',text,1);const r=w.compile();assert(r.success);assert.equal(r.diagnostics.filter(d=>d.code==='SFAN1003').length,2);assert.deepEqual(r.diagnostics.filter(d=>d.code==='SFAN1004').map(d=>text.slice(d.start,d.start+d.length)),['TODO','FIXME']);});
test('0.5 analyzer severity overrides and generation cache remain valid',()=>{const e=new ExtensionDriver().registerAnalyzer(TodoCommentAnalyzer),w=new Workspace({extensions:e,extensionOptions:{severities:{SFAN1004:'error'}}});w.update('Program.cs','// TODO\nConsole.WriteLine(1);',1);assert(!w.compile().success);w.extensionOptions.severities.SFAN1004='none';assert(w.compile().success);});
