import test from 'node:test';import assert from 'node:assert/strict';
import {compileToIL} from '@sharpforge/compiler';import {VirtualMachine,CilVirtualMachine} from '@sharpforge/runtime';import {ProjectSystem} from '@sharpforge/project-system';import {Workspace} from '@sharpforge/workspace';import {ExtensionDriver,JsonSchemaGenerator,UnreachableStatementAnalyzer} from '@sharpforge/extensions';
const project=(value,extra='')=>`<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType>${value===undefined?'':`<CheckForOverflowUnderflow>${value}</CheckForOverflowUnderflow>`}</PropertyGroup>${extra}</Project>`;
const source='int x=2147483647;try{Console.WriteLine(x+1);}catch(Exception e){Console.WriteLine("overflow");}';
for(const [name,options,output]of [['default',{},'-2147483648\n'],['checked',{checkOverflow:true},'overflow\n'],['perfile',{checkOverflow:false,checkOverflowByUri:{'Program.cs':true}},'overflow\n'],['perfile overrides',{checkOverflow:true,checkOverflowByUri:{'Program.cs':false}},'-2147483648\n']])test('0.6 compiler overflow option: '+name,()=>{const r=compileToIL(source,options);assert(r.success,JSON.stringify(r.diagnostics));for(const vm of [new VirtualMachine(r.image),new VirtualMachine(r.assembly),new CilVirtualMachine(r.assembly)])assert.equal(vm.run().output,output);});
test('0.6 compiler: lexical unchecked overrides project setting',()=>{const r=compileToIL('int x=2147483647;Console.WriteLine(unchecked(x+1));',{checkOverflow:true});assert(r.success);assert.equal(new CilVirtualMachine(r.assembly).run().output,'-2147483648\n');});
for(const value of ['true',1,null])test('0.6 compiler rejects malformed checked flag '+value,()=>{const r=compileToIL('Console.WriteLine(1);',{checkOverflow:value});assert(!r.success);assert(r.diagnostics.some(d=>d.code==='SF2009'));});
for(const [value,expected]of [[undefined,false],['true',true],[' True ',true],['FALSE',false]])test('0.6 project overflow property: '+value,()=>{const p=new ProjectSystem(new Map([['A.csproj',project(value)],['Program.cs',source]]));p.load('A.csproj');const opts=p.compilationOptions();assert.equal(opts.checkOverflow,expected);assert.equal(opts.checkOverflowByUri['Program.cs'],expected);});
test('0.6 project checked options respect referenced source contexts',()=>{const p=new ProjectSystem(new Map([['App/A.csproj',project('true','<ItemGroup><ProjectReference Include="../Lib/L.csproj"/></ItemGroup>')],['App/Program.cs',source+'Console.WriteLine(Lib.F());'],['Lib/L.csproj',project('false')],['Lib/Lib.cs','class Lib{public static int F(){int x=2147483647;return x+1;}}']]));p.load('App/A.csproj');const options=p.compilationOptions('App/A.csproj'),r=compileToIL(p.compilationFiles('App/A.csproj'),options);assert(r.success,JSON.stringify(r.diagnostics));assert.equal(new CilVirtualMachine(r.assembly).run().output,'overflow\n-2147483648\n');});
test('0.6 project rejects invalid overflow properties',()=>{const p=new ProjectSystem(new Map([['A.csproj',project('maybe')],['Program.cs',source]]));p.load('A.csproj');assert.throws(()=>p.compilationOptions(),/Invalid CheckForOverflowUnderflow/);});
test('0.6 project rejects shared-file conflicting overflow contexts',()=>{const p=new ProjectSystem(new Map([['App/A.csproj',project('true','<ItemGroup><Compile Include="../Common.cs"/><ProjectReference Include="../Lib/L.csproj"/></ItemGroup>')],['App/Program.cs',source],['Lib/L.csproj',project('false','<ItemGroup><Compile Include="../Common.cs"/></ItemGroup>')],['Common.cs','class Shared {}']]));p.load('App/A.csproj');assert.throws(()=>p.compilationOptions('App/A.csproj'),/conflicting overflow/);});
function generated(schema,source,options={}){const extensions=new ExtensionDriver().registerGenerator(JsonSchemaGenerator),w=new Workspace({extensions,extensionOptions:options,additionalFiles:[{uri:'row.schema.json',text:JSON.stringify(schema)}]});w.update('Program.cs',source,1);return w;}
const fields=[{name:'Id',type:'int'},{name:'Name',type:'string'}];
for(const [name,schema,options]of [['field constructor',{name:'Row',fields,constructor:true},{}],['property constructor',{name:'Row',fields,constructor:true},{schemaProperties:true}],['immutable constructor',{name:'Row',fields,immutable:true},{}]])test('0.6 generator: '+name,()=>{const w=generated(schema,'var row=new Row(42,"Ada");Console.WriteLine(row.Id);Console.WriteLine(row.Name);',options),r=w.compile();assert(r.success,JSON.stringify(r.diagnostics));assert.equal(new VirtualMachine(r.image).run().output,'42\nAda\n');assert([...w.generatedDocuments.values()].some(d=>d.source.text.includes('this.Id = value0;')));});
test('0.6 generator: immutable properties reject writes outside construction',()=>{const r=generated({name:'Row',fields,immutable:true},'var row=new Row(42,"Ada");row.Id=7;').compile();assert(!r.success);assert(r.diagnostics.some(d=>d.code==='CS0200'));});
for(const schema of [{name:'Row',fields:[...fields,fields[0]]},{name:'Row',fields:[{name:'Row',type:'int'}]},{name:'Row',fields:[{name:'Id',type:'byte'}]}])test('0.6 generator: invalid schema rolls back all files '+JSON.stringify(schema),()=>{const w=generated(schema,'Console.WriteLine(1);'),r=w.compile();assert(!r.success);assert(r.diagnostics.some(d=>d.code==='SFGEN001'));assert.equal(w.generatedDocuments.size,0);});
function analyzed(text,options={}){const extensions=new ExtensionDriver().registerAnalyzer(UnreachableStatementAnalyzer),w=new Workspace({extensions,extensionOptions:options});w.update('Program.cs',text,1);return w.compile();}
for(const [text,count]of [['int F(){return 1;Console.WriteLine("dead");}Console.WriteLine(F());',1],['int F(int x){if(x>0){return 1;}else{return 2;}Console.WriteLine("dead");}Console.WriteLine(F(1));',1],['int F(int x){if(x>0){return 1;}Console.WriteLine("live");return 2;}Console.WriteLine(F(0));',0],['int F(){while(true){break;Console.WriteLine("dead");}return 1;}Console.WriteLine(F());',1],['int F(){while(false){Console.WriteLine("not analyzed");}return 1;}Console.WriteLine(F());',0]])test('0.6 analyzer: syntax-local reachability '+text,()=>{const r=analyzed(text);assert.equal(r.diagnostics.filter(d=>d.code==='SFAN1005').length,count,JSON.stringify(r.diagnostics));});
test('0.6 analyzer: configurable suppression and severity',()=>{const s='int F(){return 1;Console.WriteLine("dead");}Console.WriteLine(F());';assert(!analyzed(s,{severities:{SFAN1005:'none'}}).diagnostics.some(d=>d.code==='SFAN1005'));assert.equal(analyzed(s,{severities:{SFAN1005:'error'}}).diagnostics.find(d=>d.code==='SFAN1005').severity,'error');});
test('0.6 constants: unchecked huge floating cast uses the Roslyn constant result in execution and switch labels',()=>{const r=compileToIL('const int target=unchecked((int)9000000000.0);int n=target;switch(n){case target:Console.WriteLine("matched");break;default:break;}Console.WriteLine(n);');assert(r.success,JSON.stringify(r.diagnostics));for(const vm of [new VirtualMachine(r.image),new VirtualMachine(r.assembly),new CilVirtualMachine(r.assembly)])assert.equal(vm.run().output,'matched\n0\n');});
import {spawnSync} from 'node:child_process';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';import {join} from 'node:path';
test('0.6 CLI: checked loose source executes overflow handlers',()=>{const dir=mkdtempSync(join(tmpdir(),'sf-checked-'));try{const file=join(dir,'Program.cs');writeFileSync(file,source);const result=spawnSync(process.execPath,['apps/cli/main.js','run',file,'--checked'],{encoding:'utf8'});assert.equal(result.status,0,result.stderr);assert.equal(result.stdout,'overflow\n');}finally{rmSync(dir,{recursive:true,force:true});}});
test('0.6 CLI: project --checked flag is refused, not silently ignored',()=>{const result=spawnSync(process.execPath,['apps/cli/main.js','run','examples/projects/CheckedResources/CheckedResources.slnx','--checked'],{encoding:'utf8'});assert.equal(result.status,1);assert.match(result.stderr,/--checked is for loose source/);assert.equal(result.stdout,'');});
test('0.6 constants: declared double type preserves later constant division',()=>{const r=compileToIL('const double first=1;const double half=first/2;Console.WriteLine(half);');assert(r.success,JSON.stringify(r.diagnostics));for(const vm of [new VirtualMachine(r.image),new VirtualMachine(r.assembly),new CilVirtualMachine(r.assembly)])assert.equal(vm.run().output,'0.5\n');});
