import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,writeFile,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {ExplorerCommands} from '../apps/studio/explorer-commands.js';
import {removeSolutionProject,editNamedProjectItem,editProjectMembership,rewriteProjectPath,ProjectSystem,parseXml} from '../packages/project-system/src/index.js';
import {NativeWorkspace,startMSBuildHost} from '../packages/msbuild/src/node.js';
import {handleVisualStudioKey,EDITOR_KEYMAPS} from '../packages/editor/src/keymaps.js';
function fake(records=[{path:'Program.cs',text:'Console.WriteLine(42);'}]){let context={identity:'preview:Test',name:'Test',records,folders:[],tabs:['Program.cs'],active:'Program.cs',breakpoints:{'Program.cs':[{line:1}]},native:false,readOnly:false};const errors=[],notices=[];const host={context:()=>context,error:e=>errors.push(e.message),notice:s=>notices.push(s),render(){},pathDialog:async()=>null,confirm:async()=>true,commit:async v=>{context={...context,...v,records:v.records,folders:v.folders};},open:async()=>{},copy:async()=>{},explorer:{model:{},reveal(){}}};return {commands:new ExplorerCommands(host),host,context:()=>context,set:x=>context={...context,...x},errors,notices};}
test('08 preview mutation batches preflight before replacing workspace buffers',async()=>{const f=fake();await assert.rejects(f.commands.perform([{kind:'create',path:'New.cs',text:'class New{}'},{kind:'create',path:'Program.cs',text:'overwrite'}]),/exists/);assert.equal(f.context().records.length,1);assert.equal(f.commands.history.length,0);});
test('08 preview rename/copy/delete undo restores data and editor metadata',async()=>{const f=fake();await f.commands.perform([{kind:'move',path:'Program.cs',destination:'src/Main.cs'}],[{from:'Program.cs',to:'src/Main.cs'}]);assert.equal(f.context().records[0].path,'src/Main.cs');await f.commands.undo();assert.equal(f.context().records[0].path,'Program.cs');assert.equal(f.context().restore.breakpoints['Program.cs'][0].line,1);});
test('08 preview undo refuses subsequent user edits',async()=>{const f=fake();await f.commands.perform([{kind:'create',path:'New.cs',text:'class New{}'}]);f.context().records[1].text='important edits';await assert.rejects(f.commands.undo(),/newer edits/);assert.equal(f.context().records[1].text,'important edits');});
test('08 pending file command cannot cross a workspace switch',async()=>{const f=fake();f.commands.operationIdentity='old workspace';await assert.rejects(f.commands.perform([{kind:'create',path:'New.cs',text:''}]),/Workspace changed/);assert.equal(f.context().records.length,1);});
test('08 planning a project change detects concurrent project source changes',async()=>{const f=fake([{path:'App.csproj',text:'<Project/>'}]);f.commands.readSet=new Map();await f.commands.readText('App.csproj');f.context().records[0].text='<Project><!--changed--></Project>';await assert.rejects(f.commands.perform([{kind:'write',path:'App.csproj',text:'<Project><ItemGroup/></Project>'}]),/Project changed/);});
test('08 native planning reads unsaved project buffers, not an old disk snapshot',async()=>{const f=fake([{path:'App.csproj',text:'<Project><!--unsaved--></Project>'}]);f.set({native:true,client:{read:async()=>({text:'<Project/>'})}});assert.equal(await f.commands.readText('App.csproj'),'<Project><!--unsaved--></Project>');});
test('08 cross-project source copy explicitly includes files with defaults disabled',async()=>{const f=fake([{path:'src/Value.cs',text:'class Value{}'},{path:'dest/App.csproj',text:'<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><EnableDefaultCompileItems>false</EnableDefaultCompileItems></PropertyGroup></Project>'}]);await f.commands.move([{from:'src/Value.cs',to:'dest/Value.cs'}],true,'dest/App.csproj');const system=new ProjectSystem(f.context().records),snapshot=system.load('dest/App.csproj');assert(snapshot.projects[0].compile.some(f=>f.path==='dest/Value.cs'));assert(f.context().records.some(f=>f.path==='src/Value.cs'));});
test('08 readonly explorer rejects file mutations before prompting',async()=>{const f=fake();f.set({readOnly:true});let prompts=0;f.host.pathDialog=async()=>{prompts++;return 'New.cs';};const result=await f.commands.run('new-file');assert.match(result.error,/Stop debugging/);assert.equal(prompts,0);});
test('08 overlapping explorer dialogs cannot start a second mutation',async()=>{const f=fake();let release;f.host.pathDialog=()=>new Promise(r=>release=r);const pending=f.commands.run('new-file');await Promise.resolve();const result=await f.commands.run('new-file');assert.match(result.error,/active file dialog/);release(null);await pending;assert.equal(f.commands.runningMutation,false);});
test('08 solution project removal preserves comment and neighboring configuration',()=>{const text='\uFEFF<Solution><!--keep--><Folder Name="/src/"><Project Path="A/A.csproj"><BuildType Solution="*" Project="Debug"/></Project><Project Path="B/B.csproj"/></Folder></Solution>';const result=removeSolutionProject(text,{solutionPath:'Demo.slnx',projectPath:'A/A.csproj'});assert(result.startsWith('\uFEFF'));assert(result.includes('<!--keep-->'));assert(result.includes('B/B.csproj'));assert(!result.includes('A/A.csproj'));parseXml(result);});
test('08 solution removal also removes literal dependency on the removed member',()=>{const text='<Solution><Project Path="A.csproj"/><Project Path="B.csproj"><BuildDependency Project="A.csproj"/></Project></Solution>';const next=removeSolutionProject(text,{solutionPath:'Demo.slnx',projectPath:'A.csproj'});assert(!next.includes('A.csproj'));assert(next.includes('B.csproj'));});
test('08 package reference authoring escapes metadata and does not invent relative package IDs',()=>{const next=editNamedProjectItem('<Project/>',{name:'Example.Package',metadata:{Version:'1.2.3'}});assert(next.includes('Include="Example.Package"'));assert(next.includes('<Version>1.2.3</Version>'));assert(!next.includes('../'));parseXml(next);assert.throws(()=>editNamedProjectItem('<Project/>',{name:'$(Injected)'}));});
test('08 path rewrites leave commented-out references and CDATA byte-identical',()=>{const text='<Project><!-- <Compile Include="A.cs" /> --><Value><![CDATA[Include="A.cs"]]></Value><ItemGroup><Compile Include="A.cs" /></ItemGroup></Project>';const next=rewriteProjectPath(text,{documentPath:'App.csproj',oldPath:'A.cs',newPath:'B.cs'});assert(next.includes('<!-- <Compile Include="A.cs" /> -->'));assert(next.includes('<![CDATA[Include="A.cs"]]>'));assert(next.includes('<Compile Include="B.cs" />'));});
test('08 adding compile membership removes default match before explicit include',()=>{const next=editProjectMembership('<Project Sdk="Microsoft.NET.Sdk"/>',{projectPath:'App.csproj',path:'A.cs'});assert(next.indexOf('Remove="A.cs"')<next.indexOf('Include="A.cs"'));const p=new ProjectSystem([{path:'App.csproj',text:next},{path:'A.cs',text:'class A{}'}]);assert.equal(p.load('App.csproj').projects[0].compile.length,1);});
test('08 Visual Studio modifier-only keys do not eat an active keyboard chord',()=>{let toggled=null;const e={keymap:'visual-studio',toggleLineComment:value=>toggled=value},event=(key,ctrl=true)=>({key,ctrlKey:ctrl,preventDefault(){},stopPropagation(){}});assert(handleVisualStudioKey(e,event('k')));assert.equal(handleVisualStudioKey(e,event('Control')),false);assert(e.pendingChord);assert(handleVisualStudioKey(e,event('c')));assert.equal(toggled,false);assert.equal(e.pendingChord,null);});
test('08 editor declares Visual Studio default and six distinct profiles without a DOM', () => {
  assert.equal(EDITOR_KEYMAPS[0].id, 'visual-studio');
  assert.deepEqual(EDITOR_KEYMAPS.map(keymap => keymap.id), ['visual-studio', 'vscode', 'resharper', 'vim', 'emacs', 'sublime']);
});
async function disk(t){const root=await mkdtemp(join(tmpdir(),'sf08-safety-'));t.after(()=>rm(root,{recursive:true,force:true}));return {w:await NativeWorkspace.open(root),root};}
test('08 native XML write undo restores original encoding and byte hash',async t=>{const {w,root}=await disk(t),bytes=Buffer.concat([Buffer.from([255,254]),Buffer.from('<Project><!--old--></Project>','utf16le')]);await writeFile(join(root,'A.csproj'),bytes);const a=await w.inspectItem('A.csproj'),result=await w.mutate([{kind:'write',path:'A.csproj',text:'<Project><!--new--></Project>',expectedHash:a.hash}]);assert.equal((await w.read('A.csproj')).text,'<Project><!--new--></Project>');await w.undoMutation(result.undoToken);assert.deepEqual(await readFile(join(root,'A.csproj')),bytes);});
test('08 native XML syntax validation precedes every batch mutation',async t=>{const {w}=await disk(t);await assert.rejects(w.mutate([{kind:'create',path:'First.cs',text:'class First{}'},{kind:'create',path:'Bad.csproj',text:'<Project>'}]),/XML/);await assert.rejects(w.read('First.cs'),/ENOENT/);});
test('08 native overlapping parent/child operations fail preflight instead of breaking undo',async t=>{const {w}=await disk(t);await assert.rejects(w.mutate([{kind:'mkdir',path:'New'},{kind:'create',path:'New/Child.cs',text:''}]),/Overlapping/);await assert.rejects(w.inspectItem('New'),/ENOENT/);});
test('08 native XML write followed by undo rejects later disk edits',async t=>{const {w,root}=await disk(t);await writeFile(join(root,'A.csproj'),'<Project/>');const a=await w.inspectItem('A.csproj'),r=await w.mutate([{kind:'write',path:'A.csproj',expectedHash:a.hash,text:'<Project><!--one--></Project>'}]);await writeFile(join(root,'A.csproj'),'<Project><!--two--></Project>');await assert.rejects(w.undoMutation(r.undoToken),/changed/);assert((await w.read('A.csproj')).text.includes('two'));});
test('08 actual loopback explorer APIs enforce auth/origin and preserve binary bytes',async t=>{const {root}=await disk(t);await writeFile(join(root,'A.csproj'),'<Project/>');const binary=Buffer.from([77,90,0,1,128,255]);await writeFile(join(root,'A.dll'),binary);const host=await startMSBuildHost({root,port:0});t.after(()=>host.close());const url=host.origin+'/api/msbuild',headers={Authorization:'Bearer '+host.token,'Content-Type':'application/json'};assert.equal((await fetch(url+'/item?path=A.csproj')).status,401);assert.equal((await fetch(url+'/mutations',{method:'POST',headers:{...headers,Origin:'https://other.invalid'},body:'{}'})).status,403);assert.deepEqual(Buffer.from(await (await fetch(url+'/binary?path=A.dll',{headers})).arrayBuffer()),binary);const file=await(await fetch(url+'/item?path=A.csproj',{headers})).json();const response=await fetch(url+'/mutations',{method:'POST',headers,body:JSON.stringify({operations:[{kind:'copy',path:'A.csproj',destination:'B.csproj',expectedHash:file.hash}]})});assert.equal(response.status,200);const receipt=await response.json();assert.equal((await host.workspace.read('B.csproj')).text,'<Project/>');const undo=await fetch(url+'/undo-mutation',{method:'POST',headers,body:JSON.stringify({token:receipt.undoToken})});assert.equal(undo.status,200);await assert.rejects(host.workspace.read('B.csproj'),/ENOENT/);});
