import test from 'node:test';import assert from 'node:assert/strict';
import {Workspace} from '@sharpforge/workspace';import {LanguageService} from '@sharpforge/language';import {RefactoringEngine} from '@sharpforge/refactoring';import {VirtualMachine} from '@sharpforge/runtime';
import {bracketPairs,lexicalContext,replaceLiteral,duplicateLineBlock} from '@sharpforge/editor';
function setup(text){const w=new Workspace();w.update('Program.cs',text,1);const l=new LanguageService(w),r=new RefactoringEngine(w,l);assert(w.compile().success,JSON.stringify(w.compile().diagnostics));return {w,r};}
function output(w){const result=new VirtualMachine(w.compile().image).run();assert.equal(result.state,'terminated',result.fault?.stack);return result.output;}
function apply(text,selection,title){const {w,r}=setup(text),before=output(w),start=text.indexOf(selection),actions=r.actions('Program.cs',start,start+selection.length),action=actions.find(a=>a.title.startsWith(title));assert(action,actions.map(a=>a.title).join(', '));r.apply(action);assert.equal(output(w),before);return {w,r,action};}
test('0.5 refactor: introduce whole initializer preserves side effects once',()=>{const {w}=apply('int F(){Console.WriteLine(1);return 7;}\nint x=F()+3;\nConsole.WriteLine(x);','F()+3','Introduce local');assert.match(w.documents.get('Program.cs').source.text,/var value = F\(\)\+3/);});
test('0.5 refactor: introduce return expression stays inside block',()=>apply('int F(int x){if(x>0){return x*2;}return 0;}Console.WriteLine(F(7));','x*2','Introduce local'));
test('0.5 refactor: introduce local avoids existing names',()=>{const {w}=apply('int value=1;int x=value+3;Console.WriteLine(x);','value+3','Introduce local');assert.match(w.documents.get('Program.cs').source.text,/var value2/);});
test('0.5 refactor: no extraction from conditional branch or call argument',()=>{for(const text of ['int x=1;Console.WriteLine(x+2);','int F(){if(true)return 7;return 0;}Console.WriteLine(F());']){const {r}=setup(text),selection=text.includes('x+2')?'x+2':'7',at=text.indexOf(selection);assert(!r.actions('Program.cs',at,at+selection.length).some(a=>a.kind==='refactor.extract'));}});
test('0.5 refactor: no extraction from a for initializer',()=>{const text='for(int i=0;i<3;i++)Console.WriteLine(i);',{r}=setup(text),at=text.indexOf('0');assert(!r.actions('Program.cs',at,at+1).some(a=>a.kind==='refactor.extract'));});
test('0.5 refactor: inline immutable literal preserves type and all references',()=>{const {w}=apply('int amount=7;Console.WriteLine(amount+amount);','amount','Inline constant');assert(!w.documents.get('Program.cs').source.text.includes('amount'));});
test('0.5 refactor: mutable local is not offered for inline',()=>{const text='int x=1;x++;Console.WriteLine(x);',{r}=setup(text);assert(!r.actions('Program.cs',4).some(a=>a.kind==='refactor.inline'));});
test('0.5 refactor: overload-affecting literal widening is not inlined',()=>{const text='double x=1;Console.WriteLine(x);',{r}=setup(text);assert(!r.actions('Program.cs',7).some(a=>a.kind==='refactor.inline'));});
test('0.5 refactor: invert if keeps one condition evaluation',()=>apply('int F(){Console.WriteLine("once");return 1;}if(F()==1){Console.WriteLine("a");}else{Console.WriteLine("b");}','if','Invert if'));
test('0.5 refactor: expand initialized auto-property preserves get/set execution',()=>{const {w}=apply('var c=new C();c.X+=2;Console.WriteLine(c.X);class C{public int X{get;set;}=7;}','X{get','Expand auto-property');assert.match(w.documents.get('Program.cs').source.text,/private int _x = 7/);});
test('0.5 refactor: expansion preserves static initializer and private setter',()=>apply('C.Set();Console.WriteLine(C.X);class C{public static int X{get;private set;}=3;public static void Set(){X=7;}}','X{get','Expand auto-property'));
test('0.5 refactor: getter-only constructor property is not expanded unsafely',()=>{const text='Console.WriteLine(new C().X);class C{public int X{get;}public C(){X=7;}}',{r}=setup(text);assert(!r.actions('Program.cs',text.indexOf('X')).some(a=>a.title.startsWith('Expand')));});
test('0.5 refactor: stale structural edit fails atomically',()=>{const text='int x=3;Console.WriteLine(x);',{w,r}=setup(text),action=r.actions('Program.cs',4).find(a=>a.kind==='refactor.inline');w.update('Program.cs',text+' ',2);assert.throws(()=>r.apply(action),/Stale/);assert.equal(w.documents.get('Program.cs').source.text,text+' ');});
test('0.5 editor: bracket pairs ignore comments and escaped string punctuation',()=>{const t='if (true) { string x="(\\\")"; // ]\n /* } */ Console.WriteLine(x); }',p=bracketPairs(t);assert.equal(p.get(t.indexOf('(')),t.indexOf(')'));assert.equal(p.get(t.indexOf('{')),t.lastIndexOf('}'));assert(!p.has(t.indexOf(']')));assert(!p.has(t.indexOf('(',t.indexOf('"'))));});
test('0.5 editor: unmatched delimiters are not paired across mismatch',()=>assert.equal(bracketPairs('([)]').size,0));
test('0.5 editor: lexical insertion contexts include EOF comments and incomplete strings',()=>{for(const [text,expected]of [['// comment {','comment'],['/* unfinished','comment'],['/* done */','code'],['"unfinished','literal'],['"complete"','code'],['Console.','code']])assert.equal(lexicalContext(text,text.length),expected,text);});
test('0.5 editor: literal replacement honors UTF-16, word and case constraints',()=>{const result=replaceLiteral('😀 x X x2 x','x','$&',{wholeWord:true,matchCase:true});assert.equal(result.text,'😀 $& X x2 $&');assert.equal(result.matches[0].start,3);assert.equal(result.count,2);});
test('0.5 editor: search text is literal rather than regex',()=>assert.equal(replaceLiteral('a.b axb a.b','a.b','c').text,'c axb c'));
test('0.5 editor: replacement preflights result and match limits',()=>{assert.throws(()=>replaceLiteral('x'.repeat(10001),'x','a'),/10000/);assert.throws(()=>replaceLiteral('x','x','abc',{maxLength:2}),/limit/);});
test('0.5 editor: duplicate selected whole lines excludes trailing newline',()=>{const result=duplicateLineBlock('one\ntwo\nthree',0,4,1);assert.equal(result.text,'one\none\ntwo\nthree');assert.equal(result.text.slice(result.start,result.end),'one');});
test('0.5 editor: duplicate last line upward and validate ranges',()=>{const r=duplicateLineBlock('a\nb',2,3,-1);assert.equal(r.text,'a\nb\nb');assert.equal(r.start,2);assert.throws(()=>duplicateLineBlock('a',2));});
