import test from 'node:test';
import assert from 'node:assert/strict';
import {CilDebugSession,DebugSession,instructionReference} from '@sharpforge/debugger';
import {CilVirtualMachine,ManagedFault} from '@sharpforge/runtime';
import {DebugAdapter} from '@sharpforge/protocol';
import {compileToIL} from '@sharpforge/compiler';
import {arithmeticLibrary,managedFixture} from './managed-fixtures.js';
const r=(at=0,token=0x06000001)=>instructionReference(token,at);
function start(bytes=arithmeticLibrary(),options={methodToken:'Add',arguments:[20,22]}){const d=new CilDebugSession(bytes,{recordHistory:true,...options});d.start();d.runUntilStop();return d;}
function step(d,mode='stepIn'){d.resume(mode);return d.runUntilStop();}
function compile(text){const r=compileToIL(text);assert(r.success,JSON.stringify(r.diagnostics));return r.assembly;}
test('0.6 IL reverse restores exact evaluation stack and instruction count',()=>{const d=start();step(d);step(d);assert.deepEqual(d.vm.top.stack,[20,22]);assert.equal(d.vm.instructions,2);d.stepBack();assert.deepEqual(d.vm.top.stack,[20]);assert.equal(d.vm.instructions,1);d.stepBack();assert.deepEqual(d.vm.top.stack,[]);assert.equal(d.vm.instructions,0);step(d,'continue');assert.equal(d.state().returnValue,'42');});
test('0.6 IL reverse can resume a completed in-memory invocation',()=>{const d=start();step(d,'continue');assert.equal(d.vm.state,'terminated');d.stepBack();assert.equal(d.vm.state,'paused');assert.equal(d.stackTrace()[0].ilOffset,3);step(d);assert.equal(d.state().returnValue,'42');});
test('0.6 local edit can be undone without executing an instruction',()=>{const d=start();d.setVariable(undefined,'arg0','30');assert.equal(d.evaluate('arg0').result,'30');d.stepBack();assert.equal(d.evaluate('arg0').result,'20');step(d,'continue');assert.equal(d.state().returnValue,'42');});
test('0.6 reverse history disabled avoids snapshots',()=>{const d=start(arithmeticLibrary(),{methodToken:'Add',arguments:[20,22],recordHistory:false});step(d);assert.equal(d.history.length,0);assert.throws(()=>d.stepBack(),/not enabled/);});
test('0.6 history count and estimated byte caps are enforced',()=>{const d=start(arithmeticLibrary(),{methodToken:'Add',arguments:[20,22],maxHistory:2,maxHistoryBytes:50000});step(d,'continue');assert(d.history.length<=2);assert(d.historyBytes<=50000);assert(d.historyDropped>0);const tiny=start(arithmeticLibrary(),{methodToken:'Add',arguments:[1,2],maxHistoryBytes:1});step(tiny);assert.equal(tiny.history.length,0);assert(tiny.historyDropped>0);assert.throws(()=>start(arithmeticLibrary(),{methodToken:'Add',arguments:[1,2],maxHistory:-1}),RangeError);});
test('0.6 reverse continue reaches instruction breakpoint with restored hit counts',()=>{const d=start();d.setInstructionBreakpoints([{instructionReference:r(1)}]);step(d,'continue');assert.equal(d.breakpoints[0].hits,1);step(d,'continue');d.reverseContinue();assert.equal(d.stackTrace()[0].ilOffset,1);assert.equal(d.reason.reason,'instruction breakpoint');step(d,'continue');assert.equal(d.state().returnValue,'42');});
test('0.6 VM snapshots reject other VMs and are repeatable',()=>{const a=new CilVirtualMachine(arithmeticLibrary(),{methodToken:'Add',arguments:[20,22]}),b=new CilVirtualMachine(arithmeticLibrary(),{methodToken:'Add',arguments:[1,2]}),s=a.snapshot();assert.throws(()=>b.restore(s),/another/);a.run();for(let i=0;i<3;i++){a.restore(s);assert.equal(a.run().returnValue,42);}});
for(const [name,source,expected] of [
 ['cleanup return','int F(){try{return 42;}finally{Console.WriteLine("cleanup");}}Console.WriteLine(F());','cleanup\n42\n'],
 ['nested catch in cleanup','int F(){try{return 42;}finally{try{throw new Exception("inside");}catch(Exception e){Console.WriteLine(e.Message);}}}Console.WriteLine(F());','inside\n42\n'],
 ['heap roots during cleanup','C F(){try{return new C();}finally{GC.Collect();}}Console.WriteLine(F().X);class C{public int X=42;}','42\n'],
 ['using cleanup','int F(){using var r=new R();return 42;}Console.WriteLine(F());class R:IDisposable{public void Dispose(){Console.WriteLine("dispose");}}','dispose\n42\n'],
])test('0.6 snapshots replay '+name,()=>{const vm=new CilVirtualMachine(compile(source)),snapshots=[];while(vm.state==='ready'||vm.state==='running'){snapshots.push(vm.snapshot());vm.runSlice({instructionBudget:1,timeBudgetMs:1000});}assert.equal(vm.output.join(''),expected);for(const snapshot of snapshots.filter((s,i)=>i%3===0||s.frames.some(f=>f.pending))){vm.restore(snapshot);const result=vm.run();assert.equal(result.state,'terminated',result.fault?.stack);assert.equal(result.output,expected);}});
test('0.6 first chance faults are restored with their type and shared unwind identity',()=>{const d=start(compile('try{throw new Exception("x");}catch(Exception e){Console.WriteLine(e.Message);}'),{});d.exceptionBreak='all';step(d,'continue');assert(d.vm.pendingFault instanceof ManagedFault);const s=d.vm.snapshot();step(d,'continue');assert.equal(d.vm.output.join(''),'x\n');d.vm.restore(s);assert(d.vm.pendingFault instanceof ManagedFault);step(d,'continue');assert.equal(d.vm.output.join(''),'x\n');});
test('0.6 static write breakpoint is post-write and reverse restores storage',()=>{const bytes=managedFixture({fields:[{name:'Value'}],methods:[{name:'Main',result:'int',body:(w,c)=>w.op('ldc.i4',7).op('stsfld',c.fields.Value).op('ldsfld',c.fields.Value).op('ret')}]});const d=start(bytes,{}),token=[...d.vm.statics.keys()][0];assert(d.setDataBreakpoints([{kind:'static',index:token}])[0].verified);step(d,'continue');assert.equal(d.reason.reason,'data breakpoint');assert.equal(d.vm.statics.get(token),7);d.stepBack();assert.equal(d.vm.statics.get(token),0);step(d,'continue');assert.equal(d.reason.reason,'data breakpoint');step(d,'continue');assert.equal(d.state().returnValue,'7');});
test('0.6 local stind and cpobj writes trigger data breakpoints',()=>{const bytes=managedFixture({methods:[{name:'Main',result:'int',locals:['int','int'],body:(w,c)=>w.op('ldloca.s',0).op('ldc.i4',9).op('stind.i4').op('ldloca.s',1).op('ldloca.s',0).op('cpobj',c.md.typeRef('System.Int32')).op('ldloc.1').op('ret')}]});const d=start(bytes,{});d.setDataBreakpoints([{kind:'local',frameId:d.vm.top.id,index:0},{kind:'local',frameId:d.vm.top.id,index:1}]);step(d,'continue');assert.equal(d.vm.top.locals[0],9);assert.equal(d.reason.reason,'data breakpoint');step(d,'continue');assert.equal(d.vm.top.locals[1],9);assert.equal(d.reason.reason,'data breakpoint');step(d,'continue');assert.equal(d.state().returnValue,'9');});
test('0.6 data breakpoints retain allocation identity and validate storage',()=>{const d=start();const old=d.vm.heap.array('int',1);d.vm.heap.rootProvider=()=>[];d.vm.heap.collect();const next=d.vm.heap.array('int',1);assert.equal(next.h,old.h);assert.notEqual(next.g,old.g);assert.equal(d.setDataBreakpoints([{kind:'array',handle:old.h,generation:old.g,index:0}])[0].verified,false);for(const bad of [{kind:'local',index:100},{kind:'static',index:100},{kind:'array',handle:next.h,generation:next.g,index:1},{kind:'box',handle:next.h,generation:next.g,index:0},{dataId:'junk'},{kind:'arg',index:0,accessType:'read'}])assert.equal(d.setDataBreakpoints([bad])[0].verified,false);});
test('0.6 argument write data IDs round trip and hit rules work',()=>{const d=start(),info=d.dataBreakpointInfo({name:'arg0'});assert.equal(info.canPersist,false);assert.deepEqual(info.accessTypes,['write']);assert(d.setDataBreakpoints([{dataId:info.dataId,hitCondition:'2',condition:'arg0 == 30'}])[0].verified);d.setVariable(undefined,'arg0','25');assert.notEqual(d.reason.reason,'data breakpoint');d.setVariable(undefined,'arg0','30');assert.equal(d.reason.reason,'data breakpoint');assert.equal(d.dataBreakpoints[0].hits,2);});
test('0.6 data-stop resume does not skip next instruction breakpoint',()=>{const bytes=managedFixture({methods:[{name:'Main',result:'int',locals:['int'],body:w=>w.op('ldc.i4.1').op('stloc.0').op('ldloc.0').op('ret')}]});const d=start(bytes,{});d.setDataBreakpoints([{kind:'local',index:0}]);d.setInstructionBreakpoints([{instructionReference:r(2)}]);step(d,'continue');assert.equal(d.reason.reason,'data breakpoint');step(d,'continue');assert.equal(d.reason.reason,'instruction breakpoint');});
for(const Session of [DebugSession,CilDebugSession])test('0.6 checked watches '+Session.name,()=>{const d=new Session(compile('int x=2147483647;Console.WriteLine(x);'));d.start();d.runUntilStop();assert.throws(()=>d.evaluate('checked(2147483647+1)'),/overflow/i);assert.equal(d.evaluate('unchecked(2147483647+1)').result,'-2147483648');assert.throws(()=>d.evaluate('checked((int)2147483648.0)'),/overflow/i);});
test('0.6 DAP reverse and write breakpoint requests use expiring storage refs',async()=>{const d=new DebugAdapter();let seq=0;async function req(command,a={}){const r=await d.handle({seq:++seq,command,arguments:a});assert(r.success,r.message);return r.body;}await req('launch',{assembly:Array.from(arithmeticLibrary()),managedIL:true,stopOnEntry:true,methodToken:'Add',arguments:[20,22]});await req('configurationDone');d.pump();const frame=d.session.vm.top.id,scope=(await req('scopes',{frameId:frame})).scopes[0].variablesReference;const info=await req('dataBreakpointInfo',{variablesReference:scope,name:'arg0'});assert((await req('setDataBreakpoints',{breakpoints:[{dataId:info.dataId}]})).breakpoints[0].verified);await req('setVariable',{variablesReference:scope,name:'arg0',value:'30'});await req('stepBack');assert.equal(d.session.evaluate('arg0').result,'20');const expired=await d.handle({seq:++seq,command:'variables',arguments:{variablesReference:scope}});assert(!expired.success);await req('next');d.pump();await req('reverseContinue');assert.equal(d.session.vm.instructions,0);});
test('0.6 manual debugger collection has an independently reversible snapshot',()=>{const d=start();const orphan=d.vm.heap.string('unrooted');const before=d.vm.heap.stats.collections;d.collect();assert.throws(()=>d.vm.heap.get(orphan));d.stepBack();assert.equal(d.vm.heap.get(orphan).kind,'string');assert.equal(d.vm.heap.stats.collections,before);assert.equal(d.vm.instructions,0);step(d);d.stepBack();assert.equal(d.vm.instructions,0);});
