import test from 'node:test';
import assert from 'node:assert/strict';
import {CilDebugSession,instructionReference,DebugSession} from '@sharpforge/debugger';
import {DebugAdapter} from '@sharpforge/protocol';
import {compileToIL} from '@sharpforge/compiler';
import {arithmeticLibrary,managedFixture} from './managed-fixtures.js';
const ref=(offset=0,token=0x06000001)=>instructionReference(token,offset);
function stopped(session,mode){if(mode)session.resume(mode);return session.runUntilStop();}
function start(bytes=arithmeticLibrary(),options={methodToken:'Add',arguments:[20,22]}){const d=new CilDebugSession(bytes,options);d.start();stopped(d);return d;}
test('0.5 CIL debugger: entry, real instruction bytes, and primitive slots without debug metadata',()=>{const d=start();assert.equal(d.reason.reason,'entry');assert.equal(d.stackTrace()[0].source,null);assert.equal(d.stackTrace()[0].instructionPointerReference,ref());assert.equal(d.evaluate('arg0 + arg1').result,'42');assert.deepEqual(d.disassemble(ref()).map(i=>i.instructionBytes),['02','03','58','2a']);});
test('0.5 CIL debugger: argument mutation before the load changes execution',()=>{const d=start();d.setVariable(undefined,'arg0','30');stopped(d,'continue');assert.equal(d.state().returnValue,'52');});
test('0.5 CIL debugger: editing argument does not rewrite values already on evaluation stack',()=>{const d=start();stopped(d,'stepIn');d.setVariable(undefined,'arg0','30');stopped(d,'continue');assert.equal(d.state().returnValue,'42');});
test('0.5 CIL debugger: step advances exactly one decoded instruction',()=>{const d=start();for(const offset of [1,2,3]){stopped(d,'stepIn');assert.equal(d.stackTrace()[0].ilOffset,offset);}stopped(d,'stepIn');assert.equal(d.vm.state,'terminated');});
test('0.5 CIL debugger: conditional instruction breakpoints and resume skip',()=>{const d=start();const b=d.setInstructionBreakpoints([{instructionReference:ref(2),condition:'arg0 == 20',hitCondition:'1'}]);assert(b[0].verified);stopped(d,'continue');assert.equal(d.reason.reason,'instruction breakpoint');assert.equal(d.stackTrace()[0].ilOffset,2);stopped(d,'continue');assert.equal(d.vm.state,'terminated');});
test('0.5 CIL debugger: logpoints do not stop and use safe watches',()=>{const d=start();d.setInstructionBreakpoints([{instructionReference:ref(2),logMessage:'sum {arg0 + arg1}'}]);stopped(d,'continue');assert.equal(d.vm.output.join(''),'sum 42\n');});
test('0.5 CIL debugger: invalid locations, expressions and hit conditions rejected',()=>{const d=start();for(const x of [{instructionReference:'bad'},{instructionReference:ref(999)},{instructionReference:ref(2),condition:'x +'},{instructionReference:ref(2),hitCondition:'0'}])assert.equal(d.setInstructionBreakpoints([x])[0].verified,false);assert.throws(()=>d.disassemble(ref(),{instructionCount:1001}));});
test('0.5 CIL debugger: run to instruction is temporary',()=>{const d=start();d.runToInstruction(ref(3));stopped(d);assert.equal(d.reason.reason,'goto');assert.equal(d.breakpoints.length,0);stopped(d,'continue');assert.equal(d.vm.state,'terminated');});
test('0.5 CIL debugger: conditions must be boolean',()=>{const d=start();d.setInstructionBreakpoints([{instructionReference:ref(2),condition:'arg0'}]);stopped(d,'continue');assert.match(d.reason.description,/bool/);});
test('0.5 CIL debugger: side effects and wrong-type edits are refused',()=>{const d=start();for(const e of ['arg0++','arg0=3','Console.WriteLine(3)','new Exception()'])assert.throws(()=>d.evaluate(e));assert.throws(()=>d.setVariable(undefined,'arg0','"oops"'));assert.equal(d.evaluate('arg0').result,'20');assert.throws(()=>d.stepBack(),/Reverse/);});
test('0.5 CIL debugger: comparison and boolean watch semantics',()=>{const d=start();for(const [e,expected]of [['arg0<arg1',true],['arg0<=20',true],['arg0>arg1',false],['arg0>=20',true],['arg0!=arg1',true],['arg0==arg1',false],['false && missing',false],['true || missing',true]])assert.equal(d.evaluate(e).value,expected,e);});
test('0.5 CIL debugger: exception pause resumes handling and finally exactly once',()=>{const r=compileToIL('try{try{throw new Exception("x");}finally{Console.WriteLine("final");}}catch(Exception e){Console.WriteLine(e.Message);}');assert(r.success);const d=new CilDebugSession(r.assembly);d.exceptionBreak='all';d.start(false);stopped(d);assert.equal(d.reason.reason,'exception');assert(d.vm.pendingFault);d.vm.heap.collect();stopped(d,'continue');assert.equal(d.vm.state,'terminated',d.vm.fault?.stack);assert.equal(d.vm.output.join(''),'final\nx\n');});
test('0.5 CIL debugger: uncaught-only ignores exceptions with finally plus outer catch',()=>{const r=compileToIL('try{try{throw new Exception("x");}finally{Console.WriteLine(1);}}catch(Exception e){}');const d=new CilDebugSession(r.assembly);d.exceptionBreak='uncaught';d.start(false);stopped(d);assert.equal(d.vm.state,'terminated');});
test('0.5 CIL debugger: function entry and step out honor stack depth',()=>{const r=compileToIL('int F(int x){return x+1;}Console.WriteLine(F(5));');const d=new CilDebugSession(r.assembly);assert(d.setFunctionBreakpoints(['F'])[0].verified);d.start(false);stopped(d);assert.equal(d.reason.reason,'function breakpoint');const depth=d.vm.frames.length;stopped(d,'stepOut');assert.equal(d.reason.reason,'step');assert(d.vm.frames.length<depth);stopped(d,'continue');assert.equal(d.vm.output.join(''),'6\n');});
test('0.5 CIL debugger: native break pauses only in debug mode',()=>{const b=managedFixture({methods:[{name:'Main',result:'int',body:w=>w.op('break').op('ldc.i4',7).op('ret')}]});const d=new CilDebugSession(b);d.start(false);stopped(d);assert.equal(d.reason.reason,'pause');stopped(d,'continue');assert.equal(d.state().returnValue,'7');});
test('0.5 DAP: managed DLL launch, pending instruction breakpoints, disassembly and restart',async()=>{const events=[],d=new DebugAdapter({send:e=>events.push(e)});let seq=0;const req=async(command,args={})=>{const r=await d.handle({seq:++seq,command,arguments:args});assert(r.success,r.message);return r.body;};await req('setInstructionBreakpoints',{breakpoints:[{instructionReference:ref(2)}]});await req('launch',{assembly:Array.from(arithmeticLibrary()),managedIL:true,methodToken:'Add',arguments:[20,22],stopOnEntry:false});await req('configurationDone');d.pump();assert.equal(d.session.reason.reason,'instruction breakpoint');const stack=await req('stackTrace');assert.equal(stack.stackFrames[0].source,undefined);assert.equal((await req('disassemble',{memoryReference:ref(),instructionCount:4})).instructions.length,4);const scope=await req('scopes',{frameId:stack.stackFrames[0].id}),variables=await req('variables',{variablesReference:scope.scopes[0].variablesReference});assert.equal(variables.variables.length,2);await req('continue');d.pump();assert.equal(d.session.vm.state,'terminated');await req('restart');d.pump();assert.equal(d.session.reason.reason,'instruction breakpoint');assert(events.some(e=>e.event==='capabilities'&&e.body.capabilities.supportsStepBack===true));});
