import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,readdirSync} from 'node:fs';import {join,relative} from 'node:path';
import {compileToIL} from '@sharpforge/compiler';import {VirtualMachine,CilVirtualMachine} from '@sharpforge/runtime';import {loadAssembly,formatILDocument,assembleILDocument} from '@sharpforge/cil';import {ProjectSystem,buildSolutionTree,parseXml,addSolutionProject,addSolutionFolder,rewriteProjectPath,editNamedProjectItem,editProjectMembership} from '@sharpforge/project-system';import {TreeModel} from '@sharpforge/controls';import {samples} from '../apps/studio/samples.js';
const manifest=JSON.parse(readFileSync(new URL('../examples/features-0.8/manifest.json',import.meta.url),'utf8'));
for(const sample of manifest)for(const route of ['IR','canonical','direct','edited'])test(`08 shipped example ${sample.id}: ${route}`,()=>{assert.deepEqual(samples.find(s=>s.id===sample.id),sample);const result=compileToIL(sample.files);assert(result.success,JSON.stringify(result.diagnostics));const vm=route==='IR'?new VirtualMachine(result.image):route==='canonical'?new VirtualMachine(loadAssembly(result.assembly)):new CilVirtualMachine(route==='edited'?assembleILDocument(formatILDocument(result.assembly)).bytes:result.assembly);const actual=vm.run();assert.equal(actual.state,'terminated',actual.fault?.stack);assert.equal(actual.output,sample.expectedOutput);});
function fixture(){const root=new URL('../examples/projects/ExplorerWorkshop/',import.meta.url).pathname,files=[];function walk(path){for(const entry of readdirSync(path,{withFileTypes:true})){const p=join(path,entry.name);if(entry.isDirectory())walk(p);else if(!p.endsWith('.dll'))files.push({path:relative(root,p),text:readFileSync(p,'utf8')});}}walk(root);return files;}
test('08 ExplorerWorkshop solution has linked source and visible noncompiling cs note',()=>{const files=fixture(),p=new ProjectSystem(files),snapshot=p.load('ExplorerWorkshop.slnx');assert.equal(snapshot.diagnostics.length,0,JSON.stringify(snapshot.diagnostics));const options=p.compilationOptions('App/App.csproj'),r=compileToIL(p.compilationFiles('App/App.csproj'),options);assert(r.success,JSON.stringify(r.diagnostics));assert.equal(new CilVirtualMachine(r.assembly).run().output,'42\n42\n');const t=new TreeModel(buildSolutionTree({files,snapshot}));const all=[...t.nodes.values()];assert(all.some(n=>n.path==='App/Scratch.cs'&&n.itemType==='None'&&n.included));assert(all.some(n=>n.kind==='folder'&&n.path==='App/NewItems'));assert(all.some(n=>n.path==='Shared/Answer.cs'&&n.linked));assert(all.some(n=>n.path==='App/Data/settings.json'&&n.itemType==='Content'));});
test('08 source member hierarchy retains bound spans and is never a file operation target',()=>{const symbols=[{id:'c',name:'Counter',kind:'class',uri:'Counter.cs',start:6,end:13},{id:'p',name:'Value',owner:'Counter',kind:'property',type:'int',uri:'Counter.cs',start:20,end:25},{id:'m',name:'Add',owner:'Counter',kind:'method',parameters:[{type:'int'}],uri:'Counter.cs',start:30,end:33}];const t=new TreeModel(buildSolutionTree({files:[{path:'Counter.cs'}],symbols}));const type=[...t.nodes.values()].find(n=>n.kind==='symbol'&&n.label==='Counter');assert.equal(type.children.length,2);assert(type.children.some(n=>n.label==='Add(int)'&&n.start===30));assert(type.children.every(n=>n.draggable===false));});
for(const shape of ['<Folder Name="/src/" />','<Folder Name="/src/"><!-- retained --><Project Path="Old.csproj"/></Folder>'])test('08 project is inserted into one existing solution folder: '+shape,()=>{const s='\uFEFF<Solution>'+shape+'</Solution><!-- </Solution> -->';const added=addSolutionProject(s,{solutionPath:'Demo.slnx',projectPath:'App/App.csproj',folder:'src'}),root=parseXml(added);assert.equal(root.children.length,1);assert(root.children[0].children.some(n=>n.attributes.Path==='App/App.csproj'));assert(added.endsWith('<!-- </Solution> -->'));assert(added.startsWith('\uFEFF'));assert.throws(()=>addSolutionFolder(added,'/src/'),/already exists/);});
test('08 XML path rename cannot rewrite element text or quoted metadata',()=>{const s='<Project><Property>Include="A.cs"</Property><!-- Path="A.cs" --><![CDATA[Path="A.cs"]]><Compile Include = "A.cs" Note=\'Include="A.cs"\'/><Import Project="A.cs"/></Project>';const result=rewriteProjectPath(s,{documentPath:'Demo.csproj',oldPath:'A.cs',newPath:'B.cs'});assert(result.includes('<Property>Include="A.cs"</Property>'));assert(result.includes("Note='Include=\"A.cs\"'"));assert(result.includes('Include = "B.cs"'));assert(result.includes('<Import Project="B.cs"'));});
function evaluate(xml,extra=[]){return new ProjectSystem([{path:'App.csproj',text:xml},{path:'Program.cs',text:'Console.WriteLine(42);'},...extra]).load('App.csproj');}
test('08 removed package/assembly items have no phantom unsupported dependency diagnostic',()=>{let xml='<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><PackageReference Include="Example" Version="1.0"/><Reference Include="Library"/></ItemGroup></Project>';xml=editNamedProjectItem(xml,{name:'Example',include:false});xml=editNamedProjectItem(xml,{itemType:'Reference',name:'Library',include:false});const state=evaluate(xml);assert.equal(state.projects[0].packageReferences.length,0);assert.equal(state.projects[0].references.length,0);assert.equal(state.diagnostics.length,0,JSON.stringify(state.diagnostics));});
test('08 readding a package preserves one final version and one native-only diagnostic',()=>{let xml='<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><PackageReference Include="Example" Version="1.0"/></ItemGroup></Project>';xml=editNamedProjectItem(xml,{name:'Example',metadata:{Version:'2.0'}});const state=evaluate(xml);assert.equal(state.projects[0].packageReferences.length,1);assert.equal(state.projects[0].packageReferences[0].version,'2.0');assert.equal(state.diagnostics.length,1,JSON.stringify(state.diagnostics));});
test('08 removing and readding project reference evaluates only final items',()=>{let xml='<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="Library/Library.csproj"/></ItemGroup></Project>';xml=editProjectMembership(xml,{projectPath:'App.csproj',path:'Library/Library.csproj',itemType:'ProjectReference',include:false});const state=evaluate(xml);assert.equal(state.projects[0].projectReferences.length,0);assert.equal(state.diagnostics.length,0);});
test('08 generic items retain metadata updates and compile none transitions',()=>{const xml='<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><Compile Remove="Program.cs"/><None Include="Program.cs" Link="Notes/Program.cs"/><None Update="Program.cs"><CopyToOutputDirectory>Never</CopyToOutputDirectory></None><Content Include="Temporary.txt"/><Content Remove="Temporary.txt"/></ItemGroup></Project>',state=evaluate(xml);assert.equal(state.projects[0].compile.length,0);assert.equal(state.projects[0].items.length,1);const item=state.projects[0].items[0];assert.equal(item.metadata.Link,'Notes/Program.cs');assert.equal(item.metadata.CopyToOutputDirectory,'Never');assert.equal(state.diagnostics.length,0);});
