import test from 'node:test';
import assert from 'node:assert/strict';
import {DebugAdapter} from '@sharpforge/protocol';
import {compileToIL} from '@sharpforge/compiler';
import {arithmeticLibrary} from './managed-fixtures.js';
function adapter(){const events=[],d=new DebugAdapter({send:e=>events.push(e)});let seq=0;const raw=(command,args={})=>d.handle({seq:++seq,command,arguments:args});const req=async(c,a)=>{const r=await raw(c,a);assert(r.success,r.message);return r.body;};return {d,events,req,raw};}
function bytes(text){const r=compileToIL(text);assert(r.success,JSON.stringify(r.diagnostics));return [...r.assembly];}
function pump(d){for(let i=0;i<1000&&d.session.vm.state!=='paused'&&d.session.vm.state!=='terminated'&&d.session.vm.state!=='faulted';i++)d.pump({instructionBudget:10000,timeBudgetMs:1000});}
test('0.9 DAP launch cannot run before configurationDone, default does not force entry',async()=>{const {d,req,events}=adapter();await req('launch',{assembly:bytes('Console.WriteLine(42);')});d.pump();assert.equal(d.session.vm.instructions,0);assert.equal(d.session.vm.state,'ready');await req('configurationDone');pump(d);assert.equal(d.session.vm.state,'terminated');assert.equal(events.filter(e=>e.event==='stopped').length,0);assert.equal(d.session.vm.output.join(''),'42\n');});
test('0.9 DAP explicit entry remains distinct from breakpoint',async()=>{const {d,req,events}=adapter();await req('launch',{assembly:bytes('int x=1;\nConsole.WriteLine(x);'),stopOnEntry:true});await req('setBreakpoints',{source:{path:'Program.cs'},breakpoints:[{line:2}]});await req('configurationDone');pump(d);assert.equal(d.session.reason.reason,'entry');assert.equal(d.session.state().point.line,1);await req('continue');pump(d);assert.equal(d.session.reason.reason,'breakpoint');assert.equal(d.session.state().point.line,2);assert.deepEqual(events.filter(e=>e.event==='stopped').map(e=>e.body.reason),['entry','breakpoint']);});
test('0.9 DAP pending binding publishes changed event and hit IDs',async()=>{const {d,req,events}=adapter();const a=await req('setBreakpoints',{source:{path:'Program.cs'},breakpoints:[{line:2}]});assert.equal(a.breakpoints[0].verified,false);await req('launch',{assembly:bytes('// entry comment\nConsole.WriteLine(1);')});assert(events.some(e=>e.event==='breakpoint'&&e.body.breakpoint.verified));await req('configurationDone');pump(d);assert.deepEqual(events.find(e=>e.event==='stopped').body.hitBreakpointIds,[d.session.breakpoints[0].id]);});
test('0.9 DAP zero-based locations and stack columns roundtrip',async()=>{const {d,req}=adapter();await req('initialize',{linesStartAt1:false,columnsStartAt1:false});await req('launch',{assembly:bytes('int x=1;\n  Console.WriteLine(x);')});const result=await req('setBreakpoints',{source:{path:'Program.cs'},breakpoints:[{line:1,column:5}]});assert.equal(result.breakpoints[0].line,1);assert.equal(result.breakpoints[0].column,2);await req('configurationDone');pump(d);const stack=await req('stackTrace');assert.equal(stack.stackFrames[0].line,1);assert.equal(stack.stackFrames[0].column,2);const positions=await req('breakpointLocations',{source:{path:'Program.cs'},line:1});assert.equal(positions.breakpoints[0].column,2);});
test('0.9 DAP executable-location and exact embedded source requests',async()=>{const {req}=adapter();const text='Console.WriteLine(1);';await req('launch',{assembly:bytes(text)});const sources=await req('loadedSources');assert.equal(sources.sources[0].path,'Program.cs');assert.equal((await req('source',{source:{path:'Program.cs'}})).content,text);const locations=await req('breakpointLocations',{source:{path:'Program.cs'},line:1});assert.equal(locations.breakpoints.length,1);assert.equal(locations.breakpoints[0].endColumn,text.length+1);});
test('0.9 DAP rejects inspect/continue before configuration or while running',async()=>{const {req,raw}=adapter();await req('launch',{assembly:bytes('while(true){}')});for(const c of ['continue','stackTrace','scopes','evaluate'])assert.equal((await raw(c)).success,false,c);await req('configurationDone');assert.equal((await raw('stackTrace')).success,false);await req('pause');assert.equal((await raw('stackTrace')).success,true);});
test('0.9 DAP function conditions and hit counts are not discarded',async()=>{const {d,req}=adapter();await req('launch',{assembly:bytes('class P{static void F(int x){Console.WriteLine(x);}static void Main(){F(1);F(2);F(3);}}')});const bs=await req('setFunctionBreakpoints',{breakpoints:[{name:'P.F(int)',condition:'x == 2',hitCondition:'2'}]});assert(bs.breakpoints[0].verified);await req('configurationDone');pump(d);assert.equal(d.session.reason.reason,'function breakpoint');assert.equal(d.session.evaluate('x').result,'2');assert.equal(d.session.functionBreakpoints[0].hits,2);});
test('0.9 DAP source write breakpoints select correct storage and expire refs',async()=>{const {d,req,raw}=adapter();await req('launch',{assembly:bytes('int x=1;\nx=2;\nConsole.WriteLine(x);')});await req('setBreakpoints',{source:{path:'Program.cs'},breakpoints:[{line:2}]});await req('configurationDone');pump(d);const frame=d.session.vm.top.id,scope=(await req('scopes',{frameId:frame})).scopes[0].variablesReference;const info=await req('dataBreakpointInfo',{variablesReference:scope,name:'x'});assert(info.dataId);assert.equal(info.canPersist,false);assert((await req('setDataBreakpoints',{breakpoints:[{dataId:info.dataId}]})).breakpoints[0].verified);await req('continue');pump(d);assert.equal(d.session.reason.reason,'data breakpoint');assert.equal(d.session.evaluate('x').result,'2');assert.equal((await raw('variables',{variablesReference:scope})).success,false);});
test('0.9 DAP default unhandled exception stops before unwind then exits nonzero',async()=>{const {d,req,events}=adapter();await req('launch',{assembly:bytes('throw new Exception("x");')});await req('configurationDone');pump(d);assert.equal(d.session.reason.reason,'exception');assert.equal((await req('exceptionInfo')).breakMode,'unhandled');await req('continue');pump(d);assert.equal(events.find(e=>e.event==='exited').body.exitCode,1);});
test('0.9 DAP failed replacement launch preserves prior paused session',async()=>{const {d,req,raw}=adapter();await req('launch',{assembly:bytes('int x=1;'),stopOnEntry:true});await req('configurationDone');pump(d);const previous=d.session;assert.equal((await raw('launch',{assembly:[0,1,2],managedIL:true})).success,false);assert.equal(d.session,previous);assert.equal(d.session.vm.state,'paused');});
test('0.9 DAP direct IL function and instruction debug zero-source entry',async()=>{const {d,req}=adapter();await req('launch',{managedIL:true,assembly:[...arithmeticLibrary()],methodToken:'Add',arguments:[20,22]});await req('setFunctionBreakpoints',{breakpoints:[{name:'Program.Add',condition:'arg0 == 20'}]});const b=await req('setInstructionBreakpoints',{breakpoints:[{instructionReference:'il:06000001:00000001'}]});assert(b.breakpoints[0].verified);await req('configurationDone');pump(d);assert(['function breakpoint','instruction breakpoint'].includes(d.session.reason.reason));});
test('0.9 DAP source reverse continue emits actual previous stop',async()=>{const {d,req,events}=adapter();await req('launch',{assembly:bytes('for(int i=0;i<3;i++){\nConsole.WriteLine(i);\n}')});await req('setBreakpoints',{source:{path:'Program.cs'},breakpoints:[{line:2}]});await req('configurationDone');pump(d);await req('continue');pump(d);assert.equal(d.session.evaluate('i').result,'1');await req('reverseContinue');assert.equal(d.session.evaluate('i').result,'0');assert.equal(events.at(-1).event,'stopped');assert.deepEqual(events.at(-1).body.hitBreakpointIds,[d.session.breakpoints[0].id]);});
