import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {compileToIL} from '@sharpforge/compiler';import {VirtualMachine,CilVirtualMachine} from '@sharpforge/runtime';import {DebugSession,CilDebugSession} from '@sharpforge/debugger';import {DebugAdapter} from '@sharpforge/protocol';import {AssemblyInspector,loadAssembly,formatILDocument,assembleILDocument} from '@sharpforge/cil';import {samples as sampleList} from '../apps/studio/samples.js';const samples=Object.fromEntries(sampleList.map(s=>[s.id,s]));
const compiled=s=>{const c=compileToIL(s);assert(c.success,JSON.stringify(c.diagnostics));return c;};
const factories={source:c=>new VirtualMachine(c.image,{virtualTime:true}),reload:c=>new VirtualMachine(loadAssembly(c.assembly),{virtualTime:true}),cil:c=>new CilVirtualMachine(c.assembly,{virtualTime:true}),reassembled:c=>new CilVirtualMachine(assembleILDocument(formatILDocument(c.assembly)).bytes,{virtualTime:true})};
const ids=['async-stacks','logical-threads','hot-reload','set-next','function-evaluation','portable-symbols','winui-counter','winui-controls','winui-graphics','winui-async'];
for(const id of ids){const s=samples[id],c=compiled(s.files);test(`release10 examples: ${id} Studio/disk source is identical`,()=>{for(const f of s.files)assert.equal(readFileSync(new URL(`../examples/features-0.10/${id}/${f.uri}`,import.meta.url),'utf8'),f.text);});for(const[path,factory]of Object.entries(factories))test(`release10 examples: ${id} executes via ${path}`,async()=>{const vm=factory(c),r=await vm.runAsync();assert.equal(r.state,'terminated',r.fault?.message);if(s.ui)assert.equal(vm.platform.scene().windows.length,1);else assert.equal(r.output.trim(),s.expectedOutput.trim());});}
const lifecycle=`using Microsoft.UI.Xaml;using Microsoft.UI.Xaml.Controls;using Microsoft.UI.Xaml.Media;using Microsoft.UI;class P{static Window w;static TextBlock label;static SolidColorBrush brush;static void Loaded(object s,RoutedEventArgs e){Console.WriteLine("loaded");}static void Closed(object s,RoutedEventArgs e){Console.WriteLine("closed");}static void Update(object s,RoutedEventArgs e){brush.Color=Colors.Blue;w.Close();}static void Main(){brush=new SolidColorBrush(Colors.Red);label=new TextBlock(){Text="nested",Foreground=brush};Button b=new Button(){Content=label};b.Click+=Update;b.Loaded+=Loaded;w=new Window(){Content=b};w.Closed+=Closed;w.Activate();}}`;
for(const[path,factory]of Object.entries(factories))test(`${path}: Loaded/Closed callbacks, nested visual roots and mutable brush notifications`,async()=>{const c=compiled(lifecycle),vm=factory(c),events=[];vm.platform.options.onUICommand=x=>events.push(x);const r=await vm.runAsync();assert.equal(r.output,'loaded\n');const button=vm.platform.scene().nodes.find(n=>n.type.endsWith('.Button'));vm.platform.dispatchEvent(button.id,'Click');const done=await vm.runAsync();assert.equal(done.output,'loaded\nclosed\n');assert.equal(vm.platform.windows.size,0);});
for(const direct of [false,true]){
const create=text=>{const c=compiled(text);return direct?new CilDebugSession(c.assembly,{virtualTime:true,recordHistory:true}):new DebugSession(c.image,{virtualTime:true,recordHistory:true});};
test(`${direct?'CIL':'source'}: step out crosses an async completion only to its actual awaiter`,()=>{const text='using System.Threading.Tasks;class P{static async Task<int> F(){\nawait Task.Delay(5);\nreturn 42;\n}\nstatic async Task Main(){\nint value=await F();\nConsole.WriteLine(value);\n}}';const s=create(text);s.setBreakpoints('Program.cs',[{line:3}]);s.start(false);s.runUntilStop();s.vm.scheduler.advance(5);s.runUntilStop();assert.equal(s.vm.state,'paused');const old=s.vm.scheduler.currentId;s.setBreakpoints('Program.cs',[]);s.resume('stepOut');s.runUntilStop();assert.equal(s.vm.state,'paused');assert.notEqual(s.vm.scheduler.currentId,old);assert.equal(s.stackTrace()[0].line,7);assert.equal(s.evaluate('value').result,'42');});
test(`${direct?'CIL':'source'}: queued UI clicks retain independent logical stacks over repeated GC`,async()=>{const c=create(samples['winui-counter'].files);c.start(false);c.runUntilStop();let button=c.vm.platform.scene().nodes.find(n=>n.type.endsWith('.Button'));for(let i=0;i<20;i++){c.vm.platform.dispatchEvent(button.id,'Click');c.vm.heap.collect();c.runUntilStop();}assert.equal(c.vm.platform.scene().nodes.find(n=>n.properties.Name==='Counter').properties.Text,'Count: 20');});
}
const bytes=new Uint8Array(readFileSync(new URL('../examples/managed/PortableSymbols.dll',import.meta.url))),entry=JSON.parse(readFileSync(new URL('../examples/managed/PortableSymbols.fixture.json',import.meta.url))).entryToken;
test('PortableSymbols fixture has no #SF stream and source entry/stepping uses verified PDB offsets',()=>{assert(!new AssemblyInspector(bytes).metadata.streams.has('#SF'));const s=new CilDebugSession(bytes,{methodToken:entry});s.start();s.runUntilStop();assert.equal(s.stackTrace()[0].line,3);s.resume('next');s.runUntilStop();assert.equal(s.stackTrace()[0].line,4);assert.equal(s.evaluate('value').result,'20');s.resume('stepIn',{granularity:'instruction'});s.runUntilStop();assert.equal(s.stackTrace()[0].line,4);assert.equal(s.vm.top.pc,6);});
// Pump to a managed scheduling boundary, not a single wall-clock budget under CPU contention.
function settle(a){let turns=0;do{a.pump();if(++turns>1000)throw new Error('DAP did not reach a scheduling boundary');}while(a.session.vm.state==='running');}
function dap(){const events=[],adapter=new DebugAdapter({send:x=>events.push(x)});let seq=0;return {a:adapter,events,request:async(command,arguments_={})=>{const r=await adapter.handle({seq:++seq,type:'request',command,arguments:arguments_});assert(r.success,r.message);return r.body;},raw:(command,arguments_={})=>adapter.handle({seq:++seq,type:'request',command,arguments:arguments_})};}
for(const native of [false,true])test(`DAP ${native?'ordinary IL/PDB':'IR'}: goto targets, stale token rejection and preserved locals`,async()=>{const {a,request,raw}=dap();await request('initialize');await request('launch',native?{assembly:bytes,managedIL:true,methodToken:entry,stopOnEntry:true}:{image:compiled('int x=20;\nx=x+22;\nConsole.WriteLine(x);').image,stopOnEntry:true});await request('configurationDone');settle(a);await request('next');settle(a);const line=native?5:3,uri=native?'external/ExternalProgram.cs':'Program.cs';const targets=await request('gotoTargets',{source:{path:uri},line});assert.equal(targets.targets.length,1);await request('goto',{targetId:targets.targets[0].id,threadId:1});assert.equal((await raw('goto',{targetId:targets.targets[0].id})).success,false);await request('continue');settle(a);assert.equal(a.session.vm.output.join(''),'20\n');});
test('DAP effectful evaluation remains opt-in; Hot Reload updates actual suspended code generation',async()=>{const c=compiled(samples['function-evaluation'].files),{a,request,raw}=dap();await request('launch',{image:c.image});await request('setBreakpoints',{source:{path:'Program.cs'},breakpoints:[{line:13}]});await request('configurationDone');settle(a);const fid=a.session.stackTrace()[0].id;assert.equal((await raw('evaluate',{expression:'ledger.Add(2)',frameId:fid,context:'watch'})).success,false);assert.equal((await request('evaluate',{expression:'ledger.Add(2)',frameId:fid,context:'repl',allowSideEffects:true,commit:false})).result,'42');assert.equal((await request('evaluate',{expression:'ledger.Value',frameId:fid})).result,'40');const next=compiled(samples['function-evaluation'].files.map(f=>({...f,text:f.text.replace('Value += amount','Value += amount * 2')})));await request('sharpforge/hotReload',{image:next.image,expectedVersion:0});assert.equal(a.session.codeVersion,1);assert.equal((await request('sharpforge/evaluateFunction',{expression:'ledger.Add(1)',frameId:fid,allowSideEffects:true})).result,'42');});
test('DAP maps logical threads, waiting locals, freeze and async stack dependencies',async()=>{const {a,request}=dap();await request('launch',{image:compiled(samples['async-stacks'].files).image,virtualTime:true});await request('configurationDone');settle(a);assert.equal(a.session.vm.state,'waiting');const model=await request('sharpforge/parallelStacks');assert(model.contexts.some(c=>c.waitingFor));const t=model.contexts.find(t=>t.kind==='async');assert((await request('stackTrace',{threadId:t.id})).totalFrames>0);await request('sharpforge/freezeThread',{threadId:t.id,frozen:true});assert(a.session.threads().find(x=>x.id===t.id).frozen);await request('sharpforge/freezeThread',{threadId:t.id,frozen:false});});
test('DAP retains active application after Main returns and runs managed UI events',async()=>{const {a,request,events}=dap();await request('launch',{image:compiled(samples['winui-counter'].files).image,virtualTime:true});await request('configurationDone');settle(a);assert(!events.some(e=>e.event==='terminated'));const scene=await request('sharpforge/uiScene'),b=scene.nodes.find(n=>n.type.endsWith('.Button'));await request('sharpforge/uiEvent',{id:b.id,event:'Click'});settle(a);assert.equal((await request('sharpforge/uiScene')).nodes.find(n=>n.properties.Name==='Counter').properties.Text,'Count: 1');});
