/** Actual production runtime worker with only the browser transport adapted to Node. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {Worker} from 'node:worker_threads';
import {compileToIL} from '@sharpforge/compiler';
import {samples} from '../apps/studio/samples.js';
const workerURL=new URL('../apps/studio/runtime.worker.js',import.meta.url).href;
function connect(t){
 const code=`import {parentPort} from 'node:worker_threads';globalThis.self={postMessage:value=>parentPort.postMessage(value)};await import(${JSON.stringify(workerURL)});parentPort.on('message',data=>self.onmessage({data}));parentPort.postMessage({event:'ready'});`;
 const worker=new Worker(new URL('data:text/javascript,'+encodeURIComponent(code)),{type:'module'}),pending=new Map(),events=[];let serial=0;
 worker.on('message',m=>{if(m.id!==undefined){const p=pending.get(m.id);if(!p)return;pending.delete(m.id);clearTimeout(p.timer);m.error?p.reject(new Error(m.error.message)):p.resolve(m.result);}else events.push(m);});
 worker.on('error',e=>{for(const p of pending.values()){clearTimeout(p.timer);p.reject(e);}pending.clear();});
 t.after(async()=>{await worker.terminate();for(const p of pending.values()){clearTimeout(p.timer);p.reject(new Error('Worker closed'));}pending.clear();});
 async function wait(predicate){const until=Date.now()+5000;while(Date.now()<until){const event=events.find(predicate);if(event)return event;await new Promise(r=>setTimeout(r,2));}throw new Error('Worker event timeout: '+JSON.stringify(events.slice(-3)));}
 function request(method,params={}){return new Promise((resolve,reject)=>{const id=++serial,timer=setTimeout(()=>{pending.delete(id);reject(new Error('Request timeout: '+method));},5000);pending.set(id,{resolve,reject,timer});worker.postMessage({id,method,params});});}
 return {request,wait,events,ready:()=>wait(m=>m.event==='ready'),clear:()=>{events.length=0;}};
}
function assembly(text){const r=compileToIL(text);assert(r.success,JSON.stringify(r.diagnostics));return r.assembly;}
const source='for(int i=0;i<3;i++)\n{\n Console.WriteLine(i);\n}\n';
async function setup(t,params={}){const w=connect(t);await w.ready();const launch=await w.request('launch',{assembly:assembly(source),debug:true,breakpoints:{'Program.cs':[{line:3}]},...params});const s=await w.wait(m=>m.event==='state'&&m.state==='paused'&&m.sessionId===launch.sessionId);return {w,s,launch};}

test('0.9 worker F5 default starts at breakpoint rather than forced entry',async t=>{const {s}=await setup(t);assert.equal(s.reason.reason,'breakpoint');assert.equal(s.point.line,3);assert.equal(s.output,'');assert.equal(s.breakpoints[0].hits,1);});
test('0.9 worker publishes exact source and new identity before any session state',async t=>{const {w,launch}=await setup(t),loaded=w.events.findIndex(m=>m.event==='loaded');assert(loaded>=0);assert.equal(w.events[loaded].sources[0].text,source);assert(w.events.findIndex(m=>m.event==='state'&&m.sessionId===launch.sessionId)>loaded);});
test('0.9 worker explicit entry remains distinct from breakpoint',async t=>{const {s}=await setup(t,{stopOnEntry:true});assert.equal(s.reason.reason,'entry');assert.equal(s.point.line,1);assert.equal(s.breakpoints[0].hits,0);});
test('0.9 worker malformed assembly does not destroy existing paused session',async t=>{const {w,s}=await setup(t);await assert.rejects(w.request('launch',{assembly:new Uint8Array([1,2]),debug:true}));const current=await w.request('state',{sessionId:s.sessionId});assert.equal(current.point.line,3);assert.equal(current.state,'paused');assert.equal((await w.request('evaluate',{expression:'i',sessionId:s.sessionId})).result,'0');});
test('0.9 worker bad breakpoint target preserves the previously paused session',async t=>{const {w,s}=await setup(t);await assert.rejects(w.request('launch',{assembly:assembly(source),debug:true,runToCursor:{uri:'Missing.cs',line:999}}));assert.equal((await w.request('state',{sessionId:s.sessionId})).reason.reason,'breakpoint');});
test('0.9 worker rejects stale session commands without disturbing current session',async t=>{const {w,launch}=await setup(t);w.clear();const replacement=await w.request('launch',{assembly:assembly('int x=42;\nConsole.WriteLine(x);'),debug:true,stopOnEntry:true});await w.wait(m=>m.event==='state'&&m.state==='paused'&&m.sessionId===replacement.sessionId);await assert.rejects(w.request('stop',{sessionId:launch.sessionId}),/session changed/i);assert.equal((await w.request('state',{sessionId:replacement.sessionId})).state,'paused');});
test('0.9 worker unscoped Stop safely covers a launch followed immediately by stop',async t=>{const w=connect(t);await w.ready();const launching=w.request('launch',{assembly:assembly('while(true){}'),debug:true});const stopping=w.request('stop');await Promise.all([launching,stopping]);assert.equal((await w.request('state')).state,'terminated');});
test('0.9 worker live source breakpoint update retains encounter counts',async t=>{const {w,s}=await setup(t);const [b]=await w.request('breakpoints',{uri:'Program.cs',breakpoints:[{line:3,enabled:true}],sessionId:s.sessionId});assert.equal(b.hits,1);w.clear();await w.request('resume',{mode:'continue',sessionId:s.sessionId});const next=await w.wait(m=>m.event==='state'&&m.state==='paused');assert.equal(next.breakpoints[0].hits,2);assert.equal(next.locals.find(l=>l.name==='i').value,'1');});
test('0.9 worker source write stop is at caller store not callee return',async t=>{const text='class P{\nstatic int F(){return 42;}\nstatic void Main(){\n int x=0;\n x=F();\n Console.WriteLine(x);\n}\n}',{w,s}=await setup(t,{assembly:assembly(text),breakpoints:{'Program.cs':[{line:5},{line:6}]}});const info=await w.request('dataBreakpointInfo',{frameId:s.frames[0].id,name:'x'});assert(info.dataId);await w.request('dataBreakpoints',{breakpoints:[{dataId:info.dataId}]});w.clear();await w.request('resume',{mode:'continue'});const write=await w.wait(m=>m.event==='state'&&m.state==='paused');assert.equal(write.reason.reason,'data breakpoint');assert.equal(write.point.line,5);assert.equal(write.locals.find(l=>l.name==='x').value,'42');w.clear();await w.request('resume',{mode:'continue'});const next=await w.wait(m=>m.event==='state'&&m.state==='paused');assert.equal(next.reason.reason,'breakpoint');assert.equal(next.point.line,6);});
test('0.9 worker changed condition and reverse continue reproduce exact count',async t=>{const {w,s}=await setup(t,{breakpoints:{'Program.cs':[{line:3,condition:'i',conditionMode:'whenChanged'}]}});assert.equal(s.breakpoints[0].hits,2);w.clear();await w.request('resume',{mode:'continue'});await w.wait(m=>m.event==='state'&&m.state==='paused');await w.request('reverseContinue');const back=await w.request('state');assert.equal(back.locals.find(l=>l.name==='i').value,'1');assert.equal(back.breakpoints[0].hits,2);});
test('0.9 worker function breakpoint binds signature and passes conditions',async t=>{const {s}=await setup(t,{assembly:assembly('class P {static int F(int n){return n;}static void Main(){Console.WriteLine(F(2));}}'),breakpoints:{},functionBreakpoints:[{name:'P.F(int)',condition:'n==2'}]});assert.equal(s.reason.reason,'function breakpoint');assert.equal(s.locals.find(l=>l.name==='n').value,'2');});
test('0.9 worker exact screenshot sample runs all ten requested stops',async t=>{const text=samples.find(x=>x.id==='recursion').files[0].text,{w,s}=await setup(t,{assembly:assembly(text),breakpoints:{'Program.cs':[{line:20}]}});let current=s;for(let i=0;i<10;i++){assert.equal(current.reason.reason,'breakpoint');assert.equal(current.point.line,20);assert.equal(current.frames[0].line,20);assert.equal(current.breakpoints[0].hits,i+1);assert.equal(current.locals.find(l=>l.name==='i').value,String(i));w.clear();await w.request('resume',{mode:'continue'});current=await w.wait(m=>m.event==='state'&&m.state!=='running');}assert.equal(current.state,'terminated');assert(current.output.endsWith('fib(9) = 34\n'));});
