import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {resolve} from 'node:path';
import {ProtocolMessageReader,encodeProtocolMessage} from '@sharpforge/protocol';
import {CilVirtualMachine} from '@sharpforge/runtime';
import {verifyCilAssembly} from '@sharpforge/cil';
import {managedFixture} from './managed-fixtures.js';
const te=new TextEncoder();
function execute(body,locals=[],result='int'){const bytes=managedFixture({methods:[{name:'Main',result,locals,body}]});const vm=new CilVirtualMachine(bytes),r=vm.run();assert.equal(r.state,'terminated',r.fault?.stack);return r.returnValue;}
for(const [type,size]of [['System.Boolean',1],['System.Byte',1],['System.Int16',2],['System.Char',2],['System.Int32',4],['System.UInt32',4],['System.Int64',8],['System.Single',4],['System.Double',8]])test('0.5 MSIL sizeof '+type,()=>assert.equal(execute((w,c)=>w.op('sizeof',c.resolve(type)).op('ret')),size));
test('0.5 MSIL cpobj copies primitive managed slots',()=>assert.equal(execute((w,c)=>w.op('ldc.i4',42).op('stloc.0').op('ldloca.s',1).op('ldloca.s',0).op('cpobj',c.resolve('System.Int32')).op('ldloc.1').op('ret'),['int','int']),42));
test('0.5 MSIL unbox provides an address into the original box',()=>assert.equal(execute((w,c)=>w.op('ldc.i4',5).op('box',c.resolve('System.Int32')).op('stloc.0').op('ldloc.0').op('unbox',c.resolve('System.Int32')).op('ldc.i4',23).op('stind.i4').op('ldloc.0').op('unbox.any',c.resolve('System.Int32')).op('ret'),['object']),23));
test('0.5 MSIL unbox address roots its box through collection',()=>assert.equal(execute((w,c)=>w.op('ldc.i4',17).op('box',c.resolve('System.Int32')).op('unbox',c.resolve('System.Int32')).op('call',c.member('System.GC','Collect','void')).op('ldind.i4').op('ret')),17));
test('0.5 MSIL primitive-only sizeof refuses arbitrary object layout',()=>{const bytes=managedFixture({methods:[{name:'Main',result:'int',body:(w,c)=>w.op('sizeof',c.resolve('System.Object')).op('ret')}]});const v=verifyCilAssembly(bytes);assert(!v.success);assert(v.issues.some(d=>d.code==='IL_TYPE'));});
test('0.5 MSIL wrong boxed type fails explicitly',()=>{const bytes=managedFixture({methods:[{name:'Main',result:'int',body:(w,c)=>w.op('ldc.i4',5).op('box',c.resolve('System.Int32')).op('unbox',c.resolve('System.Int16')).op('ldind.i2').op('ret')}]});const r=new CilVirtualMachine(bytes).run();assert.equal(r.state,'faulted');assert.match(r.fault.message,/Boxed type mismatch/);});
test('0.5 protocol UTF-8 byte count and one-byte chunking',()=>{const message={jsonrpc:'2.0',id:7,result:'Zażółć 😀'},frame=encodeProtocolMessage(message),reader=new ProtocolMessageReader();const all=[];for(const b of frame)all.push(...reader.feed(Uint8Array.of(b)));reader.finish();assert.deepEqual(all,[message]);assert.match(new TextDecoder().decode(frame),new RegExp('Content-Length: '+te.encode(JSON.stringify(message)).length));});
test('0.5 protocol coalesced frames and buffer compaction',()=>{const r=new ProtocolMessageReader({maxMessageBytes:20000}),frames=Array.from({length:8},(_,id)=>encodeProtocolMessage({id,text:'a'.repeat(1000)})),joined=new Uint8Array(frames.reduce((s,f)=>s+f.length,0));let at=0;for(const f of frames){joined.set(f,at);at+=f.length;}const result=[];for(let i=0;i<joined.length;i+=199)result.push(...r.feed(joined.slice(i,i+199)));r.finish();assert.equal(result.length,8);assert.equal(result[7].id,7);});
for(const text of ['Content-Length: 2\r\nContent-Length: 2\r\n\r\n{}','Content-Length: -1\r\n\r\n','X-Length: 2\r\n\r\n{}','Content-Length: 2\r\nContent-Type: application/json; charset=latin1\r\n\r\n{}','Content-Length: 2\r\n\r\n[]'])test('0.5 protocol rejects malformed framing '+text.slice(0,35),()=>{const r=new ProtocolMessageReader();assert.throws(()=>r.feed(te.encode(text)));assert.throws(()=>r.feed(encodeProtocolMessage({})),/failed/);r.reset();assert.deepEqual(r.feed(encodeProtocolMessage({})),[{}]);});
test('0.5 protocol refuses invalid UTF-8, oversized header/body and truncated streams',()=>{assert.throws(()=>new ProtocolMessageReader().feed(Uint8Array.from([...te.encode('Content-Length: 2\r\n\r\n'),0xff,0xff])));assert.throws(()=>new ProtocolMessageReader({maxHeaderBytes:24}).feed(te.encode('x'.repeat(25))));assert.throws(()=>new ProtocolMessageReader({maxMessageBytes:10}).feed(te.encode('Content-Length: 11\r\n\r\n')));const r=new ProtocolMessageReader();r.feed(te.encode('Content-Length: 2\r\n\r\n{'));assert.throws(()=>r.finish());});
function client(kind){const child=spawn(process.execPath,[resolve('packages/protocol/bin/sharpforge-'+kind+'.js')],{stdio:['pipe','pipe','pipe']}),reader=new ProtocolMessageReader(),messages=[],waiters=[];let stderr='';child.stdout.on('data',chunk=>{messages.push(...reader.feed(chunk));for(const wake of waiters.splice(0))wake();});child.stderr.on('data',c=>stderr+=c);return {child,messages,send:m=>child.stdin.write(encodeProtocolMessage(m)),wait:async predicate=>{const until=Date.now()+5000;while(!messages.some(predicate)){if(Date.now()>until)throw new Error('Timeout: '+JSON.stringify(messages)+' '+stderr);await Promise.race([new Promise(r=>waiters.push(r)),new Promise(r=>setTimeout(r,20))]);}return messages.find(predicate);},close:()=>child.kill(),stderr:()=>stderr};}
test('0.5 LSP stdio handles real UTF-8 requests, diagnostics and shutdown',async t=>{const c=client('lsp');t.after(()=>c.close());c.send({jsonrpc:'2.0',id:1,method:'initialize',params:{}});const init=await c.wait(m=>m.id===1);assert(init.result.capabilities.codeActionProvider.codeActionKinds.includes('refactor.extract'));c.send({jsonrpc:'2.0',method:'textDocument/didOpen',params:{textDocument:{uri:'Program.cs',version:1,text:'Console.WriteLine("żółć 😀");'}}});assert.deepEqual((await c.wait(m=>m.method==='textDocument/publishDiagnostics')).params.diagnostics,[]);c.send({jsonrpc:'2.0',id:2,method:'shutdown'});await c.wait(m=>m.id===2);c.send({jsonrpc:'2.0',id:3,method:'workspace/symbol',params:{query:''}});assert.equal((await c.wait(m=>m.id===3)).error.code,-32600);c.send({jsonrpc:'2.0',method:'exit'});const exit=await new Promise(r=>c.child.on('exit',r));assert.equal(exit,0);assert.equal(c.stderr(),'');});
test('0.5 DAP stdio loads a disk DLL and executes selected method',async t=>{const c=client('dap');t.after(()=>c.close());let seq=0;const request=async(command,args={})=>{const id=++seq;c.send({seq:id,type:'request',command,arguments:args});const response=await c.wait(m=>m.request_seq===id);assert(response.success,response.message);return response;};await request('initialize');await request('launch',{program:resolve('examples/managed/Arithmetic.dll'),methodToken:'Add',arguments:[20,22],stopOnEntry:true});await request('configurationDone');await c.wait(m=>m.event==='stopped');const stack=await request('stackTrace');assert(stack.body.stackFrames[0].instructionPointerReference);await request('continue');await c.wait(m=>m.event==='terminated');assert.equal(c.stderr(),'');});
