import test from 'node:test';import assert from 'node:assert/strict';
import {SyntaxHighlightIndex} from '@sharpforge/editor';import {SourceText} from '@sharpforge/text';import {Workspace} from '@sharpforge/workspace';import {LanguageService} from '@sharpforge/language';import {RefactoringEngine,selectionRanges} from '@sharpforge/refactoring';import {VirtualMachine,CilVirtualMachine} from '@sharpforge/runtime';import {emitAssembly} from '@sharpforge/cil';
function setup(text){const w=new Workspace();w.update('Program.cs',text,1);const r=new RefactoringEngine(w,new LanguageService(w));assert(w.compile().success,JSON.stringify(w.compile().diagnostics));return {w,r};}
function outputs(w){const compiled=w.compile(),a=new VirtualMachine(compiled.image).run(),b=new CilVirtualMachine(emitAssembly(compiled.image)).run();assert.equal(a.state,'terminated');assert.equal(b.state,'terminated');assert.equal(a.output,b.output);return a.output;}
function apply(text,selection,title){const {w,r}=setup(text),before=outputs(w),start=text.indexOf(selection),actions=r.actions('Program.cs',start,start+selection.length),action=actions.find(a=>a.title.startsWith(title));assert(action,actions.map(a=>a.title).join(', '));r.apply(action);assert.equal(outputs(w),before);return {w,r,action};}
const contiguous=(index,window)=>{assert.equal(window.runs.map(r=>index.source.text.slice(r.start,r.end)).join(''),index.source.text.slice(window.start,window.end));for(let i=1;i<window.runs.length;i++)assert.equal(window.runs[i-1].end,window.runs[i].start);};
test('0.6 highlight: indexed source preserves all UTF-16 and trivia characters',()=>{for(const text of ['','\n','  //😀 comment\r\nint n=1;\r\n/* a\r\nb */\tConsole.WriteLine(n);  ','/* unterminated\n  😀','\r\n\r\n']){const index=new SyntaxHighlightIndex(text);contiguous(index,index.window());}});
test('0.6 highlight: scrolling large files renders a bounded line window',()=>{const text=Array.from({length:20000},(_,i)=>`int value${i} = ${i}; // row ${i}\n`).join(''),index=new SyntaxHighlightIndex(text);for(const line of [0,50,1000,12000,19995]){const window=index.window({scrollTop:line*22,height:440});assert(window.lastLine-window.firstLine<=30);assert(window.characters<1600);assert(window.runs.length<400);contiguous(index,window);assert(window.firstLine<=line);assert(window.lastLine>line);}assert(index.runs.length>100000);});
test('0.6 highlight: lexical fallback still renders only the viewport',()=>{const index=new SyntaxHighlightIndex(('/* plain */\n').repeat(300),{maxLexCharacters:100}),view=index.window({scrollTop:1000,height:110});assert.equal(index.lexed,null);assert.equal(view.syntax,false);assert(view.characters<300);contiguous(index,view);});
test('0.6 highlight: huge-line token budget preserves text without thousands of nodes',()=>{const index=new SyntaxHighlightIndex('int x=1;'.repeat(10000)),view=index.window({maxRuns:10});assert.equal(view.runs.length,1);assert.equal(view.syntax,false);assert.equal(view.characters,index.source.length);contiguous(index,view);});
test('0.6 highlight: multiline comment clipping remains classified as comment',()=>{const text='/*\n'+('inside\n').repeat(80)+'*/',index=new SyntaxHighlightIndex(text),view=index.window({scrollTop:40*22,height:110});contiguous(index,view);assert.equal(view.runs.length,1);assert.equal(view.runs[0].kind,'comment');});
test('0.6 highlight: invalid viewport arguments fail without loops',()=>{const index=new SyntaxHighlightIndex('x');for(const opts of [{height:NaN},{scrollTop:-1},{lineHeight:0},{maxRuns:0},{overscan:1000}])assert.throws(()=>index.window(opts),RangeError);assert.throws(()=>new SyntaxHighlightIndex('x',{maxLexCharacters:-1}),RangeError);});
test('0.6 selection: nesting strictly grows and retains UTF-16 positions',()=>{const source=new SourceText('//😀\r\nint x=(1+2)*3;\r\nConsole.WriteLine(x);','Program.cs'),start=source.text.indexOf('2');const w=new Workspace();w.update(source.uri,source.text,1);let result=selectionRanges(w,source.uri,[start])[0],previous=-1,count=0;while(result){const a=source.offsetAt(result.range.start),b=source.offsetAt(result.range.end);assert(a<=start&&b>=start);assert(b-a>previous);previous=b-a;count++;result=result.parent;}assert(count>=4);});
for(const [name,source,select,title]of [
 ['make int const','int amount=7;Console.WriteLine(amount);','amount',"Make 'amount' constant"],
 ['make var const','var amount=7;Console.WriteLine(amount);','amount',"Make 'amount' constant"],
 ['make string const','string name="😀";Console.WriteLine(name);','name',"Make 'name' constant"],
 ['conditional return evaluation','int F(){Console.WriteLine("condition");return 1;}int A(){Console.WriteLine("a");return 42;}int B(){Console.WriteLine("b");return 1;}int Choose(){if(F()==1){return A();}else{return B();}}Console.WriteLine(Choose());','if(','Use conditional return'],
 ['conditional return CRLF','//😀\r\nint F(int x){\r\n if(x>0){return 7;}else{return 9;}\r\n}\r\nConsole.WriteLine(F(2));','if(','Use conditional return'],
 ['expression body method','Console.WriteLine(C.Add(41));class C{public static int Add(int x){return x+1;}}','Add(int','Use expression-bodied'],
 ['expression body void','C.Print(42);class C{public static void Print(int x){Console.WriteLine(x);}}','Print(int','Use expression-bodied'],
 ['scoped using','using(var item=new R()){Console.WriteLine("body");}Console.WriteLine("after");class R:IDisposable{public void Dispose(){Console.WriteLine("disposed");}}','using(','Use scoped using'],
 ['scoped using names remain bounded','using(R item=new R()){Console.WriteLine(2);}int item=3;Console.WriteLine(item);class R:IDisposable{public void Dispose(){Console.WriteLine(1);}}','using(','Use scoped using'],
 ])test('0.6 refactoring: '+name,()=>apply(source,select,title));
for(const source of ['int x=1;x++;Console.WriteLine(x);','int x=1;x+=2;Console.WriteLine(x);','int x=1;x=2;Console.WriteLine(x);','double x=1;Console.WriteLine(x);','const int x=1;Console.WriteLine(x);'])test('0.6 refactoring: mutable/nonexact/already const no make-const '+source,()=>{const {r}=setup(source);assert(!r.actions('Program.cs',source.indexOf('x')).some(a=>a.title.startsWith('Make')));});
for(const [source,selection,title]of [['int F(){ /* keep */ return 7;}Console.WriteLine(F());','F','Use expression-bodied'],['int F(int x){if(x>0){/* keep */ return 7;}else{return 9;}}Console.WriteLine(F(1));','if','Use conditional return'],['using(var r=new R()){/* keep */ Console.WriteLine(1);}class R:IDisposable{public void Dispose(){}}','using','Use scoped using']])test('0.6 refactoring: does not delete comments '+title,()=>{const {r}=setup(source);assert(!r.actions('Program.cs',source.indexOf(selection)).some(a=>a.title.startsWith(title)));});
test('0.6 refactoring: make-const stale edit is rejected atomically',()=>{const text='var amount=7;Console.WriteLine(amount);',{w,r}=setup(text),a=r.actions('Program.cs',text.indexOf('amount')).find(a=>a.title.startsWith('Make'));assert(a);w.update('Program.cs',text+'\n',2);assert.throws(()=>r.apply(a),/Stale/);assert.equal(w.documents.get('Program.cs').source.text,text+'\n');});
import {NavigationHistory} from '@sharpforge/editor';
const at=(uri,start=0)=>({uri,start,end:start});
test('0.6 navigation: bidirectional document locations preserve selections',()=>{const h=new NavigationHistory();h.push(at('A.cs',1));h.push({uri:'B.cs',start:2,end:7});h.push(at('C.cs',3));assert.equal(h.back().uri,'B.cs');assert.equal(h.current.end,7);assert.equal(h.back().uri,'A.cs');assert.equal(h.back(),null);assert.equal(h.forward().uri,'B.cs');assert.equal(h.forward().uri,'C.cs');assert.equal(h.forward(),null);});
test('0.6 navigation: origin cursor refresh does not create phantom jumps',()=>{const h=new NavigationHistory();h.push(at('A.cs'));h.update(at('A.cs',42));h.push(at('B.cs',5));assert.equal(h.back(at('B.cs',20)).start,42);assert.equal(h.forward().start,20);assert.equal(h.entries.length,2);});
test('0.6 navigation: new jump truncates forward history and deduplicates',()=>{const h=new NavigationHistory();h.push(at('A.cs'));h.push(at('B.cs'));h.back();h.push(at('C.cs'));h.push(at('C.cs'));assert.equal(h.canForward,false);assert.deepEqual(h.entries.map(e=>e.uri),['A.cs','C.cs']);});
test('0.6 navigation: retained history is bounded and immutable',()=>{const h=new NavigationHistory({limit:3});for(let i=0;i<8;i++)h.push(at('A.cs',i));assert.equal(h.entries.length,3);assert.equal(h.back().start,6);assert.equal(h.back().start,5);assert(Object.isFrozen(h.current));h.clear();assert.equal(h.current,null);assert.equal(h.canBack,false);assert.equal(h.canForward,false);});
test('0.6 navigation: invalid locations and limits rejected',()=>{assert.throws(()=>new NavigationHistory({limit:0}));const h=new NavigationHistory();for(const p of [at('',1),at('A',-1),{uri:'A',start:2,end:1},at('A',Infinity)])assert.throws(()=>h.push(p));});
