import test from 'node:test';import assert from 'node:assert/strict';
import {compileToIL} from '../packages/compiler/src/index.js';
import {loadAssembly} from '../packages/cil/src/index.js';
import {DebugSession,remapSourceBreakpoints,sourceBreakpointAt} from '../packages/debugger/src/index.js';
import {samples} from '../apps/studio/samples.js';
function debug(text,options={}){const r=compileToIL(typeof text==='string'?[{uri:'Program.cs',text}]:text);assert(r.success,JSON.stringify(r.diagnostics));return new DebugSession(loadAssembly(r.assembly),options);}
test('08 breakpoint reconfiguration preserves stable identity and hit counts',()=>{const d=debug('for(int i=0;i<4;i++){\nConsole.WriteLine(i);\n}');d.setBreakpoints('Program.cs',[{line:2}]);d.start(false);d.runUntilStop();const a=d.state().breakpoints[0];const b=d.setBreakpoints('Program.cs',[{line:2}])[0];assert.equal(a.id,b.id);assert.equal(b.hits,1);d.resume();d.runUntilStop();assert.equal(d.state().breakpoints[0].hits,2);d.setBreakpoints('Program.cs',[{line:2,hitCondition:'1'}]);assert.equal(d.state().breakpoints[0].hits,0);});
test('08 pending/invalid source breakpoints have useful reasons',()=>{const d=debug('// comment\nint x=1;\nConsole.WriteLine(x);');const b=d.setBreakpoints('Program.cs',[{line:1},{line:900},{line:-1},{line:NaN},{line:2,column:0}]);assert.equal(b[0].line,2);assert.equal(b[0].requestedLine,1);assert.match(b[0].message,/next executable/);assert(b.slice(1).every(b=>!b.verified&&b.message));});
test('08 resolved gutter location removes the original requested breakpoint',()=>{const requested=[{line:1,enabled:true}],bound=[{line:2,requestedLine:1}];assert.equal(sourceBreakpointAt(requested,bound,2),requested[0]);assert.equal(sourceBreakpointAt(requested,bound,1),requested[0]);assert.equal(sourceBreakpointAt(requested,bound,4),null);});
test('08 breakpoint column pins one sequence point on a multiple-statement line',()=>{const d=debug('int x=1; x=2; Console.WriteLine(x);');const b=d.setBreakpoints('Program.cs',[{line:1,column:10}])[0];d.start(false);d.runUntilStop();assert.equal(d.vm.currentPoint.id,b.pointId);d.resume();assert.equal(d.runUntilStop().state,'terminated');});
for(const [title,before,after,line,expected]of [
 ['insert before','a\nb\nc\n','x\ny\na\nb\nc\n',2,4],['delete before','a\nb\nc\n','b\nc\n',3,2],['same line edit','int x=1;\nnext();','int x=234;\nnext();',2,2],['replace preserve anchor','before\nline\nafter','NEW\nline\nAFTER',2,2],['CRLF','a\r\nb\r\nc','z\r\na\r\nb\r\nc',2,3],['EOF deletion','a\nb\nc','a',3,1]])test('08 breakpoint remap: '+title,()=>assert.equal(remapSourceBreakpoints(before,after,[{line,condition:'true'}])[0].line,expected));
test('08 source snapshots zero budget never throw or hang',()=>{const d=debug('int x=1;\nx++;',{recordHistory:true,maxHistory:0});d.start(false);assert.equal(d.runUntilStop().state,'terminated');assert.equal(d.history.length,0);});
test('08 source reverse restores hit counters before replay',()=>{const d=debug('for(int i=0;i<3;i++){\nConsole.WriteLine(i);\n}',{recordHistory:true});d.setBreakpoints('Program.cs',[{line:2}]);d.start(false);d.runUntilStop();d.resume();d.runUntilStop();assert.equal(d.state().breakpoints[0].hits,2);d.stepBack();assert(d.state().breakpoints[0].hits<2);d.resume();d.runUntilStop();assert.equal(d.state().breakpoints[0].hits,2);});
test('08 particle sample: every executable source line continues without a runtime fault',()=>{const r=compileToIL(samples[0].files);assert(r.success);const image=loadAssembly(r.assembly);for(const key of new Set(image.sequencePoints.map(p=>p.uri+':'+p.line))){const split=key.lastIndexOf(':'),uri=key.slice(0,split),line=Number(key.slice(split+1));const d=new DebugSession(image,{recordHistory:true,maxHistory:12});d.setBreakpoints(uri,[{line}]);d.start(false);let pauses=0;while(pauses<300){const state=d.runUntilStop();if(state.state!=='paused'){assert.equal(state.state,'terminated',key+' '+JSON.stringify(state.fault));assert.match(state.output,/Simulation complete/);break;}pauses++;d.resume();}assert(pauses<300,key+' made no progress');}});
