import test from 'node:test';
import assert from 'node:assert/strict';
import {compileToIL} from '@sharpforge/compiler';
import {DebugSession,CilDebugSession,SourceBreakpointIndex,instructionReference} from '@sharpforge/debugger';
import {VirtualMachine,ManagedFault} from '@sharpforge/runtime';
import {loadAssembly} from '@sharpforge/cil';
import {samples} from '../apps/studio/samples.js';
import {arithmeticLibrary,managedFixture} from './managed-fixtures.js';
const uri='Program.cs';
function compile(text){const r=compileToIL(text);assert(r.success,JSON.stringify(r.diagnostics));return r;}
function create(Session,text,options={}){return new Session(compile(text).assembly,{recordHistory:true,maxHistory:1000,...options});}
function run(d,mode='continue'){d.resume(mode);return d.runUntilStop();}
function stops(d,max=100){const results=[];while(d.vm.state==='paused'&&results.length<max){results.push(structuredClone(d.state()));run(d);}assert.notEqual(d.vm.state,'paused','stop count guard');return results;}
const loop='for(int i=0;i<5;i++)\n{\n Console.WriteLine(i);\n}\n';
for(const Session of [DebugSession,CilDebugSession]){
 const name=Session.name;
 test(`0.9 ${name} screenshot Fibonacci breakpoint hits exactly ten times before output`,()=>{
  const source=samples.find(s=>s.id==='recursion').files[0].text,d=create(Session,source);const [b]=d.setBreakpoints(uri,[{line:20}]);assert(b.verified);d.start(false);d.runUntilStop();const all=stops(d);assert.equal(all.length,10);for(const [i,s]of all.entries()){assert.equal(s.reason.reason,'breakpoint');assert.equal(s.reason.phase,'before');assert.equal(s.point.line,20);assert.equal(s.frames[0].line,20);assert.equal(s.point.column,13);assert.equal(s.breakpoints[0].hits,i+1);assert.equal(s.locals.find(l=>l.name==='i').value,String(i));assert.equal(s.output.split('\n').filter(Boolean).length,i);assert.deepEqual(s.reason.hitBreakpointIds,[b.id]);}assert.equal(d.vm.output.join(''),'fib(0) = 0\nfib(1) = 1\nfib(2) = 1\nfib(3) = 2\nfib(4) = 3\nfib(5) = 5\nfib(6) = 8\nfib(7) = 13\nfib(8) = 21\nfib(9) = 34\n');
 });
 test(`0.9 ${name} multiline continuation binds containing statement`,()=>{const d=create(Session,'int x=42;\nConsole.WriteLine(\n x\n);\nConsole.WriteLine(7);');const [b]=d.setBreakpoints(uri,[{line:3,column:2}]);assert.equal(b.line,2);assert.equal(b.endLine,4);assert.match(b.message,/containing/);d.start(false);assert.equal(d.runUntilStop().point.line,2);assert.equal(d.vm.output.join(''),'');});
 test(`0.9 ${name} closing brace never binds next method`,()=>{const d=create(Session,'class P {\nstatic void A(){\nConsole.WriteLine(1);\n}\nstatic void Main(){\nConsole.WriteLine(2);\n}\n}');const [b]=d.setBreakpoints(uri,[{line:4}]);assert.equal(b.verified,false);assert.match(b.message,/containing method/);d.start(false);assert.equal(d.runUntilStop().state,'terminated');});
 test(`0.9 ${name} explicit columns select statements sharing a line`,()=>{const source='int x=1; x=2; Console.WriteLine(x);',d=create(Session,source),index=source.indexOf('x=2')+1;const b=d.setBreakpoints(uri,[{line:1,column:index}])[0];assert.equal(b.column,index);assert.equal(b.locations.length,1);d.start(false);const s=d.runUntilStop();assert.equal(s.point.column,index);assert.equal(d.evaluate('x').result,'1');});
 test(`0.9 ${name} line breakpoint describes all same-line statement sites`,()=>{const d=create(Session,'int x=1; x=2; Console.WriteLine(x);'),b=d.setBreakpoints(uri,[{line:1}])[0];assert.equal(b.locations.length,3);d.start(false);d.runUntilStop();assert.equal(stops(d).length,3);});
 test(`0.9 ${name} false conditions still count every encounter`,()=>{const d=create(Session,loop);d.setBreakpoints(uri,[{line:3,condition:'i == 3'}]);d.start(false);assert.equal(d.runUntilStop().point.line,3);assert.equal(d.breakpoints[0].hits,4);assert.equal(d.evaluate('i').result,'3');run(d);assert.equal(d.breakpoints[0].hits,5);});
 test(`0.9 ${name} when-changed seeds then stops on changed values`,()=>{const d=create(Session,loop);d.setBreakpoints(uri,[{line:3,condition:'i / 2',conditionMode:'whenChanged'}]);d.start(false);d.runUntilStop();const list=stops(d);assert.deepEqual(list.map(s=>s.locals.find(v=>v.name==='i').value),['2','4']);assert.equal(d.breakpoints[0].hits,5);});
 test(`0.9 ${name} when-changed evaluates before hit filtering`,()=>{const d=create(Session,loop);d.setBreakpoints(uri,[{line:3,condition:'i',conditionMode:'whenChanged',hitCondition:'%2'}]);d.start(false);d.runUntilStop();assert.deepEqual(stops(d).map(s=>s.locals.find(v=>v.name==='i').value),['1','3']);});
 test(`0.9 ${name} one-shot preserves count and disables itself`,()=>{const d=create(Session,loop);d.setBreakpoints(uri,[{line:3,oneShot:true,hitCondition:'2'}]);d.start(false);d.runUntilStop();assert.equal(d.breakpoints[0].hits,2);assert.equal(d.breakpoints[0].enabled,false);assert.equal(run(d).state,'terminated');assert.equal(d.breakpoints[0].hits,2);});
 test(`0.9 ${name} all co-located rules count with logpoints`,()=>{const d=create(Session,loop);const bs=d.setBreakpoints(uri,[{line:3,logMessage:'{{i}}={i}'},{line:3,condition:'i==1'},{line:3,condition:'i==1'}]);d.start(false);const s=d.runUntilStop();assert.deepEqual(s.reason.hitBreakpointIds,[bs[1].id,bs[2].id]);assert.equal(d.vm.output.join(''),'{i}=0\n0\n{i}=1\n');assert.deepEqual(s.breakpoints.map(b=>b.hits),[2,2,2]);});
 test(`0.9 ${name} bad condition reports stop with exact breakpoint identity`,()=>{const d=create(Session,loop),[b]=d.setBreakpoints(uri,[{line:3,condition:'i'}]);d.start(false);const s=d.runUntilStop();assert.equal(s.reason.breakpointId,b.id);assert.equal(s.point.line,3);assert.match(s.reason.description,/bool/i);});
 test(`0.9 ${name} live configuration retains counts unless rule changes`,()=>{const d=create(Session,loop);const [b]=d.setBreakpoints(uri,[{line:3}]);d.start(false);d.runUntilStop();let [updated]=d.setBreakpoints(uri,[{line:3,enabled:false}]);assert.equal(updated.id,b.id);assert.equal(updated.hits,1);[updated]=d.setBreakpoints(uri,[{line:3}]);assert.equal(updated.hits,1);[updated]=d.setBreakpoints(uri,[{line:3,hitCondition:'3'}]);assert.equal(updated.id,b.id);assert.equal(updated.hits,0);run(d);assert.equal(d.evaluate('i').result,'3');});
 test(`0.9 ${name} mute preserves disabled rules and does not count muted encounters`,()=>{const d=create(Session,loop);d.setBreakpoints(uri,[{line:3},{line:1,enabled:false}]);d.start(false);d.runUntilStop();d.setBreakpointsEnabled(false);run(d);assert.equal(d.breakpoints[0].hits,1);assert.equal(d.breakpoints[1].enabled,false);assert.equal(d.breakpoints[1].hits,0);d.setBreakpointsEnabled(true);assert.equal(d.breakpoints[1].enabled,false);});
 test(`0.9 ${name} function rules bind parameter signature and overload`,()=>{const d=create(Session,'class P {static int F(int n){return n;}static double F(double n){return n;}static void Main(){Console.WriteLine(F(2));Console.WriteLine(F(3.0));}}');const [b]=d.setFunctionBreakpoints([{name:'P.F(int)',condition:'n==2'}]);assert(b.verified,b.message);d.start(false);const s=d.runUntilStop();assert.equal(s.reason.reason,'function breakpoint');assert.equal(d.evaluate('n').result,'2');assert.equal(s.functionBreakpoints[0].hits,1);assert.equal(run(d).state,'terminated');});
 test(`0.9 ${name} function breakpoint fires only at entry, not loop-back`,()=>{const d=create(Session,'class P{static void F(int n){while(n>0){n--;}}static void Main(){F(3);F(2);}}');d.setFunctionBreakpoints([{name:'P.F'}]);d.start(false);d.runUntilStop();assert.equal(stops(d).length,2);assert.equal(d.functionBreakpoints[0].hits,2);});
 test(`0.9 ${name} reverse continue restores an actual changed-condition stop`,()=>{const d=create(Session,loop);d.setBreakpoints(uri,[{line:3,condition:'i',conditionMode:'whenChanged'}]);d.start(false);d.runUntilStop();assert.equal(d.evaluate('i').result,'1');run(d);assert.equal(d.evaluate('i').result,'2');d.reverseContinue();assert.equal(d.evaluate('i').result,'1');assert.equal(d.breakpoints[0].hits,2);run(d);assert.equal(d.evaluate('i').result,'2');assert.equal(d.breakpoints[0].hits,3);});
 test(`0.9 ${name} reverse restores one-shot auto-consumption`,()=>{const d=create(Session,loop);d.setBreakpoints(uri,[{line:3,oneShot:true}]);d.start(false);d.runUntilStop();run(d);d.reverseContinue();assert.equal(d.reason.reason,'breakpoint');assert.equal(d.breakpoints[0].enabled,false);d.stepBack();assert.equal(d.breakpoints[0].enabled,true);});
 test(`0.9 ${name} per-type caught exception override and reverse checkpoint`,()=>{const d=create(Session,'try{\nthrow new Exception("x");\n}catch(Exception e){\nConsole.WriteLine(e.Message);\n}');d.setExceptionBreakpoints({mode:'none',rules:[{name:'System.Exception',mode:'all'}]});d.start(false);const s=d.runUntilStop();assert.equal(s.reason.reason,'exception');assert.equal(s.point.line,2);assert(d.vm.pendingFault instanceof ManagedFault);run(d);assert.equal(d.vm.output.join(''),'x\n');d.reverseContinue();assert.equal(d.reason.reason,'exception');assert(d.vm.pendingFault instanceof ManagedFault);assert.equal(d.state().point.line,2);run(d);assert.equal(d.vm.output.join(''),'x\n');});
 test(`0.9 ${name} uncaught default does not stop caught exceptions`,()=>{const d=create(Session,'try{throw new Exception("x");}catch(Exception e){Console.WriteLine(e.Message);}');d.setExceptionBreakpoints({mode:'uncaught'});d.start(false);assert.equal(d.runUntilStop().state,'terminated');});
 test(`0.9 ${name} exception Never override preserves actual failure`,()=>{const d=create(Session,'throw new Exception("x");');d.setExceptionBreakpoints({mode:'all',rules:[{name:'Exception',mode:'none'}]});d.start(false);assert.equal(d.runUntilStop().state,'faulted');assert.equal(d.state().fault.message,'x');});
 test(`0.9 ${name} returned-call assignment data breakpoint highlights caller`,()=>{const source='int F(){\n return 42;\n}\nint x=0;\nx=F();\nConsole.WriteLine(x);',d=create(Session,source);d.setBreakpoints(uri,[{line:5}]);d.start(false);d.runUntilStop();const info=d.dataBreakpointInfo({name:'x'});assert(info.dataId);assert(d.setDataBreakpoints([{dataId:info.dataId}])[0].verified);const s=run(d);assert.equal(s.reason.reason,'data breakpoint');assert.equal(s.reason.phase,'after');assert.equal(s.point.line,5);assert.equal(s.frames[0].line,5);assert.equal(d.evaluate('x').result,'42');assert.equal(d.vm.output.join(''),'');run(d);assert.equal(d.vm.output.join(''),'42\n');d.reverseContinue();assert.equal(d.reason.reason,'data breakpoint');assert.equal(d.evaluate('x').result,'42');assert.equal(d.state().point.line,5);});
 test(`0.9 ${name} data stop does not skip next source breakpoint`,()=>{const d=create(Session,'int x=0;\nx=42;\nConsole.WriteLine(x);');d.setBreakpoints(uri,[{line:2},{line:3}]);d.start(false);d.runUntilStop();d.setDataBreakpoints([{dataId:d.dataBreakpointInfo({name:'x'}).dataId}]);assert.equal(run(d).reason.reason,'data breakpoint');assert.equal(run(d).point.line,3);assert.equal(d.breakpoints.find(b=>b.requestedLine===3).hits,1);});
 test(`0.9 ${name} caller stack retains call-site while callee executes`,()=>{const d=create(Session,'int F(){\n return 42;\n}\nint x=F();\nConsole.WriteLine(x);');d.setBreakpoints(uri,[{line:2}]);d.start(false);d.runUntilStop();const fs=d.stackTrace();assert.equal(fs[0].line,2);assert.equal(fs[1].line,4);assert.equal(d.state().point.line,2);assert.equal(fs[0].isCurrent,true);assert.equal(fs[1].isCurrent,false);});
 test(`0.9 ${name} invalid breakpoint metadata is unverified, never silently executable`,()=>{const d=create(Session,'Console.WriteLine(1);');for(const request of [{line:0},{line:1,column:0},{line:999},{line:1,condition:'('},{line:1,conditionMode:'random'},{line:1,hitCondition:'0'},{line:1,hitCondition:'9007199254740999'},{line:1,oneShot:'yes'}])assert.equal(d.setBreakpoints(uri,[request])[0].verified,false,JSON.stringify(request));assert.equal(d.setBreakpoints('other/Program.cs',[{line:1}])[0].verified,false);});
 test(`0.9 ${name} cleanup hidden sequence does not double-hit using acquisition`,()=>{const d=create(Session,'using(var r=new R())\n{\nConsole.WriteLine(42);\n}\nclass R:IDisposable{public void Dispose(){Console.WriteLine("disposed");}}');d.setBreakpoints(uri,[{line:2}]);d.start(false);d.runUntilStop();assert.equal(stops(d).length,1);assert.equal(d.vm.output.join(''),'42\ndisposed\n');});
 test(`0.9 ${name} expression/hit/function options roundtrip with no internal seed leaks`,()=>{const d=create(Session,loop);d.setBreakpoints(uri,[{line:3,condition:'i',conditionMode:'whenChanged'}]);d.start(false);d.runUntilStop();const public_=d.state().breakpoints[0];assert.equal('conditionValue'in public_,false);assert.equal('conditionSeeded'in public_,false);assert.equal(public_.conditionMode,'whenChanged');});
}
test('0.9 source header spans do not swallow blank lines within control blocks',()=>{const r=compile('int x=0;\nif(x==0)\n{\n// body comment\nConsole.WriteLine(x);\n}'),index=new SourceBreakpointIndex(r.image);assert.equal(index.resolve(uri,{line:4}).point.line,5);});
test('0.9 source pause immediately before an unvisited SEQ must not skip its breakpoint',()=>{const d=create(DebugSession,'int x=1;\nConsole.WriteLine(x);');d.setBreakpoints(uri,[{line:2}]);d.start(false);const target=d.vm.image.sequencePoints.find(p=>p.line===2);while(d.vm.top?.point?.id!==target.id&&!(d.vm.top?.methodId===target.methodId&&d.vm.top.pc===target.offset))d.pump({instructionBudget:1,timeBudgetMs:1000});assert.equal(d.vm.sourcePause,false);d.pause();assert.equal(run(d).reason.reason,'breakpoint');assert.equal(d.breakpoints[0].hits,1);});
test('0.9 run-to-cursor from ready binds multiline and clears temporary target',()=>{const d=create(DebugSession,'int x=42;\nConsole.WriteLine(\n x\n);');assert.deepEqual(d.runToCursor(uri,3,2),{uri,line:2,column:1});const s=d.runUntilStop();assert.equal(s.reason.reason,'goto');assert.equal(s.point.line,2);assert.equal(d.breakpoints.length,0);assert.equal(d.temporaryPoint,null);});
test('0.9 run-to-cursor interrupted by breakpoint is cancelled',()=>{const d=create(DebugSession,loop+'Console.WriteLine(99);');d.setBreakpoints(uri,[{line:3,oneShot:true}]);d.runToCursor(uri,5);d.runUntilStop();assert.equal(d.reason.reason,'breakpoint');assert.equal(d.temporaryPoint,null);});
test('0.9 source VM refuses other snapshots and restores fault graph aliases',()=>{const a=create(DebugSession,'try{throw new Exception("x");}catch(Exception e){Console.WriteLine(e.Message);}'),b=create(DebugSession,'Console.WriteLine(1);');a.setExceptionBreakpoints({mode:'all'});a.start(false);a.runUntilStop();const s=a.vm.snapshot();assert.throws(()=>b.vm.restore(s),/another/);run(a);a.vm.restore(s);assert(a.vm.pendingFault instanceof ManagedFault);run(a);assert.equal(a.vm.output.join(''),'x\n');});
test('0.9 source stepping over accessor is optional but explicit property breakpoints still hit',()=>{const source='var c=new C();\nConsole.WriteLine(c.X);\nclass C{public int X{get{return 42;}}}',d=create(DebugSession,source,{stepOverProperties:true});d.setBreakpoints(uri,[{line:3}]);d.start(false);d.runUntilStop();run(d,'stepIn');assert.equal(d.vm.state,'terminated');const e=create(DebugSession,source,{stepOverProperties:true});e.setFunctionBreakpoints([{name:'C.get_X'}]);e.start(false);assert.equal(e.runUntilStop().reason.reason,'function breakpoint');});
test('0.9 source frames use monotonic IDs after reverse',()=>{const d=create(DebugSession,'int F(){return 42;}\nConsole.WriteLine(F());');d.setFunctionBreakpoints([{name:'F'}]);d.start(false);d.runUntilStop();const id=d.vm.top.id;d.stepBack();run(d);assert(d.vm.top.id>id);});
test('0.9 instruction breakpoints maintain ID and hits during live update',()=>{const d=new CilDebugSession(arithmeticLibrary(),{methodToken:'Add',arguments:[20,22]});const r=instructionReference(0x06000001,1),[b]=d.setInstructionBreakpoints([{instructionReference:r}]);d.start(false);d.runUntilStop();const [next]=d.setInstructionBreakpoints([{instructionReference:r}]);assert.equal(next.id,b.id);assert.equal(next.hits,1);});
test('0.9 UTF-16 and CRLF sequence ranges survive canonical assembly reload',()=>{const r=compile('// 😀\r\nint x=42;\r\nConsole.WriteLine(\r\n x\r\n);');for(const image of [r.image,loadAssembly(r.assembly)]){const b=new SourceBreakpointIndex(image).resolve(uri,{line:4,column:2});assert.equal(b.point.line,3);assert.equal(b.point.endLine,5);assert.equal(image.sources[0].text.slice(b.point.start,b.point.end),'Console.WriteLine(\r\n x\r\n);');}});
