import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';
import {compileToIL} from '@sharpforge/compiler';import {VirtualMachine,CilVirtualMachine} from '@sharpforge/runtime';import {loadAssembly,formatILDocument,assembleILDocument} from '@sharpforge/cil';import {parseJsonTree} from '../packages/runtime/src/json.js';
const prefix='using System;using System.Collections.Generic;using System.Text.Json;using System.Numerics;using System.Threading;using System.Threading.Tasks;using System.Net.Http;using System.Net;using SharpForge.Runtime;';
const paths={source:(c,o)=>new VirtualMachine(c.image,o),reload:(c,o)=>new VirtualMachine(loadAssembly(c.assembly),o),cil:(c,o)=>new CilVirtualMachine(c.assembly,o),reassembled:(c,o)=>new CilVirtualMachine(assembleILDocument(formatILDocument(c.assembly)).bytes,o)};
const cases=[
 ['empty collections serialize without allocating storage','Console.WriteLine(JsonSerializer.Serialize(new List<int>()));Console.WriteLine(JsonSerializer.Serialize(new Queue<string>()));Console.WriteLine(JsonSerializer.Serialize(new Dictionary<string,int>()));','[]\n[]\n{}\n'],
 ['relative request URI properties','var request=new HttpRequestMessage(HttpMethod.Get,"child");Console.WriteLine(request.RequestUri.OriginalString);Console.WriteLine(request.RequestUri.ToString());Console.WriteLine(request.RequestUri.IsAbsoluteUri);try{Console.WriteLine(request.RequestUri.AbsolutePath);}catch(Exception e){Console.WriteLine("relative");}','child\nchild\nFalse\nrelative\n'],
 ['Array null validation keeps destination unchanged','int[] missing=null;int[] a=[1,2];try{Array.Copy(missing,a,1);}catch(Exception e){Console.WriteLine("source");}try{Array.Copy(a,missing,1);}catch(Exception e){Console.WriteLine("destination");}Console.WriteLine(string.Join(",",a));','source\ndestination\n1,2\n'],

 ['Array overlap copy','int[] a=[1,2,3,4];Array.Copy(a,0,a,1,3);Console.WriteLine(string.Join(",",a));Array.Copy(a,1,a,0,3);Console.WriteLine(string.Join(",",a));','1,1,2,3\n1,2,3,3\n'],
 ['Array Fill Clear IndexOf BinarySearch','int[] a=[1,2,3,4];Array.Fill(a,8,1,2);Console.WriteLine(string.Join(",",a));Array.Clear(a,0,2);Console.WriteLine(string.Join(",",a));Console.WriteLine(Array.IndexOf(a,8));Console.WriteLine(Array.LastIndexOf(a,0));Console.WriteLine(Array.BinarySearch(new int[]{1,3,5},4));','1,8,8,4\n0,0,8,4\n2\n1\n-3\n'],
 ['Array invalid range transactional','int[] a=[1,2,3];try{Array.Copy(a,0,a,1,9);}catch(Exception e){Console.WriteLine("bounds");}try{Array.Fill(a,8,-1,1);}catch(Exception e){Console.WriteLine("bounds");}Console.WriteLine(string.Join(",",a));','bounds\nbounds\n1,2,3\n'],
 ['Array reference roots and defaults','string[] a=["a","b","c"];Array.Copy(a,0,a,1,2);GC.Collect();Console.WriteLine(a[2]);Array.Clear(a,0,3);Console.WriteLine(a[0]==null);bool[] b=[true,true];Array.Clear(b,0,1);Console.WriteLine(b[0]);','b\nTrue\nFalse\n'],
 ['Random seeded reference values','var r=new Random(1);Console.WriteLine(r.Next());Console.WriteLine(r.Next());Console.WriteLine(r.Next());','534011718\n237820880\n1002897798\n'],
 ['Random bounds and deterministic same seeds','var a=new Random(42);var b=new Random(42);for(int i=0;i<10;i++){if(a.Next()!=b.Next())throw new Exception("bad");}Console.WriteLine(a.Next(0));Console.WriteLine(a.Next(42,42));try{a.Next(-1);}catch(Exception e){Console.WriteLine("range");}Console.WriteLine(Random.Shared!=null);','0\n42\nrange\nTrue\n'],
 ['queue wrap, growth, clear and enumeration','var q=new Queue<int>(4);for(int i=0;i<4;i++)q.Enqueue(i);q.Dequeue();q.Dequeue();for(int i=4;i<10;i++)q.Enqueue(i);Console.WriteLine(string.Join(",",q.ToArray()));foreach(var n in q)Console.WriteLine(n);q.Clear();q.Enqueue(42);Console.WriteLine(q.Dequeue());','2,3,4,5,6,7,8,9\n2\n3\n4\n5\n6\n7\n8\n9\n42\n'],
 ['dictionary maintained index replacements remove GC','var d=new Dictionary<string,int>();for(int i=0;i<100;i++)d[$"k{i}"]=i;d["k42"]=142;d.Remove("k1");d["k1"]=201;GC.Collect();Console.WriteLine(d["k42"]);Console.WriteLine(d["k1"]);Console.WriteLine(d.Count);','142\n201\n100\n'],
 ['vector arithmetic immutable value and lane indexing','Vector<int> a=new(2);var b=a+new Vector<int>(3);Console.WriteLine(Vector.Sum(b));Console.WriteLine(a[0]);Console.WriteLine(a==new Vector<int>(2));Console.WriteLine(b!=a);Console.WriteLine(Vector.Dot(a,b));','20\n2\nTrue\nTrue\n40\n'],
 ['vector double and CopyTo offset','var a=new Vector<double>(new double[]{3.0,4.0});var b=new Vector<double>(2.0);Console.WriteLine(Vector.Sum(a*b));double[] c=[0.0,0.0,0.0];a.CopyTo(c,1);Console.WriteLine(c[1]);Console.WriteLine(c[2]);Console.WriteLine(Vector<double>.Count);','14\n3\n4\n2\n'],
 ['vector overflow and invalid lanes','var a=new Vector<int>(2147483647);Console.WriteLine((a+Vector<int>.One)[0]);try{var v=new Vector<int>(new int[]{1});}catch(Exception e){Console.WriteLine("short");}try{Console.WriteLine(a[4]);}catch(Exception e){Console.WriteLine("range");}','-2147483648\nshort\nrange\n'],
 ['JSON property raw spans and duplicate last wins',String.raw`using var d=JsonDocument.Parse(" { \"a\" : 1, \"a\" : 42, \"s\" : \"hello\", \"n\": null }");Console.WriteLine(d.RootElement.GetProperty("a").GetInt32());Console.WriteLine(d.RootElement.GetProperty("s").GetString());Console.WriteLine(d.RootElement.GetProperty("s").GetRawText());Console.WriteLine(d.RootElement.GetProperty("n").GetString()==null);`,'42\nhello\n"hello"\nTrue\n'],
 ['JSON array object enumeration',String.raw`var d=JsonDocument.Parse("{\"a\":[1,2],\"b\":true}");foreach(var p in d.RootElement.EnumerateObject()){Console.WriteLine(p.Name);}foreach(var e in d.RootElement.GetProperty("a").EnumerateArray())Console.WriteLine(e.GetInt32());Console.WriteLine(d.RootElement.GetProperty("b").GetBoolean());`,'a\nb\n1\n2\nTrue\n'],
 ['JSON index getters and wrong kinds',String.raw`var d=JsonDocument.Parse("[1.5,2,\"s\"]");Console.WriteLine(d.RootElement.GetArrayLength());Console.WriteLine(d.RootElement[0].GetDouble());try{d.RootElement[0].GetInt32();}catch(Exception e){Console.WriteLine("format");}try{d.RootElement[1].GetString();}catch(Exception e){Console.WriteLine("kind");}try{d.RootElement[9].GetDouble();}catch(Exception e){Console.WriteLine("index");}`,'3\n1.5\nformat\nkind\nindex\n'],
 ['JSON elements root document and invalidate after disposal',String.raw`var d=JsonDocument.Parse("{\"n\":42}");var e=d.RootElement.GetProperty("n");GC.Collect();Console.WriteLine(e.GetInt32());d.Dispose();try{e.GetInt32();}catch(Exception x){Console.WriteLine("disposed");}`,'42\ndisposed\n'],
 ['JSON serializer arrays and registered collections',String.raw`Console.WriteLine(JsonSerializer.Serialize(new int[]{1,2}));Console.WriteLine(JsonSerializer.Serialize(new List<string>(){"a","b"}));Console.WriteLine(JsonSerializer.Serialize(new Dictionary<string,int>(){{"x",42}}));Console.WriteLine(JsonSerializer.Serialize(null));`,'[1,2]\n["a","b"]\n{"x":42}\nnull\n'],
 ['Uri base address and escaping','var u=new Uri(new Uri("https://example.com/root/"),"child?q=1");Console.WriteLine(u.Host);Console.WriteLine(u.AbsolutePath);Console.WriteLine(u.Port);Console.WriteLine(Uri.EscapeDataString("a b"));Console.WriteLine(Uri.UnescapeDataString("a%20b"));','example.com\n/root/child\n443\na%20b\na b\n'],
 ['Cancellation tokens managed state','using var c=new CancellationTokenSource();var t=c.Token;Console.WriteLine(t.CanBeCanceled);Console.WriteLine(t.IsCancellationRequested);c.Cancel();Console.WriteLine(t.IsCancellationRequested);try{t.ThrowIfCancellationRequested();}catch(Exception e){Console.WriteLine("canceled");}Console.WriteLine(CancellationToken.None.CanBeCanceled);','True\nFalse\nTrue\ncanceled\nFalse\n'],
 ['parallel sum dot and array output','class P{static async Task Main(){double[] a=[1.0,2.0,3.0];double[] b=[4.0,5.0,6.0];Console.WriteLine(await ParallelMath.SumAsync(a));Console.WriteLine(await ParallelMath.DotAsync(a,b));var c=await ParallelMath.AddAsync(a,b);Console.WriteLine(c[2]);GC.Collect();}}','6\n32\n9\n']
];
for(const[name,src,expected]of cases){const c=compileToIL(prefix+src);for(const[path,make]of Object.entries(paths))test(`runtime14 ${path}: ${name}`,async()=>{assert(c.success,JSON.stringify(c.diagnostics));const vm=make(c,{initialThreshold:64,compute:{workers:2}});try{const r=await vm.runAsync();assert.equal(r.state,'terminated',JSON.stringify(r.fault));assert.equal(r.output,expected);}finally{vm.stop();}});}
for(const text of ['', 'true false','[1,]','{"a":1,}','{a:1}','01','NaN','"\n"','"\\q"','[','1e','-','.5'])test('JSON parser rejects '+JSON.stringify(text),()=>assert.throws(()=>parseJsonTree(text)));
test('JSON parser limits and exact escaped raw ranges',()=>{assert.throws(()=>parseJsonTree('['.repeat(130)+'0'+']'.repeat(130)),/depth/);assert.throws(()=>parseJsonTree(' '.repeat(1000001)),/limit/);const p=parseJsonTree(' {"a":"\\u0061"} ');const s=p.nodes.at(-1);assert.equal(s.value,'a');assert.equal(p.text.slice(s.start,s.end),'"\\u0061"');});
for(const[path,make]of Object.entries(paths))test('managed HTTP '+path+' real requests errors disposal cancellation and async GC',async(t)=>{
 const requests=[];const server=http.createServer(async(q,r)=>{try{requests.push(q.url);if(q.url==='/slow')await new Promise(r=>setTimeout(r,50));if(q.url==='/bad'){r.writeHead(404);r.end('bad');return;}if(q.url==='/big'){r.end('x'.repeat(400));return;}if(q.method==='POST'){let s='';for await(const chunk of q)s+=chunk;r.end(s);return;}r.setHeader('x-number','42');r.end('{"answer":42}');}catch{}});server.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const origin='http://127.0.0.1:'+server.address().port;t.after(()=>new Promise(r=>{server.close(r);server.closeAllConnections();}));
 const c=compileToIL(prefix+`class P{static async Task Main(){using var c=new HttpClient();c.BaseAddress=new Uri("${origin}/");c.DefaultRequestHeaders.Add("X-Test","value");var text=await c.GetStringAsync("ok");using var d=JsonDocument.Parse(text);Console.WriteLine(d.RootElement.GetProperty("answer").GetInt32());using var r=await c.PostAsync("post",new StringContent("echo"));Console.WriteLine(r.StatusCode==HttpStatusCode.OK);Console.WriteLine(await r.Content.ReadAsStringAsync());try{await c.GetStringAsync("bad");}catch(Exception e){Console.WriteLine("status");}try{await c.GetStringAsync("big");}catch(Exception e){Console.WriteLine("limit");}using var token=new CancellationTokenSource();var pending=c.GetStringAsync("slow",token.Token);token.Cancel();GC.Collect();try{await pending;}catch(Exception e){Console.WriteLine("cancel");}c.Timeout=TimeSpan.FromMilliseconds(1.0);try{await c.GetStringAsync("slow");}catch(Exception e){Console.WriteLine("timeout");}c.Dispose();try{c.GetAsync("ok");}catch(Exception e){Console.WriteLine("disposed");}}}`);
 assert(c.success,JSON.stringify(c.diagnostics));const vm=make(c,{initialThreshold:64,network:{allowedOrigins:[origin],maxResponseBytes:128}});try{const r=await vm.runAsync();assert.equal(r.state,'terminated',JSON.stringify(r.fault));assert.equal(r.output,'42\nTrue\necho\nstatus\nlimit\ncancel\ntimeout\ndisposed\n');}finally{vm.stop();}
});
for(const[path,make]of Object.entries(paths))test('host epoch snapshot barriers '+path,async()=>{
 const c=compileToIL(prefix+'class P{static async Task Main(){Console.WriteLine(await ParallelMath.SumAsync(new double[]{1.0,2.0}));}}');assert(c.success);const vm=make(c);const before=vm.snapshot();try{vm.runSlice({instructionBudget:10000,timeBudgetMs:100});assert.equal(vm.platform.hostOperations.active.size,1);assert.throws(()=>vm.snapshot(),/pending external/);await vm.runAsync();const output=[...vm.output];assert.throws(()=>vm.restore(before),/Cannot reverse/);assert.deepEqual(vm.output,output);const fresh=vm.snapshot();vm.restore(fresh);}finally{vm.stop();}
});
for(const[path,make]of Object.entries(paths))test('network permission default deny '+path,async()=>{const c=compileToIL(prefix+'class P{static async Task Main(){var c=new HttpClient();try{await c.GetStringAsync("https://example.com/");}catch(Exception e){Console.WriteLine("denied");}}}');assert(c.success);const vm=make(c);try{const r=await vm.runAsync();assert.equal(r.output,'denied\n');assert.equal(vm.platform.httpTransport.stats.requests,0);}finally{vm.stop();}});
