import test from 'node:test';import assert from 'node:assert/strict';
import {compileToIL} from '@sharpforge/compiler';import {VirtualMachine,CilVirtualMachine} from '@sharpforge/runtime';import {loadAssembly,formatILDocument,assembleILDocument} from '@sharpforge/cil';
const prefix='using Microsoft.UI.Xaml;using Microsoft.UI.Xaml.Controls;using Microsoft.UI.Xaml.Media;';
const paths={source:c=>new VirtualMachine(c.image,{initialThreshold:64}),canonical:c=>new VirtualMachine(loadAssembly(c.assembly),{initialThreshold:64}),cil:c=>new CilVirtualMachine(c.assembly,{initialThreshold:64}),reassembled:c=>new CilVirtualMachine(assembleILDocument(formatILDocument(c.assembly)).bytes,{initialThreshold:64})};
const cases=[
 ['local template-part values override bindings until cleared',`ControlTemplate t=new ControlTemplate(){TargetTypeName="TextBox"};TextBox prototype=new TextBox(){Name="PART_Input",Text="prototype"};t.VisualTree=prototype;t.Bind(prototype,"Text",TextBox.TextProperty);TextBox b=new TextBox(){Text="owner",Template=t};DependencyObject part=b.GetTemplateChild("PART_Input");Console.WriteLine(part.ReadLocalValue(TextBox.TextProperty)==DependencyProperty.UnsetValue);part.SetValue(TextBox.TextProperty,"local");b.Text="changed";Console.WriteLine(part.GetValue(TextBox.TextProperty));part.ClearValue(TextBox.TextProperty);Console.WriteLine(part.GetValue(TextBox.TextProperty));`,'True\nlocal\nchanged\n'],
 ['clearing Style removes its effective property values',`Style s=new Style("Button");s.Setters.Add(new Setter(Button.FontSizeProperty,32.0));Button b=new Button(){Style=s};b.ClearValue(FrameworkElement.StyleProperty);Console.WriteLine(b.FontSize);Console.WriteLine(b.Style==null);`,'14\nTrue\n'],

 ['default, style, local, ClearValue precedence',`Style s=new Style("Button");s.Setters.Add(new Setter(Button.WidthProperty,120.0));Button b=new Button();b.Style=s;Console.WriteLine(b.Width);b.Width=180;Console.WriteLine(b.Width);b.ClearValue(Button.WidthProperty);Console.WriteLine(b.Width);`,'120\n180\n120\n'],
 ['registered dependency property identity survives garbage collection',`DependencyProperty p=Button.WidthProperty;GC.Collect();Console.WriteLine(p==Button.WidthProperty);Console.WriteLine(p==FrameworkElement.WidthProperty);`,'True\nTrue\n'],
 ['ReadLocalValue distinguishes UnsetValue from a local null',`TextBox b=new TextBox();Console.WriteLine(b.ReadLocalValue(TextBox.TextProperty)==DependencyProperty.UnsetValue);b.Text=null;Console.WriteLine(b.ReadLocalValue(TextBox.TextProperty)==null);b.ClearValue(TextBox.TextProperty);GC.Collect();Console.WriteLine(b.ReadLocalValue(TextBox.TextProperty)==DependencyProperty.UnsetValue);`,'True\nTrue\nTrue\n'],
 ['BasedOn and shared mutable setter changes affect both consumers',`Style baseStyle=new Style("Button");baseStyle.Setters.Add(new Setter(Button.WidthProperty,150.0));Setter size=new Setter(Button.FontSizeProperty,21.0);Style s=new Style("Button");s.BasedOn=baseStyle;s.Setters.Add(size);Button a=new Button(){Style=s};Button b=new Button(){Style=s,FontSize=30};size.Value=25.0;Console.WriteLine(a.FontSize);Console.WriteLine(b.FontSize);Console.WriteLine(a.Width);b.ClearValue(Button.FontSizeProperty);Console.WriteLine(b.FontSize);`,'25\n30\n150\n25\n'],
 ['invalid shared setter mutation rolls back all managed consumers',`Style s=new Style("Button");Setter v=new Setter(Button.WidthProperty,123.0);s.Setters.Add(v);Button a=new Button(){Style=s};Button b=new Button(){Style=s};try{v.Value="invalid";}catch(Exception e){Console.WriteLine(1);}Console.WriteLine(a.Width);Console.WriteLine(b.Width);v.Value=140.0;Console.WriteLine(b.Width);`,'1\n123\n123\n140\n'],
 ['invalid setter collection insertion leaves the collection unchanged',`Style s=new Style("Button");s.Setters.Add(new Setter(Button.WidthProperty,123.0));Button b=new Button(){Style=s};try{s.Setters.Add(new Setter(Button.WidthProperty,"invalid"));}catch(Exception e){Console.WriteLine(1);}Console.WriteLine(s.Setters.Count);Console.WriteLine(b.Width);`,'1\n1\n123\n'],
 ['incorrect target style assignment is transactional',`Style good=new Style("Button");good.Setters.Add(new Setter(Button.WidthProperty,99.0));Button b=new Button(){Style=good};try{b.Style=new Style("TextBox");}catch(Exception e){Console.WriteLine(1);}Console.WriteLine(b.Style==good);Console.WriteLine(b.Width);`,'1\nTrue\n99\n'],
 ['SetValue uses the real property setter and enforces runtime types',`Button b=new Button();b.SetValue(Button.WidthProperty,142.0);Console.WriteLine(b.Width);try{b.SetValue(Button.WidthProperty,"bad");}catch(Exception e){Console.WriteLine(1);}Console.WriteLine(b.Width);`,'142\n1\n142\n'],
 ['style Thickness value objects survive boxed CIL and collection',`Style s=new Style("Button");s.Setters.Add(new Setter(Button.PaddingProperty,new Thickness(12)));Button b=new Button(){Style=s};GC.Collect();Console.WriteLine(b.Padding.Left);b.ClearValue(Button.PaddingProperty);Console.WriteLine(b.Padding.Right);`,'12\n12\n'],
 ['each template owner has distinct name-scoped visual parts',`ControlTemplate t=new ControlTemplate(){TargetTypeName="TextBox"};TextBox part=new TextBox(){Name="PART_Input"};t.VisualTree=part;t.Bind(part,"Text",TextBox.TextProperty);TextBox a=new TextBox(){Template=t,Text="A"};TextBox b=new TextBox(){Template=t,Text="B"};Console.WriteLine(a.ApplyTemplate());Console.WriteLine(a.GetTemplateChild("PART_Input")==b.GetTemplateChild("PART_Input"));GC.Collect();Console.WriteLine(a.GetTemplateChild("PART_Input")!=null);`,'True\nFalse\nTrue\n'],
 ['invalid template names and targets preserve the previous instance',`ControlTemplate good=new ControlTemplate(){TargetTypeName="Button",VisualTree=new Border(){Name="PART_Root"}};Button b=new Button(){Template=good};ControlTemplate wrong=new ControlTemplate(){TargetTypeName="TextBox",VisualTree=new TextBox()};try{b.Template=wrong;}catch(Exception e){Console.WriteLine(1);}Console.WriteLine(b.Template==good);Console.WriteLine(b.GetTemplateChild("PART_Root")!=null);`,'1\nTrue\nTrue\n'],
 ['removing a template exposes the standard control again',`ControlTemplate t=new ControlTemplate(){VisualTree=new Border(){Name="PART_Root"}};Button b=new Button(){Template=t};Console.WriteLine(b.GetTemplateChild("PART_Root")!=null);b.ClearValue(Control.TemplateProperty);Console.WriteLine(b.GetTemplateChild("PART_Root")==null);Console.WriteLine(b.ApplyTemplate());`,'True\nTrue\nFalse\n'],
];
for(const [name,body,output]of cases){const c=compileToIL(prefix+body);for(const [kind,make]of Object.entries(paths))test(`${kind}: ${name}`,()=>{assert(c.success,JSON.stringify(c.diagnostics));const vm=make(c),r=vm.run();assert.equal(r.fault,null,JSON.stringify(r.fault));assert.equal(r.output,output);});}
