import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,rm,readdir,mkdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {spawnSync} from 'node:child_process';
import {projectTemplates,itemTemplates,createProjectPlan,createItemPlan,validateFilePlan,searchTemplates} from '@sharpforge/templates';
import {readZip,writeZip,crc32,decodeWorkspaceFile,encodeWorkspaceFile,portablePath} from '@sharpforge/archive';
import {ProjectSystem,importWorkspaceZip,exportWorkspaceZip,readBrowserFiles,readLegacySolution,convertLegacySolution,buildSolutionTree,renameSolutionFolder,removeSolutionFolder,moveSolutionProject,addSolutionItem,addSolutionProject,readDirectory,writeNewDirectory,DiskWorkspace,validateWorkspaceSettings} from '@sharpforge/project-system';
import {compileToIL} from '@sharpforge/compiler';import {VirtualMachine,CilVirtualMachine} from '@sharpforge/runtime';import {loadAssembly,formatILDocument,assembleILDocument} from '@sharpforge/cil';
import {NativeWorkspace} from '../packages/msbuild/src/workspace.js';import {writePlan} from '../apps/cli/workspace.js';
const enc=s=>new TextEncoder().encode(s),text=b=>new TextDecoder().decode(b);
const compilePlan=p=>{const system=new ProjectSystem(p.records);const snapshot=system.load(p.entry);assert(!snapshot.diagnostics.some(d=>d.severity==='error'),JSON.stringify(snapshot.diagnostics));if(!p.startup)return null;const sources=system.compilationFiles(p.startup);if(!sources.length)return null;const result=compileToIL(sources,{...system.compilationOptions(p.startup),assemblyName:p.name});assert(result.success,JSON.stringify(result.diagnostics));return result;};
const paths={source:c=>new VirtualMachine(c.image,{virtualTime:true}),canonical:c=>new VirtualMachine(loadAssembly(c.assembly),{virtualTime:true}),cil:c=>new CilVirtualMachine(c.assembly,{virtualTime:true}),reassembled:c=>new CilVirtualMachine(assembleILDocument(formatILDocument(c.assembly)).bytes,{virtualTime:true})};
for(const t of projectTemplates){
 const plan=createProjectPlan(t.id,{projectName:'TemplateApp',namespace:'Example.App',solutionName:'Suite'});
 test(`template ${t.id}: deterministic validated project XML, ZIP roundtrip and startup compilation`,()=>{assert.deepEqual(createProjectPlan(t.id,{projectName:'TemplateApp',namespace:'Example.App',solutionName:'Suite'}),plan);const restored=importWorkspaceZip(exportWorkspaceZip({records:plan.records,folders:plan.folders,settings:{name:plan.name,entry:plan.entry,startup:plan.startup,mode:'solution'}}));assert.equal(restored.settings.entry,plan.entry);assert.deepEqual(restored.records.map(r=>[r.path,r.text]).sort(),plan.records.map(r=>[r.path,r.text]).sort());assert.deepEqual(restored.folders.sort(),plan.folders.sort());compilePlan(plan);});
 if(!['blank-solution','empty-project'].includes(t.id))for(const [path,factory]of Object.entries(paths))test(`template ${t.id}: actual ${path} execution`,async()=>{let c=compilePlan(plan);const isLibrary=['class-library','winui-controls-library'].includes(t.id);if(isLibrary){assert.equal(c.image.entryPoint,null);const sys=new ProjectSystem(plan.records);sys.load(plan.entry);const body=t.id==='class-library'?'Console.WriteLine(Calculator.Add(20,22));':'CardControl c=new CardControl(); c.SetCaption(\"from library\"); Microsoft.UI.Xaml.Window w=new Microsoft.UI.Xaml.Window(); w.Content=c.View; w.Activate();';c=compileToIL([...sys.compilationFiles(plan.startup),{uri:'Host.cs',text:'using Example.App; using Microsoft.UI.Xaml; class Host { static void Main(){'+body+'}}'}]);assert(c.success,JSON.stringify(c.diagnostics));}const vm=factory(c),r=await vm.runAsync();assert.equal(r.state,'terminated',r.fault?.message);if(t.winui){assert.equal(vm.platform.scene().windows.length,1);const button=vm.platform.scene().nodes.find(n=>n.type.endsWith('.Button'));if(button){vm.platform.dispatchEvent(button.id,'Click');const after=await vm.runAsync();assert.equal(after.state,'terminated',after.fault?.message);}}else assert.match(r.output,['console-library-solution','class-library'].includes(t.id)?/42/:t.id==='test-console'?/All self-tests passed/:/Hello/);});
}
for(const t of itemTemplates)test(`item ${t.id}: legal unique files, project membership and compilation`,()=>{const project=createProjectPlan('class-library',{projectName:'Components'}),xml=project.records.find(r=>r.path.endsWith('.csproj')),item=createItemPlan(t.id,{namespace:'Components',folder:'Components/Features',projectPath:xml.path,projectText:xml.text,existing:project.records});assert(item.modifications[0].text.includes('Features/'));const files=[...project.records.map(r=>r.path===xml.path?{...r,text:item.modifications[0].text}:r),...item.records];compilePlan({...project,records:files});assert.equal(item.modifications[0].expectedText,xml.text);});
test('templates: namespace and reserved-path validation has no injection or silent renaming',()=>{for(const name of ['../bad','a/b','Foo";Console.WriteLine(1);','class','8bad'])assert.throws(()=>createItemPlan('class',{name}));for(const name of ['../../Bad','A"B','a/b','CON'])assert.throws(()=>createProjectPlan('console',{projectName:name}));assert.throws(()=>createProjectPlan('console',{namespace:'System.class'}));assert.throws(()=>createProjectPlan('not-installed'));assert.equal(searchTemplates({query:'navigation'}).length,1);assert(searchTemplates({kind:'item',category:'WinUI'}).length>6);});
test('create plan: case-insensitive destination collisions, parent files and multiple item outputs preflight',()=>{assert.throws(()=>createProjectPlan('console',{existing:[{path:'application/PROGRAM.cs'}]}));assert.throws(()=>createItemPlan('partial-class',{name:'Thing',existing:[{path:'Thing.Methods.cs'}]}));assert.throws(()=>validateFilePlan({records:[{path:'assets/a.txt',text:''}]},[{path:'ASSETS',text:'file'}]));});
test('add project keeps unrelated XML, configuration and named folder',()=>{const old='\ufeff<Solution>\r\n<!-- KEEP -->\r\n<Configurations><BuildType Name="Retail" /></Configurations>\r\n<Folder Name="/Source/" />\r\n</Solution>';const plan=createProjectPlan('console',{projectName:'App',solutionMode:'existing',solutionPath:'Repo.slnx',solutionText:old,solutionFolder:'/Source/'});assert(plan.modifications[0].text.includes('<!-- KEEP -->'));assert(plan.modifications[0].text.includes('<BuildType Name="Retail" />'));const sys=new ProjectSystem([...plan.records,{path:'Repo.slnx',text:plan.modifications[0].text}]);assert.equal(sys.load('Repo.slnx').solution.items.find(i=>i.kind==='project').folder,'/Source/');});
test('same-directory and project-only templates are genuinely different layouts',()=>{const p=createProjectPlan('console',{projectName:'Hello',sameDirectory:true,solutionMode:'none',location:'src'});assert.equal(p.entry,'src/Hello.csproj');assert(p.records.some(r=>r.path==='src/Program.cs'));assert(!p.records.some(r=>r.path.endsWith('.slnx')));compilePlan(p);});
test('blank solution displays zero projects, not a synthetic loose project',()=>{const p=createProjectPlan('blank-solution'),sys=new ProjectSystem(p.records),snapshot=sys.load(p.entry),tree=buildSolutionTree({snapshot,files:p.records});assert.match(tree[0].label,/\(0 projects\)/);assert(!tree[0].children.some(n=>n.kind==='project'));assert(tree[0].children.some(n=>n.kind==='solution-folder'));});
test('ZIP CRC known vector and deterministic empty/archive output',()=>{assert.equal(crc32(enc('123456789')),0xcbf43926);assert.deepEqual(readZip(writeZip([])),[]);assert.deepEqual(writeZip([{path:'a',text:'x'}]),writeZip([{path:'a',text:'x'}]));});
test('standard Python reader validates SharpForge ZIP CRCs, Unicode assets and explicit empty folders',()=>{const bytes=writeZip([{path:'src/Zażółć.cs',text:'\r\n// ❤\r\n'},{path:'Assets/icon.dat',bytes:Uint8Array.from([0,255,128,0,3])},{path:'Empty',directory:true}]);const py=spawnSync('python',['-c','import sys,io,zipfile,json; z=zipfile.ZipFile(io.BytesIO(sys.stdin.buffer.read())); assert z.testzip() is None; print(json.dumps({n:list(z.read(n)) for n in z.namelist()}))'],{input:bytes});assert.equal(py.status,0,py.stderr.toString());const files=JSON.parse(py.stdout);assert.deepEqual(files['Assets/icon.dat'],[0,255,128,0,3]);assert.deepEqual(files['Empty/'],[]);assert.equal(text(Uint8Array.from(files['src/Zażółć.cs'])),'\r\n// ❤\r\n');});
for(const descriptor of [false,true])test(`external Python DEFLATE ZIP${descriptor?' with data descriptors':''} imports without runtime dependencies`,()=>{const py=spawnSync('python',['-c',`import sys,io,zipfile
class Pipe(io.BytesIO):
 def seekable(self): return False
 def seek(self,*a): raise io.UnsupportedOperation()
b=${descriptor?'Pipe':'io.BytesIO'}()
with zipfile.ZipFile(b,'w',compression=zipfile.ZIP_DEFLATED) as z:
 z.writestr('repo/Empty/',b'')
 z.writestr('repo/Program.cs','Console.WriteLine("42");\\n'*150)
 z.writestr('repo/Assets/pixels.bin',bytes(range(256))*128)
sys.stdout.buffer.write(b.getvalue())`]);assert.equal(py.status,0);const out=readZip(new Uint8Array(py.stdout));assert.equal(out.length,3);assert.equal(out[2].bytes.length,32768);assert.equal(out[1].bytes.length,3750);});
for(const path of ['../escape','/etc/passwd','C:/x','a/../../b','a//b','a/./b','foo\u0000.cs','NUL.cs','a./b','a/b ','CON/a','a:b'])test('ZIP rejects unsafe path '+JSON.stringify(path),()=>assert.throws(()=>writeZip([{path,text:'x'}])));
for(const kind of ['crc','data','local-name','truncation','encryption','zip64','symlink','count','overlap'])test('ZIP rejects malformed '+kind+' before returning records',()=>{const b=writeZip([{path:'a.txt',text:'Hello'},{path:'b.txt',text:'World'}]),v=new DataView(b.buffer),central=v.getUint32(b.length-6,true);if(kind==='crc')v.setUint32(14,123,true);if(kind==='data')b[35]^=1;if(kind==='local-name')b[30]=0x7a;if(kind==='encryption'){v.setUint16(6,0x801,true);v.setUint16(central+8,0x801,true);}if(kind==='zip64')v.setUint32(central+24,0xffffffff,true);if(kind==='symlink')v.setUint32(central+38,0xa1ff0000,true);if(kind==='count')v.setUint16(b.length-12,123,true);if(kind==='overlap')v.setUint32(central+51+42,0,true);assert.throws(()=>readZip(kind==='truncation'?b.slice(0,-1):b));});
test('ZIP rejects case and Unicode collisions and file-as-parent conflicts',()=>{for(const pair of [['A.cs','a.cs'],['é.txt','e\u0301.txt'],['a','a/x']])assert.throws(()=>writeZip(pair.map(path=>({path,text:'x'}))));});
test('ZIP validates expansion/file/count limits, not only compressed input size',()=>{const b=writeZip([{path:'a',text:'x'.repeat(100)}]);assert.throws(()=>readZip(b,{maxFileBytes:99}));assert.throws(()=>readZip(b,{maxTotalBytes:99}));assert.throws(()=>writeZip([{path:'a',text:''},{path:'b',text:''}],{maxEntries:1}));assert.throws(()=>readZip(b,{maxDepth:0}));});
for(const encoding of ['utf-8','utf-16le','utf-16be'])test('workspace retains '+encoding+' BOM/CRLF, assets and debugger metadata across ZIP roundtrips',()=>{const original=encodeWorkspaceFile({path:'Program.cs',text:'// żółć 😀\r\nConsole.WriteLine(42);\r\n',encoding,bom:true}),record=decodeWorkspaceFile('Program.cs',original),asset=Uint8Array.from([0,255,13,10,127]),settings={name:'App',mode:'folder',breakpoints:{'Program.cs':[{line:2,condition:'x > 0',conditionMode:'whenChanged',enabled:false,oneShot:true,hitCondition:'%2',logMessage:'{x}'}]},functionBreakpoints:[{name:'Program.Main',enabled:true}],tabs:['Program.cs'],active:'Program.cs',extensions:{schema:true,analyzers:true,additionalFiles:[{uri:'model.schema.json',text:'{}'}]}};
 const bytes=exportWorkspaceZip({records:[record,{path:'logo.bin',bytes:asset}],folders:['empty'],settings}),out=importWorkspaceZip(bytes);assert.deepEqual(out.records.find(r=>r.path==='Program.cs').bytes,original);assert.deepEqual(out.records.find(r=>r.path==='logo.bin').bytes,asset);assert.deepEqual(out.settings.breakpoints['Program.cs'],settings.breakpoints['Program.cs']);assert.equal(out.records.find(r=>r.path==='Program.cs').encoding,encoding);record.text+='// edit\r\n';const again=importWorkspaceZip(exportWorkspaceZip({records:[record]}));assert.equal(again.records[0].text,record.text);assert.equal(again.records[0].encoding,encoding);});
test('manifest allows only data, validates stale entries and never restores execution trust',()=>{assert.throws(()=>validateWorkspaceSettings({entry:'missing.csproj'},[]));assert.throws(()=>validateWorkspaceSettings({entry:'../evil'},[]));assert.throws(()=>validateWorkspaceSettings({breakpoints:{'a.cs':[{line:-1}]}},['a.cs']));const x=validateWorkspaceSettings({trusted:true,host:'http://evil',extensions:{schema:true,eval:'arbitrary code'}},[]);assert.equal(x.trusted,undefined);assert.equal(x.extensions.eval,undefined);});
test('folder FileList preserves unknown assets and .pdb instead of silently dropping them',async()=>{const files=[new File([Uint8Array.from([0,255])],'icon.png'),new File([Uint8Array.from([66,83,74,66])],'app.pdb'),new File(['int x=1;'],'Program.cs')];const records=await readBrowserFiles(files);assert.equal(records.length,3);assert.deepEqual([...records[0].bytes],[0,255]);assert.equal(records[2].text,'int x=1;');});
test('legacy SLN parses project hierarchy and converts explicitly without mutating original data',()=>{const input='Microsoft Visual Studio Solution File, Format Version 12.00\nProject("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Source", "Source", "{11111111-1111-1111-1111-111111111111}"\nEndProject\nProject("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "App", "App\\App.csproj", "{22222222-2222-2222-2222-222222222222}"\nEndProject\nGlobal\nGlobalSection(NestedProjects) = preSolution\n{22222222-2222-2222-2222-222222222222} = {11111111-1111-1111-1111-111111111111}\nEndGlobalSection\nEndGlobal';const parsed=readLegacySolution(input,'App.sln');assert.deepEqual(parsed.projectPaths,['App/App.csproj']);assert.equal(parsed.items[0].folder,'/Source/');const converted=convertLegacySolution(input,'App.sln');assert.equal(converted.path,'App.slnx');assert(converted.text.includes('/Source/'));const sys=new ProjectSystem([{path:'App.sln',text:input},{path:'App/App.csproj',text:'<Project Sdk="Microsoft.NET.Sdk" />'}]);assert.equal(sys.load('App.sln').projects.length,1);});
test('solution folder edits retain comments and per-project configuration when reparenting',()=>{let text='\ufeff<Solution>\r\n<!-- Keep -->\r\n<Folder Name="/Src/"><Project Path="A/A.csproj"><BuildType Solution="Debug" Project="Retail" /></Project></Folder>\r\n<Folder Name="/Src/Child/" />\r\n</Solution>';text=renameSolutionFolder(text,{folder:'/Src/',name:'Code'});assert(text.includes('/Code/Child/'));text=moveSolutionProject(text,{solutionPath:'Repo.slnx',projectPath:'A/A.csproj',folder:null});assert(text.includes('Project="Retail"'));text=removeSolutionFolder(text,'Code');assert(!text.includes('<Folder'));assert(text.includes('<!-- Keep -->'));assert(text.includes('A/A.csproj'));text=addSolutionItem(text,{solutionPath:'Repo.slnx',path:'Readme.md'});assert(text.includes('<File Path="Readme.md"'));});
test('native create-only binary mutation is byte exact and undo removes created asset; scan includes unknown files',async()=>{const root=await mkdtemp(join(tmpdir(),'sf-assets-'));try{const w=await NativeWorkspace.open(root),bytes=Buffer.from([0,128,255,13,10]);const r=await w.mutate([{kind:'create',path:'Assets/data.unknown',base64:bytes.toString('base64')}]);assert.deepEqual(await readFile(join(root,'Assets/data.unknown')),bytes);assert((await w.scan()).files.some(f=>f.path==='Assets/data.unknown'));await w.undoMutation(r.undoToken);assert(!(await readdir(join(root,'Assets'))).length);await assert.rejects(()=>w.mutate([{kind:'create',path:'bad.bin',base64:'????'}]));}finally{await rm(root,{recursive:true,force:true});}});
test('CLI create-only project plan never overwrites existing files and is actually runnable',async()=>{const base=await mkdtemp(join(tmpdir(),'sf-new-'));try{const root=join(base,'New'),plan=createProjectPlan('console-library-solution',{projectName:'ConsoleApp'});await writePlan(root,plan);await assert.rejects(()=>writePlan(root,plan),/empty|exist/);const run=spawnSync(process.execPath,['apps/cli/main.js','run',join(root,'ConsoleApp.slnx')],{encoding:'utf8'});assert.equal(run.status,0,run.stderr);assert.equal(run.stdout.trim(),'42');}finally{await rm(base,{recursive:true,force:true});}});
