import test from 'node:test';import assert from 'node:assert/strict';
import {compileToIL} from '@sharpforge/compiler';import {loadAssembly,verifyCilAssembly,formatILDocument,assembleILDocument} from '@sharpforge/cil';
import {VirtualMachine,CilVirtualMachine} from '@sharpforge/runtime';import {DebugSession,CilDebugSession} from '@sharpforge/debugger';
const prefix='using Microsoft.UI.Xaml;using Microsoft.UI.Xaml.Controls;using Microsoft.UI.Xaml.Media;using Microsoft.UI;using System.Threading.Tasks;';
const compile=text=>{const c=compileToIL(prefix+text);assert(c.success,JSON.stringify(c.diagnostics));return c;};
const cache=new Map();function cached(text){if(!cache.has(text))cache.set(text,compile(text));return cache.get(text);}
const paths={source:c=>new VirtualMachine(c.image,{virtualTime:true,initialThreshold:64}),reload:c=>new VirtualMachine(loadAssembly(c.assembly),{virtualTime:true,initialThreshold:64}),cil:c=>new CilVirtualMachine(c.assembly,{virtualTime:true,initialThreshold:64})};
const node=(vm,name)=>vm.platform.scene().nodes.find(n=>n.properties.Name===name),ref=n=>{const[h,g]=n.id.split(':').map(Number);return {h,g};};
const programs=[
 ['properties and object initializers','Window w=new Window(){Title="Test"};StackPanel p=new StackPanel(){Spacing=8,Padding=new Thickness(12)};TextBlock t=new TextBlock(){Name="label",Text="42",FontSize=24};p.Children.Add(t);w.Content=p;w.Activate();Console.WriteLine(t.Text);','42\n'],
 ['typed brush values and attached layout','Grid p=new Grid();Button b=new Button(){Background=new SolidColorBrush(Colors.CornflowerBlue)};Grid.SetColumn(b,2);Grid.SetRowSpan(b,3);p.Children.Add(b);Window w=new Window(){Content=p};w.Activate();Console.WriteLine(Grid.GetColumn(b));Console.WriteLine(Grid.GetRowSpan(b));','2\n3\n'],
 ['grid tracks and star lengths','Grid p=new Grid();RowDefinition a=new RowDefinition(){Height=GridLength.Auto};p.RowDefinitions.Add(a);ColumnDefinition b=new ColumnDefinition(){Width=new GridLength(2,GridUnitType.Star)};p.ColumnDefinitions.Add(b);Console.WriteLine(p.RowDefinitions.Count);Console.WriteLine(b.Width.Value);','1\n2\n'],
 ['collection insert/remove ordering','StackPanel p=new StackPanel();Button a=new Button(),b=new Button();p.Children.Add(a);p.Children.Insert(0,b);Console.WriteLine(p.Children[0]==b);Console.WriteLine(p.Children.Remove(a));p.Children.RemoveAt(0);Console.WriteLine(p.Children.Count);','True\nTrue\n0\n'],
 ['visual cycle and duplicate rejection','StackPanel p=new StackPanel();try{p.Children.Add(p);}catch(Exception e){Console.WriteLine("cycle");}Button b=new Button();p.Children.Add(b);try{p.Children.Add(b);}catch(Exception e){Console.WriteLine("duplicate");}Console.WriteLine(p.Children.Count);','cycle\nduplicate\n1\n'],
 ['detach content permits reparenting','Button b=new Button();Window a=new Window(){Content=b};a.Content=null;Window c=new Window(){Content=b};c.Activate();Console.WriteLine(c.Content==b);','True\n'],
 ['detach collection permits reparenting','Button b=new Button();StackPanel a=new StackPanel(),c=new StackPanel();a.Children.Add(b);a.Children.Clear();c.Children.Add(b);Console.WriteLine(c.Children.Count);','1\n'],
 ['readonly and validated layout values','Button b=new Button();try{b.Width=-2;}catch(Exception e){Console.WriteLine("width");}try{b.Opacity=2;}catch(Exception e){Console.WriteLine("opacity");}try{Grid.SetRow(b,-1);}catch(Exception e){Console.WriteLine("row");}','width\nopacity\nrow\n'],
 ['supported code-first controls','StackPanel p=new StackPanel();p.Children.Add(new PasswordBox());p.Children.Add(new CheckBox());p.Children.Add(new ToggleSwitch());p.Children.Add(new Slider());p.Children.Add(new ComboBox());p.Children.Add(new ListView());p.Children.Add(new ProgressBar());p.Children.Add(new ProgressRing());p.Children.Add(new Expander());p.Children.Add(new Image());p.Children.Add(new HyperlinkButton());Console.WriteLine(p.Children.Count);','11\n'],
 ['bounded drawing commands and color channels','SharpForge.UI.DrawingSurface p=new SharpForge.UI.DrawingSurface();p.FillRectangle(1,2,3,4,Colors.Red);p.DrawLine(0,0,20,20,2,Colors.Blue);Window w=new Window(){Content=p};w.Activate();Console.WriteLine(Colors.Red.R);','255\n'],
 ['window lifetime survives collection','Window w=new Window(){Content=new TextBlock(){Name="label",Text="rooted"}};w.Activate();w=null;GC.Collect();Console.WriteLine("kept");','kept\n'],
 ['FindName searches visual child hierarchy','StackPanel p=new StackPanel();Button b=new Button(){Name="target"};p.Children.Add(b);Console.WriteLine(p.FindName("target")==b);Console.WriteLine(p.FindName("missing")==null);','True\nTrue\n']
];
for(const[path,factory]of Object.entries(paths))for(const[name,text,expected]of programs)test(`${path} WinUI: ${name}`,async()=>{const vm=factory(cached(text)),r=await vm.runAsync();assert.equal(r.state,'terminated',r.fault?.message);assert.equal(r.output,expected);vm.heap.collect();assert.doesNotThrow(()=>vm.platform.scene());});
const ui=`class P{static TextBlock label;static TextBox input;static int count;static void Click(object sender,RoutedEventArgs args){count++;label.Text=input.Text+":"+count;GC.Collect();}static void Main(){Window w=new Window();StackPanel p=new StackPanel();label=new TextBlock(){Name="label",Text="0"};input=new TextBox(){Name="input",Text="initial",MaxLength=20};Button b=new Button(){Name="button",Content="Run"};b.Click+=Click;p.Children.Add(input);p.Children.Add(label);p.Children.Add(b);w.Content=p;w.Activate();}}`;
for(const[path,factory]of Object.entries(paths)){
 test(`${path}: input without subscribers updates managed properties; event calls target C# after Main`,async()=>{const vm=factory(cached(ui));await vm.runAsync();vm.heap.collect();assert.deepEqual(vm.platform.dispatchEvent(node(vm,'input').id,'TextChanged',{value:'typed'}),[]);vm.platform.dispatchEvent(node(vm,'button').id,'Click');await vm.runAsync();assert.equal(node(vm,'label').properties.Text,'typed:1');vm.platform.dispatchEvent(node(vm,'button').id,'Click');await vm.runAsync();assert.equal(node(vm,'label').properties.Text,'typed:2');});
 test(`${path}: async void event handler resumes after Delay`,async()=>{const vm=factory(cached(ui.replace('static void Click','static async void Click').replace('count++;','await Task.Delay(10);count++;')));await vm.runAsync();vm.platform.dispatchEvent(node(vm,'button').id,'Click');vm.run();assert.equal(vm.state,'waiting');assert.equal(node(vm,'label').properties.Text,'0');vm.heap.collect();await vm.runAsync();assert.equal(node(vm,'label').properties.Text,'initial:1');});
 test(`${path}: delegate unsubscription removes matching method and receiver`,async()=>{const text=ui.replace('b.Click+=Click;','b.Click+=Click;b.Click+=Click;b.Click-=Click;'),vm=factory(cached(text));await vm.runAsync();vm.platform.dispatchEvent(node(vm,'button').id,'Click');await vm.runAsync();assert.equal(node(vm,'label').properties.Text,'initial:1');});
 test(`${path}: event input validation and limits are nonmutating`,async()=>{const vm=factory(cached(ui));await vm.runAsync();const input=node(vm,'input');assert.throws(()=>vm.platform.dispatchEvent(input.id,'TextChanged',{value:42}),/input text/);assert.equal(node(vm,'input').properties.Text,'initial');vm.platform.dispatchEvent(input.id,'TextChanged',{value:'a'.repeat(100)});assert.equal(node(vm,'input').properties.Text.length,20);assert.throws(()=>vm.platform.dispatchEvent(node(vm,'button').id,'NotAnEvent'),/event/);assert.throws(()=>vm.platform.dispatchEvent('999999:1','Click'));});
 test(`${path}: disabled control cannot execute event callbacks`,async()=>{const vm=factory(cached(ui.replace('Name="button",Content="Run"','Name="button",Content="Run",IsEnabled=false')));await vm.runAsync();assert.deepEqual(vm.platform.dispatchEvent(node(vm,'button').id,'Click'),[]);assert.equal(node(vm,'label').properties.Text,'0');});
 test(`${path}: layout measurements are validated and visible to managed code`,async()=>{const vm=factory(cached(ui));await vm.runAsync();const input=node(vm,'input');assert.throws(()=>vm.platform.updateLayout([{id:input.id,width:-1,height:22}]),/measurement/);assert.equal(node(vm,'input').properties.ActualWidth,0);vm.platform.updateLayout([{id:input.id,width:320,height:32}]);assert.equal(node(vm,'input').properties.ActualWidth,320);});
 test(`${path}: stopping releases active windows and rejects stale events`,async()=>{const vm=factory(cached(ui));await vm.runAsync();const id=node(vm,'button').id;vm.stop();assert.equal(vm.platform.scene().windows.length,0);assert.throws(()=>vm.platform.dispatchEvent(id,'Click'),/active visual tree/);});
 test(`${path}: visual snapshots restore UI state and callbacks`,async()=>{const vm=factory(cached(ui));await vm.runAsync();const before=vm.snapshot();vm.platform.dispatchEvent(node(vm,'button').id,'Click');await vm.runAsync();assert.equal(node(vm,'label').properties.Text,'initial:1');vm.restore(before);assert.equal(node(vm,'label').properties.Text,'0');vm.state='terminated';vm.platform.dispatchEvent(node(vm,'button').id,'Click');await vm.runAsync();assert.equal(node(vm,'label').properties.Text,'initial:1');});
 test(`${path}: mutable brushes retain identity across consumers`,async()=>{const vm=factory(cached('SolidColorBrush b=new SolidColorBrush(Colors.Red);Button p=new Button(){Name="button",Background=b};b.Color=Colors.Blue;Window w=new Window(){Content=p};w.Activate();'));await vm.runAsync();assert.equal(node(vm,'button').properties.Background.Color.B,255);});
}
for(const direct of [false,true])test(`${direct?'CIL':'source'}: debugger UI function evaluation rolls back commands and heap`,()=>{const text=prefix+`class P{static TextBlock label;static int Update(){label.Text="changed";return 42;}static void Main(){label=new TextBlock(){Text="old",Name="label"};Window w=new Window(){Content=label};w.Activate();\nConsole.WriteLine("pause");}}`,c=compileToIL(text);assert(c.success);const commands=[],s=direct?new CilDebugSession(c.assembly,{onUICommand:c=>commands.push(c)}):new DebugSession(c.image,{onUICommand:c=>commands.push(c)});s.setBreakpoints('Program.cs',[{line:2}]);s.start(false);s.runUntilStop();const n=commands.length;const result=s.evaluateFunction('P.Update()',{allowSideEffects:true,commit:false});assert.equal(result.result,'42');assert.equal(node(s.vm,'label').properties.Text,'old');assert.equal(commands.length,n);s.evaluateFunction('P.Update()',{allowSideEffects:true});assert.equal(node(s.vm,'label').properties.Text,'changed');assert(commands.some(c=>c.op==='set'&&c.value==='changed'));});
test('WinUI IL is verified and executes after all-method editable IL reconstruction',async()=>{const c=cached(ui);assert(verifyCilAssembly(c.assembly).success);const bytes=assembleILDocument(formatILDocument(c.assembly)).bytes,vm=new CilVirtualMachine(bytes,{virtualTime:true});await vm.runAsync();vm.platform.dispatchEvent(node(vm,'button').id,'Click');await vm.runAsync();assert.equal(node(vm,'label').properties.Text,'initial:1');});
test('async compiler symbols have stable unique IDs and no generated capture fields in Solution Explorer',()=>{const c=cached(ui.replace('static void Click','static async void Click').replace('count++;','await Task.Delay(1);count++;'));assert.equal(new Set(c.symbols.map(s=>s.id)).size,c.symbols.length);assert(c.symbols.every(s=>!/^arg\d+$/.test(s.name)&&!s.name.startsWith('<>')));});
