import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,readdir,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {encodeWorkspaceFile,decodeWorkspaceFile} from '@sharpforge/archive';
import {createProjectPlan} from '@sharpforge/templates';
import {readBrowserFiles,readDirectory,DiskWorkspace,writeNewDirectory,workspaceManifestRecord,importWorkspaceRecords,exportWorkspaceZip,importWorkspaceZip} from '@sharpforge/project-system';
import {NativeWorkspace} from '../packages/msbuild/src/workspace.js';
const enc=s=>new TextEncoder().encode(s);
const missing=()=>Object.assign(new Error('Not found'),{name:'NotFoundError'});
// Deliberate File System Access test doubles: browser permission dialogs are not qualified by these tests.
class FileHandle {
 constructor(name,bytes=enc(''),options={}){this.name=name;this.kind='file';this.bytes=bytes.slice();this.options=options;this.writes=0;}
 async getFile(){return new File([this.bytes],this.name);}
 async queryPermission(){return this.options.permission??'granted';}
 async requestPermission(){return this.options.permission??'granted';}
 async createWritable(){const self=this;let bytes=null;return {async write(value){if(self.options.fail)throw new Error('Simulated full disk');bytes=typeof value==='string'?enc(value):new Uint8Array(value);},async close(){self.bytes=bytes.slice();self.writes++;},async abort(){}};}
}
class Directory {
 constructor(name='Workspace',options={}){this.name=name;this.kind='directory';this.children=new Map();this.options=options;}
 async *entries(){yield* this.children;}
 async queryPermission(){return this.options.permission??'granted';}
 async requestPermission(){return this.options.permission??'granted';}
 async getDirectoryHandle(name,{create=false}={}){const old=this.children.get(name);if(old){if(old.kind!=='directory')throw new Error('Not a directory');return old;}if(!create)throw missing();const result=new Directory(name,this.options);this.children.set(name,result);return result;}
 async getFileHandle(name,{create=false}={}){const old=this.children.get(name);if(old){if(old.kind!=='file')throw new Error('Not a file');return old;}if(!create)throw missing();const result=new FileHandle(name,enc(''),{fail:name===this.options.failName});this.children.set(name,result);return result;}
}
async function fileAt(root,path){const parts=path.split('/');let dir=root;for(const part of parts.slice(0,-1))dir=await dir.getDirectoryHandle(part);return dir.getFileHandle(parts.at(-1));}
for(const encoding of ['utf-8','utf-16le','utf-16be'])test(`empty-folder save/reopen preserves ${encoding} bytes, all assets, settings and empty directories`,async()=>{
 const root=new Directory(),plan=createProjectPlan('console-library-solution',{projectName:'FolderApp'});const original=encodeWorkspaceFile({path:'Notes.md',text:'// Żółć 😀\r\n',encoding,bom:true});
 const records=[...plan.records,decodeWorkspaceFile('Notes.md',original),{path:'Assets/random.unknown',bytes:Uint8Array.from([0,255,0,128])},{path:'Assets/not-text.cs',bytes:Uint8Array.from([255,254,0])}],settings={name:'FolderApp',entry:plan.entry,startup:plan.startup,mode:'solution',configuration:'Release',active:plan.records.find(r=>r.path.endsWith('Program.cs')).path,breakpoints:{},functionBreakpoints:[]};
 records.push(workspaceManifestRecord(settings,records));const saved=await writeNewDirectory(root,{records,folders:[...plan.folders,'Extra/Empty']});assert.equal(saved.atomic,false);assert.equal(saved.written.length,records.length);
 const disk=await readDirectory(root),input=importWorkspaceRecords(disk.records,disk.folders);assert(input.manifest);assert.equal(input.settings.configuration,'Release');assert.equal(input.settings.startup,plan.startup);assert(input.folders.includes('Extra/Empty'));assert.deepEqual(input.records.find(r=>r.path==='Notes.md').bytes,original);assert.deepEqual(input.records.find(r=>r.path==='Assets/not-text.cs').bytes,Uint8Array.from([255,254,0]));
 const again=importWorkspaceZip(exportWorkspaceZip(input));assert.equal(again.records.length,records.length-1);assert.deepEqual(again.records.find(r=>r.path==='Assets/random.unknown').bytes,Uint8Array.from([0,255,0,128]));
});
test('empty-folder writer rejects preexisting contents without opening a write stream',async()=>{const root=new Directory();const file=new FileHandle('Old.txt',enc('keep'));root.children.set(file.name,file);await assert.rejects(()=>writeNewDirectory(root,{records:[{path:'New.cs',text:'x'}]}),/empty destination/);assert.equal(root.children.size,1);assert.equal(file.writes,0);assert.equal(new TextDecoder().decode(file.bytes),'keep');});
test('empty-folder writer resolves denied permission before any mutation',async()=>{const root=new Directory('No',{permission:'denied'});await assert.rejects(()=>writeNewDirectory(root,{records:[{path:'New.cs',text:'x'}]}),/permission denied/);assert.equal(root.children.size,0);});
test('empty-folder writer reports completed writes on mid-operation failure, never claims atomicity',async()=>{const root=new Directory('Partial',{failName:'Bad.cs'});await assert.rejects(()=>writeNewDirectory(root,{records:[{path:'Good.cs',text:'ok'},{path:'Bad.cs',text:'fail'},{path:'Never.cs',text:'not'}]}),error=>{assert.deepEqual(error.written,['Good.cs']);assert.match(error.message,/1 file\(s\) written/);return true;});assert.equal(new TextDecoder().decode((await fileAt(root,'Good.cs')).bytes),'ok');assert(!root.children.has('Never.cs'));});
test('aborted empty-folder save creates no files',async()=>{const root=new Directory();const c=new AbortController();c.abort();await assert.rejects(()=>writeNewDirectory(root,{records:[{path:'a.txt',text:'x'}]},{signal:c.signal}),e=>e.name==='AbortError');assert.equal(root.children.size,0);});
for(const paths of [['A.txt','a.txt'],['A/one.txt','a/two.txt'],['é.txt','e\u0301.txt'],['a','a/b']])test('empty-folder writer validates complete path plan before mutation '+paths.join(' / '),async()=>{const root=new Directory();await assert.rejects(()=>writeNewDirectory(root,{records:paths.map(path=>({path,text:'x'}))}));assert.equal(root.children.size,0);});
test('directory loader preserves explicitly recorded files but excludes administrative code and stores warning paths',async()=>{const root=new Directory();for(const name of ['.git','node_modules','.vs']){const child=await root.getDirectoryHandle(name,{create:true});child.children.set('secret.js',new FileHandle('secret.js',enc('not evaluated')));}const admin=await root.getDirectoryHandle('.sharpforge',{create:true});admin.children.set('untrusted.js',new FileHandle('untrusted.js',enc('not restored')));root.children.set('asset.pdb',new FileHandle('asset.pdb',Uint8Array.from([66,83,74,66])));const d=await readDirectory(root);assert.deepEqual(d.records.map(r=>r.path),['asset.pdb']);assert.deepEqual(d.skipped.sort(),['.git','.vs','node_modules'].sort());});
test('folder manifests reject ambiguity and preserve the original records on failure',()=>{const a={path:'.sharpforge/workspace.json',text:'{}'},b={path:'nested/.sharpforge/workspace.json',text:'{}'},records=[a,b];assert.throws(()=>importWorkspaceRecords(records),/Multiple/);assert.equal(records.length,2);assert.equal(records[0],a);assert.throws(()=>importWorkspaceRecords([a]),/Unsupported/);});
test('FileList repository prefix is normalized only by a validated workspace manifest',async()=>{const plan=createProjectPlan('console',{projectName:'Repo'}),settings={entry:plan.entry,startup:plan.startup,mode:'solution'};const records=[...plan.records,workspaceManifestRecord(settings,plan.records)],files=records.map(r=>{const f=new File([r.text],r.path.split('/').at(-1));Object.defineProperty(f,'webkitRelativePath',{value:'download/'+r.path});return f;});const read=await readBrowserFiles(files),input=importWorkspaceRecords(read,read.folders);assert.equal(input.settings.entry,plan.entry);assert(input.records.every(r=>!r.path.startsWith('download/')));assert.equal(input.records.length,plan.records.length);});
for(const encoding of ['utf-16le','utf-16be'])test(`disk source save preserves ${encoding} and detects external edits before any writing`,async()=>{const original=encodeWorkspaceFile({path:'Program.cs',text:'// old\r\n',encoding,bom:true}),handle=new FileHandle('Program.cs',original),record=decodeWorkspaceFile('Program.cs',original),disk=new DiskWorkspace([record],new Map([['Program.cs',handle]]));await disk.save([{path:'Program.cs',text:'// new Ż\r\n'}]);assert.equal(decodeWorkspaceFile('Program.cs',handle.bytes).text,'// new Ż\r\n');assert.equal(decodeWorkspaceFile('Program.cs',handle.bytes).encoding,encoding);handle.bytes=encodeWorkspaceFile({...record,text:'// external\r\n'});await assert.rejects(()=>disk.save([{path:'Program.cs',text:'// overwrite\r\n'}]),/Disk conflict/);assert.equal(handle.writes,1);});
test('disk source save rechecks after permissions and never overwrites a prompt-time change',async()=>{const h=new FileHandle('A.cs',enc('old'));h.queryPermission=async()=>{h.bytes=enc('external');return 'granted';};const disk=new DiskWorkspace([decodeWorkspaceFile('A.cs',h.bytes)],new Map([['A.cs',h]]));await assert.rejects(()=>disk.save([{path:'A.cs',text:'new'}]),/Disk conflict/);assert.equal(h.writes,0);});
test('native disk creation rejects case-shadow files and parents before applying any batch entry',async()=>{const root=await mkdtemp(join(tmpdir(),'sf-portable-'));try{await mkdir(join(root,'Assets'));await writeFile(join(root,'Assets','Logo.bin'),Uint8Array.from([1,2,3]));const w=await NativeWorkspace.open(root);for(const path of ['assets/new.bin','Assets/logo.bin'])await assert.rejects(()=>w.mutate([{kind:'create',path:'First.txt',text:'not written'},{kind:'create',path,base64:'AQI='}]),/collid/);assert.deepEqual((await readdir(root)).sort(),['Assets']);assert.deepEqual(await readFile(join(root,'Assets','Logo.bin')),Buffer.from([1,2,3]));}finally{await rm(root,{recursive:true,force:true});}});
test('native new destination parents use portable case identity within the same batch',async()=>{const root=await mkdtemp(join(tmpdir(),'sf-parentcase-'));try{const w=await NativeWorkspace.open(root);await assert.rejects(()=>w.mutate([{kind:'create',path:'Source/A.cs',text:'x'},{kind:'create',path:'source/B.cs',text:'y'}]),/collid/);assert.deepEqual(await readdir(root),[]);}finally{await rm(root,{recursive:true,force:true});}});

test('CLI ZIP/extraction preserve an existing manifest, binaries and empty folders',async()=>{
 const {spawnSync}=await import('node:child_process');const {writePlan}=await import('../apps/cli/workspace.js');const base=await mkdtemp(join(tmpdir(),'sf-cli-zip-'));try{
 const p=createProjectPlan('console-library-solution',{projectName:'CliApp'}),source=join(base,'Source'),zip=join(base,'Backup.zip'),destination=join(base,'Extracted'),settings={entry:p.entry,startup:p.startup,configuration:'Release',breakpoints:{[p.openFile]:[{line:8,enabled:false}]}},records=[...p.records,{path:'Assets/opaque.cs',bytes:Uint8Array.from([255,254,0])}];records.push(workspaceManifestRecord(settings,records));await writePlan(source,{records,folders:[...p.folders,'Empty']});
 for(const args of [['zip',source,'-o',zip],['unzip',zip,'-o',destination]]){const r=spawnSync(process.execPath,['apps/cli/main.js',...args],{encoding:'utf8'});assert.equal(r.status,0,r.stdout+r.stderr);}
 const metadata=JSON.parse(await readFile(join(destination,'.sharpforge/workspace.json'),'utf8'));assert.equal(metadata.configuration,'Release');assert.equal(metadata.startup,p.startup);assert.equal(metadata.breakpoints[p.openFile][0].enabled,false);assert.deepEqual(await readFile(join(destination,'Assets/opaque.cs')),Buffer.from([255,254,0]));assert.deepEqual(await readdir(join(destination,'Empty')),[]);
 const r=spawnSync(process.execPath,['apps/cli/main.js','run',join(destination,p.entry)],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);assert.equal(r.stdout.trim(),'42');
 }finally{await rm(base,{recursive:true,force:true});}
});
test('CLI writePlan validates duplicate/case/traversing destinations before creating output directory',async()=>{const {writePlan}=await import('../apps/cli/workspace.js'),base=await mkdtemp(join(tmpdir(),'sf-cli-plan-'));try{for(const paths of [['A/x','a/y'],['one','one'],['../bad']]){const target=join(base,'Untouched');await assert.rejects(()=>writePlan(target,{records:paths.map(path=>({path,text:'x'}))}));assert.deepEqual(await readdir(base),[]);}}finally{await rm(base,{recursive:true,force:true});}});
