import {storage,storageKeys} from './settings/storage.js';
import {updateDebugStopBanner} from './debug-stop-banner.js';
import {debugBreakpointRows} from './debug-breakpoint-rows.js';
import {parseExpression} from '../../packages/syntax/src/index.js';
import {escapeHtml as E} from '../../packages/editor/src/index.js';
import {validateBreakpointRule} from '../../packages/debugger/src/breakpoint-rules.js';
export const debuggerDefaults=Object.freeze({stopOnEntry:false,recordHistory:true,stepOverProperties:true,breakpointsEnabled:true,exceptionBreak:'uncaught',exceptionRules:[]});
const modeOptions=(mode)=>['none','all','uncaught'].map(m=>`<option value="${m}" ${mode===m?'selected':''}>${{none:'Never',all:'When thrown',uncaught:'When unhandled'}[m]}</option>`).join('');
/** Studio presentation for source/function/storage breakpoints and safe evaluation. No debugger semantics live here. */
export class DebuggerTools {
 constructor(services){Object.assign(this,services);this.banner=document.createElement('div');this.banner.id='debug-stop-banner';this.banner.className='debug-stop-banner';this.banner.hidden=true;this.banner.setAttribute('role','status');this.banner.setAttribute('aria-live','polite');document.querySelector('#workspace').before(this.banner);}
 persist(){try{storage.setItem(storageKeys.debugger,JSON.stringify(this.state.debugSettings));}catch{}this.save();}
 async configure(patch){const next={...this.state.debugSettings,...patch};
  for(const key of ['stopOnEntry','recordHistory','stepOverProperties','breakpointsEnabled'])if(typeof next[key]!=='boolean')throw new TypeError(key+' must be Boolean');
  if(!['none','all','uncaught'].includes(next.exceptionBreak))throw new Error('Invalid exception mode');
  if(!Array.isArray(next.exceptionRules)||next.exceptionRules.length>100||next.exceptionRules.some(r=>typeof r.name!=='string'||!r.name.trim()||!['none','all','uncaught'].includes(r.mode)))throw new Error('Provide up to 100 exception type rules with a valid mode');
  const live=this.state.debug&&['ready','running','paused'].includes(this.state.debug.state);
  if(live&&('exceptionBreak'in patch||'exceptionRules'in patch))await this.request('exceptionBreak',{mode:next.exceptionBreak,rules:next.exceptionRules});
  if(live&&'breakpointsEnabled'in patch)await this.request('breakpointsEnabled',{enabled:next.breakpointsEnabled});
  this.state.debugSettings=next;this.persist();this.onSettings();this.decorate();this.render('breakpoints');this.render('debug-session');return structuredClone(next);
 }
 updateBanner(){updateDebugStopBanner(this);}
 async editRule(existing,title,{source=false,func=false}={}){return this.ask(title,`${func?`<div class="form-row"><label for="bp-function">Function</label><input id="bp-function" value="${E(existing.name??'')}" placeholder="Program.Fibonacci(int)"><small>Method, Type.Method or Type.Method(types). Matching overloads are listed after binding.</small></div>`:''}${source?`<div class="form-row"><label for="bp-column">Column (optional)</label><input id="bp-column" type="number" min="1" value="${E(existing.column??'')}"><small>Empty binds executable statements on the line. A column pins the containing statement.</small></div>`:''}<div class="form-row"><label for="bp-condition">Condition / watched expression</label><input id="bp-condition" value="${E(existing.condition??'')}" placeholder="i == 3"><select id="bp-condition-mode"><option value="whenTrue" ${existing.conditionMode!=='whenChanged'?'selected':''}>Is true (Boolean)</option><option value="whenChanged" ${existing.conditionMode==='whenChanged'?'selected':''}>Has changed since the previous encounter</option></select><small>Safe expressions only. Has changed seeds on first encounter without stopping.</small></div><div class="form-row"><label for="bp-hit">Hit condition</label><input id="bp-hit" value="${E(existing.hitCondition??'')}" placeholder="3, >=5, ==5, %10"><small>Counts location encounters, including conditions that evaluate false.</small></div><div class="form-row"><label for="bp-log">Logpoint message</label><input id="bp-log" value="${E(existing.logMessage??'')}" placeholder="i={i}, value={value}"><small>Log instead of stopping. Use {{ and }} for literal braces.</small></div><label class="debug-check"><input id="bp-once" type="checkbox" ${existing.oneShot?'checked':''}> Disable after the first qualifying hit / log</label>`,'Save breakpoint',()=>{
   const root=document.querySelector('#bp-condition')?.ownerDocument??document,q=id=>root.getElementById(id),value={...existing,...(func?{name:q('bp-function').value.trim()}:{}),condition:q('bp-condition').value.trim()||undefined,conditionMode:q('bp-condition-mode').value,hitCondition:q('bp-hit').value.trim()||undefined,logMessage:q('bp-log').value||undefined,oneShot:q('bp-once').checked};
   if(source){const text=q('bp-column').value;value.column=text?Number(text):undefined;if(value.column!==undefined&&(!Number.isInteger(value.column)||value.column<1))throw new Error('Column must be a positive integer');}
   if(func&&!value.name)throw new Error('Function name is required');validateBreakpointRule(value,text=>{const r=parseExpression(text);if(r.diagnostics.length)throw new Error(r.diagnostics[0].message);});return value;
  });}
 async setFunctions(items){if(!Array.isArray(items)||items.length>1000)throw new Error('At most 1000 function breakpoints are supported');for(const b of items){if(typeof b.name!=='string'||!b.name)throw new Error('Function name required');validateBreakpointRule(b,text=>{const r=parseExpression(text);if(r.diagnostics.length)throw new Error(r.diagnostics[0].message);});}const next=structuredClone(items);if(this.state.debug&&['paused','running','ready'].includes(this.state.debug.state))await this.request('functionBreakpoints',{breakpoints:next});this.state.functionBreakpoints=next;this.save();this.render('breakpoints');return this.state.debug?.functionBreakpoints??next;}
 async addFunction(){const value=await this.editRule({enabled:true},'New Function Breakpoint',{func:true});if(value)await this.setFunctions([...this.state.functionBreakpoints,value]);}
 rows(){return debugBreakpointRows(this.state);}
 async updateRow(row,item,remove=false){if(row.kind==='source'){const list=this.state.breakpoints[row.uri];if(remove)list.splice(row.index,1);else list[row.index]=item;await this.syncSource(row.uri);}else if(row.kind==='function'){const list=[...this.state.functionBreakpoints];if(remove)list.splice(row.index,1);else list[row.index]=item;await this.setFunctions(list);}else if(row.kind==='instruction'){const list=[...(this.state.debug?.breakpoints??[])].filter(b=>!b.source);const at=list.findIndex(b=>b.id===row.item.id);if(at<0)throw new Error('Instruction breakpoint expired');if(remove)list.splice(at,1);else list[at]=item;await this.request('instructionBreakpoints',{breakpoints:list});}else{const list=[...(this.state.debug?.dataBreakpoints??[])];if(remove)list.splice(row.index,1);else list[row.index]=item;await this.request('dataBreakpoints',{breakpoints:list});}this.save();this.decorate();this.render('breakpoints');}
 async clear(){const uris=Object.keys(this.state.breakpoints);this.state.breakpoints={};for(const uri of uris)await this.syncSource(uri);await this.setFunctions([]);if(this.state.debug&&['paused','running'].includes(this.state.debug.state)){await this.request('dataBreakpoints',{breakpoints:[]});if(this.state.debug.profile==='managed-il')await this.request('instructionBreakpoints',{breakpoints:[]});}this.save();this.decorate();this.render('breakpoints');}
 renderBreakpoints(el){const rows=this.rows(),d=this.state.debug,muted=this.state.debugSettings.breakpointsEnabled===false;this.state.renderedBreakpoints=rows;
  el.innerHTML=`<div class="panel-tools"><b>Breakpoints</b><button id="new-function-breakpoint">＋ Function…</button><button id="mute-breakpoints" aria-pressed="${muted}">${muted?'Enable all breakpoints':'Mute all breakpoints'}</button><span class="panel-spacer"></span><button id="clear-breakpoints">Remove all</button></div><div class="debug-bp-hint">Requested anchors stay separate from bound statements. Hit counts are encounters, not stops. ${muted?'Breakpoints are globally muted without changing their individual checkboxes.':''}</div>${rows.length?`<table class="data-table debugger-breakpoints"><thead><tr><th>On</th><th>Location / function / storage</th><th>Condition</th><th>Hit rule / hits</th><th>Log message</th><th>Binding / stop</th><th></th></tr></thead><tbody>${rows.map((r,i)=>{const bp=r.item,b=r.binding,hit=d?.state==='paused'&&(d.reason?.hitBreakpointIds??[d.reason?.breakpointId]).includes(b?.id),location=r.kind==='source'?`${r.uri}:${b?.line??bp.line}:${b?.column??bp.column??1}`:r.kind==='function'?bp.name:r.kind==='instruction'?bp.instructionReference:bp.description??`${bp.kind} #${bp.index}`,explanation=b?.message??(b?.verified?'Executable location verified':'Pending launch');return `<tr data-bp="${i}" data-bp-kind="${r.kind}" class="${hit?'breakpoint-hit':''}"><td><input type="checkbox" data-bp-enabled="${i}" ${(b?.enabled??bp.enabled)!==false?'checked':''} aria-label="Enable breakpoint ${i+1}"></td><td class="file-cell"><b>${E(location)}</b><small>${r.kind==='source'?`requested ${bp.line}${bp.column?':'+bp.column:''}${b?.locations?.length>1?' · '+b.locations.length+' statement locations':''}`:r.kind==='function'?(b?.locations?.length??b?.methodTokens?.length??0)+' matching locations':r.kind==='instruction'?'instruction address':'session-lifetime storage'}${bp.oneShot?' · once':''}</small></td><td class="code">${E(bp.condition??'Always')}${bp.conditionMode==='whenChanged'?' (changed)':''}</td><td class="code">${E(bp.hitCondition??'—')} / ${b?.hits??0}</td><td class="code">${E(bp.logMessage??'—')}</td><td title="${E(explanation)}">${hit?'➜ ':''}${(b?.enabled??bp.enabled)===false?'Disabled':b?.verified?'Bound':b?.verified===false?'Unbound':'Pending build'}<small>${E(explanation)}</small></td><td><button data-bp-remove="${i}" title="Remove breakpoint">×</button></td></tr>`;}).join('')}</tbody></table>`:'<div class="tool-page"><p>No breakpoints. Click a source gutter, press F9, create a function breakpoint, or select Break on write on a paused local.</p></div>'}`;
  const safe=fn=>(...args)=>Promise.resolve(fn(...args)).catch(e=>this.toast(e.message,'error'));
  el.querySelector('#new-function-breakpoint').onclick=safe(()=>this.addFunction());el.querySelector('#mute-breakpoints').onclick=safe(()=>this.configure({breakpointsEnabled:muted}));el.querySelector('#clear-breakpoints').onclick=safe(()=>this.clear());
  for(const tr of el.querySelectorAll('[data-bp]')){const row=rows[Number(tr.dataset.bp)];tr.ondblclick=safe(async event=>{if(event.target.closest('button,input'))return;const value=await this.editRule(row.item,'Edit '+row.kind+' breakpoint',{source:row.kind==='source',func:row.kind==='function'});if(value)await this.updateRow(row,value);});tr.onclick=()=>{if(row.kind==='source'){const file=this.state.files.find(f=>f.uri===row.uri);if(file)this.openFile(row.uri);}};}
  for(const input of el.querySelectorAll('[data-bp-enabled]'))input.onchange=safe(()=>this.updateRow(rows[+input.dataset.bpEnabled],{...rows[+input.dataset.bpEnabled].item,enabled:input.checked}));
  for(const button of el.querySelectorAll('[data-bp-remove]'))button.onclick=safe(()=>this.updateRow(rows[+button.dataset.bpRemove],null,true));
 }
 renderSettings(el){const s=this.state.debugSettings,d=this.state.debug;el.innerHTML=`<div class="tool-page debugger-settings"><h2>Debugger</h2><p>F5 runs to a breakpoint by default. F10 / F11 from idle explicitly break at the first executable statement.</p>${[['stopOnEntry','Break on entry when starting with F5'],['recordHistory','Record bounded managed-state history (next launch)'],['stepOverProperties','Step over property accessors (next launch)'],['breakpointsEnabled','Enable source, function, instruction and write breakpoints']].map(([key,label])=>`<label class="debug-check"><input type="checkbox" data-setting="${key}" ${s[key]?'checked':''}> ${label}</label>`).join('')}<h3>Exception Settings</h3><label>Default <select id="debug-exception-default">${modeOptions(s.exceptionBreak)}</select></label><p>Exact managed exception type overrides. “Never” suppresses a debugger stop, not the program exception. Native exceptions are not supported.</p><form id="exception-rule-form"><input id="exception-type" aria-label="Exception type" placeholder="System.OverflowException" required><select id="exception-type-mode">${modeOptions('all')}</select><button>Add / update</button></form><table class="data-table">${s.exceptionRules.map((r,i)=>`<tr><td>${E(r.name)}</td><td>${E(r.mode)}</td><td><button data-remove-exception="${i}">Remove</button></td></tr>`).join('')}</table><h3>Session</h3><p>${E(d?.profile??'Not started')} · ${E(d?.state??'idle')}</p><p>${d?.history?.count??0} retained snapshots · ${d?.history?.bytes??0} estimated bytes. History covers managed state only; it does not retract host output or undo native side effects.</p><p>Current location is yellow. A selected caller is marked separately. Source text must match the executing assembly before highlighting is allowed.</p></div>`;
  const safe=fn=>async event=>{try{await fn(event);}catch(e){this.toast(e.message,'error');}};
  for(const input of el.querySelectorAll('[data-setting]'))input.onchange=safe(()=>this.configure({[input.dataset.setting]:input.checked}));
  el.querySelector('#debug-exception-default').onchange=safe(event=>this.configure({exceptionBreak:event.target.value}));
  el.querySelector('#exception-rule-form').onsubmit=safe(event=>{event.preventDefault();const type=el.querySelector('#exception-type').value.trim(),mode=el.querySelector('#exception-type-mode').value;return this.configure({exceptionRules:[...s.exceptionRules.filter(r=>r.name!==type),{name:type,mode}]});});
  for(const button of el.querySelectorAll('[data-remove-exception]'))button.onclick=safe(()=>this.configure({exceptionRules:s.exceptionRules.filter((_,i)=>i!==+button.dataset.removeException)}));
 }
 async evaluateImmediate(expression,options={}){expression=String(expression).trim();if(!expression||expression.length>4096)throw new Error('Enter an expression of 1–4096 characters');const d=this.state.debug;if(d?.state!=='paused')throw new Error('Pause execution before evaluating');const sessionId=d.sessionId,frameId=this.state.frameId,entry={expression,frame:[...(this.state.inspectedThreadFrames??[]),...d.frames].find(f=>f.id===frameId)?.name??'',sessionId};try{const result=await this.request(options.allowSideEffects===true?'evaluateFunction':'evaluate',{expression,frameId,sessionId,...options});if(this.state.debug?.sessionId!==sessionId||this.state.frameId!==frameId||this.state.debug.state!=='paused')throw new Error('Debug frame changed while evaluating');Object.assign(entry,{result:result.result+(options.allowSideEffects?(result.committed?' · committed':' · rolled back'):''),type:result.type});}catch(error){entry.error=error.message;}if(this.state.debug?.sessionId===sessionId){this.state.immediateHistory.push(entry);if(this.state.immediateHistory.length>100)this.state.immediateHistory.shift();this.render('immediate');}return entry;}
 renderImmediate(el){const history=this.state.immediateHistory;el.innerHTML=`<div class="panel-tools"><b>Immediate</b><span>Selected frame · explicit calls available with consent</span><span class="panel-spacer"></span><button id="clear-immediate">Clear</button></div><div class="debug-immediate-log" aria-live="polite">${history.map(e=>`<div><small>${E(e.frame)}</small><pre>&gt; ${E(e.expression)}\n${E(e.error??e.result)}${e.type?'  ['+E(e.type)+']':''}</pre></div>`).join('')}</div><div class="effect-options"><label><input id="immediate-effects" type="checkbox" ${this.state.functionEvaluationEnabled?'checked':''}> Allow managed method calls and side effects</label><label><input id="immediate-rollback" type="checkbox" ${this.state.functionEvaluationRollback?'checked':''}> Roll back managed changes</label></div><form id="immediate-form"><label for="immediate-expression">&gt;</label><input id="immediate-expression" autocomplete="off" placeholder="e.g. value + 1 (no method calls / assignments)" ${this.state.debug?.state!=='paused'?'disabled':''}><button ${this.state.debug?.state!=='paused'?'disabled':''}>Evaluate</button></form><p class="debug-bp-hint">Watches stay side-effect-free. Explicit evaluation can run supported managed methods, constructors, getters and assignments in the selected frame. Execution is bounded; failed or timed-out evaluations roll back. External effects cannot be undone.</p>`;
  el.querySelector('#clear-immediate').onclick=()=>{this.state.immediateHistory=[];this.render('immediate');};const input=el.querySelector('#immediate-expression');let at=history.length;
  el.querySelector('#immediate-effects').onchange=e=>{this.state.functionEvaluationEnabled=e.target.checked;};el.querySelector('#immediate-rollback').onchange=e=>{this.state.functionEvaluationRollback=e.target.checked;};
  input.onkeydown=event=>{if(['ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();at=Math.min(history.length,Math.max(0,at+(event.key==='ArrowUp'?-1:1)));input.value=history[at]?.expression??'';}};
  el.querySelector('#immediate-form').onsubmit=async event=>{event.preventDefault();try{await this.evaluateImmediate(input.value,{allowSideEffects:el.querySelector('#immediate-effects').checked,commit:!el.querySelector('#immediate-rollback').checked});el.querySelector('#immediate-expression')?.focus();}catch(e){this.toast(e.message,'error');}};
 }
 renderTool(panel,el){if(panel==='breakpoints')this.renderBreakpoints(el);else if(panel==='debug-session')this.renderSettings(el);else if(panel==='immediate')this.renderImmediate(el);else return false;return true;}
}
