import {openDesignerSource,appendDesignSourceLocation} from './designer/source-editor.js';
import {escapeHtml as E} from '../../packages/editor/src/index.js';
import {propertySchema,resolvedProperties} from '../../packages/designer/src/index.js';
const category=k=>/^(Name|Title|Tag)$/.test(k)?'Identity':/(Width|Height|Margin|Padding|CornerRadius)/.test(k)?'Size & spacing':/(Alignment|Row|Column|Left|Top|Spacing|Orientation|ZIndex)/.test(k)?'Placement':/(Font|Text|Content|Placeholder|Header|Description)/.test(k)?'Text & typography':/(Background|Foreground|Border|Opacity|Visibility|Theme|Fill|Stroke)/.test(k)?'Appearance':/^(Is|Can|Allow|Accept|Selected|Value|Minimum|Maximum|Step|Password|Date|Time)/.test(k)?'Interaction':'Other';
const shapes={Layout:'<rect x="2" y="2" width="12" height="12" rx="1"/><path d="M2 7h12M7 2v12"/>',Input:'<rect x="1" y="3" width="14" height="10" rx="1"/><path d="M4 6v4m3-2h5"/>',Drawing:'<path d="M2 13 6 3l7 9z"/><circle cx="11" cy="4" r="2"/>',Controls:'<rect x="2" y="4" width="12" height="8" rx="2"/><path d="M5 8h6"/>'};
/** Workbench chrome remains independent of rendering and source ownership. */
export class DesignerChrome {
 constructor(view){this.view=view;this.mode='design';this.propertyGroups=new Map();this.toolboxGroups=new Map();this.installed=false;this.splitGroup=null;}
 install(){if(this.installed)return;this.installed=true;const v=this.view,p=v.panel('designer'),doc=p.ownerDocument;
  const modes=doc.createElement('div');modes.className='design-mode-bar';modes.innerHTML=`<div class="design-mode-tabs" role="tablist" aria-label="Designer views">${[['design','Design'],['split','Split'],['code','C#'],['preview','Preview']].map(([id,name])=>`<button role="tab" data-design-view="${id}" aria-selected="${this.mode===id}">${name}</button>`).join('')}</div><span class="panel-spacer"></span><label class="design-device-label">Artboard<select aria-label="Artboard preset" data-device-preset><option value="custom">Custom size</option><option value="1440x900">Desktop · 1440 × 900</option><option value="1024x768">Tablet · 1024 × 768</option><option value="390x844">Phone · 390 × 844</option><option value="800x600">Compact · 800 × 600</option></select></label>`;p.prepend(modes);modes.querySelectorAll('[data-design-view]').forEach(b=>b.onclick=()=>v.safe(()=>this.setMode(b.dataset.designView)));modes.querySelector('select').onchange=e=>{if(e.target.value==='custom')return;const [width,height]=e.target.value.split('x').map(Number);v.document.change('Artboard preset',d=>{d.width=width;d.height=height;const root=d.nodes.find(n=>n.id===d.root);const surface=root.type.endsWith('.Window')?d.nodes.find(n=>n.id===root.children[0]):root;if(surface&&propertySchema(surface.type).Width){surface.properties.Width=width;surface.properties.Height=height;}});v.action('fit');};
  const sync=doc.createElement('div');sync.className='design-sync-bar';p.insertBefore(sync,v.scroller);this.sync=sync;
  const crumbs=doc.createElement('div');crumbs.className='design-breadcrumbs';p.insertBefore(crumbs,v.scroller);this.crumbs=crumbs;
  const originalPreview=p.querySelector('[data-design-action=preview]');originalPreview.textContent='Test input';originalPreview.title='Input preview does not execute C# handlers; run the app for managed events';
  p.querySelector('[data-design-action=source]').textContent='Source & sync';p.querySelector('[data-design-action=generate]').classList.add('design-primary');
  this.scroll=()=>this.rulers();v.scroller.addEventListener('scroll',this.scroll,{passive:true});this.renderSync();this.renderSelection();this.rulers();
 }
 setMode(mode){const v=this.view;this.mode=mode;v.preview=mode==='preview';v.resizeArtboard();const uri=v.sourceSync.session?.analysis.uri;
  if(mode==='split'&&uri){openDesignerSource(v,uri);const location=v.docking.layout.locate('designer');const group=location.group?.id??location.groupId??location.group;const target=typeof group==='string'?group:v.docking.layout.groups().find(g=>g.panels.includes('designer'))?.id;const sourceLocation=v.docking.layout.groups().find(g=>g.panels.includes('source:'+uri));if(target&&sourceLocation?.id===target){v.docking.layout.dock('source:'+uri,target,'bottom');let split;v.docking.layout.visit(n=>{if(n.type==='split'&&n.first.id===target)split=n;});if(split)v.docking.layout.resize(split.id,.64,{history:false});}v.docking.activate('designer');}
  if(mode==='code'){if(uri)openDesignerSource(v,uri);else v.docking.activate('designer-source');}
  if(mode==='design'&&uri){const group=v.docking.layout.groups().find(g=>g.panels.includes('designer'));if(group)v.docking.layout.dock('source:'+uri,group.id,'center');v.docking.activate('designer');}
  this.renderSync();return mode;
 }
 renderSync(){if(!this.installed)return;const v=this.view;this.sync.innerHTML=v.sourceSync.renderControls();v.sourceSync.bindControls(this.sync);const state=v.sourceSync.snapshot();this.sync.dataset.state=state.state;this.sync.title=state.message;v.panel('designer').querySelectorAll('[data-design-view]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.designView===this.mode)));}
 renderSelection(){if(!this.installed)return;const v=this.view,preset=v.panel('designer').querySelector('[data-device-preset]'),dimensions=v.document.value.width+'x'+v.document.value.height;if(preset)preset.value=[...preset.options].some(o=>o.value===dimensions)?dimensions:'custom';const n=v.document.node();if(!n)return;const items=[];let current=n;for(let i=0;current&&i<100;i++){items.unshift(current);current=v.document.parent(current.id);}this.crumbs.innerHTML=`<span class="design-context-label">${v.live?'LIVE APP':'DOCUMENT'}</span>${items.map(n=>`<button data-crumb="${E(n.id)}" title="${E(n.type)}">${E(n.properties.Name||n.id)} <small>${E(n.type.split('.').at(-1))}</small></button>`).join('<span class="crumb-separator">›</span>')}<span class="panel-spacer"></span><span class="design-selection-count">${v.document.selection.length} selected</span>`;appendDesignSourceLocation(this.crumbs,v,v.sourceSync.session?.analysis,n);this.crumbs.querySelectorAll('[data-crumb]').forEach(b=>b.onclick=()=>v.document.select(b.dataset.crumb));}
 properties(){const v=this.view,root=v.panel('designer-properties'),list=root.querySelector('.design-property-list');if(!list)return;const rows=[...list.querySelectorAll('.design-property-row')],groups=new Map(),selected=v.document.selection.map(id=>v.document.node(id)),n=selected[0];
  for(const row of rows){const input=row.querySelector('[data-property]'),key=input?.dataset.property;if(!key)continue;const attached=/^(Row|Column|RowSpan|ColumnSpan|WrapRowSpan|WrapColumnSpan|Left|Top|ZIndex)$/.test(key);if(attached&&!v.propertySearch&&selected.every(item=>!Object.hasOwn(item.properties,key))){const parents=selected.map(item=>v.document.parent(item.id)?.type.split('.').at(-1));const relevant=key.startsWith('Wrap')?parents.some(t=>t==='VariableSizedWrapGrid'):/^(Row|Column)/.test(key)?parents.some(t=>t==='Grid'):parents.some(t=>t==='Canvas');if(!relevant)continue;}const group=category(key);if(!groups.has(group)){const details=root.ownerDocument.createElement('details');details.className='design-property-category';details.open=v.propertySearch!==''||(this.propertyGroups.get(group)??true);const summary=root.ownerDocument.createElement('summary');summary.textContent=group;details.append(summary);details.ontoggle=()=>{if(!v.propertySearch)this.propertyGroups.set(group,details.open);};groups.set(group,details);}groups.get(group).append(row);const schema=propertySchema(n.type)[key],resolved=resolvedProperties(v.document.value,n),mixed=selected.some(s=>JSON.stringify(resolvedProperties(v.document.value,s).properties[key])!==JSON.stringify(resolved.properties[key]));if(input.type==='checkbox')input.indeterminate=mixed;if(mixed&&input.tagName==='SELECT'){const option=root.ownerDocument.createElement('option');option.textContent='(Mixed)';option.value='';option.disabled=true;option.selected=true;input.prepend(option);}const origin=v.sourceSync.session?.analysis.bindings[n.id]?.properties[key];if(origin?.dynamic){input.disabled=true;row.classList.add('design-code-owned');row.title='Controlled by a dynamic C# expression. Edit the source to change this value.';row.querySelector('[data-clear]').disabled=true;}
   if(/(Background|Foreground|Fill|Stroke|BorderBrush)/.test(key)){const value=resolved.properties[key],color=value?.Color;if(color){const swatch=root.ownerDocument.createElement('span');swatch.className='design-color-swatch';swatch.style.backgroundColor=`rgba(${color.R},${color.G},${color.B},${color.A/255})`;row.querySelector('label').prepend(swatch);}}
   input.setAttribute('aria-label',key);input.onfocus=()=>{let help=root.querySelector('.design-property-help');if(!help){help=root.ownerDocument.createElement('div');help.className='design-property-help';root.append(help);}help.textContent=key+' · '+schema.type.split('.').at(-1)+' · '+(origin?.dynamic?'C# expression':mixed?'Mixed values':resolved.sources[key]??'Default');};
  }
  list.replaceChildren(...['Identity','Size & spacing','Placement','Appearance','Text & typography','Interaction','Other'].filter(k=>groups.has(k)).map(k=>groups.get(k)));
 }
 toolbox(){const v=this.view,root=v.panel('designer-toolbox').querySelector('.design-toolbox-list');if(!root)return;const fragment=root.ownerDocument.createDocumentFragment();let group=null;for(const el of [...root.children]){if(el.tagName==='H4'){group=root.ownerDocument.createElement('details');group.className='design-toolbox-category';group.open=v.search!==''||(this.toolboxGroups.get(el.textContent)??true);const name=el.textContent,s=root.ownerDocument.createElement('summary');s.textContent=name;group.append(s);group.ontoggle=()=>{if(!v.search)this.toolboxGroups.set(name,group.open);};fragment.append(group);}else{const category=group?.querySelector('summary')?.textContent??'Controls',span=el.querySelector('span');if(span)span.innerHTML=`<svg viewBox="0 0 16 16" aria-hidden="true">${shapes[category]??shapes.Controls}</svg>`;group?.append(el);}}root.replaceChildren(fragment);}
 rulers(){if(!this.installed)return;const v=this.view,h=v.panel('designer').querySelector('.design-ruler.horizontal');if(!h)return;const step=v.zoom<.5?200:100,offset=38-v.scroller.scrollLeft;h.innerHTML=Array.from({length:Math.ceil(v.document.value.width/step)+1},(_,i)=>`<span style="left:${offset+i*step*v.zoom}px">${i*step}</span>`).join('');h.style.backgroundSize=(step/10*v.zoom)+'px 100%';}
 refreshSource(){const v=this.view;if(v.state.panel==='designer-source')v.renderSource();this.renderSync();}
 source(el){const v=this.view,s=v.sourceSync.snapshot(),panel=el.ownerDocument.createElement('div');panel.className='design-source-link';panel.innerHTML=`<div class="panel-tools">${v.sourceSync.renderControls()}</div><p>${E(s.message)}</p>${s.uri?`<p><strong>${E(s.method)}</strong> · ${s.structuralEditable?'Declarative method: structure and properties can synchronize':'Protected code: only safe property edits synchronize'}</p>${s.warnings.length?`<details><summary>${s.warnings.length} protected expression(s)</summary>${s.warnings.map(w=>`<p>${E(w.node??'')} ${E(w.property??'')}: ${E(w.message)}</p>`).join('')}</details>`:''}`:'<p>Connect a source file to use the full C# editor alongside the design. Dynamic expressions are never executed by the preview.</p>'}`;el.prepend(panel);v.sourceSync.bindControls(panel);}
 dispose(){this.view.scroller?.removeEventListener('scroll',this.scroll);}
}
