import {escapeHtml as E} from '../../packages/editor/src/index.js';
/** Dockable, paged view of the actual executing assembly, independent of compiler output. */
export class DisassemblyTool {
  constructor({request,onBreakpoints=()=>{},onError=()=>{}}){this.request=request;this.onBreakpoints=onBreakpoints;this.onError=onError;this.reset();}
  reset(){this.generation=(this.generation??0)+1;this.methods=null;this.selected=null;this.page=0;this.follow=true;this.snapshot=null;this.requests=[];this.editing=null;}
  async render(host,snapshot){
    this.host=host;this.snapshot=snapshot;const generation=++this.generation;
    if(snapshot?.profile!=='managed-il'){host.innerHTML='<div class="empty-state"><div><b>MSIL instruction debugger</b><p>Open a DLL or EXE in Assembly Explorer and choose Debug IL. This panel displays the executing binary, not a stale source compilation.</p></div></div>';return;}
    try{
      this.methods??=await this.request('disassemblyMethods');if(generation!==this.generation)return;
      const frame=snapshot.frames.find(f=>f.id===snapshot.selectedFrameId)??snapshot.frames[0];
      if(this.follow&&frame){this.selected=frame.methodToken;const info=this.methods.find(m=>m.token===this.selected);this.page=Math.floor((frame.pc??0)/200);if(!info)this.selected=null;}
      this.selected??=this.methods[0]?.token;if(!this.selected){host.textContent='No executable methods';return;}
      const info=this.methods.find(m=>m.token===this.selected),reference=`il:${this.selected.toString(16).padStart(8,'0')}:00000000`;
      this.page=Math.max(0,Math.min(this.page,Math.ceil(info.count/200)-1));
      const rows=await this.request('disassemble',{reference,instructionOffset:this.page*200,instructionCount:200});if(generation!==this.generation)return;
      const paused=snapshot.state==='paused',breakpoints=snapshot.breakpoints??[];
      this.requests=breakpoints.filter(b=>!b.source).map(({instructionReference,condition,conditionMode,hitCondition,logMessage,enabled,oneShot})=>({instructionReference,condition,conditionMode,hitCondition,logMessage,enabled,oneShot}));
      host.innerHTML=`<div class="panel-tools"><select data-method aria-label="Executing assembly method">${this.methods.map(m=>`<option value="${m.token}" ${m.token===this.selected?'selected':''}>${E(m.name)}</option>`).join('')}</select><label><input type="checkbox" data-follow ${this.follow?'checked':''}> Follow frame</label><button data-page="-1" ${this.page===0?'disabled':''}>Previous</button><span>${this.page*200+1}–${this.page*200+rows.length} / ${info.count}</span><button data-page="1" ${(this.page+1)*200>=info.count?'disabled':''}>Next</button><button data-clear>Clear IL breakpoints</button><button data-reverse-step ${snapshot.state==='running'||!snapshot.history?.count?'disabled':''}>Step back</button><button data-reverse-continue ${snapshot.state==='running'||!snapshot.history?.count?'disabled':''}>Reverse continue</button></div>
        <div class="tool-page">${E(snapshot.reason?.description??snapshot.reason?.reason??snapshot.state)} · ${E(info.name)} · ${breakpoints.filter(b=>!b.source).length} instruction breakpoints. Breakpoint conditions and logpoints never execute methods. History: ${snapshot.history?.count??0} snapshots / ${Math.ceil((snapshot.history?.bytes??0)/1024)} KiB estimated; ${snapshot.history?.dropped??0} dropped.</div><details class="tool-page" ${snapshot.dataBreakpoints?.length?'open':''}><summary>Managed write breakpoints (${snapshot.dataBreakpoints?.length??0})</summary><p>Right-click a local, argument, or object/array child to watch its storage. Frame and allocation identities are checked.</p>${(snapshot.dataBreakpoints??[]).map((b,i)=>`<div data-write-breakpoint="${i}"><b>${E(b.kind)}[${b.index}]</b> ${b.frameId?'frame '+b.frameId:b.handle?'#'+b.handle+':'+b.generation:''} · ${b.hits} hits ${E(b.condition??'')} ${E(b.hitCondition??'')} ${E(b.message??'')} <button data-remove-write="${i}">Remove</button></div>`).join('')}<button data-clear-write ${!snapshot.dataBreakpoints?.length?'disabled':''}>Clear write breakpoints</button></details>
        <table class="data-table code-dump"><thead><tr><th>Break</th><th>Bytes</th><th>MSIL instruction</th><th>Actions</th></tr></thead><tbody>${rows.map((r,index)=>{const bp=breakpoints.find(b=>b.instructionReference===r.address);return `<tr data-instruction="${E(r.address)}" class="${frame?.instructionPointerReference===r.address?'instruction-current':''}"><td><button data-toggle="${index}" aria-label="Toggle breakpoint ${E(r.instruction.split(':')[0])}" aria-pressed="${!!bp}">${bp?(bp.enabled===false?'◌':'●'):'○'}</button></td><td class="offset">${E(r.instructionBytes)}</td><td class="op">${E(r.instruction)}</td><td><button data-run-to="${index}" ${!paused?'disabled':''}>Run to</button><button data-edit="${index}">Condition</button>${bp?`<small>${E(bp.condition??bp.logMessage??bp.hitCondition??'Always')}</small>`:''}</td></tr>`;}).join('')}</tbody></table><div data-condition-editor></div>`;
      host.querySelector('[data-method]').onchange=e=>{this.selected=Number(e.target.value);this.page=0;this.follow=false;this.render(host,this.snapshot);};
      host.querySelector('[data-follow]').onchange=e=>{this.follow=e.target.checked;this.render(host,this.snapshot);};
      for(const b of host.querySelectorAll('[data-page]'))b.onclick=()=>{this.page+=Number(b.dataset.page);this.follow=false;this.render(host,this.snapshot);};
      const save=async requests=>{try{const result=await this.request('instructionBreakpoints',{breakpoints:requests});const invalid=result.filter(b=>!b.verified);if(invalid.length)throw new Error(invalid.map(b=>b.message).join('; '));this.requests=requests;this.onBreakpoints(requests);}catch(e){this.onError(e);}};
      host.querySelector('[data-clear]').onclick=()=>save([]);
      for(const [selector,method]of [['[data-reverse-step]','stepBack'],['[data-reverse-continue]','reverseContinue']])host.querySelector(selector).onclick=async()=>{try{await this.request(method);}catch(error){this.onError(error);}};
      const saveData=async breakpoints=>{try{const result=await this.request('dataBreakpoints',{breakpoints});const invalid=result.filter(b=>!b.verified);if(invalid.length)throw new Error(invalid.map(b=>b.message).join('; '));}catch(error){this.onError(error);}};
      host.querySelector('[data-clear-write]').onclick=()=>saveData([]);
      for(const button of host.querySelectorAll('[data-remove-write]'))button.onclick=()=>saveData((snapshot.dataBreakpoints??[]).filter((_,i)=>i!==Number(button.dataset.removeWrite)));

      for(const b of host.querySelectorAll('[data-toggle]'))b.onclick=()=>{const reference=rows[Number(b.dataset.toggle)].address;save(this.requests.some(r=>r.instructionReference===reference)?this.requests.filter(r=>r.instructionReference!==reference):[...this.requests,{instructionReference:reference}]);};
      for(const b of host.querySelectorAll('[data-run-to]'))b.onclick=async()=>{try{await this.request('runToInstruction',{reference:rows[Number(b.dataset.runTo)].address});}catch(e){this.onError(e);}};
      for(const b of host.querySelectorAll('[data-edit]'))b.onclick=()=>{const reference=rows[Number(b.dataset.edit)].address,bp=this.requests.find(r=>r.instructionReference===reference)??{},form=host.querySelector('[data-condition-editor]');form.innerHTML=`<form class="tool-page"><b>${E(reference)}</b><label>Condition <input name="condition" aria-label="IL breakpoint condition" value="${E(bp.condition??'')}" maxlength="16384"></label><label>Hit count <input name="hitCondition" value="${E(bp.hitCondition??'')}" placeholder="N, >=N, %N"></label><label>Log message <input name="logMessage" value="${E(bp.logMessage??'')}" placeholder="value {arg0}"></label><button type="submit">Save instruction breakpoint</button></form>`;form.querySelector('form').onsubmit=e=>{e.preventDefault();save([...this.requests.filter(r=>r.instructionReference!==reference),{...bp,instructionReference:reference,condition:e.target.elements.condition.value||undefined,hitCondition:e.target.elements.hitCondition.value||undefined,logMessage:e.target.elements.logMessage.value||undefined}]);};form.scrollIntoView({block:'nearest'});};
    }catch(error){if(generation===this.generation)host.innerHTML=`<div class="tool-page">${E(error.message)}</div>`;}
  }
}
