import {createNativeBuildSettings} from './workbench/lazy-features/native-settings.js';
import {runNativeOperation,acceptNativeJob,cancelNativeJob,disposeNativeOperations,
 nativeJobTerminal as terminal} from './workbench/native-operation.js';
import { MSBuildClient, parsePropertyLines, inspectSlnx, createWorkspaceSlnx } from '@sharpforge/msbuild';
import { escapeHtml as E } from '@sharpforge/editor';
import { createCsproj } from '@sharpforge/project-system';
const formatBytes=n=>n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KiB':(n/1048576).toFixed(1)+' MiB';
/** Native build UI has a separate lifecycle from the bounded browser compiler. */
export class MSBuildTools {
 constructor({onAttach,onOpenSource,getSourceChanges,onSaved,onJob,onJobFailure,onAssembly,onSelectPanel,onError,onWorkspace,settings,buffers}={}){
  Object.assign(this,{onAttach,onOpenSource,getSourceChanges,onSaved,onJob,onJobFailure,onAssembly,onSelectPanel,onError,onWorkspace});
  this.client=null;this.capabilities=null;this.workspace=null;this.job=null;this.cursor=0;this.log='';this.buffers=buffers??new Map();this.sourcePath=null;this.hosts=new Map();this.inspection=null;this.attached=false;this.busy=false;this.disposed=false;this.settings=settings??createNativeBuildSettings();
 }
 async autoConnect(){let client;try{client=MSBuildClient.fromLocation();}catch(error){this.onError?.(error);return;}if(client){this.onSelectPanel?.('msbuild');try{await this.connect(client);}catch(error){this.onError?.(error);}}}
 async connect(client=this.client){if(!client)throw new Error('Start the local host and open its printed Studio URL.');if(this.busy)throw new Error('Finish the active operation before reconnecting');this.client=client;this.capabilities=await client.connect();this.workspace=await client.workspace();this.settings.project=this.workspace.solutions[0]??this.workspace.projects[0]??'';this.settings.trusted=false;this.renderBuild(true);this.onWorkspace?.(this.workspace);return this.snapshot();}
 snapshot(){return {connected:!!this.capabilities,attached:this.attached,capabilities:this.capabilities,workspace:this.workspace,job:this.job,inspection:this.inspection,busy:this.busy,sourcePath:this.sourcePath,dirtyBuffers:[...this.buffers.values()].filter(b=>b.text!==b.baseline).map(b=>b.path)};}
 async attach(){if(!this.client||!this.workspace)throw new Error('Connect the native host first');if(this.attached)return;await this.onAttach?.(this.workspace);this.attached=true;this.renderBuild();}
 async refresh(){if(!this.client)throw new Error('No local host is connected');this.workspace=await this.client.workspace();this.onWorkspace?.(this.workspace);this.renderBuild(true);return this.workspace;}
 async open(path,line=null,column=1){if(!this.client)throw new Error('No local host is connected');await this.attach();if(/\.cs$/i.test(path)){const file=await this.client.read(path);await this.onOpenSource?.(file,line,column);return file;}
  let file=this.buffers.get(path);if(!file){file=await this.client.read(path);file={...file,baseline:file.text};this.buffers.set(path,file);}this.sourcePath=path;this.onSelectPanel?.('project-source');this.renderSource(true);return file;
 }
 sourceChanges(){return [...this.buffers.values()].filter(f=>f.text!==f.baseline||f.hash===null).map(f=>({path:f.path,text:f.text,expectedHash:f.hash}));}
 async save(){if(!this.client)throw new Error('No local host is connected');if(this.job&&!terminal(this.job.status))throw new Error('Stop the native operation before saving inputs');const changes=[...(this.getSourceChanges?.()??[]),...this.sourceChanges()];if(!changes.length)return {written:[]};
  const reconcile=written=>{for(const saved of written??[]){const change=changes.find(c=>c.path===saved.path);if(!change)continue;const buffer=this.buffers.get(saved.path);if(buffer){buffer.hash=saved.hash;buffer.baseline=change.text;}this.onSaved?.(saved,change);}this.renderSource();};
  let report;try{report=await this.client.save(changes);}catch(error){reconcile(error.written);throw error;}
  reconcile(report.written);await this.refresh();return report;
 }
 request(action){const s=this.settings;let args=[];if(s.arguments.trim()){args=JSON.parse(s.arguments);if(!Array.isArray(args))throw new Error('Advanced arguments must be a JSON string array');}
  return {action,project:s.project,configuration:s.configuration,platform:s.platform,framework:s.framework,runtime:s.runtime,properties:parsePropertyLines(s.properties),targets:s.targets.split(/[;,]/).map(x=>x.trim()).filter(Boolean),resultTargets:s.resultTargets.split(/[;,]/).map(x=>x.trim()).filter(Boolean),arguments:args,verbosity:s.verbosity,maxNodes:Number(s.maxNodes),restore:s.restore,binaryLog:s.binaryLog,graphBuild:s.graphBuild,trusted:s.trusted};
 }
 run(action='build'){return runNativeOperation(this,action);}
 accept(job,options){return acceptNativeJob(this,job,options);}
 cancel(){return cancelNativeJob(this);}
 inspectSolution(){const buffer=this.buffers.get(this.sourcePath);if(!buffer||!/\.slnx$/i.test(buffer.path))throw new Error('Open a .slnx file first');this.inspection={project:buffer.path,action:'solution-structure',result:{Solution:inspectSlnx(buffer.text,{path:buffer.path})}};this.onSelectPanel?.('msbuild-inspector');this.renderInspector();return this.inspection;}
 async artifact(file,{inspect=false}={}){if(!this.job)throw new Error('No build output');const bytes=await this.client.artifact(this.job.id,file.path);if(inspect){await this.onAssembly?.(bytes,file.path);return;}const blob=new Blob([bytes],{type:'application/octet-stream'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=file.path.split('/').at(-1);a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 render(panel,el){this.hosts.set(panel,el);if(panel==='msbuild')this.renderBuild();else if(panel==='msbuild-inspector')this.renderInspector();else if(panel==='project-source')this.renderSource();}
 renderBuild(force=false){const el=this.hosts.get('msbuild');if(!el)return;
  if(force||!el.querySelector('.msbuild-tool')){
   const s=this.settings,workspace=this.workspace;el.innerHTML=`<div class="tool-page msbuild-tool"><div class="native-heading"><h2>MSBuild</h2><span class="native-engine-badge">LOCAL SDK ENGINE</span></div><p class="native-summary">Build real project and solution outputs. Browser preview compilation remains a separate engine.</p>${this.capabilities?`<div class="notice ${this.capabilities.available?'':'warning'}"><b>${E(this.capabilities.available?this.capabilities.version:'SDK unavailable')}</b><br>${E(workspace?.root??'')}${this.capabilities.error?'<br>'+E(this.capabilities.error):''}</div>`:`<div class="notice">Start the local host, then open its printed URL. A static website cannot run native MSBuild.</div><pre class="native-command">node packages/msbuild/bin/sharpforge-msbuild.js serve \\\n  --root /path/to/workspace --studio dist --trust-projects</pre><p>The local SDK/MSBuild and its workloads must already be installed. The session token stays in memory; reconnect by opening the host URL again.</p>`}
   <div class="tool-actions"><button class="button" data-command="nativeBuildLayout">Build layout</button><button class="button" data-native-connect>Reconnect / refresh</button><button class="button" data-native-attach ${workspace?'':'disabled'}>Use native workspace</button><button class="button" data-native-save ${workspace?'':'disabled'}>Save all native files</button></div>
   <label class="tool-field">Project / solution <select data-native-setting="project">${[...(workspace?.solutions??[]),...(workspace?.projects??[])].map(p=>`<option value="${E(p)}" ${s.project===p?'selected':''}>${E(p)}</option>`).join('')}</select></label>
   <div class="native-form-grid">${[['configuration','Configuration'],['platform','Platform (blank = default)'],['framework','Target framework (blank = all)'],['runtime','Runtime identifier (optional)']].map(([k,label])=>`<label class="tool-field">${label}<input data-native-setting="${k}" value="${E(s[k])}" maxlength="256"></label>`).join('')}</div>
   <details><summary>Properties, targets and advanced switches</summary><label class="tool-field">Global properties — one Name=Value per line<textarea data-native-setting="properties" rows="4" spellcheck="false">${E(s.properties)}</textarea></label><label class="tool-field">Custom targets, separated by semicolons<input data-native-setting="targets" value="${E(s.targets)}"></label><label class="tool-field">Target results to query (also executes these targets)<input data-native-setting="resultTargets" value="${E(s.resultTargets)}"></label><label class="tool-field">Extra MSBuild switches — JSON array, not shell text<textarea data-native-setting="arguments" rows="2" spellcheck="false" placeholder='["-warnAsError"]'>${E(s.arguments)}</textarea></label><div class="native-form-grid"><label class="tool-field">Verbosity<select data-native-setting="verbosity">${['quiet','minimal','normal','detailed','diagnostic'].map(v=>`<option ${v===s.verbosity?'selected':''}>${v}</option>`).join('')}</select></label><label class="tool-field">Parallel nodes<input type="number" min="1" max="64" data-native-setting="maxNodes" value="${E(s.maxNodes)}"></label></div></details>
   <div class="native-checks">${[['restore','Restore before build'],['save','Save before operation'],['binaryLog','Capture binary log (may contain secrets)'],['graphBuild','Graph build']].map(([k,label])=>`<label><input type="checkbox" data-native-setting="${k}" ${s[k]?'checked':''}> ${label}</label>`).join('')}</div>
   <label class="native-trust"><input type="checkbox" data-native-setting="trusted" ${s.trusted?'checked':''}> I trust this workspace. Builds, restore, imports and evaluation may execute local code with my OS permissions.</label>
   <div class="tool-actions native-build-actions">${[['build','Build'],['rebuild','Rebuild'],['clean','Clean'],['restore','Restore'],['pack','Pack'],['publish','Publish'],['test','Test (VSTest)'],['target','Run target'],['evaluate','Evaluate'],['targets','List targets'],['preprocess','Preprocess']].map(([a,label])=>`<button class="button" data-native-action="${a}">${label}</button>`).join('')}<button class="button" data-native-cancel>Cancel</button></div>
   <p class="native-operation-status" role="status"></p><details><summary>Actual invocation</summary><pre class="native-invocation"></pre></details><pre class="native-build-output" aria-label="Native MSBuild output" tabindex="0"></pre><div class="native-diagnostics"></div><div class="native-artifacts"></div></div>`;
   for(const control of el.querySelectorAll('[data-native-setting]'))control.addEventListener('input',()=>{this.settings[control.dataset.nativeSetting]=control.type==='checkbox'?control.checked:control.value;});
   const act=fn=>Promise.resolve().then(fn).catch(error=>this.onError?.(error));for(const button of el.querySelectorAll('[data-native-action]'))button.onclick=()=>act(()=>this.run(button.dataset.nativeAction));
   el.querySelector('[data-native-cancel]').onclick=()=>act(()=>this.cancel());el.querySelector('[data-native-connect]').onclick=()=>act(()=>this.client?this.refresh():this.connect());el.querySelector('[data-native-attach]').onclick=()=>act(()=>this.attach());el.querySelector('[data-native-save]').onclick=()=>act(()=>this.save());
  }
  for(const b of el.querySelectorAll('[data-native-action]'))b.disabled=this.busy||!this.capabilities?.available;
  for(const c of el.querySelectorAll('[data-native-setting]'))c.disabled=this.busy;
  el.querySelector('[data-native-cancel]').disabled=!this.job||terminal(this.job.status);
  const job=this.job;el.querySelector('.native-operation-status').textContent=job?`${job.request.action.toUpperCase()} · ${job.status}${job.exitCode!==null?' · exit '+job.exitCode:''}${job.error?' · '+job.error:''}`:this.attached?'Native workspace active. No operation has run.':'No native operation has run.';
  el.querySelector('.native-invocation').textContent=job?JSON.stringify(job.invocation,null,2):'';
  const output=el.querySelector('.native-build-output'),follow=output.scrollHeight-output.scrollTop-output.clientHeight<40;output.textContent=this.log;if(follow)output.scrollTop=output.scrollHeight;
  const diagnostics=el.querySelector('.native-diagnostics');diagnostics.innerHTML=job?.diagnostics.length?'<h3>Build diagnostics</h3>'+job.diagnostics.map((d,i)=>`<button class="native-diagnostic ${E(d.severity)}" data-native-diagnostic="${i}"><b>${E(d.severity)} ${E(d.code)}</b> ${E(d.file??d.project??'MSBuild')}${d.line?`:${d.line}:${d.column}`:''}<br>${E(d.message)}</button>`).join(''):'';
  for(const b of diagnostics.querySelectorAll('[data-native-diagnostic]'))b.onclick=()=>{const d=job.diagnostics[Number(b.dataset.nativeDiagnostic)];if(d.workspacePath)this.open(d.workspacePath,d.line,d.column).catch(e=>this.onError?.(e));};
  const artifacts=el.querySelector('.native-artifacts');artifacts.innerHTML=job?.artifacts.length?'<h3>Logs and workspace outputs</h3><p>Output discovery includes existing bin files; timestamps are shown. Building does not imply browser CLR compatibility.</p>'+job.artifacts.map((a,i)=>`<div class="native-artifact"><span>${E(a.path)}<small>${formatBytes(a.size)}${a.modified?' · '+E(a.modified):''}</small></span><button class="button" data-native-download="${i}">Save</button>${/\.(dll|exe)$/i.test(a.path)?`<button class="button" data-native-inspect="${i}">Inspect IL</button>`:''}</div>`).join(''):'';
  for(const [attribute,inspect]of [['nativeDownload',false],['nativeInspect',true]])for(const b of artifacts.querySelectorAll(inspect?'[data-native-inspect]':'[data-native-download]'))b.onclick=()=>this.artifact(job.artifacts[Number(b.dataset[attribute])],{inspect}).catch(e=>this.onError?.(e));
 }
 renderInspector(){const el=this.hosts.get('msbuild-inspector');if(!el)return;const current=this.inspection;if(!current){el.innerHTML='<div class="tool-page"><h2>MSBuild Evaluation</h2><p>Run Evaluate on a project, List targets, or Preprocess from the MSBuild tool. These use the installed engine, including SDK and package imports.</p><p>Select a .csproj for properties/items. Build a .slnx directly for native solution configuration mapping.</p></div>';return;}
  const r=current.result;el.innerHTML=`<div class="tool-page msbuild-inspector"><h2>${E(current.project)}</h2><p>${E(current.action)} · ${current.action==='solution-structure'?'data-only structure, not evaluated mappings':'native evaluated result'}</p><input class="native-inspection-filter" aria-label="Filter evaluated properties and items" placeholder="Filter properties and items"><div class="native-evaluation-content"></div></div>`;
  const render=()=>{const filter=el.querySelector('.native-inspection-filter').value.toLowerCase();let html='';if(r.Properties)html+='<h3>Evaluated properties</h3><table class="data-table">'+Object.entries(r.Properties).filter(([k,v])=>(k+' '+v).toLowerCase().includes(filter)).map(([k,v])=>`<tr><td>${E(k)}</td><td class="native-property-value">${E(v)}</td></tr>`).join('')+'</table>';
   for(const [kind,items]of Object.entries(r.Items??{})){const list=items.filter(item=>(kind+JSON.stringify(item)).toLowerCase().includes(filter));if(!list.length)continue;html+=`<details open><summary>${E(kind)} (${list.length})</summary>`+list.slice(0,500).map(item=>`<details><summary>${E(item.Identity??'item')}</summary><pre>${E(JSON.stringify(item,null,2))}</pre></details>`).join('')+(list.length>500?'<p>Showing 500 items; narrow the filter.</p>':'')+'</details>';}
   for(const key of ['targetsText','preprocessedText','TargetResults','Solution'])if(r[key])html+=`<h3>${E(key)}</h3><pre class="native-expanded-source">${E(typeof r[key]==='string'?r[key]:JSON.stringify(r[key],null,2))}</pre>`;
   el.querySelector('.native-evaluation-content').innerHTML=html||'<p>No values match.</p>';};el.querySelector('.native-inspection-filter').oninput=render;render();
 }
 renderSource(force=false){const el=this.hosts.get('project-source');if(!el)return;
  if(force||!el.querySelector('.native-project-source')){const buffer=this.buffers.get(this.sourcePath),files=(this.workspace?.files??[]).filter(f=>!['source'].includes(f.kind));
   el.innerHTML=`<div class="tool-page native-project-source"><h2>Project / Solution Source</h2><p>Edit .csproj, .slnx, imported props/targets and configuration files without flattening imports or dropping comments. Save uses a disk hash conflict check.</p><select class="native-source-picker" aria-label="Native project file"><option value="">Choose a file…</option>${files.map(f=>`<option value="${E(f.path)}" ${f.path===this.sourcePath?'selected':''}>${E(f.path)}</option>`).join('')}</select><div class="tool-actions"><button class="button" data-native-source-save>Save all changes</button><button class="button" data-native-solution-inspect ${/\.slnx$/i.test(this.sourcePath??'')?'':'disabled'}>Inspect solution structure</button><button class="button" data-native-new-project>New .csproj</button><button class="button" data-native-new-solution>New .slnx</button></div><p class="native-source-status" role="status"></p><textarea class="native-xml-editor" aria-label="Native project XML or configuration source" spellcheck="false" ${buffer?'':'disabled'}>${E(buffer?.text??'')}</textarea></div>`;
   el.querySelector('.native-source-picker').onchange=e=>{if(e.target.value)this.open(e.target.value).catch(x=>this.onError?.(x));};el.querySelector('[data-native-source-save]').onclick=()=>this.save().catch(x=>this.onError?.(x));
   el.querySelector('[data-native-solution-inspect]').onclick=()=>{try{this.inspectSolution();}catch(e){this.onError?.(e);}};
   const area=el.querySelector('.native-xml-editor');area.oninput=()=>{const current=this.buffers.get(this.sourcePath);if(current){current.text=area.value;this.renderSource();}};area.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();e.stopPropagation();this.save().catch(x=>this.onError?.(x));}});
   for(const [selector,extension,create]of [['[data-native-new-project]','.csproj',()=>createCsproj()],['[data-native-new-solution]','.slnx',name=>createWorkspaceSlnx(name,this.workspace?.projects??[])]])el.querySelector(selector).onclick=()=>{if(!this.client)return this.onError?.(new Error('Connect the local host first'));const name=globalThis.prompt('New workspace-relative filename (parent folder must exist)','New'+extension);if(!name)return;if(!name.toLowerCase().endsWith(extension))return this.onError?.(new Error('Use '+extension));if(this.workspace.files.some(f=>f.path===name)||this.buffers.has(name))return this.onError?.(new Error('File already exists'));this.buffers.set(name,{path:name,text:create(name),baseline:'',hash:null});this.sourcePath=name;this.renderSource(true);};
  }
  const b=this.buffers.get(this.sourcePath);el.querySelector('.native-source-status').textContent=b?`${b.path} · ${b.text!==b.baseline||b.hash===null?'unsaved changes':'matches loaded disk snapshot'}`:'No file selected.';
 }
 renderTree(el,query=''){const files=(this.workspace?.files??[]).filter(f=>f.path.toLowerCase().includes(query)).slice(0,500);el.innerHTML='<div class="native-tree-caption">LOCAL MSBUILD WORKSPACE</div>'+files.map(f=>`<button class="file-row" data-native-file="${E(f.path)}"><span class="file-icon">${f.kind==='source'?'C#':f.kind==='project'?'⚙':f.kind==='solution'?'◇':'≡'}</span><span>${E(f.path)}</span></button>`).join('')+(files.length===500?'<p>Showing 500 files. Use the filter to narrow the list.</p>':'');for(const b of el.querySelectorAll('[data-native-file]'))b.onclick=()=>this.open(b.dataset.nativeFile).catch(e=>this.onError?.(e));}
 dispose(){return disposeNativeOperations(this);}
}
