import {storage} from './settings/storage.js';
import {projectTemplates,itemTemplates,createProjectPlan,createItemPlan,defaultNamespace,searchTemplates} from '../../packages/templates/src/index.js';
import {workspaceCandidates} from '../../packages/project-system/src/index.js';
import {escapeHtml as E} from '../../packages/editor/src/index.js';
const dir=p=>p?.includes('/')?p.slice(0,p.lastIndexOf('/')):'',leaf=p=>p?.split('/').at(-1)??'';
/** The UI only prepares plans. All changes go through the workspace transaction boundary. */
export class ProjectWizard {
 constructor(host){this.host=host;this.active=false;this.recent=[];try{const stored=JSON.parse(storage.getItem('sharpforge.templates.recent'));this.recent=Array.isArray(stored)?stored.filter(x=>typeof x==='string'&&[...projectTemplates,...itemTemplates].some(t=>t.id===x)).slice(0,8):[];}catch{}}
 remember(id){this.recent=[id,...this.recent.filter(x=>x!==id)].slice(0,8);try{storage.setItem('sharpforge.templates.recent',JSON.stringify(this.recent));}catch{}}
 openProject({add=false,node=null}={}){return this.open({kind:'project',add,node});}
 openItem(node=null){return this.open({kind:'item',add:true,node});}
 async open({kind,add,node}){
  if(this.active)throw new Error('Complete or cancel the active wizard first');const context=this.host.context();if(context.readOnly)throw new Error('Stop debugging before creating files');this.active=true;
  const candidate=node?.project??(node?.kind==='project'?node.path:!node?context.startup:null),projectPath=candidate?.endsWith('.csproj')?candidate:null,project=context.snapshot?.projects?.find(p=>p.path===projectPath),folder=kind==='item'?(node?.kind==='folder'?node.path:node?.kind==='source'||node?.kind==='file'?dir(node.path):dir(projectPath)):'';
  const values={projectName:'Application',solutionName:'Application',namespace:kind==='project'?'Application':project?.properties?.rootnamespace??defaultNamespace(project?.name??'Application'),location:folder,framework:'net10.0',sameDirectory:false,checked:false,solutionMode:add&&context.solutionPath?'existing':'new',destination:add&&context.native?'native':'browser',name:'Class1.cs'};
  let selected=kind==='item'?'class':'console',step=0,query='',category='',language='',finished=false,busy=false,preview=null,lastName=values.projectName;
  const finish=value=>{if(finished)return;finished=true;this.active=false;this.host.closeModal();resolve(value);};let resolve;const result=new Promise(r=>resolve=r);
  const buildPlan=()=>{
   const current=this.host.context();if(current.identity!==context.identity)throw new Error('Workspace changed while the wizard was open; cancel and reopen it');
   const existing=add||values.destination==='native'?[...current.records,...current.folders.map(path=>({path,directory:true}))]:[];
   if(kind==='item'){const text=projectPath?current.records.find(r=>r.path===projectPath)?.text:undefined;return createItemPlan(selected,{...values,folder:values.location,projectPath,projectText:text??null,existing});}
   return createProjectPlan(selected,{...values,solutionPath:values.solutionMode==='existing'?context.solutionPath:null,solutionText:values.solutionMode==='existing'?current.records.find(f=>f.path===context.solutionPath)?.text:null,solutionFolder:node?.solutionFolder,existing});
  };
  const render=()=>{
   const templates=kind==='item'?itemTemplates:projectTemplates,template=templates.find(t=>t.id===selected);
   const title=kind==='item'?'Add New Item':add?'Add a new project':'Create a new project';
   const categories=[...new Set(templates.map(t=>t.category))],languages=[...new Set(templates.map(t=>t.language))];
   let body=`<div class="project-wizard" data-wizard-kind="${kind}" data-wizard-step="${step}"><div class="wizard-steps"><span class="${step===0?'current':''}">1&nbsp; Choose a template</span><span>›</span><span class="${step===1?'current':''}">2&nbsp; Configure &amp; preview</span></div>`;
   if(step===0)body+=`<div class="wizard-filter"><input id="wizard-search" type="search" placeholder="Search templates (Alt+S)" aria-label="Search templates" value="${E(query)}" autofocus><select id="wizard-language" aria-label="Template language"><option value="">All languages</option>${languages.map(c=>`<option ${c===language?'selected':''}>${E(c)}</option>`).join('')}</select><select id="wizard-category" aria-label="Project type"><option value="">All project types</option>${categories.map(c=>`<option ${c===category?'selected':''}>${E(c)}</option>`).join('')}</select></div><div class="wizard-template-layout"><div class="wizard-template-list" id="wizard-template-list" role="listbox" aria-label="Supported templates" tabindex="0"></div><aside id="wizard-description" class="wizard-description"></aside></div><p class="wizard-boundary">Templates target the implemented C# / WinUI web profile. Native Windows App SDK, WPF, ASP.NET, MAUI, C++, and package-based test frameworks are not silently substituted.</p>`;
   else{
    body+=`<div class="wizard-config"><div class="wizard-fields"><h3>${E(template.name)}</h3>`;
    if(kind==='project')body+=`<label>Project name<input id="wizard-project-name" value="${E(values.projectName)}" autofocus></label><label>Solution name<input id="wizard-solution-name" value="${E(values.solutionName)}" ${values.solutionMode==='existing'?'disabled':''}></label><label>Namespace<input id="wizard-namespace" value="${E(values.namespace)}"></label><label>Location inside workspace<input id="wizard-location" value="${E(values.location)}" placeholder="Workspace root"></label><div class="wizard-row"><label>Solution<select id="wizard-solution-mode"><option value="new" ${values.solutionMode==='new'?'selected':''}>Create new .slnx</option>${add&&context.solutionPath?`<option value="existing" ${values.solutionMode==='existing'?'selected':''}>Add to current solution</option>`:''}<option value="none" ${values.solutionMode==='none'?'selected':''}>Project only</option></select></label><label>Target framework<select id="wizard-framework">${['net10.0','net9.0','net8.0',...(['class-library','empty-project','winui-controls-library'].includes(selected)?['netstandard2.0']:[])].map(f=>`<option ${f===values.framework?'selected':''}>${f}</option>`).join('')}</select></label></div><label class="wizard-check"><input id="wizard-same-directory" type="checkbox" ${values.sameDirectory?'checked':''}> Place project and solution in the same directory</label><label class="wizard-check"><input id="wizard-checked" type="checkbox" ${values.checked?'checked':''}> Check arithmetic overflow</label><p class="wizard-destination">${add?context.native?'Destination: connected native workspace (real disk files)':'Destination: current browser workspace':'Destination: new browser workspace. Save as ZIP or save to an empty disk folder after creation.'}</p>`;
    else body+=`<label>Item name<input id="wizard-item-name" value="${E(values.name)}" autofocus></label><label>Namespace<input id="wizard-namespace" value="${E(values.namespace)}" ${template.language!=='C#'?'disabled':''}></label><label>Location inside workspace<input id="wizard-location" value="${E(values.location)}" placeholder="Workspace root"></label><p class="wizard-destination">${projectPath?'Project: '+E(projectPath):'Loose workspace item (not implicitly added to a project)'}</p>`;
    body+=`<div class="wizard-errors" id="wizard-errors" role="alert"></div><div class="wizard-warnings" id="wizard-warnings"></div></div><div class="wizard-preview"><div class="wizard-preview-head">Files to create <span id="wizard-file-count"></span></div><div class="wizard-preview-body"><div id="wizard-files" class="wizard-files" role="list" aria-label="Files to create"></div><pre id="wizard-code" tabindex="0" aria-label="Generated source preview"></pre></div></div></div>`;
   }
   body+='</div>';
   // showModal closes the previous modal; detach its onClose during a wizard step transition.
   this.host.showModal(title,body,{wide:true,onClose:()=>finish(null),footer:`<button id="wizard-cancel">Cancel</button><span class="wizard-spacer"></span>${step?'<button id="wizard-back">Back</button>':''}<button id="wizard-next" class="primary">${step?(kind==='item'?'Add':'Create'):'Next'}</button>`});
   const modal=document.querySelector('#modal'),$=s=>modal.querySelector(s);modal.classList.add('wizard-modal');
   $('#wizard-cancel').onclick=()=>finish(null);$('#wizard-back')?.addEventListener('click',()=>{step=0;render();});
   const describe=()=>{const t=templates.find(t=>t.id===selected),d=$('#wizard-description');if(d)d.innerHTML=`<span class="wizard-large-icon">${E(t.icon??(t.winui?'▣':'C#'))}</span><h3>${E(t.name)}</h3><p>${E(t.description)}</p><div class="wizard-tags"><span>${E(t.language)}</span><span>${E(t.category)}</span><span>${t.winui?'HTML / JS / GPU fallback':'Browser managed VM'}</span></div>${t.winui?'<p>Code-first components expose <code>.View</code>. No XAML loading or native WinUI inheritance is implied.</p>':t.nativeCompatible?'<p>SDK-style files are also suitable for review/build with an installed .NET toolchain.</p>':''}<p>All generated files can be inspected before creation.</p>`;};
   const drawList=()=>{const filtered=searchTemplates({kind,query,category,language}),list=$('#wizard-template-list');if(!filtered.some(t=>t.id===selected))selected=filtered[0]?.id??selected;list.innerHTML=filtered.map(t=>`<button type="button" class="wizard-template ${t.id===selected?'selected':''}" role="option" aria-selected="${t.id===selected}" data-template="${t.id}"><span class="wizard-template-icon">${E(t.icon??(t.winui?'▣':'C#'))}</span><span><b>${E(t.name)}</b><small>${E(t.description)}</small><span class="wizard-template-tags">${E(t.language)} &nbsp;·&nbsp; ${E(t.category)}${this.recent.includes(t.id)?' &nbsp;·&nbsp; Recent':''}</span></span></button>`).join('')||'<p class="wizard-empty">No supported templates match these filters.</p>';$('#wizard-next').disabled=!filtered.length;for(const button of list.querySelectorAll('[data-template]')){button.onclick=()=>{selected=button.dataset.template;for(const b of list.querySelectorAll('[data-template]')){b.classList.toggle('selected',b===button);b.setAttribute('aria-selected',String(b===button));}describe();};button.ondblclick=()=>next();}describe();};
   const updatePreview=()=>{try{preview=buildPlan();$('#wizard-errors').textContent='';$('#wizard-next').disabled=false;$('#wizard-warnings').textContent=preview.warnings.join(' ');$('#wizard-file-count').textContent=preview.records.length+' new'+(preview.modifications?.length?' · '+preview.modifications.length+' updated':'');const files=[...preview.records.map(f=>({...f,action:'Create'})),...(preview.modifications??[]).map(f=>({...f,action:'Update'}))];$('#wizard-files').innerHTML=files.map((f,i)=>`<button type="button" data-preview-file="${i}"><span>${E(f.action)}</span>${E(f.path)}</button>`).join('')+(preview.folders??[]).map(p=>`<div class="wizard-folder">▰ ${E(p)}/</div>`).join('');const show=i=>{$('#wizard-code').textContent=files[i]?.text??'';};for(const b of $('#wizard-files').querySelectorAll('button'))b.onclick=()=>show(Number(b.dataset.previewFile));show(0);}catch(error){preview=null;$('#wizard-errors').textContent=error.message;$('#wizard-next').disabled=true;$('#wizard-files').innerHTML='';$('#wizard-code').textContent='';}};
   const next=async()=>{if(busy)return;if(step===0){const t=templates.find(t=>t.id===selected);if(kind==='item')values.name=t.fileName;step=1;render();return;}try{preview=buildPlan();busy=true;this.host.lockModal?.(true);$('#modal-close').disabled=true;$('#wizard-next').disabled=true;$('#wizard-cancel').disabled=true;$('#wizard-back').disabled=true;$('#wizard-next').textContent='Creating…';await this.host.commitPlan(preview,{add,kind,context,node,destination:values.destination});this.remember(selected);this.host.lockModal?.(false);finish(preview);}catch(error){busy=false;this.host.lockModal?.(false);$('#modal-close').disabled=false;$('#wizard-errors').textContent=error.message;$('#wizard-next').disabled=false;$('#wizard-next').textContent=kind==='item'?'Add':'Create';$('#wizard-cancel').disabled=false;$('#wizard-back').disabled=false;}};
   $('#wizard-next').onclick=next;
   if(step===0){$('#wizard-search').oninput=e=>{query=e.target.value;drawList();};$('#wizard-category').onchange=e=>{category=e.target.value;drawList();};$('#wizard-language').onchange=e=>{language=e.target.value;drawList();};$('#wizard-template-list').onkeydown=e=>{if(!['ArrowDown','ArrowUp','Home','End','Enter'].includes(e.key))return;e.preventDefault();const filtered=searchTemplates({kind,query,category,language});if(e.key==='Enter'){next();return;}let i=filtered.findIndex(t=>t.id===selected);i=e.key==='Home'?0:e.key==='End'?filtered.length-1:Math.max(0,Math.min(filtered.length-1,i+(e.key==='ArrowDown'?1:-1)));if(filtered[i])selected=filtered[i].id;drawList();$(`[data-template="${selected}"]`)?.scrollIntoView({block:'nearest'});};drawList();}
   else{for(const [id,key]of [['wizard-project-name','projectName'],['wizard-solution-name','solutionName'],['wizard-namespace','namespace'],['wizard-location','location'],['wizard-framework','framework'],['wizard-solution-mode','solutionMode'],['wizard-item-name','name']]){const field=$('#'+id);if(!field)continue;field.addEventListener(field.tagName==='SELECT'?'change':'input',e=>{values[key]=e.target.value;if(key==='projectName'){if(values.solutionName===lastName){values.solutionName=values.projectName;$('#wizard-solution-name').value=values.solutionName;}if(values.namespace===defaultNamespace(lastName)){values.namespace=defaultNamespace(values.projectName);$('#wizard-namespace').value=values.namespace;}lastName=values.projectName;}if(key==='solutionMode')$('#wizard-solution-name').disabled=values.solutionMode==='existing';updatePreview();});}for(const [id,key]of [['wizard-same-directory','sameDirectory'],['wizard-checked','checked']])$('#'+id)?.addEventListener('change',e=>{values[key]=e.target.checked;updatePreview();});updatePreview();}
   modal.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();if(!busy)finish(null);}if(e.altKey&&e.key.toLowerCase()==='s'){$('#wizard-search')?.focus();e.preventDefault();}if(e.key==='Tab'){const controls=[...modal.querySelectorAll('button,input,select,textarea,[tabindex="0"]')].filter(x=>!x.disabled&&x.offsetParent!==null),first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){last?.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===last){first?.focus();e.preventDefault();}}if(e.key==='Enter'&&e.target.tagName==='INPUT'){e.preventDefault();if(!$('#wizard-next').disabled)next();}};
  };
  // A step rerender must not invoke the wizard's cancellation callback.
  const oldShow=this.host.showModal;this.host.showModal=(...args)=>{this.host.detachModalClose();oldShow(...args);};
  try{render();return await result;}finally{this.host.showModal=oldShow;const m=document.querySelector('#modal');m.classList.remove('wizard-modal');m.onkeydown=null;this.active=false;}
 }
 async selectImport(records,{name='Workspace',folders=[],settings={},force=false}={}){
  const candidates=workspaceCandidates(records),solutions=candidates.filter(p=>/\.(slnx|sln)$/i.test(p));if(!force&&(settings.entry||solutions.length===1||candidates.length<=1))return {entry:settings.entry??solutions[0]??candidates[0]??null,mode:settings.mode??(solutions.length?'solution':candidates.length?'project':'folder'),name};
  const result=await this.host.ask('Open project, solution or folder',`<p class="wizard-boundary">${records.length} files and ${folders.length} folders will be preserved. Choose the build entry; nothing is executed by loading.</p><label class="wizard-import-field">Open as<select id="workspace-entry"><option value="">Folder view — preserve all files without creating a project</option>${candidates.map(p=>`<option value="${E(p)}" ${p===(settings.entry??solutions[0]??candidates[0])?'selected':''}>${E(p)}</option>`).join('')}</select></label><p>Files outside the selected project remain in the workspace. Linked files and references must lie within this imported root.</p>`,'Open',()=>{const entry=document.querySelector('#workspace-entry').value;return {entry:entry||null,mode:entry?/\.(slnx|sln)$/i.test(entry)?'solution':'project':'folder',name};});return result;
 }
}
