/** DOM adapter. Panel elements are moved, never recreated, and retain their own state. */
export class DockHost {
  constructor(element,layout,{resolveContent,onActivate=()=>{},onError=()=>{},onClose=()=>{},onWindowKeyDown=()=>{}}={}){
    this.onWindowKeyDown=onWindowKeyDown;this.element=element;this.layout=layout;this.resolveContent=resolveContent;this.onActivate=onActivate;this.onError=onError;this.onClose=onClose;this.contents=new Map();this.popouts=new Map();this.windowWatch=null;this.autoPanel=null;this.dragPanel=null;this.disposed=false;this.controller=new AbortController();this.element.classList.add('sf-dock-host');
    this.unsubscribe=layout.subscribe(event=>{if(!['resize','bounds'].includes(event.type)||!this.dragSizing)this.render();});
    this.outside=e=>{if(this.autoPanel&&!e.target.closest('.sf-dock-auto-popup,.sf-dock-shelf')&&e.target.closest('[data-dock-toggle]')?.dataset.dockToggle!==this.autoPanel){this.autoPanel=null;this.render();}};
    element.ownerDocument.addEventListener('pointerdown',this.outside,{signal:this.controller.signal});element.ownerDocument.addEventListener('keydown',e=>{if(e.key==='Escape'&&this.autoPanel){this.autoPanel=null;this.render();}},{signal:this.controller.signal});
    this.render();
  }
  el(tag,className,text){const el=this.element.ownerDocument.createElement(tag);el.className=className;if(text!==undefined)el.textContent=text;return el;}
  content(id){let content=this.contents.get(id);if(!content){content=this.resolveContent?.(id)??this.el('div','','');content.dataset.dockPanel=id;content.classList.add('sf-dock-panel');this.contents.set(id,content);}return content;}
  attempt(action){try{return action();}catch(error){this.onError(error);}}
  button(label,title,action){const b=this.el('button','sf-dock-button',label);b.type='button';b.title=title;b.setAttribute('aria-label',title);b.onclick=e=>{e.stopPropagation();this.attempt(action);};return b;}
  render(){
    if(this.disposed)return;const doc=this.element.ownerDocument,focused=doc.activeElement,focusKey=focused?.dataset.dockTab?`[data-dock-tab="${CSS.escape(focused.dataset.dockTab)}"]`:focused?.classList.contains('sf-dock-divider')?`[data-split-id="${CSS.escape(focused.parentElement.dataset.splitId)}"] > .sf-dock-divider`:null,selection=focused&&'selectionStart'in focused?[focused.selectionStart,focused.selectionEnd]:null,scrolls=new Map([...this.contents].map(([id,c])=>[id,[c.scrollTop,c.scrollLeft]]));
    const tabScrolls=new Map([...this.element.querySelectorAll('.sf-dock-tabs')].map(tabs=>[tabs.closest('[data-dock-group]').dataset.dockGroup,tabs.scrollLeft]));
    const fragment=doc.createDocumentFragment(),parking=this.el('div','sf-dock-parking');parking.hidden=true;
    for(const [id,content] of this.contents)if(!this.popouts.has(id))parking.append(content);
    this.element.replaceChildren();this.element.append(parking);
    const shell=this.el('div','sf-dock-shell');
    for(const side of ['top','left','right','bottom']){const shelf=this.el('div','sf-dock-shelf '+side);shelf.dataset.side=side;for(const id of this.layout.state.autoHide[side]){const b=this.button(this.layout.require(id).title,`Show ${this.layout.require(id).title}`,()=>{this.autoPanel=this.autoPanel===id?null:id;this.render();this.onActivate(id);});b.classList.toggle('active',this.autoPanel===id);shelf.append(b);}shell.append(shelf);}
    const root=this.el('div','sf-dock-root');root.append(this.node(this.layout.state.root));shell.append(root);fragment.append(shell);
    for(const float of this.layout.state.floating){const box=this.el('section','sf-dock-floating');box.dataset.floatId=float.id;const bounds=this.clamp(float);Object.assign(box.style,{left:bounds.x+'px',top:bounds.y+'px',width:bounds.width+'px',height:bounds.height+'px'});box.onpointerdown=()=>{for(const floating of this.element.querySelectorAll('.sf-dock-floating'))floating.style.zIndex='12';box.style.zIndex='13';};const handle=this.el('div','sf-dock-float-title','Floating window');handle.append(this.button('↙','Dock floating group',()=>{for(const id of this.ids(float.root))this.layout.open(id);for(const id of this.ids(float.root))this.layout.dock(id,this.layout.state.root.type==='group'?this.layout.state.root.id:this.mainGroup(),'center');}));handle.onpointerdown=e=>{if(!e.target.closest('button'))this.moveFloating(e,float,box);};box.append(handle,this.node(float.root));const grip=this.el('div','sf-dock-float-grip');grip.setAttribute('role','separator');grip.setAttribute('aria-label','Resize floating group');grip.onpointerdown=e=>this.moveFloating(e,float,box,true);box.append(grip);fragment.append(box);}
    if(this.autoPanel){const where=this.layout.locate(this.autoPanel);if(where.kind==='autoHide'){const popup=this.el('section','sf-dock-auto-popup '+where.side);const bar=this.el('div','sf-dock-float-title',this.layout.require(this.autoPanel).title);bar.append(this.button('◆','Pin tool window',()=>{const id=this.autoPanel;this.autoPanel=null;this.layout.dockRoot(id,where.side);}));const content=this.content(this.autoPanel);content.hidden=false;popup.append(bar,content);fragment.append(popup);}else this.autoPanel=null;}
    this.element.append(fragment);
    for(const [id,content] of this.contents){if(!content.isConnected&&!this.popouts.has(id))parking.append(content);const scroll=scrolls.get(id);if(scroll){content.scrollTop=scroll[0];content.scrollLeft=scroll[1];}}
    if(focusKey&&!focused?.isConnected)this.element.querySelector(focusKey)?.focus({preventScroll:true});
    if(focused?.isConnected&&focused!==doc.body){focused.focus({preventScroll:true});if(selection&&typeof focused.setSelectionRange==='function')try{focused.setSelectionRange(...selection);}catch{}}
    if(this.resizeObserver)this.resizeObserver.disconnect();this.resizeObserver=new ResizeObserver(()=>this.updateOverflow());for(const strip of this.element.querySelectorAll('.sf-dock-tabs'))this.resizeObserver.observe(strip);this.updateOverflow();
    // Preserve manual strip scroll, then reveal the active caption horizontally.
    // scrollIntoView would also scroll document/tool bodies and parent windows.
    for(const tabs of this.element.querySelectorAll('.sf-dock-tabs')){
      tabs.scrollLeft=tabScrolls.get(tabs.closest('[data-dock-group]').dataset.dockGroup)??0;
      const active=tabs.querySelector('[aria-selected="true"]');if(!active)continue;
      const viewport=tabs.getBoundingClientRect(),rect=active.getBoundingClientRect();
      if(rect.left<viewport.left)tabs.scrollLeft-=viewport.left-rect.left;
      else if(rect.right>viewport.right)tabs.scrollLeft+=rect.right-viewport.right;
    }
  }
  ids(node){return node.type==='group'?[...node.panels]:[...this.ids(node.first),...this.ids(node.second)];}
  mainGroup(){let node=this.layout.state.root;while(node.type==='split')node=node.first;return node.id;}
  clamp(bounds){const maxW=Math.max(180,this.element.clientWidth),maxH=Math.max(120,this.element.clientHeight);const width=Math.min(bounds.width,maxW),height=Math.min(bounds.height,maxH);return {width,height,x:Math.max(0,Math.min(maxW-width,bounds.x)),y:Math.max(0,Math.min(maxH-40,bounds.y))};}
  node(node){
    if(node.type==='group')return this.group(node);
    const split=this.el('div','sf-dock-split '+node.axis);split.dataset.splitId=node.id;const first=this.el('div','sf-dock-branch'),second=this.el('div','sf-dock-branch');first.style.flex=`${node.ratio} 1 0`;second.style.flex=`${1-node.ratio} 1 0`;first.append(this.node(node.first));second.append(this.node(node.second));
    const divider=this.el('div','sf-dock-divider');divider.tabIndex=0;divider.setAttribute('role','separator');divider.setAttribute('aria-label','Resize docked groups');divider.setAttribute('aria-orientation',node.axis==='horizontal'?'vertical':'horizontal');divider.setAttribute('aria-valuemin','5');divider.setAttribute('aria-valuemax','95');divider.setAttribute('aria-valuenow',Math.round(node.ratio*100));
    divider.onkeydown=e=>{const delta=['ArrowRight','ArrowDown'].includes(e.key)?.03:['ArrowLeft','ArrowUp'].includes(e.key)?-.03:0;if(delta){e.preventDefault();this.layout.resize(node.id,node.ratio+delta);}};
    divider.onpointerdown=e=>{e.preventDefault();const rect=split.getBoundingClientRect();this.dragSizing=true;const initial=this.layout.snapshot();this.pointerSession(e,divider,move=>{const ratio=node.axis==='horizontal'?(move.clientX-rect.left)/rect.width:(move.clientY-rect.top)/rect.height;const value=Math.max(.05,Math.min(.95,ratio));first.style.flex=`${value} 1 0`;second.style.flex=`${1-value} 1 0`;this.layout.resize(node.id,value,{history:false});},()=>{this.dragSizing=false;this.layout.undoStack.push(initial);if(this.layout.undoStack.length>this.layout.historyLimit)this.layout.undoStack.shift();this.layout.redoStack=[];this.layout.notify('resize');});};
    split.append(first,divider,second);return split;
  }
  group(group){
    const el=this.el('section','sf-dock-group '+group.kind);el.dataset.dockGroup=group.id;
    const bar=this.el('div','sf-dock-bar'),tabs=this.el('div','sf-dock-tabs');tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label',group.kind==='document'?'Document group':'Tool window group');
    const prev=this.button('‹','Scroll tabs left',()=>tabs.scrollBy({left:-150,behavior:'smooth'})),next=this.button('›','Scroll tabs right',()=>tabs.scrollBy({left:150,behavior:'smooth'}));prev.classList.add('sf-dock-scroll');next.classList.add('sf-dock-scroll');
    for(const id of group.panels){const panel=this.layout.require(id),tab=this.el('button','sf-dock-tab',panel.title);tab.dataset.dockTab=id;tab.dataset.panel=panel.kind==='tool'?id:'';tab.title=panel.description??panel.title;tab.setAttribute('role','tab');tab.setAttribute('aria-selected',String(group.active===id));tab.tabIndex=group.active===id?0:-1;tab.draggable=true;tab.classList.toggle('selected',group.active===id);tab.onclick=()=>{this.layout.activate(id);this.onActivate(id);};tab.ondblclick=()=>this.layout.float(id);tab.oncontextmenu=e=>{e.preventDefault();this.menu(id,e.clientX,e.clientY);};tab.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const at=group.panels.indexOf(id),target=e.key==='Home'?0:e.key==='End'?group.panels.length-1:(at+(e.key==='ArrowRight'?1:-1)+group.panels.length)%group.panels.length;this.layout.activate(group.panels[target]);this.onActivate(group.panels[target]);this.element.querySelector(`[data-dock-tab="${CSS.escape(group.panels[target])}"]`)?.focus();}else if(e.key==='Delete'&&panel.closable){this.layout.close(id);this.onClose(id);}else if(e.shiftKey&&e.key==='F10'){e.preventDefault();const r=tab.getBoundingClientRect();this.menu(id,r.left,r.bottom);}};
      tab.ondragstart=e=>{this.dragPanel=id;e.dataTransfer.setData('application/x-sharpforge-panel',id);e.dataTransfer.effectAllowed='move';this.element.classList.add('sf-dock-dragging');};tab.ondragend=()=>this.clearDrag();
      tab.ondragover=e=>{if(this.dragPanel||e.dataTransfer.types.includes('application/x-sharpforge-panel')){e.preventDefault();e.stopPropagation();this.preview(el,'center');}};
      tab.ondrop=e=>{const id=e.dataTransfer.getData('application/x-sharpforge-panel');if(!id)return;e.preventDefault();e.stopPropagation();this.attempt(()=>this.layout.dock(id,group.id,'center',group.panels.indexOf(tab.dataset.dockTab)));this.clearDrag();};tabs.append(tab);
    }
    bar.append(prev,tabs,next);
    if(group.active){const id=group.active;bar.append(this.button('⌄',`Window actions: ${this.layout.require(id).title}`,()=>{const rect=bar.getBoundingClientRect();this.menu(id,rect.right-210,rect.bottom);}));if(this.layout.require(id).closable)bar.append(this.button('×',`Close ${this.layout.require(id).title}`,()=>{this.layout.close(id);this.onClose(id);}));}
    el.append(bar);const body=this.el('div','sf-dock-body');
    for(const id of group.panels){const content=this.content(id);if(this.popouts.has(id)){if(group.active===id){const placeholder=this.el('div','sf-dock-empty','This panel is in a separate browser window.');placeholder.append(this.button('Return here','Return panel to workspace',()=>this.returnPopout(id)));body.append(placeholder);}continue;}content.hidden=group.active!==id;body.append(content);}
    if(!group.panels.length)body.append(this.el('div','sf-dock-empty','Drop a document or tool here'));
    el.append(body);el.ondragover=e=>{if(!this.dragPanel&&!e.dataTransfer.types.includes('application/x-sharpforge-panel'))return;e.preventDefault();e.dataTransfer.dropEffect='move';this.preview(el,this.side(el,e));};el.ondragleave=e=>{if(!el.contains(e.relatedTarget)){el.removeAttribute('data-dock-preview');el.querySelector(':scope > .sf-dock-compass')?.remove();}};el.ondrop=e=>{const id=e.dataTransfer.getData('application/x-sharpforge-panel');if(!id)return;e.preventDefault();e.stopPropagation();this.attempt(()=>this.layout.dock(id,group.id,this.side(el,e)));this.clearDrag();};
    return el;
  }
  side(el,event){const target=event.target.closest?.('[data-dock-side]');if(target&&el.contains(target))return target.dataset.dockSide;const r=el.getBoundingClientRect(),x=(event.clientX-r.left)/Math.max(1,r.width),y=(event.clientY-r.top)/Math.max(1,r.height);if(x<.2)return 'left';if(x>.8)return 'right';if(y<.2)return 'top';if(y>.8)return 'bottom';return 'center';}
  preview(el,side){for(const other of this.element.querySelectorAll('[data-dock-preview]'))if(other!==el){other.removeAttribute('data-dock-preview');other.querySelector(':scope > .sf-dock-compass')?.remove();}el.dataset.dockPreview=side;let compass=el.querySelector(':scope > .sf-dock-compass');if(!compass){compass=this.el('div','sf-dock-compass');for(const [direction,label]of [['top','↑'],['left','←'],['center','▣'],['right','→'],['bottom','↓']]){const target=this.el('span','',label);target.dataset.dockSide=direction;target.title='Dock '+direction;compass.append(target);}el.append(compass);}for(const target of compass.children)target.classList.toggle('active',target.dataset.dockSide===side);}
  clearDrag(){this.dragPanel=null;this.element.classList.remove('sf-dock-dragging');for(const el of this.element.querySelectorAll('[data-dock-preview]')){el.removeAttribute('data-dock-preview');el.querySelector(':scope > .sf-dock-compass')?.remove();}}
  updateOverflow(){for(const tabs of this.element.querySelectorAll('.sf-dock-tabs')){const overflow=tabs.scrollWidth>tabs.clientWidth+1;for(const button of tabs.parentElement.querySelectorAll('.sf-dock-scroll'))button.hidden=!overflow;}}
  pointerSession(event,target,move,end){const id=event.pointerId;target.setPointerCapture(id);const onMove=e=>{if(e.pointerId===id)move(e);},finish=e=>{if(e.pointerId!==id)return;target.removeEventListener('pointermove',onMove);target.removeEventListener('pointerup',finish);target.removeEventListener('pointercancel',finish);if(target.hasPointerCapture(id))target.releasePointerCapture(id);end();};target.addEventListener('pointermove',onMove);target.addEventListener('pointerup',finish);target.addEventListener('pointercancel',finish);}
  moveFloating(e,float,element,resize=false){e.preventDefault();const initial=this.layout.snapshot(),start={x:e.clientX,y:e.clientY},bounds=this.clamp(float);this.dragSizing=true;this.pointerSession(e,e.currentTarget,move=>{const dx=move.clientX-start.x,dy=move.clientY-start.y;const next=this.clamp(resize?{...bounds,width:Math.max(180,bounds.width+dx),height:Math.max(120,bounds.height+dy)}:{...bounds,x:bounds.x+dx,y:bounds.y+dy});Object.assign(element.style,{left:next.x+'px',top:next.y+'px',width:next.width+'px',height:next.height+'px'});this.layout.bounds(float.id,next,{history:false});},()=>{this.dragSizing=false;this.layout.undoStack.push(initial);if(this.layout.undoStack.length>this.layout.historyLimit)this.layout.undoStack.shift();this.layout.redoStack=[];this.layout.notify('bounds');});}
  menu(id,x,y){
    this.dismissMenu?.();const menu=this.el('div','sf-dock-menu');menu.setAttribute('role','menu');const action=(name,callback)=>{const b=this.button(name,name,()=>{this.dismissMenu?.();callback();});b.setAttribute('role','menuitem');menu.append(b);};
    action('Float in workspace',()=>this.layout.float(id));
    action('Open separate browser window',()=>this.popout(id));
    for(const side of ['left','right','top','bottom'])action('Dock '+side,()=>this.layout.dockRoot(id,side));
    for(const group of this.layout.groups())if(!group.panels.includes(id))action('Join '+(group.active?this.layout.require(group.active).title:'empty document group'),()=>this.layout.dock(id,group.id));
    if(this.layout.require(id).kind==='tool')for(const side of ['left','right','bottom'])action('Auto-hide '+side,()=>this.layout.autoHide(id,side));
    if(this.layout.require(id).closable)action('Close',()=>{this.layout.close(id);this.onClose(id);});
    menu.style.left=Math.max(0,Math.min(x,innerWidth-240))+'px';menu.style.top=Math.max(0,Math.min(y,innerHeight-300))+'px';this.element.ownerDocument.body.append(menu);menu.querySelector('button')?.focus();const dismiss=e=>{if(!menu.contains(e.target))this.dismissMenu?.();};this.dismissMenu=()=>{menu.remove();this.element.ownerDocument.removeEventListener('pointerdown',dismiss,true);this.dismissMenu=null;};this.element.ownerDocument.addEventListener('pointerdown',dismiss,true);menu.onkeydown=e=>{if(e.key==='Escape')this.dismissMenu?.();else if(['ArrowUp','ArrowDown','Home','End'].includes(e.key)){e.preventDefault();const items=[...menu.querySelectorAll('button')],index=items.indexOf(menu.ownerDocument.activeElement),next=e.key==='Home'?0:e.key==='End'?items.length-1:(index+(e.key==='ArrowDown'?1:-1)+items.length)%items.length;items[next]?.focus();}};
  }
  /** Real same-origin child window, retaining the exact tool DOM and event listeners. */
  popout(id){
    this.layout.require(id);if(this.popouts.has(id)){this.popouts.get(id).window.focus();return;}
    const win=this.element.ownerDocument.defaultView.open('','', 'popup,width=900,height=650');if(!win)throw new Error('The browser blocked the tool window popup');
    const doc=win.document;doc.title=this.layout.require(id).title+' — SharpForge';doc.documentElement.dataset.theme=this.element.ownerDocument.documentElement.dataset.theme;
    for(const style of this.element.ownerDocument.querySelectorAll('style,link[rel="stylesheet"]')){const copy=style.cloneNode(true);if(copy.tagName==='LINK')copy.href=style.href;doc.head.append(copy);}
    doc.addEventListener('keydown',e=>{if(!e.defaultPrevented)this.onWindowKeyDown(e);});doc.body.className='sf-dock-popout';const returnButton=doc.createElement('button');returnButton.textContent='Return to main workspace';returnButton.onclick=()=>this.returnPopout(id);const content=this.content(id);content.hidden=false;this.popouts.set(id,{window:win});if(this.windowWatch===null)this.windowWatch=setInterval(()=>{for(const [key,entry]of this.popouts)if(entry.window.closed)this.reattachClosedPopout(key);if(!this.popouts.size){clearInterval(this.windowWatch);this.windowWatch=null;}},250);doc.body.append(returnButton,content);
    win.addEventListener('pagehide',()=>this.reattachClosedPopout(id));win.addEventListener('beforeunload',()=>this.reattachClosedPopout(id));this.render();
  }
  reattachClosedPopout(id){if(!this.popouts.has(id))return;this.popouts.delete(id);this.element.append(this.content(id));this.render();}
  returnPopout(id){const entry=this.popouts.get(id);if(!entry)return;this.popouts.delete(id);this.element.append(this.content(id));entry.window.close();this.layout.open(id);this.render();}
  dispose(){if(this.disposed)return;for(const id of [...this.popouts.keys()])this.returnPopout(id);this.disposed=true;if(this.windowWatch!==null)clearInterval(this.windowWatch);this.windowWatch=null;this.unsubscribe();this.controller.abort();this.resizeObserver?.disconnect();this.dismissMenu?.();}
}
