<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>ConsoleLibrarySolutionExample</AssemblyName>
    <RootNamespace>TemplateExamples.ConsoleLibrarySolution</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <DebugType>portable</DebugType>
    <CheckForOverflowUnderflow>false</CheckForOverflowUnderflow>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ConsoleLibrarySolutionExample.Core/ConsoleLibrarySolutionExample.Core.csproj" />
  </ItemGroup>
</Project>
