import { DesignDocumentCore } from './document-core.js';
import {designerMetadata, designerPropertySchema, designerChildSlot} from './metadata.js';
import {validateDesignerAuthoring} from './resource-validation.js';
import {normalizeProperty, track} from './document-values.js';
import {designerDocumentContracts} from './document-property-values.js';
import {cleanDesignData as cleanData} from './document-data.js';
export {normalizeProperty, track} from './document-values.js';
import {frameworkManifest,frameworkType,canonicalType,frameworkAssignable,propertiesFor,eventsFor,XAML,CONTROLS,MEDIA} from '@sharpforge/framework';
import {prepareLiveDesignChanges} from './live-capabilities.js';
import {readLiveDesignScene} from './live-scene-reader.js';
const copy=x=>structuredClone(x),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const object=x=>x!==null&&typeof x==='object'&&!Array.isArray(x);
const short=t=>t.slice(t.lastIndexOf('.')+1);
const bad=m=>{throw new TypeError(m);};
export const designControls = designerMetadata;
export const propertySchema = designerPropertySchema;
export const childSlot = designerChildSlot;
function templateCheck(part,ids,ownerType,depth=0){if(depth>50||ids.size>500)bad('Template size limit');if(!object(part)||typeof part.id!=='string'||!/^[A-Za-z_][\w.:-]{0,127}$/.test(part.id)||ids.has(part.id))bad('Template part identifiers must be unique');ids.add(part.id);part.type=canonicalType(part.type);if(!designControls.some(t=>t.type===part.type)||part.type===XAML+'Window')bad('Unsupported template part');part.properties??={};for(const [k,v]of Object.entries(part.properties))part.properties[k]=normalizeProperty(part.type,k,v);for(const [k,source]of Object.entries(part.bindings??{})){const a=propertySchema(part.type)[k],b=propertySchema(ownerType)[source];if(!a||a.readOnly||!b||!(a.type===b.type||a.type==='object'))bad('Incompatible template binding');}const slot=childSlot(part.type);if(part.children?.length&&(!slot||!slot.many&&part.children.length>1))bad('Template child cardinality');for(const child of part.children??[])templateCheck(child,ids,ownerType,depth+1);}
export function validateDesign(input){const d=copy(input);cleanData(d);if(d.version!==1||!Array.isArray(d.nodes)||d.nodes.length>5000||!d.nodes.length)bad('Invalid or oversized design document');if(typeof d.name!=='string'||d.name.length>100)bad('Invalid document name');d.width??=960;d.height??=640;if(![d.width,d.height].every(n=>Number.isFinite(n)&&n>=100&&n<=10000))bad('Artboard dimensions must be 100–10000');d.styles??={};d.templates??={};if(!object(d.styles)||!object(d.templates))bad('Resources must be named objects');for(const key of [...Object.keys(d.styles),...Object.keys(d.templates)])if(!/^[A-Za-z_]\w*$/.test(key))bad('Resource keys must be identifiers');const nodes=new Map(),names=new Set();for(const n of d.nodes){if(typeof n.id!=='string'||!/^[A-Za-z_][\w.:-]{0,127}$/.test(n.id)||nodes.has(n.id))bad('Design node identifiers must be unique');n.type=canonicalType(n.type);if(!designControls.some(t=>t.type===n.type))bad('Unsupported designer control '+n.type);n.properties??={};n.children??=[];n.events??={};if(!object(n.properties)||!object(n.events)||!Array.isArray(n.children))bad('Invalid control data');if(n.type===XAML+'Window'&&n.id!==d.root)bad('Windows must be design roots');if(n.children.length&&propertiesFor(n.type).Content)delete n.properties.Content;for(const [k,v]of Object.entries(n.properties))n.properties[k]=normalizeProperty(n.type,k,v);if(n.baseProperties){if(!object(n.baseProperties))bad('Invalid captured properties');for(const [k,v]of Object.entries(n.baseProperties))n.baseProperties[k]=normalizeProperty(n.type,k,v);}if(n.properties.Name){if(!/^[A-Za-z_]\w*$/.test(n.properties.Name)||names.has(n.properties.Name))bad('Names must be unique C# identifiers');names.add(n.properties.Name);}for(const [event,handler]of Object.entries(n.events))if(!eventsFor(n.type)[event]||!/^([A-Za-z_]\w*\.)*[A-Za-z_]\w*$/.test(handler))bad('Invalid event or handler');if(n.children.length){const slot=childSlot(n.type);if(!slot||!slot.many&&n.children.length>1)bad(short(n.type)+' cannot contain those children');}for(const key of ['rows','columns'])if(n[key]){if(n.type!==CONTROLS+'Grid'||n[key].length>64)bad('Grid track limit');n[key]=n[key].map(track);}nodes.set(n.id,n);}
  if(!nodes.has(d.root))bad('Missing design root');const seen=new Set();function visit(id,depth){if(depth>100||seen.has(id))bad('Visual tree cycle or multiple parents');const n=nodes.get(id);if(!n)bad('Missing child '+id);seen.add(id);for(const child of n.children)visit(child,depth+1);}visit(d.root,0);if(seen.size!==nodes.size)bad('Unparented design nodes');
  const resolving=new Set(),resolved=new Set();function style(name){if(resolving.has(name))bad('Style inheritance cycle');if(resolved.has(name))return;const s=d.styles[name];if(!s)bad('Unknown style '+name);s.targetType=canonicalType(s.targetType);if(!frameworkType(s.targetType))bad('Unknown style target');resolving.add(name);if(s.basedOn){style(s.basedOn);if(!frameworkAssignable(d.styles[s.basedOn].targetType,s.targetType))bad('Incompatible BasedOn style');}s.setters??={};for(const [k,v]of Object.entries(s.setters))s.setters[k]=normalizeProperty(s.targetType,k,v);resolving.delete(name);resolved.add(name);}for(const name of Object.keys(d.styles))style(name);
  for(const [name,t]of Object.entries(d.templates)){t.targetType=canonicalType(t.targetType);if(!frameworkAssignable(CONTROLS+'Control',t.targetType))bad('Templates require a Control target');templateCheck(t.root,new Set(),t.targetType);}
  for(const n of d.nodes){if(n.style&&(!propertiesFor(n.type).Style||!d.styles[n.style]||!frameworkAssignable(d.styles[n.style].targetType,n.type)))bad('Incompatible style on '+n.id);if(n.template&&(!d.templates[n.template]||!frameworkAssignable(d.templates[n.template].targetType,n.type)))bad('Incompatible template on '+n.id);}
  return validateDesignerAuthoring(d, {normalizeProperty, propertySchema, childSlot});
}
export function resolvedProperties(d,n){const p={},sources={};for(const [k,v]of Object.entries(propertiesFor(n.type)))if(!v.isStatic&&v.value!==null&&(!['double','int'].includes(v.type)||Number.isFinite(v.value))){p[k]=copy(v.value);sources[k]='default';}for(const[k,v]of Object.entries(n.baseProperties??{})){p[k]=copy(v);sources[k]='runtime style/default';}const style=name=>{const s=d.styles[name];if(!s)return;if(s.basedOn)style(s.basedOn);for(const [k,v]of Object.entries(s.setters)){p[k]=copy(v);sources[k]='style: '+name;}};for(const [name,s]of Object.entries(d.styles))if(s.implicit&&s.targetType===n.type)style(name);if(n.style)style(n.style);for(const [k,v]of Object.entries(n.properties)){p[k]=copy(v);sources[k]='local';}return {properties:p,sources};}
export function designScene(input){const d=validateDesign(input),nodes=[];for(const n of d.nodes){const {properties}=resolvedProperties(d,n),out={id:n.id,type:n.type,properties,events:Object.keys(n.events),collections:{},designId:n.id};const slot=childSlot(n.type);if(n.children.length&&slot){if(slot.many)out.collections[slot.property]=n.children.map(id=>({$ref:id}));else out.properties[slot.property]={$ref:n.children[0]};}for(const [key,property,member]of [['rows','RowDefinitions','Height'],['columns','ColumnDefinitions','Width']])if(n[key])out.collections[property]=n[key].map((length,i)=>{const id=n.id+'-'+key+i;nodes.push({id,type:CONTROLS+(key==='rows'?'RowDefinition':'ColumnDefinition'),properties:{[member]:length},events:[],collections:{}});return {$ref:id};});nodes.push(out);if(n.template){const t=d.templates[n.template];const part=(p)=>{const id=n.id+'::'+p.id,ps=copy(p.properties??{});for(const [key,source]of Object.entries(p.bindings??{}))ps[key]=copy(properties[source]??null);const item={id,type:p.type,properties:ps,events:[],collections:{},templateOwner:n.id,templateBindings:p.bindings??{},designId:n.id};const slot=childSlot(p.type),children=(p.children??[]).map(part);if(children.length&&slot){if(slot.many)item.collections[slot.property]=children.map(id=>({$ref:id}));else item.properties[slot.property]={$ref:children[0]};}nodes.push(item);return id;};out.templateRoot=part(t.root);}}
  let root=d.root;if(d.nodes.find(n=>n.id===root).type!==XAML+'Window'){root='__artboard';nodes.push({id:root,type:XAML+'Window',properties:{Content:{$ref:d.root},Title:d.name},events:[],collections:{}});}return {version:1,windows:[root],nodes};}
export function createDesign(name='Workspace'){return validateDesign({version:1,name,width:960,height:640,root:'window',nodes:[{id:'window',type:'Window',properties:{Title:name},children:['canvas']},{id:'canvas',type:'Canvas',properties:{Name:'Root',Width:960,Height:640,Background:'#20242b'},children:['title','caption','action']},{id:'title',type:'TextBlock',properties:{Name:'Title',Text:'Build something remarkable',FontSize:30,Left:48,Top:44,Width:670,Height:48,Foreground:'#f6f7fa'},children:[]},{id:'caption',type:'TextBlock',properties:{Text:'Code-first WinUI • live preview • managed events',FontSize:16,Left:50,Top:103,Width:670,Height:32,Foreground:'#b0bfd4'},children:[]},{id:'action',type:'Button',properties:{Name:'ActionButton',Content:'Run action',Left:50,Top:162,Width:160,Height:40},style:'Accent',events:{Click:'Program.OnAction'},children:[]}],styles:{Accent:{targetType:'Button',setters:{Background:'#005fb8',Foreground:'#ffffff',CornerRadius:5,FontSize:15}}},templates:{}});}
/** Indexed, bounded document transactions shared by all designer sessions. */
export class DesignDocument extends DesignDocumentCore {
  constructor(value = createDesign(), options = {}) {
    super(value, {...options, contracts: designerDocumentContracts(validateDesign)});
  }
}
export function designFromScene(scene, options = {}) {
  return readLiveDesignScene(scene, options, {validate: validateDesign, normalize: normalizeProperty, childSlot, controls: designControls});
}
/** Minimal live delta. Unchanged effective properties are omitted to preserve running input/state. */
export function designPatch(before,after){before=validateDesign(before);after=validateDesign(after);if(before.root!==after.root)bad('Replacing the live root requires restart');const extended=prepareLiveDesignChanges(before,after,{resolvedProperties}),old=new Map(before.nodes.map(n=>[n.id,n])),commands=extended.commands;
  for(const n of after.nodes){const previous=old.get(n.id);if(previous&&previous.type!==n.type)bad('Changing live control types requires delete and insert');if(!same(previous?.events??{},n.events))bad('Changing managed event handlers requires a generated-code update');if(!previous)commands.push({op:'create',id:n.id,type:n.type});
    if(!extended.collectionOwners.has(n.id)&&(n.children.length||previous?.children.length)&&!same(previous?.children,n.children))commands.push({op:'children',id:n.id,children:n.children});
    const current=resolvedProperties(after,n).properties,prior=previous?resolvedProperties(before,previous).properties:{};
    for(const [name,value]of Object.entries(current))if(!same(value,prior[name])&&!propertiesFor(n.type)[name]?.readOnly)commands.push({op:'set',id:n.id,property:name,value});
    for(const name of Object.keys(prior))if(!Object.hasOwn(current,name)&&!propertiesFor(n.type)[name]?.readOnly)commands.push({op:'clear',id:n.id,property:name});
    for(const key of ['rows','columns'])if(!same(previous?.[key],n[key]))commands.push({op:'tracks',id:n.id,axis:key,tracks:n[key]??[]});
    if(previous?.template!==n.template||!same(before.templates[n.template],after.templates[n.template]))commands.push({op:'template',id:n.id,template:n.template?after.templates[n.template]:null});
  }
  const retained = new Set(after.nodes.map(node => node.id));
  for(const n of before.nodes)if(!retained.has(n.id))commands.push({op:'remove',id:n.id});
  return {version:1,bindings:Object.fromEntries(before.nodes.filter(n=>n.runtimeId!==undefined).map(n=>[n.id,n.runtimeId])),commands};
}
