import {AnimationClock,easing,frameworkType,propertiesFor,XAML,CONTROLS,MEDIA} from '@sharpforge/framework';
import {ManagedFault,isReference} from './heap.js';
import {updateBindings} from './styling.js';
import {animationTarget as target} from './execution/animation-target.js';
const A=MEDIA+'Animation.',key=r=>`${r.h}:${r.g}`,bad=m=>{throw new ManagedFault('InvalidOperationException',m);};
const numeric=(n,name,min=0,max=1e12)=>{if(!Number.isFinite(n)||n<min||n>max)throw new ManagedFault('ArgumentOutOfRangeException',name);return n;};
const span=(p,ref)=>ref?p.native(p.get(ref,'TotalMilliseconds')):0;
const duration=(p,ref)=>!ref||p.get(ref,'$durationKind')==='auto'?null:p.get(ref,'$durationKind')==='forever'?Infinity:span(p,p.get(ref,'TimeSpan'));
function easingData(p,ref){return ref?{kind:p.record(ref).type.split('.').at(-1),mode:p.native(p.get(ref,'EasingMode',0)),power:p.native(p.get(ref,'Power',2)),amplitude:p.native(p.get(ref,'Amplitude',1))}:{kind:'Linear'};}
function definition(p,ref,seen=new Set(),depth=0){if(depth>16||seen.size>=512||seen.has(key(ref)))bad('Timeline cycle, duplicate, or size limit');seen.add(key(ref));const type=p.record(ref).type,repeat=p.get(ref,'RepeatBehavior'),d={id:key(ref),ref,begin:span(p,p.get(ref,'BeginTime')),duration:duration(p,p.get(ref,'Duration')),speed:p.native(p.get(ref,'SpeedRatio',1)),autoReverse:!!p.native(p.get(ref,'AutoReverse',false)),fill:p.native(p.get(ref,'FillBehavior',0)),repeat:repeat?p.native(p.get(repeat,'Count',1)):1,forever:repeat?!!p.get(repeat,'$forever'):false};if(repeat&&p.get(repeat,'$repeatDuration'))d.repeatDuration=span(p,p.get(repeat,'Duration'));
 if(type===A+'Storyboard'){const list=p.get(ref,'Children');d.children=(list?p.items(list):[]).map(c=>definition(p,c,seen,depth+1));if(!d.children.length&&d.duration===null)d.duration=0;}
 else if(type===A+'DoubleAnimation'){const {object,property}=target(p,ref);d.target=object;d.property=property;for(const name of ['From','To','By']){const value=p.get(ref,name);if(value!==null)d[name.toLowerCase()]=p.native(value);}d.easing=easingData(p,p.get(ref,'EasingFunction'));}
 else bad('Unsupported timeline '+type);return d;}
export function createManagedAnimationClock(p){return new AnimationClock({key,read:(ref,property)=>p.native(p.get(ref,property)),validate:(ref,property)=>{if(['$Left','$Top'].includes(property)){if(!p.isElement(ref))bad('Attached animation target must be a UIElement');return;}const prop=propertiesFor(p.record(ref).type)[property];if(!prop||prop.type!=='double'||prop.readOnly)bad('DoubleAnimation needs a writable double property: '+property);},write:(ref,property,value)=>{if(property==='Opacity')value=Math.max(0,Math.min(1,value));if(/^(Width|Height|MinWidth|MinHeight|MaxWidth|MaxHeight|FontSize|ItemWidth|ItemHeight)$/.test(property))value=Math.max(0,value);const v=p.managed(value,'double');p.set(ref,property,v);updateBindings(p,ref);p.command({op:'set',id:key(ref),property:property.replace(/^\$/,''),value});},completed:ref=>{if(isReference(ref))p.enqueueEvent(ref,'Completed');}});}
export function advanceManagedAnimations(p,delta){return p.styleMutation(()=>{try{p.animations.advance(delta);}catch(e){if(e instanceof ManagedFault)throw e;bad(e.message);}return p.animations.running;});}
export function invokeAnimation(p,d,args){const ok=value=>({handled:true,value}),owner=d.owner;
 if(owner==='System.TimeSpan'){if(d.name==='get_Zero')return ok(p.make(owner,{TotalMilliseconds:p.managed(0,'double')}));if(d.isStatic){const v=p.native(args[0])*(d.name==='FromSeconds'?1000:d.name==='FromMinutes'?60000:1);numeric(v,'TimeSpan',-1e12);return ok(p.make(owner,{TotalMilliseconds:p.managed(v,'double')}));}if(d.name==='get_TotalSeconds')return ok(p.managed(span(p,args[0])/1000,'double'));return {handled:false};}
 if(owner===XAML+'Duration'){if(d.isStatic)return ok(p.make(owner,{'$durationKind':d.property==='Automatic'?'auto':'forever'}));if(d.kind==='constructor'){numeric(span(p,args[0]),'Duration');return ok(p.make(owner,{TimeSpan:args[0]}));}if(d.property==='TimeSpan'&&p.get(args[0],'$durationKind'))bad('Automatic/Forever Duration has no finite TimeSpan');return {handled:false};}
 if(owner===A+'RepeatBehavior'){if(d.isStatic)return ok(p.make(owner,{'$forever':true}));if(d.kind==='constructor'){if(d.parameters[0]==='double'){const n=p.native(args[0]);numeric(n,'RepeatBehavior count',0,1e6);return ok(p.make(owner,{Count:p.managed(n,'double')}));}numeric(span(p,args[0]),'RepeatBehavior duration');return ok(p.make(owner,{'$repeatDuration':true,Duration:args[0],Count:p.managed(1,'double')}));}return {handled:false};}
 if(owner==='SharpForge.UI.AnimationClock')return ok((advanceManagedAnimations(p,p.native(args[0])),null));
 if(d.kind==='animationTarget'){const [ref,value]=args;p.record(ref);if(d.property==='Target'&&value!==null)p.record(value);p.set(ref,'$'+d.property,value);return ok(null);}
 if(d.kind==='animationTargetGet')return ok(p.get(args[0],'$'+d.property));
 if(owner===A+'EasingFunctionBase'&&d.name==='Ease')return ok(p.managed(easing(p.native(args[1]),easingData(p,args[0])),'double'));
 if(owner===A+'Storyboard'&&d.kind==='method'&&!d.isStatic){const ref=args[0],id=key(ref);try{return ok(p.styleMutation(()=>{switch(d.name){case 'Begin':p.animations.begin(id,definition(p,ref));break;case 'Pause':p.animations.pause(id);break;case 'Resume':p.animations.resume(id);break;case 'Stop':p.animations.stop(id);break;case 'Seek':case 'SeekAlignedToLastTick':p.animations.seek(id,span(p,args[1]));break;case 'SkipToFill':p.animations.skipToFill(id);break;case 'GetCurrentTime':return p.make('System.TimeSpan',{TotalMilliseconds:p.managed(p.animations.state(id).currentTime,'double')});case 'GetCurrentState':return p.animations.state(id).state;default:bad('Unsupported Storyboard method '+d.name);}return null;}));}catch(e){if(e instanceof ManagedFault)throw e;bad(e.message);}}
 return {handled:false};
}
