import test from 'node:test';import assert from 'node:assert/strict';import {readdir,mkdtemp,rm,mkdir,writeFile} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {resolveToolchain} from '../../../scripts/conformance/oracle/toolchain.js';
import {hydrateFixture,loadCorpus,root} from '../../../scripts/conformance/diff/fixtures.js';import {observeFixture} from '../../../scripts/conformance/diff/run.js';import {runSharpCLR,runRoslynCLR} from '../../../scripts/conformance/diff/engines/clr.js';import {reduceFixture} from '../../../scripts/conformance/diff/reduce.js';
const toolchain=await resolveToolchain({checkImage:false});
const definition={id:'native',source:'Program.cs',entry:'Main',stdin:'',capabilities:['arithmetic.double'],seed:1729,normalisers:['newlines','float-format','exception-text'],langVersion:'12.0'};
test('real pinned CLR runs SharpForge and Roslyn assemblies, stdout, managed faults and exit boundaries',{timeout:120000},async()=>{
 for(const fixture of (await loadCorpus()).filter(f=>['hello','int32-boundary','nested-finally','unhandled','syntax-negative','stdin'].includes(f.id))){const observed=await observeFixture(fixture,{toolchain});assert.equal(observed.observations.length,2);assert(observed.observations.flat().filter(r=>r.engine.startsWith('clr-')).every(r=>r.status!=='host-error'),fixture.id+JSON.stringify(observed));assert(!observed.differences.some(d=>d.class==='unclassified'));const clr=observed.observations[0].find(r=>r.engine==='clr-roslyn');if(fixture.id==='hello')assert.equal(clr.stdout.replaceAll('\r',''),'Hello → café\n1732\n');if(fixture.id==='stdin')assert.equal(clr.stdout.replaceAll('\r',''),'Ada\n');if(fixture.id==='unhandled')assert.equal(clr.exception.type,'System.Exception');if(fixture.id==='syntax-negative')assert.equal(clr.status,'compile-error');}
});
test('real same-DLL runtime difference reduces a seeded 200-line source below20lines twice',{timeout:180000},async()=>{
 const source=['using System;','class Program {','static void Main() {',...Array.from({length:200},(_,i)=>`int unused${i}=${i};`),'double value=-0.0;','Console.WriteLine(value);','}','}'].join('\n'),fixture=hydrateFixture(definition,source),observed=await observeFixture(fixture,{toolchain}),difference=observed.differences.find(d=>d.class==='runtime');assert(difference,'Signed-zero formatting should reproduce the independently observed JS/native runtime difference');
 const observe=(candidate,options)=>observeFixture(candidate,{toolchain,...options}),first=await reduceFixture(fixture,difference,observe),second=await reduceFixture(fixture,difference,observe);assert(first.afterLines<20);assert.deepEqual(second,first);assert.equal(first.budgetExhausted,false);
 await mkdir(path.join(root,'artifacts/differential'),{recursive:true});await writeFile(path.join(root,'artifacts/differential/reducer-200.json'),JSON.stringify({qualification:'real pinned CoreCLR and CIL VM; two identical reductions',toolchain:toolchain.actual,...first},null,2)+'\n');
});
test('native execution cancellation and time budgets dispose temporary DLLs',{timeout:30000},async()=>{
 const temporaryRoot=await mkdtemp(path.join(os.tmpdir(),'diff-disposal-test-')),fixture=hydrateFixture({...definition,limits:{timeoutMs:200}},'class Program { static void Main() { while(true) {} } }');
 try{for(const run of [runSharpCLR,runRoslynCLR]){const actual=await run(fixture,{toolchain,temporaryRoot});assert.equal(actual.status,'budget-exceeded');const controller=new AbortController();const pending=run({...fixture,limits:{...fixture.limits,timeoutMs:10000}},{toolchain,temporaryRoot,signal:controller.signal});setTimeout(()=>controller.abort(),150);assert.equal((await pending).status,'cancelled');}
 assert.deepEqual(await readdir(temporaryRoot),[]);}finally{await rm(temporaryRoot,{recursive:true,force:true});}
});
