export {AllocationContext} from './allocation-context.js';
export {HandleTable} from './handle-table.js';
export {TypeDescriptors, visitEdges, visitEdgeRange} from './type-descriptor.js';
export {recordSize, valueSize} from './sizing.js';
export {verifyHeap} from './verify.js';
export {HeapBarriers} from './barrier.js';
export {Collector} from './collector.js';
export {GCGeneration} from './generations.js';
export {MarkColor, IncrementalMarker} from './incremental-mark.js';
export {CardTable} from './card-table.js';
export {AllocationBlocks} from './blocks.js';
export {HeapSpaces} from './spaces.js';
export {HeapLimits} from './limits.js';
export {SafepointCoordinator} from './safepoints.js';
export {BackgroundMarker} from './background-mark.js';
export {LifetimeManager} from './lifetime.js';
export {HostHandleKind, HostHandleTable} from './host-handles.js';
export {ManagedWeakReference} from './weak-reference.js';
export {GCHandleType, ManagedGCHandle} from './gc-handle.js';
export {DependentHandleTable, ManagedConditionalWeakTable} from './dependent-handles.js';
export {ManagedSafeHandle, HostResourceTable} from './safe-handle.js';
export {PinManager} from './pinning.js';
export {ManagedAddress, VirtualAddressSpace} from './address-space.js';
export {ManagedInteriorReference, createInteriorReference, resolveInteriorReference} from './interior.js';
export {FinalizerState, ManagedFinalizationRegistry} from './finalization.js';
export {FinalizerContext} from './finalizer-context.js';
export {GCShutdownPolicy} from './shutdown.js';
export * from './api.js';
export {GCEvents, GCReason, GCEventNames} from './events.js';
export {GCCounters} from './counters.js';
export {GCSettings, GCLatencyMode, GCLargeObjectHeapCompactionMode} from './settings.js';
export {GCNotifications, GCNotificationStatus} from './notifications.js';
export {MemoryPressure} from './memory-pressure.js';
export {parseGCConfiguration} from './config.js';
export {HeapDiagnostics} from './diagnostics.js';
export {AllocationSites} from './allocation-sites.js';
export {RootCategory, RootRegistry} from './roots.js';
export {DebuggerRootScope} from './debugger-roots.js';
export {DebuggerMemoryScope} from './debug-memory.js';
export {GCStress} from './stress.js';
export {auditRoots, traceRootClosure} from './root-audit.js';
export {HeapDumpView, exportHeapDump} from './heap-dump.js';
export {diffHeapDumps} from './snapshot-diff.js';
