export {CodeEditor} from './core/code-editor.js';
export {EDITOR_KEYMAPS, ClassicKeymapAdapter, handleVisualStudioKey} from './keymaps.js';
export {NativeKeymapAdapter, getProfileBindings} from './keymaps/native.js';
export {KeybindingService} from './keymaps/resolve.js';
export {platformBindingInventory, eventStroke, normalizeStroke, normalizeSequence} from './keymaps/platform.js';
export * from './commands/index.js';
export {SyntaxHighlightIndex} from './highlight.js';
export {NavigationHistory} from './navigation.js';
export {bracketPairs, lexicalContext, replaceLiteral, duplicateLineBlock} from './operations.js';
export {EditorModel} from './model.js';
export {UndoStack} from './undo.js';
export * from './selections.js';
export * from './commands/multi-caret.js';
export * from './commands/box-selection.js';
export * from './commands/multi-clipboard.js';
export * from './services/index.js';
export * from './features/index.js';
export * from './snippets/index.js';
export * from './diff/index.js';
export {LineLayout, upperBound, canvasMeasure} from './view/layout.js';
export {VisualLineMap, wrapLine} from './view/wrap.js';
export {VirtualEditorView} from './view/virtual-view.js';
export {DocumentLayout, lineInfo} from './view/document-layout.js';
export {HiddenInputController} from './view/input.js';
export {CompositionController} from './view/composition.js';
export {BidiGeometry, hasBidi} from './view/bidi.js';
export {whitespaceMarkers} from './view/whitespace.js';
export {FoldingModel} from './folding.js';
export {FoldingProvider, fallbackFolding} from './folding-provider.js';
export {FoldingStateStore} from './folding-state.js';
export {outliningCommands} from './commands/outlining.js';
export {advancedCommands, tabify, untabify} from './commands/advanced.js';
export {overviewMarks} from './view/overview-ruler.js';
export {stickyHeaders} from './view/sticky-scroll.js';
export {BookmarkModel} from './bookmarks.js';
export {ChangeTracking} from './change-tracking.js';
export {ClipboardRing, dragTextEdits} from './clipboard-ring.js';
export {defaultEditorOptions, editorOptions, EditorOptionScope} from './options.js';
export {parseEditorConfig, resolveEditorConfig, editorConfigGlob, saveTextEdits, saveTextEditsAsync} from './editorconfig.js';
export {createEditorOptionsPage} from './options-page.js';
export {LargeFilePolicy} from './large-file.js';
export {readEditorSource, rebaseEditorSource} from './source-loader.js';
export {EditorAccessibility} from './a11y/aria.js';
export {describeDiagnostic, navigateDiagnostic, announceLineState} from './a11y/diagnostics.js';
export {accessibleWidget} from './a11y/widgets.js';
export {commandAliases} from './core/command-map.js';
export const escapeHtml = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;')
  .replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
