import {createEditorContextItems} from './editor-context.js';
export function createContextMenus(context){
const editorContextItems=instance=>createEditorContextItems(context,instance);
function panelContextItems(panel,target){
const {$,E,ask,breakOnWrite,build,copyText,debugTools,dockMenuItems,docking,download,editLocal,execute,explorerActions,inspectObject,refreshWatches,renderPanel,saveLocal,setPanel,solutionExplorer,state}=context;
const content=docking.content.get(panel),row=target.closest('tr,.search-result,.outline-row,.native-artifact,.native-diagnostic'),items=[];
 if(row)items.push({label:'Copy Row',action:()=>copyText(row.innerText??row.textContent)},{label:'Open / Navigate to Item',enabled:!!row.onclick,action:()=>row.click()});
 if(panel==='debug'&&target.closest('[data-local]')){const value=(state.inspectedLocals??state.debug?.locals??[])[Number(target.closest('[data-local]').dataset.local)];if(value){items.unshift({label:'Add Watch',action:()=>{if(!state.watches.includes(value.name))state.watches.push(value.name);refreshWatches();setPanel('watch');}},{label:'Edit Value…',enabled:()=>state.debug?.state==='paused'&&!value.reference&&value.name!=='this',action:()=>editLocal(value)},{label:'Inspect Object',enabled:!!value.reference,action:()=>inspectObject(value.name,value.reference)},{label:'Break on write',enabled:()=>state.debug?.state==='paused',action:()=>breakOnWrite({frameId:state.frameId,name:value.name})});}}
 if(panel==='watch'&&target.closest('[data-watch]')){const index=Number(target.closest('[data-watch]').dataset.watch),expression=state.watches[index];items.unshift({label:'Edit Expression…',action:async()=>{const text=await ask('Watch Expression',`<input id="edit-watch" value="${E(expression)}" autofocus>`,'Apply',()=>$('#edit-watch').value.trim());if(text){state.watches[index]=text;saveLocal();await refreshWatches();}}},{label:'Delete Watch',shortcut:'Delete',action:()=>{state.watches.splice(index,1);saveLocal();refreshWatches();renderPanel('debug');}});}
 if(panel==='breakpoints'&&target.closest('[data-bp]')){const bp=state.renderedBreakpoints[Number(target.closest('[data-bp]').dataset.bp)];if(bp)items.unshift({label:'Conditions / Hit Count / Logpoint…',action:async()=>{const value=await debugTools.editRule(bp.item,'Edit '+bp.kind+' breakpoint',{source:bp.kind==='source',func:bp.kind==='function'});if(value)await debugTools.updateRow(bp,value);}},{label:(bp.binding?.enabled??bp.item.enabled)===false?'Enable Breakpoint':'Disable Breakpoint',action:()=>debugTools.updateRow(bp,{...bp.item,enabled:(bp.binding?.enabled??bp.item.enabled)===false})},{label:'Delete Breakpoint',action:()=>debugTools.updateRow(bp,null,true)},null);}

 if(panel==='object'&&target.closest('[data-child]')&&state.objectContext){const value=state.objectContext.children[Number(target.closest('[data-child]').dataset.child)];if(value)items.unshift({label:'Break on write',enabled:()=>state.debug?.state==='paused',action:()=>breakOnWrite({reference:state.objectContext.reference,name:value.name})},{label:'Inspect Child',enabled:!!value.reference,action:()=>inspectObject(value.name,value.reference)});}
 if(panel==='stack'&&target.closest('[data-frame]'))items.unshift({label:'Switch to Frame',action:()=>target.closest('[data-frame]').click()});
 if(panel==='output')items.push({label:'Clear Output',action:()=>execute('clearOutput')});
 if(panel==='problems')items.push({label:'Build',shortcut:'Ctrl+Shift+B',action:()=>build()});
 if(panel==='heap'||panel==='diagnostics')items.push({label:'Collect Garbage',enabled:()=>!!state.debug,action:()=>execute('collect')});
 if(panel==='solution')return explorerActions.menu(solutionExplorer.model.roots[0],[]);
 const editable=target.closest('textarea,input:not([type=checkbox]):not([type=radio])');if(editable)items.push({label:'Select All',shortcut:'Ctrl+A',action:()=>{editable.focus();editable.select();}},{label:'Copy Selection',enabled:()=>editable.selectionStart!==editable.selectionEnd,action:()=>copyText(editable.value.slice(editable.selectionStart,editable.selectionEnd))});
 else items.push({label:'Select All Text',action:()=>{const doc=content.ownerDocument,range=doc.createRange();range.selectNodeContents(content);const selection=doc.getSelection();selection.removeAllRanges();selection.addRange(range);}});
 items.push({label:'Copy Panel Contents',action:()=>copyText(content.innerText??content.textContent)},{label:'Save Panel Contents…',action:()=>download(panel+'.txt',content.innerText??content.textContent,'text/plain')},null,{label:'Window',children:()=>dockMenuItems(panel)});return items;
}
function breakpointItems(uri,line){
const {state,sourceBreakpointAt,toggleBreakpoint,syncBreakpoints,setEditorDecorations,renderPanel,saveLocal,editBreakpoint,runtime,launch,setPanel,execute}=context;
const requests=state.breakpoints[uri]??[],bp=sourceBreakpointAt(requests,state.debug?.profile!=='managed-il'&&!state.buildDirty?state.debug?.breakpoints?.filter(b=>b.uri===uri)??[]:[],line),items=[{label:bp?'Delete Breakpoint':'Insert Breakpoint',shortcut:'F9',action:()=>toggleBreakpoint(uri,line)}];
 if(bp)items.push({label:bp.enabled===false?'Enable Breakpoint':'Disable Breakpoint',action:async()=>{bp.enabled=bp.enabled===false;await syncBreakpoints(uri);setEditorDecorations();renderPanel('breakpoints');saveLocal();}});
 items.push({label:'Conditions / Hit Count / Logpoint…',action:()=>editBreakpoint(uri,line)},{label:'Run to Cursor',shortcut:'Ctrl+F10',enabled:()=>!state.launchBusy&&state.debug?.state!=='running'&&state.debug?.profile!=='managed-il',action:()=>state.debug?.state==='paused'?runtime.request('runToCursor',{uri,line}):launch(true,{runToCursor:{uri,line},stopOnEntry:false})},null,{label:'Open Breakpoints Window',action:()=>setPanel('breakpoints')},{label:'Delete All Breakpoints',shortcut:'Ctrl+Shift+F9',action:()=>execute('removeBreakpoints')});return items;
}
function dockMenuItems(id){
const {docking,editorHostCommand,state,openFile,copyText,setPanel,solutionExplorer}=context;
const panel=docking.layout.require(id),location=docking.layout.locate(id),items=[{label:'Float',action:()=>docking.layout.float(id)},{label:'Open Separate Browser Window',action:()=>docking.host.popout(id)},{label:'Dock',children:['left','right','top','bottom'].map(side=>({label:side[0].toUpperCase()+side.slice(1),action:()=>docking.layout.dockRoot(id,side)}))},{label:'Join Tab Group',children:docking.layout.groups().filter(g=>!g.panels.includes(id)).map(g=>({label:g.active?docking.layout.require(g.active).title:'Empty document group',action:()=>docking.layout.dock(id,g.id)}))}];
 if(panel.kind==='tool')items.push({label:'Auto Hide',children:['left','right','bottom'].map(side=>({label:side,action:()=>docking.layout.autoHide(id,side)}))});
 if(id.startsWith('source:'))items.push(null,{label:'Save',action:()=>editorHostCommand('save',{uri:id.slice(7)})},{label:'New Vertical Tab Group',action:()=>{const group=docking.layout.groups().find(g=>g.panels.includes(id));if(group)docking.layout.dock(id,group.id,'right');}},{label:'New Horizontal Tab Group',action:()=>{const group=docking.layout.groups().find(g=>g.panels.includes(id));if(group)docking.layout.dock(id,group.id,'bottom');}},{label:'Close Other Documents',action:()=>{for(const uri of [...state.tabs])if('source:'+uri!==id){docking.layout.close('source:'+uri);state.tabs=state.tabs.filter(t=>t!==uri);}openFile(id.slice(7));}},{label:'Copy Full Path',action:()=>copyText((state.nativeMode?state.nativeWorkspace.root+'/':'')+id.slice(7))},{label:'Sync with Solution Explorer',action:()=>{setPanel('solution');solutionExplorer.reveal(id.slice(7),true);}});
 items.push(null,{label:'Close',enabled:panel.closable!==false,action:()=>{docking.layout.close(id);docking.host.onClose(id);}});return items;
}
return {editorContextItems,panelContextItems,breakpointItems,dockMenuItems};
}
