// Copyright (c) Microsoft Corporation. MIT; see THIRD-PARTY-NOTICES.md.
// Source commit 7b68d3e0b771a57d80098799406234efee479517; generated data only.
export const fluentDarkDefinitions = Object.freeze([
  ["TextFillColorPrimary","color","#FFFFFF"],
  ["TextFillColorSecondary","color","#C5FFFFFF"],
  ["TextFillColorTertiary","color","#87FFFFFF"],
  ["TextFillColorDisabled","color","#5DFFFFFF"],
  ["TextFillColorInverse","color","#E4000000"],
  ["AccentTextFillColorDisabled","color","#5DFFFFFF"],
  ["TextOnAccentFillColorSelectedText","color","#FFFFFF"],
  ["TextOnAccentFillColorPrimary","color","#000000"],
  ["TextOnAccentFillColorSecondary","color","#80000000"],
  ["TextOnAccentFillColorDisabled","color","#87FFFFFF"],
  ["ControlFillColorDefault","color","#0FFFFFFF"],
  ["ControlFillColorSecondary","color","#15FFFFFF"],
  ["ControlFillColorTertiary","color","#08FFFFFF"],
  ["ControlFillColorQuarternary","color","#0FFFFFFF"],
  ["ControlFillColorDisabled","color","#0BFFFFFF"],
  ["ControlFillColorTransparent","color","#00FFFFFF"],
  ["ControlFillColorInputActive","color","#B31E1E1E"],
  ["ControlStrongFillColorDefault","color","#8BFFFFFF"],
  ["ControlStrongFillColorDisabled","color","#3FFFFFFF"],
  ["ControlSolidFillColorDefault","color","#454545"],
  ["SubtleFillColorTransparent","color","#00FFFFFF"],
  ["SubtleFillColorSecondary","color","#0FFFFFFF"],
  ["SubtleFillColorTertiary","color","#0AFFFFFF"],
  ["SubtleFillColorDisabled","color","#00FFFFFF"],
  ["ControlAltFillColorTransparent","color","#00FFFFFF"],
  ["ControlAltFillColorSecondary","color","#19000000"],
  ["ControlAltFillColorTertiary","color","#0BFFFFFF"],
  ["ControlAltFillColorQuarternary","color","#12FFFFFF"],
  ["ControlAltFillColorDisabled","color","#00FFFFFF"],
  ["ControlOnImageFillColorDefault","color","#B31C1C1C"],
  ["ControlOnImageFillColorSecondary","color","#1A1A1A"],
  ["ControlOnImageFillColorTertiary","color","#131313"],
  ["ControlOnImageFillColorDisabled","color","#1E1E1E"],
  ["AccentFillColorDisabled","color","#28FFFFFF"],
  ["ControlStrokeColorDefault","color","#12FFFFFF"],
  ["ControlStrokeColorSecondary","color","#18FFFFFF"],
  ["ControlStrokeColorOnAccentDefault","color","#14FFFFFF"],
  ["ControlStrokeColorOnAccentSecondary","color","#23000000"],
  ["ControlStrokeColorOnAccentTertiary","color","#37000000"],
  ["ControlStrokeColorOnAccentDisabled","color","#33000000"],
  ["ControlStrokeColorForStrongFillWhenOnImage","color","#6B000000"],
  ["CardStrokeColorDefault","color","#19000000"],
  ["CardStrokeColorDefaultSolid","color","#1C1C1C"],
  ["ControlStrongStrokeColorDefault","color","#8BFFFFFF"],
  ["ControlStrongStrokeColorDisabled","color","#28FFFFFF"],
  ["SurfaceStrokeColorDefault","color","#66757575"],
  ["SurfaceStrokeColorFlyout","color","#33000000"],
  ["SurfaceStrokeColorInverse","color","#0F000000"],
  ["DividerStrokeColorDefault","color","#15FFFFFF"],
  ["FocusStrokeColorOuter","color","#FFFFFF"],
  ["FocusStrokeColorInner","color","#B3000000"],
  ["CardBackgroundFillColorDefault","color","#0DFFFFFF"],
  ["CardBackgroundFillColorSecondary","color","#08FFFFFF"],
  ["CardBackgroundFillColorTertiary","color","#12FFFFFF"],
  ["SmokeFillColorDefault","color","#4D000000"],
  ["LayerFillColorDefault","color","#4C3A3A3A"],
  ["LayerFillColorAlt","color","#0DFFFFFF"],
  ["LayerOnAcrylicFillColorDefault","color","#09FFFFFF"],
  ["LayerOnAccentAcrylicFillColorDefault","color","#09FFFFFF"],
  ["LayerOnMicaBaseAltFillColorDefault","color","#733A3A3A"],
  ["LayerOnMicaBaseAltFillColorSecondary","color","#0FFFFFFF"],
  ["LayerOnMicaBaseAltFillColorTertiary","color","#2C2C2C"],
  ["LayerOnMicaBaseAltFillColorTransparent","color","#00FFFFFF"],
  ["SolidBackgroundFillColorBase","color","#202020"],
  ["SolidBackgroundFillColorSecondary","color","#1C1C1C"],
  ["SolidBackgroundFillColorTertiary","color","#282828"],
  ["SolidBackgroundFillColorQuarternary","color","#2C2C2C"],
  ["SolidBackgroundFillColorQuinary","color","#333333"],
  ["SolidBackgroundFillColorSenary","color","#373737"],
  ["SolidBackgroundFillColorTransparent","color","#00202020"],
  ["SolidBackgroundFillColorBaseAlt","color","#0A0A0A"],
  ["SystemFillColorSuccess","color","#6CCB5F"],
  ["SystemFillColorCaution","color","#FCE100"],
  ["SystemFillColorCritical","color","#FF99A4"],
  ["SystemFillColorNeutral","color","#8BFFFFFF"],
  ["SystemFillColorSolidNeutral","color","#9D9D9D"],
  ["SystemFillColorAttentionBackground","color","#08FFFFFF"],
  ["SystemFillColorSuccessBackground","color","#393D1B"],
  ["SystemFillColorCautionBackground","color","#433519"],
  ["SystemFillColorCriticalBackground","color","#442726"],
  ["SystemFillColorNeutralBackground","color","#08FFFFFF"],
  ["SystemFillColorSolidAttentionBackground","color","#2E2E2E"],
  ["SystemFillColorSolidNeutralBackground","color","#2E2E2E"],
  ["TextFillColorPrimaryBrush","brush","{StaticResource TextFillColorPrimary}",1],
  ["TextFillColorSecondaryBrush","brush","{StaticResource TextFillColorSecondary}",1],
  ["TextFillColorTertiaryBrush","brush","{StaticResource TextFillColorTertiary}",1],
  ["TextFillColorDisabledBrush","brush","{StaticResource TextFillColorDisabled}",1],
  ["TextFillColorInverseBrush","brush","{StaticResource TextFillColorInverse}",1],
  ["AccentTextFillColorPrimaryBrush","brush","{ThemeResource SystemAccentColorLight3}",1],
  ["AccentTextFillColorSecondaryBrush","brush","{ThemeResource SystemAccentColorLight3}",1],
  ["AccentTextFillColorTertiaryBrush","brush","{ThemeResource SystemAccentColorLight2}",1],
  ["AccentTextFillColorDisabledBrush","brush","{StaticResource AccentTextFillColorDisabled}",1],
  ["TextOnAccentFillColorSelectedTextBrush","brush","{StaticResource TextOnAccentFillColorSelectedText}",1],
  ["TextOnAccentFillColorPrimaryBrush","brush","{StaticResource TextOnAccentFillColorPrimary}",1],
  ["TextOnAccentFillColorSecondaryBrush","brush","{StaticResource TextOnAccentFillColorSecondary}",1],
  ["TextOnAccentFillColorDisabledBrush","brush","{StaticResource TextOnAccentFillColorDisabled}",1],
  ["ControlFillColorDefaultBrush","brush","{StaticResource ControlFillColorDefault}",1],
  ["ControlFillColorSecondaryBrush","brush","{StaticResource ControlFillColorSecondary}",1],
  ["ControlFillColorTertiaryBrush","brush","{StaticResource ControlFillColorTertiary}",1],
  ["ControlFillColorQuarternaryBrush","brush","{StaticResource ControlFillColorQuarternary}",1],
  ["ControlFillColorDisabledBrush","brush","{StaticResource ControlFillColorDisabled}",1],
  ["ControlFillColorTransparentBrush","brush","{StaticResource ControlFillColorTransparent}",1],
  ["ControlFillColorInputActiveBrush","brush","{StaticResource ControlFillColorInputActive}",1],
  ["ControlStrongFillColorDefaultBrush","brush","{StaticResource ControlStrongFillColorDefault}",1],
  ["ControlStrongFillColorDisabledBrush","brush","{StaticResource ControlStrongFillColorDisabled}",1],
  ["ControlSolidFillColorDefaultBrush","brush","{StaticResource ControlSolidFillColorDefault}",1],
  ["SubtleFillColorTransparentBrush","brush","{StaticResource SubtleFillColorTransparent}",1],
  ["SubtleFillColorSecondaryBrush","brush","{StaticResource SubtleFillColorSecondary}",1],
  ["SubtleFillColorTertiaryBrush","brush","{StaticResource SubtleFillColorTertiary}",1],
  ["SubtleFillColorDisabledBrush","brush","{StaticResource SubtleFillColorDisabled}",1],
  ["ControlAltFillColorTransparentBrush","brush","{StaticResource ControlAltFillColorTransparent}",1],
  ["ControlAltFillColorSecondaryBrush","brush","{StaticResource ControlAltFillColorSecondary}",1],
  ["ControlAltFillColorTertiaryBrush","brush","{StaticResource ControlAltFillColorTertiary}",1],
  ["ControlAltFillColorQuarternaryBrush","brush","{StaticResource ControlAltFillColorQuarternary}",1],
  ["ControlAltFillColorDisabledBrush","brush","{StaticResource ControlAltFillColorDisabled}",1],
  ["ControlOnImageFillColorDefaultBrush","brush","{StaticResource ControlOnImageFillColorDefault}",1],
  ["ControlOnImageFillColorSecondaryBrush","brush","{StaticResource ControlOnImageFillColorSecondary}",1],
  ["ControlOnImageFillColorTertiaryBrush","brush","{StaticResource ControlOnImageFillColorTertiary}",1],
  ["ControlOnImageFillColorDisabledBrush","brush","{StaticResource ControlOnImageFillColorDisabled}",1],
  ["AccentFillColorSelectedTextBackgroundBrush","brush","{ThemeResource SystemAccentColor}",1],
  ["AccentFillColorDefaultBrush","brush","{ThemeResource SystemAccentColorLight2}",1],
  ["AccentFillColorSecondaryBrush","brush","{ThemeResource SystemAccentColorLight2}",0.9],
  ["AccentFillColorTertiaryBrush","brush","{ThemeResource SystemAccentColorLight2}",0.8],
  ["AccentFillColorDisabledBrush","brush","{StaticResource AccentFillColorDisabled}",1],
  ["ControlStrokeColorDefaultBrush","brush","{StaticResource ControlStrokeColorDefault}",1],
  ["ControlStrokeColorSecondaryBrush","brush","{StaticResource ControlStrokeColorSecondary}",1],
  ["ControlStrokeColorOnAccentDefaultBrush","brush","{StaticResource ControlStrokeColorOnAccentDefault}",1],
  ["ControlStrokeColorOnAccentSecondaryBrush","brush","{StaticResource ControlStrokeColorOnAccentSecondary}",1],
  ["ControlStrokeColorOnAccentTertiaryBrush","brush","{StaticResource ControlStrokeColorOnAccentTertiary}",1],
  ["ControlStrokeColorOnAccentDisabledBrush","brush","{StaticResource ControlStrokeColorOnAccentDisabled}",1],
  ["ControlStrokeColorForStrongFillWhenOnImageBrush","brush","{StaticResource ControlStrokeColorForStrongFillWhenOnImage}",1],
  ["CardStrokeColorDefaultBrush","brush","{StaticResource CardStrokeColorDefault}",1],
  ["CardStrokeColorDefaultSolidBrush","brush","{StaticResource CardStrokeColorDefaultSolid}",1],
  ["ControlStrongStrokeColorDefaultBrush","brush","{StaticResource ControlStrongStrokeColorDefault}",1],
  ["ControlStrongStrokeColorDisabledBrush","brush","{StaticResource ControlStrongStrokeColorDisabled}",1],
  ["SurfaceStrokeColorDefaultBrush","brush","{StaticResource SurfaceStrokeColorDefault}",1],
  ["SurfaceStrokeColorFlyoutBrush","brush","{StaticResource SurfaceStrokeColorFlyout}",1],
  ["SurfaceStrokeColorInverseBrush","brush","{StaticResource SurfaceStrokeColorInverse}",1],
  ["DividerStrokeColorDefaultBrush","brush","{StaticResource DividerStrokeColorDefault}",1],
  ["FocusStrokeColorOuterBrush","brush","{StaticResource FocusStrokeColorOuter}",1],
  ["FocusStrokeColorInnerBrush","brush","{StaticResource FocusStrokeColorInner}",1],
  ["CardBackgroundFillColorDefaultBrush","brush","{StaticResource CardBackgroundFillColorDefault}",1],
  ["CardBackgroundFillColorSecondaryBrush","brush","{StaticResource CardBackgroundFillColorSecondary}",1],
  ["CardBackgroundFillColorTertiaryBrush","brush","{StaticResource CardBackgroundFillColorTertiary}",1],
  ["SmokeFillColorDefaultBrush","brush","{StaticResource SmokeFillColorDefault}",1],
  ["LayerFillColorDefaultBrush","brush","{StaticResource LayerFillColorDefault}",1],
  ["LayerFillColorAltBrush","brush","{StaticResource LayerFillColorAlt}",1],
  ["LayerOnAcrylicFillColorDefaultBrush","brush","{StaticResource LayerOnAcrylicFillColorDefault}",1],
  ["LayerOnAccentAcrylicFillColorDefaultBrush","brush","{StaticResource LayerOnAccentAcrylicFillColorDefault}",1],
  ["LayerOnMicaBaseAltFillColorDefaultBrush","brush","{StaticResource LayerOnMicaBaseAltFillColorDefault}",1],
  ["LayerOnMicaBaseAltFillColorSecondaryBrush","brush","{StaticResource LayerOnMicaBaseAltFillColorSecondary}",1],
  ["LayerOnMicaBaseAltFillColorTertiaryBrush","brush","{StaticResource LayerOnMicaBaseAltFillColorTertiary}",1],
  ["LayerOnMicaBaseAltFillColorTransparentBrush","brush","{StaticResource LayerOnMicaBaseAltFillColorTransparent}",1],
  ["SolidBackgroundFillColorBaseBrush","brush","{StaticResource SolidBackgroundFillColorBase}",1],
  ["SolidBackgroundFillColorSecondaryBrush","brush","{StaticResource SolidBackgroundFillColorSecondary}",1],
  ["SolidBackgroundFillColorTertiaryBrush","brush","{StaticResource SolidBackgroundFillColorTertiary}",1],
  ["SolidBackgroundFillColorQuarternaryBrush","brush","{StaticResource SolidBackgroundFillColorQuarternary}",1],
  ["SolidBackgroundFillColorQuinaryBrush","brush","{StaticResource SolidBackgroundFillColorQuinary}",1],
  ["SolidBackgroundFillColorSenaryBrush","brush","{StaticResource SolidBackgroundFillColorSenary}",1],
  ["SolidBackgroundFillColorBaseAltBrush","brush","{StaticResource SolidBackgroundFillColorBaseAlt}",1],
  ["SystemFillColorAttentionBrush","brush","{ThemeResource SystemAccentColorLight2}",1],
  ["SystemFillColorSuccessBrush","brush","{StaticResource SystemFillColorSuccess}",1],
  ["SystemFillColorCautionBrush","brush","{StaticResource SystemFillColorCaution}",1],
  ["SystemFillColorCriticalBrush","brush","{StaticResource SystemFillColorCritical}",1],
  ["SystemFillColorNeutralBrush","brush","{StaticResource SystemFillColorNeutral}",1],
  ["SystemFillColorSolidNeutralBrush","brush","{StaticResource SystemFillColorSolidNeutral}",1],
  ["SystemFillColorAttentionBackgroundBrush","brush","{StaticResource SystemFillColorAttentionBackground}",1],
  ["SystemFillColorSuccessBackgroundBrush","brush","{StaticResource SystemFillColorSuccessBackground}",1],
  ["SystemFillColorCautionBackgroundBrush","brush","{StaticResource SystemFillColorCautionBackground}",1],
  ["SystemFillColorCriticalBackgroundBrush","brush","{StaticResource SystemFillColorCriticalBackground}",1],
  ["SystemFillColorNeutralBackgroundBrush","brush","{StaticResource SystemFillColorNeutralBackground}",1],
  ["SystemFillColorSolidAttentionBackgroundBrush","brush","{StaticResource SystemFillColorSolidAttentionBackground}",1],
  ["SystemFillColorSolidNeutralBackgroundBrush","brush","{StaticResource SystemFillColorSolidNeutralBackground}",1],
  ["SystemColorWindowTextColorBrush","brush","#FF00FF",1],
  ["SystemColorWindowColorBrush","brush","#FF00FF",1],
  ["SystemColorButtonFaceColorBrush","brush","#FF00FF",1],
  ["SystemColorButtonTextColorBrush","brush","#FF00FF",1],
  ["SystemColorHighlightColorBrush","brush","#FF00FF",1],
  ["SystemColorHighlightTextColorBrush","brush","#FF00FF",1],
  ["SystemColorHotlightColorBrush","brush","#FF00FF",1],
  ["SystemColorGrayTextColorBrush","brush","#FF00FF",1],
  [
    "ControlElevationBorderBrush",
    "linear",
    [
      [
        0.33,
        "{StaticResource ControlStrokeColorSecondary}"
      ],
      [
        1,
        "{StaticResource ControlStrokeColorDefault}"
      ]
    ],
    {
      "MappingMode": "Absolute",
      "StartPoint": "0,0",
      "EndPoint": "0,3"
    }
  ],
  [
    "CircleElevationBorderBrush",
    "linear",
    [
      [
        0.7,
        "{StaticResource ControlStrokeColorSecondary}"
      ],
      [
        0.5,
        "{StaticResource ControlStrokeColorDefault}"
      ]
    ],
    {
      "MappingMode": "RelativeToBoundingBox",
      "StartPoint": "0,0",
      "EndPoint": "0,1"
    }
  ],
  [
    "AccentControlElevationBorderBrush",
    "linear",
    [
      [
        0.33,
        "{StaticResource ControlStrokeColorOnAccentSecondary}"
      ],
      [
        1,
        "{StaticResource ControlStrokeColorOnAccentDefault}"
      ]
    ],
    {
      "MappingMode": "Absolute",
      "StartPoint": "0,0",
      "EndPoint": "0,3",
      "RelativeTransform": {
        "ScaleY": -1,
        "CenterY": 0.5
      }
    }
  ]
]);
