// Copyright (c) Microsoft Corporation. MIT; see THIRD-PARTY-NOTICES.md.
// Source commit 7b68d3e0b771a57d80098799406234efee479517; generated data only.
export const fluentLightDefinitions = Object.freeze([
  ["TextFillColorPrimary","color","#E4000000"],
  ["TextFillColorSecondary","color","#9E000000"],
  ["TextFillColorTertiary","color","#72000000"],
  ["TextFillColorDisabled","color","#5C000000"],
  ["TextFillColorInverse","color","#FFFFFF"],
  ["AccentTextFillColorDisabled","color","#5C000000"],
  ["TextOnAccentFillColorSelectedText","color","#FFFFFF"],
  ["TextOnAccentFillColorPrimary","color","#FFFFFF"],
  ["TextOnAccentFillColorSecondary","color","#B3FFFFFF"],
  ["TextOnAccentFillColorDisabled","color","#FFFFFF"],
  ["ControlFillColorDefault","color","#B3FFFFFF"],
  ["ControlFillColorSecondary","color","#80F9F9F9"],
  ["ControlFillColorTertiary","color","#4DF9F9F9"],
  ["ControlFillColorQuarternary","color","#C2F3F3F3"],
  ["ControlFillColorDisabled","color","#4DF9F9F9"],
  ["ControlFillColorTransparent","color","#00FFFFFF"],
  ["ControlFillColorInputActive","color","#FFFFFF"],
  ["ControlStrongFillColorDefault","color","#72000000"],
  ["ControlStrongFillColorDisabled","color","#51000000"],
  ["ControlSolidFillColorDefault","color","#FFFFFF"],
  ["SubtleFillColorTransparent","color","#00FFFFFF"],
  ["SubtleFillColorSecondary","color","#09000000"],
  ["SubtleFillColorTertiary","color","#06000000"],
  ["SubtleFillColorDisabled","color","#00FFFFFF"],
  ["ControlAltFillColorTransparent","color","#00FFFFFF"],
  ["ControlAltFillColorSecondary","color","#06000000"],
  ["ControlAltFillColorTertiary","color","#0F000000"],
  ["ControlAltFillColorQuarternary","color","#18000000"],
  ["ControlAltFillColorDisabled","color","#00FFFFFF"],
  ["ControlOnImageFillColorDefault","color","#C9FFFFFF"],
  ["ControlOnImageFillColorSecondary","color","#F3F3F3"],
  ["ControlOnImageFillColorTertiary","color","#EBEBEB"],
  ["ControlOnImageFillColorDisabled","color","#00FFFFFF"],
  ["AccentFillColorDisabled","color","#37000000"],
  ["ControlStrokeColorDefault","color","#0F000000"],
  ["ControlStrokeColorSecondary","color","#29000000"],
  ["ControlStrokeColorOnAccentDefault","color","#14FFFFFF"],
  ["ControlStrokeColorOnAccentSecondary","color","#66000000"],
  ["ControlStrokeColorOnAccentTertiary","color","#37000000"],
  ["ControlStrokeColorOnAccentDisabled","color","#0F000000"],
  ["ControlStrokeColorForStrongFillWhenOnImage","color","#59FFFFFF"],
  ["CardStrokeColorDefault","color","#0F000000"],
  ["CardStrokeColorDefaultSolid","color","#EBEBEB"],
  ["ControlStrongStrokeColorDefault","color","#72000000"],
  ["ControlStrongStrokeColorDisabled","color","#37000000"],
  ["SurfaceStrokeColorDefault","color","#66757575"],
  ["SurfaceStrokeColorFlyout","color","#0F000000"],
  ["SurfaceStrokeColorInverse","color","#15FFFFFF"],
  ["DividerStrokeColorDefault","color","#0F000000"],
  ["FocusStrokeColorOuter","color","#E4000000"],
  ["FocusStrokeColorInner","color","#B3FFFFFF"],
  ["CardBackgroundFillColorDefault","color","#B3FFFFFF"],
  ["CardBackgroundFillColorSecondary","color","#80F6F6F6"],
  ["CardBackgroundFillColorTertiary","color","#FFFFFF"],
  ["SmokeFillColorDefault","color","#4D000000"],
  ["LayerFillColorDefault","color","#80FFFFFF"],
  ["LayerFillColorAlt","color","#FFFFFF"],
  ["LayerOnAcrylicFillColorDefault","color","#40FFFFFF"],
  ["LayerOnAccentAcrylicFillColorDefault","color","#40FFFFFF"],
  ["LayerOnMicaBaseAltFillColorDefault","color","#B3FFFFFF"],
  ["LayerOnMicaBaseAltFillColorSecondary","color","#0A000000"],
  ["LayerOnMicaBaseAltFillColorTertiary","color","#F9F9F9"],
  ["LayerOnMicaBaseAltFillColorTransparent","color","#00000000"],
  ["SolidBackgroundFillColorBase","color","#F3F3F3"],
  ["SolidBackgroundFillColorSecondary","color","#EEEEEE"],
  ["SolidBackgroundFillColorTertiary","color","#F9F9F9"],
  ["SolidBackgroundFillColorQuarternary","color","#FFFFFF"],
  ["SolidBackgroundFillColorQuinary","color","#FDFDFD"],
  ["SolidBackgroundFillColorSenary","color","#FFFFFF"],
  ["SolidBackgroundFillColorTransparent","color","#00F3F3F3"],
  ["SolidBackgroundFillColorBaseAlt","color","#DADADA"],
  ["SystemFillColorSuccess","color","#0F7B0F"],
  ["SystemFillColorCaution","color","#9D5D00"],
  ["SystemFillColorCritical","color","#C42B1C"],
  ["SystemFillColorNeutral","color","#72000000"],
  ["SystemFillColorSolidNeutral","color","#8A8A8A"],
  ["SystemFillColorAttentionBackground","color","#80F6F6F6"],
  ["SystemFillColorSuccessBackground","color","#DFF6DD"],
  ["SystemFillColorCautionBackground","color","#FFF4CE"],
  ["SystemFillColorCriticalBackground","color","#FDE7E9"],
  ["SystemFillColorNeutralBackground","color","#06000000"],
  ["SystemFillColorSolidAttentionBackground","color","#F7F7F7"],
  ["SystemFillColorSolidNeutralBackground","color","#F3F3F3"],
  ["TextFillColorPrimaryBrush","brush","{StaticResource TextFillColorPrimary}",1],
  ["TextFillColorSecondaryBrush","brush","{StaticResource TextFillColorSecondary}",1],
  ["TextFillColorTertiaryBrush","brush","{StaticResource TextFillColorTertiary}",1],
  ["TextFillColorDisabledBrush","brush","{StaticResource TextFillColorDisabled}",1],
  ["TextFillColorInverseBrush","brush","{StaticResource TextFillColorInverse}",1],
  ["AccentTextFillColorPrimaryBrush","brush","{ThemeResource SystemAccentColorDark2}",1],
  ["AccentTextFillColorSecondaryBrush","brush","{ThemeResource SystemAccentColorDark3}",1],
  ["AccentTextFillColorTertiaryBrush","brush","{ThemeResource SystemAccentColorDark1}",1],
  ["AccentTextFillColorDisabledBrush","brush","{StaticResource AccentTextFillColorDisabled}",1],
  ["TextOnAccentFillColorSelectedTextBrush","brush","{StaticResource TextOnAccentFillColorSelectedText}",1],
  ["TextOnAccentFillColorPrimaryBrush","brush","{StaticResource TextOnAccentFillColorPrimary}",1],
  ["TextOnAccentFillColorSecondaryBrush","brush","{StaticResource TextOnAccentFillColorSecondary}",1],
  ["TextOnAccentFillColorDisabledBrush","brush","{StaticResource TextOnAccentFillColorDisabled}",1],
  ["ControlFillColorDefaultBrush","brush","{StaticResource ControlFillColorDefault}",1],
  ["ControlFillColorSecondaryBrush","brush","{StaticResource ControlFillColorSecondary}",1],
  ["ControlFillColorTertiaryBrush","brush","{StaticResource ControlFillColorTertiary}",1],
  ["ControlFillColorQuarternaryBrush","brush","{StaticResource ControlFillColorQuarternary}",1],
  ["ControlFillColorDisabledBrush","brush","{StaticResource ControlFillColorDisabled}",1],
  ["ControlFillColorTransparentBrush","brush","{StaticResource ControlFillColorTransparent}",1],
  ["ControlFillColorInputActiveBrush","brush","{StaticResource ControlFillColorInputActive}",1],
  ["ControlStrongFillColorDefaultBrush","brush","{StaticResource ControlStrongFillColorDefault}",1],
  ["ControlStrongFillColorDisabledBrush","brush","{StaticResource ControlStrongFillColorDisabled}",1],
  ["ControlSolidFillColorDefaultBrush","brush","{StaticResource ControlSolidFillColorDefault}",1],
  ["SubtleFillColorTransparentBrush","brush","{StaticResource SubtleFillColorTransparent}",1],
  ["SubtleFillColorSecondaryBrush","brush","{StaticResource SubtleFillColorSecondary}",1],
  ["SubtleFillColorTertiaryBrush","brush","{StaticResource SubtleFillColorTertiary}",1],
  ["SubtleFillColorDisabledBrush","brush","{StaticResource SubtleFillColorDisabled}",1],
  ["ControlAltFillColorTransparentBrush","brush","{StaticResource ControlAltFillColorTransparent}",1],
  ["ControlAltFillColorSecondaryBrush","brush","{StaticResource ControlAltFillColorSecondary}",1],
  ["ControlAltFillColorTertiaryBrush","brush","{StaticResource ControlAltFillColorTertiary}",1],
  ["ControlAltFillColorQuarternaryBrush","brush","{StaticResource ControlAltFillColorQuarternary}",1],
  ["ControlAltFillColorDisabledBrush","brush","{StaticResource ControlAltFillColorDisabled}",1],
  ["ControlOnImageFillColorDefaultBrush","brush","{StaticResource ControlOnImageFillColorDefault}",1],
  ["ControlOnImageFillColorSecondaryBrush","brush","{StaticResource ControlOnImageFillColorSecondary}",1],
  ["ControlOnImageFillColorTertiaryBrush","brush","{StaticResource ControlOnImageFillColorTertiary}",1],
  ["ControlOnImageFillColorDisabledBrush","brush","{StaticResource ControlOnImageFillColorDisabled}",1],
  ["AccentFillColorSelectedTextBackgroundBrush","brush","{ThemeResource SystemAccentColor}",1],
  ["AccentFillColorDefaultBrush","brush","{ThemeResource SystemAccentColorDark1}",1],
  ["AccentFillColorSecondaryBrush","brush","{ThemeResource SystemAccentColorDark1}",0.9],
  ["AccentFillColorTertiaryBrush","brush","{ThemeResource SystemAccentColorDark1}",0.8],
  ["AccentFillColorDisabledBrush","brush","{StaticResource AccentFillColorDisabled}",1],
  ["ControlStrokeColorDefaultBrush","brush","{StaticResource ControlStrokeColorDefault}",1],
  ["ControlStrokeColorSecondaryBrush","brush","{StaticResource ControlStrokeColorSecondary}",1],
  ["ControlStrokeColorOnAccentDefaultBrush","brush","{StaticResource ControlStrokeColorOnAccentDefault}",1],
  ["ControlStrokeColorOnAccentSecondaryBrush","brush","{StaticResource ControlStrokeColorOnAccentSecondary}",1],
  ["ControlStrokeColorOnAccentTertiaryBrush","brush","{StaticResource ControlStrokeColorOnAccentTertiary}",1],
  ["ControlStrokeColorOnAccentDisabledBrush","brush","{StaticResource ControlStrokeColorOnAccentDisabled}",1],
  ["ControlStrokeColorForStrongFillWhenOnImageBrush","brush","{StaticResource ControlStrokeColorForStrongFillWhenOnImage}",1],
  ["CardStrokeColorDefaultBrush","brush","{StaticResource CardStrokeColorDefault}",1],
  ["CardStrokeColorDefaultSolidBrush","brush","{StaticResource CardStrokeColorDefaultSolid}",1],
  ["ControlStrongStrokeColorDefaultBrush","brush","{StaticResource ControlStrongStrokeColorDefault}",1],
  ["ControlStrongStrokeColorDisabledBrush","brush","{StaticResource ControlStrongStrokeColorDisabled}",1],
  ["SurfaceStrokeColorDefaultBrush","brush","{StaticResource SurfaceStrokeColorDefault}",1],
  ["SurfaceStrokeColorFlyoutBrush","brush","{StaticResource SurfaceStrokeColorFlyout}",1],
  ["SurfaceStrokeColorInverseBrush","brush","{StaticResource SurfaceStrokeColorInverse}",1],
  ["DividerStrokeColorDefaultBrush","brush","{StaticResource DividerStrokeColorDefault}",1],
  ["FocusStrokeColorOuterBrush","brush","{StaticResource FocusStrokeColorOuter}",1],
  ["FocusStrokeColorInnerBrush","brush","{StaticResource FocusStrokeColorInner}",1],
  ["CardBackgroundFillColorDefaultBrush","brush","{StaticResource CardBackgroundFillColorDefault}",1],
  ["CardBackgroundFillColorSecondaryBrush","brush","{StaticResource CardBackgroundFillColorSecondary}",1],
  ["CardBackgroundFillColorTertiaryBrush","brush","{StaticResource CardBackgroundFillColorTertiary}",1],
  ["SmokeFillColorDefaultBrush","brush","{StaticResource SmokeFillColorDefault}",1],
  ["LayerFillColorDefaultBrush","brush","{StaticResource LayerFillColorDefault}",1],
  ["LayerFillColorAltBrush","brush","{StaticResource LayerFillColorAlt}",1],
  ["LayerOnAcrylicFillColorDefaultBrush","brush","{StaticResource LayerOnAcrylicFillColorDefault}",1],
  ["LayerOnAccentAcrylicFillColorDefaultBrush","brush","{StaticResource LayerOnAccentAcrylicFillColorDefault}",1],
  ["LayerOnMicaBaseAltFillColorDefaultBrush","brush","{StaticResource LayerOnMicaBaseAltFillColorDefault}",1],
  ["LayerOnMicaBaseAltFillColorSecondaryBrush","brush","{StaticResource LayerOnMicaBaseAltFillColorSecondary}",1],
  ["LayerOnMicaBaseAltFillColorTertiaryBrush","brush","{StaticResource LayerOnMicaBaseAltFillColorTertiary}",1],
  ["LayerOnMicaBaseAltFillColorTransparentBrush","brush","{StaticResource LayerOnMicaBaseAltFillColorTransparent}",1],
  ["SolidBackgroundFillColorBaseBrush","brush","{StaticResource SolidBackgroundFillColorBase}",1],
  ["SolidBackgroundFillColorSecondaryBrush","brush","{StaticResource SolidBackgroundFillColorSecondary}",1],
  ["SolidBackgroundFillColorTertiaryBrush","brush","{StaticResource SolidBackgroundFillColorTertiary}",1],
  ["SolidBackgroundFillColorQuarternaryBrush","brush","{StaticResource SolidBackgroundFillColorQuarternary}",1],
  ["SolidBackgroundFillColorQuinaryBrush","brush","{StaticResource SolidBackgroundFillColorQuinary}",1],
  ["SolidBackgroundFillColorSenaryBrush","brush","{StaticResource SolidBackgroundFillColorSenary}",1],
  ["SolidBackgroundFillColorBaseAltBrush","brush","{StaticResource SolidBackgroundFillColorBaseAlt}",1],
  ["SystemFillColorAttentionBrush","brush","{ThemeResource SystemAccentColor}",1],
  ["SystemFillColorSuccessBrush","brush","{StaticResource SystemFillColorSuccess}",1],
  ["SystemFillColorCautionBrush","brush","{StaticResource SystemFillColorCaution}",1],
  ["SystemFillColorCriticalBrush","brush","{StaticResource SystemFillColorCritical}",1],
  ["SystemFillColorNeutralBrush","brush","{StaticResource SystemFillColorNeutral}",1],
  ["SystemFillColorSolidNeutralBrush","brush","{StaticResource SystemFillColorSolidNeutral}",1],
  ["SystemFillColorAttentionBackgroundBrush","brush","{StaticResource SystemFillColorAttentionBackground}",1],
  ["SystemFillColorSuccessBackgroundBrush","brush","{StaticResource SystemFillColorSuccessBackground}",1],
  ["SystemFillColorCautionBackgroundBrush","brush","{StaticResource SystemFillColorCautionBackground}",1],
  ["SystemFillColorCriticalBackgroundBrush","brush","{StaticResource SystemFillColorCriticalBackground}",1],
  ["SystemFillColorNeutralBackgroundBrush","brush","{StaticResource SystemFillColorNeutralBackground}",1],
  ["SystemFillColorSolidAttentionBackgroundBrush","brush","{StaticResource SystemFillColorSolidAttentionBackground}",1],
  ["SystemFillColorSolidNeutralBackgroundBrush","brush","{StaticResource SystemFillColorSolidNeutralBackground}",1],
  [
    "ControlElevationBorderBrush",
    "linear",
    [
      [
        0.33,
        "{StaticResource ControlStrokeColorSecondary}"
      ],
      [
        1,
        "{StaticResource ControlStrokeColorDefault}"
      ]
    ],
    {
      "MappingMode": "Absolute",
      "StartPoint": "0,0",
      "EndPoint": "0,3",
      "RelativeTransform": {
        "ScaleY": -1,
        "CenterY": 0.5
      }
    }
  ],
  [
    "CircleElevationBorderBrush",
    "linear",
    [
      [
        0.5,
        "{StaticResource ControlStrokeColorDefault}"
      ],
      [
        0.7,
        "{StaticResource ControlStrokeColorSecondary}"
      ]
    ],
    {
      "MappingMode": "RelativeToBoundingBox",
      "StartPoint": "0,0",
      "EndPoint": "0,1"
    }
  ],
  [
    "AccentControlElevationBorderBrush",
    "linear",
    [
      [
        0.33,
        "{StaticResource ControlStrokeColorOnAccentSecondary}"
      ],
      [
        1,
        "{StaticResource ControlStrokeColorOnAccentDefault}"
      ]
    ],
    {
      "MappingMode": "Absolute",
      "StartPoint": "0,0",
      "EndPoint": "0,3",
      "RelativeTransform": {
        "ScaleY": -1,
        "CenterY": 0.5
      }
    }
  ],
  ["SystemColorWindowTextColorBrush","brush","#FF00FF",1],
  ["SystemColorWindowColorBrush","brush","#FF00FF",1],
  ["SystemColorButtonFaceColorBrush","brush","#FF00FF",1],
  ["SystemColorButtonTextColorBrush","brush","#FF00FF",1],
  ["SystemColorHighlightColorBrush","brush","#FF00FF",1],
  ["SystemColorHighlightTextColorBrush","brush","#FF00FF",1],
  ["SystemColorHotlightColorBrush","brush","#FF00FF",1],
  ["SystemColorGrayTextColorBrush","brush","#FF00FF",1]
]);
