import { SourceText, BoundedCache } from '@sharpforge/text';
import { parse } from '@sharpforge/syntax';
import { Compilation } from '@sharpforge/compiler';
/** Versioned workspace. Unchanged documents retain their complete syntax trees; semantic binding is compilation-wide. */
export class Workspace {
  constructor({maxDocumentLength=2_000_000,maxDocuments=100,tokenCacheSize=32768,extensions=null,extensionOptions={},additionalFiles=[],compilationOptions={}}={}){this.compilationOptions={...compilationOptions};this.extensions=extensions;this.extensionOptions=extensionOptions;this.additionalFiles=additionalFiles;this.generatedDocuments=new Map();this.documents=new Map();this.tokenCache=new BoundedCache(tokenCacheSize);this.revision=0;this.result=null;this.maxDocumentLength=maxDocumentLength;this.maxDocuments=maxDocuments;this.metrics={parsedDocuments:0,syntaxCacheHits:0,compilationCacheHits:0};}
  update(uri,text,version){
    if(typeof uri==='string'&&uri.startsWith('generated://'))throw new Error('Generated documents are read-only');if(typeof uri!=='string'||!uri||typeof text!=='string')throw new TypeError('A URI and source string are required');if(text.length>this.maxDocumentLength)throw new RangeError('Document exceeds the source size limit');
    const old=this.documents.get(uri);version??=(old?.source.version??0)+1;if(old&&version<=old.source.version)return false;
    if(old?.source.text===text){old.source=new SourceText(text,uri,version);old.parsed=null;this.result=null;this.revision++;return true;}
    if(!old&&this.documents.size>=this.maxDocuments)throw new RangeError('Workspace document limit exceeded');
    this.documents.set(uri,{source:new SourceText(text,uri,version),parsed:null});this.revision++;this.result=null;return true;
  }
  change(uri,changes,version){let source=this.documents.get(uri)?.source;if(!source)throw new Error('Document is not open');if(version<=source.version)return false;for(const change of changes){if(change.range){const start=source.offsetAt(change.range.start),end=source.offsetAt(change.range.end);source=source.withChange(start,end-start,change.text);}else source=new SourceText(change.text,uri,version);}return this.update(uri,source.text,version);}
  remove(uri){if(this.documents.delete(uri)){this.revision++;this.result=null;}}
  syntax(uri){const d=this.documents.get(uri)??this.generatedDocuments.get(uri);if(!d)throw new Error(`Unknown document '${uri}'`);if(d.parsed){this.metrics.syntaxCacheHits++;return d.parsed;}const start=performance.now();d.parsed=parse(d.source,this.tokenCache);d.parseMs=performance.now()-start;this.metrics.parsedDocuments++;return d.parsed;}
  compile({signal,...provided}={}){
    const options={...this.compilationOptions,...provided};
    if(signal?.aborted)throw new DOMException('Compilation cancelled','AbortError');const optionKey=JSON.stringify([Object.keys(options).sort().map(key=>[key,options[key]]),this.extensions?.revision??0,this.extensionOptions,this.additionalFiles]);if(this.result&&this.resultExtensions===this.extensions&&this.resultOptionKey===optionKey){this.metrics.compilationCacheHits++;return this.result;}
    const start=performance.now(),beforeParsed=this.metrics.parsedDocuments,files=[...this.documents.keys()].map(uri=>this.syntax(uri));if(!files.length)return {success:false,image:null,diagnostics:[],symbols:[],references:[],metrics:{}};
    const parseMs=performance.now()-start;let generated={files:[],diagnostics:[]};if(!this.extensions)this.generatedDocuments.clear();if(this.extensions){generated=this.extensions.generate(files.map(f=>f.source),{options:this.extensionOptions,additionalFiles:this.additionalFiles,signal});const next=new Map();for(const file of generated.files){const previous=this.generatedDocuments.get(file.uri);next.set(file.uri,previous?.source.text===file.text?previous:{source:new SourceText(file.text,file.uri,(previous?.source.version??0)+1),parsed:null,generated:true});}this.generatedDocuments=next;files.push(...[...next.keys()].map(uri=>this.syntax(uri)));}const result=new Compilation(files,options).build();if(this.extensions){result.diagnostics.push(...generated.diagnostics,...this.extensions.analyze(result,files,{options:this.extensionOptions,signal}));result.success=!result.diagnostics.some(d=>d.severity==='error');if(!result.success)result.image=null;result.metrics.errors=result.diagnostics.filter(d=>d.severity==='error').length;result.metrics.warnings=result.diagnostics.filter(d=>d.severity==='warning').length;result.metrics.extensions={...this.extensions.metrics};result.generatedSources=generated.files;}if(signal?.aborted)throw new DOMException('Compilation cancelled','AbortError');result.metrics.totalMs=performance.now()-start;result.metrics.parseMs=parseMs;result.metrics.parsedThisCompilation=this.metrics.parsedDocuments-beforeParsed;result.metrics.reusedDocuments=files.length-result.metrics.parsedThisCompilation;result.revision=this.revision;this.result=result;this.resultOptionKey=optionKey;this.resultExtensions=this.extensions;return result;
  }
  exportProject(){return {format:'sharpforge-project',version:1,files:[...this.documents.values()].map(d=>({uri:d.source.uri,text:d.source.text,version:d.source.version}))};}
  importProject(project){if(project?.format!=='sharpforge-project'||project.version!==1||!Array.isArray(project.files))throw new Error('Not a SharpForge project');if(project.files.length>this.maxDocuments)throw new Error('Too many documents');const next=new Workspace({maxDocumentLength:this.maxDocumentLength,maxDocuments:this.maxDocuments});for(const file of project.files)next.update(file.uri,file.text,1);this.documents=next.documents;this.generatedDocuments.clear();this.revision++;this.result=null;}
}
