// Generated by SharpForge Designer. Edit the design document or link this C# file with Connect C#.
public class DesignedView
{
    public static Microsoft.UI.Xaml.Window v_window;
    public static Microsoft.UI.Xaml.Controls.Canvas v_canvas;
    public static Microsoft.UI.Xaml.Controls.TextBlock v_title;
    public static Microsoft.UI.Xaml.Controls.TextBlock v_caption;
    public static Microsoft.UI.Xaml.Controls.Button v_action;
    public static Microsoft.UI.Xaml.Controls.TextBox v_TextBox_1;
    public static Microsoft.UI.Xaml.Window Create()
    {
        Microsoft.UI.Xaml.Style style_Accent = new Microsoft.UI.Xaml.Style("Microsoft.UI.Xaml.Controls.Button");
        style_Accent.Setters.Add(new Microsoft.UI.Xaml.Setter(Microsoft.UI.Xaml.Controls.Button.BackgroundProperty, new Microsoft.UI.Xaml.Media.SolidColorBrush(Windows.UI.Color.FromArgb(255, 0, 95, 184))));
        style_Accent.Setters.Add(new Microsoft.UI.Xaml.Setter(Microsoft.UI.Xaml.Controls.Button.ForegroundProperty, new Microsoft.UI.Xaml.Media.SolidColorBrush(Windows.UI.Color.FromArgb(255, 255, 255, 255))));
        style_Accent.Setters.Add(new Microsoft.UI.Xaml.Setter(Microsoft.UI.Xaml.Controls.Button.CornerRadiusProperty, new Microsoft.UI.Xaml.CornerRadius(5, 5, 5, 5)));
        style_Accent.Setters.Add(new Microsoft.UI.Xaml.Setter(Microsoft.UI.Xaml.Controls.Button.FontSizeProperty, 15.0));
        Microsoft.UI.Xaml.Controls.ControlTemplate template_InputFrame = Template_InputFrame();
        v_window = new Microsoft.UI.Xaml.Window();
        v_window.Title = "Live Designer Counter";
        v_canvas = new Microsoft.UI.Xaml.Controls.Canvas();
        v_canvas.Name = "Root";
        v_canvas.Width = 960.0;
        v_canvas.Height = 640.0;
        v_canvas.Background = new Microsoft.UI.Xaml.Media.SolidColorBrush(Windows.UI.Color.FromArgb(255, 32, 36, 43));
        v_title = new Microsoft.UI.Xaml.Controls.TextBlock();
        v_title.Name = "Title";
        v_title.Text = "Build something remarkable";
        v_title.FontSize = 30.0;
        Microsoft.UI.Xaml.Controls.Canvas.SetLeft(v_title, 48.0);
        Microsoft.UI.Xaml.Controls.Canvas.SetTop(v_title, 44.0);
        v_title.Width = 670.0;
        v_title.Height = 48.0;
        v_title.Foreground = new Microsoft.UI.Xaml.Media.SolidColorBrush(Windows.UI.Color.FromArgb(255, 246, 247, 250));
        v_caption = new Microsoft.UI.Xaml.Controls.TextBlock();
        v_caption.Text = "Code-first WinUI • live preview • managed events";
        v_caption.FontSize = 16.0;
        Microsoft.UI.Xaml.Controls.Canvas.SetLeft(v_caption, 50.0);
        Microsoft.UI.Xaml.Controls.Canvas.SetTop(v_caption, 103.0);
        v_caption.Width = 670.0;
        v_caption.Height = 32.0;
        v_caption.Foreground = new Microsoft.UI.Xaml.Media.SolidColorBrush(Windows.UI.Color.FromArgb(255, 176, 191, 212));
        v_action = new Microsoft.UI.Xaml.Controls.Button();
        v_action.Name = "ActionButton";
        v_action.Content = "Run action";
        Microsoft.UI.Xaml.Controls.Canvas.SetLeft(v_action, 50.0);
        Microsoft.UI.Xaml.Controls.Canvas.SetTop(v_action, 162.0);
        v_action.Width = 160.0;
        v_action.Height = 40.0;
        v_action.Style = style_Accent;
        v_action.Click += Program.OnAction;
        v_TextBox_1 = new Microsoft.UI.Xaml.Controls.TextBox();
        v_TextBox_1.Name = "Input";
        v_TextBox_1.Text = "Hello";
        Microsoft.UI.Xaml.Controls.Canvas.SetLeft(v_TextBox_1, 50.0);
        Microsoft.UI.Xaml.Controls.Canvas.SetTop(v_TextBox_1, 236.0);
        v_TextBox_1.Width = 320.0;
        v_TextBox_1.Height = 36.0;
        v_TextBox_1.Template = template_InputFrame;
        v_canvas.Children.Add(v_title);
        v_canvas.Children.Add(v_caption);
        v_canvas.Children.Add(v_action);
        v_canvas.Children.Add(v_TextBox_1);
        v_window.Content = v_canvas;
        v_window.Activate();
        return v_window;
    }
    static Microsoft.UI.Xaml.Controls.ControlTemplate Template_InputFrame()
    {
        Microsoft.UI.Xaml.Controls.ControlTemplate template = new Microsoft.UI.Xaml.Controls.ControlTemplate();
        Microsoft.UI.Xaml.Controls.Border v_frame = new Microsoft.UI.Xaml.Controls.Border();
        v_frame.Padding = new Microsoft.UI.Xaml.Thickness(8, 8, 8, 8);
        v_frame.Background = new Microsoft.UI.Xaml.Media.SolidColorBrush(Windows.UI.Color.FromArgb(255, 48, 58, 72));
        v_frame.CornerRadius = new Microsoft.UI.Xaml.CornerRadius(6, 6, 6, 6);
        Microsoft.UI.Xaml.Controls.TextBox v_input = new Microsoft.UI.Xaml.Controls.TextBox();
        v_input.Name = "PART_Input";
        template.Bind(v_input, "Text", Microsoft.UI.Xaml.Controls.TextBox.TextProperty);
        v_frame.Child = v_input;
        template.VisualTree = v_frame;
        return template;
    }
}
