// A self-contained "netstandard-style" core library compiled with -nostdlib.
// It defines the predefined types and the well-known attributes the metadata importer has to recognise.
#nullable enable
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

[assembly: System.Reflection.AssemblyVersion("2.1.0.0")]
// The InternalsVisibleTo declarations (they need the fixture public key) are generated by build-fixtures.mjs.

namespace System
{
    public class Object
    {
        public Object() { }
        public virtual string? ToString() => null;
        public virtual bool Equals(object? obj) => false;
        public virtual int GetHashCode() => 0;
    }
    public abstract class ValueType { }
    public abstract class Enum : ValueType { }
    public struct Void { }
    public struct Boolean { }
    public struct Char { }
    public struct SByte { }
    public struct Byte { }
    public struct Int16 { }
    public struct UInt16 { }
    public struct Int32 { }
    public struct UInt32 { }
    public struct Int64 { }
    public struct UInt64 { }
    public struct Single { }
    public struct Double { }
    public struct Decimal { }
    public struct IntPtr { }
    public struct UIntPtr { }
    public struct RuntimeTypeHandle { }
    public struct Nullable<T> where T : struct
    {
        public Nullable(T value) { }
        public bool HasValue => false;
        public T Value => default;
    }
    public struct ValueTuple<T1, T2>
    {
        public T1 Item1;
        public T2 Item2;
        public ValueTuple(T1 item1, T2 item2) { Item1 = item1; Item2 = item2; }
    }
    public sealed class String
    {
        public int Length => 0;
        [IndexerName("Chars")]
        public char this[int index] => default;
        public static string Concat(string? a, string? b) => null!;
    }
    public abstract class Array { public int Length => 0; }
    public abstract class Delegate { }
    public abstract class MulticastDelegate : Delegate { }
    public abstract class Type { }
    public class Exception { public Exception() { } public Exception(string? message) { } }
    public interface IDisposable { void Dispose(); }
    public delegate void Action();
    public delegate void Action<in T>(T obj);
    public delegate TResult Func<in T, out TResult>(T arg);
    public delegate TOutput Converter<in TInput, out TOutput>(TInput input);
    public delegate void EventHandler(object? sender, EventArgs e);
    public class EventArgs { public static readonly EventArgs Empty = new EventArgs(); }

    [Flags]
    public enum AttributeTargets { Assembly = 1, Module = 2, Class = 4, Struct = 8, Enum = 16, Constructor = 32, Method = 64, Property = 128, Field = 256, Event = 512, Interface = 1024, Parameter = 2048, Delegate = 4096, ReturnValue = 8192, GenericParameter = 16384, All = 32767 }
    public abstract class Attribute { protected Attribute() { } }
    [AttributeUsage(AttributeTargets.Class, Inherited = true)]
    public sealed class AttributeUsageAttribute : Attribute
    {
        public AttributeUsageAttribute(AttributeTargets validOn) { }
        public bool AllowMultiple { get; set; }
        public bool Inherited { get; set; }
    }
    [AttributeUsage(AttributeTargets.Enum)]
    public class FlagsAttribute : Attribute { }
    [AttributeUsage(AttributeTargets.Parameter)]
    public sealed class ParamArrayAttribute : Attribute { }
    [AttributeUsage(AttributeTargets.All, Inherited = false)]
    public sealed class ObsoleteAttribute : Attribute
    {
        public ObsoleteAttribute() { }
        public ObsoleteAttribute(string? message) { }
        public ObsoleteAttribute(string? message, bool error) { }
        public string? DiagnosticId { get; set; }
        public string? UrlFormat { get; set; }
    }

    public static class Console
    {
        public static void WriteLine() { }
        public static void WriteLine(bool value) { }
        public static void WriteLine(int value) { }
        public static void WriteLine(double value) { }
        public static void WriteLine(string? value) { }
        public static void WriteLine(object? value) { }
        public static void WriteLine(string format, params object?[] arg) { }
        public static void Write(string? value) { }
    }
}

namespace System.Reflection
{
    [AttributeUsage(AttributeTargets.Assembly)]
    public sealed class AssemblyVersionAttribute : Attribute { public AssemblyVersionAttribute(string version) { } }
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Interface)]
    public sealed class DefaultMemberAttribute : Attribute { public DefaultMemberAttribute(string memberName) { } }
}

namespace System.Runtime.InteropServices
{
    [AttributeUsage(AttributeTargets.Parameter)]
    public sealed class InAttribute : Attribute { }
    [AttributeUsage(AttributeTargets.Parameter)]
    public sealed class OutAttribute : Attribute { }
    public enum UnmanagedType { Bool = 2 }
}

namespace System.Diagnostics
{
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = true)]
    public sealed class ConditionalAttribute : Attribute { public ConditionalAttribute(string conditionString) { } }
}

namespace System.Diagnostics.CodeAnalysis
{
    [AttributeUsage(AttributeTargets.Constructor)]
    public sealed class SetsRequiredMembersAttribute : Attribute { }
}

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Class | AttributeTargets.Method)]
    public sealed class ExtensionAttribute : Attribute { }
    [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
    public sealed class InternalsVisibleToAttribute : Attribute { public InternalsVisibleToAttribute(string assemblyName) { } }
    [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
    public sealed class TypeForwardedToAttribute : Attribute { public TypeForwardedToAttribute(Type destination) { } }
    [AttributeUsage(AttributeTargets.Property)]
    public sealed class IndexerNameAttribute : Attribute { public IndexerNameAttribute(string indexerName) { } }
    [AttributeUsage(AttributeTargets.All)]
    public sealed class IsReadOnlyAttribute : Attribute { }
    [AttributeUsage(AttributeTargets.Parameter)]
    public sealed class RequiresLocationAttribute : Attribute { }
    [AttributeUsage(AttributeTargets.Struct)]
    public sealed class IsByRefLikeAttribute : Attribute { }
    [AttributeUsage(AttributeTargets.GenericParameter)]
    public sealed class IsUnmanagedAttribute : Attribute { }
    [AttributeUsage(AttributeTargets.All)]
    public sealed class DynamicAttribute : Attribute
    {
        public DynamicAttribute() { }
        public DynamicAttribute(bool[] transformFlags) { }
    }
    [AttributeUsage(AttributeTargets.All)]
    public sealed class TupleElementNamesAttribute : Attribute { public TupleElementNamesAttribute(string?[] transformNames) { } }
    [AttributeUsage(AttributeTargets.All)]
    public sealed class NullableAttribute : Attribute
    {
        public readonly byte[] NullableFlags;
        public NullableAttribute(byte flag) { NullableFlags = new byte[] { flag }; }
        public NullableAttribute(byte[] flags) { NullableFlags = flags; }
    }
    [AttributeUsage(AttributeTargets.All)]
    public sealed class NullableContextAttribute : Attribute
    {
        public readonly byte Flag;
        public NullableContextAttribute(byte flag) { Flag = flag; }
    }
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Field | AttributeTargets.Property)]
    public sealed class RequiredMemberAttribute : Attribute { }
    [AttributeUsage(AttributeTargets.All, AllowMultiple = true, Inherited = false)]
    public sealed class CompilerFeatureRequiredAttribute : Attribute
    {
        public CompilerFeatureRequiredAttribute(string featureName) { FeatureName = featureName; }
        public string FeatureName { get; }
        public bool IsOptional { get; init; }
    }
    public static class IsExternalInit { }
    public static class IsVolatile { }
    public class CallConvCdecl { }
}

namespace System.Collections
{
    public interface IEnumerable { IEnumerator GetEnumerator(); }
    public interface IEnumerator { object? Current { get; } bool MoveNext(); }
}

namespace System.Collections.Generic
{
    public interface IEnumerable<out T> : IEnumerable { new IEnumerator<T> GetEnumerator(); }
    public interface IEnumerator<out T> : IEnumerator, IDisposable { new T Current { get; } }
    public class List<T> : IEnumerable<T>
    {
        public List() { }
        public List(int capacity) { }
        public int Count => 0;
        public T this[int index] { get => default!; set { } }
        public void Add(T item) { }
        public bool Contains(T item) => false;
        public TOutput[] ConvertAll<TOutput>(Converter<T, TOutput> converter) => null!;
        public Enumerator GetEnumerator() => default;
        IEnumerator<T> IEnumerable<T>.GetEnumerator() => null!;
        IEnumerator IEnumerable.GetEnumerator() => null!;
        public struct Enumerator : IEnumerator<T>
        {
            public T Current => default!;
            object? IEnumerator.Current => null;
            public bool MoveNext() => false;
            public void Dispose() { }
        }
    }
    public class Dictionary<TKey, TValue> where TKey : notnull
    {
        public TValue this[TKey key] { get => default!; set { } }
        public bool TryGetValue(TKey key, out TValue value) { value = default!; return false; }
    }
}

namespace Mini
{
    public static class Extensions
    {
        public static int CountOf<T>(this IEnumerable<T> source) => 0;
        public static string Join(this string separator, params string[] values) => separator;
        public static void NotAnExtension(string value) { }
    }

    [Obsolete("Use NewApi instead", true)]
    public class OldApi { }
    public class NewApi
    {
        [Obsolete] public void Plain() { }
        [Obsolete("Slow path")] public void WithMessage() { }
        [Obsolete("Custom", DiagnosticId = "MINI001", UrlFormat = "https://example.test/{0}")] public int Tagged;
        [Conditional("DEBUG"), Conditional("TRACE")] public static void Trace(string message) { }
        public void Current() { }
    }
    [Conditional("MINI_ATTRIBUTES")]
    public sealed class DebugOnlyAttribute : Attribute { }

    public class Refs
    {
        public void Kinds(ref int a, out int b, in int c, ref readonly int d, params int[] rest) { b = 0; }
        public ref int ReturnsRef(ref int x) => ref x;
        public ref readonly int ReturnsRefReadOnly(in int x) => ref x;
        public void Optional(int count = 5, string? text = null, bool flag = true, double scale = 1.5, string name = "none") { }
        public const int Max = 42;
        public const string Name = "mini";
        public static readonly int Shared = 1;
        public volatile int Counter;
        protected int ProtectedField;
        internal int InternalField;
        protected internal int ProtectedInternalField;
        private protected int PrivateProtectedField;
        private int _privateField;
        public int UsePrivate() => _privateField;
    }

    public class Nullability
    {
        public string? MaybeNull;
        public string NotNull = "";
        public int? MaybeInt;
        public List<string?>? Method(string a, string? b, int? c, string?[] d) => null;
        public T? Generic<T>(T? value) where T : class => value;
        public void NotNullConstraint<T>(T value) where T : notnull { }
#nullable disable
        public string Oblivious;
        public string ObliviousMethod(string a) => a;
#nullable enable
    }

    public class Tuples
    {
        public (int count, string name) Pair() => default;
        public List<(int a, (string b, bool c) d)>? Nested;
        public (int, string) Unnamed;
    }

    public class Dynamics
    {
        public dynamic? Field;
        public dynamic Method(dynamic first, List<dynamic> second, object third, dynamic[] fourth) => first;
    }

    public readonly struct Point
    {
        public readonly int X;
        public readonly int Y;
        public Point(int x, int y) { X = x; Y = y; }
        public static Point operator +(Point a, Point b) => a;
        public static implicit operator int(Point p) => 0;
        public static explicit operator Point(int value) => default;
    }
    public struct Mutable
    {
        public int Value;
        public readonly int Peek() => Value;
        public void Bump() { }
    }
    public ref struct Window
    {
        public int Length;
    }

    public class Person
    {
        public required string Name { get; init; }
        public required int Age;
        public string? Nickname { get; set; }
        public Person() { }
        [SetsRequiredMembers] public Person(string name) { Name = name; }
    }

    public interface IVariant<in TIn, out TOut> { TOut Convert(TIn input); }
    public class Constrained<TKey, TValue, TItem> where TKey : struct where TValue : class, IDisposable, new() where TItem : unmanaged
    {
        public TValue? Find(TKey key) => null;
        public void Bind<TOther>(TOther other) where TOther : TValue { }
    }
    public class Outer<T>
    {
        public T? Value;
        public class Inner<U>
        {
            public T? First;
            public U? Second;
            public Dictionary<T, U>? Map;
            public Outer<U>.Inner<T>? Swap() => null;
        }
        public class Plain { public T? Item; }
        public enum Kind : byte { None, Some = 5 }
        public Inner<int>? Make() => null;
        public Outer<string>.Plain? Fixed;
    }

    public abstract class Notifier
    {
        public abstract event EventHandler Changed;
        public static event EventHandler Global { add { } remove { } }
        protected virtual void OnChanged() { }
        public abstract int Level { get; protected set; }
        public virtual string Title => "";
    }
    public sealed class LoudNotifier : Notifier
    {
        public override event EventHandler Changed { add { } remove { } }
        protected sealed override void OnChanged() { }
        public override int Level { get => 0; protected set { } }
    }

    public unsafe struct Native
    {
        public int* Pointer;
        public void** Raw;
        public delegate*<int, ref string, void> Managed;
        public delegate* unmanaged[Cdecl]<int, int> Unmanaged;
        public int[,] Matrix;
        public int[][] Jagged;
        public nint Handle;
    }
}
