/** ECMA-335 II.22 and Portable PDB v1.0 table and column registry. */
const definitions = [
  [0, 'Module', 'Generation Name Mvid EncId EncBaseId', ["u16", "str", "guid", "guid", "guid"]],
  [1, 'TypeRef', 'ResolutionScope Name Namespace', ["ResolutionScope", "str", "str"]],
  [2, 'TypeDef', 'Flags Name Namespace Extends FieldList MethodList', ["u32", "str", "str", "TypeDefOrRef", "t4", "t6"]],
  [3, 'FieldPtr', 'Field', ["t4"]],
  [4, 'Field', 'Flags Name Signature', ["u16", "str", "blob"]],
  [5, 'MethodPtr', 'Method', ["t6"]],
  [6, 'MethodDef', 'RVA ImplFlags Flags Name Signature ParamList', ["u32", "u16", "u16", "str", "blob", "t8"]],
  [7, 'ParamPtr', 'Param', ["t8"]],
  [8, 'Param', 'Flags Sequence Name', ["u16", "u16", "str"]],
  [9, 'InterfaceImpl', 'Class Interface', ["t2", "TypeDefOrRef"]],
  [10, 'MemberRef', 'Class Name Signature', ["MemberRefParent", "str", "blob"]],
  [11, 'Constant', 'Type Parent Value', ["u16", "HasConstant", "blob"]],
  [12, 'CustomAttribute', 'Parent Type Value', ["HasCustomAttribute", "CustomAttributeType", "blob"]],
  [13, 'FieldMarshal', 'Parent NativeType', ["HasFieldMarshal", "blob"]],
  [14, 'DeclSecurity', 'Action Parent PermissionSet', ["u16", "HasDeclSecurity", "blob"]],
  [15, 'ClassLayout', 'PackingSize ClassSize Parent', ["u16", "u32", "t2"]],
  [16, 'FieldLayout', 'Offset Field', ["u32", "t4"]],
  [17, 'StandAloneSig', 'Signature', ["blob"]],
  [18, 'EventMap', 'Parent EventList', ["t2", "t20"]],
  [19, 'EventPtr', 'Event', ["t20"]],
  [20, 'Event', 'EventFlags Name EventType', ["u16", "str", "TypeDefOrRef"]],
  [21, 'PropertyMap', 'Parent PropertyList', ["t2", "t23"]],
  [22, 'PropertyPtr', 'Property', ["t23"]],
  [23, 'Property', 'Flags Name Type', ["u16", "str", "blob"]],
  [24, 'MethodSemantics', 'Semantics Method Association', ["u16", "t6", "HasSemantics"]],
  [25, 'MethodImpl', 'Class MethodBody MethodDeclaration', ["t2", "MethodDefOrRef", "MethodDefOrRef"]],
  [26, 'ModuleRef', 'Name', ["str"]],
  [27, 'TypeSpec', 'Signature', ["blob"]],
  [28, 'ImplMap', 'MappingFlags MemberForwarded ImportName ImportScope', ["u16", "MemberForwarded", "str", "t26"]],
  [29, 'FieldRVA', 'RVA Field', ["u32", "t4"]],
  [30, 'EncLog', 'Token FuncCode', ["u32", "u32"]],
  [31, 'EncMap', 'Token', ["u32"]],
  [32, 'Assembly', 'HashAlgId MajorVersion MinorVersion BuildNumber RevisionNumber Flags PublicKey Name Culture', ["u32", "u16", "u16", "u16", "u16", "u32", "blob", "str", "str"]],
  [33, 'AssemblyProcessor', 'Processor', ["u32"]],
  [34, 'AssemblyOS', 'OSPlatformId OSMajorVersion OSMinorVersion', ["u32", "u32", "u32"]],
  [35, 'AssemblyRef', 'MajorVersion MinorVersion BuildNumber RevisionNumber Flags PublicKeyOrToken Name Culture HashValue', ["u16", "u16", "u16", "u16", "u32", "blob", "str", "str", "blob"]],
  [36, 'AssemblyRefProcessor', 'Processor AssemblyRef', ["u32", "t35"]],
  [37, 'AssemblyRefOS', 'OSPlatformId OSMajorVersion OSMinorVersion AssemblyRef', ["u32", "u32", "u32", "t35"]],
  [38, 'File', 'Flags Name HashValue', ["u32", "str", "blob"]],
  [39, 'ExportedType', 'Flags TypeDefId TypeName TypeNamespace Implementation', ["u32", "u32", "str", "str", "Implementation"]],
  [40, 'ManifestResource', 'Offset Flags Name Implementation', ["u32", "u32", "str", "Implementation"]],
  [41, 'NestedClass', 'NestedClass EnclosingClass', ["t2", "t2"]],
  [42, 'GenericParam', 'Number Flags Owner Name', ["u16", "u16", "TypeOrMethodDef", "str"]],
  [43, 'MethodSpec', 'Method Instantiation', ["MethodDefOrRef", "blob"]],
  [44, 'GenericParamConstraint', 'Owner Constraint', ["t42", "TypeDefOrRef"]],
  [48, 'Document', 'Name HashAlgorithm Hash Language', ["blob", "guid", "blob", "guid"]],
  [49, 'MethodDebugInformation', 'Document SequencePoints', ["t48", "blob"]],
  [50, 'LocalScope', 'Method ImportScope VariableList ConstantList StartOffset Length', ["t6", "t53", "t51", "t52", "u32", "u32"]],
  [51, 'LocalVariable', 'Attributes Index Name', ["u16", "u16", "str"]],
  [52, 'LocalConstant', 'Name Signature', ["str", "blob"]],
  [53, 'ImportScope', 'Parent Imports', ["t53", "blob"]],
  [54, 'StateMachineMethod', 'MoveNextMethod KickoffMethod', ["t6", "t6"]],
  [55, 'CustomDebugInformation', 'Parent Kind Value', ["HasCustomDebugInformation", "guid", "blob"]],
];

export const TableId = Object.freeze(Object.fromEntries(definitions.map(([id, name]) => [name, id])));
export const Tables = TableId;
export const tableDefinitions = Object.freeze(Object.fromEntries(definitions.map(([id, name, columns, types]) => [id,
  Object.freeze({ id, name, columns: Object.freeze(columns.split(' ')), types: Object.freeze(types) })])));
export const metadataSchemas = Object.freeze(Object.fromEntries(definitions.map(([id, , , types]) => [id, types])));
