// Generated by SharpForge Designer. Edit the .sfdesign.json document.
public class DesignedView
{
    public static Microsoft.UI.Xaml.Window v_window;
    public static Microsoft.UI.Xaml.Controls.Grid v_canvas;
    public static Microsoft.UI.Xaml.Controls.TextBlock v_title;
    public static Microsoft.UI.Xaml.Controls.TextBlock v_caption;
    public static Microsoft.UI.Xaml.Controls.Button v_action;
    public static Microsoft.UI.Xaml.Controls.NumberBox v_NumberBox_1;
    public static Microsoft.UI.Xaml.Controls.InfoBar v_InfoBar_1;
    public static Microsoft.UI.Xaml.Window Create()
    {
        Microsoft.UI.Xaml.Style style_Accent = new Microsoft.UI.Xaml.Style();
        style_Accent.Setters.Add(new Microsoft.UI.Xaml.Setter(Microsoft.UI.Xaml.Controls.Button.BackgroundProperty, new Microsoft.UI.Xaml.Media.SolidColorBrush(Windows.UI.Color.FromArgb(255, 0, 95, 184))));
        style_Accent.Setters.Add(new Microsoft.UI.Xaml.Setter(Microsoft.UI.Xaml.Controls.Button.ForegroundProperty, new Microsoft.UI.Xaml.Media.SolidColorBrush(Windows.UI.Color.FromArgb(255, 255, 255, 255))));
        style_Accent.Setters.Add(new Microsoft.UI.Xaml.Setter(Microsoft.UI.Xaml.Controls.Button.CornerRadiusProperty, new Microsoft.UI.Xaml.CornerRadius(5, 5, 5, 5)));
        style_Accent.Setters.Add(new Microsoft.UI.Xaml.Setter(Microsoft.UI.Xaml.Controls.Button.FontSizeProperty, 15.0));
        v_window = new Microsoft.UI.Xaml.Window();
        v_window.Title = "Responsive Grid Designer";
        v_canvas = new Microsoft.UI.Xaml.Controls.Grid();
        v_canvas.Name = "Root";
        v_canvas.Width = 960.0;
        v_canvas.Height = 640.0;
        v_canvas.Background = new Microsoft.UI.Xaml.Media.SolidColorBrush(Windows.UI.Color.FromArgb(255, 32, 36, 43));
        v_canvas.Padding = new Microsoft.UI.Xaml.Thickness(24, 24, 24, 24);
        v_canvas.RowDefinitions.Add(new Microsoft.UI.Xaml.Controls.RowDefinition() { Height = new Microsoft.UI.Xaml.GridLength(1, Microsoft.UI.Xaml.GridUnitType.Auto) });
        v_canvas.RowDefinitions.Add(new Microsoft.UI.Xaml.Controls.RowDefinition() { Height = new Microsoft.UI.Xaml.GridLength(1, Microsoft.UI.Xaml.GridUnitType.Star) });
        v_canvas.RowDefinitions.Add(new Microsoft.UI.Xaml.Controls.RowDefinition() { Height = new Microsoft.UI.Xaml.GridLength(1, Microsoft.UI.Xaml.GridUnitType.Auto) });
        v_canvas.ColumnDefinitions.Add(new Microsoft.UI.Xaml.Controls.ColumnDefinition() { Width = new Microsoft.UI.Xaml.GridLength(2, Microsoft.UI.Xaml.GridUnitType.Star) });
        v_canvas.ColumnDefinitions.Add(new Microsoft.UI.Xaml.Controls.ColumnDefinition() { Width = new Microsoft.UI.Xaml.GridLength(1, Microsoft.UI.Xaml.GridUnitType.Star) });
        v_title = new Microsoft.UI.Xaml.Controls.TextBlock();
        v_title.Name = "Title";
        v_title.Text = "Build something remarkable";
        v_title.FontSize = 20.0;
        v_title.Width = 670.0;
        v_title.Height = 48.0;
        v_title.Foreground = new Microsoft.UI.Xaml.Media.SolidColorBrush(Windows.UI.Color.FromArgb(255, 246, 247, 250));
        v_caption = new Microsoft.UI.Xaml.Controls.TextBlock();
        v_caption.Text = "Code-first WinUI • live preview • managed events";
        v_caption.FontSize = 16.0;
        v_caption.Width = 670.0;
        v_caption.Height = 32.0;
        v_caption.Foreground = new Microsoft.UI.Xaml.Media.SolidColorBrush(Windows.UI.Color.FromArgb(255, 176, 191, 212));
        Microsoft.UI.Xaml.Controls.Grid.SetRow(v_caption, 1);
        v_action = new Microsoft.UI.Xaml.Controls.Button();
        v_action.Name = "ActionButton";
        v_action.Content = "Run action";
        v_action.Width = 160.0;
        v_action.Height = 40.0;
        Microsoft.UI.Xaml.Controls.Grid.SetColumn(v_action, 1);
        Microsoft.UI.Xaml.Controls.Grid.SetRow(v_action, 2);
        v_action.Style = style_Accent;
        v_action.Click += Program.OnAction;
        v_NumberBox_1 = new Microsoft.UI.Xaml.Controls.NumberBox();
        v_NumberBox_1.Name = "Amount";
        v_NumberBox_1.Value = 42.0;
        v_NumberBox_1.Width = 200.0;
        Microsoft.UI.Xaml.Controls.Grid.SetRow(v_NumberBox_1, 1);
        Microsoft.UI.Xaml.Controls.Grid.SetColumn(v_NumberBox_1, 1);
        v_InfoBar_1 = new Microsoft.UI.Xaml.Controls.InfoBar();
        v_InfoBar_1.Name = "InfoBar_1";
        v_InfoBar_1.Content = "InfoBar";
        v_InfoBar_1.Title = "Designer workspace";
        v_InfoBar_1.Message = "Edit Grid tracks and shared styles without recreating managed objects.";
        Microsoft.UI.Xaml.Controls.Grid.SetRow(v_InfoBar_1, 2);
        Microsoft.UI.Xaml.Controls.Grid.SetColumn(v_InfoBar_1, 0);
        v_InfoBar_1.Width = 550.0;
        v_canvas.Children.Add(v_title);
        v_canvas.Children.Add(v_caption);
        v_canvas.Children.Add(v_action);
        v_canvas.Children.Add(v_NumberBox_1);
        v_canvas.Children.Add(v_InfoBar_1);
        v_window.Content = v_canvas;
        v_window.Activate();
        return v_window;
    }
}
