import {registerCompilerResultTools} from './compiler-result-views.js';
import {renderDesignerProblems} from '../designer-problems-view.js';
import {storage,storageKeys} from '../settings/storage.js';
export function createStudioRenderers(context){
let resultTools;
function renderPanel(panel=context.state.panel,element){
const {$,$$,E,advancedTools,breakOnWrite,debugTools,designerTools,docking,editLocal,empty,formatBytes,hydrate,ilDebugger,inspectObject,nativeBuild,openFile,openMenuAt,refreshWatches,runtimeTools,saveLocal,selectDebugFrame,setPanel,state,toast,workbench}=context;
if(panel==='solution'||panel==='diagnostics')return;if(panel==='watch')panel='debug';const el=element??docking.content.get(panel);if(!el)return;const oldScroll=el.scrollTop;if(panel==='assembly'){workbench.render(el);return;}if(panel==='disassembly'){ilDebugger.render(el,state.debug?{...state.debug,selectedFrameId:state.frameId}:null);return;}if(runtimeTools?.renderTool(panel,el))return;if(designerTools?.renderTool(panel,el))return;if(advancedTools?.renderTool(panel,el))return;if(debugTools.renderTool(panel,el))return;if(renderAdditionalTool(panel,el))return;let html='';
 switch(panel){
  case 'output':html=`<div class="panel-tools"><label for="output-kind">Show output from:</label><select id="output-kind"><option value="all" ${state.outputKind==='all'?'selected':''}>Build + Program</option><option value="program" ${state.outputKind==='program'?'selected':''}>Program only</option><option value="build" ${state.outputKind==='build'?'selected':''}>Build only</option></select><span class="panel-spacer"></span><span>${state.debug?.state==='running'?'● Running':'Local execution'}</span></div><div class="output-area">${state.outputKind!=='program'?state.logs.map(l=>`<div class="output-line ${l.type}"><span class="timestamp">${E(l.time)}</span>${E(l.text)}</div>`).join(''):''}${state.outputKind!=='build'&&state.programOutput?`<div class="output-line program">${E(state.programOutput)}</div>`:''}${!state.programOutput&&state.logs.length<2?'<div class="output-line system">Press F5 to debug, or Ctrl+F5 to run without breakpoints.</div>':''}<span class="output-caret"></span></div>`;break;
  case 'problems':return renderDesignerProblems(context,el);
  case 'debug':{
   const paused=state.debug?.state==='paused',locals=state.inspectedLocals??state.debug?.locals??[];
   html=`<div class="debug-grid"><div class="debug-pane"><div class="debug-pane-title">Locals <span>${paused?('double-click to edit · right-click to break on write'):'pause execution to inspect'}</span></div>${paused&&locals.length?`<table class="data-table"><thead><tr><th>Name</th><th>Value</th><th>Type</th></tr></thead><tbody>${locals.map((v,i)=>`<tr data-local="${i}"><td class="name">${v.reference?'▸ ':''}${E(v.name)}</td><td class="value" data-edit-local="${i}">${E(v.value)}</td><td class="type">${E(v.type)}</td></tr>`).join('')}</tbody></table>`:empty(paused?'No locals in scope':'Debugger is not paused',paused?'Step to the next statement to inspect assigned values.':'Start debugging with F5 to inspect live managed values.','bug')}</div><div class="debug-pane"><div class="debug-pane-title">Watch <span>side-effect-free expressions</span></div><div class="watch-input"><input id="watch-expression" placeholder="Add watch expression" aria-label="Watch expression"><button id="add-watch" title="Add watch">＋</button></div>${state.watches.length?`<table class="data-table"><tbody>${state.watches.map((expression,i)=>{const v=state.watchResults.get(expression);return `<tr data-watch="${i}"><td class="code">${E(expression)}</td><td class="value">${E(paused?v?.error??v?.result??'…':'<not paused>')}</td><td><button class="remove-watch" data-remove-watch="${i}" title="Remove watch">×</button></td></tr>`;}).join('')}</tbody></table>`:''}</div></div>`;break;}
  case 'stack':{const frames=state.inspectedThreadFrames??state.debug?.frames??[];html=`<div class="panel-tools"><span>Managed execution worker</span><span class="panel-spacer"></span><span>${frames.length} frames · ➜ executing · ⇢ selected caller</span><button data-command="showNext">Show Next Statement</button></div>`+(frames.length?`<table class="data-table"><thead><tr><th></th><th>Function</th><th>Source location</th><th>Instruction</th></tr></thead><tbody>${frames.map(f=>`<tr data-frame="${f.id}" class="${f.id===state.frameId?'trace-selected':''}"><td>${f.id===frames[0]?.id?'➜':f.id===state.frameId?'⇢':''}</td><td class="code">${E(f.name)}</td><td class="file-cell">${E(f.source)}:${f.line}</td><td class="code">${f.ilOffset!=null?'IL_'+f.ilOffset.toString(16).padStart(4,'0'):f.pc.toString(16).padStart(4,'0')}</td></tr>`).join('')}</tbody></table>`:empty('The managed stack is empty','Start a debug session, then step into a method call.','layers'));break;}
 }
 el.innerHTML=html;hydrate(el);el.scrollTop=oldScroll;
 if(panel==='output'){const outputKind=$('#output-kind',el);if(outputKind)outputKind.onchange=()=>{state.outputKind=outputKind.value;renderPanel(panel);};if(state.debug?.state==='running')el.scrollTop=el.scrollHeight;}
 if(panel==='debug'){
   const watchInput=$('#watch-expression',el);const add=()=>{const input=watchInput,text=input.value.trim();if(text&&!state.watches.includes(text)){state.watches.push(text);saveLocal();refreshWatches();renderPanel(panel);}};$('#add-watch',el).onclick=add;watchInput.onkeydown=e=>{if(e.key==='Enter')add();};
   $$('[data-remove-watch]',el).forEach(b=>b.onclick=e=>{e.stopPropagation();state.watches.splice(Number(b.dataset.removeWatch),1);saveLocal();renderPanel(panel);});
   const locals=state.inspectedLocals??state.debug?.locals??[];
   $$('[data-local]',el).forEach(tr=>{tr.oncontextmenu=e=>{if(state.debug?.state!=='paused')return;e.preventDefault();const v=locals[Number(tr.dataset.local)];openMenuAt(e.clientX,e.clientY,[['Break on write',()=>breakOnWrite({frameId:state.frameId,name:v.name})]]);};tr.onclick=()=>{const v=locals[Number(tr.dataset.local)];if(v.reference)inspectObject(v.name,v.reference);};tr.ondblclick=e=>{e.stopPropagation();const v=locals[Number(tr.dataset.local)];if(!v.reference&&v.name!=='this')editLocal(v);};});
   $$('[data-watch]',el).forEach(tr=>tr.ondblclick=()=>{const expression=state.watches[Number(tr.dataset.watch)],v=state.watchResults.get(expression);if(v?.reference)inspectObject(expression,v.reference);});
 }
 if(panel==='stack')$$('[data-frame]',el).forEach(tr=>tr.onclick=()=>selectDebugFrame(Number(tr.dataset.frame)).catch(error=>toast(error.message,'error')));
 if(panel==='debug'){const watch=el.querySelector('.debug-pane:nth-child(2)');if(watch){docking.content.get('watch').replaceChildren(watch);el.querySelector('.debug-grid').classList.add('locals-only');}}

}
function renderAdditionalTool(panel,el){
const {$,$$,E,applyRefactoring,build,closeModal,docking,download,empty,loadSample,nativeBuild,openFile,reloadDiskProject,requestCompiler,samples,saveLocal,setStartupProject,showModal,state,toast,toolDefinitions}=context;

 if(panel==='settings'){renderEditorSettings(el);return true;}if(panel==='properties'){renderItemProperties(el);return true;}
 if(['msbuild','msbuild-inspector','project-source'].includes(panel)){nativeBuild.render(panel,el);return true;}
 if(panel==='calls'){if(!el.childNodes.length)el.innerHTML=empty('Call Hierarchy','Place the caret on a method and use Shift+Alt+H. Calls inside top-level statements do not yet have a named caller.');return true;}
 if(panel==='outline')return context.sourceSymbols.renderOutline(el);
 if(panel==='project'){
  if(state.nativeMode){el.innerHTML=`<div class="tool-page"><h2>Native Project Properties</h2><p>${E(state.nativeWorkspace?.root??'')}</p><p>The MSBuild tool selects the solution/project, configuration, platform, framework, runtime and global properties. Evaluate a project for authoritative SDK-resolved values and item metadata.</p><div class="tool-actions"><button class="button" data-command="nativeMSBuild">MSBuild settings</button><button class="button" data-command="nativeEvaluate">Evaluate project</button><button class="button" data-command="tool:project-source">Edit project / solution XML</button></div><p>Native builds compile projects separately. Browser language services and IL execution remain limited to their supported subset.</p></div>`;return true;}
  const snapshot=state.projectSnapshot,project=state.projectSystem?.projects.get(state.startupProject);
  if(!snapshot){el.innerHTML=`<div class="tool-page"><h2>Project Properties</h2><p>Open a .csproj or .slnx together with its source files, or open the containing folder.</p><div class="tool-actions"><button class="button" data-command="openFolder">Open folder</button><button class="button" data-command="open">Open files</button></div><p>File selections grant access only to the selected files. No build tasks, package restore, or user source is executed while loading.</p></div>`;return true;}
  const allEntries=[...state.projectSystem.files.keys()].filter(p=>/\.(slnx|csproj)$/i.test(p));
  el.innerHTML=`<div class="tool-page"><h2>${E(snapshot.solution.name)}</h2><div class="notice">Source-combined browser preview. ProjectReference source is included in dependency order; projects are not separately compiled/linked. Target frameworks are metadata, not installed runtimes.</div><label class="tool-field">Solution / project <select id="project-entry">${allEntries.map(path=>`<option ${path===snapshot.solution.path?'selected':''}>${E(path)}</option>`).join('')}</select></label><label class="tool-field">Startup project <select id="startup-project">${snapshot.projects.map(p=>`<option value="${E(p.path)}" ${p.path===state.startupProject?'selected':''}>${E(p.name)} · ${E(p.outputType)}</option>`).join('')}</select></label><label class="tool-field">Configuration <select id="project-configuration"><option ${state.configuration==='Debug'?'selected':''}>Debug</option><option ${state.configuration==='Release'?'selected':''}>Release</option></select></label><div class="tool-actions"><button class="button" data-command="build">Build preview</button><button class="button" data-command="saveDisk">Save sources to disk</button></div><p>${state.disk?.handles.size?'Folder attached; explicit source saving is available.':'Read-only disk snapshot; recovery does not retain write permissions.'}</p><h3>Build order</h3><ol>${snapshot.solution.buildOrder.map(p=>`<li>${E(p)}</li>`).join('')}</ol><h3>Loading diagnostics (${snapshot.diagnostics.length})</h3>${snapshot.diagnostics.map(d=>`<div class="project-diagnostic ${E(d.severity)}"><b>${E(d.code)} · ${E(d.path)}</b><p>${E(d.message)}</p></div>`).join('')||'<p>No loading diagnostics.</p>'}<h3>Evaluated properties</h3><table class="data-table">${Object.entries(project?.properties??{}).map(([k,v])=>`<tr><td>${E(k)}</td><td>${E(v)}</td></tr>`).join('')}</table><h3>Project source (read-only)</h3><pre class="tool-source">${E(project?state.projectSystem.text(project.path):'')}</pre></div>`;
  $('#startup-project',el).onchange=e=>setStartupProject(e.target.value).catch(error=>toast(error.message,'error'));
  $('#project-entry',el).onchange=e=>reloadDiskProject(e.target.value);
  $('#project-configuration',el).onchange=e=>{state.configuration=e.target.value;reloadDiskProject(snapshot.solution.path);};return true;
 }
 if(panel==='extensions'){
  const config=state.extensionConfig??{},key=JSON.stringify(config);if(el.querySelector('#extension-apply')&&el.dataset.config===key)return true;el.dataset.config=key;
  el.innerHTML=`<div class="tool-page"><h2>Generators & Analyzers</h2><p>Built-in, trusted JavaScript extensions run in the compiler worker. Roslyn DLL extensions are not supported.</p><label class="tool-field"><span><input id="extension-build" type="checkbox" ${config.buildInfo?'checked':''}> Build information generator</span></label><label class="tool-field">Version <input id="extension-version" value="${E(config.version??'0.14.0')}"></label><label class="tool-field"><span><input id="extension-analyzers" type="checkbox" ${config.analyzers?'checked':''}> Unused locals, empty catches, constant conditions, task comments, and unreachable statements</span></label><label class="tool-field"><span><input id="extension-properties" type="checkbox" ${config.schemaProperties?'checked':''}> Generate auto-properties instead of fields</span></label><details><summary>Analyzer severities</summary>${[['SFAN1001','Unused local'],['SFAN1002','Empty catch'],['SFAN1003','Constant condition'],['SFAN1004','Task comment'],['SFAN1005','Unreachable statement']].map(([code,label])=>`<label class="tool-field">${label}<select data-severity="${code}">${['default','none','hint','info','warning','error'].map(value=>`<option ${(config.severities?.[code]??'default')===value?'selected':''}>${value}</option>`).join('')}</select></label>`).join('')}</details><p>Schemas can set <code>constructor: true</code> for positional constructors, or <code>immutable: true</code> for getter-only properties initialized by a constructor.</p><label class="tool-field">Optional class schema (JSON)<textarea id="extension-schema" rows="8" spellcheck="false" placeholder='{"name":"Customer","fields":[{"name":"Id","type":"int"}]}'></textarea></label><button class="button" id="extension-apply">Apply and build</button><button class="button" data-command="generatedSources">Show generated sources</button><div id="extension-result" role="status"></div></div>`;
  $('#extension-schema',el).value=config.additionalFiles?.[0]?.text??'';
  $('#extension-apply',el).onclick=async()=>{try{const text=$('#extension-schema',el).value.trim();if(text)JSON.parse(text);state.extensionConfig={buildInfo:$('#extension-build',el).checked,analyzers:$('#extension-analyzers',el).checked,version:$('#extension-version',el).value,schema:!!text,schemaProperties:!!$('#extension-properties',el)?.checked,severities:Object.fromEntries($$('[data-severity]',el).filter(s=>s.value!=='default').map(s=>[s.dataset.severity,s.value])),additionalFiles:text?[{uri:'model.schema.json',text}]:[]};await requestCompiler('configureExtensions',state.extensionConfig);state.buildDirty=true;state.revision++;saveLocal();const result=await build();$('#extension-result',el).textContent=result?.success?'Build succeeded. Generated source is available in its own tool window.':'Build has diagnostics; open Error List.';}catch(error){$('#extension-result',el).textContent=error.message;}};return true;
 }
 if(panel==='examples'){
  el.innerHTML=`<div class="tool-page"><h2>Feature Examples</h2><p>Each executable example has a regression test. Loading an example preserves the previous source project in local recovery.</p><div class="sample-list">${samples.map(s=>`<button class="sample-item" data-example="${E(s.id)}"><span class="sample-glyph">C#</span><span class="sample-details"><b>${E(s.name)}</b><small>${E(s.description)}</small></span></button>`).join('')}</div><h3>Disk project examples</h3><p>The source/browser archives also contain examples/projects: a multi-project .slnx, linked Compile items, configuration conditions, a library, and intentionally unsupported references. Open these folders with File → Open folder.</p><h3>Native MSBuild examples</h3><p>examples/msbuild contains a real SDK solution, an incremental target/task pipeline, local NuGet package producer/consumer, and multi-target library. Open them through the local MSBuild host, not the browser preview compiler.</p><button class="button" data-command="nativeMSBuild">Open MSBuild</button></div>`;for(const button of $$('[data-example]',el))button.onclick=()=>loadSample(button.dataset.example).catch(error=>toast(error.message,'error'));return true;
 }
 if(panel==='search'){
  if(el.querySelector('#workspace-search'))return true;
  el.innerHTML=`<div class="tool-page"><h2>Find in Files</h2><label class="tool-field">Search <input id="workspace-search" placeholder="Literal text in active project/reference sources"></label><div class="tool-actions"><label><input id="search-case" type="checkbox"> Match case</label><label><input id="search-word" type="checkbox"> Whole word</label></div><label class="tool-field">Replace with <input id="workspace-replace"></label><button class="button" id="replace-preview">Preview replace all</button><div id="workspace-search-results"></div></div>`;
  let generation=0;const search=async()=>{const revision=++generation;try{const result=await requestCompiler('findInFiles',{query:$('#workspace-search',el).value,options:{matchCase:$('#search-case',el).checked,wholeWord:$('#search-word',el).checked}});if(revision!==generation)return;const results=$('#workspace-search-results',el);results.innerHTML=`<p>${result.matches.length} matches${result.truncated?' (result limit reached)':''}</p>`+result.matches.map((m,i)=>`<button class="search-result" data-search-result="${i}"><b>${E(m.uri)}:${m.line+1}</b><code>${E(m.preview)}</code></button>`).join('');for(const b of $$('[data-search-result]',results))b.onclick=()=>{const match=result.matches[Number(b.dataset.searchResult)];openFile(match.uri,match.start,match.end);};}catch(error){$('#workspace-search-results',el).textContent=error.message;}};
  $('#workspace-search',el).oninput=search;$('#search-case',el).onchange=search;$('#search-word',el).onchange=search;
  $('#replace-preview',el).onclick=async()=>{try{const action=await requestCompiler('replaceAll',{query:$('#workspace-search',el).value,replacement:$('#workspace-replace',el).value,options:{matchCase:$('#search-case',el).checked,wholeWord:$('#search-word',el).checked}});showModal(action.title,`<p>${action.edits.length} version-checked edits. Candidate compilation is checked before application.</p><pre>${E(action.edits.slice(0,100).map(e=>`${e.uri} [${e.start}, ${e.end}) → ${e.newText}`).join('\n'))}</pre>`,{footer:'<button id="apply-search-replace">Apply edits</button><button id="modal-done">Cancel</button>'});$('#apply-search-replace').onclick=async()=>{try{await applyRefactoring(action);closeModal();search();}catch(error){toast(error.message,'error');}};}catch(error){toast(error.message,'error');}};return true;
 }
 if(panel==='references'){
  const refs=state.toolReferences??[];el.innerHTML=`<div class="panel-tools">${refs.length} bound references</div>`+refs.map((r,i)=>`<button class="search-result" data-reference="${i}"><b>${E(r.uri)}</b><code>${r.start}–${r.end}</code></button>`).join('');for(const b of $$('[data-reference]',el))b.onclick=()=>{const r=refs[Number(b.dataset.reference)];openFile(r.uri,r.start,r.end);};return true;
 }
 if(panel==='layouts'){
  let saved={};try{saved=JSON.parse(storage.getItem(storageKeys.layouts)??'{}');}catch{}
  el.innerHTML=`<div class="tool-page"><h2>Window Layouts</h2><p>Drag a tab onto a group’s center or edges. Use its arrow menu for keyboard-accessible docking, auto-hide, floating, and separate tool windows. Splitters are draggable and keyboard-resizable.</p><div class="tool-actions"><button class="button" data-command="resetLayout">Coding</button><button class="button" data-command="debugLayout">Debugging</button><button class="button" data-command="decompileLayout">Decompilation</button><button class="button" data-command="winuiLayout">WinUI development</button><button class="button" data-command="designer">Visual designer</button><button class="button" data-command="undoLayout">Undo layout</button></div><label class="tool-field">Layout name<input id="layout-name" value="My layout" maxlength="80"></label><div class="tool-actions"><button class="button" id="layout-save">Save named layout</button><button class="button" id="layout-export">Export JSON</button><button class="button" id="layout-import">Import JSON</button></div><h3>Named layouts</h3>${Object.keys(saved).map((name,i)=>`<button class="outline-row" data-layout="${i}">${E(name)}</button>`).join('')||'<p>No named layouts saved.</p>'}<h3>Tool windows</h3>${toolDefinitions.map(p=>`<button class="outline-row" data-command="tool:${p.id}">${E(p.title)}</button>`).join('')}</div>`;
  $('#layout-save',el).onclick=()=>{const name=$('#layout-name',el).value.trim();if(!name)return;const next=Object.assign(Object.create(null),saved);next[name]=docking.layout.snapshot();try{storage.setItem(storageKeys.layouts,JSON.stringify(next));renderPanel('layouts');toast('Named layout saved.');}catch(error){toast(error.message,'error');}};
  $('#layout-export',el).onclick=()=>download('SharpForge.layout.json',docking.layout.serialize());$('#layout-import',el).onclick=()=>$('#layout-file-input').click();for(const b of $$('[data-layout]',el))b.onclick=()=>{try{docking.layout.restore(saved[Object.keys(saved)[Number(b.dataset.layout)]]);}catch(error){toast('Layout has a different document set. Open its project before restoring it. '+error.message,'error');}};return true;
 }
 if(['heap','object'].includes(panel)){if(!el.childNodes.length)el.innerHTML=empty(panel==='heap'?'Managed Heap':'Object Inspector','Run or pause a program, then inspect managed values.');return true;}
 return false;
}
function renderEditorSettings(el){
const {$,E,EDITOR_KEYMAPS,setEditorKeymap,state}=context;
el.innerHTML=`<div class="tool-page settings-page"><h2>Environment · Keyboard</h2><p>Visual Studio is the default. The selected profile applies to all source editors, including split views and separate windows.</p><label class="tool-field">Keyboard profile<select id="editor-keymap" aria-label="Keyboard profile">${EDITOR_KEYMAPS.map(k=>`<option value="${k.id}" ${state.keymap===k.id?'selected':''}>${E(k.label)}</option>`).join('')}</select></label><p>Press Escape, then Tab or Shift+Tab to move focus from any source editor text input. Ordinary Tab keeps its editing behavior.</p><h3>Visual Studio</h3><p>Ctrl+K, Ctrl+C / Ctrl+U comments · Ctrl+K, Ctrl+D formats · Ctrl+R, Ctrl+R renames · F9 toggles a breakpoint · Ctrl+Shift+F9 removes all source breakpoints. Ctrl+Q opens commands.</p><h3>Vim</h3><p>Normal, insert, replace, visual and visual-block editing; operators, counts, registers, marks, macros, search and substitution. <code>:w</code> saves the workspace, <code>:e path</code> opens an existing workspace file, <code>:bn</code>/<code>:bp</code> switch documents. <code>:q</code> closes a saved document.</p><p>Alternative profiles use the bundled CodeMirror 5 keymaps, not native Vim/Emacs. Vimscript, external plugins, shell commands and terminal buffers are not implemented. VS Code is a shortcut preset, not a VS Code extension host.</p><h3>Debugger &amp; navigation</h3><p>F5 start / continue · Ctrl+F5 run · Shift+F5 stop · F10 step over · F11 step in · Shift+F11 step out · Alt+F10 step back · Ctrl+F10 run to cursor. Ctrl+; searches Solution Explorer. Shift+F10 opens the focused context menu.</p><button class="button" data-command="shortcuts">All application shortcuts</button></div>`;$('#editor-keymap',el).onchange=e=>setEditorKeymap(e.target.value);}
function renderItemProperties(el){
const {E,empty,state}=context;
if(!el)return;const nodes=state.itemSelection;if(!nodes.length){el.innerHTML=empty('Properties','Select an item in Solution Explorer.');return;}const selected=nodes[0],node=!state.nativeMode&&!state.projectSystem&&selected.kind==='source'&&state.files.some(f=>f.uri===selected.path)?{...selected,included:true,itemType:'Compile'}:selected,properties=nodes.length>1?{Selection:`${nodes.length} items`,Paths:nodes.map(n=>n.path??n.label).join('\n')}:{Name:node.label,Kind:node.kind,'Full path':node.path?(state.nativeMode?state.nativeWorkspace.root+'/':'')+node.path:'—','Relative path':node.path??'—',Project:node.project??'—','Build action':node.itemType??(node.kind==='source'&&node.included?'Compile':'Not evaluated'),'Included in build':node.included===undefined?'Not a compile item':node.included?'Yes':'No','Linked file':node.linked?'Yes':'No','Startup project':node.startup?'Yes':'No',...Object.fromEntries(Object.entries(node.metadata??{}).map(([k,v])=>['Metadata · '+k,typeof v==='object'?JSON.stringify(v):v]))};el.innerHTML=`<div class="panel-tools"><b>${E(nodes.length>1?'Multiple selection':node.label)}</b></div><table class="data-table property-grid">${Object.entries(properties).map(([key,value])=>`<tr><th>${E(key)}</th><td>${E(value)}</td></tr>`).join('')}</table>`;}
return {
  renderPanel, renderAdditionalTool, renderEditorSettings, renderItemProperties,
  registerTools: (registry, definitions) => resultTools = registerCompilerResultTools(registry, definitions, context, renderPanel),
  refreshResultTool: id => resultTools?.refresh(id)
};
}
