export const toolDefinitions=[
  ['runtime-settings','Language & Runtime'],
  ['solution','Solution Explorer'],
  ['symbols','Portable PDB Symbols'],
  ['symbol-source','Symbol Source'],
  ['threads','Threads'],
  ['parallel-stacks','Parallel Stacks'],
  ['hot-reload','Hot Reload'],
  ['winui','WinUI Application'],
  ['visual-tree','Live Visual Tree'],
  ['debug-session','Debugger / Exception Settings'],
  ['immediate','Immediate'],
  ['properties','Properties'],
  ['settings','Environment / Keyboard'],
  ['msbuild','MSBuild'],
  ['tests','Test Explorer'],
  ['msbuild-inspector','MSBuild Evaluation'],
  ['project-source','Project / Solution Source'],
  ['diagnostics','Diagnostic Tools'],
  ['output','Output'],
  ['problems','Error List'],
  ['debug','Locals'],
  ['watch','Watch'],
  ['stack','Call Stack'],
  ['breakpoints','Breakpoints'],
  ['assembly','Assembly Explorer'],
  ['bytecode','IL Compiler Output'],
  ['disassembly','MSIL Disassembly'],
  ['heap','Managed Heap'],
  ['object','Object Inspector'],
  ['generated','Generated Sources'],
  ['extensions','Generators & Analyzers'],
  ['references','Find All References'],
  ['calls','Call Hierarchy'],
  ['outline','Document Outline'],
  ['search','Find in Files'],
  ['project','Project Properties'],
  ['examples','Examples'],
  ['layouts','Window Layouts'],
  ['designer','WinUI Designer'],
  ['designer-toolbox','Toolbox'],
  ['designer-tree','Design Outline'],
  ['designer-properties','Design Properties'],
  ['designer-layout','Layout Editor'],
  ['designer-styles','Styles & Templates'],
  ['designer-source','Design Source']
].map(([id,title])=>({id,title,kind:'tool'}));
