import { bindingsFromRows, commonBindings } from './common.js';

// General/Text Editor profile; historical Surround With chord is retained by the project's compatibility contract.
const definitions = [
  ['Mod+K Mod+C', 'Edit.CommentSelection'], ['Mod+K Mod+U', 'Edit.UncommentSelection'],
  ['Mod+K Mod+D', 'Edit.FormatDocument'], ['Mod+K Mod+F', 'Edit.FormatSelection'],
  ['Mod+K Mod+S', 'Edit.SurroundWith'], ['Mod+K Mod+X', 'Edit.InsertSnippet'],
  ['Mod+K Mod+K', 'Edit.ToggleBookmark'], ['Mod+K Mod+N', 'Edit.NextBookmark'],
  ['Mod+K Mod+P', 'Edit.PreviousBookmark'], ['Mod+K Mod+L', 'Edit.ClearBookmarks'],
  ['Mod+K Mod+I', 'Edit.QuickInfo'], ['Mod+R Mod+W', 'Edit.ViewWhiteSpace'],
  ['Mod+K Mod+/', 'Edit.ToggleLineComment'],
  ['Mod+M Mod+M', 'Edit.ToggleOutliningExpansion'], ['Mod+M Mod+L', 'Edit.ToggleAllOutlining'],
  ['Mod+M Mod+O', 'Edit.CollapseToDefinitions'], ['Mod+M Mod+P', 'Edit.StopOutlining'],
  ['Mod+M Mod+U', 'Edit.StopHidingCurrent'], ['Mod+M Mod+H', 'Edit.HideSelection'],
  ['Mod+M Mod+S', 'Edit.CollapseCurrentRegion'], ['Mod+M Mod+A', 'Edit.CollapseAllOutlining'],
  ['Mod+M Mod+X', 'Edit.ExpandAllOutlining'], ['Mod+M Mod+E', 'Edit.ExpandCurrentRegion'], ['Mod+M Mod+T', 'Edit.CollapseTag'],
  ['Mod+R Mod+R', 'Refactor.Rename'], ['Mod+R Mod+M', 'Refactor.ExtractMethod'],
  ['Mod+R Mod+G', 'EditorContextMenus.CodeWindow.RemoveAndSort'],
  ['Mod+E Mod+C', 'Edit.CommentSelection'], ['Mod+E Mod+U', 'Edit.UncommentSelection'],
  ['Mod+E Mod+D', 'Edit.FormatDocument'], ['Mod+E Mod+F', 'Edit.FormatSelection'],
  ['Mod+E Mod+W', 'Edit.WordWrap'], ['Mod+E Mod+S', 'Edit.ViewWhiteSpace'],
  ['Mod+J', 'Edit.ListMembers'], ['Mod+Alt+Space', 'Edit.ToggleCompletionMode'], ['Mod+G', 'Edit.GoTo'],
  ['Mod+I', 'Edit.IncrementalSearch'], ['Mod+Shift+I', 'Edit.ReverseIncrementalSearch'],
  ['Mod+Shift+L', 'Edit.LineDelete'], ['Mod+L', 'Edit.LineCut'], ['Mod+D', 'Edit.Duplicate'],
  ['Mod+Enter', 'Edit.LineOpenAbove'], ['Mod+Shift+Enter', 'Edit.LineOpenBelow'],
  ['Mod+]', 'Edit.GoToMatchingBrace'], ['Mod+Shift+]', 'Edit.GoToMatchingBraceExtend'],
  ['Mod+Shift+U', 'Edit.MakeUppercase'], ['Mod+U', 'Edit.MakeLowercase'],
  ['Mod+Shift+ArrowUp', 'Edit.PreviousHighlightedReference'], ['Mod+Shift+ArrowDown', 'Edit.NextHighlightedReference'],
  ['Alt+Shift+ArrowUp', 'Edit.LineUpExtendColumn'], ['Alt+Shift+ArrowDown', 'Edit.LineDownExtendColumn'],
  ['Alt+Shift+ArrowLeft', 'Edit.CharLeftExtendColumn'], ['Alt+Shift+ArrowRight', 'Edit.CharRightExtendColumn'],
  ['Mod+Alt+]', 'Edit.ExpandSelection'], ['Mod+Alt+[', 'Edit.ShrinkSelection'],
  ['Mod+,', 'Edit.NavigateTo'], ['Mod+-', 'View.NavigateBackward'], ['Mod+Shift+-', 'View.NavigateForward'],
  ['Mod+Shift+P', 'View.CommandPalette'], ['Mod+Shift+.', 'View.ZoomIn'], ['Mod+Shift+,', 'View.ZoomOut'],
  ['Alt+Backspace', 'Edit.Undo'], ['Alt+Shift+Backspace', 'Edit.Redo'],
  ['Ctrl+Insert', 'Edit.Copy'], ['Shift+Insert', 'Edit.Paste'], ['Shift+Delete', 'Edit.Cut'],
  ['Shift+Enter', 'Edit.BreakLine'], ['Shift+Backspace', 'Edit.DeleteBackwards'], ['Alt+ArrowRight', 'Edit.CompleteWord'],
  ['Mod+K Mod+\\', 'Edit.DeleteHorizontalWhiteSpace'], ['Alt+Shift+-', 'Edit.ContractSelection'],
  ['Alt+Shift+=', 'Edit.ExpandSelection'], ['Alt+Shift+]', 'Edit.ExpandSelectiontoContainingBlock'],
  ['Mod+Alt+Shift+C', 'Edit.CopyParameterTip'], ['Mod+Alt+Shift+P', 'Edit.PasteParameterTip'],
  ['Alt+,', 'Edit.DecreaseFilterLevel'], ['Alt+.', 'Edit.IncreaseFilterLevel'],
  ['Alt+PageDown', 'Edit.GotoNextIssueinFile'], ['Alt+PageUp', 'Edit.GotoPreviousIssueinFile'],
  ['Alt+Shift+;', 'Edit.InsertCaretsatAllMatching'], ['Alt+Shift+.', 'Edit.InsertNextMatchingCaret'],
  ['Alt+Shift+Home', 'Edit.LineStartExtendColumn'], ['Alt+Shift+End', 'Edit.LineEndExtendColumn'],
  ['Alt+Shift+T', 'Edit.LineTranspose'], ['Mod+Shift+T', 'Edit.WordTranspose'],
  ['Mod+Alt+-', 'Edit.PeekBackward'], ['Mod+Alt+=', 'Edit.PeekForward'],
  ['Mod+ArrowDown', 'Edit.ScrollLineDown'], ['Mod+ArrowUp', 'Edit.ScrollLineUp'],
  ['Mod+=', 'Edit.SelectToLastGoBack'], ['Mod+K Mod+`', 'Edit.ShowCodeLensMenu'], ['Alt+`', 'Edit.ShowNavigateMenu'],
  ['Mod+K Mod+A', 'Edit.SwapAnchor'], ['Mod+K Mod+H', 'Edit.ToggleTaskListShortcut'],
  ['Mod+PageDown', 'Edit.ViewBottom'], ['Mod+Shift+PageDown', 'Edit.ViewBottomExtend'],
  ['Mod+PageUp', 'Edit.ViewTop'], ['Mod+Shift+PageUp', 'Edit.ViewTopExtend'],
  ['Mod+Alt+Shift+ArrowRight', 'Edit.WordNextExtendColumn'], ['Mod+Alt+Shift+ArrowLeft', 'Edit.WordPreviousExtendColumn'],
  ['Alt+Enter', 'EditorContextMenus.CodeWindow.ExecuteInInteractive'], ["Alt+'", 'EditorContextMenus.CodeWindow.ExecuteLineInInteractive']
];

export const visualStudioBindings = Object.freeze([...commonBindings, ...bindingsFromRows('visual-studio', definitions, { priority: 10 })]);
export const visualStudioReference = 'https://learn.microsoft.com/visualstudio/ide/default-keyboard-shortcuts-in-visual-studio';
