import {planSourceUpdate,commitSourceUpdate} from './edit-plan.js';
import {Op} from '@sharpforge/bytecode';
import {CilVirtualMachine,invalidateExecutionCode} from '@sharpforge/runtime';
import {verifyCilAssembly} from '@sharpforge/cil';
import {loadSymbols,bindSources} from '@sharpforge/symbols';
import {SourceBreakpointIndex} from './source-locations.js';
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const source=session=>!!session.vm.image;
const fail=m=>{throw new Error(m);};
function paused(s,frameId){if(s.vm.state!=='paused')fail('Pause execution before changing debugger state');const f=s.frame(frameId);if(f!==s.vm.top)fail('This operation requires the executing (top) frame');if(s.vm.pendingFault||s.vm.fault||f.unwinds?.length||f.pending)fail('Complete the pending exception/finally continuation before changing execution');return f;}
function zones(handlers,pc){return handlers.flatMap((h,i)=>[pc>=h.start&&pc<h.end?'try:'+i:null,pc>=h.target&&pc<(h.handlerEnd??Infinity)?'handler:'+i:null].filter(Boolean));}
function sourceZones(m,pc){return m.handlers.flatMap((h,i)=>{const end=h.kind==='finally'?h.handlerEnd:m.code[h.end*3+1];return [pc>=h.start&&pc<h.end?'try:'+i:null,pc>=h.target&&pc<end?'handler:'+i:null].filter(Boolean);});}
function ensureAssigned(method,start,locals){const queue=[[start,new Set(locals.map((v,i)=>v===undefined?-1:i).filter(i=>i>=0))]],visited=new Map();let budget=0;while(queue.length){if(++budget>100000)fail('Set Next Statement flow analysis exceeded its budget');const [pc,assigned]=queue.pop();if(pc<0||pc>=method.code.length/3)continue;const previous=visited.get(pc);if(previous){const intersection=new Set([...assigned].filter(i=>previous.has(i)));if(intersection.size===previous.size)continue;visited.set(pc,intersection);assigned.clear();for(const i of intersection)assigned.add(i);}else visited.set(pc,new Set(assigned));const [op,a]=method.code.subarray(pc*3,pc*3+3);if(op===Op.LDLOC&&!assigned.has(a))fail(`Target can read unassigned local '${method.locals[a]?.name??a}'`);if(op===Op.STLOC)assigned.add(a);if([Op.RET,Op.THROW,Op.RETHROW,Op.ENDFINALLY].includes(op))continue;if([Op.JUMP,Op.JTRUE,Op.JFALSE].includes(op))queue.push([a,new Set(assigned)]);if(op!==Op.JUMP)queue.push([pc+1,new Set(assigned)]);}}
export function setNextStatement(s,{uri,line,column=1,reference,frameId,expectedInstructions}={}){
  const f=paused(s,frameId),vm=s.vm;if(expectedInstructions!==undefined&&expectedInstructions!==vm.instructions)fail('Debugger stop changed; refresh the target');
  if(source(s)){if(!vm.sourcePause||vm.stack.length!==f.base)fail('Set Next Statement requires an empty-stack source statement boundary');const {point,message}=s.sourceIndex.resolve(uri,{line,column});if(!point)fail(message);if(line<point.line||line>point.endLine)fail('No executable target on the requested line; Set Next Statement does not relocate to another method');if(point.methodId!==f.methodId)fail('Cannot set the next statement in another method');const m=vm.image.methods[f.methodId];if(!same(sourceZones(m,f.pc),sourceZones(m,point.offset)))fail('Cannot cross a try, catch, finally or resource-cleanup boundary');ensureAssigned(m,point.offset,f.locals);s.remember?.(true);f.pc=point.offset;f.point=vm.image.sequencePoints[point.id];vm.currentPoint=f.point;vm.sourcePause=true;s.stoppedBeforeSequence=true;s.skipOnce=null;s.temporaryPoint=null;
  }else{const target=reference?s.location(reference):(()=>{const {point,message}=s.sourceIndex.resolve(uri,{line,column});if(!point)fail(message);if(line<point.line||line>point.endLine)fail('No executable target on the requested line; Set Next Statement does not relocate to another method');return {token:point.methodToken,offset:point.ilOffset};})();if(target.token!==f.method.token)fail('Cannot set the next instruction in another method');if(f.stack.length||!s.stoppedBeforeInstruction)fail('Set Next Statement requires an empty evaluation stack before an instruction');const pc=f.offsets.get(target.offset);if(pc===undefined)fail('Target is not an instruction boundary');const current=f.method.instructions[f.pc].offset;if(!same(zones(f.method.handlers,current),zones(f.method.handlers,target.offset)))fail('Cannot cross an exception-handling boundary');const report=verifyCilAssembly(vm.inspector,{methodToken:f.method.token});if(!report.success)fail('Target method did not pass IL verification');const height=report.stackHeights?.[f.method.token]?.[pc];if(height!==0)fail('Target instruction requires a nonempty or unreachable evaluation stack');if(pc&&/^(constrained\.|tail\.|readonly\.|volatile\.|unaligned\.)$/.test(f.method.instructions[pc-1].name))fail('Cannot enter an instruction prefix group');s.remember?.(true);f.pc=pc;f.lastOffset=target.offset;s.stoppedBeforeInstruction=true;s.skipOnce=null;s.temporary=null;}
  vm.writeRevision++;s.reason={reason:'goto',phase:'before',description:'Set Next Statement moved execution without running skipped statements; local and heap values were not reset'};s.rememberStop?.();return s.state();
}
export function gotoTargets(s,{uri,line,column=1}={}){const f=s.vm.top;if(s.vm.state!=='paused'||!f)return [];return s.sourceIndex.locations(uri,{line,column,endLine:line}).filter(p=>source(s)?p.methodId===f.methodId:p.methodToken===f.method.token).map(p=>({id:p.id,label:`${p.line}:${p.column}`,line:p.line,column:p.column,endLine:p.endLine,endColumn:p.endColumn,uri,reference:p.methodToken?`il:${p.methodToken.toString(16).padStart(8,'0')}:${p.ilOffset.toString(16).padStart(8,'0')}`:undefined}));}
function allFrames(vm){return vm.allFrames?[...vm.allFrames()]:vm.frames;}
export function hotReload(s,input,{expectedVersion=s.codeVersion??0}={}){
  const vm=s.vm;if(!['paused','terminated','waiting'].includes(vm.state))fail('Pause execution before applying code changes');if(expectedVersion!==(s.codeVersion??0))fail('Hot Reload base version changed');if(vm.pendingFault||vm.fault||allFrames(vm).some(f=>f.unwinds?.length||f.pending))fail('Cannot update during an exception/finally continuation');
  let changes=[],nextIndex,newImage,candidate;
  let sourcePlan;
  if(source(s)){
    sourcePlan=planSourceUpdate(vm,input,{ensureAssigned});newImage=sourcePlan.image;changes=sourcePlan.changes;
    nextIndex=new SourceBreakpointIndex(newImage);
  }else{candidate=new CilVirtualMachine(input,{...vm.options,methodToken:vm.entryToken??vm.report.entryPoint,arguments:vm.options.arguments,onOutput:()=>{}});const old=vm.inspector,next=candidate.inspector,layout=i=>({types:i.types.map(t=>({name:t.name,base:t.baseToken,fields:t.fields.map(f=>({token:f.token,name:f.name,type:i.signature(f.token)}))})),methods:[...i.methods.values()].map(m=>({token:m.token,owner:m.owner,name:m.name,signature:i.signature(m.token)}))});if(!same(layout(old),layout(next)))fail('Rude edit: managed type layout or metadata signatures changed');for(const f of allFrames(vm)){const m=next.getMethod(f.method.token),a=f.method;if(!same(a.locals,m.locals)||!same(a.handlers,m.handlers)||!same(a.instructions.map(i=>[i.name,i.size,i.operandKind.startsWith('br')||i.name==='switch'?i.operand:null]),m.instructions.map(i=>[i.name,i.size,i.operandKind.startsWith('br')||i.name==='switch'?i.operand:null])))fail('Rude edit in active IL method: instruction/local/exception layout changed');}changes=[...next.methods.values()].filter(m=>m.hasBody).map(m=>m.owner+'::'+m.name);nextIndex=new SourceBreakpointIndex(next.debug??{});}
  // All validation precedes mutation. Old snapshots are invalid across code generations.
  if(newImage){commitSourceUpdate(vm,sourcePlan);for(const item of sourcePlan.frames)for(const bp of s.dataBreakpoints)if(bp.kind==='local'&&bp.frameId===item.frame.id){if(item.localMap.has(bp.index)){bp.index=item.localMap.get(bp.index);if(bp.dataId)bp.dataId='source-data:'+encodeURIComponent(JSON.stringify({kind:'local',frameId:bp.frameId,index:bp.index}));}else{bp.enabled=false;bp.verified=false;bp.message='Local storage removed by edit and continue';}}}else{vm.inspector=candidate.inspector;vm.report=candidate.report;vm.layoutCache.clear();vm.strings.clear();for(const f of allFrames(vm)){f.method=vm.inspector.getMethod(f.method.token);f.offsets=new Map(f.method.instructions.map((i,n)=>[i.offset,n]));}vm.symbols=null;s.symbols=null;}
  invalidateExecutionCode(vm,'hot-reload');
  s.sourceIndex=nextIndex;s.evaluator?.cache?.clear();s.expressionCache?.clear();s.history=[];s.historyBytes=0;s.historyDropped=0;s.codeVersion=(s.codeVersion??0)+1;vm.writeRevision++;s.skipOnce=null;s.temporary=null;s.temporaryPoint=null;
  const breakpoints=s.breakpoints.filter(b=>b.uri).reduce((a,b)=>{(a[b.uri]??=[]).push({...b,line:b.requestedLine??b.line,column:b.requestedColumn});return a;},{});for(const [uri,bps]of Object.entries(breakpoints))s.setBreakpoints(uri,bps);s.setFunctionBreakpoints(s.functionBreakpoints.map(b=>({...b})));
  s.reason={reason:'hot reload',phase:source(s)?vm.sourcePause?'before':'suspended':s.stoppedBeforeInstruction?'before':'after',description:`Hot Reload generation ${s.codeVersion} applied; heap, statics and active values retained. Reverse history cleared.`};return {applied:true,version:s.codeVersion,changedMethods:changes,summary:sourcePlan?{addedMethods:sourcePlan.addedMethods,addedTypes:sourcePlan.addedTypes,appendedFields:sourcePlan.appendedFields,addedStatics:sourcePlan.addedStatics}:null,state:s.state()};
}
export function loadPortableSymbols(s,pdb,sources={}){if(source(s))fail('Portable PDB loading targets a managed DLL/EXE session');const vm=s.vm;if(vm.state==='running')fail('Pause before replacing symbols');const symbols=loadSymbols(vm.inspector.pe.bytes,pdb),binding=bindSources(symbols,sources);for(const method of symbols.methods){const body=vm.inspector.getMethod(method.token);if(method.points.length){const boundaries=new Set(body.instructions.map(i=>i.offset));if(method.points.some(p=>!boundaries.has(p.offset)))fail('Portable PDB sequence point is not an instruction boundary');}}s.symbols=symbols;s.symbolBinding=binding;const info={...binding,sequencePoints:binding.sequencePoints.map(p=>({...p,methodId:(()=>{const m=vm.inspector.getMethod(p.methodToken);return m.id??=(p.methodToken&0xffffff)-1;})(),offset:p.ilOffset}))};s.sourceIndex=new SourceBreakpointIndex(info);vm.inspector.debug={...(vm.inspector.debug??{}),...info};s.functionOffsets=new Map();for(const p of s.sourceIndex.byId.values())if(!s.functionOffsets.has(p.methodToken)||p.ilOffset<s.functionOffsets.get(p.methodToken))s.functionOffsets.set(p.methodToken,p.ilOffset);const old=s.breakpoints.filter(b=>b.uri);for(const uri of new Set(old.map(b=>b.uri)))s.setBreakpoints(uri,old.filter(b=>b.uri===uri).map(b=>({...b,line:b.requestedLine??b.line,column:b.requestedColumn})));return {id:symbols.idHex,bound:symbols.bound,documents:binding.documents.map(({embedded,hash,...d})=>({...d,hash:[...hash],text:undefined})),methods:symbols.methods.length,stateMachines:symbols.stateMachines};}

export {evaluateFunction,releaseEvaluationHandles} from './evaluation.js';
