import { readFile, readdir, writeFile, stat } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createHash } from 'node:crypto';

const packageRoot = dirname(fileURLToPath(import.meta.url));
const validId = /^[A-Za-z0-9][A-Za-z0-9_.-]{0,199}$/;
const compare = (left, right) => left < right ? -1 : left > right ? 1 : 0;

function checkContribution(module, path, kind) {
  const template = module.template;
  if (!template || typeof template.id !== 'string' || !validId.test(template.id) || typeof template.name !== 'string' || !template.name) {
    throw new Error('Invalid template definition in ' + path);
  }
  if (!Number.isSafeInteger(module.order ?? 10000) || (module.order ?? 10000) < 0) throw new Error('Invalid template order in ' + path);
  const legacy = module.legacyCatalog;
  if (legacy !== undefined && legacy !== kind) throw new Error('Invalid legacy catalog in ' + path);
  const kinds = kind === 'project' ? ['project', 'solution'] : ['item'];
  if (!legacy && (!kinds.includes(template.kind) || typeof template.generate !== 'function')) {
    throw new Error('A template contribution needs its kind and generator in ' + path);
  }
  if (!legacy && (!Array.isArray(template.targets) || !template.targets.length ||
      template.targets.some(target => typeof target !== 'string' || !target.trim()) ||
      new Set(template.targets).size !== template.targets.length)) {
    throw new Error('A template contribution needs explicit qualification targets in ' + path);
  }
  return { path, id: template.id, order: module.order ?? 10000, legacy };
}

/** Index trusted per-template source modules. No nupkg content is imported or executed by this build-only function. */
export async function catalogSource({ directory = packageRoot, maxTemplates = 2048, signal } = {}) {
  if (!Number.isSafeInteger(maxTemplates) || maxTemplates < 1) throw new Error('Invalid template module budget');
  const contributions = [];
  const identities = new Set();
  for (const kind of ['project', 'item']) {
    signal?.throwIfAborted();
    const entries = await readdir(resolve(directory, 'src', kind), { withFileTypes: true });
    entries.sort((left, right) => compare(left.name, right.name));
    for (const entry of entries) {
      if (!entry.name.endsWith('.template.js')) continue;
      const path = './' + kind + '/' + entry.name;
      if (!entry.isFile()) throw new Error('Template modules must be ordinary files: ' + path);
      if (contributions.length === maxTemplates) throw new Error('Template module budget exceeded');
      signal?.throwIfAborted();
      const fullPath = resolve(directory, 'src', kind, entry.name);
      if ((await stat(fullPath)).size > 40 * 1024) throw new Error('Template module exceeds 40 KiB: ' + path);
      const source = await readFile(fullPath);
      if (source.length > 40 * 1024) throw new Error('Template module exceeds 40 KiB: ' + path);
      const digest = createHash('sha256').update(source).digest('hex');
      const module = await import(pathToFileURL(fullPath).href + '?catalog=' + digest);
      signal?.throwIfAborted();
      const contribution = checkContribution(module, path, kind);
      if (identities.has(contribution.id)) throw new Error('Duplicate template identity: ' + contribution.id);
      identities.add(contribution.id);
      contributions.push(contribution);
    }
  }
  contributions.sort((left, right) => left.order - right.order || compare(left.path, right.path));
  const lines = ['// Generated by packages/templates/build-catalog.js. Add one project/item *.template.js source module.'];
  contributions.forEach((item, index) => lines.push('import { template as template' + index + ' } from ' + JSON.stringify(item.path) + ';'));
  for (const [kind, name] of [['project', 'legacyProjectTemplates'], ['item', 'legacyItemTemplates']]) {
    lines.push('', 'export const ' + name + ' = Object.freeze([');
    contributions.forEach((item, index) => { if (item.legacy === kind) lines.push('  template' + index + ','); });
    lines.push(']);');
  }
  lines.push('', 'export const builtInTemplates = Object.freeze([');
  contributions.forEach((item, index) => lines.push(item.legacy ?
    '  Object.freeze({ ...template' + index + ', kind: ' + JSON.stringify(item.legacy) + ', targets: ["browser-managed"] }),' :
    '  template' + index + ','));
  lines.push(']);', '');
  return lines.join('\n');
}

/** Build-contribution entry point; its returned index is written into the static distribution before import rewriting. */
export async function generate({ root, signal }) {
  return catalogSource({ directory: resolve(root, 'packages/templates'), signal });
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const code = await catalogSource();
  const target = resolve(packageRoot, 'src/catalog.generated.js');
  if (process.argv[2] === '--write') {
    await writeFile(target, code);
    console.log('Updated packages/templates/src/catalog.generated.js');
  } else if (process.argv[2] === '--check') {
    if (await readFile(target, 'utf8') !== code) throw new Error('Template catalog is stale; run node packages/templates/build-catalog.js --write');
  } else process.stdout.write(code);
}
