import {AnimationClock,easing,propertiesFor,frameworkAssignable,XAML,MEDIA} from '@sharpforge/framework';
const A=MEDIA+'Animation.';
/** App-local animation driver. The clock stores IDs, never DOM nodes or user functions. */
export function createAnimationSystem({objects,styles,send,value,host,options}){
 const w=host.document.defaultView;let frame=0,last=0,disposed=false;
 const resolve=id=>{const o=objects.get(id);if(!o)throw new Error('Animation target was disposed');return o;};
 const clock=new AnimationClock({key:id=>id,read:(id,k)=>resolve(id).$values[k]??(['$Left','$Top'].includes(k)?0:null),validate:(id,k)=>{const o=resolve(id);if(['$Left','$Top'].includes(k)){if(!frameworkAssignable(XAML+'UIElement',o.$node.type))throw new TypeError('Attached target requires UIElement');return;}const p=propertiesFor(o.$node.type)[k];if(!p||p.type!=='double'||p.readOnly)throw new TypeError('DoubleAnimation requires a writable double property');},write:(id,k,v)=>{const o=resolve(id);if(k==='Opacity')v=Math.max(0,Math.min(1,v));if(/^(Width|Height|MinWidth|MinHeight|MaxWidth|MaxHeight|FontSize|ItemWidth|ItemHeight)$/.test(k))v=Math.max(0,v);o.$values[k]=v;send({op:'set',id,property:k.replace(/^\$/,''),value:v});styles.bindings(o);},completed:id=>{const o=objects.get(id);if(o)for(const fn of [...(o.$events.Completed??[])]){try{fn(o,{OriginalSource:o,Handled:false});}catch(e){options.onError?.(e);}}}});
 function definition(o,seen=new Set(),depth=0){if(!o?.$node||o.$context!==objects||depth>16||seen.size>=512||seen.has(o))throw new TypeError('Invalid timeline, duplicate child, cycle or size limit');seen.add(o);const duration=o.Duration,repeat=o.RepeatBehavior,d={id:o.$node.id,ref:o.$node.id,begin:o.BeginTime?.TotalMilliseconds??0,duration:duration?.kind==='forever'?Infinity:duration?.TimeSpan?.TotalMilliseconds??null,repeat:repeat?.Count??1,repeatDuration:repeat?.Duration?.TotalMilliseconds,forever:repeat?.kind==='forever',speed:o.SpeedRatio,autoReverse:o.AutoReverse,fill:o.FillBehavior};
  if(o.$node.type===A+'Storyboard'){d.children=[...o.Children].map(c=>definition(c,seen,depth+1));if(!d.children.length&&d.duration===null)d.duration=0;}
  else if(o.$node.type===A+'DoubleAnimation'){let target=o.$target,property=o.$targetProperty;if(!target){const matches=[...objects.values()].filter(n=>n.$values.Name===o.$targetName);if(matches.length!==1)throw new TypeError('Animation target name is missing or ambiguous');target=matches[0];}if(target.$context!==objects)throw new TypeError('Animation target belongs to another app');if(typeof property!=='string'||property.length>250)throw new TypeError('Set a target property');property=property.replace(/[()]/g,'');if(property.includes('RenderTransform.')){target=target.RenderTransform;property=property.split('.').at(-1);if(!target)throw new TypeError('RenderTransform is null');}else if(/^(?:(?:Microsoft\.UI\.Xaml\.Controls\.)?Canvas\.)?(Left|Top)$/.test(property)&&property.includes('.'))property='$'+property.split('.').at(-1);else if(property.includes('.'))throw new TypeError('Unsupported target property path');d.target=target.$node.id;d.property=property;for(const name of ['From','To','By'])if(o[name]!==null)d[name.toLowerCase()]=o[name];d.easing=easeData(o.EasingFunction);}
  else throw new TypeError('Unsupported timeline');return d;
 }
 const easeData=o=>o?{kind:o.$node.type.split('.').at(-1),mode:o.EasingMode,power:o.Power??2,amplitude:o.Amplitude??1}:{kind:'Linear'};
 const request=fn=>(w.requestAnimationFrame??(cb=>w.setTimeout(()=>cb(w.performance.now()),16))).call(w,fn);
 function schedule(){if(disposed||frame||options.animationManual||!clock.running)return;last=w.performance.now();frame=request(tick);}
 function tick(now){frame=0;if(disposed)return;try{clock.advance(Math.max(0,now-last));}catch(e){clock.clear();options.onError?.(e);}last=now;if(clock.running)frame=request(tick);}
 function invoke(o,c,args){if(c.kind==='animationTarget'||c.kind==='animationTargetGet'){const t=args[0];if(t?.$context!==objects)throw new TypeError('Timeline belongs to another app');const key='$target'+(c.property==='Target'?'':c.property.slice(6));if(c.kind==='animationTargetGet')return {handled:true,value:t[key]??null};const v=args[1];if(c.property==='Target'&&v!==null&&v?.$context!==objects)throw new TypeError('Cross-app target');if(c.property!=='Target'&&(typeof v!=='string'||v.length>250))throw new TypeError('Invalid animation target name/property');t[key]=v;return {handled:true};}
  if(c.owner===A+'EasingFunctionBase'&&c.name==='Ease')return {handled:true,value:easing(args[0],easeData(o))};
  if(c.owner!==A+'Storyboard'||c.isStatic)return {handled:false};const id=o.$node.id;
  switch(c.name){case 'Begin':clock.begin(id,definition(o));break;case 'Pause':clock.pause(id);break;case 'Resume':clock.resume(id);break;case 'Stop':clock.stop(id);break;case 'Seek':case 'SeekAlignedToLastTick':if(args[0]?.valueType!=='System.TimeSpan')throw new TypeError('TimeSpan required');clock.seek(id,args[0].TotalMilliseconds);break;case 'SkipToFill':clock.skipToFill(id);break;case 'GetCurrentState':return {handled:true,value:clock.state(id).state};case 'GetCurrentTime':return {handled:true,value:Object.freeze({valueType:'System.TimeSpan',TotalMilliseconds:clock.state(id).currentTime,TotalSeconds:clock.state(id).currentTime/1000})};default:return {handled:false};}schedule();return {handled:true};
 }
 return {clock,invoke,advance(ms){clock.advance(ms);host.flush();schedule();return clock.running;},setBase(o,k,v){return clock.setBase(o.$node.id,k,v);},getBase(o,k){return clock.getBase(o.$node.id,k);},dispose(){disposed=true;if(frame)(w.cancelAnimationFrame??w.clearTimeout).call(w,frame);clock.clear();}};
}
