import {frameworkType,frameworkAssignable,canonicalType,propertiesFor,XAML,CONTROLS} from '@sharpforge/framework';
/** Instance-local style/property/template engine for the JavaScript facade. No eval or global state. */
export function createStyleSystem({objects,classes,send,host,value,animations=()=>null}){
 const registered=new Map(),unset=Object.freeze({kind:'UnsetValue'});let updating=0;
 const dp=(owner,name)=>{const k=owner+'::'+name;if(!registered.has(k))registered.set(k,Object.freeze({kind:'DependencyProperty',owner,Name:name}));return registered.get(k);};
 const descriptor=(o,p)=>{if(p?.kind!=='DependencyProperty'||registered.get(p.owner+'::'+p.Name)!==p||!propertiesFor(o.$node.type)[p.Name])throw new TypeError('A registered dependency property for this control is required');return p.Name;};
 function validate(o,key,v){const p=propertiesFor(o.$node.type)[key];if(!p||p.readOnly)throw new TypeError('Unknown or read-only property '+key);const def=frameworkType(p.type);
  if(p.type==='string'&&v!==null&&typeof v!=='string'||p.type==='bool'&&typeof v!=='boolean'||p.type==='int'&&(!Number.isInteger(v)||v< -2147483648||v>2147483647)||p.type==='double'&&(typeof v!=='number'||!Number.isFinite(v)&&!(['Width','Height','ItemWidth','ItemHeight'].includes(key)&&Number.isNaN(v))))throw new TypeError('Invalid '+p.type+' property '+key);
  if(def?.kind==='enum'&&!Object.values(def.values).includes(v))throw new RangeError('Invalid enumeration '+key);
  if(def&&def.kind!=='enum'&&v!==null&&!(p.type===XAML+'DependencyProperty'&&v.kind==='DependencyProperty')&&!frameworkAssignable(p.type,v?.$node?.type??v?.valueType))throw new TypeError('Property '+key+' requires '+p.type);
  if(['Width','Height','MinWidth','MinHeight','MaxWidth','MaxHeight','FontSize','Spacing','RowSpacing','ColumnSpacing'].includes(key)&&v<0||key==='Opacity'&&(v<0||v>1))throw new RangeError('Property range '+key);
 }
 function styleValues(o,style,seen=new Set()){if(!style)return {};if(style.$context!==objects||style.$node.type!==XAML+'Style'||seen.has(style)||seen.size>64)throw new TypeError('Invalid Style/BasedOn chain');seen.add(style);if(style.TargetTypeName&&!frameworkAssignable(canonicalType(style.TargetTypeName),o.$node.type))throw new TypeError('Style target mismatch');const result=styleValues(o,style.BasedOn,seen);for(const setter of style.Setters){const name=descriptor(o,setter.Property);validate(o,name,setter.Value);result[name]=setter.Value;}return result;}
 function emit(o,k,v){if(animations()?.setBase(o,k,v))return;o.$values[k]=v;send({op:'set',id:o.$node.id,property:k,value:value(v)});}
 function templateValue(o,key){if(!o.$templateOwner)return {found:false};if(Object.hasOwn(o.$bindings??{},key))return {found:true,value:o.$templateOwner.$values[o.$bindings[key]]};return Object.hasOwn(o.$templateValues??{},key)?{found:true,value:o.$templateValues[key]}:{found:false};}
 function refresh(){if(updating)return;updating++;try{const plans=[];for(const o of objects.values())if(propertiesFor(o.$node.type).Style){const values=styleValues(o,o.$values.Style);plans.push([o,values]);}for(const [o,values]of plans){for(const key of new Set([...(o.$styleKeys??[]),...Object.keys(values)]))if(!o.$locals.has(key)){const template=templateValue(o,key);emit(o,key,template.found?template.value:Object.hasOwn(values,key)?values[key]:propertiesFor(o.$node.type)[key].value??null);}o.$styleKeys=Object.keys(values);applyTemplate(o);bindings(o);}}finally{updating--;}}
 function bindings(owner){if(!owner.$templateRoot)return;const queue=[owner.$templateRoot],seen=new Set();while(queue.length){const o=queue.pop();if(!o?.$node||seen.has(o))continue;seen.add(o);for(const [to,from]of Object.entries(o.$bindings??{}))if(!o.$locals.has(to))emit(o,to,owner.$values[from]);for(const v of Object.values(o.$values))if(v?.$node&&frameworkAssignable(XAML+'UIElement',v.$node.type))queue.push(v);for(const c of Object.values(o.$collections))queue.push(...c);}}
 function scene(){return {version:1,windows:[...host.windows],nodes:[...objects.values()].map(o=>({id:o.$node.id,type:o.$node.type,properties:Object.fromEntries(Object.entries(o.$values).map(([k,v])=>[k,value(v)])),events:Object.entries(o.$events).filter(([,a])=>a.length).map(([k])=>k),collections:Object.fromEntries(Object.entries(o.$collections).map(([k,c])=>[k,[...c].map(value)])),templateRoot:o.$templateRoot?.$node.id,templateOwner:o.$templateOwner?.$node.id,templateBindings:Object.fromEntries(Object.entries(o.$bindings??{}).filter(([k])=>!o.$locals.has(k))),drawing:o.$drawing??[]}))};}
 function validateTemplate(owner,t){if(!t)return;if(t.$node?.type!==CONTROLS+'ControlTemplate'||t.$context!==objects||t.TargetTypeName&&!frameworkAssignable(canonicalType(t.TargetTypeName),owner.$node.type))throw new TypeError('Invalid template target');const seen=new Set(),names=new Set(),walk=o=>{if(!o?.$node||o.$context!==objects||!frameworkAssignable(XAML+'UIElement',o.$node.type))throw new TypeError('Template parts must be UI elements');if(seen.has(o)||seen.size>=500)throw new TypeError('Template visual cycle/size');seen.add(o);if(o.Name&&names.has(o.Name))throw new TypeError('Duplicate template names');if(o.Name)names.add(o.Name);for(const [to,from]of Object.entries(o.$bindings??{})){const target=propertiesFor(o.$node.type)[to],source=propertiesFor(owner.$node.type)[from];if(!source||!target||target.readOnly||target.type!==source.type&&target.type!=='object')throw new TypeError('Incompatible template property binding');}for(const [k,v]of Object.entries(o.$values))if(['Child','Content'].includes(k)&&v?.$node)walk(v);for(const list of Object.values(o.$collections))for(const child of list)if(child?.$node&&frameworkAssignable(XAML+'UIElement',child.$node.type))walk(child);};walk(t.VisualTree);}
 function applyTemplate(owner){if(!propertiesFor(owner.$node.type).Template)return false;const t=owner.$values.Template;if(t&&owner.$appliedTemplate===t&&owner.$templateRoot)return true;if(!t){if(owner.$templateRoot){owner.$templateRoot=null;owner.$appliedTemplate=null;send({op:'reset',snapshot:scene()});}return false;}validateTemplate(owner,t);const cloned=new Map(),clone=o=>{if(!o?.$node)return o;if(!frameworkAssignable(XAML+'UIElement',o.$node.type)&&frameworkType(o.$node.type)?.kind!=='value')return o;if(cloned.has(o))return cloned.get(o);const next=new (classes.get(o.$node.type))();cloned.set(o,next);next.$values={...o.$values};next.$locals=new Set();next.$templateValues=Object.fromEntries([...o.$locals].map(k=>[k,o.$values[k]]));next.$bindings={...(o.$bindings??{})};next.$templateOwner=owner;for(const[k,v]of Object.entries(o.$values))if(['Content','Child'].includes(k)&&v?.$node)next.$values[k]=clone(v);for(const[k,items]of Object.entries(o.$collections))for(const child of items)next[k].Add(clone(child));return next;};owner.$templateRoot=clone(t.VisualTree);owner.$appliedTemplate=t;bindings(owner);send({op:'reset',snapshot:scene()});return true;}
 function set(o,k,v){validate(o,k,v);if(k==='Template')validateTemplate(o,v);const previous=o.$values[k],local=o.$locals.has(k);if(animations()?.setBase(o,k,v)){o.$locals.add(k);return;}o.$values[k]=v;o.$locals.add(k);try{if(k==='Style'||['style','setter'].includes(frameworkType(o.$node.type).kind))refresh();if(k==='Template')applyTemplate(o);bindings(o);}catch(e){o.$values[k]=previous;if(!local)o.$locals.delete(k);refresh();throw e;}}
 function clear(o,p){const key=descriptor(o,p),definition=propertiesFor(o.$node.type)[key];if(definition.readOnly)throw new TypeError('Read-only dependency property');const values=styleValues(o,o.$values.Style);o.$locals.delete(key);const template=templateValue(o,key);emit(o,key,template.found?template.value:Object.hasOwn(values,key)?values[key]:definition.value??null);if(key==='Style')refresh();if(key==='Template')applyTemplate(o);bindings(o);}
 function invoke(o,name,args){if(name==='GetValue')return {handled:true,value:o.$values[descriptor(o,args[0])]};if(name==='ReadLocalValue'){const k=descriptor(o,args[0]);return {handled:true,value:o.$locals.has(k)?(animations()?.getBase(o,k)??o.$values[k]):unset};}if(name==='ClearValue'){clear(o,args[0]);return {handled:true};}if(name==='SetValue'){o[descriptor(o,args[0])]=args[1];return {handled:true};}if(name==='ApplyTemplate')return {handled:true,value:applyTemplate(o)};
  if(name==='GetTemplateChild'){const queue=[o.$templateRoot],seen=new Set();while(queue.length){const n=queue.pop();if(!n?.$node||seen.has(n))continue;seen.add(n);if(n.Name===args[0])return {handled:true,value:n};for(const v of Object.values(n.$values))if(v?.$node)queue.push(v);for(const c of Object.values(n.$collections))queue.push(...c);}return {handled:true,value:null};}
  if(o.$node?.type===CONTROLS+'ControlTemplate'&&name==='Bind'){const [part,to,property]=args;if(part?.$context!==objects||!propertiesFor(part.$node.type)[to]||property?.kind!=='DependencyProperty')throw new TypeError('Invalid template binding');part.$bindings={...part.$bindings,[to]:property.Name};return {handled:true};}return {handled:false};}
 return {dp,unset,set,clear,invoke,refresh,bindings,scene,validate};
}
