import {readFile,writeFile,readdir,mkdir,lstat} from 'node:fs/promises';
import {resolve,dirname,relative,isAbsolute} from 'node:path';
import {createProjectPlan,projectTemplates,itemTemplates,searchTemplates,validateFilePlan} from '../../packages/templates/src/index.js';
import {exportWorkspaceZip,importWorkspaceZip,importWorkspaceRecords,workspaceManifestRecord} from '../../packages/project-system/src/index.js';
import {decodeWorkspaceFile,encodeWorkspaceFile} from '../../packages/archive/src/index.js';
/** Explicit, create-only CLI IO. ZIPs are validated completely before extraction begins. */
export async function writePlan(directory,{records,folders=[]}){
 validateFilePlan({records,folders});records=records.map(r=>({...r,bytes:encodeWorkspaceFile(r)}));
 const root=resolve(directory),paths=[...records.map(r=>r.path),...folders];
 async function absent(path){try{await lstat(path);throw new Error('Destination already exists: '+path);}catch(e){if(e.code!=='ENOENT')throw e;}}
 // Existing root allowed only when entirely empty; reject symlink roots and ancestors.
 let current=root;while(current!==dirname(current)){try{if((await lstat(current)).isSymbolicLink())throw new Error('Destination contains a symbolic link');}catch(e){if(e.code!=='ENOENT')throw e;}current=dirname(current);}
 try{if((await readdir(root)).length)throw new Error('Choose a new or empty output directory');}catch(e){if(e.code!=='ENOENT')throw e;}
 for(const path of paths){const target=resolve(root,path);const rel=relative(root,target);if(!rel||isAbsolute(rel)||rel==='..'||rel.startsWith('../')||rel.startsWith('..\\'))throw new Error('Escaping output path');await absent(target);}
 await mkdir(root,{recursive:true});const written=[];try{for(const path of folders)await mkdir(resolve(root,path),{recursive:true});for(const record of records){const target=resolve(root,record.path);await mkdir(dirname(target),{recursive:true});await writeFile(target,encodeWorkspaceFile(record),{flag:'wx'});written.push(record.path);}}catch(e){e.message+='; completed files: '+written.join(', ');e.written=written;throw e;}return written;
}
async function readTree(root){root=resolve(root);if((await lstat(root)).isSymbolicLink())throw new Error('Workspace root is a symlink');const records=[],folders=[],skipped=[];let bytes=0;async function visit(path,depth=0){if(depth>48)throw new Error('Folder depth limit exceeded');for(const name of (await readdir(path)).sort()){const full=resolve(path,name),rel=relative(root,full).replaceAll('\\','/'),st=await lstat(full);if(st.isSymbolicLink())throw new Error('ZIP export does not follow symlinks: '+rel);if(st.isDirectory()){if(['.git','node_modules','.vs','.sharpforge'].includes(name)){if(name==='.sharpforge'){try{const m=resolve(full,'workspace.json'),ms=await lstat(m);if(ms.isSymbolicLink()||!ms.isFile()||ms.size>4*1024*1024)throw new Error('Invalid settings manifest');const bytes=new Uint8Array(await readFile(m));records.push(decodeWorkspaceFile(rel+'/workspace.json',bytes));}catch(e){if(e.code!=='ENOENT')throw e;}}else skipped.push(rel);continue;}folders.push(rel);await visit(full,depth+1);}else if(st.isFile()){if(records.length>=20000||st.size>64*1024*1024||(bytes+=st.size)>128*1024*1024)throw new Error('Workspace exceeds archive limits');records.push(decodeWorkspaceFile(rel,new Uint8Array(await readFile(full))));}}}await visit(root);return {...importWorkspaceRecords(records,folders),skipped};}
export async function runWorkspaceCLI(command,args){args=[...args];const option=(key,fallback)=>{const i=args.indexOf(key);if(i<0)return fallback;if(!args[i+1]||args[i+1].startsWith('--'))throw new Error('Missing value for '+key);return args.splice(i,2)[1];},flag=key=>{const i=args.indexOf(key);if(i<0)return false;args.splice(i,1);return true;};
 if(command==='templates'){const kind=flag('--items')?'item':'project',query=option('--search','');if(args.length)throw new Error('Unknown template option');for(const t of searchTemplates({kind,query}))console.log(t.id.padEnd(27)+' '+t.name+' — '+t.description);return;}
 if(command==='new'){const name=option('--name','Application'),solution=option('--solution',name),namespace=option('--namespace',undefined),framework=option('--framework','net10.0'),output=option('-o',option('--output',name)),sameDirectory=flag('--same-directory'),noSolution=flag('--no-solution'),checked=flag('--checked'),zip=flag('--zip');if(args.length!==1)throw new Error('Use new TEMPLATE --name NAME -o DIRECTORY [--zip]');const plan=createProjectPlan(args[0],{projectName:name,solutionName:solution,...(namespace?{namespace}:{}),framework,sameDirectory,solutionMode:noSolution?'none':'new',checked});if(zip){await writeFile(output,exportWorkspaceZip({records:plan.records,folders:plan.folders,settings:{name:plan.name,entry:plan.entry,startup:plan.startup}}),{flag:'wx'});console.log('Created '+output);}else{const files=await writePlan(output,plan);console.log('Created '+files.length+' files in '+resolve(output));}for(const w of plan.warnings)console.error(w);return;}
 if(command==='zip'){const output=option('-o','workspace.zip');if(args.length!==1)throw new Error('Use zip DIRECTORY -o OUTPUT.zip');const snapshot=await readTree(args[0]);const outputRelative=relative(resolve(args[0]),resolve(output));if(outputRelative&&!isAbsolute(outputRelative)&&outputRelative!=='..'&&!outputRelative.startsWith('../')&&!outputRelative.startsWith('..\\'))throw new Error('Choose an output ZIP outside the source tree');await writeFile(output,exportWorkspaceZip(snapshot),{flag:'wx'});console.log('Saved '+snapshot.records.length+' files to '+output);if(snapshot.skipped.length)console.error('Excluded administrative directories: '+snapshot.skipped.join(', '));return;}
 if(command==='unzip'){const output=option('-o','Workspace');if(args.length!==1)throw new Error('Use unzip FILE.zip -o NEW_DIRECTORY');const input=new Uint8Array(await readFile(args[0]));const plan=importWorkspaceZip(input);await writePlan(output,{...plan,records:plan.manifest?[...plan.records,workspaceManifestRecord(plan.settings,plan.records)]:plan.records});console.log('Extracted '+plan.records.length+' files without overwriting existing files.');return;}
 throw new Error('Unknown workspace command');
}
