import {undoSourceEditor} from '../designer-editor-history.js';
import {storage,storageKeys} from '../settings/storage.js';
export function registerStudioCommands(registry,context){
const {EDITOR_KEYMAPS,toolDefinitions}=context;
const metadata=[['designer','WinUI visual designer',''],...toolDefinitions.map(t=>['tool:'+t.id,'View: '+t.title,'']),['nativeMSBuild','Native MSBuild workspace',''],['nativeBuildLayout','Native build layout',''],['nativeEvaluate','Evaluate native project',''],['nativeCancel','Cancel native operation',''],['navigateBack','Navigate back','Alt+Left'],['navigateForward','Navigate forward','Alt+Right'],['openFolder','Open folder from disk',''],['openAssemblyFile','Open DLL / EXE in decompiler',''],['saveDisk','Save changed source files to disk','Ctrl+Alt+S'],['exportCsproj','Export .csproj',''],['exportSlnx','Export .slnx',''],['projectProperties','Project properties and loading diagnostics',''],['callHierarchy','Call hierarchy','Shift+Alt+H'],['findFiles','Find in files','Ctrl+Shift+F'],['outline','Document outline',''],['windowLayouts','Window layouts',''],['resetLayout','Reset window layout',''],['debug','Start / Continue debugging','F5'],['run','Run without debugging','Ctrl+F5'],['build','Build solution','Ctrl+Shift+B'],['next','Step over','F10'],['stepIn','Step into','F11'],['stepOut','Step out','Shift+F11'],['runToCursor','Run to cursor','Ctrl+F10'],['stepBack','Step back','Alt+F10'],['reverseContinue','Reverse continue (recorded history)',''],['stop','Stop debugging','Shift+F5'],['pause','Break all','F6'],['new','New C# file',''],['open','Open project or source files',''],['save','Export project','Ctrl+S'],['assemblyExport','Export .NET IL assembly (.dll)',''],['ilExport','Export IL inspection listing',''],['bytecodeExport','Export legacy VM IR',''],['examples','Load an example',''],['heap','Inspect managed heap',''],['collect','Collect managed garbage',''],['problems','Open Error List',''],['debugPanel','Open Locals & Watch',''],['stack','Open Call Stack',''],['breakpoints','Open Breakpoints',''],['disassembly','Open Disassembly',''],['theme','Toggle dark / light theme',''],['architecture','View modular architecture',''],['profile','View compatibility profile',''],['shortcuts','Keyboard shortcuts',''],['about','About SharpForge Studio','']];
metadata.push(['setNext','Set Next Statement','Ctrl+Shift+F10'],['hotReload','Hot Reload',''],['threads','Threads (managed contexts)',''],['parallelStacks','Parallel Stacks',''],['symbols','Portable PDB Symbols',''],['winui','WinUI Application','']);
metadata.push(['showNext','Show Next Statement',''],['newFunctionBreakpoint','New Function Breakpoint',''],['debugSettings','Debugger and Exception Settings',''],['immediate','Immediate — safe evaluation',''],['muteBreakpoints','Toggle All Breakpoints','']);
metadata.push(['settings','Environment: Keyboard profile',''],...EDITOR_KEYMAPS.map(k=>['keymap:'+k.id,'Keyboard: '+k.label,'']),['toggleBreakpoint','Debug: Toggle Breakpoint','F9'],['removeBreakpoints','Debug: Remove All Breakpoints','Ctrl+Shift+F9']);
const handlers=new Map();
for(const id of ["designer"])handlers.set(id,()=>context.designerTools.open());
for(const id of ["setNext"])handlers.set(id,async(command)=>{const {advancedTools}=context;await advancedTools.setNext();return;});
for(const id of ["hotReload"])handlers.set(id,async(command)=>{const {setPanel}=context;setPanel('hot-reload');return;});
for(const id of ["threads"])handlers.set(id,async(command)=>{const {setPanel}=context;setPanel('threads');return;});
for(const id of ["parallelStacks"])handlers.set(id,async(command)=>{const {setPanel}=context;setPanel('parallel-stacks');return;});
for(const id of ["symbols"])handlers.set(id,async(command)=>{const {advancedTools,setPanel}=context;setPanel('symbols');await advancedTools.inspectSymbols();return;});
for(const id of ["winui"])handlers.set(id,async(command)=>{const {setPanel}=context;setPanel('winui');return;});
for(const id of ["showNext"])handlers.set(id,async(command)=>{const {showNextStatement}=context;showNextStatement();return;});
for(const id of ["newFunctionBreakpoint"])handlers.set(id,async(command)=>{const {debugTools}=context;await debugTools.addFunction();return;});
for(const id of ["muteBreakpoints"])handlers.set(id,async(command)=>{const {debugTools,state}=context;await debugTools.configure({breakpointsEnabled:!state.debugSettings.breakpointsEnabled});return;});
for(const id of ["debugSettings"])handlers.set(id,async(command)=>{const {setPanel}=context;setPanel('debug-session');return;});
for(const id of ["immediate"])handlers.set(id,async(command)=>{const {setPanel}=context;setPanel('immediate');return;});
for(const id of ["nativeBuildLayout"])handlers.set(id,async(command)=>{const {docking,setPanel}=context;docking.reset('build');setPanel('msbuild');return;});
for(const id of ["nativeBuild"])handlers.set(id,async(command)=>{const {nativeBuild,setPanel}=context;setPanel('msbuild');await nativeBuild.run('build');return;});
for(const id of ["nativeMSBuild"])handlers.set(id,async(command)=>{const {setPanel}=context;setPanel('msbuild');return;});
for(const id of ["nativeEvaluate"])handlers.set(id,async(command)=>{const {nativeBuild,setPanel}=context;setPanel('msbuild');await nativeBuild.run('evaluate');return;});
for(const id of ["nativeCancel"])handlers.set(id,async(command)=>{const {nativeBuild}=context;await nativeBuild.cancel();return;});
for(const id of ["navigateBack"])handlers.set(id,async(command)=>{const {navigate}=context;navigate('back');return;});
for(const id of ["navigateForward"])handlers.set(id,async(command)=>{const {navigate}=context;navigate('forward');return;});
for(const id of ["openFolder"])handlers.set(id,async(command)=>{const {openFolder}=context;await openFolder();return;});
for(const id of ["openAssemblyFile"])handlers.set(id,async(command)=>{const {$,setPanel}=context;setPanel('assembly');$('#assembly-file-input').click();return;});
for(const id of ["saveDisk"])handlers.set(id,async(command)=>{const {saveToDisk}=context;await saveToDisk();return;});
for(const id of ["exportCsproj"])handlers.set(id,async(command)=>{const {createCsproj,download,state}=context;download(state.name+'.csproj',createCsproj({assemblyName:state.name,files:state.files.map(f=>f.uri)}),'application/xml');return;});
for(const id of ["exportSlnx"])handlers.set(id,async(command)=>{const {createSlnx,download,state}=context;download(state.name+'.slnx',createSlnx([state.name+'.csproj']),'application/xml');return;});
for(const id of ["projectProperties"])handlers.set(id,async(command)=>{const {setPanel}=context;setPanel('project');return;});
for(const id of ["findFiles"])handlers.set(id,async(command)=>{const {setPanel}=context;setPanel('search');return;});
for(const id of ["outline"])handlers.set(id,async(command)=>{const {setPanel}=context;setPanel('outline');return;});
for(const id of ["windowLayouts"])handlers.set(id,async(command)=>{const {setPanel}=context;setPanel('layouts');return;});
for(const id of ["resetLayout"])handlers.set(id,async(command)=>{const {docking}=context;docking.reset();return;});
for(const id of ["debugLayout"])handlers.set(id,async(command)=>{const {docking}=context;docking.reset('debug');return;});
for(const id of ["winuiLayout"])handlers.set(id,async(command)=>{const {docking}=context;docking.reset('winui');return;});
for(const id of ["decompileLayout"])handlers.set(id,async(command)=>{const {docking,renderPanel}=context;docking.reset('decompile');renderPanel('assembly');return;});
for(const id of ["undoLayout"])handlers.set(id,async(command)=>{const {docking}=context;docking.layout.undo();return;});
for(const id of ["redoLayout"])handlers.set(id,async(command)=>{const {docking}=context;docking.layout.redo();return;});
for(const id of ["assemblyExplorer"])handlers.set(id,async(command)=>{const {openAssemblyExplorer}=context;await openAssemblyExplorer();return;});
for(const id of ["codeActions"])handlers.set(id,async(command)=>{const {codeActions}=context;await codeActions();return;});
for(const id of ["format"])handlers.set(id,async(command)=>{const {languageRequest,state}=context;await languageRequest('format',{uri:state.active});return;});
for(const id of ["extensions"])handlers.set(id,async(command)=>{const {setPanel}=context;setPanel('extensions');return;});
for(const id of ["generatedSources"])handlers.set(id,async(command)=>{const {setPanel}=context;setPanel('generated');return;});
for(const id of ["debug"])handlers.set(id,async(command)=>{const {launch}=context;await launch(true);return;});
for(const id of ["run"])handlers.set(id,async(command)=>{const {launch}=context;await launch(false);return;});
for(const id of ["build"])handlers.set(id,async(command)=>{const {build}=context;await build();return;});
for(const id of ["pause"])handlers.set(id,async(command)=>{const {runtime,state}=context;if(['running','waiting'].includes(state.debug?.state))await runtime.request('pause');return;});
for(const id of ["stop"])handlers.set(id,async(command)=>{const {runtime,state}=context;state.launchEpoch++;await runtime.request('stop',{sessionId:undefined});return;});
for(const id of ["restart"])handlers.set(id,async(command)=>{const {ilDebugger,launch,runtime,setPanel,state,stopQuietly}=context;{const previous=state.lastManagedLaunch;await stopQuietly();if(previous){state.programOutput='';state.frameId=null;ilDebugger.reset();await runtime.request('launch',{...previous,debug:true});setPanel('disassembly');}else await launch(true);return;}});
for(const id of ["runToCursor"])handlers.set(id,async(command)=>{const {runToCursor,state}=context;if(state.debug?.profile==='managed-il')throw new Error('Use Run to on an MSIL instruction');await runToCursor();return;});
for(const id of ["next","stepIn","stepOut","stepBack","reverseContinue"])handlers.set(id,async(command)=>{const {step}=context;await step(command);return;});
for(const id of ["replace"])handlers.set(id,async(command)=>{const {editor}=context;editor.openFind(true);return;});
for(const id of ["goToLine"])handlers.set(id,async(command)=>{const {editor}=context;editor.gotoBox.classList.remove('hidden');editor.gotoBox.querySelector('input').focus();return;});
for(const id of ["save"])handlers.set(id,async(command)=>{const {editorHostCommand}=context;await editorHostCommand('save');return;});
for(const id of ["exportProject"])handlers.set(id,async(command)=>{const {exportProject}=context;await exportProject();return;});
for(const id of ["exportLegacyProject"])handlers.set(id,async(command)=>{const {exportLegacyProject}=context;exportLegacyProject();return;});
for(const id of ["newProject"])handlers.set(id,async(command)=>{const {openProjectWizard}=context;await openProjectWizard();return;});
for(const id of ["saveFolder"])handlers.set(id,async(command)=>{const {saveWorkspaceFolder}=context;await saveWorkspaceFolder();return;});
for(const id of ["openZip"])handlers.set(id,async(command)=>{const {$}=context;$('#zip-input').click();return;});
for(const id of ["open"])handlers.set(id,async(command)=>{const {$}=context;$('#file-input').click();return;});
for(const id of ["new"])handlers.set(id,async(command)=>{const {newFile}=context;await newFile();return;});
for(const id of ["assemblyExport"])handlers.set(id,async(command)=>{const {build,download,state,toast}=context;{const r=await build();if(r?.success){download(state.name+'.dll',r.assembly,'application/octet-stream');toast('ECMA-335 PE/CLI assembly exported. Use the File menu to export its .NET runtime configuration.');}return;}});
for(const id of ["runtimeConfigExport"])handlers.set(id,async(command)=>{const {createRuntimeConfig,download,state}=context;download(state.name+'.runtimeconfig.json',JSON.stringify(createRuntimeConfig(),null,2));return;});
for(const id of ["ilExport"])handlers.set(id,async(command)=>{const {build,download,formatAssembly,state}=context;{const r=await build();if(r?.success)download(state.name+'.il.txt',formatAssembly(r.assembly),'text/plain');return;}});
for(const id of ["bytecodeExport"])handlers.set(id,async(command)=>{const {build,download,serializeImage,state,toast}=context;{const r=await build();if(r?.success){download(state.name+'.sfb.json',serializeImage(r.image));toast('Verified managed bytecode image exported.');}return;}});
for(const id of ["examples"])handlers.set(id,async(command)=>{const {setPanel}=context;setPanel('examples');return;});
for(const id of ["about"])handlers.set(id,async(command)=>{const {aboutDialog}=context;aboutDialog();return;});
for(const id of ["shortcuts"])handlers.set(id,async(command)=>{const {shortcutsDialog}=context;shortcutsDialog();return;});
for(const id of ["profile"])handlers.set(id,async(command)=>{const {profileDialog}=context;profileDialog();return;});
for(const id of ["architecture"])handlers.set(id,async(command)=>{const {architectureDialog}=context;architectureDialog();return;});
for(const id of ["commands"])handlers.set(id,async(command)=>{const {commandsDialog}=context;commandsDialog();return;});
for(const id of ["theme"])handlers.set(id,async(command)=>{const {saveLocal}=context;document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';saveLocal();return;});
for(const id of ["output"])handlers.set(id,async(command)=>{const {setPanel}=context;setPanel('output');return;});
for(const id of ["problems"])handlers.set(id,async(command)=>{const {setPanel}=context;setPanel('problems');return;});
for(const id of ["debugPanel"])handlers.set(id,async(command)=>{const {setPanel}=context;setPanel('debug');return;});
for(const id of ["stack"])handlers.set(id,async(command)=>{const {setPanel}=context;setPanel('stack');return;});
for(const id of ["breakpoints"])handlers.set(id,async(command)=>{const {setPanel}=context;setPanel('breakpoints');return;});
for(const id of ["disassembly"])handlers.set(id,async(command)=>{const {setPanel,state}=context;setPanel(state.debug?.profile==='managed-il'?'disassembly':'bytecode');return;});
for(const id of ["clearOutput"])handlers.set(id,async(command)=>{const {renderPanel,state}=context;state.logs=[];state.programOutput='';renderPanel('output');return;});
for(const id of ["callHierarchy"])handlers.set(id,async(command)=>{const {editor,showCallHierarchy,state}=context;await showCallHierarchy({uri:state.active,offset:editor?.offset??0});return;});
for(const id of ["heap"])handlers.set(id,async(command)=>{const {inspectHeap}=context;await inspectHeap();return;});
for(const id of ["collect"])handlers.set(id,async(command)=>{const {formatBytes,runtime,state,toast}=context;if(state.debug){const stats=await runtime.request('collect');toast(`Collection reclaimed ${stats.freedThisCollection} objects (${formatBytes(stats.bytesThisCollection)}).`);}else toast('Run a program before collecting managed memory.');return;});
for(const id of ["undo"])handlers.set(id,async()=>undoSourceEditor(context));
for(const id of ["redo"])handlers.set(id,async()=>undoSourceEditor(context,true));
for(const id of ["find"])handlers.set(id,async(command)=>{const {editor}=context;editor.findBox.classList.remove('hidden');editor.findBox.querySelector('input').focus();return;});
for(const id of ["definition","references","rename"])handlers.set(id,async(command)=>{const {editor,languageRequest,state}=context;await languageRequest(command,{uri:state.active,offset:editor.offset});return;});
for(const id of ["toggleExplorer"])handlers.set(id,async(command)=>{const {toggleTool}=context;toggleTool('solution');return;});
for(const id of ["toggleTools"])handlers.set(id,async(command)=>{const {toggleTool}=context;toggleTool('diagnostics');return;});
for(const id of ["recoverPrevious"])handlers.set(id,async(command)=>{const {importFiles,toast}=context;{const project=storage.getItem(storageKeys.previous);if(!project){toast('There is no previous project in recovery.');return;}await importFiles([new File([project],'recovered.json',{type:'application/json'})]);return;}});
handlers.set('settings',()=>context.setPanel('settings'));handlers.set('toggleBreakpoint',()=>{const {editor,state,toggleBreakpoint}=context;if(editor)toggleBreakpoint(state.active,editor.sourceSnapshot().positionAt(editor.offset).line+1);});handlers.set('removeBreakpoints',()=>context.debugTools.clear());for(const tool of context.toolDefinitions)handlers.set('tool:'+tool.id,()=>context.setPanel(tool.id));for(const keymap of context.EDITOR_KEYMAPS)handlers.set('keymap:'+keymap.id,()=>context.setEditorKeymap(keymap.id));
const titles=new Map(metadata.map(row=>[row[0],row]));
for(const [id,title,shortcut]of metadata)registry.registerCommand(id,title,shortcut??'',handlers.get(id));
for(const [id,handler]of handlers)if(!titles.has(id))registry.registerCommand(id,id,'',handler,{visible:false});
return metadata;
}
