/** Deterministic, data-only timeline sampling shared by managed and JavaScript hosts. */
const finite=(n,name,min=0,max=1e12)=>{if(typeof n!=='number'||!Number.isFinite(n)||n<min||n>max)throw new RangeError(`Invalid ${name}`);return n;};
export function easing(progress,{kind='Linear',mode=0,power=2,amplitude=1}={}){const t=Math.min(1,Math.max(0,progress));let f;switch(kind){case 'QuadraticEase':f=x=>x*x;break;case 'CubicEase':f=x=>x*x*x;break;case 'QuarticEase':f=x=>x**4;break;case 'QuinticEase':f=x=>x**5;break;case 'PowerEase':finite(power,'easing power',0,100);f=x=>x**power;break;case 'SineEase':f=x=>1-Math.cos(x*Math.PI/2);break;case 'CircleEase':f=x=>1-Math.sqrt(Math.max(0,1-x*x));break;case 'BackEase':finite(amplitude,'easing amplitude',0,100);f=x=>x*x*((amplitude+1)*x-amplitude);break;case 'Linear':return t;default:throw new TypeError('Unsupported easing function '+kind);}if(![0,1,2].includes(mode))throw new RangeError('Invalid easing mode');if(t===0||t===1)return t;if(mode===1)return f(t);if(mode===0)return 1-f(1-t);if(mode===2)return t<.5?f(t*2)/2:1-f((1-t)*2)/2;throw new RangeError('Invalid easing mode');}
export function prepareTimeline(def,read,validate,{maxNodes=512,maxDepth=16}={}){let count=0;const visiting=new Set();const prepare=(d,depth)=>{if(!d||depth>maxDepth||++count>maxNodes)throw new RangeError('Timeline size/depth limit exceeded');if(visiting.has(d.id))throw new TypeError('Timeline cycle or duplicate child');visiting.add(d.id);const children=(d.children??[]).map(c=>prepare(c,depth+1)),begin=finite(d.begin??0,'BeginTime'),speed=finite(d.speed??1,'SpeedRatio',Number.MIN_VALUE,1000),autoReverse=!!d.autoReverse,repeat=finite(d.repeat??1,'repeat count',0,1e6),fill=d.fill??0;if(![0,1].includes(fill))throw new RangeError('Invalid FillBehavior');let duration=d.duration??(children.length?Math.max(0,...children.map(c=>c.end)):1000);if(duration!==Infinity)finite(duration,'Duration');const cycle=duration*(autoReverse?2:1),active=d.forever?Infinity:d.repeatDuration!==undefined?finite(d.repeatDuration,'repeat duration'):(repeat===0?0:cycle*repeat);
 const plan={id:d.id,ref:d.ref,children,begin,speed,autoReverse,repeat,fill,duration,active,end:begin+active/speed};
 if(d.target!==undefined){validate(d.target,d.property);const base=read(d.target,d.property);const from=d.from??base,to=d.to??(d.by!==undefined?from+d.by:base);finite(from,'From',-1e12,1e12);finite(to,'To',-1e12,1e12);if(d.by!==undefined)finite(d.by,'By',-1e12,1e12);if(duration===Infinity)throw new TypeError('DoubleAnimation requires a finite simple duration');plan.target=d.target;plan.property=d.property;plan.from=from;plan.to=to;plan.easing=d.easing??{kind:'Linear'};easing(.5,plan.easing);}
 return plan;};return prepare(def,0);}
export function timelinePosition(plan,time){const elapsed=(time-plan.begin)*plan.speed;if(elapsed<0)return {contributes:false,complete:false,local:0,progress:0,state:2};const complete=elapsed>=plan.active;if(complete&&plan.fill===1)return {contributes:false,complete:true,local:0,progress:0,state:2};if(plan.active===0)return {contributes:plan.fill===0,complete:true,local:0,progress:1,state:plan.fill===0?1:2};const at=complete?plan.active:elapsed;if(plan.duration===Infinity)return {contributes:true,complete,local:at,progress:0,state:complete?1:0};const cycle=plan.duration*(plan.autoReverse?2:1);let local=cycle===0?plan.duration:at%cycle;if(complete&&at>0&&local===0)local=cycle;if(plan.autoReverse&&local>plan.duration)local=2*plan.duration-local;return {contributes:true,complete,local,progress:plan.duration===0?1:local/plan.duration,state:complete?1:0};}
const walk=(p,visit)=>{visit(p);p.children.forEach(c=>walk(c,visit));};
/** Adapter read/write must not run user callbacks. Completed callbacks run after the update. */
export class AnimationClock {
 constructor(adapter){this.adapter=adapter;this.states=new Map();this.bases=new Map();this.serial=0;this.applying=false;}
 key(target,property){return this.adapter.key(target)+'|'+property;}
 get running(){return [...this.states.values()].some(s=>!s.paused&&s.time<s.plan.end);}
 getBase(target,property){return this.bases.get(this.key(target,property))?.value??this.adapter.read(target,property);}
 setBase(target,property,value){if(this.applying)return false;const base=this.bases.get(this.key(target,property));if(!base)return false;base.value=value;this.apply();return true;}
 begin(id,definition){const plan=prepareTimeline(definition,(t,p)=>this.adapter.read(t,p),this.adapter.validate);if(!this.states.has(id)&&this.states.size>=128)throw new RangeError('Active storyboard limit exceeded');const needed=[];walk(plan,n=>{if(n.target!==undefined){const key=this.key(n.target,n.property);if(!this.bases.has(key))needed.push([key,{target:n.target,property:n.property,value:this.adapter.read(n.target,n.property)}]);}});for(const [key,b]of needed)this.bases.set(key,b);this.states.set(id,{plan,time:0,paused:false,status:0,serial:++this.serial,completed:[]});this.apply();return this.states.get(id);}
 pause(id){const s=this.states.get(id);if(s)s.paused=true;}
 resume(id){const s=this.states.get(id);if(s)s.paused=false;}
 stop(id){if(this.states.delete(id))this.apply();}
 seek(id,time){finite(time,'seek time');const s=this.states.get(id);if(!s)throw new Error('Begin the storyboard before seeking');s.time=time;this.apply();}
 skipToFill(id){const s=this.states.get(id);if(!s)return;if(s.plan.end===Infinity)throw new Error('A repeating-forever storyboard cannot skip to fill');s.time=s.plan.end;this.apply();}
 advance(delta){finite(delta,'animation delta',0,1e12);for(const s of this.states.values())if(!s.paused&&s.time<s.plan.end)s.time+=delta;this.apply();}
 apply(){if(this.applying)return;this.applying=true;const values=new Map(),used=new Set(),events=[];try{for(const s of [...this.states.values()].sort((a,b)=>a.serial-b.serial)){const sample=(n,time,inherited=true)=>{const p=timelinePosition(n,time),active=inherited&&p.contributes;if(n===s.plan)s.status=p.state;if(inherited&&p.complete&&!s.completed.includes(n.id)){s.completed.push(n.id);events.push(n.ref??n.id);}if(n.target!==undefined){const key=this.key(n.target,n.property);used.add(key);if(active)values.set(key,n.from+(n.to-n.from)*easing(p.progress,n.easing));}for(const child of n.children)sample(child,p.local,active);};sample(s.plan,s.time);}
   for(const [key,b]of this.bases){const value=values.has(key)?values.get(key):b.value;if(!Object.is(this.adapter.read(b.target,b.property),value))this.adapter.write(b.target,b.property,value);if(!used.has(key))this.bases.delete(key);}
 }finally{this.applying=false;}for(const event of events)this.adapter.completed?.(event);}
 state(id){const s=this.states.get(id);return s?{time:s.time,currentTime:timelinePosition(s.plan,s.time).local,state:s.status,paused:s.paused}: {time:0,currentTime:0,state:2,paused:false};}
 snapshot(){return structuredClone({states:[...this.states],bases:[...this.bases],serial:this.serial});}
 restore(snapshot){this.states=new Map(structuredClone(snapshot?.states??[]));this.bases=new Map(structuredClone(snapshot?.bases??[]));this.serial=Math.max(this.serial,snapshot?.serial??0);}
 *roots(){for(const s of this.states.values()){const refs=[];walk(s.plan,n=>{if(n.ref)refs.push(n.ref);if(n.target)refs.push(n.target);});yield* refs;}for(const b of this.bases.values())yield b.target;}
 clear(){this.states.clear();this.apply();}
}
